#pragma TextEncoding     = "UTF-8"
#pragma rtGlobals        = 3 // Use modern global access method and strict wave access.
#pragma rtFunctionErrors = 1
#pragma ModuleName       = BasicIncludes

#include "UTF_HelperFunctions"

// keep sorted
#include "UTF_Amplifier"
#include "UTF_AnalysisBrowserTest"
#include "UTF_AnalysisFunctionHelpers"
#include "UTF_AnalysisFunctionParameters"
#include "UTF_AnalysisFunctionPrototypes"
#include "UTF_AsynFrameworkTest"
#include "UTF_Cache"
#include "UTF_Configuration"
#include "UTF_DAEphyswoHardware"
#include "UTF_Debugging"
#include "UTF_EpochswoHardware"
#include "UTF_ForeignFunctionInterface"
#include "UTF_GuiUtilities"
#include "UTF_JSONWaveNotes"
#include "UTF_Labnotebook"
#include "UTF_Macros"
#include "UTF_oodDAQ"
#include "UTF_PGCSetAndActivateControl"
#include "UTF_StimsetAPI"
#include "UTF_SweepFormula"
#include "UTF_SweepFormula_Operations"
#include "UTF_SweepFormula_PSX"
#include "UTF_Testpulse"
#include "UTF_ThreadsafeDataSharing"
#include "UTF_TraceUserData"
#include "UTF_UpgradeDataFolderLocation"
#include "UTF_UpgradeWaveLocationAndGetIt"
#include "UTF_Utils_Algorithm"
#include "UTF_Utils_Checks"
#include "UTF_Utils_Conversions"
#include "UTF_Utils_DataFolder"
#include "UTF_Utils_File"
#include "UTF_Utils_GUI"
#include "UTF_Utils_List"
#include "UTF_Utils_Mies_Algorithm"
#include "UTF_Utils_Mies_BackupWaves"
#include "UTF_Utils_Mies_Config"
#include "UTF_Utils_Mies_Logging"
#include "UTF_Utils_Mies_Sweep"
#include "UTF_Utils_Numeric"
#include "UTF_Utils_ProgramFlow"
#include "UTF_Utils_Strings"
#include "UTF_Utils_Settings"
#include "UTF_Utils_System"
#include "UTF_Utils_Time"
#include "UTF_Utils_WaveHandling"
#include "UTF_UtilsChecks"
#include "UTF_WaveAveraging"
#include "UTF_WaveBuilder"
#include "UTF_WaveBuilderRegression"
#include "UTF_WaveVersioning"
#include "UTF_XOPsCompilation"
#include "UTF_ZeroMQPublishing"

// include examples here so that these are compile tested as well
#include "example-stimulus-set-api"
