[lint]
noreturn-func=FATAL_ERROR|SFH_FATAL_ERROR|FAIL
files = "Packages/Conversion/MIES_MassExperimentProcessing.ipf"
files = "Packages/MIES/DR_MIES_TangoInteract.ipf"
files = "Packages/MIES/MIES_AcceleratedModifyGraph.ipf"
files = "Packages/MIES/MIES_AcquisitionStateHandling.ipf"
files = "Packages/MIES/MIES_AmplifierInteraction.ipf"
files = "Packages/MIES/MIES_AnalysisBrowser.ipf"
files = "Packages/MIES/MIES_AnalysisBrowser_Macro.ipf"
files = "Packages/MIES/MIES_AnalysisBrowser_SweepBrowser.ipf"
files = "Packages/MIES/MIES_AnalysisBrowser_SweepBrowser_Export.ipf"
files = "Packages/MIES/MIES_AnalysisBrowser_SweepBrowser_Export_Macro.ipf"
files = "Packages/MIES/MIES_AnalysisFunctionHelpers.ipf"
files = "Packages/MIES/MIES_AnalysisFunctionManagement.ipf"
files = "Packages/MIES/MIES_AnalysisFunctionPrototypes.ipf"
files = "Packages/MIES/MIES_AnalysisFunctions.ipf"
files = "Packages/MIES/MIES_AnalysisFunctions_Dashboard.ipf"
files = "Packages/MIES/MIES_AnalysisFunctions_MultiPatchSeq.ipf"
files = "Packages/MIES/MIES_AnalysisFunctions_MultiPatchSeq_SpikeControl.ipf"
files = "Packages/MIES/MIES_AnalysisFunctions_PatchSeq.ipf"
files = "Packages/MIES/MIES_ArtefactRemoval.ipf"
files = "Packages/MIES/MIES_Async.ipf"
files = "Packages/MIES/MIES_AsynchronousData.ipf"
files = "Packages/MIES/MIES_BackgroundWatchdog.ipf"
files = "Packages/MIES/MIES_Blowout.ipf"
files = "Packages/MIES/MIES_BrowserSettingsPanel.ipf"
files = "Packages/MIES/MIES_Browser_Plotter.ipf"
files = "Packages/MIES/MIES_Cache.ipf"
files = "Packages/MIES/MIES_CheckInstallation.ipf"
files = "Packages/MIES/MIES_Configuration.ipf"
files = "Packages/MIES/MIES_Constants.ipf"
files = "Packages/MIES/MIES_ConversionConstants.ipf"
files = "Packages/MIES/MIES_DAC-Hardware.ipf"
files = "Packages/MIES/MIES_DAEphys.ipf"
files = "Packages/MIES/MIES_DAEphys_GuiState.ipf"
files = "Packages/MIES/MIES_DAEphys_Macro.ipf"
files = "Packages/MIES/MIES_DANDI.ipf"
files = "Packages/MIES/MIES_DataAcquisition.ipf"
files = "Packages/MIES/MIES_DataAcquisition_Multi.ipf"
files = "Packages/MIES/MIES_DataAcquisition_Single.ipf"
files = "Packages/MIES/MIES_DataBrowser.ipf"
files = "Packages/MIES/MIES_DataBrowser_Macro.ipf"
files = "Packages/MIES/MIES_DataConfiguratonRecreation.ipf"
files = "Packages/MIES/MIES_DataConfigurator.ipf"
files = "Packages/MIES/MIES_DebugPanel.ipf"
files = "Packages/MIES/MIES_DebugPanel_Macro.ipf"
files = "Packages/MIES/MIES_Debugging.ipf"
files = "Packages/MIES/MIES_Downsample.ipf"
files = "Packages/MIES/MIES_EnhancedWMRoutines.ipf"
files = "Packages/MIES/MIES_Epochs.ipf"
files = "Packages/MIES/MIES_ExperimentDocumentation.ipf"
files = "Packages/MIES/MIES_ForeignFunctionInterface.ipf"
files = "Packages/MIES/MIES_GlobalStringAndVariableAccess.ipf"
files = "Packages/MIES/MIES_GuiPopupMenuExt.ipf"
files = "Packages/MIES/MIES_GuiUtilities.ipf"
files = "Packages/MIES/MIES_HDF5Ops.ipf"
files = "Packages/MIES/MIES_IVSCC.ipf"
files = "Packages/MIES/MIES_IVSCC_Macro.ipf"
files = "Packages/MIES/MIES_IgorHooks.ipf"
files = "Packages/MIES/MIES_Indexing.ipf"
files = "Packages/MIES/MIES_InputDialog.ipf"
files = "Packages/MIES/MIES_InputDialog_Macro.ipf"
files = "Packages/MIES/MIES_JSONWaveNotes.ipf"
files = "Packages/MIES/MIES_Labnotebook.ipf"
files = "Packages/MIES/MIES_LogbookViewer.ipf"
files = "Packages/MIES/MIES_Logging.ipf"
files = "Packages/MIES/MIES_Menu.ipf"
files = "Packages/MIES/MIES_MiesUtilities_Algorithm.ipf"
files = "Packages/MIES/MIES_MiesUtilities_BackupWaves.ipf"
files = "Packages/MIES/MIES_MiesUtilities_Channels.ipf"
files = "Packages/MIES/MIES_MiesUtilities_Checks.ipf"
files = "Packages/MIES/MIES_MiesUtilities_Config.ipf"
files = "Packages/MIES/MIES_MiesUtilities_Conversion.ipf"
files = "Packages/MIES/MIES_MiesUtilities_DataManagement.ipf"
files = "Packages/MIES/MIES_MiesUtilities_Device.ipf"
files = "Packages/MIES/MIES_MiesUtilities_GUI.ipf"
files = "Packages/MIES/MIES_MiesUtilities_Getter.ipf"
files = "Packages/MIES/MIES_MiesUtilities_Logbook.ipf"
files = "Packages/MIES/MIES_MiesUtilities_Logging.ipf"
files = "Packages/MIES/MIES_MiesUtilities_Recreation.ipf"
files = "Packages/MIES/MIES_MiesUtilities_Settings.ipf"
files = "Packages/MIES/MIES_MiesUtilities_Sweep.ipf"
files = "Packages/MIES/MIES_MiesUtilities_System.ipf"
files = "Packages/MIES/MIES_MiesUtilities_Uploads.ipf"
files = "Packages/MIES/MIES_MiesUtilities_ZeroMQ.ipf"
files = "Packages/MIES/MIES_NeuroDataWithoutBorders.ipf"
files = "Packages/MIES/MIES_OptimzedOverlapDistributedAcquisition.ipf"
files = "Packages/MIES/MIES_Oscilloscope.ipf"
files = "Packages/MIES/MIES_OverlaySweeps.ipf"
files = "Packages/MIES/MIES_PackageSettings.ipf"
files = "Packages/MIES/MIES_Pictures.ipf"
files = "Packages/MIES/MIES_PressureControl.ipf"
files = "Packages/MIES/MIES_ProgrammaticGUIControl.ipf"
files = "Packages/MIES/MIES_Publish.ipf"
files = "Packages/MIES/MIES_PulseAveraging.ipf"
files = "Packages/MIES/MIES_RepeatedAcquisition.ipf"
files = "Packages/MIES/MIES_SamplingInterval.ipf"
files = "Packages/MIES/MIES_StimsetAPI.ipf"
files = "Packages/MIES/MIES_Structures.ipf"
files = "Packages/MIES/MIES_SweepFormula.ipf"
files = "Packages/MIES/MIES_SweepFormula_Executor.ipf"
files = "Packages/MIES/MIES_SweepFormula_Helpers.ipf"
files = "Packages/MIES/MIES_SweepFormula_Operations.ipf"
files = "Packages/MIES/MIES_SweepFormula_Operations_Select.ipf"
files = "Packages/MIES/MIES_SweepFormula_Operations_TP.ipf"
files = "Packages/MIES/MIES_SweepFormula_PSX.ipf"
files = "Packages/MIES/MIES_SweepFormula_PSX_Macro.ipf"
files = "Packages/MIES/MIES_SweepFormula_Parser.ipf"
files = "Packages/MIES/MIES_SweepSaving.ipf"
files = "Packages/MIES/MIES_TangoInteract.ipf"
files = "Packages/MIES/MIES_TestPulse.ipf"
files = "Packages/MIES/MIES_TestPulse_Multi.ipf"
files = "Packages/MIES/MIES_TestPulse_Single.ipf"
files = "Packages/MIES/MIES_ThreadedFIFOHandling.ipf"
files = "Packages/MIES/MIES_ThreadsafeDataSharing.ipf"
files = "Packages/MIES/MIES_ThreadsafeUtilities.ipf"
files = "Packages/MIES/MIES_TraceUserData.ipf"
files = "Packages/MIES/MIES_Utilities_Algorithm.ipf"
files = "Packages/MIES/MIES_Utilities_Checks.ipf"
files = "Packages/MIES/MIES_Utilities_Conversions.ipf"
files = "Packages/MIES/MIES_Utilities_DataFolder.ipf"
files = "Packages/MIES/MIES_Utilities_Debugger.ipf"
files = "Packages/MIES/MIES_Utilities_File.ipf"
files = "Packages/MIES/MIES_Utilities_GUI.ipf"
files = "Packages/MIES/MIES_Utilities_Generators.ipf"
files = "Packages/MIES/MIES_Utilities_JSON.ipf"
files = "Packages/MIES/MIES_Utilities_List.ipf"
files = "Packages/MIES/MIES_Utilities_Numeric.ipf"
files = "Packages/MIES/MIES_Utilities_ProgramFlow.ipf"
files = "Packages/MIES/MIES_Utilities_SFHCheckers.ipf"
files = "Packages/MIES/MIES_Utilities_Strings.ipf"
files = "Packages/MIES/MIES_Utilities_System.ipf"
files = "Packages/MIES/MIES_Utilities_Time.ipf"
files = "Packages/MIES/MIES_Utilities_WaveHandling.ipf"
files = "Packages/MIES/MIES_WaveBuilder.ipf"
files = "Packages/MIES/MIES_WaveBuilderPanel.ipf"
files = "Packages/MIES/MIES_WaveBuilder_Macro.ipf"
files = "Packages/MIES/MIES_WaveDataFolderGetters.ipf"
files = "Packages/MIES/MIES_WaverefBrowser.ipf"
files = "Packages/MIES/MIES_WaverefBrowser_Macro.ipf"
files = "Packages/MIES_Include.ipf"
files = "Packages/doc/ipf/MIES_Regenerate-Screenshots.ipf"
files = "Packages/doc/ipf/example-stimulus-set-api.ipf"
files = "Packages/tests/Basic/UTF_Amplifier.ipf"
files = "Packages/tests/Basic/UTF_AnalysisBrowserTest.ipf"
files = "Packages/tests/Basic/UTF_AnalysisFunctionHelpers.ipf"
files = "Packages/tests/Basic/UTF_AnalysisFunctionParameters.ipf"
files = "Packages/tests/Basic/UTF_AnalysisFunctionPrototypes.ipf"
files = "Packages/tests/Basic/UTF_AsynFrameworkTest.ipf"
files = "Packages/tests/Basic/UTF_Basic.ipf"
files = "Packages/tests/Basic/UTF_Basic_Includes.ipf"
files = "Packages/tests/Basic/UTF_Cache.ipf"
files = "Packages/tests/Basic/UTF_Configuration.ipf"
files = "Packages/tests/Basic/UTF_DAEphyswoHardware.ipf"
files = "Packages/tests/Basic/UTF_Debugging.ipf"
files = "Packages/tests/Basic/UTF_Downsample.ipf"
files = "Packages/tests/Basic/UTF_EpochswoHardware.ipf"
files = "Packages/tests/Basic/UTF_ForeignFunctionInterface.ipf"
files = "Packages/tests/Basic/UTF_GuiUtilities.ipf"
files = "Packages/tests/Basic/UTF_JSONWaveNotes.ipf"
files = "Packages/tests/Basic/UTF_Labnotebook.ipf"
files = "Packages/tests/Basic/UTF_Macros.ipf"
files = "Packages/tests/Basic/UTF_PGCSetAndActivateControl.ipf"
files = "Packages/tests/Basic/UTF_PackageSettings.ipf"
files = "Packages/tests/Basic/UTF_StimsetAPI.ipf"
files = "Packages/tests/Basic/UTF_SweepFormula.ipf"
files = "Packages/tests/Basic/UTF_SweepFormula_Operations.ipf"
files = "Packages/tests/Basic/UTF_SweepFormula_PSX.ipf"
files = "Packages/tests/Basic/UTF_Testpulse.ipf"
files = "Packages/tests/Basic/UTF_ThreadsafeDataSharing.ipf"
files = "Packages/tests/Basic/UTF_TraceUserData.ipf"
files = "Packages/tests/Basic/UTF_UpgradeDataFolderLocation.ipf"
files = "Packages/tests/Basic/UTF_UpgradeWaveLocationAndGetIt.ipf"
files = "Packages/tests/Basic/UTF_UtilsChecks.ipf"
files = "Packages/tests/Basic/UTF_Utils_Algorithm.ipf"
files = "Packages/tests/Basic/UTF_Utils_Checks.ipf"
files = "Packages/tests/Basic/UTF_Utils_Conversions.ipf"
files = "Packages/tests/Basic/UTF_Utils_DataFolder.ipf"
files = "Packages/tests/Basic/UTF_Utils_File.ipf"
files = "Packages/tests/Basic/UTF_Utils_GUI.ipf"
files = "Packages/tests/Basic/UTF_Utils_List.ipf"
files = "Packages/tests/Basic/UTF_Utils_Mies_Algorithm.ipf"
files = "Packages/tests/Basic/UTF_Utils_Mies_BackupWaves.ipf"
files = "Packages/tests/Basic/UTF_Utils_Mies_Config.ipf"
files = "Packages/tests/Basic/UTF_Utils_Mies_Logging.ipf"
files = "Packages/tests/Basic/UTF_Utils_Mies_Sweep.ipf"
files = "Packages/tests/Basic/UTF_Utils_Numeric.ipf"
files = "Packages/tests/Basic/UTF_Utils_ProgramFlow.ipf"
files = "Packages/tests/Basic/UTF_Utils_Settings.ipf"
files = "Packages/tests/Basic/UTF_Utils_Strings.ipf"
files = "Packages/tests/Basic/UTF_Utils_System.ipf"
files = "Packages/tests/Basic/UTF_Utils_Time.ipf"
files = "Packages/tests/Basic/UTF_Utils_WaveHandling.ipf"
files = "Packages/tests/Basic/UTF_WaveAveraging.ipf"
files = "Packages/tests/Basic/UTF_WaveBuilder.ipf"
files = "Packages/tests/Basic/UTF_WaveBuilderRegression.ipf"
files = "Packages/tests/Basic/UTF_WaveVersioning.ipf"
files = "Packages/tests/Basic/UTF_XOPsCompilation.ipf"
files = "Packages/tests/Basic/UTF_ZeroMQPublishing.ipf"
files = "Packages/tests/Basic/UTF_oodDAQ.ipf"
files = "Packages/tests/Compilation/CompilationTester.ipf"
files = "Packages/tests/HardwareAnalysisFunctions/UTF_HardwareAnalysisFunctions.ipf"
files = "Packages/tests/HardwareAnalysisFunctions/UTF_HardwareAnalysisFunctions_Includes.ipf"
files = "Packages/tests/HardwareAnalysisFunctions/UTF_MultiPatchSeqDaScale.ipf"
files = "Packages/tests/HardwareAnalysisFunctions/UTF_MultiPatchSeqFastRheoEstimate.ipf"
files = "Packages/tests/HardwareAnalysisFunctions/UTF_MultiPatchSeqSpikeControl.ipf"
files = "Packages/tests/HardwareAnalysisFunctions/UTF_PatchSeqAccessResistanceSmoke.ipf"
files = "Packages/tests/HardwareAnalysisFunctions/UTF_PatchSeqChirp.ipf"
files = "Packages/tests/HardwareAnalysisFunctions/UTF_PatchSeqDAScale_Adapt.ipf"
files = "Packages/tests/HardwareAnalysisFunctions/UTF_PatchSeqDAScale_Sub.ipf"
files = "Packages/tests/HardwareAnalysisFunctions/UTF_PatchSeqDAScale_Supra.ipf"
files = "Packages/tests/HardwareAnalysisFunctions/UTF_PatchSeqPipetteInBath.ipf"
files = "Packages/tests/HardwareAnalysisFunctions/UTF_PatchSeqRamp.ipf"
files = "Packages/tests/HardwareAnalysisFunctions/UTF_PatchSeqRheobase.ipf"
files = "Packages/tests/HardwareAnalysisFunctions/UTF_PatchSeqSealEvaluation.ipf"
files = "Packages/tests/HardwareAnalysisFunctions/UTF_PatchSeqSquarePulse.ipf"
files = "Packages/tests/HardwareAnalysisFunctions/UTF_PatchSeqTrueRestingMembranePotential.ipf"
files = "Packages/tests/HardwareAnalysisFunctions/UTF_ReachTargetVoltage.ipf"
files = "Packages/tests/HardwareAnalysisFunctions/UTF_SetControls.ipf"
files = "Packages/tests/HardwareBasic/UTF_AnalysisFunctionManagement.ipf"
files = "Packages/tests/HardwareBasic/UTF_AutoTestpulse.ipf"
files = "Packages/tests/HardwareBasic/UTF_BasicHardwareTests.ipf"
files = "Packages/tests/HardwareBasic/UTF_ConfigurationHardware.ipf"
files = "Packages/tests/HardwareBasic/UTF_DAEphys.ipf"
files = "Packages/tests/HardwareBasic/UTF_Dashboard.ipf"
files = "Packages/tests/HardwareBasic/UTF_Databrowser.ipf"
files = "Packages/tests/HardwareBasic/UTF_Epochs.ipf"
files = "Packages/tests/HardwareBasic/UTF_HardwareBasic.ipf"
files = "Packages/tests/HardwareBasic/UTF_HardwareBasic_Includes.ipf"
files = "Packages/tests/HardwareBasic/UTF_HardwareTestsWithBUG.ipf"
files = "Packages/tests/HardwareBasic/UTF_SweepFormulaHardware.ipf"
files = "Packages/tests/HardwareBasic/UTF_SweepSkipping.ipf"
files = "Packages/tests/HardwareBasic/UTF_TestPulseAndTPDuringDAQ.ipf"
files = "Packages/tests/HardwareBasic/UTF_TrackSweepCounts.ipf"
files = "Packages/tests/HardwareBasic/UTF_VeryBasicHardwareTests.ipf"
files = "Packages/tests/HardwareBasic/UTF_VeryLastTestsuite.ipf"
files = "Packages/tests/HistoricData/UTF_AttemptNWB2ExportOnOldData.ipf"
files = "Packages/tests/HistoricData/UTF_EpochRecreation.ipf"
files = "Packages/tests/HistoricData/UTF_HistoricAnalysisBrowser.ipf"
files = "Packages/tests/HistoricData/UTF_HistoricDashboard.ipf"
files = "Packages/tests/HistoricData/UTF_HistoricData.ipf"
files = "Packages/tests/HistoricData/UTF_HistoricDataHelpers.ipf"
files = "Packages/tests/HistoricData/UTF_HistoricData_Includes.ipf"
files = "Packages/tests/HistoricData/UTF_HistoricEpochClipping.ipf"
files = "Packages/tests/HistoricData/UTF_HistoricSweepBrowser.ipf"
files = "Packages/tests/HistoricData/UTF_HistoricSweepUpgrade.ipf"
files = "Packages/tests/PAPlot/UTF_PAPlot.ipf"
files = "Packages/tests/PAPlot/UTF_PAPlot_Includes.ipf"
files = "Packages/tests/PAPlot/UTF_PA_Tests.ipf"
files = "Packages/tests/UTF_All_Includes.ipf"
files = "Packages/tests/UTF_BackgroundFunctions.ipf"
files = "Packages/tests/UTF_Constants.ipf"
files = "Packages/tests/UTF_DataGenerators.ipf"
files = "Packages/tests/UTF_HardwareHelperFunctions.ipf"
files = "Packages/tests/UTF_HelperFunctions.ipf"
files = "Packages/tests/UTF_TestNWBExportV1.ipf"
files = "Packages/tests/UTF_TestNWBExportV2.ipf"
files = "Packages/tests/UserAnalysisFunctions.ipf"
