#pragma rtGlobals=3		// Use modern global access method and strict wave access.

#include "C:Users:timj:Documents:MIES:SourceTree:ACL_TabUtilities"
#include "C:Users:timj:Documents:MIES:SourceTree:ACL_UserdataEditor"
#include "C:Users:timj:Documents:MIES:SourceTree:TJ_MIES_AmplifierInteraction"
#include "C:Users:timj:Documents:MIES:SourceTree:TJ_MIES_Analysis"
#include "C:Users:timj:Documents:MIES:SourceTree:TJ_MIES_DataAcqITC"
#include "C:Users:timj:Documents:MIES:SourceTree:TJ_MIES_DataBrowser"
#include "C:Users:timj:Documents:MIES:SourceTree:TJ_MIES_DataConfiguratorITC"
#include "C:Users:timj:Documents:MIES:SourceTree:TJ_MIES_DataManagementNew"
#include "C:Users:timj:Documents:MIES:SourceTree:TJ_MIES_ExperimentDocumentation"
#include "C:Users:timj:Documents:MIES:SourceTree:TJ_MIES_HardwareSetUp"
#include "C:Users:timj:Documents:MIES:SourceTree:TJ_MIES_Indexing"
#include "C:Users:timj:Documents:MIES:SourceTree:TJ_MIES_InitiateMIES"
#include "C:Users:timj:Documents:MIES:SourceTree:TJ_MIES_Oscilloscope"
#include "C:Users:timj:Documents:MIES:SourceTree:TJ_MIES_PanelITC"
#include "C:Users:timj:Documents:MIES:SourceTree:TJ_MIES_RepeatedAcquisition"
#include "C:Users:timj:Documents:MIES:SourceTree:TJ_MIES_TestPulse"
#include "C:Users:timj:Documents:MIES:SourceTree:TJ_MIES_WaveBuilder"
#include "C:Users:timj:Documents:MIES:SourceTree:TJ_MIES_WaveBuilderPanel"
#include "C:Users:timj:Documents:MIES:SourceTree:TJ_MIES_WaveNoteMgmnt"