[lint]
noreturn-func=FATAL_ERROR|SFH_FATAL_ERROR|FAIL
files = "DR_MIES_TangoInteract.ipf"
files = "MIES_AcceleratedModifyGraph.ipf"
files = "MIES_AcquisitionStateHandling.ipf"
files = "MIES_AmplifierInteraction.ipf"
files = "MIES_AnalysisBrowser.ipf"
files = "MIES_AnalysisBrowser_Macro.ipf"
files = "MIES_AnalysisBrowser_SweepBrowser.ipf"
files = "MIES_AnalysisBrowser_SweepBrowser_Export.ipf"
files = "MIES_AnalysisBrowser_SweepBrowser_Export_Macro.ipf"
files = "MIES_AnalysisFunctionHelpers.ipf"
files = "MIES_AnalysisFunctionManagement.ipf"
files = "MIES_AnalysisFunctionPrototypes.ipf"
files = "MIES_AnalysisFunctions.ipf"
files = "MIES_AnalysisFunctions_Dashboard.ipf"
files = "MIES_AnalysisFunctions_MultiPatchSeq.ipf"
files = "MIES_AnalysisFunctions_MultiPatchSeq_SpikeControl.ipf"
files = "MIES_AnalysisFunctions_PatchSeq.ipf"
files = "MIES_ArtefactRemoval.ipf"
files = "MIES_Async.ipf"
files = "MIES_AsynchronousData.ipf"
files = "MIES_BackgroundWatchdog.ipf"
files = "MIES_Blowout.ipf"
files = "MIES_BrowserSettingsPanel.ipf"
files = "MIES_Browser_Plotter.ipf"
files = "MIES_Cache.ipf"
files = "MIES_CheckInstallation.ipf"
files = "MIES_Configuration.ipf"
files = "MIES_Constants.ipf"
files = "MIES_ConversionConstants.ipf"
files = "MIES_DAC-Hardware.ipf"
files = "MIES_DAEphys.ipf"
files = "MIES_DAEphys_GuiState.ipf"
files = "MIES_DAEphys_Macro.ipf"
files = "MIES_DANDI.ipf"
files = "MIES_DataAcquisition.ipf"
files = "MIES_DataAcquisition_Multi.ipf"
files = "MIES_DataAcquisition_Single.ipf"
files = "MIES_DataBrowser.ipf"
files = "MIES_DataBrowser_Macro.ipf"
files = "MIES_DataConfiguratonRecreation.ipf"
files = "MIES_DataConfigurator.ipf"
files = "MIES_DebugPanel.ipf"
files = "MIES_DebugPanel_Macro.ipf"
files = "MIES_Debugging.ipf"
files = "MIES_Downsample.ipf"
files = "MIES_EnhancedWMRoutines.ipf"
files = "MIES_Epochs.ipf"
files = "MIES_ExperimentDocumentation.ipf"
files = "MIES_ForeignFunctionInterface.ipf"
files = "MIES_GlobalStringAndVariableAccess.ipf"
files = "MIES_GuiPopupMenuExt.ipf"
files = "MIES_GuiUtilities.ipf"
files = "MIES_HDF5Ops.ipf"
files = "MIES_IVSCC.ipf"
files = "MIES_IVSCC_Macro.ipf"
files = "MIES_IgorHooks.ipf"
files = "MIES_Indexing.ipf"
files = "MIES_InputDialog.ipf"
files = "MIES_InputDialog_Macro.ipf"
files = "MIES_JSONWaveNotes.ipf"
files = "MIES_Labnotebook.ipf"
files = "MIES_LogbookViewer.ipf"
files = "MIES_Logging.ipf"
files = "MIES_Menu.ipf"
files = "MIES_MiesUtilities_Algorithm.ipf"
files = "MIES_MiesUtilities_BackupWaves.ipf"
files = "MIES_MiesUtilities_Channels.ipf"
files = "MIES_MiesUtilities_Checks.ipf"
files = "MIES_MiesUtilities_Config.ipf"
files = "MIES_MiesUtilities_Conversion.ipf"
files = "MIES_MiesUtilities_DataManagement.ipf"
files = "MIES_MiesUtilities_Device.ipf"
files = "MIES_MiesUtilities_GUI.ipf"
files = "MIES_MiesUtilities_Getter.ipf"
files = "MIES_MiesUtilities_Logbook.ipf"
files = "MIES_MiesUtilities_Logging.ipf"
files = "MIES_MiesUtilities_Recreation.ipf"
files = "MIES_MiesUtilities_Settings.ipf"
files = "MIES_MiesUtilities_Sweep.ipf"
files = "MIES_MiesUtilities_System.ipf"
files = "MIES_MiesUtilities_Uploads.ipf"
files = "MIES_MiesUtilities_ZeroMQ.ipf"
files = "MIES_NeuroDataWithoutBorders.ipf"
files = "MIES_OptimzedOverlapDistributedAcquisition.ipf"
files = "MIES_Oscilloscope.ipf"
files = "MIES_OverlaySweeps.ipf"
files = "MIES_PackageSettings.ipf"
files = "MIES_Pictures.ipf"
files = "MIES_PressureControl.ipf"
files = "MIES_ProgrammaticGUIControl.ipf"
files = "MIES_Publish.ipf"
files = "MIES_PulseAveraging.ipf"
files = "MIES_RepeatedAcquisition.ipf"
files = "MIES_SamplingInterval.ipf"
files = "MIES_StimsetAPI.ipf"
files = "MIES_Structures.ipf"
files = "MIES_SweepFormula.ipf"
files = "MIES_SweepFormula_Executor.ipf"
files = "MIES_SweepFormula_Helpers.ipf"
files = "MIES_SweepFormula_Operations.ipf"
files = "MIES_SweepFormula_Operations_Select.ipf"
files = "MIES_SweepFormula_Operations_TP.ipf"
files = "MIES_SweepFormula_PSX.ipf"
files = "MIES_SweepFormula_PSX_Macro.ipf"
files = "MIES_SweepFormula_Parser.ipf"
files = "MIES_SweepSaving.ipf"
files = "MIES_TangoInteract.ipf"
files = "MIES_TestPulse.ipf"
files = "MIES_TestPulse_Multi.ipf"
files = "MIES_TestPulse_Single.ipf"
files = "MIES_ThreadedFIFOHandling.ipf"
files = "MIES_ThreadsafeDataSharing.ipf"
files = "MIES_ThreadsafeUtilities.ipf"
files = "MIES_TraceUserData.ipf"
files = "MIES_Utilities_Algorithm.ipf"
files = "MIES_Utilities_Checks.ipf"
files = "MIES_Utilities_Conversions.ipf"
files = "MIES_Utilities_DataFolder.ipf"
files = "MIES_Utilities_Debugger.ipf"
files = "MIES_Utilities_File.ipf"
files = "MIES_Utilities_GUI.ipf"
files = "MIES_Utilities_Generators.ipf"
files = "MIES_Utilities_JSON.ipf"
files = "MIES_Utilities_List.ipf"
files = "MIES_Utilities_Numeric.ipf"
files = "MIES_Utilities_ProgramFlow.ipf"
files = "MIES_Utilities_SFHCheckers.ipf"
files = "MIES_Utilities_Strings.ipf"
files = "MIES_Utilities_System.ipf"
files = "MIES_Utilities_Time.ipf"
files = "MIES_Utilities_WaveHandling.ipf"
files = "MIES_WaveBuilder.ipf"
files = "MIES_WaveBuilderPanel.ipf"
files = "MIES_WaveBuilder_Macro.ipf"
files = "MIES_WaveDataFolderGetters.ipf"
files = "MIES_WaverefBrowser.ipf"
files = "MIES_WaverefBrowser_Macro.ipf"
