IPNWB_NWBUtils.ipf
variable GetNoCompression()
Convenience getters.
Igor Pro does not allow cross IM access to constants
References NO_COMPRESSION.
Referenced by NWB_PrepareExport, NWB_WriteTestpulseData.
variable GetChunkedCompression()
References CHUNKED_COMPRESSION.
Referenced by NWB_AppendIgorHistoryAndLogFile, NWB_ExportAllData, NWB_ExportAllStimsets.
variable GetSingleChunkCompression()
References SINGLE_CHUNK_COMPRESSION.
Referenced by NWB_WriteTestpulseData.
string CompressionModeToString(variable mode)
References ASSERT_TS, CHUNKED_COMPRESSION, NO_COMPRESSION, SINGLE_CHUNK_COMPRESSION.
Referenced by NWB_ExportAllData.
const string NWB_PATCHCLAMPSERIES_V1
Referenced by GetNWBgroupPatchClampSeries.
const string NWB_PATCHCLAMPSERIES_V2
Referenced by GetNWBgroupPatchClampSeries.
const string NWB_VERSION_V1
Referenced by GetNWBVersionString.
const string NWB_VERSION_V2
Referenced by GetNWBVersionString.
string DetermineNamespace(string neurodata_type)
Determine the namespace of the given neurodata type.
Note: - core specification "2.2.0" hdmf-common "1.1.0"
References HDMF_SPEC_NAME, NDX_MIES_SPEC_NAME, NWB_SPEC_NAME.
Referenced by WriteNeuroDataType.
string GetTimeSeriesMissingFields(variable channelType, variable clampMode)
Return the initial values for the missing_fields attribute depending on the channel type, one of IPNWBChannelTypes, and the clamp mode, one in IPNWB_ClampModes.
References DetermineDataTypeFromProperties.
Referenced by InitTimeSeriesProperties.
variable GetChannelTypeFromNeurodataType(string neurodata_type)
Derive the channel type, one of IPNWBChannelTypes, from the neurodata_type attribute and return it.
neurodata_type string with neurodata type specification defined in nwb.icephys.json_
References ASSERT_TS, IPNWB_CHANNEL_TYPE_ADC, IPNWB_CHANNEL_TYPE_DAC, IPNWB_CHANNEL_TYPE_OTHER.
Referenced by ReadTimeSeriesProperties.
variable GetClampModeFromNeurodataType(string neurodata_type)
Derive the clamp mode from the neurodata_type attribute and return it.
neurodata_type string with neurodata type specification defined in nwb.icephys.json_
References ASSERT_TS, I_CLAMP_MODE, I_EQUAL_ZERO_MODE, V_CLAMP_MODE.
Referenced by ReadTimeSeriesProperties.
string DetermineDataTypeFromProperties(variable channelType, variable clampMode)
Determine the neurodata type based on channel type and clamp mode.
GetClampModeFromNeurodataType channelType one in IPNWBChannelTypes clampMode one in IPNWB_ClampModes neurodata_type string with neurodata type specification defined in nwb.icephys.json_
References I_CLAMP_MODE, I_EQUAL_ZERO_MODE, IPNWB_CHANNEL_TYPE_ADC, IPNWB_CHANNEL_TYPE_DAC, V_CLAMP_MODE.
Referenced by GetTimeSeriesMissingFields, InitTimeSeriesProperties, NWB_GetTimeSeriesProperties, WriteSingleChannel.
string ReadNWBVersion(variable fileID)
get the (major) version of the nwb file
fileID id of open hdf5 file major version e.g. 1 or 2
References H5_AttributeExists, H5_LoadAttribute.
Referenced by AB_AddMapEntry, AB_LoadSweepFromNWB, AB_LoadSweepsFromNWB, AB_LoadUserCommentAndHistoryFromNWB, AddTimeSeriesUnitAndRes, NWB_AppendIgorHistoryAndLogFile, NWB_GetFileForExport, ReadNeuroDataType, WriteNeuroDataType.
variable GetNWBMajorVersion(string version)
convert version string to major version
GetNWBVersionString
References AnalyzeNWBVersion, EnsureValidNWBVersion.
Referenced by AB_AddMapEntry, AB_LoadSweepFromNWB, AB_LoadSweepsFromNWB, AB_LoadUserCommentAndHistoryFromNWB, NWB_AppendIgorHistoryAndLogFile, NWB_GetFileForExport.
variable AnalyzeNWBVersion(string version, variable *version0, variable *version1, variable *version2)
convert version string to major and all minor numeric versions
version version0 numeric first part of the version string (major Version) version1 numeric second part of the version string (minor Version) version2 numeric third part of the version string (sub Version) analyzed numeric versions
References ASSERT_TS, EnsureValidNWBVersion.
Referenced by GetNWBMajorVersion.
variable EnsureValidNWBVersion(variable version)
References ASSERT_TS.
Referenced by AddDevice, AddElectrode, AddModificationTimeEntry, AnalyzeNWBVersion, CreateCommonGroups, GetNWBMajorVersion, LoadSweepNumber, LoadTimeseries, NWB_AddGeneratorString, NWB_AddSpecifications, NWB_AppendIgorHistoryAndLogFile, OpenAcquisition, ReadAcquisition, ReadDevices, ReadElectrodeName, ReadNeuroDataType, WriteNeuroDataType, WriteSingleChannel.
string LoadSpecification(string specLoc, string specName)
Load the NWB specification from files in the main directory.
Note: Open, FbinRead and Close are not threadsafe specLoc Igor Pro file path to specifications (Path Separator: ":") specName specifications file identifier (without trailing *.json ending) JSON string
References ASSERT_TS, ClearRTError, SpecificationsDiscLocation.
Referenced by WriteSpecification.
string SpecificationsDiscLocation()
Return Folder of NWB:N specifications.
Note: This is typically located at the location of the IPNWB program ipf files. FunctionPath is not threadsafe
References GetFolder.
Referenced by LoadSpecification.
string ReadTextAttributeAsList(variable locationID, string path, string name)
Read a text attribute as semicolon ; separated list.
locationID HDF5 identifier, can be a file or group path Additional path on top of locationID which identifies the group or dataset name Name of the attribute to load
References ReadTextAttribute, TextWaveToList.
Referenced by ReadNeuroDataType.
wave ReadTextAttribute(variable locationID, string path, string name)
Read a text attribute as text wave, return a single element wave with PLACEHOLDER if it does not exist.
locationID HDF5 identifier, can be a file or group path Additional path on top of locationID which identifies the group or dataset name Name of the attribute to load
References ASSERT_TS, H5_LoadAttribute, IsTextWave, PLACEHOLDER.
Referenced by ReadTextAttributeAsList.
string ReadTextAttributeAsString(variable locationID, string path, string name)
Read a text attribute as string, return PLACEHOLDER if it does not exist.
locationID HDF5 identifier, can be a file or group path Additional path on top of locationID which identifies the group or dataset name Name of the attribute to load
References ASSERT_TS, H5_LoadAttribute, IsTextWave, PLACEHOLDER, ROWS.
Referenced by ReadDevices, ReadNeuroDataType.
variable ReadAttributeAsNumber(variable locationID, string path, string name)
Read a text attribute as number, return NaN if it does not exist.
locationID HDF5 identifier, can be a file or group path Additional path on top of locationID which identifies the group or dataset name Name of the attribute to load
References ASSERT_TS, H5_LoadAttribute, IsNumericWave, ROWS.
Referenced by LoadSweepNumber.
wave ReadTextDataSet(variable locationID, string name)
Read a text dataset as text wave, return a single element wave with PLACEHOLDER if it does not exist.
locationID HDF5 identifier, can be a file or group name Name of the HDF5 dataset
References ASSERT_TS, H5_LoadDataset, IsTextWave, PLACEHOLDER.
Referenced by ReadTopLevelInfo.
string ReadTextDataSetAsString(variable locationID, string name)
Read a text dataset as string, return PLACEHOLDER if it does not exist.
locationID HDF5 identifier, can be a file or group name Name of the HDF5 dataset
References ASSERT_TS, H5_LoadDataset, IsTextWave, PLACEHOLDER, ROWS.
Referenced by AB_LoadUserCommentAndHistoryFromNWB, NWB_ReadSessionStartTime, ReadElectrodeName, ReadGeneralInfo, ReadSubjectInfo, ReadTopLevelInfo.
variable ReadDataSetAsNumber(variable locationID, string name)
Read a text dataset as number, return NaN if it does not exist.
locationID HDF5 identifier, can be a file or group name Name of the HDF5 dataset
References ASSERT_TS, H5_LoadDataset, IsNumericWave, ROWS.
Referenced by ReadTimeSeriesProperties.
variable WriteTextDatasetIfSet(variable locationID, string name, string str, variable compressionMode=defaultValue)
Write a text dataset only if it is not equal to PLACEHOLDER.
locationID HDF5 identifier, can be a file or group name Name of the HDF5 dataset str Contents to write into the dataset compressionMode [optional, defaults to NO_COMPRESSION] Type of compression to use, one of CompressionMode
References H5_WriteTextDataset, NO_COMPRESSION, PLACEHOLDER.
Referenced by CreateCommonGroups.
string GetNWBgroupPatchClampSeries(variable version)
get location of the patchclamp series acquisition object
version target NWB version full path to patchclampseries group
References NWB_PATCHCLAMPSERIES_V1, NWB_PATCHCLAMPSERIES_V2.
Referenced by CreateCommonGroups, LoadTimeseries, NWB_AppendSweepLowLevel, OpenAcquisition, ReadAcquisition.
string GetNWBVersionString(variable version)
get NWB version for current Igor Pro implementation
version maior NWB version e.g. 2 full version string in the format (?:NWB-)?[1,2]\.[0-9](?:\.[0-9])?[b]?
References NWB_VERSION_LATEST, NWB_VERSION_V1, NWB_VERSION_V2.
Referenced by InitToplevelInfo.
variable GetNWBVersion()
get latest supported NWB version
maior version
References NWB_VERSION_LATEST.
Referenced by NWB_ExportWithDialog.
string GetHistoryAndLogFileDatasetName(variable version)
Return the name of the history dataset.
References ASSERT_TS.
Referenced by AB_LoadUserCommentAndHistoryFromNWB, NWB_AppendIgorHistoryAndLogFile.