IPNWB_Debugging.ipf
const string functionReturnMessage
Referenced by DEBUGPRINTs, DEBUGPRINTv.
variable ASSERT_TS(variable var, string errorMsg)
Low overhead function to check assertions (threadsafe variant)
var if zero an error message is printed into the history and procedure execution is aborted, nothing is done otherwise. errorMsg error message to output in failure case Example usage: ASSERT_TS(DataFolderExistsDFR(dfr),"MyFunc:dfrdoesnotexist") dosomethingwithdfr Unlike ASSERT() this function does not print a stacktrace or jumps into the debugger. The reasons are Igor Pro limitations. Therefore it is advised to prefix errorMsg with the current function name.
variable DEBUGPRINTv(variable var, string format=defaultValue)
Output debug information and return the parameter var.
Debug function especially designed for usage in return statements. For example calling the following function FunctiondoStuff() variablevar=1+2 returnDEBUGPRINTv(var) End will output DEBUG doStuff(...)#L5: return value 3 to the history. var numerical argument for debug output format optional format string to override the default of "%g"
string DEBUGPRINTs(string str, string format=defaultValue)
Output debug information and return the parameter str.
Debug function especially designed for usage in return statements. For example calling the following function Function/sdoStuff() variablestr="a"+"b" returnDEBUGPRINTs(str) End will output DEBUG doStuff(...)#L5: return value ab to the history. str string argument for debug output format optional format string to override the default of "%s"
variable DEBUGPRINT(string msg, variable var=defaultValue, string str=defaultValue, string format=defaultValue)
Generic debug output function.
Outputs variables and strings with optional format argument. Examples: DEBUGPRINT("beforeapossiblecrash") DEBUGPRINT("somevariable",var=myVariable) DEBUGPRINT("mystring",str=myString) DEBUGPRINT("Currentstate",var=state,format="%.5f") msg descriptive string for the debug message var variable str string format format string overrides the default of "%g" for variables and "%s" for strings
variable DEBUG_TIMER_START()
Start a timer for performance measurements.
Usage: variablereferenceTime=DEBUG_TIMER_START() //partonetobenchmark DEBUGPRINT_ELAPSED(referenceTime) //parttwotobenchmark DEBUGPRINT_ELAPSED(referenceTime)
Referenced by AD_Update, AverageWavesFromSameYAxisIfReq, DB_UpdateSweepPlot, SWS_DeleteDataWaves, TPM_BkrdTPFuncMD, UploadCrashDumps, WB_GetStimSet, WB_NoiseSegment.
variable DEBUGPRINT_ELAPSED(variable referenceTime)
Print the elapsed time for performance measurements.
DEBUG_TIMER_START()
References DEBUGPRINT.
Referenced by AD_Update, AverageWavesFromSameYAxisIfReq, DB_UpdateSweepPlot, SWS_DeleteDataWaves, TPM_BkrdTPFuncMD, UploadCrashDumps, WB_GetStimSet, WB_NoiseSegment.
variable EnableDebugMode()
Enable debug mode.
Referenced by DP_CheckProc_Debug.
variable DisableDebugMode()
Disable debug mode.
Referenced by DP_CheckProc_Debug.
variable DEBUG_STOREFUNCTION()