IPNWB_Reader.ipf
string ReadDevices(variable fileID, variable version)
List devices in given hdf5 file.
fileID identifier of open HDF5 file version major NWB version comma separated list of devices
References EnsureValidNWBVersion, H5_ListGroupMembers, H5_ListGroups, NWB_DEVICES, NWB_VERSION_LATEST, ReadTextAttributeAsString, RemovePrefixFromListItem.
string ReadElectrodeName(string discLocation, string seriesPath, variable version)
return name of electrode
AddElectrode discLocation full path to file in Igor disc path notation seriesPath Full Path inside HDF5 structure to TimeSeries group version major NWB version the name of the electrode or "" for unassociated channels
References AnalyseChannelName, ASSERT_TS, EnsureValidNWBVersion, H5_CloseFile, H5_GetLinkTarget, H5_OpenFile, NWB_ELECTRODE_PREFIX, NWB_INTRACELLULAR_EPHYS, NWB_VERSION_LATEST, ReadTextDataSetAsString.
string ReadLabNoteBooks(variable fileID)
List groups inside /general/labnotebook.
fileID identifier of open HDF5 file list with name of all groups inside /general/labnotebook/*
References H5_GroupExists, H5_ListGroups, NWB_LABNOTEBOOK.
Referenced by AB_LoadLabNotebookFromNWB.
string ReadAcquisition(variable fileID, variable version)
List all acquisition channels.
fileID identifier of open HDF5 file version NWB major version comma separated list of channels
References AddPrefixToEachListItem, EnsureValidNWBVersion, GetNWBgroupPatchClampSeries, H5_ListGroups.
Referenced by AB_LoadSweepsFromNWB.
string ReadStimulus(variable fileID)
List all stimulus channels.
fileID identifier of open HDF5 file comma separated list of channels
References AddPrefixToEachListItem, H5_ListGroups, NWB_STIMULUS_PRESENTATION.
Referenced by AB_LoadSweepsFromNWB.
string ReadStimsets(variable fileID)
List all stimsets.
fileID identifier of open HDF5 file comma separated list of contents of the stimset group
References ASSERT_TS, H5_IsFileOpen, H5_ListGroupMembers, NWB_STIMULUS, StimsetPathExists.
Referenced by NWB_LoadAllStimsets.
variable AnalyseChannelName(string channel, ReadChannelParams *p)
Try to extract information from channel name string.
channel Input channel name in form data_00000_TTL1_3 p ReadChannelParams structure to get filled
References ReadChannelParams::channelNumber, ReadChannelParams::channelSuffix, ReadChannelParams::channelType, GetBaseName, ReadChannelParams::groupIndex, IPNWB_CHANNEL_TYPE_ADC, IPNWB_CHANNEL_TYPE_DAC, IPNWB_CHANNEL_TYPE_OTHER, IPNWB_CHANNEL_TYPE_TTL, ReadChannelParams::ttlBit.
Referenced by AB_LoadSweepFromNWBgeneric, ReadElectrodeName.
variable LoadSourceAttribute(variable locationID, string channel, ReadChannelParams *p)
Read parameters from source attribute.
Function is NWBv1 specific LoadSweepNumber locationID HDF5 group specified channel is a member of channel channel to load p ReadChannelParams structure to get filled
References ASSERT_TS, ReadChannelParams::channelNumber, ReadChannelParams::channelType, ReadChannelParams::device, ReadChannelParams::electrodeNumber, H5_LoadAttribute, IPNWB_CHANNEL_TYPE_ADC, IPNWB_CHANNEL_TYPE_DAC, IPNWB_CHANNEL_TYPE_TTL, IsTextWave, ROWS, ReadChannelParams::sweep, ReadChannelParams::ttlBit.
Referenced by LoadSweepNumber.
variable LoadSweepNumber(variable locationID, string channel, variable version)
Load sweep number from specified channel name.
locationID id of an open hdf5 group containing channel channel name of channel for which sweep number is loaded version NWB maior version sweep number
References EnsureValidNWBVersion, LoadSourceAttribute, NWB_VERSION_LATEST, ReadAttributeAsNumber.
Referenced by AB_StoreChannelsBySweep.
wave LoadDataWave(variable locationID, string channel, string path=defaultValue)
Load data wave from specified path.
locationID id of an open hdf5 group containing channel id can also be of an open nwb file. In this case specify (optional) path. channel name of channel for which data attribute is loaded path use path to specify group inside hdf5 file where ./channel/data is located. reference to free wave containing loaded data
References H5_GroupExists, H5_LoadDataset.
Referenced by LoadStimulus, LoadTimeseries.
wave LoadTimeseries(variable locationID, string path, variable version)
Load single TimeSeries data as a wave from NWB_PATCHCLAMPSERIES_V[12].
locationID id of an open hdf5 group or file path name or path of TimeSeries for which data is loaded version NWB major version reference to wave containing loaded data
References EnsureValidNWBVersion, GetBaseName, GetNWBgroupPatchClampSeries, LoadDataWave.
Referenced by AB_LoadSweepFromNWBgeneric.
wave LoadStimulus(variable locationID, string path)
Load single TimeSeries data as a wave from NWB_STIMULUS_PRESENTATION.
locationID id of an open hdf5 group or file path name or path of TimeSeries for which data is loaded reference to wave containing loaded data
References GetBaseName, LoadDataWave, NWB_STIMULUS_PRESENTATION.
Referenced by AB_LoadSweepFromNWBgeneric.
variable OpenAcquisition(variable fileID, variable version)
Open hdf5 group containing acquisition channels.
fileID id of an open hdf5 group or file version NWB major version id of hdf5 group
References EnsureValidNWBVersion, GetNWBgroupPatchClampSeries, H5_OpenGroup.
Referenced by AB_LoadSweepFromNWB.
variable OpenStimulus(variable fileID)
Open hdf5 group containing stimulus channels.
fileID id of an open hdf5 group or file id of hdf5 group
References H5_OpenGroup, NWB_STIMULUS_PRESENTATION.
Referenced by AB_LoadSweepFromNWB.
variable OpenStimset(variable fileID)
Open hdf5 group containing stimsets.
fileID id of an open hdf5 group or file id of hdf5 group
References ASSERT_TS, H5_OpenGroup, NWB_STIMULUS, StimsetPathExists.
Referenced by AB_LoadStimsetFromFile, NWB_LoadAllStimsets.
variable StimsetPathExists(variable fileID)
Check if the path to the stimsets exist in the NWB file.
References H5_GroupExists, NWB_STIMULUS.
Referenced by AB_LoadStimsetFromFile, NWB_LoadAllStimsets, OpenStimset, ReadStimsets.
variable ReadTopLevelInfo(variable fileID, ToplevelInfo *toplevelInfo)
Read in all NWB datasets from the root group ('/')
References ToplevelInfo::file_create_date, H5_OpenGroup, ToplevelInfo::identifier, ToplevelInfo::nwb_version, ParseISO8601TimeStamp, ReadTextDataSet, ReadTextDataSetAsString, ToplevelInfo::session_description, ToplevelInfo::session_start_time.
variable ReadGeneralInfo(variable fileID, GeneralInfo *generalinfo)
Read in all standard NWB datasets from the group '/general'.
References H5_OpenGroup, ReadTextDataSetAsString.
variable ReadSubjectInfo(variable fileID, SubjectInfo *subjectInfo)
Read in all NWB datasets from the root group '/general/subject'.
References SubjectInfo::age, SubjectInfo::date_of_birth, SubjectInfo::description, SubjectInfo::genotype, H5_OpenGroup, ReadTextDataSetAsString, SubjectInfo::sex, SubjectInfo::species, SubjectInfo::subject_id, SubjectInfo::weight.
variable ReadTimeSeriesProperties(variable locationID, string channel, TimeSeriesProperties *tsp)
Read the TimeSeries properties from the given group in locationID.
locationID TimeSeries group ID channel TimeSeries group name tsp TimeSeriesProperties structure
References TimeSeriesProperties::data, GetChannelTypeFromNeurodataType, GetClampModeFromNeurodataType, H5_OpenGroup, InitTimeSeriesProperties, TimeSeriesProperties::isCustom, IsNaN, TimeSeriesProperties::missing_fields, TimeSeriesProperties::names, ReadDataSetAsNumber, ReadNeuroDataType.
string ReadNeuroDataType(variable fileID, string name)
Read nwb data type.
WriteNeuroDataType fileID HDF5 identifier of file (not group) name Path to element who's DataType is queried string with data type (e.g. uint, DynamicTable, SweepTable)
References EnsureValidNWBVersion, ReadNWBVersion, ReadTextAttributeAsList, ReadTextAttributeAsString.
Referenced by ReadTimeSeriesProperties.
std::tuple< WaveOrNull, WaveTextOrNull > LoadSweepTable(variable locationID, variable version)
Return the two SweepTable data columns sweep_number and series
TodoAllow Executions for files with missing SweepTable entry using LoadSweepNumber locationID HDF5 identifier version major NWB version sweep_number and path to TimeSeries as waves
References ASSERT_TS, H5_LoadDataset, H5_OpenGroup, IsNaN, NWB_INTRACELLULAR_EPHYS.
Referenced by AB_StoreChannelsBySweep.
wave LoadEpochTable(string nwbFilePath)
Return the epoch table as wave reference wave.
Due to IP limitations, the NWB file path of the closed file must be passed. See GetEpochsWaveInternal() for the wave layout.
References ASSERT, ASSERT_TS, ClearRTError, EnsureLargeEnoughWave, EPOCHTIME_PRECISION, ExpandRuggedVector, GetEpochsWaveInternal, GetNumberFromWaveNote, GetTimeseriesProperties, GetWindowsPath, H5_GroupExists, H5_LoadDataset, H5_OpenFile, H5_OpenGroup, IsInteger, IsNaN, NOTE_INDEX, NWB_TIME_INTERVALS_EPOCHS, NWB_TIME_INTERVALS_TIMESERIES_EPOCHS, ROWS, SetNumberInWaveNote.
static wave GetTimeseriesProperties(variable locationID, WaveText timeseries, string name, string attrName=defaultValue)
Return timeseries properties which can be a dataset or attribute as wave.
References ASSERT_TS, GetUniqueEntries, H5_LoadAttribute, H5_LoadDataset, ROWS.
Referenced by LoadEpochTable.
static wave GetEpochsWaveInternal(WaveText timeseries)
Return a free wave reference wave.
ROWS: One entry for each unique timeseries path, with dimension label Each row will hold a Nx4 wave for the epoch info of each row. GetEpochsWave()
References GetUniqueEntries, MINIMUM_WAVE_SIZE, NOTE_INDEX, ROWS, SetEpochsDimensionLabels, SetNumberInWaveNote.
Referenced by LoadEpochTable.
static wave ExpandRuggedVector(WaveText data_rugged, wave index, string sep)
Expand data from rugged DynamicTable column entry.
See also https://github.com/hdmf-dev/hdmf-common-schema/blob/main/common/table.yaml#L4.
References ROWS.
Referenced by LoadEpochTable.