IPNWB_Structures.ipf
variable InitWriteChannelParams(WriteChannelParams *p)
Initialize WriteChannelParams structure.
References WriteChannelParams::epochs, WriteChannelParams::groupIndex.
Referenced by NWB_AppendSweepLowLevel.
variable InitReadChannelParams(ReadChannelParams *p)
Initialization routine for InitReadChannelParams.
References ReadChannelParams::channelNumber, ReadChannelParams::channelSuffix, ReadChannelParams::channelType, ReadChannelParams::device, ReadChannelParams::electrodeNumber, ReadChannelParams::groupIndex, ReadChannelParams::sweep, ReadChannelParams::ttlBit.
variable InitGeneralInfo(GeneralInfo *gi)
Initialization routine for GeneralInfo.
References GeneralInfo::data_collection, GeneralInfo::experiment_description, GeneralInfo::experimenter, GeneralInfo::institution, GeneralInfo::lab, GeneralInfo::notes, GeneralInfo::pharmacology, PLACEHOLDER, GeneralInfo::protocol, GeneralInfo::related_publications, GeneralInfo::session_id, GeneralInfo::slices, GeneralInfo::stimulus, GeneralInfo::surgery, GeneralInfo::virus.
Referenced by CreateCommonGroups.
variable InitSubjectInfo(SubjectInfo *si)
Initialization routine for SubjectInfo.
References SubjectInfo::age, SubjectInfo::date_of_birth, SubjectInfo::description, SubjectInfo::genotype, PLACEHOLDER, SubjectInfo::sex, SubjectInfo::species, SubjectInfo::subject_id, SubjectInfo::weight.
Referenced by CreateCommonGroups.
variable InitToplevelInfo(ToplevelInfo *ti, variable version)
Initialization routine for ToplevelInfo.
ti TopLevelInfo Structure version [optional] defaults to latest version specified in NWB_VERSION_LATEST
References DateTimeInUTC, ToplevelInfo::file_create_date, GetISO8601TimeStamp, GetNWBVersionString, ToplevelInfo::identifier, NOISE_GEN_MERSENNE_TWISTER, ToplevelInfo::nwb_version, NWB_VERSION_LATEST, PLACEHOLDER, ToplevelInfo::session_description, ToplevelInfo::session_start_time.
Referenced by NWB_GetFileForExport.
variable InitTimeSeriesProperties(TimeSeriesProperties *tsp, variable channelType, variable clampMode)
Initialization of TimeSeriesProperties.
tsp structure to initialize channelType one of IPNWBChannelTypes clampMode one of IPNWB_ClampModes
References TimeSeriesProperties::data, DetermineDataTypeFromProperties, GetTimeSeriesMissingFields, TimeSeriesProperties::isCustom, TimeSeriesProperties::missing_fields, TimeSeriesProperties::names, TimeSeriesProperties::neurodata_type, TimeSeriesProperties::unit.
Referenced by NWB_GetTimeSeriesProperties, ReadTimeSeriesProperties.
variable InitDynamicTable(DynamicTable *dt)
References DynamicTable::colnames, DynamicTable::data_type, DynamicTable::description.
Referenced by AppendToEpochTable, AppendToSweepTable.
variable InitElementIdentifiers(ElementIdentifiers *eli)
References ElementIdentifiers::data_type.
Referenced by AppendToEpochTable, AppendToSweepTable.
variable InitVectorData(VectorData *vd)
References VectorData::data_type, VectorData::description, VectorData::path.
Referenced by AppendToEpochTable, AppendToSweepTable.
variable InitVectorIndex(VectorIndex *vi)
References VectorIndex::data_type.
Referenced by AppendToEpochTable, AppendToSweepTable.