IPNWB_HDF5Helpers.ipf
const double kHDF5DataInfoVersion
Taken from HDF5 Browser.ipf Included here for convenience.
Referenced by InitHDF5DataInfo.
const double H5S_MAX_RANK
static variable InitHDF5DataInfo(HDF5DataInfo *di)
References kHDF5DataInfoVersion, HDF5DataInfo::structName, HDF5DataInfo::version.
Referenced by H5_AttributeExists, H5_DatasetExists, H5_GetDatasetSize.
const double H5_ATTRIBUTE_SIZE_LIMIT
Referenced by H5_WriteDatasetLowLevel.
const double H5_CHUNK_SIZE
Referenced by H5_GetChunkSizes.
variable H5_WriteTextDataset(variable locationID, string name, string str=defaultValue, WaveTextOrNull wvText=defaultValue, variable overwrite=defaultValue, variable compressionMode=defaultValue, variable skipIfExists=defaultValue, variable writeIgorAttr=defaultValue, variable appendData=defaultValue, variable refMode=defaultValue)
Write a string or text wave into a HDF5 dataset.
locationID HDF5 identifier, can be a file or group name Name of the HDF5 dataset str Contents to write into the dataset wvText Contents to write into the dataset overwrite [optional, defaults to false] Should existing datasets be overwritten compressionMode [optional, defaults to NO_COMPRESSION] Type of compression to use, one of CompressionMode skipIfExists [optional, defaults to false] Do nothing if the dataset already exists writeIgorAttr [optional, defaults to false] Add Igor specific attributes to the dataset, see the /IGOR flag of HDF5SaveData appendData [optional, defaults to -1] Set the dimension to append to within the given dataset (requires compression) refMode [optional, defaults to NO_REFERENCE] Set refMode, one in ReferenceMode (DisplayHelpTopic "Saving Reference Data") Only one of str or wvText can be given.
References ASSERT_TS, H5_WriteDatasetLowLevel, NO_COMPRESSION.
Referenced by AddDevice, AddElectrode, AppendToEpochTable, AppendToSweepTable, CreateCommonGroups, CreateIntraCellularEphys, NWB_AddGeneratorString, NWB_AppendIgorHistoryAndLogFile, NWB_WriteLabnoteBooksAndComments, NWB_WriteResultsWaves, WriteSingleChannel, WriteSpecification, WriteTextDatasetIfSet.
variable H5_WriteDataset(variable locationID, string name, variable var=defaultValue, variable varType=defaultValue, WaveOrNull wv=defaultValue, variable overwrite=defaultValue, variable compressionMode=defaultValue, variable skipIfExists=defaultValue, variable writeIgorAttr=defaultValue, variable appendData=defaultValue)
Write a variable or text wave into a HDF5 dataset.
locationID HDF5 identifier, can be a file or group name Name of the HDF5 dataset var Contents to write into the dataset varType Type of the data, must be given if var is supplied. See IgorTypes wv Contents to write into the dataset overwrite [optional, defaults to false] Should existing datasets be overwritten compressionMode [optional, defaults to NO_COMPRESSION] Type of compression to use, one of CompressionMode skipIfExists [optional, defaults to false] Do nothing if the dataset already exists writeIgorAttr [optional, defaults to false] Add Igor specific attributes to the dataset, see the /IGOR flag of HDF5SaveData appendData [optional, defaults to -1] Set the dimension to append to within the given dataset (requires compression) Only one of var or wv can be given.
References ASSERT_TS, H5_WriteDatasetLowLevel, NO_COMPRESSION.
Referenced by AppendToEpochTable, AppendToSweepTable, NWB_AppendStoredTestPulses, NWB_WriteLabnoteBooksAndComments, NWB_WriteResultsWaves, NWB_WriteStimsetCustomWave, NWB_WriteStimsetTemplateWaves, NWB_WriteTestpulseData, WriteSingleChannel.
static wave H5_GetChunkSizes(wave wv, variable compressionMode)
Return a wave for the valid chunk sizes of each dimension taking into account the compression mode.
References ASSERT_TS, CHUNKED_COMPRESSION, H5_CHUNK_SIZE, NO_COMPRESSION, SINGLE_CHUNK_COMPRESSION.
Referenced by H5_WriteDatasetLowLevel.
static variable H5_WriteDatasetLowLevel(variable locationID, string name, wave wv, variable overwrite, variable compressionMode, variable skipIfExists, variable writeIgorAttr, variable appendData, variable refMode)
H5_WriteTextDataset or H5_WriteDataset
References ASSERT_TS, CHUNKS, COLS, GetFile, H5_ATTRIBUTE_SIZE_LIMIT, H5_DatasetExists, H5_GetChunkSizes, H5_IsValidIdentifier, LAYERS, NO_COMPRESSION, ROWS.
Referenced by H5_WriteDataset, H5_WriteTextDataset.
variable H5_WriteTextAttribute(variable locationID, string attrName, string path, string list=defaultValue, string str=defaultValue, variable overwrite=defaultValue, variable refMode=defaultValue)
Attach a text attribute to the given location.
locationID HDF5 identifier, can be a file, group or dataset attrName Name of the attribute path Additional path on top of locationID which identifies the object onto which the attribute should be attached. list Contents to write into the attribute, list will be always written as 1D-array str Contents to write into the attribute overwrite [optional, defaults to false] Should existing attributes be overwritten refMode [optional, defaults to 0] Set refMode, one in ReferenceMode (DisplayHelpTopic "Saving Reference Data") Only one of str or list can be given.
References ASSERT_TS, NO_REFERENCE, OBJECT_REFERENCE.
Referenced by AddDevice, AddTimeSeriesUnitAndRes, AppendToEpochTable, AppendToSweepTable, CreateCommonGroups, CreateDynamicTable, NWB_AddGeneratorString, WriteNeuroDataType, WriteSingleChannel, WriteSpecification.
variable H5_WriteAttribute(variable locationID, string attrName, string path, variable var, variable varType, variable overwrite=defaultValue)
Attach a numerical attribute to the given location.
locationID HDF5 identifier, can be a file, group or dataset attrName Name of the attribute path Additional path on top of locationID which identifies the object onto which the attribute should be attached. var Contents to write into the attribute varType Type of the attribute, see IgorTypes overwrite [optional, defaults to false] Should existing attributes be overwritten
References ASSERT_TS.
Referenced by AddTimeSeriesUnitAndRes, WriteSingleChannel.
variable H5_CreateSoftLink(variable locationID, string path, string target)
Create a link to a group.
locationID HDF5 identifier, can be a file, group or dataset path Name of the link target The linked destination
References ASSERT_TS.
Referenced by AddElectrode, WriteSingleChannel.
variable H5_OpenFile(string discLocation, variable write=defaultValue)
Open HDF5 file and return ID.
discLocation full path to nwb file write open file for writing. default is readonly. ID for referencing open hdf5 file
References ASSERT_TS.
Referenced by AB_AddMapEntry, AB_LoadLabNotebookFromNWB, AB_LoadResultsFromNWB, AB_LoadStimsetFromFile, AB_LoadStoredTestpulsesFromNWB, AB_LoadSweepFromNWB, AB_LoadSweepsFromNWB, AB_LoadTPStorageFromNWB, AB_LoadUserCommentAndHistoryFromNWB, AppendToEpochTable, LoadEpochTable, NWB_GetFileForExport, NWB_LoadAllStimsets, ReadElectrodeName, WriteSingleChannel.
variable H5_CloseFile(variable fileID)
Close HDF5 file.
fileID ID of open hdf5 file open state as true/false
References H5_IsFileOpen.
Referenced by AB_AddMapEntry, AB_LoadLabNotebookFromNWB, AB_LoadResultsFromNWB, AB_LoadStimsetFromFile, AB_LoadStoredTestpulsesFromNWB, AB_LoadSweepFromNWB, AB_LoadSweepsFromNWB, AB_LoadTPStorageFromNWB, AB_LoadUserCommentAndHistoryFromNWB, NWB_LoadAllStimsets, ReadElectrodeName.
variable H5_IsFileOpen(variable fileID)
Return 1 if the given HDF5 file is already open, 0 otherwise.
fileID HDF5 locationID from HDF5OpenFile.
References H5_GroupExists.
Referenced by BeforeExperimentSaveHook, H5_CloseFile, NWB_GetFileForExport, ReadStimsets.
variable H5_DatasetExists(variable locationID, string name)
Return 1 if the given HDF5 dataset exists, 0 otherwise.
locationID HDF5 identifier, can be a file or group name Additional path on top of locationID which identifies the dataset
References InitHDF5DataInfo.
Referenced by H5_AttributeExists, H5_LoadDataset, H5_WriteDatasetLowLevel, NWB_LoadCustomWave, NWB_LoadStimset.
wave H5_LoadDataset(variable locationID, string name)
Load a specified dataset as wave.
locationID HDF5 identifier, can be a file or group name path on top of locationID which identifies the dataset reference to wave containing loaded data
References ASSERT_TS, H5_DatasetExists.
Referenced by AB_LoadResultsFromNWB, AB_LoadStoredTestpulsesFromNWB, AB_LoadTPStorageFromNWB, AppendToSweepTable, GetTimeseriesProperties, LoadDataWave, LoadEpochTable, LoadSweepTable, NWB_LoadCustomWave, NWB_LoadStimset, ReadDataSetAsNumber, ReadTextDataSet, ReadTextDataSetAsString.
wave H5_GetDatasetSize(variable locationID, string dataset)
Return the dimension sizes of the given dataset.
locationID HDF5 identifier, can be a file or group dataset name of the dataset wave with the dimension sizes or an invalid wave reference
References ASSERT_TS, InitHDF5DataInfo.
Referenced by AppendToEpochTable.
variable H5_AttributeExists(variable locationID, string path, string attribute, variable *objectType=defaultValue)
Check if a given attribute exists.
locationID HDF5 identifier, can be a file or group path Additional path on top of locationID which identifies the group or dataset attribute Name of the attribute objectType [optional] Return the type of the element to which the attribute is attached to. Can be used for subsequent HDF5LoadData calls.
References ASSERT_TS, H5_DatasetExists, H5_GroupExists, InitHDF5DataInfo.
Referenced by H5_LoadAttribute, ReadNWBVersion.
wave H5_LoadAttribute(variable locationID, string path, string attribute)
Load the given attribute and return its contents.
locationID HDF5 identifier, can be a file or group path Additional path on top of locationID which identifies the group or dataset attribute Name of the attribute to load
References ASSERT_TS, H5_AttributeExists.
Referenced by GetTimeseriesProperties, LoadSourceAttribute, ReadAttributeAsNumber, ReadNWBVersion, ReadTextAttribute, ReadTextAttributeAsString.
variable H5_GroupExists(variable locationID, string path)
Return 1 if the given HDF5 group exists, 0 otherwise.
locationID HDF5 identifier, can be a file or group path Additional path on top of locationID which identifies the group.
Referenced by AddElectrode, AppendToEpochTable, AppendToSweepTable, CreateDynamicTable, GetNextFreeGroupIndex, H5_AttributeExists, H5_CreateGroupsRecursively, H5_IsFileOpen, H5_OpenGroup, LoadDataWave, LoadEpochTable, NWB_LoadLabNoteBook, ReadLabNoteBooks, StimsetPathExists.
variable H5_CreateGroupsRecursively(variable locationID, string fullPath)
Create all groups along the given path.
locationID HDF5 identifier, can be a file or group fullPath Additional path on top of locationID which identifies the group
References ASSERT_TS, H5_GroupExists, H5_IsValidIdentifier.
Referenced by AddDevice, AddElectrode, CreateCommonGroups, CreateDynamicTable, CreateIntraCellularEphys, NWB_WriteLabnoteBooksAndComments, NWB_WriteResultsWaves, NWB_WriteStimsetCustomWave, NWB_WriteStimsetTemplateWaves, NWB_WriteTestpulseData, WriteSingleChannel, WriteSpecification.
variable H5_IsValidIdentifier(string name)
Return true if name is a valid hdf5 identifier.
This is more restrictive than the actual HDF5 library checks. See the BNF Grammar here.
Referenced by AddElectrode, H5_CreateGroupsRecursively, H5_WriteDatasetLowLevel.
string H5_ListGroupMembers(variable locationID, string path)
List all datasets at path (non-recursively)
locationID HDF5 identifier, can be a file or group path Additional path on top of locationID which identifies the group
References ASSERT_TS.
Referenced by AB_LoadResultsFromNWB, AB_LoadStoredTestpulsesFromNWB, AB_LoadTPStorageFromNWB, NWB_LoadStimset, ReadDevices, ReadStimsets.
string H5_ListGroups(variable fileID, string path)
List all groups inside a group (non-recursively)
fileID HDF5 file identifier path Full path to the group inside fileID
References ASSERT_TS.
Referenced by ReadAcquisition, ReadDevices, ReadLabNoteBooks, ReadStimulus.
variable H5_OpenGroup(variable locationID, string path)
Open the group reachable via locationID and path and return its ID.
locationID HDF5 identifier, can be a file or group path Additional path on top of locationID which identifies the group the groupID of the opened group. Return NaN if the group did not exist.
References H5_GroupExists.
Referenced by AB_LoadLabNotebookFromNWB, AB_LoadResultsFromNWB, AB_LoadStoredTestpulsesFromNWB, AB_LoadTPStorageFromNWB, AB_LoadUserCommentAndHistoryFromNWB, AddDevice, AddElectrode, AppendToEpochTable, AppendToSweepTable, CreateCommonGroups, CreateDynamicTable, CreateIntraCellularEphys, LoadEpochTable, LoadSweepTable, NWB_AppendIgorHistoryAndLogFile, NWB_WriteLabnoteBooksAndComments, NWB_WriteResultsWaves, NWB_WriteStimsetCustomWave, NWB_WriteStimsetTemplateWaves, NWB_WriteTestpulseData, OpenAcquisition, OpenStimset, OpenStimulus, ReadGeneralInfo, ReadSubjectInfo, ReadTimeSeriesProperties, ReadTopLevelInfo, WriteSingleChannel, WriteSpecification.
variable H5_FlushFile(variable fileID)
Flush the file contents to disc.
fileID HDF5 file identifier
Referenced by NWB_Flush.
string H5_GetLinkTarget(string discLocation, string path)
TodoNeeds HDF5 XOP support for reading link targets use HDF5LinkInfo
References ASSERT_TS.
Referenced by ReadElectrodeName.
string H5_GetLibraryVersion()
Return the HDF5 Library version.
Referenced by NWB_AddGeneratorString.