IPNWB_Writer.ipf
variable CreateCommonGroups(variable locationID, ToplevelInfo *toplevelInfo, GeneralInfo *generalInfo=defaultValue, string subjectInfo=defaultValue)
Create and fill common HDF5 groups and datasets.
locationID HDF5 identifier toplevelInfo [optional, see ToplevelInfo() for defaults] datasets directly below / generalInfo [optional, see GeneralInfo() for defaults] datasets directly below /general subjectInfo [optional, see SubjectInfo() for defaults] datasets below /general/subject
References AddModificationTimeEntry, CHUNKED_COMPRESSION, EnsureValidNWBVersion, GetISO8601TimeStamp, GetNWBgroupPatchClampSeries, H5_CreateGroupsRecursively, H5_OpenGroup, H5_WriteTextAttribute, H5_WriteTextDataset, InitGeneralInfo, InitSubjectInfo, NWB_ANALYSIS, NWB_DEVICES, NWB_EPOCHS, NWB_GENERAL, NWB_PROCESSING, NWB_ROOT, NWB_STIMULUS, NWB_STIMULUS_PRESENTATION, NWB_STIMULUS_TEMPLATES, NWB_SUBJECT, NWB_VERSION_LATEST, WriteNeuroDataType, WriteTextDatasetIfSet.
Referenced by NWB_GetFileForExport.
variable CreateIntraCellularEphys(variable locationID, string filtering=defaultValue)
Create the HDF5 group for intracellular ephys.
locationID HDF5 identifier filtering [optional, defaults to PLACEHOLDER] filtering information
References H5_CreateGroupsRecursively, H5_OpenGroup, H5_WriteTextDataset, NWB_INTRACELLULAR_EPHYS, PLACEHOLDER.
Referenced by NWB_GetFileForExport.
variable AddDevice(variable locationID, string name, variable version, string description)
Add an entry for the device name in the nwb file specified by locationID.
locationID HDF5 identifier name name of device to create version major NWB version description a string describing the created device 1 if a new device was created and 0 if it already existed
References EnsureValidNWBVersion, H5_CreateGroupsRecursively, H5_OpenGroup, H5_WriteTextAttribute, H5_WriteTextDataset, NWB_DEVICES, NWB_VERSION_LATEST, WriteNeuroDataType.
Referenced by NWB_AddDevice.
variable AddElectrode(variable locationID, string name, variable version, string data, string device)
Add an entry for the electrode name with contents data
References ASSERT_TS, EnsureValidNWBVersion, H5_CreateGroupsRecursively, H5_CreateSoftLink, H5_GroupExists, H5_IsValidIdentifier, H5_OpenGroup, H5_WriteTextDataset, NWB_DEVICES, NWB_ELECTRODE_PREFIX, NWB_INTRACELLULAR_EPHYS, NWB_VERSION_LATEST, WriteNeuroDataType.
Referenced by NWB_AppendSweepLowLevel.
variable AddModificationTimeEntry(variable locationID, variable version)
Add a modification timestamp to the NWB file.
References ASSERT_TS, EnsureValidNWBVersion, GetISO8601TimeStamp, ROWS.
Referenced by CreateCommonGroups, NWB_AddDeviceSpecificData, NWB_AppendStimset, NWB_ASYNC_Worker.
variable MarkAsCustomEntry(variable locationID, string name)
Mark a dataset/group as custom.
According to the NWB spec everything not required should be specifically marked. In NWBv2, schema extensions can be used to accomplish this. locationID HDF5 identifier name dataset or group name
References WriteNeuroDataType.
Referenced by NWB_AddGeneratorString, NWB_AppendIgorHistoryAndLogFile, NWB_WriteLabnoteBooksAndComments, NWB_WriteStimsetTemplateWaves, NWB_WriteTestpulseData, WriteSingleChannel.
variable AddTimeSeriesUnitAndRes(variable locationID, string fullAbsPath, string unitWithPrefix, variable resolution=defaultValue, variable overwrite=defaultValue)
Add unit and resolution to TimeSeries dataset.
locationID HDF5 identifier fullAbsPath absolute path to the TimeSeries dataset unitWithPrefix unit with optional prefix of the data in the TimeSeries, ParseUnit resolution [optional, defaults to NaN for unknown] experimental resolution overwrite [optional, defaults to false] should existing attributes be overwritten
References H5_WriteAttribute, H5_WriteTextAttribute, IGOR_TYPE_32BIT_FLOAT, isEmpty, NWB_VERSION_LATEST, ParseUnit, ReadNWBVersion.
Referenced by WriteSingleChannel.
variable AddProperty(TimeSeriesProperties *tsp, string nwbProp, variable value, string unit=defaultValue)
Add a TimeSeries property to the tsp structure.
References ASSERT_TS, TimeSeriesProperties::data, IsFinite, TimeSeriesProperties::missing_fields, TimeSeriesProperties::names, TimeSeriesProperties::neurodata_type, TimeSeriesProperties::unit.
Referenced by NWB_AddSweepDataSets, NWB_GetTimeSeriesProperties.
variable AddCustomProperty(TimeSeriesProperties *tsp, string nwbProp, variable value)
Add a custom TimeSeries property to the names and data waves.
MarkAsCustomEntry
References ASSERT_TS, TimeSeriesProperties::data, TimeSeriesProperties::isCustom, IsFinite, TimeSeriesProperties::names.
Referenced by NWB_GetTimeSeriesProperties.
variable GetNextFreeGroupIndex(variable locationID, string path)
Return the next free group index of the format data_$NUM
References ASSERT_TS, H5_GroupExists, IsEmpty.
Referenced by NWB_AppendSweepLowLevel.
variable WriteSingleChannel(variable locationID, string path, variable version, WriteChannelParams *p, TimeSeriesProperties *tsp, variable compressionMode=defaultValue, string nwbFilePath=defaultValue)
Write the data of a single channel to the NWB file.
locationID HDF5 file identifier path Absolute path in the HDF5 file where the data should be stored version major NWB version p Filled WriteChannelParams structure tsp Filled TimeSeriesProperties structure compressionMode [optional, defaults to NO_COMPRESSION] Type of compression to use, one of CompressionMode nwbFilePath [optional, required only for epoch writing] disc location of the NWB file locationID, this is different from the parameter if epoch information was written
References AddTimeSeriesUnitAndRes, AppendToSweepTable, ASSERT_TS, CHANNEL_NAMES, WriteChannelParams::channelNumber, WriteChannelParams::channelSuffix, WriteChannelParams::channelSuffixDesc, WriteChannelParams::channelType, WriteChannelParams::clampMode, WriteChannelParams::data, TimeSeriesProperties::data, DetermineDataTypeFromProperties, WriteChannelParams::device, WriteChannelParams::electrodeName, WriteChannelParams::electrodeNumber, EnsureValidNWBVersion, WriteChannelParams::epochs, WriteChannelParams::groupIndex, H5_CreateGroupsRecursively, H5_CreateSoftLink, H5_OpenFile, H5_OpenGroup, H5_WriteAttribute, H5_WriteDataset, H5_WriteTextAttribute, H5_WriteTextDataset, I_EQUAL_ZERO_MODE, IGOR_TYPE_32BIT_FLOAT, IGOR_TYPE_32BIT_INT, IGOR_TYPE_64BIT_FLOAT, IGOR_TYPE_UNSIGNED, IPNWB_CHANNEL_TYPE_ADC, IPNWB_CHANNEL_TYPE_DAC, IPNWB_CHANNEL_TYPE_OTHER, TimeSeriesProperties::isCustom, IsEmpty, IsFinite, MarkAsCustomEntry, TimeSeriesProperties::missing_fields, TimeSeriesProperties::names, NO_COMPRESSION, NormalizeToEOL, NWB_INTRACELLULAR_EPHYS, NWB_VERSION_LATEST, PLACEHOLDER, ROWS, WriteChannelParams::samplingRate, WriteChannelParams::startingTime, WriteChannelParams::stimSet, WriteChannelParams::sweep, TimeSeriesProperties::unit, WriteEpochs, WriteNeuroDataType.
Referenced by NWB_AppendSweepLowLevel.
static variable WriteEpochs(string nwbFilePath, WaveText epochs, string timeseries, variable startingTime, variable samplingRate)
References AppendToEpochTable, ROWS.
Referenced by WriteSingleChannel.
static variable AppendToEpochTable(string nwbFilePath, variable startTime, variable stopTime, WaveText tags, WaveText timeseries, wave startingTime, wave rate, variable treelevel)
Append an epoch to the TimeIntervals table.
Note: NWBv2 specific function nwbFilePath HDF5 file path (required for writing the timeseries compound using a custom XOP) startTime start time of the epoch in seconds in the global time coordinate system (included in the range) stopTime stop time of the epoch in seconds in the global time coordinate system (not included in the range) tags text wave with strings for the epoch, format is unspecified timeseries absolute paths to existing timeseries groups startingTime timeseries starting time in s according to NWBv2 spec rate timeseries rate in Hz according to NWBv2 spec treelevel Tree level of the epoch
References ASSERT_TS, CHUNKED_COMPRESSION, ClearRTError, CreateDynamicTable, GetWindowsPath, H5_GetDatasetSize, H5_GroupExists, H5_OpenFile, H5_OpenGroup, H5_WriteDataset, H5_WriteTextAttribute, H5_WriteTextDataset, IGOR_TYPE_32BIT_INT, IGOR_TYPE_64BIT_FLOAT, InitDynamicTable, InitElementIdentifiers, InitVectorData, InitVectorIndex, IsNaN, NO_COMPRESSION, NWB_TIME_INTERVALS_EPOCHS, NWB_TIME_INTERVALS_TIMESERIES_EPOCHS, OBJECT_REFERENCE, ROWS, WriteNeuroDataType.
Referenced by WriteEpochs.
static variable CreateDynamicTable(variable locationID, string path, DynamicTable *dt)
Create a Dynamic Table group at path.
Note: A dynamic table needs at least an id and a vectorData column NaN if the group already exists, 1 otherwise
References DynamicTable::colnames, DynamicTable::data_type, DynamicTable::description, H5_CreateGroupsRecursively, H5_GroupExists, H5_OpenGroup, H5_WriteTextAttribute, WriteNeuroDataType.
Referenced by AppendToEpochTable, AppendToSweepTable.
static variable AppendToSweepTable(variable locationID, string reference, variable sweepNumber)
Append a sweep to the sweep table.
Note: NWBv2 specific function locationID HDF5 identifier reference path to dataset where sweep is stored sweepNumber sweep number
References ASSERT_TS, CHUNKED_COMPRESSION, CreateDynamicTable, H5_GroupExists, H5_LoadDataset, H5_OpenGroup, H5_WriteDataset, H5_WriteTextAttribute, H5_WriteTextDataset, IGOR_TYPE_32BIT_INT, IGOR_TYPE_UNSIGNED, InitDynamicTable, InitElementIdentifiers, InitVectorData, InitVectorIndex, IsNaN, NO_COMPRESSION, NWB_INTRACELLULAR_EPHYS, OBJECT_REFERENCE, ROWS, WriteNeuroDataType.
Referenced by WriteSingleChannel.
variable WriteSpecifications(variable locationID)
write NWB:N specifications that were used for creating this file
Note: non threadsafe due to limitations in LoadSpecification locationID open HDF5 file identifier
References HDMF_SPEC_INCLUDE, HDMF_SPEC_LOCATION, HDMF_SPEC_NAME, HDMF_SPEC_START, HDMF_SPEC_VERSION, NDX_MIES_SPEC_INCLUDE, NDX_MIES_SPEC_LOCATION, NDX_MIES_SPEC_NAME, NDX_MIES_SPEC_START, NDX_MIES_SPEC_VERSION, NWB_SPEC_INCLUDE, NWB_SPEC_LOCATION, NWB_SPEC_NAME, NWB_SPEC_START, NWB_SPEC_VERSION, WriteSpecification.
Referenced by NWB_AddSpecifications.
variable WriteSpecification(variable locationID, string spec_name, string spec_version, string spec_location, string spec_start, string spec_include)
write a specifications group to NWB_SPECIFICATIONS and link its location in .specloc
locationID open HDF5 file identifier spec_name name of namespace, e.g. "core" spec_version version of added namespace as string spec_location Igor File Path to location of *.json files in IPNWB repository spec_start namespace.json declaration file spec_include ";" separated list of include files for defining extensions within the namespace
References H5_CreateGroupsRecursively, H5_OpenGroup, H5_WriteTextAttribute, H5_WriteTextDataset, LoadSpecification, NWB_ROOT, NWB_SPECIFICATIONS, OBJECT_REFERENCE.
Referenced by WriteSpecifications.
variable WriteNeuroDataType(variable locationID, string path, string neurodata_type)
Write a NeuroDataType.
ReadNeuroDataType locationID HDF5 identifier path Path to element who's DataType is queried neurodata_type String version of the data type that should get written
References DetermineDataTypeRefTree, DetermineNamespace, EnsureValidNWBVersion, GenerateRFC4122UUID, H5_WriteTextAttribute, ReadNWBVersion.
Referenced by AddDevice, AddElectrode, AppendToEpochTable, AppendToSweepTable, CreateCommonGroups, CreateDynamicTable, MarkAsCustomEntry, NWB_AddGeneratorString, NWB_AppendStoredTestPulses, NWB_WriteLabnoteBooksAndComments, NWB_WriteResultsWaves, NWB_WriteStimsetCustomWave, NWB_WriteStimsetTemplateWaves, NWB_WriteTestpulseData, WriteSingleChannel.
string DetermineDataTypeRefTree(string ancestry)
Determine the ancestry tree for the specified neurodata type definition.
ancestry A list of all previously ancester dataTypes a specified neurodata type definition string json
References DetermineDataTypeRefTree.
Referenced by DetermineDataTypeRefTree, NWB_GetTimeSeriesProperties, WriteNeuroDataType.