IPNWB_Utils.ipf
variable IsFinite(variable var)
Returns 1 if var is a finite/normal number, 0 otherwise.
variable IsNaN(variable var)
Returns 1 if var is a NaN, 0 otherwise.
variable isNull(string *str)
Returns 1 if str is null, 0 otherwise.
str must not be a SVAR
variable isEmpty(string *str)
Returns one if str is empty or null, zero otherwise.
str must not be a SVAR
variable DateTimeInUTC()
Return the seconds since Igor Pro epoch (1/1/1904) in UTC time zone.
Referenced by CA_StoreEntryIntoCache, DAP_CheckSettings, DAP_LockDevice, ED_createTextNotes, ED_createWaveNotes, GetISO8601TimeStamp, InitToplevelInfo, NWB_GetFileForExport, P_RecordUserPressure, SaveExperimentSpecial, TP_RecordTP, UploadCrashDumpsDaily, UploadLogFilesDaily.
variable IsInteger(variable var)
Returns one if var is an integer and zero otherwise.
References IsFinite.
Referenced by AFH_GetHeadstageFromActiveADC, AR_HighlightArtefactsEntry, BSP_ParseChannelSelectionControl, CreateLBNUnassocKey, DC_GenerateStimsetFingerprint, GetDecimatedWaveSize, GetISO8601TimeStamp, IsValidEpochNumber, IsValidSweepNumber, IsValidWaveVersion, LBN_SetDimensionLabels, LoadEpochTable, NumberToHex, PA_CalculatePulseInfos, PA_GeneratePulseWaveName, PA_SpikePositionsForNonVC, PA_TAAdaptAverageWave, PSQ_Chirp_CheckParam, PSQ_PB_CreateTestpulseEpochs, PSQ_PipetteInBath_CheckParam, SC_SpikeControl_CheckParam, SC_SpikeCountsQC, ST_CreateStimSet, TP_GetValuesFromTPStorage, WB_NoiseSegment, WBP_ShowFFTSpectrumIfReq.
string GetISO8601TimeStamp(variable secondsSinceIgorEpoch=defaultValue, variable numFracSecondsDigits=defaultValue, variable localTimeZone=defaultValue)
Return a string in ISO 8601 format with timezone UTC.
secondsSinceIgorEpoch [optional, defaults to number of seconds until now] Seconds since the Igor Pro epoch (1/1/1904) in UTC (or local time zone depending on localTimeZone) numFracSecondsDigits [optional, defaults to zero] Number of sub-second digits localTimeZone [optional, defaults to false] Use the local time zone instead of UTC
References ASSERT_TS, DateTimeInUTC, IsInteger.
Referenced by AddModificationTimeEntry, CA_OutputCacheStatistics, CreateCommonGroups, ED_MarkSweepStart, FFI_GetJSONTemplate, GenerateJSONTemplateForUpload, InitToplevelInfo, LOG_GenerateEntryTemplate, NWB_AppendLogFileToString, TP_StoreTP, UploadLogFiles.
variable ParseUnit(string unitWithPrefix, string *prefix, variable *numPrefix, string *unit)
Parse a simple unit with prefix into its prefix and unit.
Note: The currently allowed units are the SI base units [1] and other common derived units. And in accordance to SI definitions, "kg" is a base unit. "Simple" unit means means one unit with prefix, not e.g. "km/s". unitWithPrefix string to parse, examples are "ms" or "kHz" prefix symbol of decimal multipler of the unit, see below or [1] chapter 3 for the full list numPrefix numerical value of the decimal multiplier unit unit embed:rst:leading-asterisk * * ===== ====== =============== * Name Symbol Numerical value * ===== ====== =============== * yotta Y 1e24 * zetta Z 1e21 * exa E 1e18 * peta P 1e15 * tera T 1e12 * giga G 1e9 * mega M 1e6 * kilo k 1e3 * hecto h 1e2 * deca da 1e1 * deci d 1e-1 * centi c 1e-2 * milli m 1e-3 * micro mu 1e-6 * nano n 1e-9 * pico p 1e-12 * femto f 1e-15 * atto a 1e-18 * zepto z 1e-21 * yocto y 1e-24 * ===== ====== =============== * * [1]: 8th edition of the SI Brochure (2014), http://www.bipm.org/en/publications/si-brochure
References ASSERT_TS, GetDecimalMultiplierValue, isEmpty.
Referenced by AddTimeSeriesUnitAndRes.
variable GetDecimalMultiplierValue(string prefix)
Return the numerical value of a SI decimal multiplier.
ParseUnit
References ASSERT_TS, isEmpty, ROWS.
Referenced by ParseUnit.
variable IsTextWave(wave wv)
Return 1 if the wave is a text wave, zero otherwise.
Referenced by DEBUGPRINT, ED_AddEntriesToLabnotebook, ED_AddEntriesToResults, ED_AddEntryToLabnotebook, ED_GetHeadstageContingency, ExtractLogbookSlice, FindIndizes, GetLastSetting, GetLastSettingChannelInternal, GetLastSettingNoCache, GetLastSettingTextIndep, GetLastSweepWithSettingText, GetLBIndexCache, GetLBNidCache, GetLBRowCache, GetSweepsWithSetting, LBV_AddTraceToLBGraph, LoadSourceAttribute, ReadTextAttribute, ReadTextAttributeAsString, ReadTextDataSet, ReadTextDataSetAsString, SC_AddPulseRegionLBNEntries, ST_GetStimsetParameterAsString, ST_SetStimsetParameter, TextWaveToList, TS_GetNewestFromThreadQueueMult, WB_AddAnalysisParameterIntoWPT.
variable IsNumericWave(wave wv)
Return 1 if the wave is a numeric wave, zero otherwise.
Referenced by DEBUGPRINT, ED_FindIndizesAndRedimension, FindRange, GetLastSettingChannelInternal, GetLastSweepWithSetting, GetLBIndexCache, GetLBRowCache, PSQ_AddLabnotebookEntriesToJSON, ReadAttributeAsNumber, ReadDataSetAsNumber, SC_AddPulseRegionLBNEntries, ST_GetStimsetParameterAsVariable, ST_SetStimsetParameter.
string RemovePrefixFromListItem(string prefix, string list, string listSep=defaultValue)
Remove a string prefix from each list item and return the new list.
Referenced by ReadDevices, SC_SpikeCountsQC, ST_GetStimsetList.
wave MakeWaveFree(wave wv)
Turn a persistent wave into a free wave.
Referenced by AR_ComputeRanges, ExtractLogbookSlice, WB_FillWaveFromFormula.
string UniqueWaveName(dfref dfr, string baseName)
Returns a wave name not used in the given datafolder.
Basically a datafolder aware version of UniqueName for datafolders dfr datafolder reference where the new datafolder should be created baseName first part of the wave name, might be shorted due to Igor Pro limitations
References ASSERT_TS, DataFolderExistsDFR, DEBUGPRINT, isEmpty, MAX_OBJECT_NAME_LENGTH_IN_BYTES.
Referenced by SBE_ExportSweepBrowser.
variable DataFolderExistsDFR(dfref dfr)
Checks if the datafolder referenced by dfr exists.
Unlike DataFolderExists() a dfref pointing to an empty ("") dataFolder is considered non-existing here. one if dfr is valid and references an existing or free datafolder, zero otherwise Taken from http://www.igorexchange.com/node/2055
References ASSERT_TS.
Referenced by AB_LoadDataWrapper, BSP_GetFolder, BSP_SetFolder, CreateTiledChannelGraph, GetAnaFuncDashboardColorWave, GetAnaFuncDashboardHelpWave, GetAnaFuncDashboardInfoWave, GetAnaFuncDashboardListWave, GetAnaFuncDashboardSelWave, GetArtefactRemovalDataWave, GetArtefactRemovalListWave, GetChannelSelectionWave, GetDAQDataSingleColumnWaves, GetNVARAsString, GetOverlaySweepHeadstageRemoval, GetOverlaySweepSelectionChoices, GetOverlaySweepsListSelWave, GetOverlaySweepsListWave, GetPulseAverageDisplayMapping, GetPulseAverageProperties, GetPulseAveragePropertiesWaves, GetPulseAverageSetImageWave, GetPulseAverageSetIndizes, GetPulseAverageWave, GetPulseAverageWaveNoteWave, GetSingleSweepFolderAsString, GetSVARAsString, GetSweepBrowserMap, ID_GetFolder, KillOrMoveToTrash, LBV_PopupExtGetTPStorageKeys, LBV_SwitchLBGraphXAxis, MoveToTrash, NWB_LoadLabNoteBook, OVS_GetFolder, PA_GenerateAllPulseWaves, PA_GetPulseInfos, PA_PreProcessPulses, PA_SerializeSettings, RemoveTracesFromGraph, SB_UpdateSweepPlot, SWS_DeleteDataWaves, TFH_FifoLoop, TS_ThreadGroupGetVariable, TS_ThreadGroupPutDFR, UniqueWaveName, UpgradeWaveLocationAndGetIt.
string GetBaseName(string filePathWithSuffix, string sep=defaultValue)
Return the base name of the file.
Given path/file.suffix this gives file. filePathWithSuffix full path sep [optional, defaults to ":"] character separating the path components
Referenced by AB_LoadDataWrapper, AnalyseChannelName, LoadStimulus, LoadTimeseries, SB_GetChannelInfoFromGraph, SB_GetSweepList.
string GetFileSuffix(string filePathWithSuffix, string sep=defaultValue)
Return the file extension (suffix)
Given path/file.suffix this gives suffix. filePathWithSuffix full path sep [optional, defaults to ":"] character separating the path components
Referenced by AB_AddMapEntry, AB_LoadDataWrapper, AB_ReExport, BeforeFileOpenHook, SB_GetSweepList.
string GetFolder(string filePathWithSuffix, string sep=defaultValue)
Return the folder of the file.
Given /path/file.suffix this gives path/. filePathWithSuffix full path sep [optional, defaults to ":"] character separating the path components
Referenced by AB_LoadDataWrapper, AB_LoadWave, AB_ReExport, BSP_UpdateHelpNotebook, CONF_Position_MCC_Win, DAP_LoadBuiltinStimsets, GetSavePath, NWB_LoadCustomWave, PerformMiesTasks, SI_StoreMinSampIntOnDisk, SpecificationsDiscLocation, WBP_ButtonProc_OpenAnaFuncs.
string GetFile(string filePathWithSuffix, string sep=defaultValue)
Return the filename with extension.
Given path/file.suffix this gives file.suffix. filePathWithSuffix full path sep [optional, defaults to ":"] character separating the path components
Referenced by AB_ReExport, CONF_OpenConfigInNotebook, DND_FetchAsset, DP_FillDebugPanelWaves, FilterLogfileByDate, H5_WriteDatasetLowLevel.
variable ParseISO8601TimeStamp(string timestamp)
Parse a ISO8601 timestamp, e.g. created by GetISO8601TimeStamp(), and returns the number of seconds, including fractional parts, since Igor Pro epoch (1/1/1904) in UTC time zone.
Accepts also the following specialities: no UTC timezone specifier (UTC timezone is still used) /T between date and time fractional seconds ,/. as decimal separator
References ASSERT_TS, IsEmpty.
Referenced by DAP_CheckSettings, FilterByDate, NWB_GetStartTimeOfSweep, NWB_ReadSessionStartTime, ReadTopLevelInfo, UploadCrashDumpsDaily, UploadLogFilesDaily.
string TextWaveToList(WaveText txtWave, string sep)
Convert a text wave to string list.
References ASSERT_TS, COLS, IsTextWave, ROWS.
Referenced by AB_SortConfigSweeps, AI_OpenMCCs, AR_GetHighlightTraces, CHI_CheckInstallation, CONF_WindowToJSON, DEBUGPRINT, EP_EpochWaveToStr, FilterLogfileByDate, GetDandiDialogWave, GetLBNumericalDescription, ID_GetPopupEntries, LBV_AddTraceToLBGraphTPStorage, LBV_GetAllDevicesForExperiment, OVS_GetSweepSelectionChoices, PA_LayoutGraphs, ReadTextAttributeAsList, SBE_GetSourceGraphADTraces, SC_AddPulseRegionLBNEntries, SC_GetSpikeNumbersAndPositions, SC_SpikeCountsQC, SC_SpikePositionQC, TimeAlignGetAllTraces, TUD_SetUserDataFromWaves, WB_AddAnalysisParameterIntoWPT, WBP_ListBoxProc_AnalysisParams.
string ResolveAlias(string path, string pathName=defaultValue)
Recursively resolve shortcuts to files/directories.
full path or an empty string if the file does not exist or the shortcut points to a non existing file/folder
References ResolveAlias.
Referenced by FileExists, FolderExists, ResolveAlias.
variable FileExists(string filepath)
Check wether the given path points to an existing file.
Resolves shortcuts and symlinks recursively.
References ResolveAlias.
Referenced by AB_LoadDataWrapper, AI_GetMCCWinFilePath, CalcHashForFile, CONF_AddConfigFileUserData, CONF_Position_MCC_Win, CONF_RestoreDAEphys, CreateMiesVersion, MEN_OpenMIESLogFile, MEN_OpenZeroMQXOPLogFile, NWB_AppendLogFileToString, NWB_ExportAllData, NWB_GetFileForExport, PostLoadNextExperiment, PS_FixPackageLocation, UploadLogFiles, WBP_ButtonProc_OpenAnaFuncs.
variable FolderExists(string folderpath)
Check wether the given path points to an existing folder.
References ResolveAlias.
Referenced by AB_LoadDataWrapper, CONF_GetSettingsPath, CreateMiesVersion, PerformMiesTasks, PS_Initialize.
string AddPrefixToEachListItem(string prefix, string list)
Add a string prefix to each list item and return the new list.
Referenced by IH_KillStimSets, PA_ShowImage, ReadAcquisition, ReadStimulus, TP_StoreTP.
variable NewRandomSeed()
Initializes the random number generator with a new seed between (0,1] The time base is assumed to be at least 0.1 microsecond precise, so a new seed is available every 0.1 microsecond.
Usage example for the case that one needs n non reproducible random numbers. Whenever the following code block is executed a new seed is set, resulting in a different series of numbers embed:rst:leading-asterisk * .. code-block:: igorpro * * Make/D/N=(n) newRandoms * NewRandomSeed() // Initialize random number series with a new seed * newRandoms[] = GetReproducibleRandom() // Get n randoms from the new series * *
Referenced by DAP_LockDevice, SCOPE_UpdateOscilloscopeData, WB_InitializeSeed, WBP_ButtonProc_NewSeed.
variable GetReproducibleRandom()
Return a random value in the range (0,1] which can be used as a seed for SetRandomSeed
Return a reproducible random number depending on the RNG seed.
References NOISE_GEN_MERSENNE_TWISTER.
Referenced by DAP_LockDevice, GenerateRFC4122UUID, GetNextRandomNumberForDevice, WB_InitializeSeed, WBP_ButtonProc_NewSeed.
string GenerateRFC4122UUID()
Generate a version 4 UUID according to https://tools.ietf.org/html/rfc4122.
embed:rst:leading-asterisk * .. code-block:: text * * 4.4. Algorithms for Creating a UUID from Truly Random or * Pseudo-Random Numbers * * The version 4 UUID is meant for generating UUIDs from truly-random or * pseudo-random numbers. * * The algorithm is as follows: * * o Set the two most significant bits (bits 6 and 7) of the * clock_seq_hi_and_reserved to zero and one, respectively. * * o Set the four most significant bits (bits 12 through 15) of the * time_hi_and_version field to the 4-bit version number from * Section 4.1.3. * * o Set all the other bits to randomly (or pseudo-randomly) chosen * values. * * See Section 4.5 for a discussion on random numbers. * * [...] * * In the absence of explicit application or presentation protocol * specification to the contrary, a UUID is encoded as a 128-bit object, * as follows: * * The fields are encoded as 16 octets, with the sizes and order of the * fields defined above, and with each field encoded with the Most * Significant Byte first (known as network byte order). Note that the * field names, particularly for multiplexed fields, follow historical * practice. * * 0 1 2 3 * 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 * +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ * | time_low | * +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ * | time_mid | time_hi_and_version | * +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ * |clk_seq_hi_res | clk_seq_low | node (0-1) | * +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ * | node (2-5) | * +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ * * [...] * * 4.1.3. Version * * The version number is in the most significant 4 bits of the time * stamp (bits 4 through 7 of the time_hi_and_version field). * * The following table lists the currently-defined versions for this * UUID variant. * * Msb0 Msb1 Msb2 Msb3 Version Description * * 0 0 0 1 1 The time-based version * specified in this document. * * 0 0 1 0 2 DCE Security version, with * embedded POSIX UIDs. * * 0 0 1 1 3 The name-based version * specified in this document * that uses MD5 hashing. * * 0 1 0 0 4 The randomly or pseudo- * randomly generated version * specified in this document. * * 0 1 0 1 5 The name-based version * specified in this document * that uses SHA-1 hashing. * * The version is more accurately a sub-type; again, we retain the term * for compatibility. * * See also https://www.rfc-editor.org/errata/eid3546 and https://www.rfc-editor.org/errata/eid1957 for some clarifications.
References GetReproducibleRandom, HexToBinary, num2strHighPrec.
Referenced by UploadLogFiles, WriteNeuroDataType.
variable HexToNumber(string ch)
Convert a hexadecimal character into a number.
References ASSERT_TS.
Referenced by HexToBinary.
string NumberToHex(variable var)
Convert a number into hexadecimal.
References ASSERT_TS, IsInteger.
wave HexToBinary(string str)
Convert a string in hex format to an unsigned binary wave.
This function works on a byte level so it does not care about endianess.
References ASSERT_TS, HexToNumber.
Referenced by GenerateRFC4122UUID.
string num2strHighPrec(variable val, variable precision=defaultValue)
Converts a number to a string with specified precision (digits after decimal dot). This function is an extension for the regular num2str that is limited to 5 digits. Input numbers are rounded using the "round-half-to-even" rule to the given precision. The default precision is 5. If val is complex only the real part is converted to a string.
val number that should be converted to a string precision [optional, default 5] number of precision digits after the decimal dot using "round-half-to-even" rounding rule. Precision must be in the range 0 to 15. string with textual number representation
References ASSERT_TS.
Referenced by ED_createTextNotes, EP_AdaptEpochInfo, EP_AddEpoch, EP_SortEpochs, GenerateRFC4122UUID.
variable ClearRTError()
Helper function for try/catch with AbortOnRTE.
Not clearing the RTE before calling AbortOnRTE will always trigger the RTE no matter what you do in that line. Usage: embed:rst:leading-asterisk * .. code-block:: igorpro * * try * ClearRTError() * myFunc(); AbortOnRTE * catch * err = GetRTError(1) * endtry * *
Referenced by AB_LoadDataWrapper, AB_LoadLabNotebookFromNWB, AFH_CheckAnalysisParameter, AFH_GetHelpForAnalysisParameter, AFM_CallAnalysisFunctions, AfterCompiledHook, AI_UpdateAmpModel, AppendToEpochTable, CalculateAverage, CONF_AllWindowsToJSON, CONF_ControlToJSON, CONF_JSONToWindow, CONF_ParseJSON, CONF_RestoreDAEphys, CONF_RestoreWindow, CONF_SaveDAEphys, CONF_SaveWindow, CONF_WindowToJSON, DAP_CheckProc_AD, DAP_CheckProc_ClampMode, DAP_CheckProc_HedstgeChck, DAP_DAorTTLCheckProc, DAP_WindowHook, DB_WindowHook, DQM_FIFOMonitor, DQM_StartDAQMultiDevice, DQS_StartDAQSingleDevice, FFI_Publish, IH_Cleanup, IVS_finishGigOhmSealQCCheck, IVS_SaveExperiment, LoadEpochTable, LoadSpecification, PerformMiesTasks, ProcessCurrentExperiment, PS_ApplyStoredWindowCoordinate, PS_SerializeSettings, PS_StoreWindowCoordinates, PSQ_DAScale, RA_Counter, SWS_AfterSweepDataChangeHook, TP_AutoFitBaseline, TP_FitResistance, TPM_BkrdTPFuncMD, TPM_StartTPMultiDeviceLow, TPS_StartTestPulseSingleDevice, UploadCrashDumpsDaily, UploadLogFilesDaily.
string NormalizeToEOL(string str, string eol)
Normalize the line endings in the given string to either classic Mac OS/Igor Pro EOLs (\r) or Unix EOLs (\n)
Referenced by CreateMiesVersion, DC_PrepareLBNEntries, ED_createTextNotes, FilterLogfileByDate, GetMIESVersionAsString, NWB_AppendIgorHistoryAndLogFile, NWB_AppendLogFileToString, SetControlInEvent, WriteSingleChannel.
string GetStackTrace(string prefix=defaultValue)
Return a nicely formatted multiline stacktrace.
Referenced by ASSERT_TS, BUG, BUG_TS, DEBUGPRINTSTACKINFO.
string GetExperimentName()
Referenced by ASSERT_TS, DB_UpdateSweepPlot, DEBUGPRINTSTACKINFO, IgorBeforeNewHook, IgorBeforeQuitHook, LBV_GetExperiments, LOG_GenerateEntryTemplate, NWB_ExportWithDialog, NWB_GetFileForExport, OVS_GetSweepAndExperiment, ProcessCurrentExperiment, SaveExperimentSpecial, SaveHistoryLog.
string GetExperimentFileType()
Return the experiment file type.
Referenced by ASSERT_TS.
string GetIgorProVersion()
Return the Igor Pro version string.
Referenced by ASSERT_TS, DC_PrepareLBNEntries, NWB_AddGeneratorString.
string GetWindowsPath(string path)
Return the path converted to a windows style path.
Referenced by AB_ReExport, AppendToEpochTable, CONF_Position_MCC_Win, LoadEpochTable.
variable SetEpochsDimensionLabels(wave wv)
Referenced by GetEpochsWaveInternal, NWB_FetchEpochs.
wave GetUniqueEntries(wave wv, variable caseSensitive=defaultValue)
Returns an unsorted free wave with all unique entries from wv neglecting NaN/Inf.
uses built-in igor function FindDuplicates. Entries are deleted from left to right.
Referenced by AB_GetSweepsFromLabNotebook, AD_SelectResult, AI_GetMCCSerialNumbers, CheckAllDimensionLabels, CHI_CheckInstallation, CONF_WindowToJSON, GetEpochsWaveInternal, GetPopupMenuRates, GetSweepsWithSetting, GetTimeseriesProperties, GetUserdataKeys, LayoutGraph, OVS_GetSweepSelectionChoices, PA_GetUniqueHeadstages, PA_LayoutGraphs, SB_GetSweepList, WBP_ListControlsPerStimulusType.
string GetUniqueTextEntriesFromList(string list, string sep=defaultValue, variable caseSensitive=defaultValue)
Convenience wrapper around GetUniqueTextEntries() for string lists.
Referenced by DB_GetAllDevicesWithData, GetSizeOfAllWavesInExperiment, LBV_SwitchLBGraphXAxis, MSQ_FastRheoEst, NWB_LoadAllStimsets, SC_SpikeControl, WB_StimsetFamilyNames, WB_StimsetRecursionForList.
static wave GetUniqueTextEntries(WaveText wv, variable caseSensitive=defaultValue)
Search and Remove Duplicates from Text Wave wv.
Duplicates are removed from left to right wv text wave reference caseSensitive [optional] Indicates whether comparison should be case sensitive. defaults to True free wave with unique entries
variable SetNumberInWaveNote(wave wv, string key, variable val, string format=defaultValue)
Updates the numeric value of key found in the wave note to val
wv wave key key of the Key/Value pair val value of the Key/Value pair format [optional] printf compatible format string to set the conversion to string for val The expected wave note format is: key1:val1;key2:val2;
Referenced by AB_AddMapEntry, AB_ClearAnalysisFolder, AB_FillListWave, AB_LoadStoredTestpulsesFromNWB, AB_LoadSweepFromNWBgeneric, AB_LoadSweepsFromExperiment, AB_RemoveMapEntry, AB_SaveDeviceList, AB_StoreChannelsBySweep, AD_FillWaves, AD_Update, AR_ComputeRanges, AS_RecordStateTransition, CA_MakeSpaceForNewEntry, CalculateAverage, CreateTiledChannelGraph, DAP_SweepRollback, DAP_UnlockDevice, DC_MakeHelperWaves, DQ_ApplyAutoBias, ED_createTextNotes, ED_createWaveNotes, ExtractLogbookSlice, FitResistance, GetAcqStateTracking, GetActiveDevicesTPMD, GetAnaFuncDashboardListWave, GetAnalysisBrowserMap, GetAnalysisChannelAcqWave, GetAnalysisChannelStimWave, GetAnalysisChannelStorage, GetAnalysisChannelSweepWave, GetAnalysisDeviceWave, GetAnalysisFuncDAScaleDeltaV, GetAxisLabelCacheWave, GetCacheKeyWave, GetCacheStatsWave, GetCacheValueWave, GetElapsedTimeWave, GetEpochsWaveInternal, GetExperimentBrowserGUIList, GetGraphUserData, GetLBIndexCache, GetLBNidCache, GetLBNumericalValues, GetLBRowCache, GetLBTextualValues, GetNumericalResultsValues, GetOverlaySweepSelectionChoices, GetPulseAverageProperties, GetPulseAverageSetImageWave, GetPulseAverageSetIndizes, GetSerialExecutionBuffer, GetStoredTestPulseWave, GetSweepBrowserMap, GetTextualResultsValues, GetTPResultsBuffer, GetTPStorage, InitBufferedDrawInfo, LoadEpochTable, MeasureMidSweepTiming_V3, OVS_BeginIncrementalUpdate, OVS_UpdatePanel, OVS_UpdateSweepSelectionChoices, P_AddSealedEntryToTPStorage, PA_ApplyPulseSortingOrder, PA_CopySetIndiceSizeDispRestart, PA_CreateAndFillPulseWaveIfReq, PA_GenerateAllPulseWaves, PA_GetFeaturePosition, PA_MarkFailedPulses, PA_PulseHasFailed, PA_SetDiagonalityNote, PA_SetFeaturePosition, PA_ShowImage, PA_StoreMaxAndUnitsInWaveNote, PA_TagSearchedPulses, PA_UpdateIndiceNotesImpl, PA_UpdateMinAndMax, PA_ZeroWave, PSQ_CR_DetermineBoundsActionFromState, PSQ_CR_DetermineBoundsActionHelper, SB_AddToSweepBrowser, SetWaveVersion, TestOverrideActive, TimeAlignmentIfReq, TP_AutoAmplitudeAndBaseline, TP_CalculateAverage, TP_RecordTP, TP_SetupCommon, TP_StoreTP, TPM_AddDevice, TPM_RemoveDevice, TUD_AddTrace, TUD_ClearImpl, TUD_GetIndexJSON, TUD_RemoveTrace, UpgradeLabNotebook, WBP_ListControlsPerStimulusType, ZeroWave.
variable GetNumberFromWaveNote(wave wv, string key)
Returns the numeric value of key found in the wave note, returns NaN if it could not be found.
The expected wave note format is: key1:val1;key2:val2;
Referenced by AB_AddFile, AB_AddMapEntry, AB_ButtonProc_ResaveAsNWB, AB_FillListWave, AB_GetAllExperiments, AB_LoadFile, AB_LoadSweepFromNWB, AB_RemoveMapEntry, AB_ScanFolder, AB_StoreChannelsBySweep, AD_FillWaves, AR_ComputeRanges, AS_GenerateEncounteredTransitions, AS_RecordStateTransition, BeforeFileOpenHook, BSP_ButtonProc_RestoreData, CA_MakeSpaceForNewEntry, CA_OutputCacheStatistics, CalculateAverage, CreateTiledChannelGraph, DAP_SweepRollback, DQ_ApplyAutoBias, ED_FindIndizesAndRedimension, ExtractLogbookSlice, FFI_ReturnTPValues, FitResistance, GetCacheStatsWave, GetLBIndexCache, GetLBNidCache, GetLBRowCache, GetWaveVersion, LBV_AddTagsForTextualLBNEntries, LBV_GetAllDevicesForExperiment, LoadEpochTable, NWB_AppendStoredTestPulses, OVS_EndIncrementalUpdate, OVS_UpdateSweepSelectionChoices, P_AddSealedEntryToTPStorage, P_RecordUserPressure, P_UpdateSSRSlopeAndSSR, P_UpdateTPStorage, PA_AddColorScales, PA_ApplyPulseSortingOrder, PA_CopySetIndiceSizeDispRestart, PA_CreateAndFillPulseWaveIfReq, PA_DrawScaleBars, PA_GenerateAllPulseWaves, PA_GetFeaturePosition, PA_GetMinAndMax, PA_GetSetWaves_TS, PA_InitPASIInParts, PA_MarkFailedPulses, PA_PulseHasFailed, PA_ResetWavesIfRequired, PA_SetFeaturePosition, PA_ShowImage, PA_ShowPulses, PA_ZeroWave, PSQ_CR_DetermineBoundsActionHelper, PSQ_GetFinalDAScaleFake, SB_AddToSweepBrowser, SB_GetChannelInfoFromGraph, SB_GetListOfExperiments, SB_GetLogbookWave, SB_GetPlainSweepList, SB_GetSweepList, SC_FilterPulses, SC_GetPulseIndizes, SC_GetSpikeNumbersAndPositions, SCOPE_GetTPTopAxisStart, SCOPE_ITC_UpdateOscilloscope, SCOPE_NI_UpdateOscilloscope, TestOverrideActive, TimeAlignmentIfReq, TP_AutoAmplitudeAndBaseline, TP_CalculateAverage, TP_GetStoredTPs, TP_GetValuesFromTPStorage, TP_RecordTP, TP_SetupCommon, TP_SplitStoredTestPulseWave, TP_StoreTP, TP_TestPulseHasCycled, TP_UpdateHoldCmdInTPStorage, TPM_AddDevice, TPM_BkrdTPFuncMD, TPM_HasActiveDevices, TPM_RemoveDevice, TUD_AddTrace, TUD_ClearImpl, TUD_GetIndexJSON, TUD_GetTraceCount, TUD_GetUserDataAsWave, TUD_RegenerateJSONIndex, TUD_RemoveTrace, WBP_ListControlsPerStimulusType, ZeroWave.