MIES_BrowserSettingsPanel.ipf
const string EXT_PANEL_SUBWINDOW
Referenced by BSP_GetPanel.
const string EXT_PANEL_SWEEPCONTROL
Referenced by BSP_GetSweepControlsPanel.
const string EXT_PANEL_SF_FORMULA
Referenced by BSP_GetSFFormula.
const string EXT_PANEL_SF_JSON
Referenced by BSP_GetSFJSON.
const string EXT_PANEL_SF_HELP
Referenced by BSP_GetSFHELP.
const double BROWSERSETTINGS_PANEL_VERSION
Referenced by BSP_DynamicStartupSettings.
const string BROWSERTYPE_DATABROWSER
Referenced by BSP_IsDataBrowser, BSP_SetBrowserType, BSP_SetDataBrowser.
const string BROWSERTYPE_SWEEPBROWSER
Referenced by BSP_IsSweepBrowser, BSP_SetBrowserType, BSP_SetSweepBrowser.
const string BROWSERSETTINGS_CONTROLS_DATABROWSER
exclusive controls that are enabled/disabled for the specific browser window type
Referenced by BSP_DynamicStartupSettings.
const string BROWSERSETTINGS_AXES_SCALING_CHECKBOXES
Referenced by BSP_CheckProc_ScaleAxes.
const string SWEEPCONTROL_CONTROLS_DATABROWSER
exclusive controls that are enabled/disabled for the specific browser window type
Referenced by BSP_DynamicSweepControls.
const string SWEEPCONTROL_CONTROLS_SWEEPBROWSER
Referenced by BSP_DynamicSweepControls.
string BSP_GetPanel(string mainPanel)
return the name of the external panel depending on main window name
mainPanel mainWindow panel name
References EXT_PANEL_SUBWINDOW, GetMainWindow.
Referenced by AD_SelectResult, AD_Update, AR_HandleRanges, AR_HighlightArtefactsEntry, AR_UpdateListBoxWave, BSP_AxisScalingLevelCross, BSP_BindListBoxWaves, BSP_ButtonProc_RestoreData, BSP_CheckProc_ChangedSetting, BSP_CheckProc_OverlaySweeps, BSP_CheckProc_ScaleAxes, BSP_DynamicStartupSettings, BSP_GatherTiledGraphSettings, BSP_GetNotebookSubWindow, BSP_GetSFFormula, BSP_GetSFHELP, BSP_GetSFJSON, BSP_InitMainCheckboxes, BSP_IsActive, BSP_ScaleAxes, BSP_SetControlStatus, BSP_SweepFormulaHook, BSP_UnHideSettingsPanel, BSP_UnsetDynamicStartupSettingsOfDataBrowser, BSP_UpdateSweepNote, DB_LockToDevice, DB_OpenDataBrowser, DB_ResetAndStoreCurrentDBPanel, DB_UpdateToLastSweep, InitPostPlotSettings, OVS_ChangeSweepSelection, OVS_GetHeadstageRemoval, OVS_IgnoreHeadstageInOverlay, OVS_UpdatePanel, PA_DeconvGatherSettings, PA_GatherSettings, PSQ_PipetteInBath, SC_SpikeControl, ScreenShotsForDataBrowser, TimeAlignCursorMovedHook, TimeAlignHandleCursorDisplay, TimeAlignUpdateControls, UpdateSettingsPanel, WB_OpenStimulusSetInWaveBuilder.
string BSP_GetNotebookSubWindow(string win)
return the name of the WaveNote Display inside BSP
References BSP_GetPanel.
Referenced by BSP_UpdateSweepNote, DB_UpdateSweepPlot, SB_UpdateSweepPlot.
string BSP_GetSweepControlsPanel(string mainPanel)
return the name of the bottom Panel
mainPanel mainWindow panel name
References EXT_PANEL_SWEEPCONTROL, GetMainWindow.
Referenced by AB_ButtonProc_LoadSweeps, BSP_ButtonProc_ChangeSweep, BSP_DynamicSweepControls, BSP_SweepsAndMouseWheel, BSP_UnHideSweepControls, BSP_UnsetDynamicSweepControlOfDataBrowser, BSP_UpdateSweepControls, BSP_UpdateSweepNote, DB_ResetAndStoreCurrentDBPanel, DB_UpdateLastSweepControls, DB_UpdateSweepPlot, DB_UpdateToLastSweep, LBV_LimitXRangeToSelected, OVS_UpdatePanel, PSQ_PipetteInBath, SB_UpdateSweepPlot, SC_SpikeControl, ScreenShotsForDataBrowser, SWS_AfterSweepDataChangeHook.
string BSP_GetSFFormula(string mainPanel)
References BSP_GetPanel, EXT_PANEL_SF_FORMULA.
Referenced by DB_ResetAndStoreCurrentDBPanel, PSQ_PipetteInBath.
string BSP_GetSFJSON(string mainPanel)
References BSP_GetPanel, EXT_PANEL_SF_JSON.
Referenced by DB_ResetAndStoreCurrentDBPanel.
string BSP_GetSFHELP(string mainPanel)
References BSP_GetPanel, EXT_PANEL_SF_HELP.
Referenced by BSP_UpdateHelpNotebook.
variable BSP_InitPanel(string mainPanel)
Inits controls of BrowserSettings side Panel.
mainPanel mainWindow panel name
References BSP_DynamicSettingsHistory, BSP_DynamicStartupSettings, BSP_DynamicSweepControls, LBV_GetLabNoteBookGraph, TUD_Init.
Referenced by DB_OpenDataBrowser, DB_ResetAndStoreCurrentDBPanel, SB_OpenSweepBrowser.
variable BSP_UnHidePanel(string mainPanel)
UnHides BrowserSettings side Panel.
mainPanel mainWindow panel name
References BSP_MainPanelButtonToggle, BSP_UnHideSettingsPanel, BSP_UnHideSweepControls.
Referenced by BSP_ButtonProc_Panel.
variable BSP_UnHideSettingsPanel(string mainPanel)
References BSP_GetPanel, DATA_SWEEP_BROWSER_PANEL_VERSION, DoAbortNow, HasPanelLatestVersion.
Referenced by BSP_UnHidePanel.
variable BSP_UnHideSweepControls(string mainPanel)
open bottom Panel
mainPanel mainWindow panel name
References ASSERT, BSP_GetSweepControlsPanel, GetMainWindow, WindowExists.
Referenced by BSP_UnHidePanel.
static variable BSP_DynamicSweepControls(string mainPanel)
dynamic settings for bottom panel at initialization
mainPanel mainWindow panel name
References ASSERT, BSP_GetSweepControlsPanel, BSP_IsDataBrowser, DisableControls, EnableControls, SetControlProcedures, SetSetVariable, SetSetVariableLimits, SetValDisplay, SWEEPCONTROL_CONTROLS_DATABROWSER, SWEEPCONTROL_CONTROLS_SWEEPBROWSER, WindowExists.
Referenced by BSP_InitPanel.
variable BSP_UnsetDynamicSweepControlOfDataBrowser(string mainPanel)
Unsets all control properties that are set in BSP_DynamicSweepControls for DataBrowser type.
mainPanel mainWindow panel name
References ASSERT, BSP_GetSweepControlsPanel, BSP_IsDataBrowser, WindowExists.
Referenced by DB_ResetAndStoreCurrentDBPanel.
variable BSP_DynamicStartupSettings(string mainPanel)
dynamic settings for panel initialization
mainPanel mainWindow panel name
References AddVersionToPanel, BROWSERSETTINGS_CONTROLS_DATABROWSER, BROWSERSETTINGS_PANEL_VERSION, BSP_BindListBoxWaves, BSP_GetPanel, BSP_HasBoundDevice, BSP_InitMainCheckboxes, BSP_IsDataBrowser, BSP_UpdateHelpNotebook, DisableControls, EnableControls, LBV_GetSettingsHistoryPanel, NONE, PS_InitCoordinates, SetPopupMenuIndex, SetPopupMenuVal.
Referenced by BSP_InitPanel, DB_LockToDevice.
variable BSP_SweepFormulaHook(WMWinHookStruct *s)
Hook function for the Sweep Formula Notebook.
References BSP_GetPanel, GetMainWindow, PGC_SetAndActivateControl, SF_IsActive.
variable BSP_UnsetDynamicStartupSettingsOfDataBrowser(string mainPanel)
Unsets all control properties that are set in BSP_DynamicStartupSettings for DataBrowser type.
mainPanel mainWindow panel name
References ASSERT, BSP_GetPanel, BSP_IsDataBrowser, EnableControls, LBV_GetSettingsHistoryPanel, NONE, SetPopupMenuVal, WindowExists.
Referenced by DB_LockToDevice, DB_ResetAndStoreCurrentDBPanel.
variable BSP_BindListBoxWaves(string win)
References ASSERT, BSP_ChannelSelectionWaveToGUI, BSP_GetChannelSelectionWave, BSP_GetFolder, BSP_GetPanel, BSP_HasBoundDevice, BSP_IsDataBrowser, GetAnaFuncDashboardColorWave, GetAnaFuncDashboardHelpWave, GetAnaFuncDashboardListWave, GetArtefactRemovalListWave, GetMainWindow, GetOverlaySweepsListSelWave, GetOverlaySweepsListWave, MIES_BSP_PANEL_FOLDER, SetSetVariableString, SetValDisplay.
Referenced by BSP_DynamicStartupSettings.
wave BSP_GetChannelSelectionWave(string win)
Get the channel selection wave.
win name of external panel or main window channel selection wave
References BSP_GetFolder, GetChannelSelectionWave, MIES_BSP_PANEL_FOLDER.
Referenced by BSP_BindListBoxWaves, BSP_FetchSelectedChannels, BSP_GUIToChannelSelectionWave, LBV_AddTraceToLBGraphTPStorage.
dfref BSP_GetFolder(string win, string MIES_BSP_FOLDER_TYPE, variable versionCheck=defaultValue)
get a FOLDER property from the specified panel
win name of external panel or main window MIES_BSP_FOLDER_TYPE see the FOLDER constants in this file versionCheck [optional, defaults to true] abort on outdated window version DFR to specified folder. No check for invalid folders
References ASSERT, DATA_SWEEP_BROWSER_PANEL_VERSION, DataFolderExistsDFR, DoAbortNow, GetMainWindow, HasPanelLatestVersion.
Referenced by AD_PlotBounds, AD_SelectResult, AD_Update, AR_GetFolder, AR_GetSweepFolder, BSP_BindListBoxWaves, BSP_GetChannelSelectionWave, BSP_GetFormulaGraph, DB_WindowHook, InitPostPlotSettings, OVS_BeginIncrementalUpdate, OVS_EndIncrementalUpdate, OVS_GetFolder, OVS_GetSweepAndExperiment, OVS_UpdatePanel, PA_GatherSettings, SB_GetSweepBrowserFolder, SB_OpenSweepBrowser, SC_GetPulseAveragePropertiesWaves.
variable BSP_SetFolder(string win, dfref dfr, string MIES_BSP_FOLDER_TYPE)
set a FOLDER property at the specified panel
win name of external panel or main window dfr DataFolder Reference to the folder MIES_BSP_FOLDER_TYPE see the FOLDER constants in this file
References ASSERT, DataFolderExistsDFR, GetMainWindow, WindowExists.
Referenced by AR_SetSweepFolder, DB_SetUserData, SB_SetUserData.
string BSP_GetDevice(string win)
get the assigned DEVICE property from the main panel
win name of external panel or main window device as string
References ASSERT, GetDAQDevicesFolder, GetMainWindow, IsEmpty, MIES_BSP_DEVICE, WindowExists.
Referenced by AD_FillWaves, BSP_ButtonProc_RestoreData, BSP_GetLogbookWave, BSP_HasBoundDevice, BSP_UpdateSweepNote, DB_AddSweepToGraph, DB_FindDataBrowser, DB_GetLBNWave, DB_GetPlainSweepList, DB_SplitSweepsIfReq, DB_UpdateSweepPlot, LBV_GetAllDevicesForExperiment, LBV_GetTPStorageLocation.
string BSP_SetDevice(string win, string device)
set DEVICE property to the userdata of the main panel
win name of external panel or main window device bound device as string
References ASSERT, BSP_IsDataBrowser, GetMainWindow, WindowExists.
Referenced by DB_SetUserData.
string BSP_GetBrowserType(string win)
get the MIES Browser Type
win name of external panel or main window D for DataBrowser or S for SweepBrowser
References ASSERT, GetMainWindow, MIES_BSP_BROWSER, WindowExists.
Referenced by AD_UpdateAllDatabrowser, BSP_IsDataBrowser, BSP_IsSweepBrowser.
static string BSP_SetBrowserType(string win, string type)
set DEVICE property to the userdata of the main panel
win name of external panel or main window type One of BROWSERTYPE_DATABROWSER or BROWSERTYPE_SWEEPBROWSER
References ASSERT, BROWSERTYPE_DATABROWSER, BROWSERTYPE_SWEEPBROWSER, DATABROWSER_WINDOW_TITLE, GetMainWindow, SWEEPBROWSER_WINDOW_TITLE, WindowExists.
Referenced by BSP_SetDataBrowser, BSP_SetSweepBrowser.
variable BSP_SetDataBrowser(string win)
wrapper function for external calls
References BROWSERTYPE_DATABROWSER, BSP_SetBrowserType.
Referenced by DB_OpenDataBrowser.
variable BSP_SetSweepBrowser(string win)
wrapper function for external calls
References BROWSERTYPE_SWEEPBROWSER, BSP_SetBrowserType.
Referenced by SB_OpenSweepBrowser.
variable BSP_IsSweepBrowser(string win)
wrapper function for external calls
References BROWSERTYPE_SWEEPBROWSER, BSP_GetBrowserType.
variable BSP_IsDataBrowser(string win)
wrapper function for external calls
References BROWSERTYPE_DATABROWSER, BSP_GetBrowserType.
Referenced by AD_FillWaves, AD_SelectResult, AddSweepToGraph, BSP_BindListBoxWaves, BSP_ButtonProc_ChangeSweep, BSP_ButtonProc_RestoreData, BSP_DynamicStartupSettings, BSP_DynamicSweepControls, BSP_GetLogbookWave, BSP_HasBoundDevice, BSP_SetDevice, BSP_UnsetDynamicStartupSettingsOfDataBrowser, BSP_UnsetDynamicSweepControlOfDataBrowser, BSP_UpdateSweepControls, BSP_UpdateSweepNote, DB_FindDataBrowser, GetPlainSweepList, LBV_CloseSettingsHistoryHook, LBV_GetAllDevicesForExperiment, LBV_GetExperiments, LBV_GetTPStorageLocation, OVS_GetSweepAndExperiment, OVS_UpdatePanel, UpdateSweepPlot, WB_OpenStimulusSetInWaveBuilder.
variable BSP_HasBoundDevice(string win)
check if the DEVICE property has a not nullstring property
win name of external panel or main window 1 if device is assigned and 0 otherwise. does not check if device is valid.
References BSP_GetDevice, BSP_IsDataBrowser, IsEmpty, NONE.
Referenced by AddSweepToGraph, BSP_BindListBoxWaves, BSP_ButtonProc_RestoreData, BSP_DoTimeAlignment, BSP_DynamicStartupSettings, BSP_GetFormulaGraph, BSP_UpdateSweepNote, DB_GetPlainSweepList, DB_LockToDevice, DB_SplitSweepsIfReq, DB_UpdateSweepPlot, DB_UpdateToLastSweep, DB_WindowHook, LBV_GetAllDevicesForExperiment, LBV_GetTPStorageLocation, LBV_PopupExtGetLBKeys, LBV_PopupExtGetResultsKeys, OVS_GetSweepAndExperiment, PSQ_PipetteInBath, RemoveSweepFromGraph, SC_SpikeControl.
static variable BSP_InitMainCheckboxes(string win)
set the initial state of the enable/disable buttons
win name of external panel or main window
References BSP_GetPanel, BSP_SetARControlStatus, BSP_SetOVSControlStatus, BSP_SetSFControlStatus, WindowExists.
Referenced by BSP_DynamicStartupSettings.
variable BSP_SetOVSControlStatus(string win)
enable/disable the OVS buttons
win specify mainPanel or bsPanel with OVS controls
References BSP_SetControlStatus, OVS_IsActive.
Referenced by BSP_CheckProc_OverlaySweeps, BSP_InitMainCheckboxes.
variable BSP_SetARControlStatus(string win)
enable/disable the AR buttons
win specify mainPanel or bsPanel with OVS controls
References AR_IsActive, BSP_SetControlStatus.
Referenced by BSP_CheckBoxProc_ArtRemoval, BSP_InitMainCheckboxes.
variable BSP_SetSFControlStatus(string win)
enable/disable the SF buttons
win specify mainPanel or bsPanel with OVS controls
References BSP_SetControlStatus, SF_IsActive.
Referenced by BSP_CheckBoxProc_SweepFormula, BSP_InitMainCheckboxes.
variable BSP_SetControlStatus(string win, string controlList, variable status)
enable/disable a list of controls
win specify mainPanel or bsPanel with OVS controls controlList list of controls status 1: enable; 0: disable
References ASSERT, BSP_GetPanel, DisableControls, EnableControls.
Referenced by BSP_SetARControlStatus, BSP_SetOVSControlStatus, BSP_SetSFControlStatus.
variable BSP_MainPanelButtonToggle(string mainPanel, variable visible)
action for button in mainPanel
mainPanel main Panel window visible set status of external Panel (opened: visible = 1)
References ControlExists, HideControl, ShowControl.
Referenced by BSP_ClosePanelHook, BSP_UnHidePanel, LBV_CloseSettingsHistoryHook.
variable BSP_ClosePanelHook(WMWinHookStruct *s)
panel close hook for side panel
References BSP_MainPanelButtonToggle, GetMainWindow.
variable BSP_SweepsAndMouseWheel(WMWinHookStruct *s)
References BSP_GetSweepControlsPanel, EVENT_MOD_ALT_OPTION, GetMainWindow, PGC_SetAndActivateControl.
variable BSP_CheckBoxProc_ArtRemoval(WMCheckBoxAction *cba)
enable/disable checkbox control for side panel
References BSP_SetARControlStatus, GetMainWindow, UpdateSweepPlot.
variable BSP_CheckBoxProc_PerPulseAver(WMCheckBoxAction *cba)
enable/disable checkbox control for side panel
References GetMainWindow, PA_Update, POST_PLOT_FULL_UPDATE.
variable BSP_CheckBoxProc_SweepFormula(WMCheckBoxAction *cba)
enable/disable checkbox control for side panel
References BSP_SetSFControlStatus, GetMainWindow.
variable BSP_ButtonProc_Panel(WMButtonAction *ba)
procedure for the open button of the side panel
References BSP_UnHidePanel, GetMainWindow.
Referenced by DB_ButtonProc_Panel.
variable BSP_SliderProc_ChangedSetting(WMSliderAction *spa)
References UpdateSweepPlot.
variable BSP_TimeAlignmentProc(WMCheckBoxAction *cba)
References UpdateSettingsPanel.
variable BSP_TimeAlignmentPopup(WMPopupAction *pa)
References UpdateSettingsPanel.
variable BSP_TimeAlignmentLevel(WMSetVariableAction *sva)
References UpdateSettingsPanel.
variable BSP_DoTimeAlignment(WMButtonAction *ba)
References BSP_HasBoundDevice, GetMainWindow, POST_PLOT_FULL_UPDATE, PostPlotTransformations, UpdateSettingsPanel.
variable BSP_CheckProc_ScaleAxes(WMCheckboxAction *cba)
References BROWSERSETTINGS_AXES_SCALING_CHECKBOXES, BSP_GetPanel, BSP_ScaleAxes, CHECKBOX_UNSELECTED, DisableControl, EnableControl, GetCheckBoxState, GetMainWindow, SetCheckBoxState.
variable BSP_AxisScalingLevelCross(WMSetVariableAction *sva)
References BSP_GetPanel, BSP_ScaleAxes, GetCheckBoxState, GetMainWindow.
static variable BSP_UpdateSweepControls(string win, string ctrl, variable firstSweepOrIndex, variable lastSweepOrIndex)
update controls in scPanel and change to new sweep
win name of external panel or main window ctrl name of the button that was pressed and is initiating the update firstSweepOrIndex first available sweep(DB) or index(SB) lastSweepOrIndex last available sweep(DB) or index(SB) the new sweep number in case of DB or the index for SB
References ASSERT, BSP_GetSweepControlsPanel, BSP_IsDataBrowser, DATA_SWEEP_BROWSER_PANEL_VERSION, DoAbortNow, GetMainWindow, GetPopupMenuIndex, GetSetVariable, HasPanelLatestVersion, ROWS, SB_GetPlainSweepList, SetPopupMenuIndex, SetSetVariable, SetSetVariableLimits, SetValDisplay.
Referenced by BSP_ButtonProc_ChangeSweep.
variable BSP_IsActive(string win, variable elementID)
check if the specified setting is activated
win name of external panel or main window elementID one of MIES_BSP_* constants like MIES_BSP_PA 1 if setting was activated, 0 otherwise
References BSP_GetPanel, CHECKBOX_SELECTED, DATA_SWEEP_BROWSER_PANEL_VERSION, DoAbortNow, HasPanelLatestVersion, MIES_BSP_AR, MIES_BSP_CS, MIES_BSP_DS, MIES_BSP_OVS, MIES_BSP_PA, MIES_BSP_SF.
Referenced by AD_Update, AR_IsActive, OVS_IsActive, PA_GatherSettings.
variable BSP_UpdateHelpNotebook(string win)
Fill the SweepFormula help notebook with the contents of the stored file.
References ASSERT, BSP_GetSFHELP, GetFolder, GetNotebookText, IsEmpty, ReplaceNotebookText.
Referenced by BSP_DynamicStartupSettings.
string BSP_GetFormulaGraph(string win)
Return a sweep formula graph name unique for that sweepbrowser/databrowser.
References BSP_GetFolder, BSP_HasBoundDevice, MIES_BSP_PANEL_FOLDER.
variable BSP_ParseChannelSelectionControl(string ctrl, string *channelType, variable *channelNum)
Parse a control name for the "Channel Selection Panel" and return its channel type and number. The number will be NaN for the ALL control.
References ASSERT, IsInteger, str2numSafe.
Referenced by BSP_ChannelSelectionWaveToGUI, BSP_GUIToChannelSelectionWave.
variable BSP_ChannelSelectionWaveToGUI(string panel, wave channelSel)
Set the channel selection dialog controls according to the channel selection wave.
References BSP_ParseChannelSelectionControl, IsNaN, panel, SetCheckBoxState.
Referenced by BSP_BindListBoxWaves.
variable BSP_GUIToChannelSelectionWave(string win, string ctrl, variable checked)
Set the channel selection wave acccording to the channel selection controls.
References BSP_GetChannelSelectionWave, BSP_ParseChannelSelectionControl, GetNumberFromType, SetCheckBoxState.
Referenced by BSP_CheckProc_ChangedSetting.
variable BSP_RemoveDisabledChannels(wave channelSel, wave ADCs, wave DACs, wave statusHS, wave numericalValues, variable sweepNo)
Removes the disabled channels and headstages from ADCs, DACs and statusHS
channelSel will be the result from BSP_FetchSelectedChannels() which is a copy of the permanent channel selection wave.
References DATA_ACQUISITION_MODE, GetLastSetting, IsConstant, NUM_HEADSTAGES, ROWS.
Referenced by CreateTiledChannelGraph.
variable BSP_ScaleAxes(string win)
References ASSERT, AutoscaleVertAxisVisXRange, BSP_GetPanel, EqualizeVerticalAxesRanges, GetCheckBoxState, GetMainWindow, GetSetVariable, IsControlDisabled.
Referenced by BSP_AxisScalingLevelCross, BSP_CheckProc_ScaleAxes, PostPlotTransformations, SB_OpenSweepBrowser, UpdateSettingsPanel.
std::tuple< TiledGraphSettings > BSP_GatherTiledGraphSettings(string win)
References BSP_GetPanel, GetCheckBoxState, GetSliderPositionIndex.
Referenced by DB_AddSweepToGraph, DB_UpdateSweepPlot, PostPlotTransformations, SB_AddSweepToGraph, SB_UpdateSweepPlot.
variable BSP_CheckProc_ChangedSetting(WMCheckBoxAction *cba)
References BSP_GetPanel, BSP_GUIToChannelSelectionWave, ControlWindowToFront, DATA_SWEEP_BROWSER_PANEL_VERSION, DisableControl, DisableControls, DoAbortNow, EnableControl, EnableControls, GetMainWindow, HasPanelLatestVersion, UpdateSweepPlot.
variable BSP_ButtonProc_RestoreData(WMButtonAction *ba)
References BSP_GetDevice, BSP_GetPanel, BSP_HasBoundDevice, BSP_IsDataBrowser, CHECKBOX_UNSELECTED, GetAnalysisSweepPath, GetDeviceDataPath, GetMainWindow, GetNumberFromWaveNote, GetPlainSweepList, GetSingleSweepFolder, GetSweepBrowserMap, NOTE_INDEX, ReplaceWaveWithBackupForAll, ROWS, SB_GetSweepBrowserFolder, SetCheckBoxState, UpdateSweepPlot.
variable BSP_CheckProc_OverlaySweeps(WMCheckBoxAction *cba)
References BSP_GetPanel, BSP_SetOVSControlStatus, GetMainWindow, OVS_UpdatePanel.
wave BSP_GetLogbookWave(string win, variable logbookType, variable logbookWaveType, variable sweepNumber=defaultValue, variable selectedExpDevice=defaultValue)
Generic getter for labnotebook waves.
Works with Databrowser/Sweepbrowser win panel logbookType one of LogbookTypes logbookWaveType one of LabnotebookWaveTypes sweepNumber [optional] sweep number selectedExpDevice [optional, defaults to off] return the labnotebook for the selected experiment/device combination returns the specified logbook wave or a null wave
References ASSERT, BSP_GetDevice, BSP_IsDataBrowser, GetLogbookWaves, GetPlainSweepList, GetPopupMenuString, IsValidSweepNumber, LBV_GetSettingsHistoryPanel, NONE, ROWS, SB_GetLogbookWave.
Referenced by AD_FillWaves, AD_PlotBounds, AR_UpdateTracesIfReq, LBV_AddTraceToLBGraphTPStorage, LBV_GetLogbookWavesForEntry, LBV_LimitXRangeToSelected, LBV_PlotAllAnalysisFunctionLBNKeys, LBV_PopupExtGetLBKeys, LBV_PopupExtGetResultsKeys, OVS_UpdatePanel, OVS_UpdateSweepSelectionChoices, PSQ_PipetteInBath.
wave BSP_FetchSelectedChannels(string graph, variable index=defaultValue, variable sweepNo=defaultValue)
Return the wave with the selected channels respecting the overlay sweeps headstage ignore list. The wave has the same layout as BSP_GetChannelSelectionWave.
References ASSERT, BSP_GetChannelSelectionWave, NUM_HEADSTAGES, OVS_GetHeadstageRemoval.
Referenced by DB_AddSweepToGraph, DB_UpdateSweepPlot, SB_AddSweepToGraph, SB_UpdateSweepPlot.
std::tuple< variable, variable > BSP_FirstAndLastSweepAcquired(string win)
Return the last and first sweep numbers.
References GetPlainSweepList, ROWS.
Referenced by BSP_ButtonProc_ChangeSweep, DB_LockToDevice, DB_UpdateToLastSweep.
variable BSP_ButtonProc_ChangeSweep(WMButtonAction *ba)
References BSP_FirstAndLastSweepAcquired, BSP_GetSweepControlsPanel, BSP_IsDataBrowser, BSP_UpdateSweepControls, CHECKBOX_SELECTED, DB_UpdateLastSweepControls, GetMainWindow, OVS_ChangeSweepSelectionState, OVS_IsActive, UpdateSweepPlot.
variable BSP_MainTabControlFinal(WMTabControlAction *tca)
References BSP_UpdateSweepNote.
variable BSP_UpdateSweepNote(string win)
References BSP_GetDevice, BSP_GetNotebookSubWindow, BSP_GetPanel, BSP_GetSweepControlsPanel, BSP_HasBoundDevice, BSP_IsDataBrowser, GetAnalysisSweepDataPath, GetDeviceDataPath, GetMainWindow, GetPopupMenuIndex, GetSetVariable, GetSweepBrowserMap, GetTabID, ReplaceNotebookText, SB_GetSweepBrowserFolder.
Referenced by BSP_MainTabControlFinal, DB_UpdateSweepPlot, SB_UpdateSweepPlot.
variable BSP_DynamicSettingsHistory(string win)
References LBV_GetSettingsHistoryPanel.
Referenced by BSP_InitPanel, DB_LockToDevice.
variable BSP_UnsetDynamicSettingsHistory(string win)
Unsets all control properties that are set in DB_DynamicSettingsHistory.
References ASSERT, LBV_GetSettingsHistoryPanel, WindowExists.
Referenced by DB_LockToDevice, DB_ResetAndStoreCurrentDBPanel.
variable BSP_UnHideSettingsHistory(string win)
References ASSERT, GetMainWindow, LBV_GetSettingsHistoryPanel, WindowExists.
Referenced by DB_ButtonProc_Panel.
variable BSP_AddTracesForEpochs(string win)
References BUG.
Referenced by PostPlotTransformations.