MIES_DataConfigurator.ipf
static variable DC_UpdateGlobals(string device, variable dataAcqOrTP)
Update global variables used by the Testpulse or DAQ.
References AFM_UpdateAnalysisFunctionWave, DATA_ACQUISITION_MODE, GetTPSettingsLabnotebook, GetTPSettingsLabnotebookKeyWave, KillOrMoveToTrash, TP_UpdateTPLBNSettings, TP_UpdateTPSettingsCalculated.
Referenced by DC_Configure.
variable DC_Configure(string device, variable dataAcqOrTP, variable multiDevice=defaultValue)
Prepare test pulse/data acquisition.
device panel title dataAcqOrTP one of DATA_ACQUISITION_MODE or TEST_PULSE_MODE multiDevice [optional: defaults to false] Fine tune data handling for single device (false) or multi device (true) Abort configuration failure
References AFM_CallAnalysisFunctions, AS_HandlePossibleTransition, AS_PRE_SWEEP, AS_PRE_SWEEP_CONFIG, ASSERT, ControlWindowToFront, DATA_ACQUISITION_MODE, DC_ChannelCalcForDAQConfigWave, DC_MakeDAQConfigWave, DC_MakeHelperWaves, DC_PlaceDataInDAQConfigWave, DC_PlaceDataInDAQDataWave, DC_UpdateGlobals, DC_UpdateHSProperties, EP_ClearEpochs, FREE_MEMORY_LOWER_LIMIT, GetADCListFromConfig, GetDACListFromConfig, GetDAQConfigWave, GetDAQDataWave, GetFreeMemory, GetHardwareType, GetSweepSettingsKeyWave, GetSweepSettingsTextKeyWave, GetSweepSettingsTextWave, GetSweepSettingsWave, GetTPResultsBuffer, HARDWARE_ABORT_ON_ERROR, HARDWARE_PREVENT_ERROR_POPUP, HW_IsRunning, IsValidSweepAndConfig, KillOrMoveToTrash, PRE_SET_EVENT, ROWS, SAVE_AND_SPLIT, SaveExperimentSpecial, SCOPE_CreateGraph, TEST_PULSE_MODE, TP_CreateTestPulseWave.
Referenced by DQM_StartDAQMultiDevice, DQS_StartDAQSingleDevice, RA_Counter, TP_Setup.
static variable DC_UpdateHSProperties(string device, wave ADCs)
References AFH_GetDACFromHeadstage, AFH_GetHeadstageFromADC, DAG_GetHeadstageMode, GetHSProperties, IsFinite, ROWS.
Referenced by DC_Configure.
static variable DC_NoOfChannelsSelected(string device, variable type)
Return the number of selected checkboxes for the given type.
References DAG_GetChannelState.
Referenced by DC_ChannelCalcForDAQConfigWave, DC_GetStopCollectionPoint, DC_ReturnTotalLengthIncrease.
static variable DC_ChannelCalcForDAQConfigWave(string device, variable dataAcqOrTP)
Returns the total number of combined channel types (DA, AD, and front TTLs) selected in the DA_Ephys Gui.
device panel title dataAcqOrTP acquisition mode, one of DATA_ACQUISITION_MODE or TEST_PULSE_MODE
References ASSERT, CHANNEL_TYPE_ADC, CHANNEL_TYPE_DAC, CHANNEL_TYPE_HEADSTAGE, CHANNEL_TYPE_TTL, DATA_ACQUISITION_MODE, DC_AreTTLsInRackChecked, DC_NoOfChannelsSelected, GetHardwareType, HARDWARE_ITC_DAC, HARDWARE_NI_DAC, RACK_ONE, RACK_ZERO, TEST_PULSE_MODE.
Referenced by DC_Configure.
static variable DC_AreTTLsInRackChecked(string device, variable rackNo)
Returns the ON/OFF status of the front TTLs on a specified rack.
device device rackNo Only the ITC1600 can have two racks. For all other ITC devices RackNo = 0.
References CHANNEL_TYPE_TTL, DAG_GetChannelState, HW_ITC_GetRackRange.
Referenced by DC_ChannelCalcForDAQConfigWave, DC_PlaceDataInDAQConfigWave, DC_WriteTTLIntoDAQDataWave.
static variable DC_LongestOutputWave(string device, variable dataAcqOrTP, variable channelType)
Returns the number of points in the longest stimset.
device device dataAcqOrTP acquisition mode, one of DATA_ACQUISITION_MODE or TEST_PULSE_MODE channelType channel type, one of ChannelTypeAndControlConstants
References ASSERT, CHANNEL_CONTROL_WAVE, DAG_GetChannelTextual, DAG_GetNumericalValue, DATA_ACQUISITION_MODE, DC_GetFilteredChannelState, GetHardwareType, GetTestPulse, HARDWARE_ITC_DAC, MINIMUM_ITCDATAWAVE_EXPONENT, ROWS, TEST_PULSE_MODE, WB_CreateAndGetStimSet.
Referenced by DC_CalculateLongestSweep.
static variable DC_CalculateDAQDataWaveLength(string device, variable dataAcqOrTP)
Calculate the required length of the DAQDataWave.
ITC Hardware: The DAQDataWave length = 2^x where is the first integer large enough to contain the longest output wave plus one. X also has a minimum value of 17 to ensure sufficient time for communication with the ITC device to prevent FIFO overflow or underrun. NI Hardware: Returns stopCollectionPoint device panel title dataAcqOrTP acquisition mode, one of DATA_ACQUISITION_MODE or TEST_PULSE_MODE
References DATA_ACQUISITION_MODE, FindNextPower, GetHardwareType, HARDWARE_ITC_DAC, HARDWARE_NI_DAC, MINIMUM_ITCDATAWAVE_EXPONENT.
Referenced by DC_FillDAQDataWaveForTP, DC_MakeAndGetDAQDataWave.
static variable DC_MakeDAQConfigWave(string device, variable numActiveChannels)
Create the DAQConfigWave used to configure the DAQ device.
device panel title numActiveChannels number of active channels as returned by DC_ChannelCalcForDAQConfigWave()
References ASSERT, GetDAQConfigWave, IsValidConfigWave.
Referenced by DC_Configure.
static std::tuple< WaveOrNull, WaveRefWave > DC_MakeAndGetDAQDataWave(string device, variable hardwareType, variable numActiveChannels, variable samplingInterval, variable dataAcqOrTP)
Creates DAQDataWave; The wave that the device takes DA and TTL data from and passes AD data to for all channels.
Config all refers to configuring all the channels at once device panel title hardwareType hardware type numActiveChannels number of active channels as returned by DC_ChannelCalcForDAQConfigWave() samplingInterval sampling interval as returned by DAP_GetSampInt() dataAcqOrTP one of DATA_ACQUISITION_MODE or TEST_PULSE_MODE
References DC_CalculateDAQDataWaveLength, DC_MakeNIChannelWave, GetDAQConfigWave, GetDAQDataWave, HARDWARE_ITC_DAC, HARDWARE_NI_DAC, IGOR_TYPE_8BIT_INT, IGOR_TYPE_UNSIGNED, SWS_GetRawDataFPType, XOP_CHANNEL_TYPE_TTL.
Referenced by DC_FillDAQDataWaveForDAQ, DC_FillDAQDataWaveForTP.
static wave DC_MakeNIChannelWave(string device, variable numRows, variable samplingInterval, variable index, variable type)
Creates a single NIChannel wave.
Config all refers to configuring all the channels at once device panel title numRows size of the 1D channel wave samplingInterval minimum sample intervall in microseconds index number of NI channel type numeric data type of NI channel Wave Reference to NI Channel wave
References GetNIDAQChannelWave.
Referenced by DC_MakeAndGetDAQDataWave.
static variable DC_MakeHelperWaves(string device, variable dataAcqOrTP)
Initializes the waves used for displaying DAQ/TP results in the oscilloscope window and the scaled data wave.
device panel title dataAcqOrTP one of DATA_ACQUISITION_MODE or TEST_PULSE_MODE
References ASSERT, DAG_GetNumericalValue, DATA_ACQUISITION_MODE, DC_InitDataHoldingWave, DECIMATION_NONE, DEFAULT_DECIMATION_FACTOR, FindPreviousPower, GetADCListFromConfig, GetDACListFromConfig, GetDAQConfigWave, GetDAQDataWave, GetDecimatedWaveSize, GetHardwareType, GetOscilloscopeWave, GetPlotArea, GetScaledDataWave, GetTPOscilloscopeWave, GetTPSettingsCalculated, GetTTLListFromConfig, HARDWARE_ITC_DAC, HARDWARE_NI_DAC, ROWS, SCOPE_GetGraph, SetNumberInWaveNote, SWS_GetRawDataFPType, TEST_PULSE_MODE, TP_GetPowerSpectrumLength.
Referenced by DC_Configure.
static variable DC_InitDataHoldingWave(wave wv, variable numRows, variable sampleInterval, variable numDACs, variable numADCs, variable numTTLs, variable type=defaultValue, variable isFourierTransform=defaultValue)
Initialize data holding waves to NaN.
References ASSERT, BUG, ChangeWaveLock, GetLockState, IsFloatingPointWave.
Referenced by DC_MakeHelperWaves.
wave DC_GetFilteredChannelState(string device, variable dataAcqOrTP, variable channelType, variable DAQChannelType=defaultValue)
Return the list of active channels, filtered for various special cases.
device panel title dataAcqOrTP one of DATA_ACQUISITION_MODE or TEST_PULSE_MODE channelType one of the channel type constants from ChannelTypeAndControlConstants DAQChannelType only return channels as active if they have the desired DAQChannel type (only respected for DA channel)
References AFH_GetHeadstageFromADC, AFH_GetHeadstageFromDAC, ASSERT, CHANNEL_CONTROL_WAVE, CHANNEL_TYPE_ADC, CHANNEL_TYPE_DAC, CHANNEL_TYPE_HEADSTAGE, CHANNEL_TYPE_TTL, DAG_GetChannelState, DAG_GetChannelTextual, DAQ_CHANNEL_TYPE_DAQ, DAQ_CHANNEL_TYPE_TP, DAQ_CHANNEL_TYPE_UNKOWN, DATA_ACQUISITION_MODE, IsFinite, NUM_AD_CHANNELS, NUM_DA_TTL_CHANNELS, STIMSET_TP_WHILE_DAQ.
Referenced by DAP_CheckSettings, DC_GotTPChannelWhileDAQ, DC_ITC_MakeTTLWave, DC_LongestOutputWave, DC_NI_MakeTTLWave, DC_PlaceDataInDAQConfigWave, IDX_ApplyUnLockedIndexing, IDX_IndexingDoIt, IDX_MaxNoOfSweeps, IDX_MinNoOfSweeps.
static variable DC_PlaceDataInDAQConfigWave(string device, variable dataAcqOrTP)
Places channel (DA, AD, and TTL) settings data into DAQConfigWave.
device panel title dataAcqOrTP one of DATA_ACQUISITION_MODE or TEST_PULSE_MODE
References AddEntryIntoWaveNoteAsList, AFH_GetHeadstageFromADC, CHANNEL_CONTROL_UNIT, CHANNEL_CONTROL_WAVE, CHANNEL_TYPE_ADC, CHANNEL_TYPE_DAC, CHANNEL_TYPE_TTL, CHANNEL_UNIT_KEY, DAG_GetChannelState, DAG_GetChannelTextual, DAG_GetTextualValue, DAP_GetSampInt, DAQ_CHANNEL_TYPE_DAQ, DAQ_CHANNEL_TYPE_TP, DATA_ACQUISITION_MODE, DC_AreTTLsInRackChecked, DC_GetChannelTypefromHS, DC_GetFilteredChannelState, GetDAQConfigWave, GetHardwareType, GetSpecialControlLabel, GetSweepSettingsWave, HARDWARE_ITC_DAC, HARDWARE_NI_DAC, HW_ITC_GetITCXOPChannelForRack, INDEP_HEADSTAGE, IsFinite, RACK_ONE, RACK_ZERO, ROWS, STIMSET_TP_WHILE_DAQ, TEST_PULSE_MODE, XOP_CHANNEL_TYPE_ADC, XOP_CHANNEL_TYPE_DAC, XOP_CHANNEL_TYPE_TTL.
Referenced by DC_Configure.
static variable DC_GetDecimationFactor(string device, variable dataAcqOrTP)
Get the decimation factor for the current channel configuration.
This is the factor between the minimum sampling interval and the real. If the multiplier is taken into account depends on dataAcqOrTP. device device dataAcqOrTP one of DATA_ACQUISITION_MODE or TEST_PULSE_MODE
References DAP_GetSampInt, WAVEBUILDER_MIN_SAMPINT.
Referenced by DC_CalculateGeneratedDataSize, DC_GetConfiguration.
static variable DC_CalculateLongestSweep(string device, variable dataAcqOrTP, variable channelType)
Returns the longest sweep in a stimulus set across the given channel type.
device device dataAcqOrTP mode, either DATA_ACQUISITION_MODE or TEST_PULSE_MODE channelType One of ChannelTypeAndControlConstants number of data points, not time
References DC_CalculateGeneratedDataSize, DC_LongestOutputWave.
Referenced by DC_GetStopCollectionPoint.
static variable DC_CalculateStimsetLength(wave stimSet, string device, variable dataAcqOrTP)
Get the stimset length for the real sampling interval.
stimSet stimset wave device device dataAcqOrTP one of DATA_ACQUISITION_MODE or TEST_PULSE_MODE
References DC_CalculateGeneratedDataSize, ROWS.
Referenced by DC_GetConfiguration, DC_WriteTTLIntoDAQDataWave.
static variable DC_CalculateGeneratedDataSize(string device, variable dataAcqOrTP, variable genLength)
Get the length for the real sampling interval from a generated wave with length.
device device dataAcqOrTP one of DATA_ACQUISITION_MODE or TEST_PULSE_MODE genLength length of a generated data wave
References ASSERT, DATA_ACQUISITION_MODE, DC_GetDecimationFactor, TEST_PULSE_MODE.
Referenced by DC_CalculateLongestSweep, DC_CalculateStimsetLength.
static variable DC_PlaceDataInDAQDataWave(string device, variable numActiveChannels, variable dataAcqOrTP, variable multiDevice)
Places data from appropriate DA and TTL stimulus set(s) into DAQDataWave. Also records certain DA_Ephys GUI settings into sweepDataLNB and sweepDataTxTLNB.
device panel title numActiveChannels number of active channels as returned by DC_ChannelCalcForDAQConfigWave() dataAcqOrTP one of DATA_ACQUISITION_MODE or TEST_PULSE_MODE multiDevice Fine tune data handling for single device (false) or multi device (true) Abort configuration failure
References AssertOnAndClearRTError, ControlWindowToFront, DATA_ACQUISITION_MODE, DC_CheckIfDataWaveHasBorderVals, DC_FillDAQDataWaveForDAQ, DC_FillDAQDataWaveForTP, DC_FillSetEventFlag, DC_GetConfiguration, DC_GetStopCollectionPoint, DC_PrepareLBNEntries, DC_WriteTTLIntoDAQDataWave, EP_CollectEpochInfo, TEST_PULSE_MODE.
Referenced by DC_Configure.
static variable DC_WriteTTLIntoDAQDataWave(string device, DataConfigurationResult *s)
References DATA_ACQUISITION_MODE, DataConfigurationResult::dataAcqOrTP, DC_AreTTLsInRackChecked, DC_CalculateStimsetLength, DC_ITC_MakeTTLWave, DC_NI_MakeTTLWave, DataConfigurationResult::decimationFactor, GetDAQConfigWave, GetDAQDataWave, GetTTLWave, HARDWARE_ITC_DAC, HARDWARE_NI_DAC, DataConfigurationResult::hardwareType, DataConfigurationResult::numADCEntries, DataConfigurationResult::numDACEntries, DataConfigurationResult::numTTLEntries, RACK_ONE, RACK_ZERO, ROWS, SIGNED_INT_16BIT_MAX, SIGNED_INT_16BIT_MIN, XOP_CHANNEL_TYPE_TTL.
Referenced by DC_PlaceDataInDAQDataWave.
static variable DC_PrepareLBNEntries(string device, DataConfigurationResult *s)
References DataConfigurationResult::ADCList, ANALYSIS_FUNCTION_PARAMS, ANALYSIS_FUNCTION_PARAMS_LBN, ASSERT, CHANNEL_CONTROL_GAIN, CHANNEL_CONTROL_INDEX_END, CHANNEL_CONTROL_UNIT, CHANNEL_TYPE_ADC, CHANNEL_TYPE_DAC, CLAMPMODE_ENTRY_KEY, DataConfigurationResult::DACAmp, DataConfigurationResult::DACList, DAG_GetChannelTextual, DAG_GetHeadstageMode, DAG_GetNumericalValue, DAG_GetTextualValue, DAQ_CHANNEL_TYPE_DAQ, DATA_ACQUISITION_MODE, DataConfigurationResult::dataAcqOrTP, DC_DocumentChannelProperty, DC_DocumentHardwareProperties, DC_GenerateStimsetFingerprint, DC_GetStimsetAcqCycleID, DeviceCanLead, DataConfigurationResult::distributedDAQ, DataConfigurationResult::distributedDAQOptOv, EVENT_NAME_LIST_LBN, EXPCONFIG_UDATA_SOURCEFILE_HASH, EXPCONFIG_UDATA_SOURCEFILE_PATH, EXPCONFIG_UDATA_STIMSET_NWB_PATH, GetAnalysisFunctionStorage, GetArchitectureBits, GetCellElectrodeNames, GetDAQConfigWave, GetFollowerList, GetIgorProBuildVersion, GetIgorProVersion, GetMIESVersionAsString, GetSpecialControlLabel, GetValDisplayAsNum, DataConfigurationResult::hardwareType, DataConfigurationResult::headstageADC, DataConfigurationResult::headstageDAC, INDEP_HEADSTAGE, IsConstant, IsFinite, NormalizeToEOL, NUM_HEADSTAGES, DataConfigurationResult::numADCEntries, DataConfigurationResult::numDACEntries, DataConfigurationResult::offsets, RA_ACQ_CYCLE_ID_KEY, DataConfigurationResult::regions, ROStr, DataConfigurationResult::samplingInterval, DataConfigurationResult::setColumn, DataConfigurationResult::setCycleCount, DataConfigurationResult::setLength, DataConfigurationResult::setName, DataConfigurationResult::statusHS, STIM_WAVE_NAME_KEY, DataConfigurationResult::stimSet, STIMSET_ACQ_CYCLE_ID_KEY, STIMSET_SCALE_FACTOR_KEY, STIMSET_WAVE_NOTE_KEY, str2numSafe, TOTAL_NUM_EVENTS, WAVEBUILDER_MIN_SAMPINT, WB_GetITI, WB_GetStimsetChecksum, XOP_CHANNEL_TYPE_ADC, XOP_CHANNEL_TYPE_DAC.
Referenced by DC_PlaceDataInDAQDataWave.
static variable DC_FillSetEventFlag(string device, DataConfigurationResult *s)
References DataConfigurationResult::DACList, DAQ_CHANNEL_TYPE_DAQ, GetDAQConfigWave, GetSetEventFlag, IDX_NumberOfSweepsInSet, DataConfigurationResult::numDACEntries, DataConfigurationResult::setColumn, DataConfigurationResult::setName.
Referenced by DC_PlaceDataInDAQDataWave.
static variable DC_FillDAQDataWaveForTP(string device, DataConfigurationResult *s)
References ASSERT, DataConfigurationResult::baselineFrac, CA_HardwareDataTPKey, CA_StoreEntryIntoCache, CA_TryFetchingEntryFromCache, COLS, DataConfigurationResult::DACAmp, HardwareDataTPInput::DACAmpTP, HardwareDataTPInput::DAGain, DataConfigurationResult::DAGain, DC_CalculateDAQDataWaveLength, DC_MakeAndGetDAQDataWave, GetDAQDataWave, GetNIDAQChannelWave, GetStringFromWaveNote, HARDWARE_ITC_DAC, HARDWARE_NI_DAC, HardwareDataTPInput::hardwareType, DataConfigurationResult::hardwareType, DataConfigurationResult::insertStart, IsWaveRefWave, MoveWaveWithOverwrite, DataConfigurationResult::multiDevice, NI_DAC_MAX, NI_DAC_MIN, HardwareDataTPInput::numActiveChannels, DataConfigurationResult::numActiveChannels, DataConfigurationResult::numADCEntries, HardwareDataTPInput::numberOfRows, DataConfigurationResult::numDACEntries, HardwareDataTPInput::numDACs, ROWS, HardwareDataTPInput::samplingInterval, DataConfigurationResult::samplingInterval, DataConfigurationResult::setColumn, SetStringInWaveNote, SIGNED_INT_16BIT_MAX, SIGNED_INT_16BIT_MIN, TEST_PULSE_MODE, DataConfigurationResult::testPulse, HardwareDataTPInput::testPulseLength, DataConfigurationResult::testPulseLength, TP_PROPERTIES_HASH.
Referenced by DC_PlaceDataInDAQDataWave.
static variable DC_FillDAQDataWaveForDAQ(string device, DataConfigurationResult *s)
References ASSERT, COLS, DataConfigurationResult::DACAmp, DataConfigurationResult::DACList, DataConfigurationResult::DAGain, DAQ_CHANNEL_TYPE_DAQ, DAQ_CHANNEL_TYPE_TP, DATA_ACQUISITION_MODE, DC_MakeAndGetDAQDataWave, DataConfigurationResult::decimationFactor, GetDAQConfigWave, DataConfigurationResult::globalTPInsert, HARDWARE_ITC_DAC, HARDWARE_NI_DAC, DataConfigurationResult::hardwareType, DataConfigurationResult::headstageDAC, DataConfigurationResult::insertStart, NI_DAC_MAX, NI_DAC_MIN, DataConfigurationResult::numActiveChannels, DataConfigurationResult::numDACEntries, ROWS, DataConfigurationResult::samplingInterval, DataConfigurationResult::setColumn, DataConfigurationResult::setLength, SIGNED_INT_16BIT_MAX, SIGNED_INT_16BIT_MIN, DataConfigurationResult::stimSet, DataConfigurationResult::testPulse, DataConfigurationResult::testPulseLength.
Referenced by DC_PlaceDataInDAQDataWave.
static std::tuple< DataConfigurationResult > DC_GetConfiguration(string device, variable numActiveChannels, variable dataAcqOrTP, variable multiDevice)
References ASSERT, HardwareDataTPInput::baselineFrac, CHANNEL_CONTROL_SCALE, CHANNEL_CONTROL_WAVE, CHANNEL_TYPE_DAC, CHANNEL_TYPE_HEADSTAGE, DAG_GetChannelState, DAG_GetChannelTextual, DAG_GetNumericalValue, DAP_GetSampInt, DAQ_CHANNEL_TYPE_DAQ, DAQ_CHANNEL_TYPE_TP, DATA_ACQUISITION_MODE, DC_CalculateChannelColumnNo, DC_CalculateStimsetLength, DC_GetDecimationFactor, DC_ReturnTotalLengthIncrease, GAIN_BEFORE_DAQ, GetADCListFromConfig, GetChannelClampMode, GetDACAmplitudes, GetDACListFromConfig, GetDAQConfigWave, GetHardwareType, GetSpecialControlLabel, GetTestPulse, GetTPSettings, GetTPSettingsCalculated, GetTTLListFromConfig, I_CLAMP_MODE, I_EQUAL_ZERO_MODE, InitOOdDAQParams, IsFinite, HardwareDataTPInput::numActiveChannels, OOD_GetResultWaves, ROWS, STIMSET_TP_WHILE_DAQ, SWS_GetChannelGains, TEST_PULSE_MODE, V_CLAMP_MODE, WAVEBUILDER_MIN_SAMPINT, WB_CreateAndGetStimSet.
Referenced by DC_PlaceDataInDAQDataWave.
static variable DC_DocumentHardwareProperties(string device, variable hardwareType)
Document hardware type/name/serial number into the labnotebook.
References ASSERT, CA_HWDeviceInfoKey, CA_StoreEntryIntoCache, CA_TryFetchingEntryFromCache, DC_DocumentChannelProperty, DEVICE_TYPES_ITC, HARDWARE_ABORT_ON_ERROR, HARDWARE_ITC_DAC, HARDWARE_NI_DAC, HARDWARE_PREVENT_ERROR_POPUP, HardwareDataTPInput::hardwareType, HW_GetDeviceInfo, INDEP_HEADSTAGE.
Referenced by DC_PrepareLBNEntries.
static variable DC_GetStimsetAcqCycleID(string device, variable fingerprint, variable DAC)
Return the stimset acquisition cycle ID.
device device fingerprint fingerprint as returned by DC_GenerateStimsetFingerprint() DAC DA channel
References GetNextRandomNumberForDevice, GetStimsetAcqIDHelperWave, IsFinite.
Referenced by DC_PrepareLBNEntries.
static variable DC_GenerateStimsetFingerprint(variable raCycleID, string setName, variable setCycleCount, variable setChecksum, variable dataAcqOrTP)
Generate the stimset fingerprint.
This fingerprint is unique for the combination of the following properties: Repeated acquisition cycle ID stimset name stimset checksum set cycle count Always then this fingerprint changes, a new stimset acquisition cycle ID has to be generated. Returns NaN for the testpulse.
References ASSERT, IsEmpty, IsInteger, TEST_PULSE_MODE.
Referenced by DC_PrepareLBNEntries.
static std::tuple< variable, variable, variable > DC_CheckIfDataWaveHasBorderVals(string device, variable dataAcqOrTP)
References ASSERT, GetDAQDataWave, GetHardwareType, HARDWARE_ITC_DAC, HARDWARE_NI_DAC, HardwareDataTPInput::hardwareType, IGOR_TYPE_16BIT_INT, IsWaveRefWave, NI_DAC_MAX, NI_DAC_MIN, SIGNED_INT_16BIT_MAX, SIGNED_INT_16BIT_MIN.
Referenced by DC_PlaceDataInDAQDataWave.
variable DC_DocumentChannelProperty(string device, string entry, variable headstage, variable channelNumber, variable channelType, variable var=defaultValue, string str=defaultValue)
Document channel properties of DA and AD channels.
Knows about unassociated channels and creates the special key returned by CreateLBNUnassocKey(). device device entry name of the property headstage number of headstage, must be NaN for unassociated channels channelNumber number of the channel channelType type of the channel var [optional] numeric value str [optional] string value
References ASSERT, COLS, CreateLBNUnassocKey, GetSweepSettingsKeyWave, GetSweepSettingsTextKeyWave, GetSweepSettingsTextWave, GetSweepSettingsWave, INDEP_HEADSTAGE, IsFinite.
Referenced by DC_DocumentHardwareProperties, DC_PrepareLBNEntries, EP_WriteEpochInfoIntoSweepSettings.
static variable DC_ITC_MakeTTLWave(string device, variable rackNo)
Combines the TTL stimulus sweeps across different TTL channels into a single wave.
device panel title rackNo Front TTL rack aka number of ITC devices. Only the ITC1600 has two racks, see RackConstants. Rack number for all other devices is RACK_ZERO.
References ASSERT, CHANNEL_CONTROL_INDEX_END, CHANNEL_CONTROL_WAVE, CHANNEL_TYPE_TTL, DAG_GetChannelTextual, DATA_ACQUISITION_MODE, DC_CalculateChannelColumnNo, DC_GetFilteredChannelState, GetSweepSettingsTextWave, GetSweepSettingsWave, GetTTLWave, HW_ITC_GetRackRange, INDEP_HEADSTAGE, NUM_DA_TTL_CHANNELS, RACK_ZERO, ROWS, WB_CreateAndGetStimSet, WB_GetStimsetChecksum.
Referenced by DC_WriteTTLIntoDAQDataWave.
static variable DC_NI_MakeTTLWave(string device)
References CHANNEL_CONTROL_INDEX_END, CHANNEL_CONTROL_WAVE, CHANNEL_TYPE_TTL, DAG_GetChannelTextual, DATA_ACQUISITION_MODE, DC_CalculateChannelColumnNo, DC_GetFilteredChannelState, GetSweepSettingsTextWave, GetTTLWave, INDEP_HEADSTAGE, NUM_DA_TTL_CHANNELS, ROWS, WB_CreateAndGetStimSet, WB_GetStimsetChecksum.
Referenced by DC_WriteTTLIntoDAQDataWave.
static std::tuple< variable, variable > DC_CalculateChannelColumnNo(string device, string setName, variable channelNo, variable channelType)
Returns column number/step of the stimulus set, independent of the times the set is being cycled through (as defined by SetVar_DataAcq_SetRepeats)
device panel title setName name of the stimulus set channelNo channel number channelType channel type, one of CHANNEL_TYPE_DAC or CHANNEL_TYPE_TTL column stimset column setCycleCount set cycle count
References ASSERT, DAG_GetNumericalValue, DAP_GetskipAhead, GetDevicePath, IDX_CalculcateActiveSetCount, IDX_NumberOfSweepsInSet, IDX_UnlockedIndexingStepNo, InPlaceRandomShuffle, IsFinite, RA_IsFirstSweep, RA_StepSweepsRemaining.
Referenced by DC_GetConfiguration, DC_ITC_MakeTTLWave, DC_NI_MakeTTLWave.
static variable DC_ReturnTotalLengthIncrease(string device, variable *onsetDelayUser=defaultValue, variable *onsetDelayAuto=defaultValue, variable *terminationDelay=defaultValue, variable *distributedDAQDelay=defaultValue)
Returns the length increase of the DAQDataWave following onset/termination delay insertion and distributed data aquisition. Does not incorporate adaptations for oodDAQ.
All returned values are in number of points, not in time. device panel title onsetDelayUser [optional] onset delay set by the user onsetDelayAuto [optional] onset delay required by other settings terminationDelay [optional] termination delay distributedDAQDelay [optional] distributed DAQ delay
References ASSERT, CHANNEL_TYPE_DAC, DAG_GetNumericalValue, DAP_GetSampInt, DATA_ACQUISITION_MODE, DC_NoOfChannelsSelected, GetValDisplayAsNum, HardwareDataTPInput::samplingInterval.
Referenced by DC_GetConfiguration, DC_GetStopCollectionPoint.
static variable DC_GetStopCollectionPoint(string device, variable dataAcqOrTP, wave setLengths)
Calculate the stop collection point, includes all required global adjustments.
References ASSERT, CHANNEL_TYPE_DAC, CHANNEL_TYPE_TTL, DAG_GetNumericalValue, DAP_GetSampInt, DAQ_CHANNEL_TYPE_DAQ, DATA_ACQUISITION_MODE, DC_CalculateLongestSweep, DC_NoOfChannelsSelected, DC_ReturnTotalLengthIncrease, GetDACTypesFromConfig, GetDAQConfigWave, TEST_PULSE_MODE, TIME_TP_ONLY_ON_DAQ.
Referenced by DC_PlaceDataInDAQDataWave.
variable DC_GotTPChannelWhileDAQ(string device)
Returns 1 if a channel is set to TP, the check is through the stimset name from the GUI.
References CHANNEL_CONTROL_WAVE, CHANNEL_TYPE_DAC, DAG_GetChannelTextual, DATA_ACQUISITION_MODE, DC_GetFilteredChannelState, ROWS, STIMSET_TP_WHILE_DAQ.
Referenced by DAP_CheckSettings, DAP_OneTimeCallAfterDAQ, DAP_OneTimeCallBeforeDAQ.
variable DC_GetChannelTypefromHS(string device, variable headstage)
Get the channel type of given headstage.
device panel title headstage head stage One of DaqChannelTypeConstants
References AFH_GetDACFromHeadstage, AFH_GetDAQDataColumn, ASSERT, DAQ_CHANNEL_TYPE_UNKOWN, GetDAQConfigWave, IsFinite, XOP_CHANNEL_TYPE_DAC.
Referenced by DC_PlaceDataInDAQConfigWave, P_PressureMethodPossible, TP_AnalyzeTP.