MIES_GlobalStringAndVariableAccess.ipf
static string GetNVARAsString(dfref dfr, string globalVarName, variable initialValue=defaultValue)
Returns the full path to a global variable.
dfr location of the global variable, must exist globalVarName name of the global variable initialValue initial value of the variable. Will only be used if it is created. 0 by default.
References ASSERT_TS, DataFolderExistsDFR.
Referenced by GetAcquisitionState, GetActiveSetCount, GetADChannelToMonitor, GetAnalysisFuncErrorCounter, GetBugCount, GetCount, GetDAQDeviceID, GetDataAcqRunMode, GetFIFOFileRef, GetFifoPosition, GetInteractiveMode, GetLastAcqHookCallTimeStamp, GetMaxIntertrialInterval, GetNI_ADCTaskID, GetNI_DACTaskID, GetNI_TTLTaskID, GetNITestPulseCounter, GetNWBFileIDExport, GetPxPVersion, GetPxPVersionForAB, GetRepeatedAcquisitionCycleID, GetRepeatedAcquisitionDuration, GetRepeatedAcquisitionStart, GetRepurposedSweepTime, GetRNGSeed, GetSessionStartTime, GetSessionStartTimeReadBack, GetSettingsJSONid, GetStopCollectionPoint, GetSweepFormulaJSONid, GetTemporaryVar, GetTestpulseCycleID, GetTestpulseRunMode, GetThreadGroupIDFIFO.
static string GetSVARAsString(dfref dfr, string globalStrName, string initialValue=defaultValue)
Returns the full path to a global string.
dfr location of the global string, must exist globalStrName name of the global string initialValue initial value of the string. Will only be used if it is created. null by default.
References ASSERT_TS, DataFolderExistsDFR.
Referenced by GetFollowerList, GetITCDeviceList, GetLockedDevices, GetMiesVersion, GetNI_AISetup, GetNIDeviceList, GetNWBFilePathExport, GetNWBOverrideHistoryAndLogFile, GetRepeatedAcquisitionFuncList, GetRunningSingleDevice, GetSweepFormulaParseErrorMessage, GetTemporaryString, GetUserComment.
variable ROVar(string path)
Helper function to get read-only access to a global variable.
path absolute path to a global variable
References ASSERT.
Referenced by AD_FillWaves, AFM_CallAnalysisFunctions, DQ_StopDAQ, ED_createTextNotes, ED_createWaveNotes, EP_CollectEpochInfo, ID_AskUserForSettings, RA_Counter, RA_CounterMD, SCOPE_UpdatePowerSpectrum, TP_UpdateTPLBNSettings.
string ROStr(string path)
Helper function to get read-only access to a global string.
path absolute path to a global string
References ASSERT.
Referenced by AB_ScanFolder, DC_PrepareLBNEntries, DeviceHasUserComments, GenerateJSONTemplateForUpload, IgorStartOrNewHook, MEN_CreateIssueOnGithub, MEN_OpenAboutDialog, NWB_AppendIgorHistoryAndLogFile, NWB_AppendSweepDuringDAQ, NWB_ExportAllData, NWB_GetExportedFileSize.
string GetMiesVersion()
Returns the full path to the mies-igor version string. Creating it when necessary.
Never ever write this string!
References CreateMiesVersion, GetMiesPath, GetSVARAsString, UNKNOWN_MIES_VERSION.
Referenced by AB_OpenAnalysisBrowser, GenerateJSONTemplateForUpload, IgorStartOrNewHook, MEN_CreateIssueOnGithub, MEN_OpenAboutDialog.
static string CreateMiesVersion()
Return the version string for the mies-igor project.
The mies version looks like /// Release_1.4_20170929-16-g497e7aa8 /// Date and time of last commit: 2018-05-08T14:42:50+02:00 /// Submodule status: /// 160000 6c47163858d99986b27c70f6226e8fca894ed5f7 0 Packages/IPNWB /// 160000 ed7e824a6e065e383ae31bb304383e13d7c7ccb5 0 Packages/ITCXOP2 /// 160000 2bd259940cb332339ed3c82b74632f06c9b68a15 0 Packages/ZeroMQ /// 160000 657e9e8abdc92aa299301796d710a0a717da4ef8 0 Packages/unit-testing /// or #UNKNOWN_MIES_VERSION on error @returns the mies version
References ASSERT, ControlWindowToFront, DEBUGPRINT, FileExists, FolderExists, GetSystemUserName, IsEmpty, NormalizeToEOL, UNKNOWN_MIES_VERSION.
Referenced by GetMiesVersion.
string GetDataAcqRunMode(string device)
Returns the absolute path to the variable runMode
The variable holds one of DAQRunModes.
References DAQ_NOT_RUNNING, GetDevicePath, GetNVARAsString.
Referenced by DQ_StopDAQ, RA_Counter, RA_CounterMD.
string GetFollowerList(string leadPanel)
Return the list of follower devices of a lead device.
GetListofLeaderAndPossFollower()
References GetDevicePath, GetSVARAsString.
Referenced by DC_PrepareLBNEntries.
string GetDAQDeviceID(string device)
Returns the absolute path to the device ID.
References GetDevicePath, GetNVARAsString.
string GetCount(string device)
Returns the absolute path to the global variable count storing the number of data acquisition cycles performed.
Count equals zero on the first sweep.
References GetDevicePath, GetNVARAsString.
string GetLockedDevices()
Returns the list of locked devices.
References GetDAQDevicesFolder, GetSVARAsString.
string GetUserComment(string device)
Return the absolute path to the user comment string.
References GetDevicePath, GetSVARAsString.
Referenced by DeviceHasUserComments, NWB_AppendSweepDuringDAQ, NWB_ExportAllData.
string GetStopCollectionPoint(string device)
Return the stop collection point, this is a length.
GetFifoPosition()
References GetDevicePath, GetNVARAsString.
Referenced by EP_CollectEpochInfo, SCOPE_ITC_AdjustFIFOPos, SCOPE_ITC_UpdateOscilloscope, SCOPE_NI_UpdateOscilloscope.
string GetADChannelToMonitor(string device)
Return the ADC to monitor.
This is the first actice AD channel in DAQDataWave and DAQConfigWave.
References GetDevicePath, GetNVARAsString.
Referenced by SCOPE_UpdatePowerSpectrum.
string GetRunningSingleDevice()
Return global device for background tasks.
Todoremove and use background struct members for the deviceID and GetDeviceMapping instead
References GetDAQDevicesFolder, GetSVARAsString.
string GetActiveSetCount(string device)
Return the active set count.
Active set count keeps track of how many steps of the largest currently selected set on all active channels still have to be done. Not counting the currently acquiring sweep.
References GetDevicePath, GetNVARAsString.
string GetInteractiveMode()
Return the interactive mode.
By default MIES operates in interactive mode (1) in the main thread and in non-interactive mode in preemptive threads. The user can change that to non-interactive mode where all dialog/popups etc. are avoided and replaced with sensible defaults.
References GetMiesPath, GetNVARAsString.
Referenced by ID_AskUserForSettings.
string GetTestpulseRunMode(string device)
Returns the absolute path to the testpulse running modes, holds one of TestPulseRunModes.
References GetDeviceTestPulse, GetNVARAsString.
Referenced by DAP_AdaptAutoTPColorAndDependent.
string GetNIDeviceList()
Returns NI device list.
Internal use only, prefer DAP_GetNIDeviceList() instead.
References GetDAQDevicesFolder, GetSVARAsString.
string GetITCDeviceList()
Returns ITC device list.
Internal use only, prefer DAP_GetITCDeviceList() instead.
References GetDAQDevicesFolder, GetSVARAsString.
string GetLastAcqHookCallTimeStamp(string device)
Returns the last time stamp HW_NI_RepeatAcqHook was called.
References GetDeviceTestPulse, GetNVARAsString.
string GetFIFOFileRef(string device)
Returns FIFO file reference.
References GetDeviceTestPulse, GetNVARAsString.
string GetNITestPulseCounter(string device)
Returns TestPulse Counter for Background Task.
References GetDeviceTestPulse, GetNVARAsString.
string GetNI_AISetup(string device)
Returns the current NI setup string for analog in through DAQmx_Scan.
References GetDevicePath, GetSVARAsString.
string GetNI_ADCTaskID(string device)
Returns the ADC task ID set after DAQmx_Scan in HW_NI_StartAcq.
References GetDevicePath, GetNVARAsString.
string GetNI_DACTaskID(string device)
Returns the DAC task ID set after DAQmx_WaveFormGen in HW_NI_PrepareAcq.
References GetDevicePath, GetNVARAsString.
string GetNI_TTLTaskID(string device)
Returns the TTL task ID set by DAQmx_DIO_Config in HW_NI_PrepareAcq.
References GetDevicePath, GetNVARAsString.
string GetSessionStartTime()
Return the experiment session start time in NWB-speech.
This is the time when the last device was locked.
References GetNVARAsString, GetNWBFolder.
string GetNWBFileIDExport()
Return the HDF5 file identifier for the NWB export.
References GetNVARAsString, GetNWBFolder.
string GetNWBFilePathExport()
Return the absolute path to the file for NWB export.
References GetNWBFolder, GetSVARAsString.
Referenced by AB_ScanFolder, NWB_ExportAllData, NWB_GetExportedFileSize.
string GetSessionStartTimeReadBack()
Return the experiment session start time in NWB-speech as read back from the NWB file.
References GetNVARAsString, GetNWBFolder.
Referenced by NWB_AppendSweepDuringDAQ, NWB_ExportAllData.
string GetThreadGroupIDFIFO(string device)
Return the thread group ID for the FIFO monitor/resetting daemon.
References GetDevicePath, GetNVARAsString.
string GetTemporaryString()
Return the absolute path to the temporary global string.
Callers should always assume that this string contains garbage.
References GetSVARAsString, GetTempPath.
Referenced by GetPopupMenuList.
string GetTemporaryVar()
Return the absolute path to the temporary global variable.
Callers should always assume that this variable contains garbage.
References GetNVARAsString, GetTempPath.
string GetRNGSeed(string device)
Return the absolute path to the RNG seed value.
This seed value can be used for deriving device dependent random numbers. Typical sequence: embed:rst:leading-asterisk * .. code-block:: igorpro * * NVAR rngSeed = $GetRNGSeed(device) * SetRandomSeed/BETR=1 rngSeed * rngSeed += 1 * variable val = GetReproducibleRandonNumber() *
References GetDevicePath, GetNVARAsString.
string GetRepeatedAcquisitionCycleID(string device)
Return the absolute path to the repeated acquisition cycle ID.
References GetDevicePath, GetNVARAsString.
string GetRepurposedSweepTime(string device)
Return the absolute path to the repurposed sweep time global variable.
Units are seconds.
References GetDevicePath, GetNVARAsString.
string GetRepeatedAcquisitionFuncList()
Return the list of functions to be executed after ITI in repeated acquisition.
References GetDAQDevicesFolder, GetSVARAsString.
string GetRepeatedAcquisitionStart()
Return the start time, in ticks, of the ITI cycle.
References GetDAQDevicesFolder, GetNVARAsString.
string GetRepeatedAcquisitionDuration()
Return the duration, in ticks, of the ITI cycle.
References GetDAQDevicesFolder, GetNVARAsString.
string GetFifoPosition(string device)
Return the current fifo position (a length)
Only valid if called during DAQ with DATA_ACQUISITION_MODE. This value is relative to first row of the rawDACWave, so an possible offset is already included in it.
References GetDevicePath, GetNVARAsString.
Referenced by AFM_CallAnalysisFunctions.
string GetAnalysisFuncErrorCounter(string device)
Return the error counter for the analysis function management.
Mainly used during testing to ensure that no RTE was thrown.
References GetDevicePath, GetNVARAsString.
string GetMaxIntertrialInterval(string device)
Return the maximum ITI of all active sets.
Only meaningful after preparing DAQ in DC_Configure()
References GetDevicePath, GetNVARAsString.
string GetPxPVersion()
Return the version number of the Igor experiment.
References EXPERIMENT_VERSION, GetMiesPath, GetNVARAsString.
Referenced by DAP_LockDevice.
string GetPxPVersionForAB(dfref dfr)
Return the version number of the Igor experiment loaded into the analysis browser.
dfr experiment folder, GetAnalysisExpFolder()
References GetNVARAsString.
string GetSweepFormulaJSONid(dfref dfr)
Return the JSON ID for the sweep formula.
References GetNVARAsString.
string GetSweepFormulaParseErrorMessage()
Return the formula error message for the sweep formula.
References GetSVARAsString, GetSweepFormulaPath.
string GetSettingsJSONid()
Return the JSON id of the settings file.
Loads the stored settings on disc if required.
References GenerateSettingsDefaults, GetMiesPath, GetNVARAsString, IsNaN, PACKAGE_MIES, PS_ReadSettings, UpgradeSettings.
string GetAcquisitionState(string device)
Return the path to the acquisition state.
Holds one of AcquisitionStates
References AS_INACTIVE, GetDevicePath, GetNVARAsString.
Referenced by AD_FillWaves, AS_GetSweepNumber, ED_createTextNotes, ED_createWaveNotes.
string GetBugCount()
Return the global bug count, incremented by Bug()
Mostly used for testing.
References GetMiesPath, GetNVARAsString.
string GetNWBOverrideHistoryAndLogFile()
Temporary storage for IP history and logfile.
Used for reexporting from NWBv1 into NWBv2, see AB_ReExport()
References GetSVARAsString.
Referenced by NWB_AppendIgorHistoryAndLogFile.
string GetTestpulseCycleID(string device)
Return the absolute path to the test pulse cycle ID.
References GetDeviceTestPulse, GetNVARAsString.
Referenced by TP_RecordTP, TP_StoreTP, TP_UpdateTPLBNSettings.