MIES_SweepFormula.ipf
const double SF_STATE_UNINITIALIZED
Referenced by SF_FormulaParser, SF_StringifyState.
const double SF_STATE_DEFAULT
Referenced by SF_FormulaParser, SF_StringifyState.
const double SF_STATE_COLLECT
Referenced by SF_FormulaParser, SF_StringifyState.
const double SF_STATE_ADDITION
Referenced by SF_FormulaParser, SF_StringifyState.
const double SF_STATE_SUBTRACTION
Referenced by SF_FormulaParser, SF_StringifyState.
const double SF_STATE_MULTIPLICATION
Referenced by SF_FormulaParser, SF_StringifyState.
const double SF_STATE_DIVISION
Referenced by SF_FormulaParser, SF_StringifyState.
const double SF_STATE_PARENTHESIS
Referenced by SF_FormulaParser, SF_StringifyState.
const double SF_STATE_FUNCTION
Referenced by SF_FormulaParser, SF_StringifyState.
const double SF_STATE_ARRAY
Referenced by SF_FormulaParser, SF_StringifyState.
const double SF_STATE_ARRAYELEMENT
Referenced by SF_FormulaParser, SF_StringifyState.
const double SF_STATE_WHITESPACE
Referenced by SF_FormulaParser, SF_StringifyState.
const double SF_STATE_NEWLINE
Referenced by SF_FormulaParser, SF_StringifyState.
const double SF_STATE_OPERATION
Referenced by SF_FormulaParser, SF_StringifyState.
const double SF_STATE_STRING
Referenced by SF_FormulaParser, SF_StringifyState.
const double SF_STATE_STRINGTERMINATOR
Referenced by SF_FormulaParser, SF_StringifyState.
const double SF_ACTION_UNINITIALIZED
Referenced by SF_FormulaParser, SF_StringifyAction.
const double SF_ACTION_SKIP
Referenced by SF_FormulaParser, SF_StringifyAction.
const double SF_ACTION_COLLECT
Referenced by SF_FormulaParser, SF_StringifyAction.
const double SF_ACTION_CALCULATION
Referenced by SF_FormulaParser, SF_StringifyAction.
const double SF_ACTION_SAMECALCULATION
Referenced by SF_FormulaParser, SF_StringifyAction.
const double SF_ACTION_HIGHERORDER
Referenced by SF_FormulaParser, SF_StringifyAction.
const double SF_ACTION_ARRAYELEMENT
Referenced by SF_FormulaParser, SF_StringifyAction.
const double SF_ACTION_PARENTHESIS
Referenced by SF_FormulaParser, SF_StringifyAction.
const double SF_ACTION_FUNCTION
Referenced by SF_FormulaParser, SF_StringifyAction.
const double SF_ACTION_ARRAY
Referenced by SF_FormulaParser, SF_StringifyAction.
const string SF_SWEEPFORMULA_REGEXP
Regular expression which extracts both formulas from $a vs $b
const string SF_SWEEPFORMULA_GRAPHS_REGEXP
Regular expression which extracts formulas pairs from $a vs $b\rand\r$c vs $d\rand\r...
const double SF_MAX_NUMPOINTS_FOR_MARKERS
const double SF_APFREQUENCY_FULL
const double SF_APFREQUENCY_INSTANTANEOUS
const double SF_APFREQUENCY_APCOUNT
const string SF_OP_MINUS
const string SF_OP_PLUS
const string SF_OP_MULT
const string SF_OP_DIV
const string SF_OP_RANGE
const string SF_OP_RANGESHORT
const string SF_OP_MIN
const string SF_OP_MAX
const string SF_OP_AVG
const string SF_OP_MEAN
const string SF_OP_RMS
const string SF_OP_VARIANCE
const string SF_OP_STDEV
const string SF_OP_DERIVATIVE
const string SF_OP_INTEGRATE
const string SF_OP_TIME
const string SF_OP_XVALUES
const string SF_OP_MERGE
const string SF_OP_TEXT
const string SF_OP_LOG
const string SF_OP_LOG10
const string SF_OP_APFREQUENCY
const string SF_OP_CURSORS
const string SF_OP_SWEEPS
const string SF_OP_AREA
const string SF_OP_SETSCALE
const string SF_OP_BUTTERWORTH
const string SF_OP_CHANNELS
const string SF_OP_DATA
const string SF_OP_LABNOTEBOOK
const string SF_OP_WAVE
const string SF_OP_FINDLEVEL
const string SF_OP_EPOCHS
const string SF_OP_TP
const string SF_OP_STORE
const string SF_OP_EPOCHS_TYPE_RANGE
const string SF_OP_EPOCHS_TYPE_NAME
const string SF_OP_EPOCHS_TYPE_TREELEVEL
const string SF_OP_TP_TYPE_BASELINE
const string SF_OP_TP_TYPE_INSTANT
const string SF_OP_TP_TYPE_STATIC
const double SF_OP_TP_TYPE_BASELINE_NUM
const double SF_OP_TP_TYPE_INSTANT_NUM
const double SF_OP_TP_TYPE_STATIC_NUM
const double EPOCHS_TYPE_INVALID
const double EPOCHS_TYPE_RANGE
const double EPOCHS_TYPE_NAME
const double EPOCHS_TYPE_TREELEVEL
const string SF_CHAR_COMMENT
const string SF_CHAR_CR
const string SF_CHAR_NEWLINE
const string MIXED_UNITS
static string SF_StringifyState(variable state)
References ASSERT, SF_STATE_ADDITION, SF_STATE_ARRAY, SF_STATE_ARRAYELEMENT, SF_STATE_COLLECT, SF_STATE_DEFAULT, SF_STATE_DIVISION, SF_STATE_FUNCTION, SF_STATE_MULTIPLICATION, SF_STATE_NEWLINE, SF_STATE_OPERATION, SF_STATE_PARENTHESIS, SF_STATE_STRING, SF_STATE_STRINGTERMINATOR, SF_STATE_SUBTRACTION, SF_STATE_UNINITIALIZED, SF_STATE_WHITESPACE.
Referenced by SF_FormulaParser.
static string SF_StringifyAction(variable action)
References ASSERT, SF_ACTION_ARRAY, SF_ACTION_ARRAYELEMENT, SF_ACTION_CALCULATION, SF_ACTION_COLLECT, SF_ACTION_FUNCTION, SF_ACTION_HIGHERORDER, SF_ACTION_PARENTHESIS, SF_ACTION_SAMECALCULATION, SF_ACTION_SKIP, SF_ACTION_UNINITIALIZED.
Referenced by SF_FormulaParser.
static variable SF_Assert(variable condition, string message, variable jsonId=defaultValue)
Assertion for sweep formula.
This assertion does not indicate a genearl programmer error but a sweep formula user error. All programmer error checks must still use ASSERT().
Referenced by SF_FormulaParser, SF_FormulaPreParser.
static string SF_FormulaPreParser(string formula)
preparse user input to correct formula patterns
parsed formula
References CountSubstrings, SF_Assert.
static variable SF_FormulaParser(string formula, variable *createdArray=defaultValue, variable indentLevel=defaultValue)
serialize a string formula into JSON
formula string formula createdArray [optional, default 0] set on recursive calls, returns boolean if parser created a JSON array indentLevel [internal use only] recursive call level, used for debug output a JSONid representation
References ASSERT, DP_DebuggingEnabledForCaller, IsEmpty, SF_ACTION_ARRAY, SF_ACTION_ARRAYELEMENT, SF_ACTION_CALCULATION, SF_ACTION_COLLECT, SF_ACTION_FUNCTION, SF_ACTION_HIGHERORDER, SF_ACTION_PARENTHESIS, SF_ACTION_SAMECALCULATION, SF_ACTION_SKIP, SF_ACTION_UNINITIALIZED, SF_Assert, SF_EscapeJsonPath, SF_FormulaParser, SF_FPAddArray, SF_FPPutInArrayAtPath, SF_STATE_ADDITION, SF_STATE_ARRAY, SF_STATE_ARRAYELEMENT, SF_STATE_COLLECT, SF_STATE_DEFAULT, SF_STATE_DIVISION, SF_STATE_FUNCTION, SF_STATE_MULTIPLICATION, SF_STATE_NEWLINE, SF_STATE_OPERATION, SF_STATE_PARENTHESIS, SF_STATE_STRING, SF_STATE_STRINGTERMINATOR, SF_STATE_SUBTRACTION, SF_STATE_UNINITIALIZED, SF_STATE_WHITESPACE, SF_StringifyAction, SF_StringifyState.
Referenced by SF_FormulaParser.
static variable SF_FPPutInArrayAtPath(variable subId, string jsonPath)
Create a new empty array object, add mainId into it at path and return created json, release subId.
Referenced by SF_FormulaParser.
static variable SF_FPAddArray(variable mainId, string jsonPath, variable subId, variable arrayWasCreated)
Adds subId to mainId, if necessary puts subId into an array, release subId.
Referenced by SF_FormulaParser.
static string SF_EscapeJsonPath(string str)
add escape characters to a path element
Referenced by SF_FormulaParser.
static variable SF_FormulaPlotter(string graph, string formula, dfref dfr=defaultValue, variable dmMode=defaultValue)
Plot the formula using the data from graph.
graph graph to pass to SF_FormulaExecutor formula formula to plot dfr [optional, default current] working dataFolder dmMode [optional, default DM_SUBWINDOWS] display mode that defines how multiple sweepformula graphs are arranged
static variable SF_SplitPlotting(wave wv, variable dim, variable i, variable split)
utility function for SF_FormulaPlotter
split dimension dim of wave wv into slices of size split and get the starting index i
static wave SF_GetRangeFromEpoch(string graph, string epochName, variable sweep, variable channel)
Returns a range from a epochName.
graph name of databrowser graph epochName name epoch sweep number of sweep channel number of DA channel a 1D wave with two elements, [startTime, endTime] in ms, if no epoch could be resolved [NaN, NaN] is returned
static variable SF_GetDAChannel(string graph, variable sweep, variable channelType, variable channelNumber)
static wave SF_GetSweepForFormula(string graph, wave range, wave channels, wave sweeps)
static variable SF_FormulaWaveScaleTransfer(wave source, wave dest, variable dimSource, variable dimDest)
transfer the wave scaling from one wave to another
Note: wave scale transfer requires wave units for the first wave in the array that source Wave whos scaling should get transferred dest Wave that accepts the new scaling dimSource dimension of the source wave dimDest dimension of the destination wave 0 if wave scaling was transferred, 1 if not
static wave SF_GetActiveChannelNumbers(string graph, wave channels, wave sweeps, variable entrySourceType)
Use the labnotebook information to return the active channel numbers for a given set of sweeps.
graph DataBrowser or SweepBrowser reference graph channels SF_FormulaExecutor style channels() wave sweeps SF_FormulaExecutor style sweeps() wave entrySourceType type of the labnotebook entry, one of DataAcqModes. If you don't care about the entry source type pass UNKNOWN_MODE. a SF_FormulaExecutor style channels() wave with two columns containing channelType and channelNumber
static string SF_PreprocessInput(string formula)
Pre process code entered into the notebook.
unify line endings to CR remove comments at line ending cut off last CR from back conversion with TextWaveToList
variable SF_button_sweepFormula_check(WMButtonAction *ba)
static variable SF_CheckInputCode(string code, dfref dfr)
Checks input code, sets globals for jsonId and error string.
variable SF_Update(string graph)
Referenced by PostPlotTransformations.
variable SF_IsActive(string win)
checks if SweepFormula (SF) is active.
Referenced by BSP_SetSFControlStatus, BSP_SweepFormulaHook.
std::tuple< string, string > SF_GetCode(string win)
Return the sweep formula code in raw and with all necessary preprocesssing.
variable SF_button_sweepFormula_display(WMButtonAction *ba)
static string SF_PrepareDataForResultsWave(wave data)
static std::tuple< WaveText, WaveText > SF_CreateResultsWaveWithCode(string graph, string code, wave data=defaultValue, string name=defaultValue)
variable SF_TabProc_Formula(WMTabControlAction *tca)
static wave SF_FilterEpochs(WaveOrNull epochs, WaveOrNull ignoreTPs)
static wave SF_OperationTP(variable jsonId, string jsonPath, string graph)
static wave SF_OperationEpochs(variable jsonId, string jsonPath, string graph)
static variable SF_EpochsSetOutValues(variable epType, wave out, variable outCnt, string name=defaultValue, string treeLevel=defaultValue, string startTime=defaultValue, string endtime=defaultValue)
static wave SF_OperationMinus(variable jsonId, string jsonPath, string graph)
static wave SF_OperationPlus(variable jsonId, string jsonPath, string graph)
static wave SF_OperationDiv(variable jsonId, string jsonPath, string graph)
static wave SF_OperationMult(variable jsonId, string jsonPath, string graph)
static wave SF_OperationRange(variable jsonId, string jsonPath, string graph)
range (start[, stop[, step]])
static wave SF_OperationMin(variable jsonId, string jsonPath, string graph)
static wave SF_OperationMax(variable jsonId, string jsonPath, string graph)
static wave SF_OperationAvg(variable jsonId, string jsonPath, string graph)
static wave SF_OperationRMS(variable jsonId, string jsonPath, string graph)
static wave SF_OperationVariance(variable jsonId, string jsonPath, string graph)
static wave SF_OperationStdev(variable jsonId, string jsonPath, string graph)
static wave SF_OperationDerivative(variable jsonId, string jsonPath, string graph)
static wave SF_OperationIntegrate(variable jsonId, string jsonPath, string graph)
static wave SF_OperationArea(variable jsonId, string jsonPath, string graph)
static wave SF_OperationButterworth(variable jsonId, string jsonPath, string graph)
static wave SF_OperationXValues(variable jsonId, string jsonPath, string graph)
static wave SF_OperationText(variable jsonId, string jsonPath, string graph)
static wave SF_OperationSetScale(variable jsonId, string jsonPath, string graph)
static wave SF_OperationWave(variable jsonId, string jsonPath, string graph)
static wave SF_OperationMerge(variable jsonId, string jsonPath, string graph)
static wave SF_OperationChannels(variable jsonId, string jsonPath, string graph)
channels([str name]+) converts a named channel from string to numbers. returns [[channelName, channelNumber]+]
static wave SF_OperationSweeps(variable jsonId, string jsonPath, string graph)
sweeps([str type]) type: |displayed|all displayed (default): get (selected) sweeps all: get all possible sweeps
static wave SF_OperationData(variable jsonId, string jsonPath, string graph)
data(array range,array channels,array sweeps) returns [[sweeps][channel]] for all [sweeps] in list sweepNumbers, grouped by channels
static wave SF_OperationLabnotebook(variable jsonId, string jsonPath, string graph)
labnotebook(string key, array channels, array sweeps [, string entrySourceType]) return lab notebook key for all sweeps that belong to the channels channels
static wave SF_OperationLog(variable jsonId, string jsonPath, string graph)
static wave SF_OperationLog10(variable jsonId, string jsonPath, string graph)
static wave SF_OperationCursors(variable jsonId, string jsonPath, string graph)
static wave SF_OperationFindLevel(variable jsonId, string jsonPath, string graph)
static wave SF_OperationApFrequency(variable jsonId, string jsonPath, string graph)
static wave SF_OperationStore(variable jsonId, string jsonPath, string graph)
static wave SF_SplitCodeToGraphs(string code)
static wave SF_SplitGraphsToFormulas(WaveText graphCode)
static string SF_GetFormulaWinNameTemplate(string mainWindow)
variable SF_button_sweepFormula_tofront(WMButtonAction *ba)
static wave SF_NewChannelsWave(variable size)
static wave SF_GetDefaultEmptyWave()
static wave SF_AverageTPFromSweep(WaveText epochMatches, wave sweepData)
static variable SF_AverageTPFromSweepImpl(wave tpData, wave tpStart, wave sweepData, variable i)
wave SF_GetAllOldCodeForGUI(string win)
static wave SF_GetAllOldCode()
variable SF_PopMenuProc_OldCode(WMPopupAction *pa)