MIES_GuiUtilities.ipf
const string USERDATA_PREFIX
Referenced by GetUserdataKeys.
const string USERDATA_SUFFIX
Referenced by GetUserdataKeys.
variable ShowControl(string win, string control)
Show a GUI control in the given window.
References ASSERT, HIDDEN_CONTROL_BIT.
Referenced by BSP_MainPanelButtonToggle, CONF_RestoreControl, ShowControls.
variable ShowControls(string win, string controlList)
Show a list of GUI controls in the given window.
References ShowControl.
Referenced by DAP_UpdateYokeControls, WBP_FinalTabHook.
variable HideControl(string win, string control)
Hide a GUI control in the given window.
References ASSERT, HIDDEN_CONTROL_BIT.
Referenced by BSP_MainPanelButtonToggle, CONF_RestoreControl, HideControls.
variable HideControls(string win, string controlList)
Hide a list of GUI controls in the given window.
References HideControl.
Referenced by DAP_UpdateYokeControls, WBP_FinalTabHook.
variable EnableControl(string win, string control)
Enable a GUI control in the given window.
References ASSERT, DISABLE_CONTROL_BIT.
Referenced by ApplyConstantRateChanges, BSP_CheckProc_ChangedSetting, BSP_CheckProc_ScaleAxes, CheckProc_ClearEnable, CONF_RestoreControl, DAP_ButtonProc_Follow, DAP_ButtonProc_Independent, DAP_EphysPanelStartUpSettings, DAP_LockDevice, DAP_PopMenuProc_FixedSampInt, DAP_PopMenuProc_SampMult, DAP_ResetGUIAfterDAQ, DAP_UpdateAllYokeControls, DAP_UpdateFollowerControls, EnableControls, P_Disable, P_Enable, P_EnableButtonsIfValid, SBE_PopMenu_ExportTargetGraph, TimeAlignUpdateControls, UpdatePopupMenuWindowFunction, WBP_FinalTabHook, WBP_UpdatePanelIfAllowed.
variable EnableControls(string win, string controlList)
Enable a list of GUI controls in the given window.
References EnableControl.
Referenced by AD_CheckProc_Toggle, AdaptDependentControls, BSP_CheckProc_ChangedSetting, BSP_DynamicStartupSettings, BSP_DynamicSweepControls, BSP_SetControlStatus, BSP_UnsetDynamicStartupSettingsOfDataBrowser, DAP_AdaptPanelForDeviceSpecifics, DAP_ButtonProc_Lead, DAP_EphysPanelStartUpSettings, DAP_HandleSingleDeviceDependentControls, DAP_RemoveYokedDAC, DAP_ResetGUIAfterDAQ, DAP_UnlockDevice, MSQ_DAScale, MSQ_FastRheoEst, P_ButtonProc_UserPressure, P_Disable, P_Enable, P_EnableButtonsIfValid, PSQ_Chirp, PSQ_DAScale, PSQ_PipetteInBath, PSQ_Ramp, PSQ_Rheobase, PSQ_SquarePulse, SBE_CheckProc_UsePulseForXRange, SBE_PopMenu_ExportTargetAxis, TimeAlignUpdateControls, WBP_AdjustDeltaControls, WBP_ChangeWaveType, WBP_UpdateDependentControls, WBP_UpdatePanelIfAllowed.
variable DisableControl(string win, string control)
Disable a GUI control in the given window.
References ASSERT, DISABLE_CONTROL_BIT.
Referenced by ApplyConstantRateChanges, BSP_CheckProc_ChangedSetting, BSP_CheckProc_ScaleAxes, CheckProc_ClearEnable, CONF_RestoreControl, DAP_ButtonProc_Lead, DAP_EphysPanelStartUpSettings, DAP_OneTimeCallAfterDAQ, DAP_OneTimeCallBeforeDAQ, DAP_PopMenuProc_FixedSampInt, DAP_PopMenuProc_SampMult, DAP_RemoveYokedDAC, DAP_UnlockDevice, DisableControls, ID_AskUserForSettings, LBV_SelectExperimentAndDevice, P_Disable, P_Enable, SBE_PopMenu_ExportTargetGraph, TimeAlignUpdateControls, UpdatePopupMenuWindowFunction, WBP_UpdatePanelIfAllowed.
variable DisableControls(string win, string controlList)
Disable a list of GUI controls in the given window.
References DisableControl.
Referenced by AD_CheckProc_Toggle, AdaptDependentControls, BSP_CheckProc_ChangedSetting, BSP_DynamicStartupSettings, BSP_DynamicSweepControls, BSP_SetControlStatus, DAP_AdaptPanelForDeviceSpecifics, DAP_ButtonProc_Follow, DAP_ButtonProc_Independent, DAP_LockDevice, DAP_OneTimeCallBeforeDAQ, DAP_UpdateAllYokeControls, MSQ_DAScale, MSQ_FastRheoEst, P_ButtonProc_UserPressure, P_Disable, P_EnableButtonsIfValid, PSQ_Chirp, PSQ_DAScale, PSQ_PipetteInBath, PSQ_Ramp, PSQ_Rheobase, PSQ_SquarePulse, SBE_CheckProc_UsePulseForXRange, SBE_PopMenu_ExportTargetAxis, SetPressureButtonsToBaseState, TimeAlignUpdateControls, TP_Setup, WBP_AdjustDeltaControls, WBP_ChangeWaveType, WBP_UpdateDependentControls, WBP_UpdatePanelIfAllowed.
variable SetControlTitles(string win, string controlList, string controlTitleList)
Set the title of a list of controls.
References ASSERT, SetControlTitle.
Referenced by P_EnableButtonsIfValid, SetPressureButtonsToBaseState.
variable SetControlTitle(string win, string controlName, string newTitle)
Set the title of a control.
References ASSERT.
Referenced by DAP_ResetClampModeTitle, DAP_SetAmpModeControls, P_LoadPressureButtonState, P_ResetAll_P_ButtonsToBaseState, P_UpdatePressureMode, SetControlTitles, WBP_ButtonProc_OpenAnaParamGUI.
variable SetControlProcedures(string win, string controlList, string newProcedure)
Set the procedure of a list of controls.
References SetControlProcedure.
Referenced by BSP_DynamicSweepControls.
variable SetControlProcedure(string win, string controlName, string newProcedure)
Set the procedure of a control.
References ASSERT.
Referenced by SetControlProcedures.
string GetTitle(string recMacro, variable supress=defaultValue)
Return the title of a control.
recMacro recreation macro for ctrl supress supress assertion that ctrl must have a title Returns the title or an empty string
References ASSERT.
variable SetControlTitleColors(string win, string controlList, variable R, variable G, variable B)
Change color of the title of mulitple controls.
References SetControlTitleColor.
Referenced by P_EnableButtonsIfValid, SetPressureButtonsToBaseState.
variable SetControlTitleColor(string win, string controlName, variable R, variable G, variable B)
Change color of a control.
References ASSERT.
Referenced by DAP_ResetClampModeTitle, DAP_SetAmpModeControls, P_LoadPressureButtonState, P_ResetAll_P_ButtonsToBaseState, P_UpdatePressureMode, SetControlTitleColors.
variable ChangeControlColor(string win, string controlName, variable R, variable G, variable B)
Change color of a control.
References ASSERT.
variable ChangeControlValueColor(string win, string controlName, variable R, variable G, variable B)
Change the font color of a control.
References ASSERT.
Referenced by P_PressureDisplayHighlite.
variable ChangeControlValueColors(string win, string controlList, variable R, variable G, variable B)
Change the font color of a list of controls.
References ASSERT.
variable SetControlBckgColor(string win, string controlName, variable R, variable G, variable B, variable Alpha=defaultValue)
Changes the background color of a control.
win panel controlName GUI control name R red G green B blue Alpha defaults to opaque if not provided
References ASSERT.
variable ChangeControlBckgColors(string win, string controlList, variable R, variable G, variable B)
Change the background color of a list of controls.
References ASSERT.
variable GetCheckBoxState(string win, string control)
Returns one if the checkbox is selected or zero if it is unselected.
References ASSERT, CONTROL_TYPE_CHECKBOX.
Referenced by AB_ButtonProc_ResaveAsNWB, AB_LoadFromFile, AD_SelectResult, AR_HandleRanges, AR_HighlightArtefactsEntry, BSP_AxisScalingLevelCross, BSP_CheckProc_ScaleAxes, BSP_GatherTiledGraphSettings, BSP_ScaleAxes, ButtonDoIt, CONF_RestoreHeadstageAssociation, DAG_ControlStatusWave, DAP_ChangeHeadstageState, DAP_GetInfoFromControl, DB_UpdateToLastSweep, ExpandRateToList, GetGuiControlValue, GetPopupMenuRates, InitPostPlotSettings, LBV_LimitXRangeToSelected, OVS_GetHeadstageRemoval, OVS_UpdatePanel, ReachTargetVoltage, SBE_FillExportSettings, SWS_AfterSweepDataChangeHook, TimeAlignCursorMovedHook, TimeAlignHandleCursorDisplay, TimeAlignUpdateControls, WBP_ButtonProc_SaveSet, WBP_LoadSet, WBP_ParameterWaveToPanel, WBP_ReturnPulseDurationMax, WBP_UpdateDependentControls, WBP_UpdatePanelIfAllowed.
variable SetSetVariable(string win, string Control, variable newValue, variable respectLimits=defaultValue)
Set the internal number in a setvariable control.
References ASSERT, CONTROL_TYPE_SETVARIABLE, GetLimitConstrainedSetVar.
Referenced by AI_UpdateAmpView, BSP_DynamicSweepControls, BSP_UpdateSweepControls, DAP_ApplyClmpModeSavdSettngs, DAP_EphysPanelStartUpSettings, DAP_SetVarProc_DA_Scale, DAP_UpdateSweepLimitsAndDisplay, DB_UpdateLastSweepControls, DB_UpdateToLastSweep, ID_AskUserForSettings, P_UpdatePressureControls, PA_SetVarProc_Common, PGC_SetAndActivateControl, SB_PopupMenuSelectSweep, SetGuiControlValue, SWS_SaveAcquiredData, WBP_CutOffCrossOver, WBP_HighPassDeltaLimits, WBP_LoadSet, WBP_LowPassDeltaLimits, WBP_UpdatePanelIfAllowed.
variable SetSetVariableString(string win, string control, string str, variable setHelp=defaultValue)
Set the SetVariable contents as string.
win window control control of type SetVariable str string to set setHelp [optional, defaults to false] set the help string as well. Allows to work around long text in small controls.
References ASSERT, CONTROL_TYPE_SETVARIABLE.
Referenced by AB_BrowserStartupSettings, AB_ButtonProc_SelectDirectory, AB_OpenAnalysisBrowser, BSP_BindListBoxWaves, DAP_ApplyClmpModeSavdSettngs, DAP_EphysPanelStartUpSettings, P_UpdatePressureControls, PGC_SetAndActivateControl, SetGuiControlValue, WBP_ButtonProc_AddParam, WBP_ButtonProc_SaveSet, WBP_ListBoxProc_AnalysisParams, WBP_LoadSet, WBP_ParameterWaveToPanel.
variable SetCheckBoxState(string win, string control, variable state)
Set the state of the checkbox.
References ASSERT, CHECKBOX_SELECTED, CONTROL_TYPE_CHECKBOX.
Referenced by AB_BrowserStartupSettings, AI_UpdateAmpView, AR_ButtonProc_RemoveRanges, BSP_ButtonProc_RestoreData, BSP_ChannelSelectionWaveToGUI, BSP_CheckProc_ScaleAxes, BSP_GUIToChannelSelectionWave, DAP_ApplyClmpModeSavdSettngs, DAP_ChangeHeadstageState, DAP_CheckProc_AD, DAP_CheckProc_ClampMode, DAP_CheckProc_HedstgeChck, DAP_DAorTTLCheckProc, DAP_RemoveClampModeSettings, DAP_ToggleCheckBoxes, DP_OpenDebugPanel, DP_WindowHook, EqualizeCheckBoxes, SetGuiControlValue, ToggleCheckBoxes, UpdateCheckBoxes, WBP_LoadSet, WBP_StartupSettings.
variable SetSetVariableLimits(string win, string Control, variable low, variable high, variable increment)
Set the input limits for a setVariable control.
References ASSERT, CONTROL_TYPE_SETVARIABLE.
Referenced by BSP_DynamicSweepControls, BSP_UpdateSweepControls, DAP_setSkipAheadLimit, DB_UpdateLastSweepControls, ShowSetVariableLimitsSelectionPopup, SWS_SaveAcquiredData.
variable GetSetVariable(string win, string control)
Returns the contents of a SetVariable.
References ASSERT, CONTROL_TYPE_SETVARIABLE.
Referenced by AR_UpdateListBoxWave, BSP_ScaleAxes, BSP_UpdateSweepControls, BSP_UpdateSweepNote, CONF_GetAmplifierSettings, DAP_UpdateChanAmpAssignStorWv, DB_UpdateLastSweepControls, DB_UpdateSweepPlot, GetAllDAEphysSetVarNum, GetGuiControlValue, InitPostPlotSettings, IVS_runInitAccessResisQC, LBV_LimitXRangeToSelected, OVS_ChangeSweepSelection, OVS_UpdatePanel, P_UpdatePressureDataStorageWv, PA_DeconvGatherSettings, PA_GatherSettings, SBE_FillExportSettings, SC_ReactToQCFailures, SC_SpikeControl, WB_MakeWaveBuilderWave, WBP_ButtonProc_SaveSet, WBP_CutOffCrossOver, WBP_DisplaySetInPanel, WBP_HighPassDeltaLimits, WBP_InitialTabHook, WBP_LowPassDeltaLimits, WBP_MainWindowHook, WBP_ParameterWaveToPanel, WBP_PopMenuProc_WaveToLoad, WBP_ReturnPulseDurationMax, WBP_SetVarCombineEpochFormula, WBP_UpdateControlAndWave, WBP_UpdateEpochControls, WBP_UpdatePanelIfAllowed.
string GetSetVariableString(string win, string control)
Returns the contents of a SetVariable with an internal string.
References ASSERT, CONTROL_TYPE_SETVARIABLE.
Referenced by AB_ButtonProc_SelectDirectory, AB_ScanFolder, CONF_GetAmplifierSettings, DAP_UpdateChanAmpAssignStorWv, GetAllDAEphysSetVarTxT, GetGuiControlValue, P_UpdatePressureDataStorageWv, SBE_FillExportSettings, WBP_ButtonProc_AddParam, WBP_ButtonProc_SaveSet, WBP_ReturnListSavedSets.
string GetPopupMenuString(string win, string control)
Returns the current PopupMenu item as string.
References ASSERT, CONTROL_TYPE_POPUPMENU.
Referenced by AFM_UpdateAnalysisFunctionWave, BSP_GetLogbookWave, ButtonDoIt, CONF_GetAmplifierSettings, CONF_GetUserPressure, DAP_ButtonProc_ClearChanCon, DAP_CheckPressureSettings, DAP_LockDevice, DAP_SetVarProc_Channel_Search, DAP_UpdateChanAmpAssignPanel, DAP_UpdateChanAmpAssignStorWv, DAP_UpdateStimulusSetPopup, GetAllDAEphysPopMenuString, GetTargetRate, InitPostPlotSettings, LBV_GetAllDevicesForExperiment, LBV_GetTPStorageLocation, OVS_SetVarProc_SelectionRange, P_CheckDeviceAndChannelSelection, P_UpdatePopupDevices, P_UpdatePressureDataStorageWv, PA_GatherSettings, SBE_FillExportSettings, SBE_GetPulseStartTimesForSel, SBE_GetSelectedAxis, SBE_GetSourceGraphADTraces, SetPopupMenuString, TimeAlignHandleCursorDisplay, UpdatePanel, WBP_AnaFuncsToWPT, WBP_ButtonProc_AddParam, WBP_ButtonProc_DeleteSet, WBP_ButtonProc_LoadSet, WBP_ButtonProc_OpenAnaFuncs, WBP_GetStimulusType, WBP_InitialTabHook, WBP_PopupMenu_LoadSet.
variable GetPopupMenuIndex(string win, string control)
Returns the zero-based index of a PopupMenu.
References ASSERT, CONTROL_TYPE_POPUPMENU.
Referenced by BSP_UpdateSweepControls, BSP_UpdateSweepNote, GetAllDAEphysPopMenuIndex, GetDecimationMethod, GetGuiControlValue, InitPostPlotSettings, OVS_UpdatePanel, P_UpdatePressureDataStorageWv, PA_GatherSettings, SB_UpdateSweepPlot, SBE_CheckProc_UsePulseForXRange, TimeAlignUpdateControls, UpdatePopupMenuTargetRate, WBP_AdjustDeltaControls.
variable SetPopupMenuIndex(string win, string control, variable index)
Sets the zero-based index of the PopupMenu.
References ASSERT, CONTROL_TYPE_POPUPMENU.
Referenced by BSP_DynamicStartupSettings, BSP_UpdateSweepControls, DAP_EphysPanelStartUpSettings, DAP_PopMenuChkProc_StimSetList, DAP_UpdateStimulusSetPopup, IDX_IndexSingleChannel, IDX_ResetStartFinishForIndexing, LBV_SelectExperimentAndDevice, P_UpdatePopupDevices, P_UpdatePressureControls, SetGuiControlValue, UpdatePopupMenuTargetRate, WBP_LoadSet, WBP_StartupSettings.
variable SetPopupMenuVal(string win, string control, string list=defaultValue, string func=defaultValue)
Sets the popupmenu value.
References ASSERT, CONTROL_TYPE_POPUPMENU, GetPopupMenuList, IsEmpty, MAX_COMMANDLINE_LENGTH, POPUPMENULIST_TYPE_OTHER.
Referenced by BSP_DynamicStartupSettings, BSP_UnsetDynamicStartupSettingsOfDataBrowser, ButtonProc_Hrdwr_P_UpdtDAClist, DAP_EphysPanelStartUpSettings.
string SetPopupMenuString(string win, string control, string str)
Sets the popupmenu string.
win target window control target control str popupmenu string to select. Supports wildcard character(*) set string with wildcard expanded
References ASSERT, CONTROL_TYPE_POPUPMENU, GetPopupMenuString.
Referenced by PGC_SetAndActivateControl, SetAnalysisFunctionIfFuncExists, WBP_ListBoxProc_AnalysisParams.
string GetValDisplayAsString(string win, string control)
Returns the contents of a ValDisplay.
References ASSERT, CONTROL_TYPE_VALDISPLAY.
Referenced by DAP_CheckSettingsAcrossYoked, SetValDisplay.
variable GetValDisplayAsNum(string win, string control)
Returns the contents of a ValDisplay as a number.
References ASSERT, CONTROL_TYPE_VALDISPLAY.
Referenced by DAP_CheckSettings, DB_UpdateLastSweepControls, DC_PrepareLBNEntries, DC_ReturnTotalLengthIncrease, DQ_StopOngoingDAQHelper, IDX_CalculcateActiveSetCount, PSQ_Chirp, PSQ_CR_DetermineBoundsAction, PSQ_DAScale, PSQ_EvaluateBaselineChunks, PSQ_GetNumberOfChunks, PSQ_PB_CreateTestpulseEpochs, PSQ_Ramp, RA_GetTotalNumberOfSweepsLowLev, switchHolding.
variable GetSliderPositionIndex(string win, string control)
Returns the slider position.
References ASSERT, CONTROL_TYPE_SLIDER.
Referenced by BSP_GatherTiledGraphSettings, DAP_LockDevice, PA_GatherSettings, ReachTargetVoltage, SC_ReactToQCFailures.
variable SetSliderPositionIndex(string win, string control, variable index)
Sets the slider position.
References ASSERT, CONTROL_TYPE_SLIDER.
variable SetValDisplay(string win, string control, variable var=defaultValue, string str=defaultValue, string format=defaultValue)
Set a ValDisplay.
win panel control GUI control var numeric variable to set format format string referencing the numeric variable var str path to global variable or wave element The following parameter combinations are valid: var var and format str
References ASSERT, GetValDisplayAsString.
Referenced by BSP_BindListBoxWaves, BSP_DynamicSweepControls, BSP_UpdateSweepControls, DAP_OneTimeCallAfterDAQ, DAP_UpdateDAQControls, DAP_UpdateOnsetDelay, DAP_UpdateSweepSetVariables, DB_UpdateLastSweepControls, DQM_Timer, DQS_Timer, P_SetAndGetPressure, P_SetLEDValueAssoc, PGC_SetAndActivateControl, RA_StepSweepsRemaining, RA_WaitUntiIITIDone, TPS_StartTestPulseForeground, UpdateCurrentSize, UpdateEstimatedSizeAfterwards.
variable ControlExists(string win, string control)
Check if a given control exists.
Referenced by BSP_MainPanelButtonToggle, FindControl, SetControlInEvent.
string FindControl(string control)
Return the full subwindow path to the windows the control belongs to.
References ControlExists, GetAllWindows.
Referenced by SetControlInEvent.
string FindNotebook(string nb)
Return the full subwindow path to the given notebook.
References GetAllWindows.
Referenced by SetControlInEvent.
variable GetTabID(string win, string ctrl)
Returns the number of the current tab.
win window name ctrl name of the control
References ASSERT, CONTROL_TYPE_TAB.
Referenced by AI_UpdateAmpModel, BSP_UpdateSweepNote, DAP_ChangeHeadStageMode, DAP_UpdateYokeControls, DAP_WindowHook, IVS_ConfigureMCC, P_MethodBreakIn, P_MethodClear, P_MethodSeal, PGC_ShowControlInTab, WB_MakeWaveBuilderWave, WBP_ShowFFTSpectrumIfReq, WBP_UpdateControlAndWave, WBP_UpdateDependentControls, WBP_UpdatePanelIfAllowed.
variable SetControlUserData(string win, string control, string key, string value)
Set value as the user data named key.
win window name control name of the control key user data identifier value user data value
References ASSERT.
Referenced by AdaptDependentControls, DAP_EphysPanelStartUpSettings, DAP_OneTimeCallBeforeDAQ, DAP_UpdateDaEphysStimulusSetPopups, WBP_UpdateDependentControls.
std::tuple< RGBColor > GetTraceColor(variable index)
Get distinctive trace colors for a given index.
Holds 21 different trace colors, code originally from http://www.igorexchange.com/node/6532 but completely rewritten and bug-fixed. The colors are "Twenty two colors of maximum contrast" by L. Kelly, see http://www.iscc.org/pdf/PC54_1724_001.pdf, where the color white has been removed.
References ASSERT.
Referenced by AverageWavesFromSameYAxisIfReq, FitResistance, GetHeadstageColor, PA_LayoutGraphs, PA_ShowPulses, WBP_GetSweepColor.
std::tuple< variable, variable > GetAxisRange(string graph, string axis, variable mode=defaultValue)
Query the axis minimum and maximum values.
For none existing graph or axis NaN is returned for minimum and high. The return value for autoscale axis depends on the mode flag: AXIS_RANGE_INC_AUTOSCALED -> [0, 0] AXIS_RANGE_DEFAULT -> [NaN, NaN] graph graph name axis axis name mode [optional:default AXIS_RANGE_DEFAULT] optional mode option, see AxisRangeModeConstants minimum and maximum value of the axis range
References ASSERT, AXIS_RANGE_DEFAULT, AXIS_RANGE_INC_AUTOSCALED, isEmpty.
Referenced by GetAxesRanges, PA_DrawScaleBarsHelper, SCOPE_CreateGraph.
variable GetAxisOrientation(string graph, string axes)
Return the orientation of the axis as numeric value.
one of AxisOrientationConstants
References AXIS_ORIENTATION_BOTTOM, AXIS_ORIENTATION_LEFT, AXIS_ORIENTATION_RIGHT, AXIS_ORIENTATION_TOP, DoAbortNow.
Referenced by AutoscaleVertAxisVisXRange, AverageWavesFromSameYAxisIfReq, EqualizeVerticalAxesRanges, GetAxesRanges, HorizExpandWithVisX, LBV_EntryDescription, SetAxesRanges.
wave GetAxesRanges(string graph=defaultValue, string axesRegexp=defaultValue, variable orientation=defaultValue, variable mode=defaultValue)
Returns a wave with the minimum and maximum values of each axis.
Use SetAxesRanges to set the minimum and maximum values GetAxisRange graph Name of graph axesRegexp [optional: default not set] filter axes names list by this optional regular expression orientation [optional: default not set] filter orientation of axes see AxisOrientationConstants mode [optional: default AXIS_RANGE_DEFAULT] filter returned axis information by mode see AxisRangeModeConstants free wave with rows = axes, cols = axes info, dimlabel of rows is axis name
References AXIS_RANGE_DEFAULT, COLS, GetAxisOrientation, GetAxisRange, ROWS.
Referenced by DB_UpdateSweepPlot, SB_UpdateSweepPlot, SCOPE_CreateGraph, UpdateSweepInGraph, WBP_DisplaySetInPanel, WBP_ShowFFTSpectrumIfReq.
variable SetAxesRanges(string graph, wave ranges=defaultValue, string axesRegexp=defaultValue, variable orientation=defaultValue, variable mode=defaultValue)
Set the range of all axes as stored by GetAxesRange.
Includes a heuristic if the name of the axis changed after GetAxesRange. The axis range is also restored if its index in the sorted axis list and its orientation is the same. GetAxisRange graph Name of graph ranges wave with graph ranges as set in GetAxesRanges axesRegexp [optional: default not set] filter axes names list by this optional regular expression orientation [optional: default not set] filter orientation of axes see AxisOrientationConstants mode [optional: default 0] axis set mode see AxisRangeModeConstants
References ASSERT, AXIS_RANGE_DEFAULT, AXIS_RANGE_USE_MINMAX, COLS, GetAxisOrientation, IsFinite, ROWS.
Referenced by DB_UpdateSweepPlot, SB_UpdateSweepPlot, SCOPE_CreateGraph, UpdateSweepInGraph, WBP_DisplaySetInPanel, WBP_ShowFFTSpectrumIfReq.
string GetNextFreeAxisName(string graph, string axesBaseName)
Returns the next axis name in a row of consecutive and already existing axis names.
Referenced by LBV_AddTraceToLBGraph, LBV_AddTraceToLBGraphTPStorage.
string GetUniqueAxisName(string graph, string axesBaseName)
Return a unique axis name.
References ASSERT.
Referenced by SBE_FillExportSettings.
variable SetGuiControlValue(string win, string control, string value)
Generic wrapper for setting a control's value pass in the value as a string, and then decide whether to change to a number based on the type of control.
References ASSERT, CONTROL_TYPE_CHECKBOX, CONTROL_TYPE_POPUPMENU, CONTROL_TYPE_SETVARIABLE, CONTROL_TYPE_SLIDER, GetInternalSetVariableType, GetRecreationMacroAndType, SET_VARIABLE_BUILTIN_NUM, SET_VARIABLE_BUILTIN_STR, SetCheckBoxState, SetPopupMenuIndex, SetSetVariable, SetSetVariableString.
Referenced by DAP_SyncGuiFromLeaderToFollower.
string GetGuiControlValue(string win, string control)
Generic wrapper for getting a control's value.
References ASSERT, CONTROL_TYPE_CHECKBOX, CONTROL_TYPE_POPUPMENU, CONTROL_TYPE_SETVARIABLE, CONTROL_TYPE_SLIDER, GetCheckBoxState, GetInternalSetVariableType, GetPopupMenuIndex, GetSetVariable, GetSetVariableString, SET_VARIABLE_BUILTIN_NUM, SET_VARIABLE_BUILTIN_STR.
Referenced by DAP_CheckSettingsAcrossYoked, DAP_SyncGuiFromLeaderToFollower.
string GetGuiControlState(string win, string control)
Generic wrapper for getting a controls state (enabled, hidden, disabled)
References ASSERT.
variable SetGuiControlState(string win, string control, string controlState)
Generic wrapper for setting a controls state (enabled, hidden, disabled)
References ASSERT.
variable IsControlDisabled(string win, string control)
Return one if the given control is disabled, zero otherwise.
References ASSERT, DISABLE_CONTROL_BIT.
Referenced by BSP_ScaleAxes, DAP_AdaptAutoTPColorAndDependent, DAP_CheckSettingsAcrossYoked, DAP_OneTimeCallBeforeDAQ, DAP_UnlockDevice, SBE_FillExportSettings, SetControlInEvent, WBP_MainWindowHook.
variable IsControlHidden(string win, string control)
Return one if the given control is hidden, zero otherwise.
References ASSERT, HIDDEN_CONTROL_BIT.
string GetMainWindow(string subwindow)
Return the main window name from a full subwindow specification.
subwindow window name including subwindows, e.g. panel#subWin1#subWin2
Referenced by AD_PlotBounds, AR_ButtonProc_RemoveRanges, AR_MainListBoxProc, AR_SetVarProcCutoffLength, AR_UpdateTracesIfReq, BSP_AxisScalingLevelCross, BSP_BindListBoxWaves, BSP_ButtonProc_ChangeSweep, BSP_ButtonProc_Panel, BSP_ButtonProc_RestoreData, BSP_CheckBoxProc_ArtRemoval, BSP_CheckBoxProc_PerPulseAver, BSP_CheckBoxProc_SweepFormula, BSP_CheckProc_ChangedSetting, BSP_CheckProc_OverlaySweeps, BSP_CheckProc_ScaleAxes, BSP_ClosePanelHook, BSP_DoTimeAlignment, BSP_GetBrowserType, BSP_GetDevice, BSP_GetFolder, BSP_GetPanel, BSP_GetSweepControlsPanel, BSP_ScaleAxes, BSP_SetBrowserType, BSP_SetDevice, BSP_SetFolder, BSP_SweepFormulaHook, BSP_SweepsAndMouseWheel, BSP_UnHideSettingsHistory, BSP_UnHideSweepControls, BSP_UpdateSweepControls, BSP_UpdateSweepNote, CONF_AllWindowsToJSON, CONF_JSONToWindow, CONF_RestoreWindow, CONF_SaveDAEphys, CONF_SaveWindow, DAP_CommentPanelHook, DAP_EphysPanelStartUpSettings, DB_AddSweepToGraph, DB_ButtonProc_Panel, DB_GetMainGraph, DB_OpenDataBrowser, DB_PopMenuProc_LockDBtoDevice, DB_ResetAndStoreCurrentDBPanel, HasPanelLatestVersion, IH_ResetScaling, LayoutGraph, LBV_CloseSettingsHistoryHook, LBV_GetSettingsHistoryPanel, OVS_GetSweepAndExperiment, OVS_HighlightSweep, PA_DrawScaleBarsHelper, PA_GatherSettings, PA_GenerateAllPulseWaves, PA_GetGraphPrefix, PA_GetGraphs, PA_PreProcessPulses, PA_Update, PostPlotTransformations, RemoveSweepFromGraph, SB_AddSweepToGraph, SB_ButtonProc_ExportTraces, SB_OpenSweepBrowser, SB_SweepBrowserWindowHook, SB_UpdateSweepPlot, SBE_ShowExportPanel, TimeAlignCursorMovedHook, TimeAlignHandleCursorDisplay, TimeAlignUpdateControls, TUD_Init, UpdateSweepInGraph.
string GetCurrentWindow()
Return the currently active window.
Referenced by CONF_RestoreWindow, CONF_SaveDAEphys, CONF_SaveWindow, DAP_CreateDAEphysPanel, DAP_EphysPanelStartUpSettings, DB_OpenDataBrowser, DB_ResetAndStoreCurrentDBPanel, HorizExpandWithVisX, ID_AskUserForSettings, ID_GetPopupEntries, SB_OpenSweepBrowser.
variable GraphHasCursors(string graph)
Return 1 if there are cursors on the graph, 0 if not.
References CURSOR_NAMES.
Referenced by GetCursorInfos.
wave GetCursorInfos(string graph)
Return a 1D text wave with all infos about the cursors.
Returns an invalid wave reference when no cursors are present. Counterpart to RestoreCursors(). The data is sorted like CURSOR_NAMES.
References CURSOR_NAMES, GraphHasCursors.
Referenced by DB_UpdateSweepPlot, SB_UpdateSweepPlot, UpdateSweepInGraph, WBP_ShowFFTSpectrumIfReq.
variable RestoreCursors(string graph, WaveTextOrNull cursorInfos)
Restore the cursors from the info of GetCursorInfos().
References IsEmpty, ReplaceWordInString, ROWS.
Referenced by DB_UpdateSweepPlot, SB_UpdateSweepPlot, UpdateSweepInGraph, WBP_ShowFFTSpectrumIfReq.
variable AutoscaleVertAxisVisXRange(string graph)
Autoscale all vertical axes in the visible x range.
References AXIS_ORIENTATION_LEFT, AXIS_ORIENTATION_RIGHT, GetAxisOrientation.
Referenced by BSP_ScaleAxes, HorizExpandWithVisX.
variable GetInternalSetVariableType(string recMacro)
Return the type of the variable of the SetVariable control.
one of GetInternalSetVariableTypeReturnTypes
References ASSERT, SET_VARIABLE_BUILTIN_NUM, SET_VARIABLE_BUILTIN_STR, SET_VARIABLE_GLOBAL.
Referenced by CONF_ControlToJSON, CONF_RestoreControl, GetGuiControlValue, PGC_SetAndActivateControl, SetGuiControlValue.
variable ExtractLimitsFromRecMacro(string recMacro, variable *minVal, variable *maxVal, variable *incVal)
Referenced by ExtractLimits, GetLimitConstrainedSetVar.
variable ExtractLimits(string win, string control, variable *minVal, variable *maxVal, variable *incVal)
Extract the limits specification of the control and return it in minVal, maxVal and incVal
0 on success, 1 if no specification could be found ExtractLimitsFromRecMacro for a faster way if you already have the recreation macro
References ExtractLimitsFromRecMacro, GetRecreationMacroAndType.
Referenced by CheckIfValueIsInsideLimits, ShowSetVariableLimitsSelectionPopup.
variable CheckIfValueIsInsideLimits(string win, string control, variable val)
Check if the given value is inside the limits defined by the control.
- 0: outside limits 1: inside limits, i.e. val lies in the range [min, max] NaN: no limits could be found
References ExtractLimits.
Referenced by AI_UpdateAmpModel.
variable GetLimitConstrainedSetVar(string recMacro, variable val)
Returns a value that is constrained by the limits defined by the control.
val <= control max and val >= contorl min
References ExtractLimitsFromRecMacro.
Referenced by PGC_SetAndActivateControl, SetSetVariable.
variable GetFunctionParameterType(string func, variable paramIndex)
Return the parameter type a function parameter.
func name of the function paramIndex index of the parameter
References ASSERT.
Referenced by PGC_GetProcAndCheckParamType.
string GetValueFromRecMacro(string key, string recMacro)
Return an entry from the given recreation macro.
The recreation macro of a single GUI control looks like: embed:rst:leading-asterisk * .. code-block:: igorpro * * PopupMenu popup_ctrl,pos={1.00,1.00},size={55.00,19.00},proc=PGCT_PopMenuProc * PopupMenu popup_ctrl,mode=1,popvalue="Entry1",value= #"\"Entry1;Entry2;Entry3\"" * This function allows to extract key/value pairs from it. key non-empty string (must be followed by = in the recreation macro) recMacro GUI control recreation macro as returned by ControlInfo
References ASSERT, IsEmpty.
Referenced by PGC_GetProcAndCheckParamType, PGC_SetAndActivateControl, SearchForInvalidControlProcs.
variable SearchForInvalidControlProcs(string win, variable warnOnEmpty=defaultValue)
Search for invalid control procedures in the given panel or graph.
Searches recursively in all subwindows. win panel or graph warnOnEmpty [optional, default to false] print out controls which don't have a control procedure but can have one. 1 on error, 0 if everything is fine.
References CONTROL_TYPE_GROUPBOX, CONTROL_TYPE_VALDISPLAY, ControlWindowToFront, GetNumericSubType, GetRecreationMacroAndType, GetValueFromRecMacro, IsEmpty, REC_MACRO_PROCEDURE, SearchForInvalidControlProcs.
Referenced by AB_BrowserStartupSettings, DAP_EphysPanelStartUpSettings, DB_ResetAndStoreCurrentDBPanel, SearchForInvalidControlProcs, WBP_StartupSettings.
variable GetNumericSubType(string subType)
Convert the function subType names for GUI control procedures to a numeric value as used by ControlInfo
References ASSERT, CONTROL_TYPE_BUTTON, CONTROL_TYPE_CHECKBOX, CONTROL_TYPE_LISTBOX, CONTROL_TYPE_POPUPMENU, CONTROL_TYPE_SETVARIABLE, CONTROL_TYPE_SLIDER, CONTROL_TYPE_TAB.
Referenced by SearchForInvalidControlProcs.
variable GetControlType(string win, string control)
Return the numeric control type.
one of GUIControlTypes
References ASSERT.
Referenced by SetControlInEvent.
variable DoesControlHaveInternalString(string recMacro)
Determines if control stores numeric or text data.
Referenced by DAG_GetSpecificCtrlNum, DAG_GetSpecificCtrlTxT.
variable GetCheckBoxMode(string win, string checkBoxName)
Returns checkbox mode.
References ASSERT, IsFinite.
variable GetListBoxSelRow(string win, string ctrl)
Returns the selected row of the ListBox for some modes without selection waves.
References ASSERT.
Referenced by AD_SelectResult, AR_HighlightArtefactsEntry.
variable IsInsideRect(Point *loc, RectF *r)
Check if the location loc is inside the rectangle r
Referenced by DAP_WindowHook, WBP_MainWindowHook.
variable GetControlCoordinates(string win, string ctrl, RectF *s)
Return the coordinates of the control borders relative to the top left corner in pixels.
References ASSERT.
Referenced by DAP_WindowHook, WBP_MainWindowHook.
string GetNotebookText(string win, variable mode=defaultValue)
Get the text (plain or formatted) from the notebook.
References ASSERT.
Referenced by BSP_UpdateHelpNotebook, DAP_FormatCommentString, DAP_SerializeCommentNotebook, DeviceHasUserComments, WBP_ButtonProc_AddParam.
variable ReplaceNotebookText(string win, string text)
Replace the contents of the notebook.
References ASSERT.
Referenced by AB_ButtonProc_OpenCommentNB, BSP_UpdateHelpNotebook, BSP_UpdateSweepNote, DAP_ClearCommentNotebook, DAP_OpenCommentPanel, DB_ResetAndStoreCurrentDBPanel, LBV_ClearGraph, LBV_EntryDescription, PSQ_PipetteInBath, SetControlInEvent.
variable AppendToNotebookText(string win, string text)
Append to a notebook.
References ASSERT.
Referenced by DAP_AddUserComment.
variable NotebookSelectionAtEnd(string win)
Select the end in the given notebook.
The selection is the place where the user would naïvely enter new text.
References ASSERT.
Referenced by DAP_AddUserComment, DAP_SerializeCommentNotebook, MEN_OpenMIESLogFile, MEN_OpenZeroMQXOPLogFile.
wave GetUserdataKeys(string recMacro)
Retrieves named userdata keys from a recreation macro string.
recMacro recreation macro string Textwave with all unqiue entries or $"" if nothing could be found.
References ASSERT, EnsureLargeEnoughWave, GetUniqueEntries, USERDATA_PREFIX, USERDATA_SUFFIX.
string ControlTypeToName(variable ctrlType)
Converts an Igor control type number to control name.
ctrlType ctrl type of Igor control Igor name of control type
References EXPCONFIG_GUI_CTRLLIST, EXPCONFIG_GUI_CTRLTYPES.
Referenced by CONF_ControlToJSON.
variable Name2ControlType(string ctrlName)
Converts an Igor control name to control type number.
ctrlName Name of Igor control Igor control type number
References EXPCONFIG_GUI_CTRLLIST, EXPCONFIG_GUI_CTRLTYPES.
variable WindowTypeCanHaveChildren(string wName)
Checks if a certain window can act as valid host for subwindows developer note: The only integrated Igor function that does this is ChildWindowList. Though, ChildWindowList generates an RTE for non-valid windows, where this check function does not.
wName window name that should be checked to be a valid host for subwindows 1 if window is a valid host, 0 otherwise
References WINTYPE_GRAPH, WINTYPE_PANEL.
Referenced by GetAllWindowsImpl.
string GetAllWindows(string wName)
Recursively build a list of windows, including all child windows, starting with wName.
wName parent window name to start with A string containing names of windows. This list is a semicolon separated list. It will include the window wName and all of its children and children of children, etc.
References GetAllWindowsImpl.
Referenced by CONF_AllWindowsToJSON, CONF_FindWindow, FindControl, FindNotebook, IH_ResetScaling, TUD_Clear.
static variable GetAllWindowsImpl(string wName, string *windowList)
References GetAllWindowsImpl, WindowTypeCanHaveChildren.
Referenced by GetAllWindows, GetAllWindowsImpl.
variable PanelIsType(string device, string typeTag)
Checks if a window is tagged as certain type.
device Window name to check typeTag one of PANELTAG_* constants panelTags returns 1 if window is a DA_Ephys panel
References EXPCONFIG_UDATA_PANELTYPE, WindowExists.
Referenced by CONF_RestoreDAEphys, CONF_RestoreWindow, CONF_SaveDAEphys, CONF_SaveWindow.
variable ShowSetVariableLimitsSelectionPopup(WMSetVariableAction *sva)
Show a contextual popup menu which allows the user to change the set variable limit's increment.
Expects the ctrl to have the named user data "DefaultIncrement" Works only on right mouse click on the title or the value field, not the up/down arrow buttons
References ASSERT, ExtractLimits, IsFinite, IsNaN, NumericWaveToList, SetSetVariableLimits, str2numSafe.
Referenced by DAP_SetVar_SetScale, DAP_SetVarProc_CAA, DAP_SetVarProc_DA_Scale.
variable DrawScaleBar(string graph, variable x0, variable y0, variable x1, variable y1, string unit=defaultValue, variable drawLength=defaultValue, variable labelOffset=defaultValue, variable newlineBeforeUnit=defaultValue)
Draw a scale bar on a graph.
graph graph x0 horizontal coordinate of first point y0 vertical coordinate of first point x1 horizontal coordinate of second point y1 vertical coordinate of second point unit [optional] data unit when drawing the label drawLength [optional, defaults to false] true/false for outputting the label labelOffset [optional] offset in current coordinates of the label newlineBeforeUnit [optional] Use a newline before the unit instead of a space
References ASSERT, DEBUGPRINT, IsEmpty, NUMBER_UNIT_SPACE.
Referenced by PA_DrawScaleBarsHelper.
variable AccelerateHideTraces(string graph, WaveText w, variable h, variable s)
Accelerated setting of multiple traces in a graph to un/hidden.
graph name of graph window w 1D text wave with trace names h number of traces in text wave s new hidden state
References ASSERT.
Referenced by PA_ShowPulses, TiledGraphAccelerateDraw.
variable AccelerateModLineSizeTraces(string graph, WaveText w, variable h, variable l)
Accelerated setting of line size of multiple traces in a graph.
graph name of graph window w 1D text wave with trace names h number of traces in text wave l new line size
References ASSERT.
Referenced by PA_ShowPulses.
std::tuple< string, variable > ParsePopupMenuValue(string recMacro)
Return the value and type of the popupmenu list.
value extracted string with the contents of value from the recreation macro type popup menu list type, one of PopupMenuListTypes
References POPUPMENULIST_TYPE_BUILTIN, POPUPMENULIST_TYPE_OTHER, RemovePrefix.
Referenced by PGC_SetAndActivateControl.
string GetPopupMenuList(string value, variable type)
Return the popupmenu list entries.
value String with a list or function (what you enter with PopupMenu value=#XXX) type One of PopupMenuListTypes
References ASSERT, GetTemporaryString, POPUPMENULIST_TYPE_BUILTIN, POPUPMENULIST_TYPE_OTHER.
Referenced by PGC_SetAndActivateControl, SetPopupMenuVal.
std::tuple< string, variable > GetRecreationMacroAndType(string win, string control)
Return the recreation macro and the type of the given control.
References ASSERT, WindowExists.
Referenced by DAG_GetSpecificCtrlNum, DAG_GetSpecificCtrlTxT, ExtractLimits, GetControlSettingImpl, SearchForInvalidControlProcs, SetGuiControlValue.
variable GetControlSettingVar(string win, string control, string setting, variable defValue=defaultValue)
Query a numeric GUI control property.
References GetControlSettingImpl, str2numSafe.
Referenced by DAP_UpdateSweepLimitsAndDisplay.
string GetControlSettingStr(string win, string control, string setting, string defValue=defaultValue)
Query a string GUI control property.
References GetControlSettingImpl, PossiblyUnquoteName.
static std::tuple< string, variable > GetControlSettingImpl(string win, string control, string setting)
References ASSERT, GetRecreationMacroAndType.
Referenced by GetControlSettingStr, GetControlSettingVar.
variable AdaptDependentControls(string device, string controls, variable newState)
Check and disable dependent controls.
Enables a list of checkbox controls and stores their current values as user data before disabling them. On switching back their previous values are restored and they are also enabled again.
References CHECKBOX_SELECTED, DAG_GetNumericalValue, DisableControls, EnableControls, PGC_SetAndActivateControl, SetControlUserData.
Referenced by DAP_AdaptAutoTPColorAndDependent, DAP_CheckProc_MDEnable.
variable ReflowNotebookText(string win)
Adjust the "Normal" ruler in the notebook so that all text is visible.
Referenced by LBV_EntryDescription.