MIES_DAEphys_GuiState.ipf
variable DAG_RecordGuiStateNum(string device, wave GUIState=defaultValue)
Records the state of the DA_ephys panel into the numerical GUI state wave.
References ASSERT, CHANNEL_CONTROL_ALARM_MAX, CHANNEL_CONTROL_ALARM_MIN, CHANNEL_CONTROL_CHECK, CHANNEL_CONTROL_GAIN, CHANNEL_CONTROL_INDEX_END, CHANNEL_CONTROL_SCALE, CHANNEL_CONTROL_WAVE, CHANNEL_TYPE_ADC, CHANNEL_TYPE_ALARM, CHANNEL_TYPE_ASYNC, CHANNEL_TYPE_DAC, CHANNEL_TYPE_HEADSTAGE, CHANNEL_TYPE_TTL, COLS, COMMON_CONTROL_GROUP_COUNT_NUM, CONTROL_TYPE_POPUPMENU, DAG_ControlStatusWave, DAG_GetAllHSMode, GetAllDAEphysPopMenuIndex, GetAllDAEphysSetVarNum, GetDA_EphysGuiStateNum, GetSpecialControlLabel, ROWS.
Referenced by DAP_LockDevice, GetDA_EphysGuiStateNum.
variable DAG_RecordGuiStateTxT(string device, wave GUIState=defaultValue)
Records the state of the DA_ephys panel into the textual GUI state wave.
References ASSERT, CHANNEL_CONTROL_INDEX_END, CHANNEL_CONTROL_SEARCH, CHANNEL_CONTROL_TITLE, CHANNEL_CONTROL_UNIT, CHANNEL_CONTROL_WAVE, CHANNEL_TYPE_ADC, CHANNEL_TYPE_ASYNC, CHANNEL_TYPE_DAC, CHANNEL_TYPE_TTL, COLS, COMMON_CONTROL_GROUP_COUNT_TXT, GetAllDAEphysPopMenuString, GetAllDAEphysSetVarTxT, GetDA_EphysGuiStateTxT, GetSpecialControlLabel, ROWS.
Referenced by DAP_LockDevice, GetDA_EphysGuiStateTxT.
variable DAG_GetNumericalValue(string device, string ctrl, variable index=defaultValue)
Query a control value from the numerical gui state wave.
This does return the zero-based index for PopupMenues. Convienience wrapper to make the call sites nicer. device device ctrl control name index [optional, default to NaN] Some control entries have multiple entries per headstage/channel/etc.
References BUG, CheckIfClose, CONTROL_TYPE_POPUPMENU, DP_DebuggingEnabledForCaller, EqualValuesOrBothNaN, GetDA_EphysGuiStateNum, IsFinite, IsNaN.
Referenced by AdaptDependentControls, AFM_CallAnalysisFunctions, AI_SetMIESHeadstage, AI_SyncGUIToAmpStorageAndMCCApp, AI_UpdateAmpModel, AI_UpdateAmpView, AS_GetSweepNumber, ASD_CheckAsynAlarmState, ASD_ReadChannel, ButtonProc_ManPP, BWO_CheckGlobalSettings, CheckProc_ClearEnable, CONF_GetAmplifierSettings, DAP_AdaptAssocHeadstageState, DAP_AllChanDASettings, DAP_ButtonProc_AmpCntrls, DAP_ButtonProc_TPDAQ, DAP_ChangeHeadStageMode, DAP_ChangeHeadstageState, DAP_CheckAnalysisFunctionAndParameter, DAP_CheckHeadStage, DAP_CheckProc_AmpCntrls, DAP_CheckProc_Channel_All, DAP_CheckProc_LockedLogic, DAP_CheckSettings, DAP_CheckSkipAhead, DAP_CheckStimset, DAP_HandleSingleDeviceDependentControls, DAP_OneTimeCallAfterDAQ, DAP_OneTimeCallBeforeDAQ, DAP_PopMenuChkProc_StimSetList, DAP_SetVarProc_AmpCntrls, DAP_TPGUISettingToWave, DAP_TPSettingsToGUI, DAP_TPSettingsToWave, DAP_UnlockDevice, DAP_UpdateClampmodeTabs, DAP_UpdateITIAcrossSets, DAP_UpdateOnsetDelay, DAP_UpdateSweepLimitsAndDisplay, DAP_UpdateSweepSetVariables, DC_CalculateChannelColumnNo, DC_GetConfiguration, DC_GetStopCollectionPoint, DC_LongestOutputWave, DC_MakeHelperWaves, DC_PrepareLBNEntries, DC_ReturnTotalLengthIncrease, DQ_ApplyAutoBias, DQM_BkrdDataAcq, DQM_StartDAQMultiDevice, DQS_BkrdDataAcq, DQS_DataAcq, DQS_StartDAQSingleDevice, ED_createAsyncWaveNoteTags, ED_createWaveNoteTags, IDX_CalculcateActiveSetCount, IDX_GetCurrentSets, IDX_GetSetsInRange, IDX_HandleIndexing, IDX_IndexSingleChannel, MSQ_CommonPreDAQ, MSQ_DAScale, P_ApplyNegV, P_CheckAll, P_Enable, P_EnableButtonsIfValid, P_GetAutoUserOff, P_GetUserAccess, P_PressureControl, P_UpdatePressureDataStorageWv, PSQ_Chirp, PSQ_CR_DetermineBoundsAction, PSQ_DAScale, PSQ_EvaluateBaselineChunks, PSQ_EvaluateBaselineProperties, PSQ_GetNumberOfChunks, PSQ_PB_CreateTestpulseEpochs, PSQ_Ramp, PSQ_Rheobase, RA_ContinueOrStop, RA_Counter, RA_GetTotalNumberOfSweepsLowLev, RA_HandleITI, RA_HandleITI_MD, RA_RecalculateITI, RA_SkipSweepCalc, RA_StepSweepsRemaining, SCOPE_CreateGraph, SCOPE_GetCheckBoxesForAddons, SCOPE_KillScopeWindowIfRequest, SCOPE_SetADAxisLabel, SCOPE_UpdateGraph, SCOPE_UpdateOscilloscopeData, SCOPE_UpdatePowerSpectrum, SetDAScale, switchHolding, SWS_DeleteDataWaves, SWS_GetRawDataFPType, SWS_SaveAcquiredData, TestAnalysisFunction_V1, TPS_StartTestPulseSingleDevice.
string DAG_GetTextualValue(string device, string ctrl, variable index=defaultValue)
Query a control value from the textual gui state wave.
Convienience wrapper to make the call sites nicer. device device ctrl control name index [optional, default to NaN] Some control entries have multiple entries per headstage/channel/etc.
References BUG, DP_DebuggingEnabledForCaller, GetDA_EphysGuiStateTxT, IsEmpty, IsFinite, IsNaN, IsNull.
Referenced by DAP_AddUserComment, DAP_CheckHeadStage, DAP_CheckSettings, DAP_CheckStimset, DAP_DeviceIsLeader, DAP_GetSampInt, DC_PlaceDataInDAQConfigWave, DC_PrepareLBNEntries, DeviceHasUserComments, ED_createAsyncWaveNoteTags, P_ButtonProc_UserPressure, PSQ_EvaluateBaselineProperties, PSQ_PB_CreateTestpulseEpochs, PSQ_PB_GetPrePulseBaselineDuration, PSQ_SetSamplingIntervalMultiplier, SetDAScale, SWS_SaveAcquiredData.
wave DAG_GetChannelState(string device, variable type)
Return a free wave of the status of the checkboxes specified by channelType, uses GetDA_EphysGuiStateNum() instead of GUI queries.
type one of the type constants from ChannelTypeAndControlConstants device panel title
References ASSERT, CHANNEL_TYPE_ADC, CHANNEL_TYPE_ALARM, CHANNEL_TYPE_ASYNC, CHANNEL_TYPE_DAC, CHANNEL_TYPE_HEADSTAGE, CHANNEL_TYPE_TTL, GetDA_EphysGuiStateNum, GetNumberFromType.
Referenced by AFM_CallAnalysisFunctions, AFM_UpdateAnalysisFunctionWave, AI_UpdateAmpModel, CONF_GetAmplifierSettings, DAG_GetActiveHeadstages, DAG_HeadstageIsHighestActive, DAP_ChangeHeadstageState, DAP_CheckSettings, DAP_OneTimeCallBeforeDAQ, DAP_SyncChanAmpAssignToActiveHS, DC_AreTTLsInRackChecked, DC_GetConfiguration, DC_GetFilteredChannelState, DC_NoOfChannelsSelected, DC_PlaceDataInDAQConfigWave, DQ_ApplyAutoBias, ED_createAsyncWaveNoteTags, ED_TPDocumentation, FitResistance, IDX_MaxSets, IDX_StepsInSetWithMaxSweeps, LastStimSetRun, MSQ_DAScale, MSQ_DeterminePulseDuration, MSQ_FastRheoEst, PSQ_Chirp, PSQ_CR_DetermineCycles, PSQ_DAScale, PSQ_DeterminePulseDuration, PSQ_EvaluateBaselineProperties, PSQ_PipetteInBath, PSQ_Ramp, PSQ_Rheobase, PSQ_SquarePulse, ReachTargetVoltage, SC_SpikeControl, setHolding, setIClampMode, setVClampMode, SI_FillActiveChannelsStruct, SI_NI_CalculateMinSampInterval, switchHolding, TP_AutoAmplitudeAndBaseline, TP_AutoBaseline, TP_AutoDisableIfFinished, TP_RecordTP, TP_UpdateTPLBNSettings.
wave DAG_GetActiveHeadstages(string device, variable clampMode)
Return a wave with NUM_HEADSTAGES rows with 1 where the given headstages is active and in the given clamp mode.
References AI_AssertOnInvalidClampMode, CHANNEL_TYPE_HEADSTAGE, DAG_GetChannelState, GetDA_EphysGuiStateNum, NUM_HEADSTAGES.
Referenced by DAG_HeadstageIsHighestActive, MSQ_CreateOverrideResults, MSQ_DAScale, MSQ_FastRheoEst, SC_GetHeadstageQCForSetCount, SC_GetTrials, SC_HeadstageQC, SC_ProcessPulses, SC_ReactToQCFailures, SC_SpikeControl, SC_SpikeCountsCalc, SC_SpikeCountsQC, SC_SpikePositionQC, SC_SpontaneousSpikingCheckQC, TP_AutoTPActive.
variable DAG_HeadstageIsHighestActive(string device, variable headstage, variable clampMode=defaultValue)
Return true/false if the given headstage is the highest active.
device device headstage headstage to check clampMode [optional, defaults to all clamp modes] Restrict to the given clamp mode
References CHANNEL_TYPE_HEADSTAGE, DAG_GetActiveHeadstages, DAG_GetChannelState, NUM_HEADSTAGES.
Referenced by AdjustDAScale, MSQ_CommonPreDAQ, MSQ_DAScale, MSQ_FastRheoEst, ReachTargetVoltage, SC_SpikeControl, SetControlInEvent.
wave DAG_GetChannelTextual(string device, variable channelType, variable controlType)
Return a free wave of the popup menu strings specified by channelType, uses GetDA_EphysGuiStateTxT() instead of GUI queries.
device panel title channelType one of the channel type constants from ChannelTypeAndControlConstants controlType one of the control type constants from ChannelTypeAndControlConstants
References GetDA_EphysGuiStateTxT, GetNumberFromType.
Referenced by AFM_CallAnalysisFunctions, DAP_CheckSettings, DC_GetConfiguration, DC_GetFilteredChannelState, DC_GotTPChannelWhileDAQ, DC_ITC_MakeTTLWave, DC_LongestOutputWave, DC_NI_MakeTTLWave, DC_PlaceDataInDAQConfigWave, DC_PrepareLBNEntries.
variable DAG_GetHeadstageState(string device, variable headStage)
Returns the headstage State.
References CHANNEL_CONTROL_CHECK, CHANNEL_TYPE_HEADSTAGE, GetDA_EphysGuiStateNum.
Referenced by DAP_ChangeHeadStageMode, DAP_SetHeadstageChanControls, P_IsHSActiveAndInVClamp.
variable DAG_GetHeadstageMode(string device, variable headStage)
the mode of the headstage defined in the locked DA_ephys panel, can be V_CLAMP_MODE or I_CLAMP_MODE or NC
References GetDA_EphysGuiStateNum.
Referenced by AdjustDAScale, AI_MIESAutoPipetteOffset, AI_UpdateAmpModel, CONF_GetAmplifierSettings, CONF_RestoreAmplifierSettings, DAP_AllChanDASettings, DAP_CheckHeadStage, DAP_CheckSettings, DAP_DACHasExpectedClampMode, DAP_SliderProc_MIESHeadStage, DAP_SyncChanAmpAssignToActiveHS, DC_PrepareLBNEntries, DC_UpdateHSProperties, DQ_ApplyAutoBias, Enforce_IC, Enforce_VC, P_IsHSActiveAndInVClamp, PSQ_Chirp, PSQ_DAScale, PSQ_PipetteInBath, PSQ_Ramp, PSQ_Rheobase, PSQ_SquarePulse, ReachTargetVoltage, switchHolding, TP_AutoAmplitudeAndBaseline, TP_AutoDisableIfFinished.
variable DAG_Update(string device, string controlName, variable val=defaultValue, string str=defaultValue)
Updates the state of a control in the GUIState numeric wave.
One or both parameters have to be passed. device device controlName control name val [optional] numerical value, 0-based index for popup menues str [optional] textual value
References ASSERT, COLS, DAP_ParsePanelControl, GetDA_EphysGuiStateNum, GetDA_EphysGuiStateTxT, GetSpecialControlLabel.
Referenced by AI_UpdateAmpView, CheckProc_ClearEnable, DAP_CheckProc_AD, DAP_CheckProc_AmpCntrls, DAP_CheckProc_Channel_All, DAP_CheckProc_HedstgeChck, DAP_CheckProc_IndexingState, DAP_CheckProc_InsertTP, DAP_CheckProc_LockedLogic, DAP_CheckProc_MDEnable, DAP_CheckProc_PowerSpectrum, DAP_CheckProc_RandomRA, DAP_CheckProc_RepeatedAcq, DAP_CheckProc_Settings_PUser, DAP_CheckProc_ShowScopeWin, DAP_CheckProc_SyncCtrl, DAP_CheckProc_TestPulseSett, DAP_CheckProc_UpdateGuiState, DAP_DAorTTLCheckProc, DAP_PopMenuChkProc_StimSetList, DAP_PopMenuProc_FixedSampInt, DAP_PopMenuProc_Headstage, DAP_PopMenuProc_OsciUpdMode, DAP_PopMenuProc_SampMult, DAP_PopMenuProc_UpdateGuiState, DAP_SetVar_SetScale, DAP_SetVar_UpdateGuiState, DAP_SetVarProc_AmpCntrls, DAP_SetVarProc_CAA, DAP_SetVarProc_Channel_Search, DAP_SetVarProc_DA_Scale, DAP_SetVarProc_NextSweepLimit, DAP_SetVarProc_skipAhead, DAP_SetVarProc_SyncCtrl, DAP_SetVarProc_TestPulseSett, DAP_SetVarProc_TotSweepCount, DAP_SliderProc_MIESHeadStage, DAP_ToggleCheckBoxes, DAP_UpdateStimulusSetPopup, DAP_UpdateSweepLimitsAndDisplay, EqualizeCheckBoxes, IDX_IndexSingleChannel, IDX_ResetStartFinishForIndexing, P_Check_ApproachNear, P_Check_SealAtm, SWS_SaveAcquiredData, ToggleCheckBoxes.
string DAG_GetUniqueSpecCtrlListNum(string device)
Returns a list of unique and type specific controls.
References ASSERT, DAG_GetSpecificCtrlNum, DAG_GetUniqueCtrlList, WindowExists.
Referenced by GetDA_EphysGuiStateNum.
string DAG_GetUniqueSpecCtrlListTxT(string device)
Returns a list of unique and type specific controls with textual values.
References ASSERT, DAG_GetSpecificCtrlTxT, DAG_GetUniqueCtrlList, WindowExists.
static wave DAG_ControlStatusWave(string device, variable type)
Returns a free wave of the status of the checkboxes specified by channelType.
The only caller should be DAG_RecordGuiStateNum(). type one of the type constants from ChannelTypeAndControlConstants device panel title
References CHANNEL_CONTROL_CHECK, GetCheckBoxState, GetNumberFromType, GetPanelControl.
Referenced by DAG_RecordGuiStateNum.
static wave DAG_GetAllHSMode(string device)
Return the mode of all DA_Ephys panel headstages.
All callers, except the ones updating the GUIState wave, should prefer DAG_GetHeadstageMode() instead.
References ASSERT, CHANNEL_CONTROL_CHECK, CHANNEL_TYPE_HEADSTAGE, DAP_GetInfoFromControl, GetPanelControl, NUM_HEADSTAGES.
Referenced by DAG_RecordGuiStateNum.
static string DAG_GetUniqueCtrlList(string device)
Parses a list of controls in the device and returns a list of unique controls.
References DAP_ParsePanelControl.
Referenced by DAG_GetUniqueSpecCtrlListNum, DAG_GetUniqueSpecCtrlListTxT.
static string DAG_GetSpecificCtrlNum(string device, string list)
Parses a list of controls and returns numeric checkBox, valDisplay, setVariable, popUpMenu, and slider controls.
References CONTROL_TYPE_CHECKBOX, CONTROL_TYPE_POPUPMENU, CONTROL_TYPE_SETVARIABLE, CONTROL_TYPE_SLIDER, CONTROL_TYPE_VALDISPLAY, DoesControlHaveInternalString, GetRecreationMacroAndType.
Referenced by DAG_GetUniqueSpecCtrlListNum.
static string DAG_GetSpecificCtrlTxT(string device, string list)
Parses a list of controls and returns textual valDisplay, setVariable and popUpMenu controls.
References CONTROL_TYPE_POPUPMENU, CONTROL_TYPE_SETVARIABLE, CONTROL_TYPE_VALDISPLAY, DoesControlHaveInternalString, GetRecreationMacroAndType.
Referenced by DAG_GetUniqueSpecCtrlListTxT.