MIES_DAC-Hardware.ipf
const double OLD_IGOR
const double UNHANDLED_CPP_EXCEPTION
const double SLOT_LOCKED_TO_OTHER_THREAD
const double SLOT_EMPTY
const double COULDNT_FIND_EMPTY_SLOT
const double ITC_DLL_ERROR
const double INVALID_DEVICETYPE_NUMERIC
const double INVALID_DEVICETYPE_STRING
const double DTN_DTS_DISAGREE
const double INVALID_CHANNELTYPE_NUMERIC
const double INVALID_CHANNELTYPE_STRING
const double CHN_CHS_DISAGREE
const double MUST_SPECIFY_CHN_OR_CHS
const double ITCCONFIGCHANNEL2_BAD_S
const double ITCCONFIGCHANNEL2_BAD_M
const double ITCCONFIGCHANNEL2_BAD_A
const double ITCCONFIGCHANNEL2_BAD_O
const double ITCCONFIGCHANNEL2_BAD_U
const double NEED_MIN_ROWS
const double F_FLAG_REQ_ITC18_18USB_1600
const double D_FLAG_REQUIRES_ITC1600
const double H_FLAG_REQUIRES_ITC1600
const double R_FLAG_REQUIRES_ITC1600
const double THREAD_DEVICE_ID_NOT_SET
variable HW_PrepareAcq(variable hardwareType, variable deviceID, variable mode, WaveOrNull data=defaultValue, HW_WAVE_GETTER_PROTOTYPE dataFunc=defaultValue, WaveOrNull config=defaultValue, HW_WAVE_GETTER_PROTOTYPE configFunc=defaultValue, variable flags=defaultValue, variable offset=defaultValue)
Prepare for data acquisition.
hardwareType One of HardwareDACTypeConstants deviceID device identifier mode one of DATA_ACQUISITION_MODE or TEST_PULSE_MODE data hardware data wave dataFunc [optional, defaults to GetDAQDataWave()] override wave getter for the ITC data wave config ITC config wave configFunc [optional, defaults to GetDAQConfigWave()] override wave getter for the ITC config wave flags [optional, default none] One or multiple flags from HardwareInteractionFlags offset [optional, defaults to zero] offset into the data wave in points
References HARDWARE_ITC_DAC, HARDWARE_NI_DAC, HW_ITC_PrepareAcq, HW_NI_PrepareAcq.
Referenced by DQM_StartDAQMultiDevice, DQS_BkrdDataAcq, DQS_DataAcq, TP_Setup.
variable HW_SelectDevice(variable hardwareType, variable deviceID, variable flags=defaultValue)
Select a device.
Only used in special cases for ITC hardware as all ITC operations use the /DEV flag nowadays. hardwareType One of HardwareDACTypeConstants deviceID identifier of the device flags [optional, default none] One or multiple flags from HardwareInteractionFlags 0 if sucessfull, 1 on error
References HARDWARE_ITC_DAC, HARDWARE_NI_DAC, HW_ITC_SelectDevice.
Referenced by DAP_CheckSettings, P_CloseDeviceLowLevel, TPM_StopTPMDWrapper.
variable HW_OpenDevice(string deviceToOpen, variable *hardwareType, variable *flags=defaultValue)
Open a device.
deviceToOpen device hardwareType One of HardwareDACTypeConstants flags [optional, default none] One or multiple flags from HardwareInteractionFlags device identifier
References ASSERT, DEVICE_NUMBERS, DEVICE_TYPES_ITC, GetHardwareType, HARDWARE_ABORT_ON_ERROR, HARDWARE_ITC_DAC, HARDWARE_NI_DAC, HW_AssertOnInvalid, HW_ITC_OpenDevice, HW_NI_ListDevices, HW_NI_OpenDevice, ParseDeviceString.
Referenced by DAP_LockDevice, HW_GetDeviceInfoUnregistered, P_ButtonProc_UserPressure, P_OpenDevice.
variable HW_CloseDevice(variable hardwareType, variable deviceID, variable flags=defaultValue)
Close a device.
hardwareType One of HardwareDACTypeConstants deviceID device identifier flags [optional, default none] One or multiple flags from HardwareInteractionFlags
References HARDWARE_ITC_DAC, HARDWARE_NI_DAC, HW_AssertOnInvalid, HW_ITC_CloseDevice, HW_NI_CloseDevice.
Referenced by DAP_UnlockDevice, HW_GetDeviceInfoUnregistered, P_ButtonProc_UserPressure, P_CloseDeviceLowLevel.
variable HW_WriteDAC(variable hardwareType, variable deviceID, variable channel, variable value, variable flags=defaultValue)
Write a value to a DA/AO channel.
hardwareType One of HardwareDACTypeConstants deviceID device identifier channel channel number value value to write in volts flags [optional, default none] One or multiple flags from HardwareInteractionFlags
References HARDWARE_ITC_DAC, HARDWARE_NI_DAC, HW_AssertOnInvalid, HW_GetDeviceName, HW_ITC_WriteDAC, HW_NI_AssertOnInvalid, HW_NI_WriteAnalogSingleAndSlow.
Referenced by P_OpenDevice, P_SetAndGetPressure.
variable HW_ReadADC(variable hardwareType, variable deviceID, variable channel, variable flags=defaultValue)
Read a value from an AD/AI channel.
hardwareType One of HardwareDACTypeConstants deviceID device identifier channel channel number flags [optional, default none] One or multiple flags from HardwareInteractionFlags value in volts
References HARDWARE_ITC_DAC, HARDWARE_NI_DAC, HW_AssertOnInvalid, HW_GetDeviceName, HW_ITC_ReadADC, HW_NI_AssertOnInvalid, HW_NI_ReadAnalogSingleAndSlow.
Referenced by ASD_ReadChannel, P_RecordUserPressure.
variable HW_ReadDigital(variable hardwareType, variable deviceID, variable channel, variable line=defaultValue, variable flags=defaultValue)
Read from a digital channel.
hardwareType One of HardwareDACTypeConstants deviceID device identifier channel The hardware documentation terms this as port(NI). For the ITC we call that ttlBit. Takes care of special rack handling for the ITC 1600. Range depends on hardware and hardware type. line bit of TTL line, (only for hardware types which support single TTL writes/read) flags [optional, default none] One or multiple flags from HardwareInteractionFlags bitmask denoting the state of the channel/line
References HARDWARE_ITC_DAC, HARDWARE_NI_DAC, HW_AssertOnInvalid, HW_GetDeviceName, HW_ITC_GetITCXOPChannelForRack, HW_ITC_GetRackForTTLBit, HW_ITC_ReadDigital, HW_NI_AssertOnInvalid, HW_NI_ReadDigital.
Referenced by P_TTLforPpulse, P_UpdateTTLstate.
variable HW_WriteDigital(variable hardwareType, variable deviceID, variable channel, variable value, variable line=defaultValue, variable flags=defaultValue)
Write to a digital channel.
hardwareType One of HardwareDACTypeConstants deviceID device identifier channel The hardware documentation terms this as port(NI). For the ITC we call that ttlBit. Takes care of special rack handling for the ITC 1600. Range depends on hardware and hardware type. value bitmask to write line bit of TTL line, (only for hardware types which support single TTL writes/read) flags [optional, default none] One or multiple flags from HardwareInteractionFlags
References HARDWARE_ITC_DAC, HARDWARE_NI_DAC, HW_AssertOnInvalid, HW_GetDeviceName, HW_ITC_GetITCXOPChannelForRack, HW_ITC_GetRackForTTLBit, HW_ITC_WriteDigital, HW_NI_AssertOnInvalid, HW_NI_WriteDigital.
Referenced by P_DataAcq, P_NI_StopDAQ, P_UpdateTTLstate.
variable HW_EnableYoking(variable hardwareType, variable deviceID, variable flags=defaultValue)
Enable yoking.
hardwareType One of HardwareDACTypeConstants deviceID device identifier flags [optional, default none] One or multiple flags from HardwareInteractionFlags
References ASSERT, HARDWARE_ITC_DAC, HARDWARE_NI_DAC, HW_AssertOnInvalid, HW_ITC_EnableYoking.
Referenced by DAP_SetITCDACasFollower.
variable HW_DisableYoking(variable hardwareType, variable deviceID, variable flags=defaultValue)
Enable yoking.
hardwareType One of HardwareDACTypeConstants deviceID device identifier flags [optional, default none] One or multiple flags from HardwareInteractionFlags
References ASSERT, HARDWARE_ITC_DAC, HARDWARE_NI_DAC, HW_AssertOnInvalid, HW_ITC_DisableYoking.
Referenced by DAP_RemoveYokedDAC.
variable HW_StopAcq(variable hardwareType, variable deviceID, variable prepareForDAQ=defaultValue, variable zeroDAC=defaultValue, variable flags=defaultValue)
Stop data acquisition.
hardwareType One of HardwareDACTypeConstants deviceID device identifier prepareForDAQ immediately prepare for the next data acquisition after stopping it zeroDAC set all used DA channels to zero flags [optional, default none] One or multiple flags from HardwareInteractionFlags
References HARDWARE_ITC_DAC, HARDWARE_NI_DAC, HW_AssertOnInvalid, HW_ITC_StopAcq, HW_NI_StopAcq.
Referenced by DQ_StopOngoingDAQHelper, DQM_StopDataAcq, DQM_TerminateOngoingDAQHelper, DQS_StopDataAcq, P_DataAcq, P_ITC_FIFOMonitorProc, PSQ_Ramp, TPM_StopTPMDWrapper, TPS_StartTestPulseForeground, TPS_TestPulseFunc.
variable HW_IsRunning(variable hardwareType, variable deviceID, variable flags=defaultValue)
Determine if data acquisition is currently active.
hardwareType One of HardwareDACTypeConstants deviceID device identifier flags [optional, default none] One or multiple flags from HardwareInteractionFlags one if running, zero otherwise
References HARDWARE_ITC_DAC, HARDWARE_NI_DAC, HW_AssertOnInvalid, HW_GetDeviceName, HW_ITC_IsRunning, HW_NI_AssertOnInvalid, HW_NI_IsRunning.
Referenced by DC_Configure, P_DACIsCollectingData, TPM_StopTPMDWrapper.
wave HW_GetDeviceInfo(variable hardwareType, variable deviceID, variable flags=defaultValue)
Return hardware specific information from the device.
hardwareType One of HardwareDACTypeConstants deviceID device identifier flags [optional, default none] One or multiple flags from HardwareInteractionFlags free numeric/text wave with information and dimension labels
References HARDWARE_ITC_DAC, HARDWARE_NI_DAC, HW_AssertOnInvalid, HW_GetDeviceName, HW_ITC_GetDeviceInfo, HW_NI_AssertOnInvalid, HW_NI_GetDeviceInfo.
Referenced by DC_DocumentHardwareProperties.
wave HW_GetDeviceInfoUnregistered(variable hardwareType, string device, variable flags=defaultValue)
Return hardware specific information from the device.
This function does not require the device to be registered compared to HW_GetDeviceInfo(). hardwareType One of HardwareDACTypeConstants device name of the device flags [optional, default none] One or multiple flags from HardwareInteractionFlags
References ASSERT, HARDWARE_ITC_DAC, HARDWARE_NI_DAC, HW_CloseDevice, HW_ITC_GetDeviceInfo, HW_NI_AssertOnInvalid, HW_NI_GetDeviceInfo, HW_OpenDevice.
Referenced by DAP_UpdateDeviceInfoWaves.
variable HW_WriteDeviceInfo(variable hardwareType, wave deviceInfo, WaveOrNull devInfoHW)
Update the device info wave.
Query the data via GetDeviceInfoWave().
References ASSERT, HARDWARE_ITC_DAC, HARDWARE_NI_DAC.
Referenced by DAP_UpdateDeviceInfoWaves.
variable HW_StartAcq(variable hardwareType, variable deviceID, variable triggerMode=defaultValue, variable flags=defaultValue, variable repeat=defaultValue)
Start data acquisition.
hardwareType One of HardwareDACTypeConstants deviceID device identifier triggerMode [optional, defaults to HARDWARE_DAC_DEFAULT_TRIGGER] one of TriggerModeStartAcq flags [optional, default none] One or multiple flags from HardwareInteractionFlags repeat [optional, default 0] for NI devices, repeats the scan after it ends
References HARDWARE_DAC_DEFAULT_TRIGGER, HARDWARE_ITC_DAC, HARDWARE_NI_DAC, HW_AssertOnInvalid, HW_ITC_StartAcq, HW_NI_StartAcq.
Referenced by DQM_BkrdDataAcq, DQS_BkrdDataAcq, DQS_DataAcq, P_DataAcq, PSQ_Ramp, TPM_BkrdTPMD, TPS_StartTestPulseForeground, TPS_TestPulseFunc.
variable HW_ResetDevice(variable hardwareType, variable deviceID, variable flags=defaultValue)
Reset the device.
hardwareType One of HardwareDACTypeConstants deviceID device identifier flags [optional, default none] One or multiple flags from HardwareInteractionFlags
References HARDWARE_ITC_DAC, HARDWARE_NI_DAC, HW_AssertOnInvalid, HW_GetDeviceName, HW_NI_AssertOnInvalid, HW_NI_ResetDevice.
Referenced by DAP_UnlockDevice, P_CloseDeviceLowLevel.
variable HW_AssertOnInvalid(variable hardwareType, variable deviceID)
Assert on using an invalid value of hardwareType or deviceID
hardwareType One of HardwareDACTypeConstants deviceID device identifier
References ASSERT, HW_IsValidDeviceID, HW_IsValidHardwareType.
Referenced by HW_CloseDevice, HW_DisableYoking, HW_EnableYoking, HW_GetDeviceInfo, HW_GetDeviceName, HW_GetMainDeviceName, HW_IsRunning, HW_OpenDevice, HW_ReadADC, HW_ReadDigital, HW_RegisterDevice, HW_ResetDevice, HW_StartAcq, HW_StopAcq, HW_WriteDAC, HW_WriteDigital.
static variable HW_IsValidHardwareType(variable hardwareType)
Check if the given hardware type is valid.
Invalid here means that the value is out-of-range.
References HARDWARE_ITC_DAC, HARDWARE_NI_DAC.
Referenced by HW_AssertOnInvalid, HW_DeRegisterDevice.
static variable HW_IsValidDeviceID(variable deviceID)
Check if the given device ID is valid.
Invalid here means that the value is out-of-range.
References HARDWARE_MAX_DEVICES.
Referenced by HW_AssertOnInvalid, HW_DeRegisterDevice.
variable HW_RegisterDevice(string mainDevice, variable hardwareType, variable deviceID, string pressureDevice=defaultValue)
Register an opened device in our device map.
mainDevice Name of the DA_EPhys device hardwareType One of HardwareDACTypeConstants deviceID device identifier pressureDevice required for registering pressure control devices
References ASSERT, GetDeviceMapping, HW_AssertOnInvalid, isEmpty.
Referenced by DAP_LockDevice, P_ButtonProc_UserPressure, P_OpenDevice.
variable HW_DeRegisterDevice(variable hardwareType, variable deviceID, variable flags=defaultValue)
Deregister an opened device in our device map.
hardwareType One of HardwareDACTypeConstants deviceID device identifier flags [optional, default none] One or multiple flags from HardwareInteractionFlags
References GetDeviceMapping, HW_IsValidDeviceID, HW_IsValidHardwareType.
Referenced by DAP_UnlockDevice, P_ButtonProc_UserPressure, P_CloseDeviceLowLevel.
string HW_GetMainDeviceName(variable hardwareType, variable deviceID)
Return the name of the main device given the deviceID and the hardwareType
Use this function if you want to derive a storage location from the device name. deviceID device identifier hardwareType One of HardwareDACTypeConstants
References ASSERT, GetDeviceMapping, HW_AssertOnInvalid, isEmpty.
Referenced by DQM_FIFOMonitor, TFH_StartFIFODeamonInternal, TFH_StopFIFODaemon, TPM_BkrdTPFuncMD.
string HW_GetDeviceName(variable hardwareType, variable deviceID)
Return the name of the device given the deviceID and the hardwareType
Prefers the pressure device name if set. deviceID device identifier hardwareType One of HardwareDACTypeConstants
References ASSERT, GetDeviceMapping, HW_AssertOnInvalid, isEmpty, IsEmpty.
Referenced by HW_GetDeviceInfo, HW_IsRunning, HW_ReadADC, HW_ReadDigital, HW_ResetDevice, HW_WriteDAC, HW_WriteDigital, P_DataAcq, P_DeviceIsUsedForPressureCtrl, P_UpdateTTLstate.
string HW_ITC_BuildDeviceString(string deviceType, string deviceNumber)
Build the device string for ITC devices.
There is no corresponding function for other hardware types like NI devices because those do not have a two part device name
References ASSERT, DEVICE_TYPES_ITC, isEmpty.
Referenced by AB_LoadLabNotebookFromIgor, AppendEntries, GetAllDevices, GetPopupMenuDeviceListWithData, OOD_StorePreload.
string HW_ITC_ListOfOpenDevices()
References DEBUGPRINT.
string HW_ITC_ListDevices()
References DEBUGPRINT.
Referenced by DAP_GetITCDeviceList.
variable HW_ITC_HandleReturnValues_TS(variable flags, variable ITCError, variable ITCXOPError)
References DEBUGPRINT_TS.
variable HW_ITC_HandleReturnValues(variable flags, variable ITCError, variable ITCXOPError)
References DEBUGPRINT.
static string HW_ITC_GetXOPErrorMessage(variable errCode)
References DEBUGPRINT_TS.
variable HW_ITC_OpenDevice(variable deviceType, variable deviceNumber, variable flags=defaultValue)
References DEBUGPRINT.
Referenced by HW_OpenDevice.
variable HW_ITC_CloseAllDevices(variable flags=defaultValue)
References DEBUGPRINT.
variable HW_ITC_CloseDevice(variable deviceID, variable flags=defaultValue)
References DEBUGPRINT.
Referenced by HW_CloseDevice.
variable HW_ITC_SelectDevice(variable deviceID, variable flags=defaultValue)
References DEBUGPRINT.
Referenced by HW_SelectDevice.
wave HW_ITC_GetDeviceInfo(variable deviceID, variable flags=defaultValue)
References DEBUGPRINT.
Referenced by HW_GetDeviceInfo, HW_GetDeviceInfoUnregistered.
variable HW_ITC_EnableYoking(variable deviceID, variable flags=defaultValue)
References DEBUGPRINT.
Referenced by HW_EnableYoking.
variable HW_ITC_DisableYoking(variable deviceID, variable flags=defaultValue)
References DEBUGPRINT.
Referenced by HW_DisableYoking.
variable HW_ITC_StopAcq_TS(variable deviceID, variable prepareForDAQ=defaultValue, variable flags=defaultValue)
References DEBUGPRINT_TS.
Referenced by TFH_FifoLoop.
variable HW_ITC_StopAcq(variable deviceID, WaveOrNull config=defaultValue, HW_WAVE_GETTER_PROTOTYPE configFunc=defaultValue, variable prepareForDAQ=defaultValue, variable zeroDAC=defaultValue, variable flags=defaultValue)
References DEBUGPRINT.
Referenced by HW_StopAcq.
variable HW_ITC_GetCurrentDevice(variable flags=defaultValue)
References DEBUGPRINT.
static wave HW_ITC_GetFifoPosFromConfig(wave config_t)
References DEBUGPRINT_TS.
variable HW_ITC_ResetFifo_TS(variable deviceID, wave config, variable flags=defaultValue)
References DEBUGPRINT_TS.
Referenced by TFH_FifoLoop.
variable HW_ITC_ResetFifo(variable deviceID, WaveOrNull config=defaultValue, HW_WAVE_GETTER_PROTOTYPE configFunc=defaultValue, variable flags=defaultValue)
References DEBUGPRINT.
Referenced by TPM_BkrdTPMD, TPS_StartTestPulseForeground, TPS_TestPulseFunc.
variable HW_ITC_StartAcq_TS(variable deviceID, variable triggerMode, variable flags=defaultValue)
References DEBUGPRINT_TS.
Referenced by TFH_FifoLoop.
variable HW_ITC_StartAcq(variable deviceID, variable triggerMode, variable flags=defaultValue)
References DEBUGPRINT.
Referenced by HW_StartAcq.
variable HW_ITC_IsRunning(variable deviceID, variable flags=defaultValue)
References DEBUGPRINT.
Referenced by HW_IsRunning.
wave HW_ITC_GetState(variable deviceID, variable flags=defaultValue)
References DEBUGPRINT.
variable HW_ITC_ReadADC(variable deviceID, variable channel, variable flags=defaultValue)
References DEBUGPRINT.
Referenced by HW_ReadADC.
variable HW_ITC_WriteDAC(variable deviceID, variable channel, variable value, variable flags=defaultValue)
References DEBUGPRINT.
Referenced by HW_WriteDAC.
variable HW_ITC_ReadDigital(variable deviceID, variable xopChannel, variable flags=defaultValue)
References DEBUGPRINT.
Referenced by HW_ReadDigital.
variable HW_ITC_WriteDigital(variable deviceID, variable xopChannel, variable value, variable flags=defaultValue)
References DEBUGPRINT.
Referenced by HW_WriteDigital.
variable HW_ITC_DebugMode_TS(variable state, variable flags=defaultValue)
References DEBUGPRINT_TS.
Referenced by TFH_FifoLoop.
variable HW_ITC_DebugMode(variable state, variable flags=defaultValue)
References DEBUGPRINT.
Referenced by DP_CheckProc_Debug.
variable HW_ITC_PrepareAcq(variable deviceID, variable mode, WaveOrNull data=defaultValue, HW_WAVE_GETTER_PROTOTYPE dataFunc=defaultValue, WaveOrNull config=defaultValue, HW_WAVE_GETTER_PROTOTYPE configFunc=defaultValue, variable flags=defaultValue, variable offset=defaultValue)
References DEBUGPRINT.
Referenced by DQM_StartDAQMultiDevice, HW_PrepareAcq, P_DataAcq, PSQ_Ramp.
variable HW_ITC_MoreData_TS(variable deviceID, variable ADChannelToMonitor, variable stopCollectionPoint, wave config, variable *fifoPos=defaultValue, variable flags=defaultValue)
References DEBUGPRINT_TS.
Referenced by TFH_FifoLoop.
variable HW_ITC_MoreData(variable deviceID, variable ADChannelToMonitor=defaultValue, variable stopCollectionPoint=defaultValue, WaveOrNull config=defaultValue, HW_WAVE_GETTER_PROTOTYPE configFunc=defaultValue, variable *fifoPos=defaultValue, variable flags=defaultValue)
References DEBUGPRINT.
Referenced by DQS_DataAcq, DQS_FIFOMonitor, P_ITC_FIFOMonitorProc, TPS_StartTestPulseForeground, TPS_TestPulseFunc.
static variable HW_ITC_GetZValue(variable flags)
Construct the /Z flag value for the ITC operations.
Takes interactiveMode into account for automated testing.
References HARDWARE_PREVENT_ERROR_POPUP.
wave HW_WAVE_GETTER_PROTOTYPE(string str)
wave HW_ITC_TransposeAndToDouble(wave wv)
wave HW_ITC_TransposeAndToInt(wave wv)
variable HW_ITC_CalculateDevChannelOff(string device)
Returns the device channel offset for the given device.
16 for ITC1600 and 0 for all other types
References IsITC1600.
Referenced by ASD_ReadChannel, DAP_CheckSettings.
variable HW_ITC_GetRackRange(variable rack, variable *first, variable *last)
Return the first and last TTL bits/channels for the given rack
References ASSERT_TS, NUM_ITC_TTL_BITS_PER_RACK, RACK_ONE, RACK_ZERO.
Referenced by DC_AreTTLsInRackChecked, DC_ITC_MakeTTLWave, GetTTLChannelsOrBits.
variable HW_ITC_ClipTTLBit(string device, variable ttlBit)
Clip the ttlBit to adapt for differences in notation.
The DA_Ephys panel e.g. labels the first ttlBit of RACK_ONE as 4, but the ITC XOP treats that as 0.
References HW_ITC_GetRackForTTLBit, NUM_ITC_TTL_BITS_PER_RACK, RACK_ONE.
Referenced by P_UpdateTTLdecimal, P_UpdateTTLstate.
variable HW_ITC_GetRackForTTLBit(string device, variable ttlBit)
Return the rack number for the given ttlBit (the ttlBit is called TTL channel in the DA Ephys panel)
References ASSERT, IsITC1600, NUM_DA_TTL_CHANNELS, NUM_ITC_TTL_BITS_PER_RACK, RACK_ONE, RACK_ZERO.
Referenced by HW_ITC_ClipTTLBit, HW_ReadDigital, HW_WriteDigital, P_TTLforPpulse, P_UpdateTTLstate.
variable HW_ITC_GetITCXOPChannelForRack(string device, variable rack)
Return the ITC XOP channel for the given rack.
Only the ITC1600 has two racks. The channel numbers differ for the different ITC device types.
References ASSERT, HARDWARE_ITC_TTL_1600_RACK_ONE, HARDWARE_ITC_TTL_1600_RACK_ZERO, HARDWARE_ITC_TTL_DEF_RACK_ZERO, IsITC1600, RACK_ONE, RACK_ZERO.
Referenced by DC_PlaceDataInDAQConfigWave, HW_ReadDigital, HW_WriteDigital, P_PrepareITCWaves.
variable HW_ITC_GetNumberOfRacks(string device)
Get the number of racks for the given device.
ITC: ITC1600 can have 1 or 2 racks other device types have 1 NI: NaN (concept is not applicable)
References GetDeviceInfoWave.
variable HW_NI_AssertOnInvalid(string deviceName)
Assert on using an invalid NI device name.
deviceName NI device name
References ASSERT, HW_NI_IsValidDeviceName.
Referenced by HW_GetDeviceInfo, HW_GetDeviceInfoUnregistered, HW_IsRunning, HW_ReadADC, HW_ReadDigital, HW_ResetDevice, HW_WriteDAC, HW_WriteDigital.
variable HW_NI_IsValidDeviceName(string deviceName)
Check wether the given NI device name is valid.
Currently a device name is valid if it is not empty.
References isEmpty.
Referenced by HW_NI_AssertOnInvalid.
string HW_NI_AnalogInputToString(variable config)
Return the analog input configuration bits as string.
config Bit combination of NIAnalogInputConfigs
References ASSERT, HW_NI_CONFIG_DIFFERENTIAL, HW_NI_CONFIG_NRSE, HW_NI_CONFIG_PSEUDO_DIFFERENTIAL, HW_NI_CONFIG_RSE, IsEmpty.
Referenced by DAP_CheckHeadStage, DAP_CheckPressureSettings.
variable HW_NI_StartAcq(variable deviceID, variable triggerMode, variable flags=defaultValue, variable repeat=defaultValue)
Referenced by HW_StartAcq, TPM_BkrdTPFuncMD.
variable HW_NI_PrepareAcq(variable deviceID, variable mode, WaveOrNull data=defaultValue, HW_WAVE_GETTER_PROTOTYPE dataFunc=defaultValue, WaveOrNull config=defaultValue, HW_WAVE_GETTER_PROTOTYPE configFunc=defaultValue, variable flags=defaultValue, variable offset=defaultValue)
Referenced by HW_PrepareAcq, TPM_BkrdTPFuncMD.
string HW_NI_GetPropertyListOfDevices(variable devNr)
Referenced by DAP_GetNIDeviceList.
variable HW_NI_PrintPropertiesOfDevices()
variable HW_NI_ReadDigital(string device, variable DIOPort=defaultValue, variable DIOLine=defaultValue, variable flags=defaultValue)
Referenced by HW_ReadDigital.
variable HW_NI_WriteDigital(string device, variable value, variable DIOPort=defaultValue, variable DIOLine=defaultValue, variable flags=defaultValue)
Referenced by HW_WriteDigital.
variable HW_NI_WriteAnalogSingleAndSlow(string device, variable channel, variable value, variable flags=defaultValue)
Referenced by HW_WriteDAC.
variable HW_NI_ReadAnalogSingleAndSlow(string device, variable channel, variable flags=defaultValue)
Referenced by HW_ReadADC.
variable HW_NI_GetAnalogInputConfig(string device, variable channel, variable flags=defaultValue)
Referenced by DAP_CheckHeadStage, DAP_CheckPressureSettings.
string HW_NI_ListDevices(variable flags=defaultValue)
Referenced by ButtonProc_Hrdwr_P_UpdtDAClist, DAP_GetNIDeviceList, HW_OpenDevice.
variable HW_NI_StopAcq(variable deviceID, variable zeroDAC=defaultValue, variable flags=defaultValue)
Referenced by HW_StopAcq, TPM_BkrdTPFuncMD.
variable HW_NI_StopDAC(variable deviceID, variable flags=defaultValue)
Referenced by PSQ_Ramp.
variable HW_NI_StopADC(variable deviceID, variable flags=defaultValue)
variable HW_NI_StopTTL(variable deviceID, variable flags=defaultValue)
variable HW_NI_ZeroDAC(variable deviceID, variable flags=defaultValue)
Referenced by PSQ_Ramp.
static variable HW_NI_ResetDevice(string device, variable flags=defaultValue)
Referenced by HW_ResetDevice.
static variable HW_NI_CalibrateDevice(string device, variable force=defaultValue, variable flags=defaultValue)
variable HW_NI_IsRunning(string device, variable flags=defaultValue)
Referenced by HW_IsRunning.
variable HW_NI_OpenDevice(string device, variable flags=defaultValue)
Referenced by HW_OpenDevice.
variable HW_NI_CloseDevice(variable deviceID, variable flags=defaultValue)
Referenced by HW_CloseDevice.
wave HW_NI_GetDeviceInfo(string device, variable flags=defaultValue)
Referenced by HW_GetDeviceInfo, HW_GetDeviceInfoUnregistered.
variable HW_NI_ResetTaskIDs(string device)
Referenced by DAP_OneTimeCallAfterDAQ, DAP_OneTimeCallBeforeDAQ.
const double HW_ITC_RUNNING_STATE