MIES_Configuration.ipf
const double CONF_AUTO_LOADER_GLOBAL
Parameters for CONF_GetSettingsPath()
Referenced by CONF_GetConfigFiles, CONF_GetSettingsPath, CONF_RestoreWindow, CONF_SaveDAEphys, CONF_SaveWindow.
const double CONF_AUTO_LOADER_USER
Referenced by CONF_GetConfigFiles, CONF_GetSettingsPath.
const string EXPCONFIG_FIELD_CTRLTYPE
Referenced by CONF_ControlToJSON, CONF_RestoreControl.
const string EXPCONFIG_FIELD_CTRLVVALUE
Referenced by CONF_ControlToJSON, CONF_GetVariableFromSavedControl, CONF_RestoreControl.
const string EXPCONFIG_FIELD_CTRLSVALUE
Referenced by CONF_ControlToJSON, CONF_GetStringFromSavedControl, CONF_RestoreControl.
const string EXPCONFIG_FIELD_CTRLSDF
Referenced by CONF_ControlToJSON, CONF_RestoreControl.
const string EXPCONFIG_FIELD_CTRLDISABLED
Referenced by CONF_ControlToJSON, CONF_RestoreControl.
const string EXPCONFIG_FIELD_CTRLPOSHEIGHT
Referenced by CONF_ControlToJSON, CONF_RestoreControl.
const string EXPCONFIG_FIELD_CTRLPOSWIDTH
Referenced by CONF_ControlToJSON, CONF_RestoreControl.
const string EXPCONFIG_FIELD_CTRLPOSTOP
Referenced by CONF_ControlToJSON, CONF_RestoreControl.
const string EXPCONFIG_FIELD_CTRLPOSLEFT
const string EXPCONFIG_FIELD_CTRLPOSRIGHT
const string EXPCONFIG_FIELD_CTRLPOSPOS
Referenced by CONF_ControlToJSON, CONF_RestoreControl.
const string EXPCONFIG_FIELD_CTRLPOSALIGN
Referenced by CONF_ControlToJSON, CONF_RestoreControl.
const string EXPCONFIG_FIELD_CTRLUSERDATA
Referenced by CONF_ControlToJSON, CONF_RestoreControl.
const string EXPCONFIG_FIELD_BASE64PREFIX
Referenced by CONF_ControlToJSON, CONF_RestoreControl.
const string EXPCONFIG_FIELD_CTRLARRAYVALUES
Referenced by CONF_ControlToJSON, CONF_GetWaveFromSavedControlArray, CONF_RestoreControl.
const string EXPCONFIG_UDATA_NICENAME
Referenced by CONF_ControlToJSON, CONF_JSONToWindow, CONF_RestoreControl, CONF_WindowToJSON.
const string EXPCONFIG_UDATA_JSONPATH
Referenced by CONF_ControlToJSON, CONF_WindowToJSON.
const string EXPCONFIG_UDATA_EXCLUDE_SAVE
Referenced by CONF_ControlToJSON, CONF_WindowToJSON.
const string EXPCONFIG_UDATA_EXCLUDE_RESTORE
Referenced by CONF_JSONToWindow, CONF_RestoreControl, CONF_RestoreDAEphys, CONF_WindowToJSON.
const string EXPCONFIG_UDATA_BUTTONPRESS
Referenced by CONF_ControlToJSON, CONF_RestoreControl, CONF_WindowToJSON.
const string EXPCONFIG_UDATA_RESTORE_PRIORITY
Referenced by CONF_JSONToWindow, CONF_WindowToJSON.
const string EXPCONFIG_UDATA_WINHANDLE
Referenced by CONF_FindWindow, CONF_JSONToWindow, CONF_WindowToJSON.
const string EXPCONFIG_UDATA_RADIOCOUPLING
Referenced by CONF_WindowToJSON.
const string EXPCONFIG_UDATA_CTRLARRAY
Referenced by CONF_ControlToJSON, CONF_GetControlArrayList, CONF_JSONToWindow, CONF_RestoreControl, CONF_WindowToJSON.
const string EXPCONFIG_UDATA_CTRLARRAYINDEX
Referenced by CONF_ControlToJSON, CONF_RestoreControl.
const double EXPCONFIG_UDATA_MAXCTRLARRAYINDEX
Referenced by CONF_ControlToJSON, CONF_RestoreControl.
const double EXPCONFIG_JSON_INDENT
Referenced by CONF_SaveDAEphys, CONF_SaveWindow.
const string EXPCONFIG_FILEFILTER
Referenced by CONF_RestoreWindow, CONF_SaveDAEphys, CONF_SaveWindow.
const string EXPCONFIG_CTRLGROUP_SUFFIX
Referenced by CONF_GatherControlsFromJSON, CONF_GetCompleteJSONCtrlPath, CONF_TraversalFinder, CONF_WindowToJSON.
const string EXPCONFIG_SETTINGS_FOLDER
Referenced by CONF_AutoLoader, CONF_GetSettingsPath, CONF_OpenConfigInNotebook.
const string DAEPHYS_UDATA_WINHANDLE
Referenced by CONF_RestoreDAEphys.
const string DAEPHYS_HEADSTAGECTRLARRAYPREFIX
Referenced by CONF_GetDAEphysActiveHeadstages.
const string DAEPHYS_EXCLUDE_CTRLTYPES
Referenced by CONF_SaveDAEphys.
const string EXPCONFIG_DEFAULT_CTRL_JSONPATH
Referenced by CONF_ControlToJSON.
const string EXPCONFIG_RESERVED_DATABLOCK
Referenced by CONF_ControlToJSON, CONF_GetStringFromSettings, CONF_GetVariableFromSettings, CONF_GetWindowNames, CONF_RequireConfigBlockExists, CONF_RestoreHeadstageAssociation, CONF_RestoreUserPressure, CONF_SaveDAEphys.
const string EXPCONFIG_RESERVED_TAGENTRY
Referenced by CONF_AllWindowsToJSON, CONF_GetWindowNames, CONF_RestoreWindow.
const string EXPCONFIG_EXCLUDE_USERDATA
Referenced by CONF_WindowToJSON.
const string EXPCONFIG_EXCLUDE_CTRLTYPES
Referenced by CONF_SaveWindow.
const string EXPCONFIG_SETTINGS_AMPTITLE
Referenced by CONF_GetAmplifierSettings.
const string EXPCONFIG_JSON_HSASSOCBLOCK
Referenced by CONF_RestoreHeadstageAssociation, CONF_SaveDAEphys.
const string EXPCONFIG_JSON_AMPBLOCK
Referenced by CONF_GetAmplifierSettings, CONF_RestoreAmplifierSettings, CONF_RestoreHeadstageAssociation.
const string EXPCONFIG_JSON_ICBLOCK
Referenced by CONF_GetAmplifierSettings, CONF_RestoreAmplifierSettings, CONF_RestoreHeadstageAssociation.
const string EXPCONFIG_JSON_VCBLOCK
Referenced by CONF_GetAmplifierSettings, CONF_RestoreAmplifierSettings, CONF_RestoreHeadstageAssociation.
const string EXPCONFIG_JSON_PRESSUREBLOCK
Referenced by CONF_GetAmplifierSettings, CONF_RestoreHeadstageAssociation.
const string EXPCONFIG_JSON_AMPSERIAL
Referenced by CONF_GetAmplifierSettings, CONF_RestoreHeadstageAssociation.
const string EXPCONFIG_JSON_AMPTITLE
Referenced by CONF_GetAmplifierSettings, CONF_RestoreHeadstageAssociation.
const string EXPCONFIG_JSON_AMPCHANNEL
Referenced by CONF_GetAmplifierSettings, CONF_RestoreHeadstageAssociation.
const string EXPCONFIG_JSON_AMPVCDA
Referenced by CONF_GetAmplifierSettings, CONF_RestoreHeadstageAssociation.
const string EXPCONFIG_JSON_AMPVCAD
Referenced by CONF_GetAmplifierSettings, CONF_RestoreHeadstageAssociation.
const string EXPCONFIG_JSON_AMPICDA
Referenced by CONF_GetAmplifierSettings, CONF_RestoreHeadstageAssociation.
const string EXPCONFIG_JSON_AMPICAD
Referenced by CONF_GetAmplifierSettings, CONF_RestoreHeadstageAssociation.
const string EXPCONFIG_JSON_PRESSDEV
Referenced by CONF_GetAmplifierSettings, CONF_RestoreHeadstageAssociation.
const string EXPCONFIG_JSON_PRESSDA
Referenced by CONF_GetAmplifierSettings, CONF_RestoreHeadstageAssociation.
const string EXPCONFIG_JSON_PRESSAD
Referenced by CONF_GetAmplifierSettings, CONF_RestoreHeadstageAssociation.
const string EXPCONFIG_JSON_PRESSDAGAIN
Referenced by CONF_GetAmplifierSettings, CONF_RestoreHeadstageAssociation.
const string EXPCONFIG_JSON_PRESSADGAIN
Referenced by CONF_GetAmplifierSettings, CONF_RestoreHeadstageAssociation.
const string EXPCONFIG_JSON_PRESSDAUNIT
Referenced by CONF_GetAmplifierSettings, CONF_RestoreHeadstageAssociation.
const string EXPCONFIG_JSON_PRESSADUNIT
Referenced by CONF_GetAmplifierSettings, CONF_RestoreHeadstageAssociation.
const string EXPCONFIG_JSON_PRESSTTLA
Referenced by CONF_GetAmplifierSettings, CONF_RestoreHeadstageAssociation.
const string EXPCONFIG_JSON_PRESSTTLB
Referenced by CONF_GetAmplifierSettings, CONF_RestoreHeadstageAssociation.
const string EXPCONFIG_JSON_PRESSCONSTNEG
Referenced by CONF_GetAmplifierSettings, CONF_RestoreHeadstageAssociation.
const string EXPCONFIG_JSON_PRESSCONSTPOS
Referenced by CONF_GetAmplifierSettings, CONF_RestoreHeadstageAssociation.
const string EXPCONFIG_JSON_SAVE_PATH
Referenced by CONF_DefaultSettings, CONF_RestoreDAEphys.
const string EXPCONFIG_JSON_STIMSET_NAME
Referenced by CONF_DefaultSettings, CONF_RestoreDAEphys.
const string EXPCONFIG_JSON_POSITION_MCC
Referenced by CONF_DefaultSettings, CONF_RestoreHeadstageAssociation.
const string EXPCONFIG_JSON_SWEEP_ROLLBACK
Referenced by CONF_DefaultSettings, CONF_RestoreDAEphys.
const double EXPCONFIG_SWEEPROLLBACK_DEFAULT
Referenced by CONF_DefaultSettings, CONF_RestoreDAEphys.
const string EXPCONFIG_JSON_LOGFILE_UPLOAD
Referenced by CONF_DefaultSettings, CONF_RestoreDAEphys.
const double EXPCONFIG_JSON_LOGFILE_UPLOAD_DEFAULT
Referenced by CONF_DefaultSettings, CONF_RestoreDAEphys.
const string EXPCONFIG_JSON_USERPRESSBLOCK
Referenced by CONF_RestoreUserPressure, CONF_SaveDAEphys.
const string EXPCONFIG_JSON_USERPRESSDEV
Referenced by CONF_GetUserPressure, CONF_RestoreUserPressure.
const string EXPCONFIG_JSON_USERPRESSDA
Referenced by CONF_GetUserPressure, CONF_RestoreUserPressure.
const string EXPCONFIG_JSON_AMP_HOLD_VC
Referenced by CONF_GetAmplifierSettings, CONF_RestoreAmplifierSettings.
const string EXPCONFIG_JSON_AMP_HOLD_ENABLE_VC
Referenced by CONF_GetAmplifierSettings, CONF_RestoreAmplifierSettings.
const string EXPCONFIG_JSON_AMP_PIPETTE_OFFSET_VC
Referenced by CONF_GetAmplifierSettings, CONF_RestoreAmplifierSettings.
const string EXPCONFIG_JSON_AMP_WHOLE_CELL_CAPACITANCE
Referenced by CONF_GetAmplifierSettings, CONF_RestoreAmplifierSettings.
const string EXPCONFIG_JSON_AMP_WHOLE_CELL_RESISTANCE
Referenced by CONF_GetAmplifierSettings, CONF_RestoreAmplifierSettings.
const string EXPCONFIG_JSON_AMP_WHOLE_CELL_ENABLE
Referenced by CONF_GetAmplifierSettings, CONF_RestoreAmplifierSettings.
const string EXPCONFIG_JSON_AMP_RS_COMP_CORRECTION
Referenced by CONF_GetAmplifierSettings, CONF_RestoreAmplifierSettings.
const string EXPCONFIG_JSON_AMP_RS_COMP_PREDICTION
Referenced by CONF_GetAmplifierSettings, CONF_RestoreAmplifierSettings.
const string EXPCONFIG_JSON_AMP_RS_COMP_ENABLE
Referenced by CONF_GetAmplifierSettings, CONF_RestoreAmplifierSettings.
const string EXPCONFIG_JSON_AMP_COMP_CHAIN
Referenced by CONF_GetAmplifierSettings, CONF_RestoreAmplifierSettings.
const string EXPCONFIG_JSON_AMP_HOLD_IC
Referenced by CONF_GetAmplifierSettings, CONF_RestoreAmplifierSettings.
const string EXPCONFIG_JSON_AMP_HOLD_ENABLE_IC
Referenced by CONF_GetAmplifierSettings, CONF_RestoreAmplifierSettings.
const string EXPCONFIG_JSON_AMP_BRIDGE_BALANCE
Referenced by CONF_GetAmplifierSettings, CONF_RestoreAmplifierSettings.
const string EXPCONFIG_JSON_AMP_BRIDGE_BALANCE_ENABLE
Referenced by CONF_GetAmplifierSettings, CONF_RestoreAmplifierSettings.
const string EXPCONFIG_JSON_AMP_CAP_NEUTRALIZATION
Referenced by CONF_GetAmplifierSettings, CONF_RestoreAmplifierSettings.
const string EXPCONFIG_JSON_AMP_CAP_NEUTRALIZATION_ENABLE
Referenced by CONF_GetAmplifierSettings, CONF_RestoreAmplifierSettings.
const string EXPCONFIG_JSON_AMP_AUTOBIAS_V
Referenced by CONF_GetAmplifierSettings, CONF_RestoreAmplifierSettings.
const string EXPCONFIG_JSON_AMP_AUTOBIAS_V_RANGE
Referenced by CONF_GetAmplifierSettings, CONF_RestoreAmplifierSettings.
const string EXPCONFIG_JSON_AMP_AUTOBIAS_I_BIAS_MAX
Referenced by CONF_GetAmplifierSettings, CONF_RestoreAmplifierSettings.
const string EXPCONFIG_JSON_AMP_AUTOBIAS
Referenced by CONF_GetAmplifierSettings, CONF_RestoreAmplifierSettings.
const string EXPCONFIG_JSON_AMP_PIPETTE_OFFSET_IC
Referenced by CONF_GetAmplifierSettings, CONF_RestoreAmplifierSettings.
const string EXPCONFIG_RIGFILESUFFIX
Referenced by CONF_AutoLoader.
const double EXPCONFIG_MIDDLEEXP_OFF
const double EXPCONFIG_MIDDLEEXP_ON
const string CONF_AUTO_LOADER_USER_PATH
Referenced by CONF_GetSettingsPath.
static variable CONF_DefaultSettings()
Creates a json with default experiment configuration block.
json with default experiment configuration
References EXPCONFIG_JSON_LOGFILE_UPLOAD, EXPCONFIG_JSON_LOGFILE_UPLOAD_DEFAULT, EXPCONFIG_JSON_POSITION_MCC, EXPCONFIG_JSON_SAVE_PATH, EXPCONFIG_JSON_STIMSET_NAME, EXPCONFIG_JSON_SWEEP_ROLLBACK, EXPCONFIG_SWEEPROLLBACK_DEFAULT, NONE.
Referenced by CONF_SaveDAEphys.
variable CONF_OpenConfigInNotebook()
Open all configuration files in plain text notebooks.
Existing notebooks with the files are brought to the front.
References CONF_GetConfigFiles, ControlWindowToFront, EXPCONFIG_SETTINGS_FOLDER, GetFile, ROWS, WindowExists.
static wave CONF_GetConfigFiles()
Return a text wave with absolute paths to the JSON configuration files.
References CONF_AUTO_LOADER_GLOBAL, CONF_AUTO_LOADER_USER, CONF_GetSettingsPath, GetAllFilesRecursivelyFromPath, IsEmpty.
Referenced by CONF_AutoLoader, CONF_OpenConfigInNotebook.
variable CONF_AutoLoader()
Automatically loads all *.json files from MIES Settings folder and opens and restores the corresponding windows Files are restored in case-insensitive alphanumeric order. Associated *_rig.json files are taken into account.
References CONF_GetConfigFiles, CONF_RestoreWindow, ControlWindowToFront, EXPCONFIG_RIGFILESUFFIX, EXPCONFIG_SETTINGS_FOLDER, ROWS, SplitTextWaveBySuffix.
static string CONF_GetSettingsPath(variable type)
Returns a symbolic path to the settings folder.
type One of CONF_AUTO_LOADER_GLOBAL or CONF_AUTO_LOADER_USER name of an igor symbolic path to the settings folder
References ASSERT, CONF_AUTO_LOADER_GLOBAL, CONF_AUTO_LOADER_USER, CONF_AUTO_LOADER_USER_PATH, CreateFolderOnDisk, EXPCONFIG_SETTINGS_FOLDER, FolderExists.
Referenced by CONF_GetConfigFiles.
variable CONF_SaveWindow(string fName)
Saves the GUI state of a window and all of its subwindows to a configuration file.
fName file name of configuration file to save configuration
References ASSERT, AssertOnAndClearRTError, ClearRTError, CONF_AllWindowsToJSON, CONF_AUTO_LOADER_GLOBAL, CONF_SaveDAEphys, ControlWindowToFront, EXPCONFIG_EXCLUDE_CTRLTYPES, EXPCONFIG_FILEFILTER, EXPCONFIG_JSON_INDENT, EXPCONFIG_SAVE_VALUE, GetCurrentWindow, GetMainWindow, IsNaN, PanelIsType, PANELTAG_DAEPHYS, SaveTextFile.
variable CONF_RestoreWindow(string fName=defaultValue, variable usePanelTypeFromFile=defaultValue, string rigFile=defaultValue)
Restores the GUI state of window and all of its subwindows from a configuration file.
fName file name of configuration file to read configuration usePanelTypeFromFile [optional, default = 0] if set to 1 then the panel type from the json is interpreted and a new panel of that type is opened rigFile [optional, default = ""] name of secondary rig configuration file with complementary data. This parameter is valid when loading for a DA_Ephys panel
References ASSERT, AssertOnAndClearRTError, ClearRTError, CONF_AddConfigFileUserData, CONF_AUTO_LOADER_GLOBAL, CONF_JoinRigFile, CONF_JSONToWindow, CONF_ParseJSON, CONF_RestoreDAEphys, DB_OpenDataBrowser, EXPCONFIG_FILEFILTER, EXPCONFIG_RESERVED_TAGENTRY, EXPCONFIG_SAVE_DISABLED, EXPCONFIG_SAVE_USERDATA, EXPCONFIG_SAVE_VALUE, GetCurrentWindow, GetMainWindow, IsEmpty, IsNaN, LoadTextFile, PanelIsType, PANELTAG_DAEPHYS, PANELTAG_DATABROWSER.
Referenced by CONF_AutoLoader.
static variable CONF_SaveDAEphys(string fName)
Saves the GUI state of a DA_Ephys panel to a configuration file.
fName file name of configuration file to store DA_Ephys configuration
References ASSERT, AssertOnAndClearRTError, ClearRTError, CONF_AllWindowsToJSON, CONF_AUTO_LOADER_GLOBAL, CONF_DefaultSettings, CONF_GetAmplifierSettings, CONF_GetUserPressure, DAEPHYS_EXCLUDE_CTRLTYPES, EXPCONFIG_FILEFILTER, EXPCONFIG_JSON_HSASSOCBLOCK, EXPCONFIG_JSON_INDENT, EXPCONFIG_JSON_USERPRESSBLOCK, EXPCONFIG_RESERVED_DATABLOCK, EXPCONFIG_SAVE_BUTTONS_ONLY_PRESSED, EXPCONFIG_SAVE_ONLY_RELEVANT, EXPCONFIG_SAVE_POPUPMENU_AS_STRING_ONLY, EXPCONFIG_SAVE_VALUE, GetCurrentWindow, GetMainWindow, IsNaN, PanelIsType, PANELTAG_DAEPHYS, SaveTextFile.
Referenced by CONF_SaveWindow.
string CONF_RestoreDAEphys(variable jsonID, string fullFilePath, variable middleOfExperiment=defaultValue, variable forceNewPanel=defaultValue)
Restores the GUI state of a DA_Ephys panel from a configuration file.
jsonID json ID of json object to restore DA_Ephys panel from fullFilePath full file path of the file where the json object was parsed from middleOfExperiment [optional, default = 0] Allows MIES config in the middle of experiment. Instead of setting MCC parameters they are pulled from actively recording MCCs to configure MIES] forceNewPanel [optional, default = 0] When set opens always a fresh DA_Ephys panel, otherwise follows this priority order: Reuses locked DA_Ephys panel with same device as saved in configuration Uses open unlocked DA_Ephys panel Opens new DA_Ephys panel name of the created DAEphys panel
References ASSERT, AssertOnAndClearRTError, CHECKBOX_UNSELECTED, ClearRTError, CONF_FindWindow, CONF_GetStringFromSavedControl, CONF_GetStringFromSettings, CONF_GetVariableFromSettings, CONF_JSONToWindow, CONF_RestoreHeadstageAssociation, CONF_RestoreUserPressure, CreateFolderOnDisk, DAEPHYS_UDATA_WINHANDLE, DAP_CreateDAEphysPanel, EXPCONFIG_JSON_LOGFILE_UPLOAD, EXPCONFIG_JSON_LOGFILE_UPLOAD_DEFAULT, EXPCONFIG_JSON_SAVE_PATH, EXPCONFIG_JSON_STIMSET_NAME, EXPCONFIG_JSON_SWEEP_ROLLBACK, EXPCONFIG_MINIMIZE_ON_RESTORE, EXPCONFIG_SAVE_DISABLED, EXPCONFIG_SAVE_ONLY_RELEVANT, EXPCONFIG_SAVE_POPUPMENU_AS_STRING_ONLY, EXPCONFIG_SAVE_VALUE, EXPCONFIG_SWEEPROLLBACK_DEFAULT, EXPCONFIG_UDATA_EXCLUDE_RESTORE, FileExists, GetListOfUnlockedDevices, GetTimeStamp, GetUniqueInteger, IsDriveValid, IsEmpty, PACKED_FILE_EXPERIMENT_SUFFIX, PanelIsType, PANELTAG_DAEPHYS, PGC_SetAndActivateControl, UploadLogFilesDaily, WindowExists.
Referenced by CONF_RestoreWindow.
static variable CONF_AddConfigFileUserData(string win, string fullFilePath, string rigFile)
Add the config file paths and SHA-256 hashes to the panel as user data.
References CalcHashForFile, FileExists.
Referenced by CONF_RestoreWindow.
static variable CONF_ParseJSON(string str)
Parses a json formatted string to a json object. This function shows a helpful error message if the parse fails.
str string in json format jsonID of the json object
References ASSERT, AssertOnAndClearRTError, ClearRTError.
Referenced by CONF_JoinRigFile, CONF_RestoreWindow.
static string CONF_GetDAEphysActiveHeadstages(variable jsonID)
Retrieves list of active headstages saved in a DA_Ephys configuration file.
jsonID ID of existing json List of active head stages
References CONF_GetWaveFromSavedControlArray, DAEPHYS_HEADSTAGECTRLARRAYPREFIX, NumericWaveToList.
static variable CONF_RequireConfigBlockExists(variable jsonID)
Checks if EXPCONFIG_RESERVED_DATABLOCK exists in json; ASSERTion is thrown if not found.
jsonID ID of existing json
References ASSERT, EXPCONFIG_RESERVED_DATABLOCK.
Referenced by CONF_GetStringFromSettings, CONF_GetVariableFromSettings, CONF_RestoreHeadstageAssociation, CONF_RestoreUserPressure.
static string CONF_GetStringFromSettings(variable jsonID, string keyName)
Retrieves a string value from a setting.
jsonID ID of existing json keyName key name of setting string from member with keyname in the EXPCONFIG_RESERVED_DATABLOCK
References CONF_RequireConfigBlockExists, EXPCONFIG_RESERVED_DATABLOCK.
Referenced by CONF_RestoreDAEphys, CONF_RestoreHeadstageAssociation.
static variable CONF_GetVariableFromSettings(variable jsonID, string keyName, variable defaultValue=defaultValue)
Retrieves a variable/boolean/null value from a saved control note: boolean control property values are also saved in the EXPCONFIG_FIELD_CTRLVVALUE field.
jsonID ID of existing json keyName key name of setting defaultValue [optional, defaults to off] allows to query optional entries, if the value could not be found this is returned instead value of the EXPCONFIG_FIELD_CTRLVVALUE field of the control
References CONF_RequireConfigBlockExists, EXPCONFIG_RESERVED_DATABLOCK, IsNaN.
Referenced by CONF_RestoreDAEphys.
static string CONF_FindControl(variable jsonID, string niceName)
Returns the path to the first control named nicename found in the json in all saved windows This might as well be a ControlArray.
jsonID ID of existing json niceName nice name of control Path to control in json, empty string if not found
References CONF_GetWindowNames, CONF_TraversalFinder, IsEmpty, ROWS.
Referenced by CONF_GetStringFromSavedControl, CONF_GetVariableFromSavedControl, CONF_GetWaveFromSavedControlArray, CONF_RestoreControl.
static string CONF_TraversalFinder(variable jsonID, string basePath, string niceName)
Returns the path to the first control named nicename found traversing the json starting at basePath This might as well be a ControlArray. This function runs recursively.
jsonID ID of existing json basePath root of traversal start niceName nice name of control Path to control in json, empty string if not found
References CONF_TraversalFinder, EXPCONFIG_CTRLGROUP_SUFFIX, IsEmpty, ROWS, SplitTextWaveBySuffix.
Referenced by CONF_FindControl, CONF_TraversalFinder.
static wave CONF_GetWaveFromSavedControlArray(variable jsonID, string arrayName)
Retrieves a wave from a saved ControlArray It is REQUIRED that ALL ELEMENTS of the ControlArray are of NUMERIC type.
jsonID ID of existing json arrayName name of ControlArray text wave with data from ControlArray
References ASSERT, CONF_FindControl, EXPCONFIG_FIELD_CTRLARRAYVALUES, IsEmpty.
Referenced by CONF_GetDAEphysActiveHeadstages.
static string CONF_GetStringFromSavedControl(variable jsonID, string niceName)
Retrieves a string value from a saved control.
jsonID ID of existing json niceName nice name of control value of the EXPCONFIG_FIELD_CTRLSVALUE field of the control
References ASSERT, CONF_FindControl, EXPCONFIG_FIELD_CTRLSVALUE, IsEmpty.
Referenced by CONF_RestoreDAEphys.
static variable CONF_GetVariableFromSavedControl(variable jsonID, string niceName)
Retrieves a variable value from a saved control.
jsonID ID of existing json niceName nice name of control value of the EXPCONFIG_FIELD_CTRLVVALUE field of the control
References ASSERT, CONF_FindControl, EXPCONFIG_FIELD_CTRLVVALUE, IsEmpty.
static wave CONF_GetWindowNames(variable jsonID)
Returns a wave with all configuration sections ( aka control groups). This equals the top level keys without the EXPCONFIG_RESERVED_DATABLOCK key.
jsonID ID of existing json Text wave with all named configuration sections
References EXPCONFIG_RESERVED_DATABLOCK, EXPCONFIG_RESERVED_TAGENTRY, RemoveTextWaveEntry1D.
Referenced by CONF_FindControl, CONF_JSONToWindow.
static wave CONF_GetControlArrayList(string wName)
Returns a two column free wave with ControlArrayName and associated control list from a window.
wName Name of window Text wave with two columns and in each row ControlArray name (column ARRAYNAME) and control list (column CTRLNAMELIST)
References COLS, EnsureLargeEnoughWave, EXPCONFIG_UDATA_CTRLARRAY, IsEmpty, MINIMUM_WAVE_SIZE, ROWS.
Referenced by CONF_JSONToWindow.
static variable CONF_GatherControlsFromJSON(WaveText ctrlData, variable jsonID, string basePath)
Gathers recursively all control nice names and control paths from a configuration json by traversing all sub objects.
ctrlData ctrlData wave, 2d four column text wave as created in CONF_JSONToWindow(). This wave is updated by this function. jsonID json object to traverse basePath root path for traversal
References CONF_GatherControlsFromJSON, EXPCONFIG_CTRLGROUP_SUFFIX, ROWS, SplitTextWaveBySuffix.
Referenced by CONF_GatherControlsFromJSON, CONF_JSONToWindow.
string CONF_JSONToWindow(string wName, variable restoreMask, variable jsonID)
Restores GUI state of a window from a json The following userdata properties are considered: EXPCONFIG_UDATA_EXCLUDE_RESTORE, EXPCONFIG_UDATA_RESTORE_PRIORITY It is supported that the current main reference window in the GUI changes its name. It is not supported that a not yet restored subwindow of it changes its name.
wName main reference window name in GUI restoreMask Bit mask which properties are restored from WindowControlSavingMask constants jsonID ID of existing json name of main window after restore
References ASSERT, AssertOnAndClearRTError, ClearRTError, COLS, CONF_FindWindow, CONF_GatherControlsFromJSON, CONF_GetControlArrayList, CONF_GetWindowNames, CONF_RestoreControl, EXPCONFIG_MINIMIZE_ON_RESTORE, EXPCONFIG_SAVE_CTRLTYPE, EXPCONFIG_SAVE_DISABLED, EXPCONFIG_SAVE_POSITION, EXPCONFIG_SAVE_USERDATA, EXPCONFIG_SAVE_VALUE, EXPCONFIG_UDATA_CTRLARRAY, EXPCONFIG_UDATA_EXCLUDE_RESTORE, EXPCONFIG_UDATA_NICENAME, EXPCONFIG_UDATA_RESTORE_PRIORITY, EXPCONFIG_UDATA_WINHANDLE, GetMainWindow, GetUniqueInteger, IsEmpty, ROWS, SearchForDuplicates, WindowExists.
Referenced by CONF_RestoreDAEphys, CONF_RestoreWindow.
static string CONF_FindWindow(string winHandle=defaultValue, string uKey=defaultValue)
Returns the window with the set window handle.
winHandle window handle uKey [optional, default = EXPCONFIG_UDATA_WINHANDLE] userdata key that stores the handle value Window name of the window with the given handle; empty string if not found.
References EXPCONFIG_UDATA_WINHANDLE, GetAllWindows.
Referenced by CONF_JSONToWindow, CONF_RestoreDAEphys.
static variable CONF_RestoreControl(string wName, variable restoreMask, variable jsonID, string ctrlName=defaultValue, string jsonPath=defaultValue)
Restores properties of a control from a json The following control userdata properties are considered: EXPCONFIG_UDATA_EXCLUDE_RESTORE; EXPCONFIG_UDATA_BUTTONPRESS (for Buttons)
wName Window name restoreMask Bit mask which properties are restored from WindowControlSavingMask constants jsonID ID of existing json ctrlName Control name jsonPath [optional, default = n/a] When given: the control is expected to be a named json object (with the control nice name) If not given: the jsons second level (assuming default format) is searched for the associated object. This is slower.
References ASSERT, CONF_FindControl, CONTROL_TYPE_BUTTON, CONTROL_TYPE_CHART, CONTROL_TYPE_CHECKBOX, CONTROL_TYPE_CUSTOMCONTROL, CONTROL_TYPE_GROUPBOX, CONTROL_TYPE_LISTBOX, CONTROL_TYPE_POPUPMENU, CONTROL_TYPE_SETVARIABLE, CONTROL_TYPE_SLIDER, CONTROL_TYPE_TAB, CONTROL_TYPE_TITLEBOX, CONTROL_TYPE_VALDISPLAY, DISABLE_CONTROL_BIT, DisableControl, EnableControl, EXISTS_AS_VAR_OR_STR, EXISTS_AS_WAVE, EXPCONFIG_FIELD_BASE64PREFIX, EXPCONFIG_FIELD_CTRLARRAYVALUES, EXPCONFIG_FIELD_CTRLDISABLED, EXPCONFIG_FIELD_CTRLPOSALIGN, EXPCONFIG_FIELD_CTRLPOSHEIGHT, EXPCONFIG_FIELD_CTRLPOSPOS, EXPCONFIG_FIELD_CTRLPOSTOP, EXPCONFIG_FIELD_CTRLPOSWIDTH, EXPCONFIG_FIELD_CTRLSDF, EXPCONFIG_FIELD_CTRLSVALUE, EXPCONFIG_FIELD_CTRLTYPE, EXPCONFIG_FIELD_CTRLUSERDATA, EXPCONFIG_FIELD_CTRLVVALUE, EXPCONFIG_GUI_CTRLLIST, EXPCONFIG_GUI_CTRLTYPES, EXPCONFIG_SAVE_DISABLED, EXPCONFIG_SAVE_ONLY_RELEVANT, EXPCONFIG_SAVE_POPUPMENU_AS_INDEX_ONLY, EXPCONFIG_SAVE_POPUPMENU_AS_STRING_ONLY, EXPCONFIG_SAVE_POSITION, EXPCONFIG_SAVE_USERDATA, EXPCONFIG_SAVE_VALUE, EXPCONFIG_UDATA_BUTTONPRESS, EXPCONFIG_UDATA_CTRLARRAY, EXPCONFIG_UDATA_CTRLARRAYINDEX, EXPCONFIG_UDATA_EXCLUDE_RESTORE, EXPCONFIG_UDATA_MAXCTRLARRAYINDEX, EXPCONFIG_UDATA_NICENAME, GetInternalSetVariableType, HIDDEN_CONTROL_BIT, HideControl, IsEmpty, IsNaN, PGC_MODE_SKIP_ON_DISABLED, PGC_SetAndActivateControl, ROWS, SET_VARIABLE_BUILTIN_NUM, SET_VARIABLE_BUILTIN_STR, ShowControl.
Referenced by CONF_JSONToWindow.
variable CONF_AllWindowsToJSON(string wName, variable saveMask=defaultValue, string excCtrlTypes=defaultValue)
Serializes all controls of a window and its subwindows into a json object.
wName name of main window saveMask bit pattern based configuration setting for saving WindowControlSavingMask excCtrlTypes [optional, default = ""], list of control type codes for excluded control types for saving e.g. "1;6;" to exclude all buttons and charts json ID of object where all controls where serialized into
References ASSERT, AssertOnAndClearRTError, ClearRTError, CONF_WindowToJSON, EXPCONFIG_RESERVED_TAGENTRY, EXPCONFIG_UDATA_PANELTYPE, GetAllWindows, GetMainWindow, ROWS.
Referenced by CONF_SaveDAEphys, CONF_SaveWindow.
wave CONF_GetRadioButtonCouplingProtoFunc()
variable CONF_WindowToJSON(string wName, variable saveMask=defaultValue, string excCtrlTypes=defaultValue)
Saves complete GUI state of a window in a json For coupled CheckBoxes aka (radio buttons) the enabled radio button is saved, the disabled is not saved. For three or more coupled CheckBoxes the first enabled radio button is saved, the disabled are not saved. For three or more coupled CheckBoxes an assertion is thrown if no CheckBox is set.
wName Window name saveMask Bit mask which properties are saved from WindowControlSavingMask constants excCtrlTypes [optional, default = ""] List of excluded control types that are ignored jsonID ID of json containing the serialized GUI data
References ASSERT, AssertOnAndClearRTError, ClearRTError, COLS, CONF_ControlToJSON, DEBUGPRINT, EXPCONFIG_CTRLGROUP_SUFFIX, EXPCONFIG_EXCLUDE_USERDATA, EXPCONFIG_UDATA_BUTTONPRESS, EXPCONFIG_UDATA_CTRLARRAY, EXPCONFIG_UDATA_EXCLUDE_RESTORE, EXPCONFIG_UDATA_EXCLUDE_SAVE, EXPCONFIG_UDATA_JSONPATH, EXPCONFIG_UDATA_NICENAME, EXPCONFIG_UDATA_RADIOCOUPLING, EXPCONFIG_UDATA_RESTORE_PRIORITY, EXPCONFIG_UDATA_WINHANDLE, GetUniqueEntries, IsEmpty, IsNaN, ROWS, SearchForDuplicates, StringEndsWith, TextWaveToList.
Referenced by CONF_AllWindowsToJSON.
static string CONF_GetCompleteJSONCtrlPath(string path)
References EXPCONFIG_CTRLGROUP_SUFFIX.
Referenced by CONF_ControlToJSON.
static variable CONF_ControlToJSON(string wName, string ctrlName, variable saveMask, variable jsonID, string excCtrlTypes, string excUserKeys)
Adds properties of a control to a json.
wName Window name ctrlName Control name saveMask Bit mask which properties are saved from WindowControlSavingMask constants jsonID ID of existing json excCtrlTypes List of excluded control types that are ignored excUserKeys List of excluded keys of userdata fields that are ignored
References ASSERT, AssertOnAndClearRTError, ClearRTError, CONF_GetCompleteJSONCtrlPath, CONTROL_TYPE_BUTTON, CONTROL_TYPE_CHART, CONTROL_TYPE_CHECKBOX, CONTROL_TYPE_CUSTOMCONTROL, CONTROL_TYPE_GROUPBOX, CONTROL_TYPE_LISTBOX, CONTROL_TYPE_POPUPMENU, CONTROL_TYPE_SETVARIABLE, CONTROL_TYPE_SLIDER, CONTROL_TYPE_TAB, CONTROL_TYPE_TITLEBOX, CONTROL_TYPE_VALDISPLAY, ControlTypeToName, EXPCONFIG_DEFAULT_CTRL_JSONPATH, EXPCONFIG_FIELD_BASE64PREFIX, EXPCONFIG_FIELD_CTRLARRAYVALUES, EXPCONFIG_FIELD_CTRLDISABLED, EXPCONFIG_FIELD_CTRLPOSALIGN, EXPCONFIG_FIELD_CTRLPOSHEIGHT, EXPCONFIG_FIELD_CTRLPOSPOS, EXPCONFIG_FIELD_CTRLPOSTOP, EXPCONFIG_FIELD_CTRLPOSWIDTH, EXPCONFIG_FIELD_CTRLSDF, EXPCONFIG_FIELD_CTRLSVALUE, EXPCONFIG_FIELD_CTRLTYPE, EXPCONFIG_FIELD_CTRLUSERDATA, EXPCONFIG_FIELD_CTRLVVALUE, EXPCONFIG_GUI_CTRLTYPES, EXPCONFIG_GUI_PREFERRED, EXPCONFIG_GUI_SDATAFOLDER, EXPCONFIG_GUI_SUSERDATA, EXPCONFIG_GUI_SVALUE, EXPCONFIG_GUI_VVALUE, EXPCONFIG_RESERVED_DATABLOCK, EXPCONFIG_SAVE_BUTTONS_ONLY_PRESSED, EXPCONFIG_SAVE_CTRLTYPE, EXPCONFIG_SAVE_DISABLED, EXPCONFIG_SAVE_ONLY_RELEVANT, EXPCONFIG_SAVE_POPUPMENU_AS_INDEX_ONLY, EXPCONFIG_SAVE_POPUPMENU_AS_STRING_ONLY, EXPCONFIG_SAVE_POSITION, EXPCONFIG_SAVE_USERDATA, EXPCONFIG_SAVE_VALUE, EXPCONFIG_UDATA_BUTTONPRESS, EXPCONFIG_UDATA_CTRLARRAY, EXPCONFIG_UDATA_CTRLARRAYINDEX, EXPCONFIG_UDATA_EXCLUDE_SAVE, EXPCONFIG_UDATA_JSONPATH, EXPCONFIG_UDATA_MAXCTRLARRAYINDEX, EXPCONFIG_UDATA_NICENAME, GetInternalSetVariableType, IsEmpty, IsNaN, IsNull, ROWS, SET_VARIABLE_BUILTIN_NUM, SET_VARIABLE_BUILTIN_STR.
Referenced by CONF_WindowToJSON.
static variable CONF_RestoreHeadstageAssociation(string device, variable jsonID, variable midExp)
Opens MCCs and restores Headstage Association from configuration data to DA_Ephys panel.
device panel title of DA_Ephys panel jsonID ID of json object with configuration data midExp middle of experiment - uploads MCC relevant settings from panel to MCC instead
References AI_OpenMCCs, ASSERT, CONF_FindAmpInList, CONF_GetStringFromSettings, CONF_MCC_MidExp, CONF_Position_MCC_Win, CONF_RequireConfigBlockExists, CONF_RestoreAmplifierSettings, EXPCONFIG_JSON_AMPBLOCK, EXPCONFIG_JSON_AMPCHANNEL, EXPCONFIG_JSON_AMPICAD, EXPCONFIG_JSON_AMPICDA, EXPCONFIG_JSON_AMPSERIAL, EXPCONFIG_JSON_AMPTITLE, EXPCONFIG_JSON_AMPVCAD, EXPCONFIG_JSON_AMPVCDA, EXPCONFIG_JSON_HSASSOCBLOCK, EXPCONFIG_JSON_ICBLOCK, EXPCONFIG_JSON_POSITION_MCC, EXPCONFIG_JSON_PRESSAD, EXPCONFIG_JSON_PRESSADGAIN, EXPCONFIG_JSON_PRESSADUNIT, EXPCONFIG_JSON_PRESSCONSTNEG, EXPCONFIG_JSON_PRESSCONSTPOS, EXPCONFIG_JSON_PRESSDA, EXPCONFIG_JSON_PRESSDAGAIN, EXPCONFIG_JSON_PRESSDAUNIT, EXPCONFIG_JSON_PRESSDEV, EXPCONFIG_JSON_PRESSTTLA, EXPCONFIG_JSON_PRESSTTLB, EXPCONFIG_JSON_PRESSUREBLOCK, EXPCONFIG_JSON_VCBLOCK, EXPCONFIG_RESERVED_DATABLOCK, GetAmplifierTelegraphServers, GetCheckBoxState, IsFinite, IsNaN, NONE, NUM_HEADSTAGES, P_GetPressureDataWaveRef, PGC_SetAndActivateControl, ROWS.
Referenced by CONF_RestoreDAEphys.
static variable CONF_GetUserPressure(string device)
Retrieves current User Pressure settings to json.
device panel title of DA_Ephys panel jsonID ID of json object with user pressure configuration data
References EXPCONFIG_JSON_USERPRESSDA, EXPCONFIG_JSON_USERPRESSDEV, GetPopupMenuString.
Referenced by CONF_SaveDAEphys.
static variable CONF_RestoreUserPressure(string device, variable jsonID)
Restore User Pressure settings.
device panel title of DA_Ephys panel jsonID ID of json object with configuration data
References ASSERT, CONF_RequireConfigBlockExists, EXPCONFIG_JSON_USERPRESSBLOCK, EXPCONFIG_JSON_USERPRESSDA, EXPCONFIG_JSON_USERPRESSDEV, EXPCONFIG_RESERVED_DATABLOCK, PGC_SetAndActivateControl.
Referenced by CONF_RestoreDAEphys.
static variable CONF_GetAmplifierSettings(string device)
Retrieves current amplifier and pressure settings to json.
device device jsonID ID of json object with user pressure configuration data
References CHANNEL_TYPE_HEADSTAGE, DAG_GetChannelState, DAG_GetHeadstageMode, DAG_GetNumericalValue, DAP_ChangeHeadStageMode, DO_MCC_MIES_SYNCING, EXPCONFIG_JSON_AMP_AUTOBIAS, EXPCONFIG_JSON_AMP_AUTOBIAS_I_BIAS_MAX, EXPCONFIG_JSON_AMP_AUTOBIAS_V, EXPCONFIG_JSON_AMP_AUTOBIAS_V_RANGE, EXPCONFIG_JSON_AMP_BRIDGE_BALANCE, EXPCONFIG_JSON_AMP_BRIDGE_BALANCE_ENABLE, EXPCONFIG_JSON_AMP_CAP_NEUTRALIZATION, EXPCONFIG_JSON_AMP_CAP_NEUTRALIZATION_ENABLE, EXPCONFIG_JSON_AMP_COMP_CHAIN, EXPCONFIG_JSON_AMP_HOLD_ENABLE_IC, EXPCONFIG_JSON_AMP_HOLD_ENABLE_VC, EXPCONFIG_JSON_AMP_HOLD_IC, EXPCONFIG_JSON_AMP_HOLD_VC, EXPCONFIG_JSON_AMP_PIPETTE_OFFSET_IC, EXPCONFIG_JSON_AMP_PIPETTE_OFFSET_VC, EXPCONFIG_JSON_AMP_RS_COMP_CORRECTION, EXPCONFIG_JSON_AMP_RS_COMP_ENABLE, EXPCONFIG_JSON_AMP_RS_COMP_PREDICTION, EXPCONFIG_JSON_AMP_WHOLE_CELL_CAPACITANCE, EXPCONFIG_JSON_AMP_WHOLE_CELL_ENABLE, EXPCONFIG_JSON_AMP_WHOLE_CELL_RESISTANCE, EXPCONFIG_JSON_AMPBLOCK, EXPCONFIG_JSON_AMPCHANNEL, EXPCONFIG_JSON_AMPICAD, EXPCONFIG_JSON_AMPICDA, EXPCONFIG_JSON_AMPSERIAL, EXPCONFIG_JSON_AMPTITLE, EXPCONFIG_JSON_AMPVCAD, EXPCONFIG_JSON_AMPVCDA, EXPCONFIG_JSON_ICBLOCK, EXPCONFIG_JSON_PRESSAD, EXPCONFIG_JSON_PRESSADGAIN, EXPCONFIG_JSON_PRESSADUNIT, EXPCONFIG_JSON_PRESSCONSTNEG, EXPCONFIG_JSON_PRESSCONSTPOS, EXPCONFIG_JSON_PRESSDA, EXPCONFIG_JSON_PRESSDAGAIN, EXPCONFIG_JSON_PRESSDAUNIT, EXPCONFIG_JSON_PRESSDEV, EXPCONFIG_JSON_PRESSTTLA, EXPCONFIG_JSON_PRESSTTLB, EXPCONFIG_JSON_PRESSUREBLOCK, EXPCONFIG_JSON_VCBLOCK, EXPCONFIG_SETTINGS_AMPTITLE, GetChanAmpAssign, GetPopupMenuString, GetSetVariable, GetSetVariableString, I_CLAMP_MODE, IsFinite, NUM_HEADSTAGES, P_GetPressureDataWaveRef, PGC_SetAndActivateControl, ROWS, V_CLAMP_MODE.
Referenced by CONF_SaveDAEphys.
static variable CONF_RestoreAmplifierSettings(string device, variable headStage, variable jsonID, string basePath)
Restore the per headstage amplifier settings.
device device headStage MIES headstage number, must be in the range [0, NUM_HEADSTAGES] jsonID ID of json object with configuration data basePath absolute path in the json file to search the entries
References DAG_GetHeadstageMode, DAP_ChangeHeadStageMode, DO_MCC_MIES_SYNCING, EXPCONFIG_JSON_AMP_AUTOBIAS, EXPCONFIG_JSON_AMP_AUTOBIAS_I_BIAS_MAX, EXPCONFIG_JSON_AMP_AUTOBIAS_V, EXPCONFIG_JSON_AMP_AUTOBIAS_V_RANGE, EXPCONFIG_JSON_AMP_BRIDGE_BALANCE, EXPCONFIG_JSON_AMP_BRIDGE_BALANCE_ENABLE, EXPCONFIG_JSON_AMP_CAP_NEUTRALIZATION, EXPCONFIG_JSON_AMP_CAP_NEUTRALIZATION_ENABLE, EXPCONFIG_JSON_AMP_COMP_CHAIN, EXPCONFIG_JSON_AMP_HOLD_ENABLE_IC, EXPCONFIG_JSON_AMP_HOLD_ENABLE_VC, EXPCONFIG_JSON_AMP_HOLD_IC, EXPCONFIG_JSON_AMP_HOLD_VC, EXPCONFIG_JSON_AMP_PIPETTE_OFFSET_IC, EXPCONFIG_JSON_AMP_PIPETTE_OFFSET_VC, EXPCONFIG_JSON_AMP_RS_COMP_CORRECTION, EXPCONFIG_JSON_AMP_RS_COMP_ENABLE, EXPCONFIG_JSON_AMP_RS_COMP_PREDICTION, EXPCONFIG_JSON_AMP_WHOLE_CELL_CAPACITANCE, EXPCONFIG_JSON_AMP_WHOLE_CELL_ENABLE, EXPCONFIG_JSON_AMP_WHOLE_CELL_RESISTANCE, EXPCONFIG_JSON_AMPBLOCK, EXPCONFIG_JSON_ICBLOCK, EXPCONFIG_JSON_VCBLOCK, I_CLAMP_MODE, PGC_SetAndActivateControl, V_CLAMP_MODE.
Referenced by CONF_RestoreHeadstageAssociation.
static variable CONF_FindAmpInList(variable ampSerialRef, variable ampChannelIDRef)
Find the list index of a connected amplifier serial number.
ampSerialRef Amplifier Serial Number to search for ampChannelIDRef Headstage reference number
References ASSERT, DAP_GetNiceAmplifierChannelList, DAP_ParseAmplifierDef.
Referenced by CONF_RestoreHeadstageAssociation.
static variable CONF_MCC_MidExp(string device, variable headStage, variable jsonID)
References AI_GetMode, AI_SendToAmp, CHECKBOX_SELECTED, CHECKBOX_UNSELECTED, I_CLAMP_MODE, I_EQUAL_ZERO_MODE, MCC_GETBRIDGEBALENABLE_FUNC, MCC_GETBRIDGEBALRESIST_FUNC, MCC_GETHOLDING_FUNC, MCC_GETHOLDINGENABLE_FUNC, MCC_GETNEUTRALIZATIONCAP_FUNC, MCC_GETNEUTRALIZATIONENABL_FUNC, MCC_GETPIPETTEOFFSET_FUNC, PGC_SetAndActivateControl, V_CLAMP_MODE.
Referenced by CONF_RestoreHeadstageAssociation.
variable CONF_Position_MCC_Win(string serialNum, string winTitle, string winPosition)
Position MCC windows to upper right monitor using nircmd.exe.
serialNum Serial number of MCC winTitle Name of MCC window winPosition One of 4 monitors to position MCCs in
References FileExists, GetFolder, GetWindowsPath, NONE, NUM_HEADSTAGES.
Referenced by CONF_RestoreHeadstageAssociation.
static variable CONF_JoinRigFile(variable jsonID, string rigFileName)
Loads, parses and joins a *_rig.json file to a main configuration file.
jsonID jsonID of main configuration rigFileName full file path of rig file
References CONF_ParseJSON, IsEmpty, LoadTextFile, SyncJSON.
Referenced by CONF_RestoreWindow.