MIES_AmplifierInteraction.ipf
const double ZERO_TOLERANCE
Referenced by AI_ZeroAmps.
const string AMPLIFIER_CONTROLS_VC
Referenced by AI_SyncGUIToAmpStorageAndMCCApp, AI_UpdateAmpView.
const string AMPLIFIER_CONTROLS_IC
Referenced by AI_SyncGUIToAmpStorageAndMCCApp, AI_UpdateAmpView.
const double MAX_PIPETTEOFFSET
Referenced by AI_MIESAutoPipetteOffset.
const double MIN_PIPETTEOFFSET
Referenced by AI_MIESAutoPipetteOffset.
static variable AI_InitAxonTelegraphStruct(AxonTelegraph_DataStruct *tds)
static variable AI_GetAmpAxonSerial(string device, variable headStage)
Returns the serial number of the headstage compatible with Axon* functions,.
GetChanAmpAssign
References GetChanAmpAssign.
Referenced by AI_GetAmpMCCSerial.
static string AI_GetAmpMCCSerial(string device, variable headStage)
Returns the serial number of the headstage compatible with MCC* functions,.
GetChanAmpAssign
References AI_GetAmpAxonSerial.
static variable AI_GetAmpChannel(string device, variable headStage)
Return the channel of the currently selected head stage.
References GetChanAmpAssign.
static variable AI_IsValidSerialAndChannel(string mccSerial=defaultValue, variable axonSerial=defaultValue, variable channel=defaultValue)
References isEmpty, IsFinite.
variable AI_GetMCCScale(variable clampMode, variable func)
Return the unit prefixes used by MIES in comparison to the MCC app.
clampMode clamp mode (pass NaN for doesn't matter) func MCC function, one of AI_SendToAmpConstants
References AI_AssertOnInvalidClampMode, IsFinite, MCC_AUTOBRIDGEBALANCE_FUNC, MCC_AUTOPIPETTEOFFSET_FUNC, MCC_GETBRIDGEBALRESIST_FUNC, MCC_GETHOLDING_FUNC, MCC_GETNEUTRALIZATIONCAP_FUNC, MCC_GETPIPETTEOFFSET_FUNC, MCC_GETRSCOMPBANDWIDTH_FUNC, MCC_GETWHOLECELLCOMPCAP_FUNC, MCC_GETWHOLECELLCOMPRESIST_FUNC, MCC_SETBRIDGEBALRESIST_FUNC, MCC_SETHOLDING_FUNC, MCC_SETNEUTRALIZATIONCAP_FUNC, MCC_SETPIPETTEOFFSET_FUNC, MCC_SETRSCOMPBANDWIDTH_FUNC, MCC_SETWHOLECELLCOMPCAP_FUNC, MCC_SETWHOLECELLCOMPRESIST_FUNC, V_CLAMP_MODE.
variable AI_UpdateAmpModel(string device, string ctrl, variable headStage, variable value=defaultValue, variable sendToAll=defaultValue, variable checkBeforeWrite=defaultValue, variable selectAmp=defaultValue)
Update the AmpStorageWave entry and send the value to the amplifier.
Additionally setting the GUI value if the given headstage is the selected one and a value has been passed. device device ctrl name of the amplifier control headStage MIES headstage number, must be in the range [0, NUM_HEADSTAGES] value [optional: defaults to the controls value] value to set. values is in MIES units, see AI_SendToAmp() and there the description of usePrefixes. sendToAll [optional: defaults to the state of the checkbox] should the value be send to all active headstages (true) or just to the given one (false) checkBeforeWrite [optional, defaults to false] (ignored for getter functions) check the current value and do nothing if it is equal within some tolerance to the one written selectAmp [optional, defaults to true] Select the amplifier before use, some callers might save time in doing that once themselves. 0 on success, 1 otherwise
References AI_SelectMultiClamp, AI_SendToAmp, AI_UpdateAmpModel, AI_UpdateAmpView, AMPLIFIER_CONNECTION_SUCCESS, ASSERT, AssertOnAndClearRTError, CHANNEL_TYPE_HEADSTAGE, CheckIfValueIsInsideLimits, ClearRTError, ConvertAmplifierModeToString, DAG_GetChannelState, DAG_GetHeadstageMode, DAG_GetNumericalValue, DAP_AbortIfUnlocked, DAP_ChangeHeadStageMode, DEBUGPRINT, DeviceHasFollower, GetAmplifierParamStorageWave, GetTabID, I_CLAMP_MODE, MCC_AUTOBRIDGEBALANCE_FUNC, MCC_AUTOFASTCOMP_FUNC, MCC_AUTOPIPETTEOFFSET_FUNC, MCC_AUTOSLOWCOMP_FUNC, MCC_AUTOWHOLECELLCOMP_FUNC, MCC_GETPIPETTEOFFSET_FUNC, MCC_GETWHOLECELLCOMPCAP_FUNC, MCC_GETWHOLECELLCOMPENABLE_FUNC, MCC_GETWHOLECELLCOMPRESIST_FUNC, MCC_SETBRIDGEBALENABLE_FUNC, MCC_SETBRIDGEBALRESIST_FUNC, MCC_SETHOLDING_FUNC, MCC_SETHOLDINGENABLE_FUNC, MCC_SETNEUTRALIZATIONCAP_FUNC, MCC_SETNEUTRALIZATIONENABL_FUNC, MCC_SETPIPETTEOFFSET_FUNC, MCC_SETRSCOMPCORRECTION_FUNC, MCC_SETRSCOMPENABLE_FUNC, MCC_SETRSCOMPPREDICTION_FUNC, MCC_SETWHOLECELLCOMPCAP_FUNC, MCC_SETWHOLECELLCOMPENABLE_FUNC, MCC_SETWHOLECELLCOMPRESIST_FUNC, MCC_SKIP_UPDATES, NUM_HEADSTAGES, PGC_SetAndActivateControl, TEST_PULSE_NOT_RUNNING, TP_RestartTestPulse, TP_StopTestPulseFast, TP_UpdateHoldCmdInTPStorage, V_CLAMP_MODE.
Referenced by AI_MIESAutoPipetteOffset, AI_SyncGUIToAmpStorageAndMCCApp, AI_UpdateAmpModel, DAP_ButtonProc_AmpCntrls, DAP_CheckProc_AmpCntrls, DAP_SetVarProc_AmpCntrls, DQ_ApplyAutoBias, P_MethodApproach, P_UpdateVcom.
variable AI_SyncAmpStorageToGUI(string device, variable headstage)
Convenience wrapper for AI_UpdateAmpView.
Disallows setting single controls for outside callers as AI_UpdateAmpModel should be used for that.
References AI_UpdateAmpView.
Referenced by DAP_UpdateClampmodeTabs.
variable AI_SyncGUIToAmpStorageAndMCCApp(string device, variable headStage, variable clampMode)
Sync the settings from the GUI to the amp storage wave and the MCC application.
References AI_AssertOnInvalidClampMode, AI_EnsureCorrectMode, AI_UpdateAmpModel, AMPLIFIER_CONTROLS_IC, AMPLIFIER_CONTROLS_VC, DAG_GetNumericalValue, DAP_AbortIfUnlocked, V_CLAMP_MODE.
Referenced by DAP_UpdateClampmodeTabs.
static variable AI_UpdateAmpView(string device, variable headStage, string ctrl=defaultValue)
Synchronizes the AmpStorageWave to the amplifier GUI control.
device device headStage MIES headstage number, must be in the range [0, NUM_HEADSTAGES] ctrl [optional, defaults to all controls] name of the control being updated
References AI_AmpStorageControlToRowLabel, AMPLIFIER_CONTROLS_IC, AMPLIFIER_CONTROLS_VC, ASSERT, DAG_GetNumericalValue, DAG_Update, DAP_AbortIfUnlocked, GetAmplifierParamStorageWave, IsEmpty, SetCheckBoxState, SetSetVariable.
Referenced by AI_SyncAmpStorageToGUI, AI_UpdateAmpModel.
static string AI_AmpStorageControlToRowLabel(string ctrl)
Convert amplifier controls to row labels for AmpStorageWave
References ASSERT.
Referenced by AI_UpdateAmpView.
variable AI_SetMIESHeadstage(string device, variable headstage=defaultValue, variable increment=defaultValue)
References DAG_GetNumericalValue, NUM_HEADSTAGES, PGC_SetAndActivateControl.
variable AI_ZeroAmps(string device, variable headStage=defaultValue)
Executes MCC auto zero command if the baseline current exceeds ZERO_TOLERANCE.
device device headStage [optional: defaults to all active headstages]
References AI_MIESAutoPipetteOffset, GetTPResults, IsDeviceActiveWithBGTask, NUM_HEADSTAGES, ZERO_TOLERANCE.
Referenced by P_MethodApproach.
static variable AI_MIESAutoPipetteOffset(string device, variable headStage)
Auto pipette zeroing Quicker than MCC auto pipette offset.
device device headStage MIES headstage number, must be in the range [0, NUM_HEADSTAGES]
References AI_SendToAmp, AI_UpdateAmpModel, ASSERT, DAG_GetHeadstageMode, GetTPResults, I_CLAMP_MODE, MAX_PIPETTEOFFSET, MCC_GETPIPETTEOFFSET_FUNC, MIN_PIPETTEOFFSET, V_CLAMP_MODE.
Referenced by AI_ZeroAmps.
variable AI_QueryGainsUnitsForClampMode(string device, variable headstage, variable clampMode, variable *DAGain, variable *ADGain, string *DAUnit, string *ADUnit)
Query the MCC application for the gains and units of the given clamp mode.
Assumes that the correct amplifier is already selected!
References AI_AssertOnInvalidClampMode, AI_RetrieveGains, V_CLAMP_MODE.
Referenced by DAP_CheckHeadStage.
variable AI_UpdateChanAmpAssign(string device, variable headStage, variable clampMode, variable DAGain, variable ADGain, string DAUnit, string ADUnit)
Update the ChanAmpAssign and ChanAmpAssignUnit waves according to the passed clamp mode with the gains and units.
References AI_AssertOnInvalidClampMode, GetChanAmpAssign, GetChanAmpAssignUnit, I_CLAMP_MODE, I_EQUAL_ZERO_MODE, V_CLAMP_MODE.
Referenced by DAP_CheckHeadStage.
variable AI_AssertOnInvalidClampMode(variable clampMode)
Assert on invalid clamp modes, does nothing otherwise.
References AI_IsValidClampMode, ASSERT.
Referenced by AI_GetMCCScale, AI_QueryGainsUnitsForClampMode, AI_SyncGUIToAmpStorageAndMCCApp, AI_UpdateChanAmpAssign, DAG_GetActiveHeadstages, DAP_ChangeHeadStageMode, DAP_GetInfoFromControl, DAP_UpdateClampmodeTabs.
variable AI_IsValidClampMode(variable clampMode)
Return true if the given clamp mode is valid.
References I_CLAMP_MODE, I_EQUAL_ZERO_MODE, V_CLAMP_MODE.
Referenced by AI_AssertOnInvalidClampMode, DAP_CheckHeadStage, GetHeadstageFromSettings.
variable AI_OpenMCCs(string ampSerialNumList, string ampTitleList=defaultValue)
Opens Multi-clamp commander software.
ampSerialNumList A text list of amplifier serial numbers without leading zeroes Ex. "834001;435003;836059", "0;" starts the MCC in Demo mode Duplicate serial numbers are ignored as well as amplifier titles for the duplicates. For each unique serial number one MCC is opened. ampTitleList [optional, defaults to blank] MCC gui window title 1 if all unique MCCs specified in ampSerialNumList were opened, 0 if one or more MCCs specified in ampSerialNumList were not able to be opened
References AI_GetMCCSerialNumbers, AI_GetMCCWinFilePath, ASSERT, ControlWindowToFront, ROWS, TextWaveToList.
Referenced by CONF_RestoreHeadstageAssociation.
static wave AI_GetMCCSerialNumbers()
Gets the serial numbers of all open MCCs.
a 1D FREE wave containing amplifier serial numbers without leading zeroes
References AI_FindConnectedAmps, COLS, GetAmplifierTelegraphServers, GetUniqueEntries.
Referenced by AI_OpenMCCs.
static string AI_GetMCCWinFilePath()
Return a path to the MCC.
Hardcoded as Igor does not allow to query that information. Distinguishes between i386 and x64 Igor versions
References ASSERT, FileExists, GetProgramFilesFolder, ROWS.
Referenced by AI_OpenMCCs.
variable AI_GetHoldingCommand(string device, variable headstage)
References DEBUGPRINT.
Referenced by TP_UpdateHoldCmdInTPStorage.
variable AI_GetMode(string device, variable headstage)
References DEBUGPRINT.
Referenced by CONF_MCC_MidExp.
static variable AI_RetrieveGains(string device, variable headstage, variable clampMode, variable *ADGain, variable *DAGain)
References DEBUGPRINT.
Referenced by AI_QueryGainsUnitsForClampMode.
static variable AI_SwitchAxonAmpMode()
References DEBUGPRINT.
variable AI_SelectMultiClamp(string device, variable headStage)
References DEBUGPRINT.
Referenced by AI_UpdateAmpModel, BWO_CheckGlobalSettings, DAP_CheckHeadStage, ED_TPDocumentation, IVS_ConfigureMCC.
variable AI_SetClampMode(string device, variable headStage, variable mode, variable zeroStep=defaultValue)
References DEBUGPRINT.
Referenced by DAP_ChangeHeadStageMode.
variable AI_SendToAmp(string device, variable headStage, variable mode, variable func, variable value, variable checkBeforeWrite=defaultValue, variable usePrefixes=defaultValue, variable selectAmp=defaultValue)
References DEBUGPRINT.
Referenced by AI_MIESAutoPipetteOffset, AI_UpdateAmpModel, CONF_MCC_MidExp, DQ_ApplyAutoBias, ED_TPDocumentation, IVS_ConfigureMCC.
variable AI_EnsureCorrectMode(string device, variable headStage, variable selectAmp=defaultValue)
References DEBUGPRINT.
Referenced by AI_SyncGUIToAmpStorageAndMCCApp, DAP_CheckHeadStage.
variable AI_FillAndSendAmpliferSettings(string device, variable sweepNo)
References DEBUGPRINT.
Referenced by ED_createWaveNoteTags.
variable AI_QueryGainsFromMCC(string device)
References DEBUGPRINT.
Referenced by DAP_ButtonProc_AutoFillGain.
variable AI_FindConnectedAmps()
References DEBUGPRINT.
Referenced by AI_GetMCCSerialNumbers, DAP_ButtonCtrlFindConnectedAmps, DAP_LockDevice.
static variable AI_PublishAutoBridgeBalance(string device, variable headstage, variable resistance)
References AMPLIFIER_AUTO_BRIDGE_BALANCE, FFI_GetJSONTemplate, FFI_Publish.