MIES_IVSCC.ipf
const double IVS_DEFAULT_NWBVERSION
Referenced by IVS_ExportAllData.
const double IVS_DEFAULT_HEADSTAGE
Referenced by IVS_ConfigureMCC, IVS_finishGigOhmSealQCCheck, IVS_finishInitAccessQCCheck, IVS_runBaselineCheckQC, IVS_RunGigOhmSealQC, IVS_runInitAccessResisQC, IVS_runStimWave.
const string IVS_DEFAULT_DEVICE
Referenced by IVS_ConfigureMCC, IVS_finishGigOhmSealQCCheck, IVS_finishInitAccessQCCheck, IVS_runBaselineCheckQC, IVS_RunGigOhmSealQC, IVS_runInitAccessResisQC, IVS_runStimWave.
variable IVS_ConfigureMCC()
References AI_SelectMultiClamp, AI_SendToAmp, AMPLIFIER_CONNECTION_SUCCESS, CHECKBOX_SELECTED, DAP_GetClampModeControl, GetTabID, I_CLAMP_MODE, IsFinite, IVS_DEFAULT_DEVICE, IVS_DEFAULT_HEADSTAGE, MCC_SETBRIDGEBALENABLE_FUNC, MCC_SETHOLDING_FUNC, MCC_SETHOLDINGENABLE_FUNC, MCC_SETNEUTRALIZATIONCAP_FUNC, MCC_SETNEUTRALIZATIONENABL_FUNC, MCC_SETOSCKILLERENABLE_FUNC, MCC_SETRSCOMPBANDWIDTH_FUNC, MCC_SETRSCOMPCORRECTION_FUNC, MCC_SETRSCOMPENABLE_FUNC, MCC_SETRSCOMPPREDICTION_FUNC, MCC_SETSLOWCOMPTAUX20ENAB_FUNC, MCC_SETSLOWCURRENTINJENABL_FUNC, MCC_SETSLOWCURRENTINJLEVEL_FUNC, MCC_SETSLOWCURRENTINJSETLT_FUNC, MCC_SETWHOLECELLCOMPCAP_FUNC, MCC_SETWHOLECELLCOMPENABLE_FUNC, MCC_SETWHOLECELLCOMPRESIST_FUNC, PGC_SetAndActivateControl, V_CLAMP_MODE.
Referenced by IVS_ButtonProc_Setup.
variable IVS_runBaselineCheckQC()
Run the baseline QC check.
PSQ_PipetteInBath
References CHANNEL_CONTROL_WAVE, CHANNEL_TYPE_DAC, GetPanelControl, IVS_DEFAULT_DEVICE, IVS_DEFAULT_HEADSTAGE, PGC_SetAndActivateControl.
Referenced by IVS_ButtonProc_BaselineQC.
variable IVS_runInitAccessResisQC()
Run the initial access resistance check from the WSE.
This will check must be < 20MΩ or 15% of the R input. The EXTPBREAKN wave will also be run as a way of making sure the reading is recorded into the data set for post-experiment analysis
References CHANNEL_CONTROL_WAVE, CHANNEL_TYPE_DAC, GetIVSCCTemporaryWave, GetPanelControl, GetSetVariable, IVS_DEFAULT_DEVICE, IVS_DEFAULT_HEADSTAGE, IVS_finishInitAccessQCCheck, PGC_SetAndActivateControl, TP_CheckIfTestpulseIsRunning.
Referenced by IVS_ButtonProc_AccessResist.
variable IVS_finishInitAccessQCCheck(WMBackgroundStruct *s)
Complete the Baseline QC check in the background.
References GetIVSCCTemporaryWave, GetTPResults, IVS_DEFAULT_DEVICE, IVS_DEFAULT_HEADSTAGE, IVS_PublishQCState, PGC_SetAndActivateControl, TP_TestPulseHasCycled.
Referenced by IVS_runInitAccessResisQC.
variable IVS_RunGigOhmSealQC()
run the GigOhm seal QC check from the WSE
This will make sure the Steady State resistance must be > 1.0 GOhm. The EXTPCIIATT wave will also be run as a way of making sure the baseline is recorded into the data set for post-experiment analysis.
References CHANNEL_CONTROL_WAVE, CHANNEL_TYPE_DAC, GetPanelControl, IVS_DEFAULT_DEVICE, IVS_DEFAULT_HEADSTAGE, IVS_finishGigOhmSealQCCheck, PGC_SetAndActivateControl, TP_CheckIfTestpulseIsRunning.
Referenced by IVS_ButtonProc_GOhmSeal.
variable IVS_Load_StimSet(string stim_filename)
Loads a single stimulus for the user when using the ZMQ Proxy.
static variable IVS_PublishQCState(variable result, string description)
Push QC results onto ZeroMQ Publisher socket.
Filter: IVS_PUB_FILTER Payload: JSON-encoded string with three elements in the top-level object Example: embed:rst:leading-asterisk * .. code-block:: json * * { * "Description": "some text", * "Issuer": "My QC Function", * "Value": 123 * } * *
References FFI_Publish, IVS_PUB_FILTER.
Referenced by IVS_finishGigOhmSealQCCheck, IVS_finishInitAccessQCCheck.
variable IVS_finishGigOhmSealQCCheck(WMBackgroundStruct *s)
finish the Gig Ohm Seal QC in the background
References AssertOnAndClearRTError, ClearRTError, GetTPResults, IVS_DEFAULT_DEVICE, IVS_DEFAULT_HEADSTAGE, IVS_PublishQCState, PGC_SetAndActivateControl, TP_TestPulseHasCycled.
Referenced by IVS_RunGigOhmSealQC.
variable IVS_ExportAllData(string filePath)
References IVS_DEFAULT_NWBVERSION, NWB_ExportAllData.
string IVS_ReturnNWBFileLocation()
variable IVS_SaveExperiment(string filename)
References ASSERT, AssertOnAndClearRTError, ClearRTError.
variable IVS_runStimWave(string stimWaveName, variable scaleFactor)
Run a designated stim wave.
stimWaveName stimWaveName to be used scaleFactor scale factor to run the stim wave at
References CHANNEL_CONTROL_SCALE, CHANNEL_CONTROL_WAVE, CHANNEL_TYPE_DAC, GetPanelControl, IVS_DEFAULT_DEVICE, IVS_DEFAULT_HEADSTAGE, PGC_SetAndActivateControl.
variable IVS_ButtonProc_Setup(WMButtonAction *ba)
References IVS_ConfigureMCC.
variable IVS_ButtonProc_BaselineQC(WMButtonAction *ba)
References IVS_runBaselineCheckQC.
variable IVS_ButtonProc_AccessResist(WMButtonAction *ba)
References IVS_runInitAccessResisQC.
variable IVS_ButtonProc_GOhmSeal(WMButtonAction *ba)
References IVS_RunGigOhmSealQC.
variable IVS_CreatePanel()
void IVSCCControlPanel()
variable IVS_GetSetQCForSweep(string device, variable sweepNo)
Return the Set QC passed/failed state for the given sweep.
1 if passed, 0 if not (or not yet) and asserts out on all other errors.
References ASSERT, CreateAnaFuncLBNKey, DATA_ACQUISITION_MODE, EVENT_NAME_LIST_LBN, GENERIC_EVENT, GetLastSetting, GetLastSettingIndepSCI, GetLBNumericalValues, GetLBTextualValues, INVALID_ANALYSIS_FUNCTION, LABNOTEBOOK_LAYER_COUNT, MapAnaFuncToConstant, PSQ_FMT_LBN_SET_PASS, UNKNOWN_MODE.