MIES_Downsample.ipf
const string checkbox_equalize
Referenced by ApplyConstantRateChanges, ExpandRateToList, UpdateCheckBoxes.
const string checkbox_downsample
Referenced by UpdateCheckBoxes.
const string popup_targetrate
Referenced by GetTargetRate, UpdatePopupMenuTargetRate.
const string checkbox_interpolation
Referenced by GetPopupMenuRates.
const string popup_windowfunction
Referenced by ButtonDoIt, UpdatePopupMenuWindowFunction.
const string popup_decimationmethod
const string popup_deviceselection
Referenced by UpdatePanel.
const string checkbox_backupwaves
Referenced by ButtonDoIt.
const string valdisp_estimatedsize
Referenced by UpdateEstimatedSizeAfterwards.
const string valdisp_currentsize
Referenced by UpdateCurrentSize.
const string listbox_waves
const string button_doit
const string button_restorebackup
const string dataPath
Referenced by AB_LoadStimsetRAW, AB_LoadStimsetTemplateWaves, AB_LoadSweepFromIgor, DownsampleWindowHook, GetAllDevicesWithContent, GetDownsampleDataFolder.
const string panel
Referenced by AB_BrowserStartupSettings, AB_ButtonProc_LoadSweeps, AB_CheckPanelVersion, AB_OpenAnalysisBrowser, AverageWavesFromSameYAxisIfReq, BSP_ChannelSelectionWaveToGUI, CreateDownsamplePanel, DAP_CreateDAEphysPanel, DB_FindDataBrowser, DP_OpenDebugPanel, GetPopupMenuRates, MEN_OpenAboutDialog, SBE_ShowExportPanel, ScreenShotsForAnalysisBrowser, ScreenShotsForDAEphys, ScreenShotsForWaveBuilder, StoreCurrentPanelsResizeInfo.
static dfref GetDownsampleDataFolder()
References createDFWithAllParents, dataPath.
Referenced by GetDownsampleDataRefWave, GetDownsampleListWave, GetDownsampleRateWave.
static wave GetDownsampleDataRefWave()
References GetDownsampleDataFolder.
Referenced by ButtonDoIt, ButtonRestoreBackup, DownsampleWindowHook, UpdateCurrentSize, UpdateDataWaves, UpdateEstimatedSizeAfterwards.
static wave GetDownsampleRateWave()
References GetDownsampleDataFolder.
Referenced by ApplyConstantRateChanges, ButtonDoIt, DownsampleWindowHook, GetPopupMenuRates, UpdateDataWaves, UpdateEstimatedSizeAfterwards.
static wave GetDownsampleListWave()
References COLS, GetDownsampleDataFolder.
Referenced by ButtonDoIt, CreateDownsamplePanel, DownsampleWindowHook, UpdateDataWaves.
string GetPopupMenuDeviceListWithData()
Create a list of all devices with acquired data, honour yoking dependencies.
Todois not very accurate as we should store the yoking dependencies in a permanent way instead of hoping that ListOfFollowerITC1600s is accurate list of all devices with data in the format ITC18USB_Dev_1;ITC1600_Dev_1;ITC1600_Dev_0 (2,3);
References DEVICE_NUMBERS, DEVICE_TYPES_ITC, DeviceHasFollower, GetDevicePathAsString, GetDeviceTypePathAsString, HW_ITC_BuildDeviceString, isEmpty, ParseDeviceString.
static variable ParsePopupItem(string popStr, string *deviceType, string *deviceNumber, string *followerList)
Parse the given popup item string created by GetPopupMenuDeviceListWithData() and return the device name, type and possible follower list.
References ParseDeviceString.
Referenced by UpdatePanel.
static variable AppendEntries(WaveText list, WaveRefWave dataRef, wave rate, variable startIndex, string deviceType, string deviceNumber)
Searches for sweep waves from all devices.
list ListBox wave, see GetDownsampleListWave() for the format dataRef wave with wave references to all data waves rate wave with the sampling rates in kHz of all data waves startIndex first unused index into the passed waves deviceType device type deviceNumber device number index of the last valid entry into the passed waves
References ConvertSamplingIntervalToRate, DATA_SWEEP_REGEXP, EnsureLargeEnoughWave, GetConfigWave, GetDeviceDataPath, GetListOfObjects, GetSamplingInterval, HW_ITC_BuildDeviceString.
Referenced by UpdateDataWaves.
static variable UpdateDataWaves(string deviceType, string deviceNumber, string followerList)
Updates all waves holding acquired data info.
References AppendEntries, GetDownsampleDataRefWave, GetDownsampleListWave, GetDownsampleRateWave.
Referenced by UpdatePanel.
static variable UpdateCurrentSize(string win)
References ConvertFromBytesToMiB, GetDownsampleDataRefWave, GetWaveSize, ROWS, SetValDisplay, valdisp_currentsize.
Referenced by UpdatePanel.
static variable GetTargetRate(string win)
References GetPopupMenuString, NONE, popup_targetrate.
Referenced by ButtonDoIt, UpdateEstimatedSizeAfterwards.
static variable UpdateEstimatedSizeAfterwards(string win)
References ConvertFromBytesToMiB, GetDownsampleDataRefWave, GetDownsampleRateWave, GetTargetRate, GetWaveSize, ROWS, SetValDisplay, valdisp_estimatedsize.
Referenced by CheckBoxInterpolation, PopupMenuTargetRate, UpdateCheckBoxes, UpdatePanel.
static variable ApplyConstantRateChanges(string win)
Disable the equalize checkbox if all data waves have the same rate.
References checkbox_equalize, CHECKBOX_UNSELECTED, DisableControl, EnableControl, GetDownsampleRateWave, UpdateCheckBoxes, WaveMinAndMaxWrapper.
Referenced by UpdatePanel.
static string ExpandRateToList(string win, variable var, variable constantRates=defaultValue)
Returns a list of values 1/k*var with k = {1..10} or k = {2..10} if constantRates == 1.
win panel name var variable to expand constantRates boolean switch, defaults to false
References checkbox_equalize, GetCheckBoxState.
Referenced by GetPopupMenuRates.
string GetPopupMenuRates()
Returns a list of all possible equalize/downsampling rates.
References CalculateLCMOfWave, checkbox_interpolation, ExpandRateToList, GetCheckBoxState, GetDownsampleRateWave, GetUniqueEntries, NONE, panel, ROWS, WaveMinAndMaxWrapper.
Referenced by UpdatePopupMenuTargetRate.
static variable GetDecimationMethod(string win)
References GetPopupMenuIndex.
Referenced by ButtonDoIt, UpdatePopupMenuWindowFunction.
static variable UpdateCheckBoxes(string win, string control, variable state)
References ASSERT, checkbox_downsample, checkbox_equalize, SetCheckBoxState, UpdateEstimatedSizeAfterwards, UpdatePopupMenuTargetRate.
Referenced by ApplyConstantRateChanges, CheckBoxEqualizeDown.
static variable UpdatePopupMenuWindowFunction(string win, variable decimationMethod=defaultValue)
References DECIMATION_BY_SMOOTHING, DisableControl, EnableControl, GetDecimationMethod, popup_windowfunction.
Referenced by CreateDownsamplePanel, PopupMenuDecimationMethod.
variable CreateDownsamplePanel()
References ASSERT, GetDownsampleListWave, panel, PS_InitCoordinates, UpdatePanel, UpdatePopupMenuWindowFunction.
variable DownsampleWindowHook(WMWinHookStruct *s)
References dataPath, EVENT_KILL_WINDOW_HOOK, GetDownsampleDataRefWave, GetDownsampleListWave, GetDownsampleRateWave, KillOrMoveToTrash, PS_StoreWindowCoordinate, RecursiveRemoveEmptyDataFolder.
variable CheckBoxInterpolation(WMCheckboxAction *cba)
References UpdateEstimatedSizeAfterwards.
variable PopupMenuTargetRate(WMPopupAction *pa)
References UpdateEstimatedSizeAfterwards.
variable ButtonRestoreBackup(WMButtonAction *ba)
References ControlWindowToFront, GetBackupWave, GetConfigWave, GetDownsampleDataRefWave, ReplaceWaveWithBackup, ROWS, UpdatePanel.
variable ButtonDoIt(WMButtonAction *ba)
References ASSERT, checkbox_backupwaves, ConvertRateToSamplingInterval, CreateBackupWave, DECIMATION_BY_SMOOTHING, GetCheckBoxState, GetConfigWave, GetDecimationMethod, GetDownsampleDataRefWave, GetDownsampleListWave, GetDownsampleRateWave, GetPopupMenuString, GetTargetRate, popup_windowfunction, ROWS, UpdatePanel, UpdateSweepConfig.
static variable UpdatePopupMenuTargetRate(string win)
References GetPopupMenuIndex, GetPopupMenuRates, popup_targetrate, SetPopupMenuIndex.
Referenced by UpdateCheckBoxes, UpdatePanel.
static variable UpdatePanel(string win, string deviceSelectionString=defaultValue)
References ApplyConstantRateChanges, GetPopupMenuString, ParsePopupItem, popup_deviceselection, UpdateCurrentSize, UpdateDataWaves, UpdateEstimatedSizeAfterwards, UpdatePopupMenuTargetRate.
Referenced by ButtonDoIt, ButtonRestoreBackup, CreateDownsamplePanel, PopupMenuDeviceSelection.
variable PopupMenuDeviceSelection(WMPopupAction *pa)
References UpdatePanel.
variable PopupMenuDecimationMethod(WMPopupAction *pa)
References UpdatePopupMenuWindowFunction.
variable CheckBoxEqualizeDown(WMCheckboxAction *cba)
References UpdateCheckBoxes.