MIES_AnalysisFunctions_Dashboard.ipf
variable AD_UpdateAllDatabrowser()
Update the dashboards of all databrowsers.
References AD_Update, BSP_GetBrowserType, IsEmpty.
Referenced by MSQ_DAScale, MSQ_FastRheoEst, PSQ_Chirp, PSQ_DAScale, PSQ_PipetteInBath, PSQ_Ramp, PSQ_Rheobase, PSQ_SquarePulse, SC_SpikeControl.
static variable AD_GetColorForResultMessage(string result)
References DASHBOARD_PASSING_MESSAGE, NOT_AVAILABLE.
Referenced by AD_Update.
variable AD_Update(string win)
Update the dashboards of the given sweepbrowser/databrowser.
References AD_FillWaves, AD_GetColorForResultMessage, BSP_GetFolder, BSP_GetPanel, BSP_IsActive, DEBUG_TIMER_START, DEBUGPRINT_ELAPSED, GetAnaFuncDashboardColorWave, GetAnaFuncDashboardHelpWave, GetAnaFuncDashboardInfoWave, GetAnaFuncDashboardListWave, MIES_BSP_DS, MIES_BSP_PANEL_FOLDER, NOTE_INDEX, SetNumberInWaveNote.
Referenced by AB_ButtonProc_LoadSweeps, AD_CheckProc_Toggle, AD_UpdateAllDatabrowser, DB_UpdateLastSweepControls.
static string AD_GetResultMessage(variable anaFuncType, variable passed, wave numericalValues, WaveText textualValues, variable sweepNo, variable headstage, variable ongoingDAQ)
References AD_GetChirpFailMsg, AD_GetFastRheoEstFailMsg, AD_GetPipetteInBathFailMsg, AD_GetRampFailMsg, AD_GetRheobaseFailMsg, AD_GetSpikeControlFailMsg, AD_GetSquarePulseFailMsg, ASSERT, BUG, GetLastSettingIndepSCI, INVALID_ANALYSIS_FUNCTION, IsNaN, MSQ_DA_SCALE, MSQ_FAST_RHEO_EST, NOT_AVAILABLE, PSQ_CHIRP, PSQ_DA_SCALE, PSQ_PIPETTE_BATH, PSQ_RAMP, PSQ_RHEOBASE, PSQ_SQUARE_PULSE, SC_SPIKE_CONTROL, UNKNOWN_MODE.
Referenced by AD_FillWaves.
static variable AD_FillWaves(string win, WaveText list, WaveText info)
Get result list of analysis function runs.
References AD_FormatListKey, AD_GetResultMessage, AFH_GetSweepsFromSameSCI, AS_INACTIVE, ASSERT, BSP_GetDevice, BSP_GetLogbookWave, BSP_IsDataBrowser, CreateAnaFuncLBNKey, DATA_ACQUISITION_MODE, EnsureLargeEnoughWave, EVENT_NAME_LIST_LBN, GENERIC_EVENT, GetAcquisitionState, GetLastSetting, GetLastSettingEachSCI, GetLastSettingIndep, GetLastSettingIndepEachSCI, GetLastSettingIndepSCI, GetNumberFromWaveNote, GetPlainSweepList, INVALID_ANALYSIS_FUNCTION, IsNaN, LABNOTEBOOK_LAYER_COUNT, LBN_NUMERICAL_VALUES, LBN_TEXTUAL_VALUES, LBT_LABNOTEBOOK, MapAnaFuncToConstant, MSQ_DA_SCALE, MSQ_FAST_RHEO_EST, NOT_AVAILABLE, NOTE_INDEX, NUM_HEADSTAGES, NumericWaveToList, PSQ_CHIRP, PSQ_DA_SCALE, PSQ_FMT_LBN_SET_PASS, PSQ_FMT_LBN_SPIKE_DETECT, PSQ_FMT_LBN_SWEEP_PASS, PSQ_PIPETTE_BATH, PSQ_RAMP, PSQ_RHEOBASE, PSQ_SQUARE_PULSE, ROVar, ROWS, SC_SPIKE_CONTROL, SetNumberInWaveNote, STIM_WAVE_NAME_KEY, STIMSET_ACQ_CYCLE_ID_KEY, UNKNOWN_MODE, ZapNaNs.
Referenced by AD_Update.
static string AD_FormatListKey(variable stimsetCycleID, variable headstage)
Referenced by AD_FillWaves.
static variable AD_LabnotebookEntryExistsAndIsTrue(WaveOrNull data)
References ZapNaNs.
Referenced by AD_GetFastRheoEstFailMsg, AD_GetSpikeControlFailMsg.
static string AD_GetSquarePulseFailMsg(wave numericalValues, variable sweepNo, variable headstage)
Return an appropriate error message for why PSQ_SQUARE_PULSE failed.
numericalValues Numerical labnotebook sweepNo Sweep number headstage Headstage
References ASSERT, BUG, CreateAnaFuncLBNKey, GetLastSettingIndepEachSCI, GetLastSettingIndepSCI, GetLastSettingSCI, IsFinite, PSQ_FMT_LBN_SPIKE_DASCALE_ZERO, PSQ_FMT_LBN_SPIKE_DETECT, PSQ_FMT_LBN_STEPSIZE, PSQ_SP_INIT_AMP_p10, PSQ_SQUARE_PULSE, ROWS, UNKNOWN_MODE, ZapNaNs.
Referenced by AD_GetResultMessage.
static string AD_GetDAScaleFailMsg(wave numericalValues, WaveText textualValues, variable sweepNo, variable headstage)
Return an appropriate error message for why PSQ_DA_SCALE failed.
numericalValues Numerical labnotebook textualValues Textual labnotebook sweepNo Sweep number headstage Headstage
References AD_GetPerSweepFailMessage, AFH_GetAnalysisParamNumerical, AFH_GetAnalysisParamWave, ASSERT, BUG, CreateAnaFuncLBNKey, DATA_ACQUISITION_MODE, GetLastSettingEachSCI, GetLastSettingIndepEachSCI, GetLastSettingTextSCI, IsEmpty, NumericWaveToList, PSQ_DA_SCALE, PSQ_FMT_LBN_DA_fI_SLOPE, PSQ_FMT_LBN_DA_fI_SLOPE_REACHED, PSQ_NumPassesInSet, ROWS, UNKNOWN_MODE.
static string AD_GetRampFailMsg(wave numericalValues, WaveText textualValues, variable sweepNo, variable headstage)
Return an appropriate error message for why PSQ_RAMP failed.
numericalValues Numerical labnotebook textualValues Textual labnotebook sweepNo Sweep number headstage Headstage
References AD_GetPerSweepFailMessage, PSQ_RA_NUM_SWEEPS_PASS, PSQ_RAMP.
Referenced by AD_GetResultMessage.
static string AD_GetRheobaseFailMsg(wave numericalValues, WaveText textualValues, variable sweepNo, variable headstage)
Return an appropriate error message for why PSQ_RHEOBASE failed.
numericalValues Numerical labnotebook textualValues Textual labnotebook sweepNo Sweep number headstage Headstage
References AD_GetPerSweepFailMessage, CreateAnaFuncLBNKey, GetLastSettingEachSCI, NumericWaveToList, PSQ_FMT_LBN_SPIKE_DETECT, PSQ_RHEOBASE, UNKNOWN_MODE.
Referenced by AD_GetResultMessage.
static string AD_GetPipetteInBathFailMsg(wave numericalValues, WaveText textualValues, variable sweepNo, variable headstage)
References AD_GetPerSweepFailMessage, PSQ_PB_NUM_SWEEPS_PASS, PSQ_PIPETTE_BATH.
Referenced by AD_GetResultMessage.
static string AD_GetFastRheoEstFailMsg(wave numericalValues, variable sweepNo, variable headstage)
References AD_LabnotebookEntryExistsAndIsTrue, CreateAnaFuncLBNKey, GetLastSettingEachSCI, MSQ_FAST_RHEO_EST, MSQ_FMT_LBN_DASCALE_EXC, UNKNOWN_MODE.
Referenced by AD_GetResultMessage.
static string AD_GetSpikeControlFailMsg(wave numericalValues, wave textualValues, variable sweepNo, variable headstage)
References AD_LabnotebookEntryExistsAndIsTrue, CreateAnaFuncLBNKey, GetLastSettingEachSCI, MSQ_FMT_LBN_RERUN_TRIAL_EXC, SC_SPIKE_CONTROL, UNKNOWN_MODE.
Referenced by AD_GetResultMessage.
static string AD_GetChirpFailMsg(wave numericalValues, WaveText textualValues, variable sweepNo, variable headstage)
Return an appropriate error message for why PSQ_CHIRP failed.
numericalValues Numerical labnotebook textualValues Textual labnotebook sweepNo Sweep number headstage Headstage
References AD_GetPerSweepFailMessage, ASSERT, BUG, CreateAnaFuncLBNKey, DATA_ACQUISITION_MODE, GetLastSettingEachSCI, GetLastSettingIndepEachSCI, IsEmpty, PSQ_CHIRP, PSQ_CR_NUM_SWEEPS_PASS, PSQ_CR_SetHasPassed, PSQ_FMT_LBN_SWEEP_PASS, ROWS, STIMSET_SCALE_FACTOR_KEY, ToPassFail, UNKNOWN_MODE.
Referenced by AD_GetResultMessage.
static string AD_GetBaselineFailMsg(variable anaFuncType, wave numericalValues, variable sweepNo, variable headstage)
Return an appropriate error message if the baseline QC failed for the given sweep, or an empty string otherwise.
anaFuncType One of PatchSeqAnalysisFunctionTypes numericalValues Numerical labnotebook sweepNo Sweep number headstage Headstage
References AD_GetBaselineChunkFailMsg, BUG, CreateAnaFuncLBNKey, GetLastSetting, GetLastSettingIndep, IsEmpty, IsNaN, PSQ_CHIRP, PSQ_DA_SCALE, PSQ_FMT_LBN_BL_QC_PASS, PSQ_FMT_LBN_CHUNK_PASS, PSQ_FMT_LBN_LEAKCUR_PASS, PSQ_FMT_LBN_RMS_LONG_PASS, PSQ_FMT_LBN_RMS_SHORT_PASS, PSQ_FMT_LBN_TARGETV_PASS, PSQ_PIPETTE_BATH, PSQ_RAMP, PSQ_RHEOBASE, UNKNOWN_MODE.
Referenced by AD_GetPerSweepFailMessage.
static string AD_GetBaselineChunkFailMsg(variable anaFuncType, wave numericalValues, variable sweepNo, variable headstage, variable chunk, string subkey, string testname)
References ASSERT, CreateAnaFuncLBNKey, GetLastSetting, IsFinite, ToPassFail, UNKNOWN_MODE.
Referenced by AD_GetBaselineFailMsg.
static string AD_GetPerSweepFailMessage(variable anaFuncType, wave numericalValues, WaveText textualValues, variable refSweepNo, variable headstage, variable numRequiredPasses=defaultValue)
Gather per sweep failure information for some analysis function types.
anaFuncType analysis function type numericalValues numerical labnotebook textualValues textual labnotebook refSweepNo reference sweep number headstage headstage numRequiredPasses [optional, defaults to off] allows to determine the set failure state by not having reached enough passing sets AD_GetResultMessage()
References AD_GetBaselineFailMsg, AFH_GetSweepsFromSameSCI, ASSERT, BUG, CreateAnaFuncLBNKey, GetLastSetting, GetLastSettingIndep, GetLastSettingIndepEachSCI, GetLastSettingIndepSCI, INDEP_HEADSTAGE, IsEmpty, IsFinite, PSQ_CHIRP, PSQ_CR_BoundsActionToString, PSQ_CR_PASS, PSQ_DA_SCALE, PSQ_FMT_LBN_CR_BOUNDS_ACTION, PSQ_FMT_LBN_CR_SPIKE_CHECK, PSQ_FMT_LBN_CR_SPIKE_PASS, PSQ_FMT_LBN_PB_RESISTANCE_PASS, PSQ_FMT_LBN_RB_DASCALE_EXC, PSQ_FMT_LBN_RB_LIMITED_RES, PSQ_FMT_LBN_SAMPLING_PASS, PSQ_FMT_LBN_SWEEP_PASS, PSQ_NumPassesInSet, PSQ_PIPETTE_BATH, PSQ_RAMP, PSQ_RHEOBASE, ROWS, UNKNOWN_MODE.
Referenced by AD_GetChirpFailMsg, AD_GetDAScaleFailMsg, AD_GetPipetteInBathFailMsg, AD_GetRampFailMsg, AD_GetRheobaseFailMsg.
static variable AD_SelectResult(string win, variable index=defaultValue)
Show the sweeps of the given index entry into the listbox.
References BSP_GetFolder, BSP_GetPanel, BSP_IsDataBrowser, ControlWindowToFront, DB_UpdateToLastSweep, FindIndizes, GetAnaFuncDashboardInfoWave, GetCheckBoxState, GetListBoxSelRow, GetOverlaySweepsListWave, GetPlainSweepList, GetSetIntersection, GetUniqueEntries, IsEmpty, IsFinite, IsNull, ListToNumericWave, MIES_BSP_PANEL_FOLDER, OVS_ChangeSweepSelectionState, PGC_SetAndActivateControl, ROWS.
Referenced by AD_CheckProc_FailedSweeps, AD_CheckProc_PassedSweeps, AD_ListBoxProc.
variable AD_PlotBounds(string browser, variable sweepNo)
Plot the inner/outer bounds for PSQ_CHIRP
Requires that the sweep is displayed.
References AFH_GetAnalysisParamNumerical, ASSERT, BSP_GetFolder, BSP_GetLogbookWave, CreateAnaFuncLBNKey, DATA_ACQUISITION_MODE, FindIndizes, GetLastSetting, GetMainWindow, LBN_NUMERICAL_VALUES, LBN_TEXTUAL_VALUES, LBT_LABNOTEBOOK, MIES_BSP_PANEL_FOLDER, PSQ_CHIRP, PSQ_FMT_LBN_TARGETV, ROWS, TUD_GetUserDataAsWave, UNKNOWN_MODE.
variable AD_ListBoxProc(WMListboxAction *lba)
References AD_SelectResult.
variable AD_CheckProc_PassedSweeps(WMCheckboxAction *cba)
References AD_SelectResult.
variable AD_CheckProc_FailedSweeps(WMCheckboxAction *cba)
References AD_SelectResult.
variable AD_CheckProc_Toggle(WMCheckboxAction *cba)
References AD_Update, DisableControls, EnableControls.