MIES_ExperimentDocumentation.ipf
variable ED_AddEntriesToLabnotebook(wave vals, WaveText keys, variable sweepNo, string device, variable entrySourceType)
Add numerical/textual entries to the labnotebook.
ED_createTextNotes, ED_createWaveNote
References ED_CheckValuesAndKeys, ED_createTextNotes, ED_createWaveNotes, IsTextWave, LBT_LABNOTEBOOK.
Referenced by DAP_DocumentStopReason, DAP_SweepRollback, ED_AddEntryToLabnotebook, ED_createAsyncWaveNoteTags, ED_createWaveNoteTags, ED_TPDocumentation, ED_TPSettingsDocumentation, ED_WriteUserCommentToLabNB, RA_DocumentSweepSkipping.
variable ED_AddEntriesToResults(wave vals, WaveText keys, variable entrySourceType)
Add numerical/textual entries to results.
References ED_CheckValuesAndKeys, ED_createTextNotes, ED_createWaveNotes, IsTextWave, LBT_RESULTS.
static variable ED_CheckValuesAndKeys(wave vals, wave keys)
References ASSERT, COLS, LABNOTEBOOK_LAYER_COUNT, LAYERS, ROWS.
Referenced by ED_AddEntriesToLabnotebook, ED_AddEntriesToResults.
static variable ED_createTextNotes(WaveText incomingTextualValues, WaveText incomingTextualKeys, variable sweepNo, variable entrySourceType, variable logbookType, string device=defaultValue)
Add textual entries to the logbook.
The text documentation wave will use layers to report the different headstages. The incoming value wave can have zero to nine (NUM_HEADSTAGES + 1) layers. The first eight layers are for headstage dependent data, the last layer for headstage independent data. incomingTextualValues incoming Text Documentation Wave sent by the each reporting subsystem incomingTextualKeys incoming Text Documentation key wave that is used to reference the incoming settings wave sweepNo sweep number device [optional for logbookType LBT_RESULTS only] device entrySourceType type of reporting subsystem, one of DataAcqModes logbookType type of the logbook, one of LogbookTypes
References AS_INACTIVE, ASSERT, COLS, DateTimeInUTC, ED_FindIndizesAndRedimension, EnsureLargeEnoughWave, ExtractLogbookSliceSweep, ExtractLogbookSliceTimeStamp, GetAcquisitionState, GetLogbookWaves, LAYERS, LBN_TEXTUAL_KEYS, LBN_TEXTUAL_VALUES, LBT_RESULTS, NormalizeToEOL, NOTE_INDEX, num2strHighPrec, ROVar, ROWS, SetNumberInWaveNote.
Referenced by ED_AddEntriesToLabnotebook, ED_AddEntriesToResults.
static variable ED_ParseHeadstageContigencyMode(string str)
References HCM_DEPEND, HCM_EMPTY, HCM_INDEP.
Referenced by ED_FindIndizesAndRedimension.
static variable ED_GetHeadstageContingency(wave values)
Return the headstage contigency mode for values.
References HCM_DEPEND, HCM_EMPTY, HCM_INDEP, INDEP_HEADSTAGE, IsNaN, IsTextWave, LABNOTEBOOK_LAYER_COUNT, NUM_HEADSTAGES.
Referenced by ED_AddEntryToLabnotebook, ED_FindIndizesAndRedimension.
static variable ED_createWaveNotes(wave incomingNumericalValues, WaveText incomingNumericalKeys, variable sweepNo, variable entrySourceType, variable logbookType, string device=defaultValue)
Add numerical entries to the labnotebook.
The history wave will use layers to report the different headstages. The incoming value wave can have zero to nine LABNOTEBOOK_LAYER_COUNT layers. The first eight layers are for headstage dependent data, the last layer for headstage independent data. incomingNumericalValues settingsWave sent by the each reporting subsystem incomingNumericalKeys key wave that is used to reference the incoming settings wave sweepNo sweep number device [optional for logbooktype LBT_RESULTS only] device entrySourceType type of reporting subsystem, one of DataAcqModes logbookType one of LogbookTypes
References AS_INACTIVE, ASSERT, COLS, DateTimeInUTC, ED_FindIndizesAndRedimension, EnsureLargeEnoughWave, ExtractLogbookSliceTimeStamp, GetAcquisitionState, GetLogbookWaves, LAYERS, LBN_NUMERICAL_KEYS, LBN_NUMERICAL_VALUES, LBT_RESULTS, NOTE_INDEX, ROVar, ROWS, SetNumberInWaveNote.
Referenced by ED_AddEntriesToLabnotebook, ED_AddEntriesToResults.
variable ED_AddEntryToLabnotebook(string device, string key, wave values, string unit=defaultValue, variable tolerance=defaultValue, variable overrideSweepNo=defaultValue)
Add custom entries to the numerical/textual labnotebook for the very last sweep acquired.
The entries are prefixed with USER_ to distinguish them from stock MIES entries. The index of the entry in values determines the headstage to which the setting applies. You can not set both headstage dependent and independent values at the same time as this does not make sense. Sample invocation: embed:rst:leading-asterisk * .. code-block:: igorpro * * Make/D/FREE/N=(LABNOTEBOOK_LAYER_COUNT) values = NaN * values[0] = 4711 // setting of the first headstage * ED_AddEntryToLabnotebook(device, "SomeSetting", values) * The later on the labnotebook can be queried with: embed:rst:leading-asterisk * .. code-block:: igorpro * * WAVE/Z settings = GetLastSetting(values, NaN, LABNOTEBOOK_USER_PREFIX + key, UNKNOWN_MODE) * device device key name under which to store the entry. values entry to add, wave can be numeric (floating point) or text, must have LABNOTEBOOK_LAYER_COUNT rows. It can be all NaN or empty (text), this is useful if you want to make the key known without adding an entry. unit [optional, defaults to ""] physical unit of the entry tolerance [optional, defaults to LABNOTEBOOK_NO_TOLERANCE] tolerance of the entry, used for judging if a change is "relevant" and should then be written to the sweep wave overrideSweepNo [optional, defaults to last acquired sweep] Adds metadata to the given sweep number. Mostly useful for adding labnotebook entries during MID_SWEEP_EVENT for analysis functions.
References AFH_GetLastSweepAcquired, ASSERT, COLS, ED_AddEntriesToLabnotebook, ED_GetHeadstageContingency, HCM_DEPEND, HCM_INDEP, IsEmpty, IsFinite, IsFloatingPointWave, IsTextWave, LABNOTEBOOK_LAYER_COUNT, LABNOTEBOOK_NO_TOLERANCE, LABNOTEBOOK_USER_PREFIX, MAX_OBJECT_NAME_LENGTH_IN_BYTES, ROWS, UNKNOWN_MODE.
Referenced by AdjustDAScale, FitResistance, MSQ_DAScale, MSQ_FastRheoEst, MSQ_GetPulseDurations, PSQ_CheckSamplingFrequencyAndStoreInLabnotebook, PSQ_Chirp, PSQ_CR_DetermineBoundsAction, PSQ_CR_GetCycles, PSQ_DAScale, PSQ_EvaluateBaselinePassed, PSQ_EvaluateBaselineProperties, PSQ_GetPulseDurations, PSQ_PipetteInBath, PSQ_Ramp, PSQ_Rheobase, PSQ_SquarePulse, PSQ_StoreRMSThresholdsInLabnotebook, PSQ_StoreStepSizeInLBN, ReachTargetVoltage, SC_DetermineQCState, SC_GetTrials, SC_ProcessPulses, SC_SpikeControl, SetAnalysisFunctionVersion.
static variable ED_WriteChangedValuesToNote(string device, variable sweepNo)
Record changed labnotebook entries compared to the last sweep to the sweep wave note.
Honours tolerances defined in the keywave and LABNOTEBOOK_BINARY_UNIT values
References ASSERT, COLS, GetLastSetting, GetLBNumericalKeys, GetLBNumericalValues, GetSweepWave, INITIAL_KEY_WAVE_COL_COUNT, isEmpty, IsFinite, LABNOTEBOOK_NO_TOLERANCE, NUM_HEADSTAGES, ROWS, str2numSafe, UNKNOWN_MODE.
Referenced by ED_createWaveNoteTags.
static variable ED_WriteChangedValuesToNoteText(string device, variable sweepNo)
Record changed labnotebook entries compared to the last sweep to the sweep wave note.
Textual version. Honours tolerances defined in the keywave and LABNOTEBOOK_BINARY_UNIT values
References ASSERT, COLS, GetLastSetting, GetLBTextualKeys, GetLBTextualValues, GetSweepWave, INITIAL_KEY_WAVE_COL_COUNT, isEmpty, NUM_HEADSTAGES, ROWS, UNKNOWN_MODE.
Referenced by ED_createWaveNoteTags.
static std::tuple< WAVE, variable > ED_FindIndizesAndRedimension(WaveText incomingKey, wave incomingValues, WaveText key, wave values, variable logbookType)
Returns the column indizes of each parameter in incomingKey into the key wave.
Redimensions key and values waves. Prefills key with incomingKey data if necessary. Ensures that key and values have a matching column size at return. incomingKey text wave with the keys to add incomingValues wave with the values to add key key wave of the labnotebook (Rows: 1/3/6, Columns: Same as values, Layers: 1) values values/data wave of the labnotebook logbookType type of the logbook, one of LogbookTypes colIndizes column indizes of the entries from incomingKey rowIndex returns the row index into values at which the new values should be written
References ASSERT, BUG, COLS, ED_GetHeadstageContingency, ED_ParseHeadstageContigencyMode, EnsureLargeEnoughWave, GetLBNumericalDescription, GetNumberFromWaveNote, HCM_EMPTY, HCM_INDEP, IsFinite, IsNumericWave, IsValidLiberalObjectName, LABNOTEBOOK_USER_PREFIX, LBN_SetDimensionLabels, LBT_LABNOTEBOOK, NOTE_INDEX, ROWS.
Referenced by ED_createTextNotes, ED_createWaveNotes.
variable ED_MarkSweepStart(string device)
Remember the "exact" start of the sweep.
Should be called immediately after HW_StartAcq().
References GetISO8601TimeStamp, GetSweepSettingsTextWave, INDEP_HEADSTAGE.
Referenced by AS_HandlePossibleTransition.
variable ED_createWaveNoteTags(string device, variable sweepCount)
Add sweep specific information to the labnotebook.
References AI_FillAndSendAmpliferSettings, CheckIfClose, DAG_GetNumericalValue, DATA_ACQUISITION_MODE, ED_AddEntriesToLabnotebook, ED_createAsyncWaveNoteTags, ED_TPSettingsDocumentation, ED_WriteChangedValuesToNote, ED_WriteChangedValuesToNoteText, GetSweepSettingsKeyWave, GetSweepSettingsTextKeyWave, GetSweepSettingsTextWave, GetSweepSettingsWave, INDEP_HEADSTAGE, LABNOTEBOOK_LAYER_COUNT.
Referenced by SWS_SaveAcquiredData.
variable ED_WriteUserCommentToLabNB(string device, string comment, variable sweepNo)
Write the user comment from the DA_Ephys panel to the labnotebook.
References ED_AddEntriesToLabnotebook, INDEP_HEADSTAGE, LABNOTEBOOK_LAYER_COUNT, LABNOTEBOOK_NO_TOLERANCE, UNKNOWN_MODE.
Referenced by DAP_AddUserComment.
static variable ED_createAsyncWaveNoteTags(string device, variable sweepCount)
This function is used to create wave notes for the informations found in the Asynchronous tab in the DA_Ephys panel.
References ASD_CheckAsynAlarmState, ASD_ReadChannel, CHANNEL_CONTROL_ALARM_MAX, CHANNEL_CONTROL_ALARM_MIN, CHANNEL_CONTROL_CHECK, CHANNEL_CONTROL_GAIN, CHANNEL_CONTROL_TITLE, CHANNEL_CONTROL_UNIT, CHANNEL_TYPE_ALARM, CHANNEL_TYPE_ASYNC, CHECKBOX_SELECTED, ControlWindowToFront, DAG_GetChannelState, DAG_GetNumericalValue, DAG_GetTextualValue, DATA_ACQUISITION_MODE, ED_AddEntriesToLabnotebook, GetAsyncSettingsKeyWave, GetAsyncSettingsTextKeyWave, GetAsyncSettingsTextWave, GetAsyncSettingsWave, GetSpecialControlLabel, INDEP_HEADSTAGE, IsConstant, NUM_ASYNC_CHANNELS, RA_SkipSweeps.
Referenced by ED_createWaveNoteTags.
variable ED_TPDocumentation(string device)
Stores test pulse related data in the labnotebook.
References AFH_GetLastSweepAcquired, AI_SelectMultiClamp, AI_SendToAmp, AMPLIFIER_CONNECTION_SUCCESS, CHANNEL_TYPE_HEADSTAGE, CLAMPMODE_ENTRY_KEY, DAG_GetChannelState, ED_AddEntriesToLabnotebook, ED_TPSettingsDocumentation, GetHSProperties, GetTPResults, I_CLAMP_MODE, INDEP_HEADSTAGE, LABNOTEBOOK_BINARY_UNIT, LABNOTEBOOK_LAYER_COUNT, LABNOTEBOOK_NO_TOLERANCE, MCC_GETFASTCOMPCAP_FUNC, MCC_GETFASTCOMPTAU_FUNC, MCC_GETSLOWCOMPCAP_FUNC, MCC_GETSLOWCOMPTAU_FUNC, NUM_HEADSTAGES, TEST_PULSE_MODE, TP_UpdateTPLBNSettings, V_CLAMP_MODE.
Referenced by TP_Teardown.
static variable ED_TPSettingsDocumentation(string device, variable sweepNo, variable entrySourceType)
Document the settings of the Testpulse.
The source type entry is not fixed. We want to document the testpulse settings during ITI and the testpulse settings for plain test pulses. device device sweepNo sweep number entrySourceType type of reporting subsystem, one of DataAcqModes
References ED_AddEntriesToLabnotebook, GetTPSettingsLabnotebook, GetTPSettingsLabnotebookKeyWave.
Referenced by ED_createWaveNoteTags, ED_TPDocumentation.