MIES_Include.ipf
TOO_OLD_IGOR
void OpenPanelWithDocumentationLink()
variable ButtonProc_OpenMiesDocuUpdateNightly(WMButtonAction *ba)
static string GetDownloadLink()
Referenced by ButtonProc_DownloadNightly.
static string GetFileNameFromURL(string url)
Referenced by ButtonProc_DownloadNightly.
static string GetDestinationIgorPath()
Referenced by ButtonProc_DownloadNightly.
variable ButtonProc_DownloadNightly(WMButtonAction *ba)
References GetDestinationIgorPath, GetDownloadLink, GetFileNameFromURL.
static variable AfterCompiledHook()