MIES_CheckInstallation.ipf
const string CHI_NIDAQ_XOP_64_HASH
Referenced by CHI_CheckInstallation.
const string CHI_NIDAQ_XOP_HASH
const string CHI_JSON_XOP_VERSION
Referenced by CHI_CheckJSONXOPVersion.
static variable CHI_InitInstallationState(CHI_InstallationState *state)
References CHI_InstallationState::numErrors, CHI_InstallationState::numTries.
Referenced by CHI_CheckInstallation.
static variable CHI_CheckJSONXOPVersion(CHI_InstallationState *state)
References CHI_JSON_XOP_VERSION, CHI_InstallationState::numErrors.
Referenced by CHI_CheckInstallation.
static variable CHI_CheckXOP(string *list, string *item, string *name, CHI_InstallationState *state, string expectedHash=defaultValue)
Search list for matches of item and print the results.
References CalcHashForFile, CheckIfPathsRefIdenticalFiles, GetFileVersion, CHI_InstallationState::numErrors, CHI_InstallationState::numTries.
Referenced by CHI_CheckInstallation.
variable CHI_CheckInstallation()
Check the installation and print the results to the history.
Currently checks that all expected/optional XOPs are installed. number of errors
References CHI_CheckJSONXOPVersion, CHI_CheckXOP, CHI_InitInstallationState, CHI_NIDAQ_XOP_64_HASH, ControlWindowToFront, GetAllFilesRecursivelyFromPath, GetArchitectureBits, GetASLREnabledState, GetIgorExtensionFolderName, GetUniqueEntries, GetUniqueSymbolicPath, isEmpty, IsWindows10, TextWaveToList, ToTrueFalse, UNKNOWN_MIES_VERSION.
Referenced by MEN_CreateIssueOnGithub.