MIES_Structures.ipf
variable InitPulseAverageSettings(PulseAverageSettings *pa)
References PulseAverageSettings::autoTimeAlignment, PulseAverageSettings::dfr, PulseAverageSettings::drawXZeroLine, PulseAverageSettings::enabled, PulseAverageSettings::endingPulse, PulseAverageSettings::failedPulsesLevel, PulseAverageSettings::fixedPulseLength, PulseAverageSettings::hideFailedPulses, PulseAverageSettings::imageColorScale, PulseAverageSettings::multipleGraphs, PulseAverageSettings::overridePulseLength, PulseAverageSettings::pulseSortOrder, PulseAverageSettings::regionSlider, PulseAverageSettings::searchFailedPulses, PulseAverageSettings::showAverage, PulseAverageSettings::showImages, PulseAverageSettings::showIndividualPulses, PulseAverageSettings::showTraces, PulseAverageSettings::startingPulse, PulseAverageSettings::yScaleBarLength, PulseAverageSettings::zeroPulses.
Referenced by PA_DeserializeSettings, PA_GatherSettings.
variable InitFormulaProperties(FormulaProperties *fp)
References FormulaProperties::formula, FormulaProperties::numCols, FormulaProperties::numRows, FormulaProperties::stimsetList.
Referenced by WB_FormulaSwitchToStimset, WB_ParseCombinerFormula.
variable InitOOdDAQParams(OOdDAQParams *params, WaveRefWave stimSets, wave setColumns, variable preFeatureTime, variable postFeatureTime)
References ASSERT, OOdDAQParams::offsets, OOdDAQParams::postFeaturePoints, OOdDAQParams::preFeaturePoints, OOdDAQParams::preload, OOdDAQParams::regions, ROWS, OOdDAQParams::setColumns, OOdDAQParams::stimSets, WAVEBUILDER_MIN_SAMPINT.
Referenced by DC_GetConfiguration.
variable InitDeltaControlNames(DeltaControlNames *s)
References DeltaControlNames::delta, DeltaControlNames::dme, DeltaControlNames::ldelta, DeltaControlNames::main, DeltaControlNames::op.
Referenced by WB_GetDeltaDimLabel.
variable InitRectD(RectD *s)
References RectD::bottom, RectD::left, RectD::right, RectD::top.
Referenced by GetPlotArea.
variable InitBufferedDrawInfo(BufferedDrawInfo *s)
initializes a BufferedDrawInfo structure The json path for AppendTracesToGraph and Labels is set empty by default
TiledGraphAccelerateDraw
References BUFFEREDDRAWAPPEND, BUFFEREDDRAWDDAQAXES, BUFFEREDDRAWHIDDENTRACES, BUFFEREDDRAWLABEL, BufferedDrawInfo::jsonID, MINIMUM_WAVE_SIZE_LARGE, NOTE_INDEX, SetNumberInWaveNote, BufferedDrawInfo::traceWaves.
Referenced by OVS_EndIncrementalUpdate.
variable NWB_ASYNC_SerializeStruct(NWBAsyncParameters *s, dfref threadDFR)
References ASYNC_AddParam, NWBAsyncParameters::compressionMode, NWBAsyncParameters::DAQConfigWave, NWBAsyncParameters::DAQDataWave, NWBAsyncParameters::device, NWBAsyncParameters::locationID, NWBAsyncParameters::numericalKeys, NWBAsyncParameters::numericalResultsKeys, NWBAsyncParameters::numericalResultsValues, NWBAsyncParameters::numericalValues, NWBAsyncParameters::nwbVersion, NWBAsyncParameters::session_start_time, NWBAsyncParameters::sweep, NWBAsyncParameters::textualKeys, NWBAsyncParameters::textualResultsKeys, NWBAsyncParameters::textualResultsValues, NWBAsyncParameters::textualValues, NWBAsyncParameters::userComment.
Referenced by NWB_AppendSweepDuringDAQ.
std::tuple< NWBAsyncParameters > NWB_ASYNC_DeserializeStruct(dfref threadDFR)
References ASYNC_FetchString, ASYNC_FetchVariable, ASYNC_FetchWave, ChangeWaveLock.
Referenced by NWB_ASYNC_Worker.