MIES_Cache.ipf
string CA_DistDAQCreateCacheKey(OOdDAQParams *params)
Cache key generator for oodDAQ offset waves.
References OOdDAQParams::postFeaturePoints, OOdDAQParams::preFeaturePoints, OOdDAQParams::preload, ROWS, OOdDAQParams::setColumns, OOdDAQParams::stimSets.
Referenced by OOD_GetResultWaves.
string CA_PulseTimes(wave wv, string fullPath, variable channelNumber, variable totalOnsetDelay)
Cache key generator for FindLevel in PA_CalculatePulseTimes()
References WaveModCountWrapper.
Referenced by PA_CalculatePulseInfos.
string CA_SmoothDeconv(wave wv, variable smoothingFactor, variable range_pnts)
Cache key generator for PA_SmoothDeconv()
wv input wave (average) smoothingFactor smoothing factor range_pnts number of points (p) the smoothing was performed
References ROWS.
Referenced by PA_SmoothDeconv.
string CA_Deconv(wave wv, variable tau)
Cache key generator for PA_Deconvolution()
wv input wave (smoothed average) tau convolution time
References ROWS.
Referenced by PA_Deconvolution.
string CA_ArtefactRemovalRangesKey(dfref singleSweepDFR, variable sweepNo)
Cache key generator for artefact removal ranges.
Referenced by AR_ComputeRanges.
string CA_AveragingKey(WaveRefWave waveRefs)
Cache key generator for averaging.
References CA_WaveCRCs, ROWS.
Referenced by CalculateAverage.
string CA_AveragingWaveModKey(wave wv)
Cache key generator for averaging info from non-free waves.
References CA_RecursiveWavemodCRC.
Referenced by PA_CalculateAllAverages.
static variable CA_RecursiveWavemodCRC(WaveOrNull wv, variable prevCRC=defaultValue)
Calculated a CRC from non wave reference waves using modification data, wave modification count and wave location. If the given wave is a wave reference wave, then the CRC is calculated recursively from all non wave reference waves and null wave references found.
References CA_GetWaveModCRC, CA_RecursiveWavemodCRC, CHUNKS, COLS, IsWaveRefWave, LAYERS, ROWS.
Referenced by CA_AveragingWaveModKey, CA_RecursiveWavemodCRC.
static variable CA_GetWaveModCRC(wave wv, variable crc)
References WaveModCountWrapper.
Referenced by CA_RecursiveWavemodCRC.
static variable CA_WaveScalingCRC(variable crc, wave wv, variable dimension=defaultValue)
Calculate the CRC of all metadata of all or the given dimension.
References ASSERT_TS, CHUNKS, ROWS.
Referenced by CA_WaveCRCs.
static string CA_WaveCRCs(WaveRefWave waveRefs, variable crcMode=defaultValue, variable includeWaveScalingAndUnits=defaultValue, variable dims=defaultValue)
Calculate all CRC values of the waves referenced in waveRefs.
waveRefs wave reference wave crcMode [optional] parameter to WaveCRC includeWaveScalingAndUnits [optional] include the wave scaling and units of filled dimensions dims [optional] number of dimensions to include wave scaling and units in crc
References ASSERT, CA_WaveScalingCRC, NUM_ENTRIES_FOR_MULTITHREAD, NumericWaveToList, ROWS.
Referenced by CA_AveragingKey.
string CA_SamplingIntervalKey(wave lut, ActiveChannels *s)
Calculate the cache key for SI_FindMatchingTableEntry.
We are deliberatly not using a WaveCRC here as know that the wave is not changed in IP once loaded. Therefore using its name and ModDate is enough.
References ASSERT, IsFreeWave, ActiveChannels::numADRack1, ActiveChannels::numADRack2, ActiveChannels::numDARack1, ActiveChannels::numDARack2, ActiveChannels::numTTLRack1, ActiveChannels::numTTLRack2.
Referenced by SI_FindMatchingTableEntry.
string CA_TemporaryWaveKey(wave dims)
Generic key generator for storing throw away waves used for Multithread assignments.
Only the size is relevant, the rest is undefined.
References ASSERT_TS, COLS, MAX_DIMENSION_COUNT, ROWS.
Referenced by DecimateWithMethod, FindIndizes.
string CA_HWDeviceInfoKey(string device, variable hardwareType, variable deviceID)
Calculate the cache key for the hardware device info wave.
Referenced by DC_DocumentHardwareProperties.
string CA_HardwareDataTPKey(HardwareDataTPInput *s)
Generate a key for the DAQDataWave in TEST_PULSE_MODE.
Properties which influence the Testpulse: hardwareType numDA (filled columns) numActiveChannels (number of columns) number of rows, return from DC_CalculateDAQDataWaveLength(device, TEST_PULSE_MODE) samplingInterval DAGain DACAmp[][TPAmp] column testPulseLength, baselineFrac
References HardwareDataTPInput::baselineFrac, HardwareDataTPInput::DACAmpTP, HardwareDataTPInput::DAGain, HardwareDataTPInput::hardwareType, HardwareDataTPInput::numActiveChannels, HardwareDataTPInput::numberOfRows, HardwareDataTPInput::numDACs, HardwareDataTPInput::samplingInterval, HardwareDataTPInput::testPulseLength.
Referenced by DC_FillDAQDataWaveForTP.
static variable CA_MakeSpaceForNewEntry()
Make space for one new entry in the cache waves.
index into cache waves
References ASSERT_TS, EnsureLargeEnoughWave, GetCacheKeyWave, GetCacheStatsWave, GetCacheValueWave, GetNumberFromWaveNote, NOTE_INDEX, ROWS, SetNumberInWaveNote.
Referenced by CA_StoreEntryIntoCache.
variable CA_StoreEntryIntoCache(string key, wave val, variable options=defaultValue)
Add a new entry into the cache.
key string which uniquely identifies the cached wave val wave to store options [optional, defaults to none] One or multiple constants from CacheFetchOptions Existing entries with the same key are overwritten.
References ASSERT_TS, CA_MakeSpaceForNewEntry, CA_OPTS_NO_DUPLICATE, DateTimeInUTC, DeepCopyWaveRefWave, GetCacheKeyWave, GetCacheStatsWave, GetCacheValueWave, GetWaveSize, IsEmpty, IsWaveRefWave.
Referenced by AR_ComputeRanges, CalculateAverage, DC_DocumentHardwareProperties, DC_FillDAQDataWaveForTP, DecimateWithMethod, FindIndizes, GetLBIndexCache, GetLBNidCache, GetLBRowCache, OOD_GetResultWaves, PA_CalculateAllAverages, PA_CalculatePulseInfos, PA_Deconvolution, PA_SmoothDeconv, SI_FindMatchingTableEntry.
static variable CA_GetCacheIndex(string key)
Return the index of the entry key
non-negative number or NaN if it could not be found.
References ASSERT_TS, GetCacheKeyWave, isEmpty.
Referenced by CA_DeleteCacheEntry, CA_TryFetchingEntryFromCache.
wave CA_TryFetchingEntryFromCache(string key, variable options=defaultValue)
Try to fetch the wave stored under key from the cache.
key string which uniquely identifies the cached wave options [optional, defaults to none] One or multiple constants from CacheFetchOptions A wave reference with the stored data or a invalid wave reference if nothing could be found.
References ASSERT_TS, CA_GetCacheIndex, CA_OPTS_NO_DUPLICATE, DEBUGPRINT_TS, DeepCopyWaveRefWave, GetCacheKeyWave, GetCacheStatsWave, GetCacheValueWave, IsFinite, IsWaveRefWave, ROWS.
Referenced by AR_ComputeRanges, CalculateAverage, DC_DocumentHardwareProperties, DC_FillDAQDataWaveForTP, DecimateWithMethod, FindIndizes, GetLBIndexCache, GetLBNidCache, GetLBRowCache, OOD_GetResultWaves, PA_CalculateAllAverages, PA_CalculatePulseInfos, PA_Deconvolution, PA_SmoothDeconv, SI_FindMatchingTableEntry.
variable CA_DeleteCacheEntry(string key)
Try to delete a cache entry.
One if it could be found and deleted, zero otherwise
References ASSERT, CA_GetCacheIndex, GetCacheKeyWave, GetCacheStatsWave, GetCacheValueWave, IsFinite, ROWS.
variable CA_FlushCache()
Remove all entries from the wave cache.
References GetCacheKeyWave, GetCacheStatsWave, GetCacheValueWave, KillOrMoveToTrash.
Referenced by IH_Cleanup.
variable CA_OutputCacheStatistics()
Output cache statistics.
References COLS, ControlWindowToFront, GetCacheStatsWave, GetISO8601TimeStamp, GetNumberFromWaveNote, NOTE_INDEX.