MIES_WaveBuilder.ipf
const double WB_IDX_DURATION
Referenced by WB_GetControlWithDeltaIdx.
const double WB_IDX_AMPLITUDE
const double WB_IDX_OFFSET
const double WB_IDX_SIN_CHIRP_SAW_FREQUENCY
const double WB_IDX_TRAIN_PULSE_DURATION
const double WB_IDX_PSC_EXP_RISE_TIME
const double WB_IDX_PSC_EXP_DECAY_TIME_1_2
const double WB_IDX_PSC_EXP_DECAY_TIME_2_2
const double WB_IDX_PSC_RATIO_DECAY_TIMES
const double WB_IDX_LOW_PASS_FILTER_CUT_OFF
const double WB_IDX_HIGH_PASS_FILTER_CUT_OFF
const double WB_IDX_CHIRP_END_FREQUENCY
const double WB_IDX_NOISE_FILTER_ORDER
const double WB_IDX_PT_FIRST_MIXED_FREQUENCY
const double WB_IDX_PT_LAST_MIXED_FREQUENCY
const double WB_IDX_NUMBER_OF_PULSES
const double WB_IDX_ITI
static variable WB_SquareSegment(SegmentParameters *pa)
References SegmentParameters::amplitude, SegmentParameters::duration, GetSegmentWave.
Referenced by WB_MakeWaveBuilderWave.
static variable WB_RampSegment(SegmentParameters *pa)
References SegmentParameters::amplitude, SegmentParameters::duration, GetSegmentWave, WAVEBUILDER_MIN_SAMPINT.
Referenced by WB_MakeWaveBuilderWave.
variable WB_IsValidCutoffFrequency(variable freq)
Check if the given frequency is a valid setting for the noise epoch.
References WAVEBUILDER_MIN_SAMPINT_HZ, WB_IsValidScaledCutoffFrequency.
Referenced by WBP_CutOffCrossOver, WBP_UpdatePanelIfAllowed.
variable WB_IsValidScaledCutoffFrequency(variable freq)
Check if the given frequency is a valid setting for the noise epoch.
Requires a scaled frequency as input, see DisplayHelpTopic "FilterIIR"
Referenced by WB_IsValidCutoffFrequency, WB_NoiseSegment.
static variable WB_NoiseSegment(SegmentParameters *pa)
References SegmentParameters::amplitude, ASSERT, SegmentParameters::buildResolution, DEBUG_TIMER_START, DEBUGPRINT_ELAPSED, DP_DebuggingEnabledForCaller, SegmentParameters::duration, SegmentParameters::filterOrder, GetSegmentWave, IsInteger, NOISE_GEN_MERSENNE_TWISTER, NOISE_TYPE_BROWN, NOISE_TYPE_PINK, NOISE_TYPE_WHITE, SegmentParameters::noiseType, ROWS, WAVEBUILDER_MIN_SAMPINT_HZ, WB_IsValidScaledCutoffFrequency.
Referenced by WB_MakeWaveBuilderWave.
static variable WB_TrigSegment(SegmentParameters *pa)
References SegmentParameters::amplitude, SegmentParameters::duration, SegmentParameters::endFrequency, SegmentParameters::frequency, GetSegmentWave, SegmentParameters::logChirp, SegmentParameters::trigFuncType.
Referenced by WB_MakeWaveBuilderWave.
static variable WB_SawToothSegment(SegmentParameters *pa)
References SegmentParameters::amplitude, SegmentParameters::duration, SegmentParameters::frequency, GetSegmentWave.
Referenced by WB_MakeWaveBuilderWave.
static variable WB_CreatePulse(wave wv, variable pulseType, variable amplitude, variable first, variable last)
References SegmentParameters::amplitude, ASSERT, SegmentParameters::pulseType, WB_PULSE_TRAIN_TYPE_SQUARE, WB_PULSE_TRAIN_TYPE_TRIANGLE.
Referenced by WB_PulseTrainSegment.
string WB_ToEpochTypeString(variable epochType)
Convert the numeric epoch type to a stringified version.
References ASSERT, EPOCH_TYPE_COMBINE, EPOCH_TYPE_CUSTOM, EPOCH_TYPE_NOISE, EPOCH_TYPE_PSC, EPOCH_TYPE_PULSE_TRAIN, EPOCH_TYPE_RAMP, EPOCH_TYPE_SAW_TOOTH, EPOCH_TYPE_SIN_COS, EPOCH_TYPE_SQUARE_PULSE.
Referenced by ScreenShotsForWaveBuilder, WB_MakeWaveBuilderWave.
variable WB_ToEpochType(string epochTypeStr)
Convert the stringified epoch type to a numerical one.
References ASSERT, EPOCH_TYPE_COMBINE, EPOCH_TYPE_CUSTOM, EPOCH_TYPE_NOISE, EPOCH_TYPE_PSC, EPOCH_TYPE_PULSE_TRAIN, EPOCH_TYPE_RAMP, EPOCH_TYPE_SAW_TOOTH, EPOCH_TYPE_SIN_COS, EPOCH_TYPE_SQUARE_PULSE.
Referenced by EP_AddEpochsFromStimSetNote.
string WB_GetWaveNoteEntry(string text, variable entryType, string key=defaultValue, variable sweep=defaultValue, variable epoch=defaultValue)
Query stimset wave note entries.
embed:rst:leading-asterisk * Format of the wave note: * * Lines separated by ``\r`` (carriage return) in UTF-8 encoding. * The lines hold Igor Pro style key value pairs in the form ``key = value;`` * where value can contain any character except ``;`` (semicolon). * * Four types of entries can be distinguished: * * - Version: In the very first line (line 1) * - Sweep specific entries have an epoch of ``nan``: (line 2, 7) * - Epoch specific: (line 3 - 6) * - Stimset specific: (line 12) * * Additional infos on selected entries: * - `ITI` is in seconds * - `Flipping` is done on a per stimset basis * - `Durations` are in `stimset build ms` * - `Pulse Train Pulses` are absolute pulse starting times in `epoch build ms` * - `Pulse To Pulse Length` is in `stimset build ms` * - `Function params (encoded)` contains the analysis function parameters. The values have the format described at GetWaveBuilderWaveTextParam(). * * Example: * * .. code-block:: none * :linenos: * * Version = 2; * Sweep = 0;Epoch = nan;ITI = 1; * Sweep = 0;Epoch = 0;Type = Square pulse;Duration = 500;Amplitude = 0; * Sweep = 0;Epoch = 1;Type = Ramp;Duration = 150;Amplitude = 1;Offset = 0; * Sweep = 0;Epoch = 2;Type = Square pulse;Duration = 300;Amplitude = 0; * Sweep = 0;Epoch = 3;Type = Pulse Train;Duration = 960.005;Amplitude = 1;Offset = 0;Pulse Type = Square;Frequency = 20;Pulse To Pulse Length = 50;Pulse duration = 10;Number of pulses = 20;Mixed frequency = False;First mixed frequency = 0;Last mixed frequency = 0;Poisson distribution = False;Random seed = 0.963638;Pulse Train Pulses = 0,50,100,150,200,250,300,350,400,450,500,550,600,650,700,750,800,850,900,950,;Definition mode = Duration; * Sweep = 1;Epoch = nan;ITI = 2; * Sweep = 1;Epoch = 0;Type = Square pulse;Duration = 500;Amplitude = 0; * Sweep = 1;Epoch = 1;Type = Ramp;Duration = 150;Amplitude = 1;Offset = 0; * Sweep = 1;Epoch = 2;Type = Square pulse;Duration = 300;Amplitude = 0; * Sweep = 1;Epoch = 3;Type = Pulse Train;Duration = 960.005;Amplitude = 1;Offset = 0;Pulse Type = Square;Frequency = 20;Pulse To Pulse Length = 50;Pulse duration = 10;Number of pulses = 20;Mixed frequency = False;First mixed frequency = 0;Last mixed frequency = 0;Poisson distribution = False;Random seed = 0.963638;Pulse Train Pulses = 0,50,100,150,200,250,300,350,400,450,500,550,600,650,700,750,800,850,900,950,;Definition mode = Duration; * Stimset;Sweep Count = 2;Epoch Count = 4;Pre DAQ = ;Mid Sweep = ;Post Sweep = ;Post Set = ;Post DAQ = ;Pre Sweep = ;Generic = PSQ_Ramp;Pre Set = ;Function params (encoded)= NumberOfSpikes:variable=5,Elements:string=%20%3B%2C;Flip = 0;Random Seed = 0.963638;Checksum = 65446509; * text stimulus set wave note entryType one of StimsetWaveNoteEntryTypes key [optional] named entry to return, not required for VERSION_ENTRY sweep [optional] number of the sweep epoch [optional] number of the epoch
References ASSERT, EPOCH_ENTRY, ExtractStringFromPair, IsEmpty, IsValidEpochNumber, IsValidSweepNumber, STIMSET_ENTRY, SWEEP_ENTRY, VERSION_ENTRY.
Referenced by EP_AddEpochsFromStimSetNote, ExtractAnalysisFuncFromStimSet, ExtractAnalysisFunctionParams, WB_GetPulsesFromPTSweepEpoch, WB_GetWaveNoteEntryAsNumber.
variable WB_GetWaveNoteEntryAsNumber(string text, variable entryType, string key=defaultValue, variable sweep=defaultValue, variable epoch=defaultValue)
References IsEmpty, WB_GetWaveNoteEntry.
Referenced by EP_AddEpochsFromStimSetNote, WB_GetITI, WB_GetPulsesFromPTSweepEpoch, WB_StimsetHasLatestNoteVersion.
wave WB_GetPulsesFromPTSweepEpoch(wave stimset, variable sweep, variable epoch, variable *pulseToPulseLength)
References ASSERT, EPOCH_ENTRY, IsFinite, ListToNumericWave, PULSE_START_TIMES_KEY, PULSE_TO_PULSE_LENGTH_KEY, ROWS, WB_GetWaveNoteEntry, WB_GetWaveNoteEntryAsNumber.
Referenced by EP_AddEpochsFromStimSetNote.
static wave WB_PulseTrainSegment(SegmentParameters *pa, variable mode, wave pulseStartTimes, variable *pulseToPulseLength)
References SegmentParameters::amplitude, ASSERT, DEBUGPRINT, SegmentParameters::duration, EnsureLargeEnoughWave, SegmentParameters::firstFreq, SegmentParameters::frequency, GetSegmentWave, InPlaceRandomShuffle, SegmentParameters::lastFreq, SegmentParameters::mixedFreq, SegmentParameters::mixedFreqShuffle, NOISE_GEN_LINEAR_CONGRUENTIAL, NOISE_GEN_MERSENNE_TWISTER, SegmentParameters::numberOfPulses, SegmentParameters::poisson, PULSE_TRAIN_MODE_DUR, PULSE_TRAIN_MODE_PULSE, SegmentParameters::pulseDuration, SegmentParameters::pulseType, ROWS, WAVEBUILDER_MIN_SAMPINT, WB_CreatePulse, WB_PULSE_TRAIN_TYPE_SQUARE.
Referenced by WB_MakeWaveBuilderWave.
static variable WB_PSCSegment(SegmentParameters *pa)
References SegmentParameters::amplitude, SegmentParameters::duration, GetSegmentWave, WAVEBUILDER_MIN_SAMPINT, WaveMinAndMaxWrapper.
Referenced by WB_MakeWaveBuilderWave.
static variable WB_CustomWaveSegment(SegmentParameters *pa, wave customWave)
References SegmentParameters::duration, GetSegmentWave, ROWS, WAVEBUILDER_MIN_SAMPINT.
Referenced by WB_MakeWaveBuilderWave.
static wave WB_FillWaveFromFormula(string formula, variable channelType, variable sweep)
Create a wave segment as combination of existing stim sets.
References DEBUGPRINT, GetSetFolder, KillOrMoveToTrash, MakeWaveFree, WB_FormulaSwitchToShorthand, WB_ParseCombinerFormula, WB_UpdateEpochCombineList.
Referenced by WB_MakeWaveBuilderWave.
const double PULSE_TRAIN_MODE_DUR
Referenced by WB_MakeWaveBuilderWave, WB_PulseTrainSegment.
const double PULSE_TRAIN_MODE_PULSE
Referenced by WB_MakeWaveBuilderWave, WB_PulseTrainSegment.
const double WB_PULSE_TRAIN_TYPE_SQUARE
Referenced by WB_CreatePulse, WB_PulseTrainSegment.
const double WB_PULSE_TRAIN_TYPE_TRIANGLE
Referenced by WB_CreatePulse.
const double DELTA_OPERATION_EXPLICIT
Referenced by WB_CalculateParameterWithDelta.
wave WB_CreateAndGetStimSet(string setName)
Return the stim set wave and create it permanently in the datafolder hierarchy.
stimset wave ref or an invalid wave ref
References CHANNEL_TYPE_UNKNOWN, GetSetFolder, GetStimSetType, isEmpty, KillOrMoveToTrash, WB_GetStimSet, WB_StimsetIsFromThirdParty, WB_StimsetNeedsUpdate.
Referenced by AFM_UpdateAnalysisFunctionWave, DAP_CheckAnalysisFunctionAndParameter, DAP_CheckStimset, DC_GetConfiguration, DC_ITC_MakeTTLWave, DC_LongestOutputWave, DC_NI_MakeTTLWave, IDX_NumberOfSweepsInSet, MSQ_CreateOverrideResults, MSQ_GetDAStimsetLength, NWB_WriteStimsetTemplateWaves, PSQ_CreateOverrideResults, PSQ_GetDAStimsetLength, PSQ_PipetteInBath_CheckParam, ReachTargetVoltage, WB_GetStimSet, WB_MakeStimsetThirdParty, WB_OpenStimulusSetInWaveBuilder, WB_ParseCombinerFormula, WB_SaveStimSet.
string WB_GetParameterWaveName(string stimset, variable type, variable nwbFormat=defaultValue)
Return the name of one of the three stimset parameter waves.
stimset name of stimset type indicate parameter wave (WP, WPT, or SegWvType), see ParameterWaveTypes nwbFormat [optional, defaults to false] nwbFormat has type as suffix name as string
References GetWaveBuilderParameterTypeName.
Referenced by AB_LoadStimsetTemplateWaves, NWB_LoadStimset, NWB_WriteStimsetTemplateWaves.
wave WB_GetWaveParamForSet(string setName)
Return the wave WP for a stim set.
valid/invalid wave reference
References CHANNEL_TYPE_UNKNOWN, GetSetParamFolder, GetStimSetType, STIMSET_PARAM_WP, UpgradeWaveParam.
Referenced by NWB_WriteStimsetTemplateWaves, WB_CalculateStimsetChecksum, WB_GetStimSet, WB_KillParameterWaves, WB_MakeStimsetThirdParty, WB_ParameterWavesExist, WB_ParameterWvsNewerThanStim, WB_StimsetChildren, WB_StimsetIsFromThirdParty, WB_UpdateEpochCombineList, WBP_LoadSet.
wave WB_GetWaveTextParamForSet(string setName)
Return the wave WPT for a stim set.
valid/invalid wave reference
References CHANNEL_TYPE_UNKNOWN, GetSetParamFolder, GetStimSetType, STIMSET_PARAM_WPT, UpgradeWaveTextParam.
Referenced by AFH_AddAnalysisParameter, NWB_WriteStimsetTemplateWaves, WB_CalculateStimsetChecksum, WB_CustomWavesPathFromStimSet, WB_GetStimSet, WB_KillParameterWaves, WB_MakeStimsetThirdParty, WB_ParameterWavesExist, WB_ParameterWvsNewerThanStim, WB_StimsetChildren, WB_StimsetIsFromThirdParty, WB_UpgradeCustomWaves, WBP_LoadSet.
wave WB_GetSegWvTypeForSet(string setName)
Return the wave SegmentWvType for a stim set.
valid/invalid wave reference
References CHANNEL_TYPE_UNKNOWN, GetSetParamFolder, GetStimSetType, STIMSET_PARAM_SEGWVTYPE, UpgradeSegWvType.
Referenced by NWB_WriteStimsetTemplateWaves, WB_CalculateStimsetChecksum, WB_CustomWavesPathFromStimSet, WB_GetStimSet, WB_KillParameterWaves, WB_MakeStimsetThirdParty, WB_ParameterWavesExist, WB_ParameterWvsNewerThanStim, WB_StimsetChildren, WB_StimsetIsFromThirdParty, WB_UpgradeCustomWaves, WBP_LoadSet.
static variable WB_StimsetNeedsUpdate(string setName)
Check if stimset needs to be created.
Stimset is recreated if one of the parameter waves was modified the custom wave that was used to build the stimset was modified 1 if stimset needs to be recreated, 0 otherwise
References ASSERT, ROWS, WB_CustomWavesFromStimSet, WB_GetLastModStimSet, WB_ParameterWvsNewerThanStim, WB_StimsetHasLatestNoteVersion, WB_StimsetRecursion.
Referenced by WB_CreateAndGetStimSet, WB_GetStimSet.
static variable WB_StimsetHasLatestNoteVersion(string setName)
Check if the stimset wave note has the latest version.
References ASSERT, CHANNEL_TYPE_UNKNOWN, GetSetFolder, GetStimSetType, STIMSET_NOTE_VERSION, VERSION_ENTRY, WB_GetWaveNoteEntryAsNumber.
Referenced by WB_StimsetNeedsUpdate.
static variable WB_ParameterWvsNewerThanStim(string setName)
Check if parameter waves' are newer than the saved stimset.
setName string containing name of stimset 1 if Parameter waves were modified, 0 otherwise
References ASSERT, CHANNEL_TYPE_UNKNOWN, DEBUGPRINT, GetSetFolder, GetStimSetType, GetStringFromWaveNote, IsEmpty, WaveModCountWrapper, WB_GetLastModStimSet, WB_GetSegWvTypeForSet, WB_GetWaveParamForSet, WB_GetWaveTextParamForSet.
Referenced by WB_StimsetNeedsUpdate.
variable WB_GetStimsetChecksum(wave stimset, string setName, variable dataAcqOrTP)
Return a checksum of the stimsets and its parameter waves.
Uses the entry from the stimset wave note if available.
References IsFinite, TEST_PULSE_MODE, WB_CalculateStimsetChecksum.
Referenced by DC_ITC_MakeTTLWave, DC_NI_MakeTTLWave, DC_PrepareLBNEntries.
static variable WB_CalculateStimsetChecksum(wave stimset, string setName)
Calculcate the checksum of the stimsets and its parameter waves.
References WB_GetSegWvTypeForSet, WB_GetWaveParamForSet, WB_GetWaveTextParamForSet.
Referenced by WB_GetStimSet, WB_GetStimsetChecksum.
variable WB_GetLastModStimSet(string setName)
Get modification date of saved stimset wave.
setName string containing name of stimset date of last modification as double precision Igor date/time value
References CHANNEL_TYPE_UNKNOWN, GetSetFolder, GetStimSetType.
Referenced by WB_ParameterWvsNewerThanStim, WB_StimsetNeedsUpdate.
wave WB_GetStimSetForWaveBuilder()
Return the current stimset wave for the wavebuilder.
References WB_GetStimSet.
Referenced by WBP_DisplaySetInPanel.
static wave WB_GetStimSet(string setName=defaultValue)
Return the stim set wave.
As opposed to WB_CreateAndGetStimSet this function returns a free wave only setName [optional, defaults to WaveBuilderPanel GUI settings] name of the set free wave with the stim set, invalid wave ref if the WP* parameter waves could not be found.
References AddEntryIntoWaveNoteAsList, ASSERT, CHANNEL_TYPE_UNKNOWN, DEBUG_TIMER_START, DEBUGPRINT_ELAPSED, GetSegmentTypeWave, GetStimSetType, GetWaveBuilderWaveParam, GetWaveBuilderWaveTextParam, isEmpty, ROWS, WAVEBUILDER_MIN_SAMPINT, WaveModCountWrapper, WB_AddDelta, WB_CalculateStimsetChecksum, WB_CreateAndGetStimSet, WB_GetSegWvTypeForSet, WB_GetWaveParamForSet, WB_GetWaveTextParamForSet, WB_MakeWaveBuilderWave, WB_StimsetNeedsUpdate, WB_StimsetRecursion, WBP_GetStimulusType.
Referenced by WB_CreateAndGetStimSet, WB_GetStimSetForWaveBuilder.
static wave WB_GetControlWithDeltaIdx()
Return a free wave with indizes referencing the values with delta values.
Indizes are into WP and reference the entry with the value itself. AddDimLabelsToWP() Constants are defined at ControlDeltaIndizes.
References WB_IDX_DURATION.
Referenced by WB_AddDelta.
static wave WB_GetControlWithDeltaWvs(wave WP, wave SegWvType)
Return a free wave with wave references where the values with delta reside in.
AddDimLabelsToWP()
Referenced by WB_AddDelta.
variable WB_GetDeltaDimLabel(wave wv, variable index, DeltaControlNames *s)
Return the WP/WPT/SegWvType dimension labels for the related delta controls given the index into WP of the value itself.
0 on success, 1 otherwise
References DeltaControlNames::delta, DeltaControlNames::dme, InitDeltaControlNames, IsEmpty, DeltaControlNames::ldelta, DeltaControlNames::main, DeltaControlNames::op, ROWS.
Referenced by WB_AddDelta, WBP_AdjustDeltaControls.
static variable WB_AddDelta(string setName, wave WP, wave WPOrig, WaveText WPT, wave SegWvType, wave SegWvTypeOrig, variable sweep, variable numSweeps)
Add delta to appropriate parameters.
Relies on alternating sequence of parameter and delta's in parameter waves as documented in WB_MakeWaveBuilderWave(). setName name of the stimset WP wavebuilder parameter wave (temporary copy) WPOrig wavebuilder parameter wave (original) WPT wavebuilder text parameter wave SegWvType segment parameter wave (temporary copy) SegWvTypeOrig segment parameter wave (original) sweep sweep number numSweeps total number of sweeps
References ASSERT, INDEP_EPOCH_TYPE, isEmpty, ROWS, WB_CalculateParameterWithDelta, WB_GetControlWithDeltaIdx, WB_GetControlWithDeltaWvs, WB_GetDeltaDimLabel.
Referenced by WB_GetStimSet.
static variable WB_CalculateParameterWithDelta(variable operation, variable *value, variable *delta, variable dme, string ldelta, variable originalValue, variable sweep, variable numSweeps, string setName, string paramName)
Calculate the new value of a parameter taking into account the delta operation.
operation delta operation, one of WaveBuilderDeltaOperationModes value parameter value (might be incremented by former delta application calls) delta delta value dme delta multiplier or exponent ldelta explicit list of delta values originalValue unmodified parameter value sweep sweep number numSweeps number of sweeps setName name of the stimulus set (used for error reporting) paramName name of the parameter (used for error reporting)
References DELTA_OPERATION_ALTERNATE, DELTA_OPERATION_DEFAULT, DELTA_OPERATION_EXPLICIT, DELTA_OPERATION_FACTOR, DELTA_OPERATION_LOG, DELTA_OPERATION_POWER, DELTA_OPERATION_SQUARED, IsNaN, str2numSafe.
Referenced by WB_AddDelta.
static wave WB_MakeWaveBuilderWave(wave WP, WaveText WPT, wave SegWvType, variable stepCount, variable numEpochs, variable channelType, variable updateEpochIDWave, string stimset=defaultValue)
References AddEntryIntoWaveNoteAsList, ANALYSIS_FUNCTION_PARAMS_STIMSET, ASSERT, DEBUGPRINT, EPOCH_TYPE_COMBINE, EPOCH_TYPE_CUSTOM, EPOCH_TYPE_NOISE, EPOCH_TYPE_PSC, EPOCH_TYPE_PULSE_TRAIN, EPOCH_TYPE_RAMP, EPOCH_TYPE_SAW_TOOTH, EPOCH_TYPE_SIN_COS, EPOCH_TYPE_SQUARE_PULSE, EVENT_NAME_LIST, GENERIC_EVENT, GetEpochID, GetSegmentWave, GetSetVariable, GetTabID, INDEP_EPOCH_TYPE, isEmpty, IsFinite, MID_SWEEP_EVENT, MINIMUM_WAVE_SIZE, NOISE_TYPES_STRINGS, NumericWaveToList, POST_DAQ_EVENT, POST_SET_EVENT, POST_SWEEP_EVENT, PRE_DAQ_EVENT, PRE_SET_EVENT, PRE_SWEEP_CONFIG_EVENT, PULSE_START_TIMES_KEY, PULSE_TO_PULSE_LENGTH_KEY, PULSE_TRAIN_MODE_DUR, PULSE_TRAIN_MODE_PULSE, PULSE_TYPES_STRINGS, ROWS, STIMSET_NOTE_VERSION, ToTrueFalse, WAVEBUILDER_COMBINE_FORMULA_VER, WAVEBUILDER_MIN_SAMPINT, WB_ApplyOffset, WB_CustomWaveSegment, WB_FillWaveFromFormula, WB_InitializeSeed, WB_NoiseSegment, WB_PSCSegment, WB_PulseTrainSegment, WB_RampSegment, WB_SawToothSegment, WB_SquareSegment, WB_ToEpochTypeString, WB_TrigSegment, WB_UpdateEpochID, WBP_GetNoiseBuildResolution, WBP_ShowFFTSpectrumIfReq, WBP_UpdateControlAndWave.
Referenced by WB_GetStimSet.
static variable WB_UpdateEpochID(variable epochIndex, variable epochDuration, variable accumulatedDuration)
Update the accumulated stimset duration for the mouse selection via GetEpochID()
epochIndex index of the epoch epochDuration duration of the current segment accumulatedDuration accumulated duration in the stimset for the first step
References GetEpochID.
Referenced by WB_MakeWaveBuilderWave.
variable WB_GetITI(wave stimset, variable sweep)
Query the stimset wave note for the sweep/set specific ITI.
References IsFinite, STIMSET_ENTRY, SWEEP_ENTRY, WB_GetWaveNoteEntryAsNumber.
Referenced by DC_PrepareLBNEntries.
variable WB_UpgradeCustomWaveInWPT(WaveText wv, variable channelType, variable i)
Try to recover a custom wave when in the old format (aka with only a wave name and not a full path)
wv WPT wave reference channelType AD/DA or TTL channel type i index of epoch containing custom wave
References EPOCH_TYPE_CUSTOM, GetSetFolder, isEmpty, WBP_GetFolderPath.
static variable WB_ApplyOffset(SegmentParameters *pa)
References GetSegmentWave, SegmentParameters::offset.
Referenced by WB_MakeWaveBuilderWave.
static variable WB_InitializeSeed(wave WP, wave SegWvType, variable epoch, variable type, variable stepCount)
Initialize the seed value of the pseudo random number generator.
References GetReproducibleRandom, NewRandomSeed, SegmentParameters::randomSeed.
Referenced by WB_MakeWaveBuilderWave.
variable WB_UpdateEpochCombineList(variable channelType)
Update the shorthand/stimset wave for the epoch type Combine
The rows are sorted by creationDate of the WP/stimset wave to try to keep the shorthands constants even when new stimsets are added.
References ASSERT, GetSetFolder, GetWBEpochCombineList, ST_GetStimsetList, STIMSET_TP_WHILE_DAQ, WB_GenerateUniqueLabel, WB_GetWaveParamForSet.
Referenced by WB_FillWaveFromFormula, WB_SaveStimSet, WBP_ButtonProc_SaveSet, WBP_UpdatePanelIfAllowed.
static string WB_GenerateUniqueLabel(variable idx)
Generate a unique textual representation of an index.
Returns the alphabet for 1-26, and then A1, B1, ..., Z1000
Referenced by WB_UpdateEpochCombineList.
variable WB_ParseCombinerFormula(string formula, variable sweep, FormulaProperties *fp)
Parse the formula from the epoch type Combine
formula math formula to execute, all operators which Igor can grok are allowed sweep current sweep (aka step) fp parsed formula structure, with shorthands replaced by stimsets, empty on parse error, ready to be executed by WB_FillWaveFromFormula() 0 on success, 1 on parse errors (currently not many are found)
References ASSERT, COLS, ControlWindowToFront, CountSubstrings, FormulaProperties::formula, InitFormulaProperties, MAX_COMMANDLINE_LENGTH, FormulaProperties::numCols, FormulaProperties::numRows, ROWS, FormulaProperties::stimsetList, WB_CreateAndGetStimSet, WB_FormulaSwitchToStimset, WB_PrepareFormulaForExecute.
Referenced by WB_FillWaveFromFormula.
variable WB_FormulaSwitchToStimset(string formula, FormulaProperties *fp)
Replace shorthands with the real stimset names suffixed with ?
References ASSERT, FormulaProperties::formula, GetWBEpochCombineList, InitFormulaProperties, isEmpty, ROWS, SearchWordInString, FormulaProperties::stimsetList.
Referenced by WB_ParseCombinerFormula, WBP_TranslateControlContents.
static variable WB_PrepareFormulaForExecute(FormulaProperties *fp, variable sweep)
Add wave ranges to every stimset (location marked by ?) and add a left hand side to the formula.
References FormulaProperties::formula.
Referenced by WB_ParseCombinerFormula.
string WB_FormulaSwitchToShorthand(string formula)
Replace all stimsets suffixed with ? by their shorthands.
References FormulaProperties::formula, GetWBEpochCombineList, isEmpty, ROWS.
Referenced by WB_FillWaveFromFormula, WBP_TranslateControlContents.
wave WB_CustomWavesFromStimSet(string stimsetList=defaultValue)
Get all custom waves that are used by the supplied stimset.
used by WaveBuilder and NeuroDataWithoutBorders a wave of wave references
References ROWS, FormulaProperties::stimsetList, WB_CustomWavesPathFromStimSet, WB_UpgradeCustomWaves.
Referenced by NWB_AppendStimset, WB_StimsetNeedsUpdate.
wave WB_CustomWavesPathFromStimSet(string stimsetList=defaultValue)
Get all custom waves that are used by the supplied stimset.
a text wave with paths to custom waves.
References ASSERT, EPOCH_TYPE_CUSTOM, GetSegmentTypeWave, GetWaveBuilderWaveTextParam, ROWS, FormulaProperties::stimsetList, WB_GetSegWvTypeForSet, WB_GetWaveTextParamForSet, WB_TOTAL_NUMBER_OF_EPOCHS.
Referenced by AB_LoadCustomWaves, NWB_LoadCustomWaves, WB_CustomWavesFromStimSet.
static wave WB_UpgradeCustomWaves(string stimsetList=defaultValue)
Try to upgrade all epochs with custom waves from the stimsetlist.
you can only use this function if the custom wave is present in the current experiment. do not try to upgrade when loading stimsets. The custom waves have to be loaded first. a text wave with paths to custom waves.
References ASSERT, CHANNEL_TYPE_UNKNOWN, EPOCH_TYPE_CUSTOM, GetSegmentTypeWave, GetStimSetType, GetWaveBuilderWaveTextParam, ROWS, FormulaProperties::stimsetList, WB_GetSegWvTypeForSet, WB_GetWaveTextParamForSet, WBP_GetStimulusType.
Referenced by WB_CustomWavesFromStimSet.
static string WB_StimsetChildren(string stimset=defaultValue)
Search for stimsets in formula epochs.
a stimset (parent) can depend on other stimsets (child) non-unique list of all (child) stimsets
References ASSERT, CountSubstrings, EPOCH_TYPE_CUSTOM, FormulaProperties::formula, GetSegmentTypeWave, GetWaveBuilderWaveParam, GetWaveBuilderWaveTextParam, ROWS, SearchStringBase, WB_GetSegWvTypeForSet, WB_GetWaveParamForSet, WB_GetWaveTextParamForSet, WB_ParameterWavesExist.
Referenced by WB_StimsetFamilyNames.
variable WB_StimsetFamilyNames(string *knownNames, string *parent=defaultValue)
Get children of current parent stimset.
parent [optional: defaults to current WB panel] specify parent stimset. knownNames unique list of stimsets number of parents stimsets that were moved to child stimsets
References GetUniqueTextEntriesFromList, WB_StimsetChildren.
Referenced by AB_LoadStimsets, NWB_LoadStimsets, WB_StimsetRecursion.
string WB_StimsetRecursion(string parent=defaultValue, string knownStimsets=defaultValue)
Recursively descents into parent stimsets.
You can not recurse into a stimset that depends on itself. list of stimsets that derive from the input stimset
References WB_StimsetFamilyNames, WB_StimsetRecursion.
Referenced by WB_GetStimSet, WB_SaveStimSet, WB_StimsetNeedsUpdate, WB_StimsetRecursion, WB_StimsetRecursionForList.
string WB_StimsetRecursionForList(string stimsetQueue)
Recursively descents into parent stimsets.
stimsetQueue can be a list of stimsets (separated by ;) or a simple string list of stimsets that derive from the input stimsets
References GetUniqueTextEntriesFromList, FormulaProperties::stimsetList, WB_StimsetRecursion.
Referenced by NWB_AppendStimset, NWB_LoadCustomWaves.
variable WB_ParameterWavesExist(string stimset)
check if parameter waves exist
1 if parameter waves exist, 0 otherwise
References WB_GetSegWvTypeForSet, WB_GetWaveParamForSet, WB_GetWaveTextParamForSet.
Referenced by AB_LoadStimset, AB_LoadStimsetTemplateWaves, NWB_LoadStimset, WB_StimsetChildren.
variable WB_StimsetExists(string stimset)
check if (custom) stimset exists
1 if stimset wave was found, 0 otherwise
References CHANNEL_TYPE_UNKNOWN, GetSetFolder, GetStimSetType.
Referenced by AB_LoadStimset, NWB_LoadStimset.
variable WB_KillParameterWaves(string stimset)
Kill Parameter waves for stimset.
References KillOrMoveToTrash, WB_GetSegWvTypeForSet, WB_GetWaveParamForSet, WB_GetWaveTextParamForSet.
Referenced by AB_LoadStimset, AB_LoadStimsetRAW, DAP_DeleteStimulusSet, NWB_LoadStimset.
variable WB_KillStimset(string stimset)
Kill (custom) stimset.
References CHANNEL_TYPE_UNKNOWN, GetSetFolder, GetStimSetType, KillOrMoveToTrash.
Referenced by AB_LoadStimset, AB_LoadStimsetRAW, DAP_DeleteStimulusSet, NWB_LoadStimset.
variable WB_StimsetIsFromThirdParty(string stimset)
Determine if the stimset is third party or from MIES.
Third party stimsets don't have all parameter waves true if from third party, false otherwise
References ASSERT, IsEmpty, WB_GetSegWvTypeForSet, WB_GetWaveParamForSet, WB_GetWaveTextParamForSet.
Referenced by EP_CollectEpochInfo, NWB_WriteStimsetTemplateWaves, WB_CreateAndGetStimSet, WB_MakeStimsetThirdParty.
variable WB_AddAnalysisParameterIntoWPT(WaveText WPT, string name, variable var=defaultValue, string str=defaultValue, wave wv=defaultValue)
Internal use only.
References AFH_GetListOfAnalysisParamNames, AFH_IsValidAnalysisParameter, AFH_IsValidAnalysisParamType, ASSERT, INDEP_EPOCH_TYPE, IsTextWave, NumericWaveToList, ROWS, TextWaveToList.
Referenced by AFH_AddAnalysisParameter, UpgradeWaveTextParam, WBP_ButtonProc_AddParam.
variable WB_SetAnalysisFunctionGeneric(variable stimulusType, string analysisFunction, WaveText WPT)
Internal use only.
References CHANNEL_TYPE_DAC, INDEP_EPOCH_TYPE, NONE.
Referenced by ST_SetStimsetParameter, WBP_AnaFuncsToWPT.
string WB_SaveStimSet(string baseName, variable stimulusType, wave SegWvType, wave WP, WaveText WPT, variable setNumber, variable saveAsBuiltin)
References AFH_CheckAnalysisParameter, ASSERT, ControlWindowToFront, DAP_UpdateDaEphysStimulusSetPopups, GetSetParamFolder, INDEP_EPOCH_TYPE, IsEmpty, CheckParametersStruct::params, ST_RemoveStimSet, STIMSET_PARAM_SEGWVTYPE, STIMSET_PARAM_WP, STIMSET_PARAM_WPT, WB_AssembleSetName, WB_CreateAndGetStimSet, WB_StimsetRecursion, WB_UpdateEpochCombineList, WBP_IsBuiltinStimset.
Referenced by ST_CreateStimSet, WBP_ButtonProc_SaveSet.
string WB_SerializeStimulusType(variable stimulusType)
References ASSERT, CHANNEL_TYPE_DAC, CHANNEL_TYPE_TTL.
Referenced by WB_AssembleSetName.
variable WB_ParseStimulusType(string stimulusType)
References ASSERT, CHANNEL_TYPE_DAC, CHANNEL_TYPE_TTL.
Referenced by WB_SplitStimsetName, WBP_GetStimulusType.
string WB_AssembleSetName(string basename, variable stimulusType, variable setNumber, string suffix=defaultValue)
Return the name of a stimulus set build up from the passed parts.
References MAX_OBJECT_NAME_LENGTH_IN_BYTES_SHORT, WB_SerializeStimulusType.
Referenced by WB_SaveStimSet.
variable WB_SplitStimsetName(string setName, string *setPrefix, variable *stimulusType, variable *setNumber)
Split the full setname into its three parts: prefix, stimulusType and set number.
Counterpart to WB_AssembleSetName()
References CHANNEL_TYPE_UNKNOWN, WB_ParseStimulusType.
Referenced by GetStimSetType, WBP_LoadSet.
variable WB_MakeStimsetThirdParty(string setName)
Changes an existing stimset to a third party stimset.
References ASSERT, IsEmpty, KillOrMoveToTrash, WB_CreateAndGetStimSet, WB_GetSegWvTypeForSet, WB_GetWaveParamForSet, WB_GetWaveTextParamForSet, WB_StimsetIsFromThirdParty.