MIES_AnalysisBrowser_SweepBrowser.ipf
static wave SB_GetSweepBrowserMapFromGraph(string win)
References GetSweepBrowserMap, SB_GetSweepBrowserFolder.
Referenced by SB_AddSweepToGraph, SB_GetChannelInfoFromGraph, SB_GetIndexFromSweepDataPath, SB_GetListOfExperiments, SB_GetLogbookWave, SB_GetPlainSweepList, SB_GetSweepList, SB_GetSweepPropertyFromNumLBN, SB_TranslateSBMapIndexToABMapIndex.
dfref SB_GetSweepBrowserFolder(string win)
References BSP_GetFolder, MIES_BSP_PANEL_FOLDER.
Referenced by BSP_ButtonProc_RestoreData, BSP_UpdateSweepNote, OVS_GetSweepAndExperiment, SB_GetSweepBrowserMapFromGraph, SB_SweepBrowserWindowHook, SB_UpdateSweepPlot, SBE_ExportSweepBrowser, WB_OpenStimulusSetInWaveBuilder.
variable SB_TranslateSBMapIndexToABMapIndex(string win, variable sbIndex)
References ASSERT, COLS, GetAnalysisBrowserMap, SB_GetSweepBrowserMapFromGraph.
Referenced by WB_OpenStimulusSetInWaveBuilder.
static dfref SB_GetSweepDataPathFromIndex(dfref sweepBrowserDFR, variable mapIndex)
References GetSweepBrowserMap, IsFinite, ROWS.
Referenced by SB_GetChannelInfoFromGraph.
variable SB_GetIndexFromSweepDataPath(string win, dfref dataDFR)
References ASSERT, ExtractSweepNumber, FindIndizes, GetRowIndex, IsFinite, ROWS, SB_GetSweepBrowserMapFromGraph, ZapNaNs.
Referenced by OVS_IgnoreHeadstageInOverlay, WB_OpenStimulusSetInWaveBuilder.
static variable SB_SetUserData(string win)
set graph userdata similar to DB_SetUserData()
win name of main window or external subwindow in SweepBrowser
References BSP_SetFolder, MIES_BSP_PANEL_FOLDER, UniqueDataFolder.
Referenced by SB_OpenSweepBrowser.
static wave SB_GetSweepPropertyFromNumLBN(string graph, variable mapIndex, string key)
Return numeric labnotebook entries.
graph sweep browser graph mapIndex index into the sweep browser map, equal to the index into the popup menu (0-based) key labnotebook key wave with the setting for each headstage or an invalid wave reference if the setting does not exist
References DATA_ACQUISITION_MODE, GetAnalysLBNumericalValues, GetLastSetting, IsFinite, ROWS, SB_GetSweepBrowserMapFromGraph.
Referenced by SB_GetChannelInfoFromGraph.
string SB_GetListOfExperiments(string graph)
Return a list of experiments from which the sweeps in the sweep browser graph originated from.
graph sweep browser name
References GetNumberFromWaveNote, NOTE_INDEX, SB_GetSweepBrowserMapFromGraph.
Referenced by LBV_GetExperiments.
wave SB_GetChannelInfoFromGraph(string graph, string channel, string experiment=defaultValue)
Return a text wave with information about the channel waves of the sweep browser graph of all or a specific experiment.
The returned textwave will have multiple columns with different information on each wave. Rows: One entry for each wave Columns: 0: channel number 1: absolute path to the wave 2: headstage embed:rst:leading-asterisk * .. code-block:: igorpro * * variable channelNumber, headstage, numWaves, i * string graph = "SweepBrowser1" // name of an existing sweep browser graph * string channel = "DA" * WAVE/T wv = SB_GetChannelInfoFromGraph(graph, channel) * * numWaves = DimSize(wv, ROWS) * for(i = 0; i < numWaves; i += 1) * WAVE data = $(wv[i][%path]) * channelNumber = str2num(wv[i][%channel]) * headstage = str2num(wv[i][%headstage]) * * printf "Channel %d acquired by headstage %d is stored in %s\r", channelNumber, headstage, NameOfWave(data) * endfor * graph name of main window or external subwindow in SweepBrowser channel type of the channel, one of XOP_CHANNEL_NAMES experiment [optional, defaults to all] name of the experiment the channel wave should originate from
References ASSERT, COLS, EnsureLargeEnoughWave, FindIndizes, GetBaseName, GetListOfObjects, GetNumberFromWaveNote, IsEmpty, IsFinite, MINIMUM_WAVE_SIZE, NOTE_INDEX, RemovePrefix, ROWS, SB_GetSweepBrowserMapFromGraph, SB_GetSweepDataPathFromIndex, SB_GetSweepPropertyFromNumLBN, XOP_CHANNEL_NAMES.
variable SB_UpdateSweepPlot(string win)
References AR_UpdateTracesIfReq, ASSERT, BSP_FetchSelectedChannels, BSP_GatherTiledGraphSettings, BSP_GetNotebookSubWindow, BSP_GetSweepControlsPanel, BSP_UpdateSweepNote, CreateTiledChannelGraph, DATA_SWEEP_BROWSER_PANEL_VERSION, DataFolderExistsDFR, DoAbortNow, GetAnalysisConfigWave, GetAnalysisSweepPath, GetAnalysLBNumericalValues, GetAnalysLBTextualValues, GetAxesRanges, GetAxisLabelCacheWave, GetCursorInfos, GetMainWindow, GetPopupMenuIndex, GetSweepBrowserMap, HasPanelLatestVersion, OVS_GetSelectedSweeps, OVS_SWEEP_SELECTION_INDEX, POST_PLOT_FULL_UPDATE, PostPlotTransformations, RemoveFreeAxisFromGraph, RemoveTracesFromGraph, RestoreCursors, ROWS, SB_GetSweepBrowserFolder, SetAxesRanges, TUD_Clear.
Referenced by UpdateSweepPlot.
variable SB_AddToSweepBrowser(dfref sweepBrowser, string fileName, string dataFolder, string device, variable sweep)
References EnsureLargeEnoughWave, GetNumberFromWaveNote, GetRowWithSameContent, GetSweepBrowserMap, IsFinite, NOTE_INDEX, SetNumberInWaveNote.
Referenced by AB_LoadFromExpandedRange, AB_LoadFromFile.
variable SB_SweepBrowserWindowHook(WMWinHookStruct *s)
References GetMainWindow, KillOrMoveToTrash, SB_GetSweepBrowserFolder.
dfref SB_OpenSweepBrowser()
References AddVersionToPanel, BSP_GetFolder, BSP_InitPanel, BSP_ScaleAxes, BSP_SetSweepBrowser, DATA_SWEEP_BROWSER_PANEL_VERSION, GetCurrentWindow, GetMainWindow, GetSweepBrowserMap, MIES_BSP_PANEL_FOLDER, SB_SetUserData, SWEEPBROWSER_WINDOW_TITLE.
Referenced by AB_ButtonProc_LoadSweeps.
string SB_GetSweepList(string win)
References COLS, GetBaseName, GetFileSuffix, GetNumberFromWaveNote, GetUniqueEntries, NOTE_INDEX, ROWS, SB_GetSweepBrowserMapFromGraph.
wave SB_GetPlainSweepList(string win)
Returns a numeric wave with all sweep numbers.
Can contain duplicates!
References GetNumberFromWaveNote, NOTE_INDEX, SB_GetSweepBrowserMapFromGraph.
Referenced by BSP_UpdateSweepControls, GetPlainSweepList, SB_PopupMenuSelectSweep.
wave SB_GetLogbookWave(string win, variable logbookType, variable logbookWaveType, variable sweepNumber=defaultValue, string dataFolder=defaultValue, string device=defaultValue)
Generic getter for the labnotebook waves.
LBT_LABNOTEBOOK: Use case 1 ( only): No optional parameters given: Returns a wave reference wave with all labnotebook waves from all displayed sweeps, ordered by index Use case 2 (LBT_LABNOTEBOOK only): sweepNumber given: Return the labnotebook wave of that sweep only Use case 3: dataFolder and device given: Return the labnotebook for the given nwb/pxp data folder and device combination LBT_RESULTS: Return one of the four results waves from the given nwb/pxp data folder win panel logbookType one of LogbookTypes logbookWaveType one of LabnotebookWaveTypes sweepNumber [optional] sweep number dataFolder [optional] nwb/pxp data folder (aka experiment) device [optional] device of the experiment valid labnotebook wave or a null wave in case it does not exist
References ASSERT, FindIndizes, GetAnalysisResultsWave, GetNumberFromWaveNote, LBN_NUMERICAL_KEYS, LBN_NUMERICAL_VALUES, LBN_TEXTUAL_KEYS, LBN_TEXTUAL_VALUES, LBT_LABNOTEBOOK, LBT_RESULTS, NOTE_INDEX, SB_GetSweepBrowserMapFromGraph.
Referenced by BSP_GetLogbookWave.
variable SB_PopupMenuSelectSweep(WMPopupAction *pa)
References CHECKBOX_SELECTED, OVS_ChangeSweepSelectionState, OVS_IsActive, SB_GetPlainSweepList, SetSetVariable, UpdateSweepPlot.
variable SB_ButtonProc_ExportTraces(WMButtonAction *ba)
References GetMainWindow, SBE_ShowExportPanel.
variable SB_AddSweepToGraph(string win, variable index)
References AR_UpdateTracesIfReq, ASSERT, BSP_FetchSelectedChannels, BSP_GatherTiledGraphSettings, CreateTiledChannelGraph, GetAnalysisConfigWave, GetAnalysisSweepPath, GetAnalysLBNumericalValues, GetAnalysLBTextualValues, GetAxisLabelCacheWave, GetMainWindow, GetNextTraceIndex, SB_GetSweepBrowserMapFromGraph.
Referenced by AddSweepToGraph.