MIES_LogbookViewer.ipf
const string LABNOTEBOOK_BOTTOM_AXIS_DELTA_TIME
Referenced by LBV_SetLabNotebookBottomLabel.
const string LABNOTEBOOK_BOTTOM_AXIS_TIME
Referenced by LBV_SetLabNotebookBottomLabel.
const string LABNOTEBOOK_BOTTOM_AXIS_SWEEP
Referenced by LBV_SetLabNotebookBottomLabel.
const string LBV_UD_VALUES_WAVE
Referenced by LBV_GetTraceUserDataNames, LBV_SwitchLBGraphXAxis.
const string LBV_UD_KEYS_WAVE
Referenced by LBV_EntryDescription, LBV_GetTraceUserDataNames.
const string LBV_UD_HEADSTAGE
Referenced by LBV_GetTraceUserDataNames, LBV_UpdateLBGraphLegend.
const string LBV_UD_KEY
Referenced by LBV_EntryDescription, LBV_GetTraceUserDataNames, LBV_UpdateTagsForTextualLBNEntries.
const string LBV_UD_ISTEXT
Referenced by LBV_GetTraceUserDataNames, LBV_SwitchLBGraphXAxis, LBV_UpdateLBGraphLegend, LBV_UpdateTagsForTextualLBNEntries.
const string LBV_UD_YAXIS
Referenced by LBV_EntryDescription, LBV_GetTraceUserDataNames.
string LBV_GetSettingsHistoryPanel(string win)
References EXT_PANEL_SETTINGSHISTORY, GetMainWindow.
Referenced by BSP_DynamicSettingsHistory, BSP_DynamicStartupSettings, BSP_GetLogbookWave, BSP_UnHideSettingsHistory, BSP_UnsetDynamicSettingsHistory, BSP_UnsetDynamicStartupSettingsOfDataBrowser, DB_ResetAndStoreCurrentDBPanel, LBV_CloseSettingsHistoryHook, LBV_GetAllDevicesForExperiment, LBV_GetDescriptionNotebook, LBV_GetLabNoteBookGraph, LBV_GetTPStorageLocation, LBV_LimitXRangeToSelected, LBV_PlotAllAnalysisFunctionLBNKeys, LBV_SelectExperimentAndDevice.
string LBV_GetLabNoteBookGraph(string win)
References LBV_GetSettingsHistoryPanel.
Referenced by BSP_InitPanel, LBV_ButtonProc_SwitchXAxis, LBV_ClearGraph, LBV_EntryDescription, LBV_LimitXRangeToSelected, LBV_PopMenuProc_LabNotebookAndResults, LBV_PopMenuProc_TPStorage.
string LBV_GetDescriptionNotebook(string win)
References LBV_GetSettingsHistoryPanel.
Referenced by DB_ResetAndStoreCurrentDBPanel, LBV_ClearGraph, LBV_EntryDescription.
static wave LBV_PopupExtFormatEntries(WaveTextOrNull entries)
References PEXT_GenerateSubMenuNames, PEXT_SplitToSubMenus, PEXT_SUBSPLIT_ALPHA.
Referenced by LBV_PopupExtGetLBKeys, LBV_PopupExtGetResultsKeys, LBV_PopupExtGetTPStorageKeys.
wave LBV_PopupExtGetTPStorageKeys(string win)
Returns the list of TPStorage keys.
References DataFolderExistsDFR, LBV_GetTPStorageEntries, LBV_GetTPStorageLocation, LBV_PopupExtFormatEntries.
wave LBV_PopupExtGetLBKeys(string win)
Returns the list of LNB keys for the settings history window menu.
References BSP_GetLogbookWave, BSP_HasBoundDevice, LBN_NUMERICAL_KEYS, LBN_TEXTUAL_KEYS, LBT_LABNOTEBOOK, LBV_GetAllLogbookKeys, LBV_PopupExtFormatEntries.
wave LBV_PopupExtGetResultsKeys(string win)
Returns the list of results keys for the settings history window menu.
References BSP_GetLogbookWave, BSP_HasBoundDevice, LBN_NUMERICAL_KEYS, LBN_TEXTUAL_KEYS, LBT_RESULTS, LBV_GetAllLogbookKeys, LBV_PopupExtFormatEntries.
static wave LBV_GetAllLogbookKeys(WaveTextOrNull textualKeys, WaveTextOrNull numericalKeys)
Returns the combined keys from the numerical and textual MD key loogbook waves as 1D text wave.
References GetSetUnion, LBV_GetLogbookKeys.
Referenced by LBV_PlotAllAnalysisFunctionLBNKeys, LBV_PopupExtGetLBKeys, LBV_PopupExtGetResultsKeys.
static wave LBV_GetLogbookKeys(WaveTextOrNull keyWave)
Return a wave with all keys in the logbook key wave.
References GetSetDifference, LABNOTEBOOK_KEYS_INITIAL, ROWS.
Referenced by LBV_GetAllLogbookKeys.
wave LBV_GetTPStorageEntries(dfref dfr)
Return a text wave with all entries from all TPStorage waves which are candidates for plotting.
References GetListOfObjects, GetSetIntersection, GrepTextWave, LAYERS, TP_STORAGE_REGEXP.
Referenced by LBV_PopupExtGetTPStorageKeys.
static dfref LBV_GetTPStorageLocation(string win)
Return the datafolder reference where TPStorage waves can be found.
References BSP_GetDevice, BSP_HasBoundDevice, BSP_IsDataBrowser, GetAnalysisDeviceTestpulse, GetDeviceTestPulse, GetPopupMenuString, LBV_GetSettingsHistoryPanel, NONE.
Referenced by LBV_PopMenuProc_TPStorage, LBV_PopupExtGetTPStorageKeys, LBV_SwitchLBGraphXAxis.
variable LBV_CloseSettingsHistoryHook(WMWinHookStruct *s)
panel close hook for settings history panel
References ASSERT, BSP_IsDataBrowser, BSP_MainPanelButtonToggle, GetMainWindow, LBV_GetSettingsHistoryPanel.
variable LBV_ButtonProc_ClearGraph(WMButtonAction *ba)
References LBV_ClearGraph.
variable LBV_ButtonProc_SwitchXAxis(WMButtonAction *ba)
References LBV_GetLabNoteBookGraph, LBV_SwitchLBGraphXAxis.
variable LBV_PopMenuProc_LabNotebookAndResults(WMPopupAction *pa)
References LBV_AddTraceToLBGraph, LBV_GetLabNoteBookGraph, LBV_GetLogbookWavesForEntry, NONE.
Referenced by LBV_PlotAllAnalysisFunctionLBNKeys.
std::tuple< WAVE, WAVE > LBV_GetLogbookWavesForEntry(string win, string key)
Return the keys/values logbook pair for the given key.
valid waves or null if it can not be found.
References ASSERT, BSP_GetLogbookWave, COLS, LBN_NUMERICAL_KEYS, LBN_NUMERICAL_VALUES, LBN_TEXTUAL_KEYS, LBN_TEXTUAL_VALUES, LBT_LABNOTEBOOK, LBT_RESULTS.
Referenced by LBV_PopMenuProc_LabNotebookAndResults.
variable LBV_PopMenuProc_TPStorage(WMPopupAction *pa)
References LBV_AddTraceToLBGraphTPStorage, LBV_GetLabNoteBookGraph, LBV_GetTPStorageLocation, NONE.
string LBV_GetExperiments(string win)
References BSP_IsDataBrowser, GetExperimentName, NONE, SB_GetListOfExperiments.
Referenced by LBV_SelectExperimentAndDevice.
string LBV_GetAllDevicesForExperiment(string win)
References BSP_GetDevice, BSP_HasBoundDevice, BSP_IsDataBrowser, GetAnalysisDeviceWave, GetNumberFromWaveNote, GetPopupMenuString, LBV_GetSettingsHistoryPanel, NONE, NOTE_INDEX, TextWaveToList.
Referenced by LBV_SelectExperimentAndDevice.
variable LBV_ClearGraph(string win)
References LBV_GetDescriptionNotebook, LBV_GetLabNoteBookGraph, LBV_UpdateLBGraphLegend, RemoveDrawLayers, RemoveFreeAxisFromGraph, RemoveTracesFromGraph, ReplaceNotebookText, TUD_Clear, WindowExists.
Referenced by DB_ResetAndStoreCurrentDBPanel, LBV_ButtonProc_ClearGraph.
static variable LBV_UpdateLBGraphLegend(string graph, string traceList=defaultValue)
Update the legend in the labnotebook graph.
Passing traceList is required if you just added traces to the graph as these can not be immediately queried using TraceNameList as that would require an DoUpdate call before. Assumes that the traceList displays information from the labnotebook. All entries with indizes equal or higher than NUM_HEADSTAGES will be labeled as all denoting that the information is headstage independent and therefore valid for all headstages. graph name of the graph traceList list of traces in the graph
References IsEmpty, IsFinite, LBV_UD_HEADSTAGE, LBV_UD_ISTEXT, NUM_HEADSTAGES, RemoveEndingRegExp, TUD_GetUserData.
Referenced by LBV_AddTraceToLBGraph, LBV_AddTraceToLBGraphTPStorage, LBV_ClearGraph, LBV_SwitchLBGraphXAxis.
static wave LBV_GetTraceUserDataNames()
References LBV_UD_HEADSTAGE, LBV_UD_ISTEXT, LBV_UD_KEY, LBV_UD_KEYS_WAVE, LBV_UD_VALUES_WAVE, LBV_UD_YAXIS.
Referenced by LBV_AddTraceToLBGraph, LBV_AddTraceToLBGraphTPStorage.
static string LBV_MakeTraceNameUnique(string graph, string trace)
References TUD_TraceIsOnGraph, UniqueTraceName.
Referenced by LBV_AddTraceToLBGraph, LBV_AddTraceToLBGraphTPStorage.
static variable LBV_AddTraceToLBGraph(string graph, wave keys, wave values, string key)
Add a trace to the labnotebook graph.
graph name of the graph keys labnotebook keys wave (numerical or text) values labnotebook values wave (numerical or text) key name of the key to add
References ASSERT, EquallySpaceAxis, ExtractLogbookSliceEmpty, ExtractLogbookSliceSweep, ExtractLogbookSliceTimeStamp, GetHeadstageColor, GetLogbookType, GetNextFreeAxisName, GetSweepColumn, isEmpty, IsTextWave, LABNOTEBOOK_BINARY_UNIT, LABNOTEBOOK_LAYER_COUNT, LBT_LABNOTEBOOK, LBT_RESULTS, LBV_AddTagsForTextualLBNEntries, LBV_CheckIfXAxisIsTime, LBV_GetPropertiesForLabnotebookEntry, LBV_GetTraceUserDataNames, LBV_MakeTraceNameUnique, LBV_SetLabNotebookBottomLabel, LBV_UpdateLBGraphLegend, NUM_HEADSTAGES, TUD_SetUserDataFromWaves, VERT_AXIS_BASE_NAME.
Referenced by LBV_PopMenuProc_LabNotebookAndResults.
variable LBV_Update(string win)
References LBV_LimitXRangeToSelected.
Referenced by PostPlotTransformations.
variable LBV_UpdateTagsForTextualLBNEntries(string win, variable sweepNo)
References ASSERT, DB_GetLBNWave, IsEmpty, LBN_TEXTUAL_KEYS, LBN_TEXTUAL_VALUES, LBV_AddTagsForTextualLBNEntries, LBV_UD_ISTEXT, LBV_UD_KEY, TUD_GetUserData.
Referenced by DB_UpdateToLastSweep.
static variable LBV_AddTraceToLBGraphTPStorage(string graph, dfref dfr, string key, variable isTimeAxis=defaultValue)
References AFH_GetHeadstageFromActiveADC, ASSERT, BSP_GetChannelSelectionWave, BSP_GetLogbookWave, BUG, COLS, EquallySpaceAxis, ExtractLogbookSliceTimeStamp, FindIndizes, GetHeadstageColor, GetLastSetting, GetListOfObjects, GetNextFreeAxisName, IsEmpty, IsFinite, IsNaN, LAYERS, LBN_NUMERICAL_VALUES, LBT_LABNOTEBOOK, LBV_CheckIfXAxisIsTime, LBV_GenerateTraceNames, LBV_GetTraceUserDataNames, LBV_MakeTraceNameUnique, LBV_SetLabNotebookBottomLabel, LBV_UpdateLBGraphLegend, NUM_DA_TTL_CHANNELS, NUM_HEADSTAGES, PROP_NON_EMPTY, TEST_PULSE_MODE, TextWaveToList, TP_STORAGE_REGEXP, TUD_GetUserDataAsWave, TUD_SetUserDataFromWaves, VERT_AXIS_BASE_NAME.
Referenced by LBV_PopMenuProc_TPStorage, LBV_SwitchLBGraphXAxis.
static std::tuple< WaveTextOrNull, string, string, variable > LBV_GetPropertiesForLabnotebookEntry(WaveText keys, string key)
References LABNOTEBOOK_LAYER_COUNT, LBN_GetEntryProperties, LBV_GenerateTraceNames.
Referenced by LBV_AddTagsForTextualLBNEntries, LBV_AddTraceToLBGraph.
static std::tuple< WaveText, string > LBV_GenerateTraceNames(string name, variable count)
References LineBreakingIntoPar, MAX_OBJECT_NAME_LENGTH_IN_BYTES.
Referenced by LBV_AddTraceToLBGraphTPStorage, LBV_GetPropertiesForLabnotebookEntry.
static variable LBV_AddTagsForTextualLBNEntries(string graph, WaveText keys, WaveText values, string key, variable firstSweep=defaultValue)
References ExtractLogbookSliceSweep, ExtractLogbookSliceTimeStamp, GetHeadstageColor, GetNumberFromWaveNote, GetSweepColumn, IsEmpty, IsFinite, LABNOTEBOOK_LAYER_COUNT, LAYERS, LBV_CheckIfXAxisIsTime, LBV_GetPropertiesForLabnotebookEntry, NOTE_INDEX.
Referenced by LBV_AddTraceToLBGraph, LBV_UpdateTagsForTextualLBNEntries.
static variable LBV_SwitchLBGraphXAxis(string graph)
Switch the labnotebook graph x axis type (time <-> sweep numbers)
References ASSERT, DataFolderExistsDFR, ExtractLogbookSliceSweep, ExtractLogbookSliceTimeStamp, GetLogbookType, GetSweepColumn, GetUniqueTextEntriesFromList, isEmpty, LBT_LABNOTEBOOK, LBT_RESULTS, LBT_TPSTORAGE, LBV_AddTraceToLBGraphTPStorage, LBV_CheckIfXAxisIsTime, LBV_GetTPStorageLocation, LBV_LimitXRangeToSelected, LBV_SetLabNotebookBottomLabel, LBV_UD_ISTEXT, LBV_UD_VALUES_WAVE, LBV_UpdateLBGraphLegend, RemoveTracesFromGraph, TUD_GetUserData, TUD_RemoveUserData.
Referenced by LBV_ButtonProc_SwitchXAxis.
static variable LBV_CheckIfXAxisIsTime(string graph)
Check if the x wave belonging to the first trace in the graph has a date/time scale. Returns false if no traces have been found.
References GetPlainSweepList, isEmpty.
Referenced by LBV_AddTagsForTextualLBNEntries, LBV_AddTraceToLBGraph, LBV_AddTraceToLBGraphTPStorage, LBV_LimitXRangeToSelected, LBV_SwitchLBGraphXAxis.
static variable LBV_SetLabNotebookBottomLabel(string graph, variable isTimeAxis)
Set the appropriate label for the bottom axis of the graph created by CreateTiledChannelGraph.
Assumes that wave data units are equal for all traces
References LABNOTEBOOK_BOTTOM_AXIS_DELTA_TIME, LABNOTEBOOK_BOTTOM_AXIS_SWEEP, LABNOTEBOOK_BOTTOM_AXIS_TIME.
Referenced by LBV_AddTraceToLBGraph, LBV_AddTraceToLBGraphTPStorage, LBV_SwitchLBGraphXAxis.
variable LBV_SelectExperimentAndDevice(string win)
References DisableControl, LBV_GetAllDevicesForExperiment, LBV_GetExperiments, LBV_GetSettingsHistoryPanel, SetPopupMenuIndex.
Referenced by AB_ButtonProc_LoadSweeps.
static string LBV_FormatDescription(WaveTextOrNull keys, string name)
References COLS, IsEmpty, ROWS.
Referenced by LBV_EntryDescription.
variable LBV_EntryDescription(WMWinHookStruct *s)
References ASSERT, AXIS_ORIENTATION_LEFT, GetAxisOrientation, GetNumFromModifyStr, IsEmpty, LBV_FormatDescription, LBV_GetDescriptionNotebook, LBV_GetLabNoteBookGraph, LBV_UD_KEY, LBV_UD_KEYS_WAVE, LBV_UD_YAXIS, ReflowNotebookText, ReplaceNotebookText, TUD_GetUserDataAsWave.
variable LBV_PlotAllAnalysisFunctionLBNKeys(string browser, variable anaFuncType)
References BSP_GetLogbookWave, ControlWindowToFront, CreateAnaFuncLBNKey, GetSetDifference, GrepTextWave, LBN_NUMERICAL_KEYS, LBN_TEXTUAL_KEYS, LBT_LABNOTEBOOK, LBV_GetAllLogbookKeys, LBV_GetSettingsHistoryPanel, LBV_PopMenuProc_LabNotebookAndResults, ROWS, STIMSET_SCALE_FACTOR_KEY.
static variable LBV_LimitXRangeToSelected(string browser)
Limit the bottom axis of the settings history graph to the selected/displayed sweeps.
References ASSERT, BSP_GetLogbookWave, BSP_GetSweepControlsPanel, DATA_ACQUISITION_MODE, GetCheckBoxState, GetLastSettingIndep, GetSetVariable, IsFinite, IsNaN, LBN_NUMERICAL_VALUES, LBT_LABNOTEBOOK, LBV_CheckIfXAxisIsTime, LBV_GetLabNoteBookGraph, LBV_GetSettingsHistoryPanel, OVS_GetSelectedSweeps, OVS_SWEEP_SELECTION_SWEEPNO, TUD_GetTraceCount, WaveMinAndMaxWrapper.
Referenced by LBV_CheckProc_XRangeSelected, LBV_SwitchLBGraphXAxis, LBV_Update.
variable LBV_CheckProc_XRangeSelected(WMCheckboxAction *cba)
References LBV_LimitXRangeToSelected.