MIES_AnalysisFunctions_PatchSeq.ipf
const double PSQ_BL_PRE_PULSE
Referenced by PSQ_EvaluateBaselineProperties.
const double PSQ_BL_POST_PULSE
Referenced by PSQ_EvaluateBaselineProperties.
const double PSQ_RMS_SHORT_TEST
Referenced by PSQ_EvaluateBaselineProperties.
const double PSQ_RMS_LONG_TEST
Referenced by PSQ_EvaluateBaselineProperties.
const double PSQ_TARGETV_TEST
Referenced by PSQ_EvaluateBaselineProperties.
const double PSQ_LEAKCUR_TEST
Referenced by PSQ_EvaluateBaselineProperties.
const double PSQ_DEFAULT_SAMPLING_MULTIPLIER
Referenced by PSQ_Chirp.
const double PSQ_RHEOBASE_DURATION
Referenced by PSQ_DS_GetDAScaleOffset.
static variable PSQ_GetPulseSettingsForType(variable type, PSQ_PulseSettings *s)
Fills s according to the analysis function type.
References ASSERT, DEBUGPRINT, PSQ_PulseSettings::postPulseChunkLength, PSQ_PulseSettings::prePulseChunkLength, PSQ_BL_EVAL_RANGE, PSQ_CHIRP, PSQ_DA_SCALE, PSQ_DS_PULSE_DUR, PSQ_PIPETTE_BATH, PSQ_RAMP, PSQ_RHEOBASE, PSQ_PulseSettings::pulseDuration.
Referenced by PSQ_EvaluateBaselineProperties.
static wave PSQ_GetPulseDurations(string device, variable type, variable sweepNo, variable totalOnsetDelay, variable forceRecalculation=defaultValue)
Return the pulse durations from the labnotebook or calculate them before if required in ms. For convenience unused headstages will have 0 instead of NaN in the returned wave. We recalculate the durations on every sweep again as we can not assume that it is constant for the whole stimulus set.
References CreateAnaFuncLBNKey, ED_AddEntryToLabnotebook, GetLastSetting, GetLBNumericalValues, IsNaN, PSQ_DeterminePulseDuration, PSQ_FMT_LBN_PULSE_DUR, UNKNOWN_MODE.
Referenced by PSQ_Chirp, PSQ_EvaluateBaselineProperties, PSQ_GetNumberOfChunks, PSQ_Ramp.
static wave PSQ_DeterminePulseDuration(string device, variable sweepNo, variable type, variable totalOnsetDelay)
Determine the pulse duration on each headstage.
Returns the labnotebook wave as well.
References AFH_ExtractOneDimDataFromSweep, ASSERT, CHANNEL_TYPE_HEADSTAGE, DAG_GetChannelState, DATA_ACQUISITION_MODE, GetConfigWave, GetDAQConfigWave, GetDAQDataWave, GetMachineEpsilon, GetSweepWave, LABNOTEBOOK_LAYER_COUNT, NUM_HEADSTAGES, PSQ_CHIRP, ROWS, XOP_CHANNEL_TYPE_DAC.
Referenced by PSQ_DAScale, PSQ_GetPulseDurations.
static std::tuple< variable, variable > PSQ_GetBaselineRMSThresholds(string params)
Return the baseline RMS short/long thresholds in mV.
References AFH_GetAnalysisParamNumerical, PSQ_RMS_LONG_THRESHOLD, PSQ_RMS_SHORT_THRESHOLD.
Referenced by PSQ_EvaluateBaselineProperties.
static variable PSQ_StoreRMSThresholdsInLabnotebook(string device, variable type, variable sweepNo, variable headstage, variable rmsShortThreshold, variable rmsLongThreshold)
References CreateAnaFuncLBNKey, ED_AddEntryToLabnotebook, LABNOTEBOOK_LAYER_COUNT, PSQ_FMT_LBN_RMS_LONG_THRESHOLD, PSQ_FMT_LBN_RMS_SHORT_THRESHOLD.
Referenced by PSQ_EvaluateBaselineProperties.
static variable PSQ_EvaluateBaselinePassed(string device, variable type, variable sweepNo, variable headstage, variable chunk, variable ret)
References ANALYSIS_FUNC_RET_EARLY_STOP, CreateAnaFuncLBNKey, DEBUGPRINT, ED_AddEntryToLabnotebook, LABNOTEBOOK_BINARY_UNIT, LABNOTEBOOK_LAYER_COUNT, PSQ_FMT_LBN_BL_QC_PASS, ToPassFail.
Referenced by PSQ_Chirp, PSQ_DAScale, PSQ_PipetteInBath, PSQ_Ramp, PSQ_Rheobase.
static std::tuple< variable, variable > PSQ_EvaluateBaselineChunks(string device, variable type, AnalysisFunction_V3 *s)
References ASSERT, DAG_GetNumericalValue, GetValDisplayAsNum, IsNaN, AnalysisFunction_V3::lastKnownRowIndex, AnalysisFunction_V3::lastValidRowIndex, PSQ_BL_FAILED, PSQ_CHIRP, PSQ_EvaluateBaselineProperties, PSQ_GetNumberOfChunks, PSQ_PIPETTE_BATH, ROWS, AnalysisFunction_V3::sweepNo.
Referenced by PSQ_Chirp, PSQ_DAScale, PSQ_PipetteInBath, PSQ_Ramp, PSQ_Rheobase.
static variable PSQ_EvaluateBaselineProperties(string device, AnalysisFunction_V3 *s, variable type, variable chunk, variable fifoInStimsetTime, variable totalOnsetDelay)
Evaluate one chunk of the baseline.
device device s AnalysisFunction_V3 struct type analysis function type, one of PatchSeqAnalysisFunctionTypes chunk chunk number, chunk == 0 -> Pre pulse baseline chunk, chunk >= 1 -> Post pulse baseline fifoInStimsetTime Fifo position in ms relative to the start of the stimset (therefore ignoring the totalOnsetDelay) totalOnsetDelay total onset delay in ms pre pulse baseline: 0 if the chunk passes, one of the possible AnalysisFuncReturnTypesConstants values otherwise post pulse baseline: 0 if the chunk passes, PSQ_BL_FAILED if it does not pass
References AFH_GetADCFromHeadstage, AFH_GetAnalysisParamNumerical, AFH_GetDACFromHeadstage, AFH_GetDAQDataColumn, ANALYSIS_FUNC_RET_EARLY_STOP, ANALYSIS_FUNC_RET_REPURP_TIME, ASSERT, CHANNEL_CONTROL_UNIT, CHANNEL_TYPE_ADC, CHANNEL_TYPE_HEADSTAGE, CreateAnaFuncLBNKey, DAG_GetChannelState, DAG_GetNumericalValue, DAG_GetTextualValue, DEBUGPRINT, ED_AddEntryToLabnotebook, EP_AddUserEpoch, GetDAQConfigWave, GetLastSettingIndep, GetLBNumericalValues, GetLBTextualValues, GetOverrideResults, GetSpecialControlLabel, HasOneValidEntry, INDEP_HEADSTAGE, IsFinite, LABNOTEBOOK_BINARY_UNIT, LABNOTEBOOK_LAYER_COUNT, NUM_HEADSTAGES, AnalysisFunction_V3::params, PSQ_PulseSettings::postPulseChunkLength, PSQ_PulseSettings::prePulseChunkLength, PSQ_BASELINE_CHUNK_SHORT_NAME_PREFIX, PSQ_BL_FAILED, PSQ_BL_POST_PULSE, PSQ_BL_PRE_PULSE, PSQ_CALC_METHOD_AVG, PSQ_CALC_METHOD_RMS, PSQ_Calculate, PSQ_CHIRP, PSQ_FMT_LBN_CHUNK_PASS, PSQ_FMT_LBN_LEAKCUR, PSQ_FMT_LBN_LEAKCUR_PASS, PSQ_FMT_LBN_RMS_LONG_PASS, PSQ_FMT_LBN_RMS_SHORT_PASS, PSQ_FMT_LBN_TARGETV, PSQ_FMT_LBN_TARGETV_PASS, PSQ_GetBaselineRMSThresholds, PSQ_GetPulseDurations, PSQ_GetPulseSettingsForType, PSQ_LEAKCUR_TEST, PSQ_PIPETTE_BATH, PSQ_RAMP, PSQ_RHEOBASE, PSQ_RMS_LONG_TEST, PSQ_RMS_SHORT_TEST, PSQ_StoreRMSThresholdsInLabnotebook, PSQ_TARGETV_TEST, PSQ_TARGETV_THRESHOLD, PSQ_PulseSettings::pulseDuration, AnalysisFunction_V3::scaledDACWave, AnalysisFunction_V3::sweepNo, TestOverrideActive, ToPassFail, UNKNOWN_MODE, XOP_CHANNEL_TYPE_ADC, XOP_CHANNEL_TYPE_DAC.
Referenced by PSQ_EvaluateBaselineChunks.
static variable PSQ_GetNumberOfChunks(string device, variable sweepNo, variable headstage, variable type)
Return the number of chunks.
A chunk is PSQ_BL_EVAL_RANGE [ms] of baseline. For calculating the number of chunks we ignore the one chunk after the pulse which we don't evaluate!
References ASSERT, DAG_GetNumericalValue, DATA_ACQUISITION_MODE, DEBUGPRINTv, GetDAQDataWave, GetValDisplayAsNum, PSQ_BL_EVAL_RANGE, PSQ_CHIRP, PSQ_DA_SCALE, PSQ_DS_PULSE_DUR, PSQ_GetPulseDurations, PSQ_PB_GetPrePulseBaselineDuration, PSQ_PIPETTE_BATH, PSQ_RAMP, PSQ_RHEOBASE, ROWS.
Referenced by PSQ_CreateOverrideResults, PSQ_EvaluateBaselineChunks.
static variable PSQ_Calculate(wave wv, variable column, variable startTime, variable rangeTime, variable method)
References ASSERT, IsFinite, PSQ_CALC_METHOD_AVG, PSQ_CALC_METHOD_RMS, ROWS.
Referenced by PSQ_EvaluateBaselineProperties.
static variable PSQ_NumAcquiredSweepsInSet(string device, variable sweepNo, variable headstage)
Return the number of already acquired sweeps from the given stimset cycle.
References AFH_GetSweepsFromSameSCI, GetLBNumericalValues, ROWS.
Referenced by PSQ_Chirp, PSQ_DAScale, PSQ_PipetteInBath, PSQ_Ramp.
variable PSQ_NumPassesInSet(wave numericalValues, variable type, variable sweepNo, variable headstage)
Return the number of passed sweeps in all sweeps from the given stimset cycle.
References AFH_GetSweepsFromSameSCI, CreateAnaFuncLBNKey, GetLastSettingIndep, PSQ_FMT_LBN_SWEEP_PASS, ROWS, UNKNOWN_MODE.
Referenced by AD_GetDAScaleFailMsg, AD_GetPerSweepFailMessage, PSQ_Chirp, PSQ_DAScale, PSQ_PipetteInBath, PSQ_Ramp, PSQ_SquarePulse.
static variable PSQ_GetDAStimsetLength(string device, variable headstage)
Return the DA stimset length in ms of the given headstage.
stimset length or -1 on error
References AFH_GetDACFromHeadstage, AFH_GetStimSetName, CHANNEL_TYPE_DAC, ROWS, WB_CreateAndGetStimSet.
Referenced by PSQ_Chirp, PSQ_DAScale, PSQ_Ramp, PSQ_Rheobase.
wave PSQ_CreateOverrideResults(string device, variable headstage, variable type)
Create the overrides results wave for CI testing.
PSQ_SQUARE_PULSE: Rows: x position in ms where the spike is in each sweep/step For convenience the values 0 always means no spike and 1 spike detected (at the appropriate position). PSQ_RHEOBASE/PSQ_RAMP: Rows: chunk indizes Cols: sweeps/steps Layers: 0: 1 if the chunk has passing baseline QC or not 1: x position in ms where the spike is in each sweep/step For convenience the values 0 always means no spike and 1 spike detected (at the appropriate position). Chunks (only for layer 0): 0: RMS short baseline QC 1: RMS long baseline QC 2: target voltage baseline QC 3: leak current baseline QC PSQ_DA_SCALE: Rows: chunk indizes Cols: sweeps/steps Layers: 0: 1 if the chunk has passing baseline QC or not 1: x position in ms where the spike is in each sweep/step For convenience the values 0 always means no spike and 1 spike detected (at the appropriate position). 2: Number of spikes Chunks (only for layer 0): 0: RMS short baseline QC 1: RMS long baseline QC 2: target voltage baseline QC 3: leak current baseline QC PSQ_CHIRP: Rows: chunk indizes Cols: sweeps/steps Layers: 0: 1 if the chunk has passing baseline QC or not 1: maximum of AD data in chirp region [first row only, others are ignored], use NaN to use the real values 2: minimum of AD data in chirp region [first row only, others are ignored], use NaN to use the real values 3: passing spike check in chirp region or not [first row only, others are ignored] Chunks (only for layer 0): 0: RMS short baseline QC 1: RMS long baseline QC 2: target voltage baseline QC 3: leak current baseline QC PSQ_PIPETTE_BATH: Rows: chunk indizes Cols: sweeps/steps Layers: 0: 1 if the chunk has passing baseline QC or not 1: averaged steady state resistance [MOhm] Chunks (only for layer 0): 0: RMS short baseline QC 1: RMS long baseline QC 2: target voltage baseline QC 3: leak current baseline QC
References AFH_GetDACFromHeadstage, AFH_GetStimSetName, ASSERT, CHANNEL_TYPE_DAC, IDX_NumberOfSweepsInSet, PSQ_CHIRP, PSQ_DA_SCALE, PSQ_GetNumberOfChunks, PSQ_PIPETTE_BATH, PSQ_RAMP, PSQ_RHEOBASE, PSQ_SQUARE_PULSE, WB_CreateAndGetStimSet.
static variable PSQ_StoreStepSizeInLBN(string device, variable type, variable sweepNo, variable stepsize, variable future=defaultValue)
Store the step size in the labnotebook.
References CreateAnaFuncLBNKey, ED_AddEntryToLabnotebook, INDEP_HEADSTAGE, LABNOTEBOOK_LAYER_COUNT, PSQ_FMT_LBN_STEPSIZE, PSQ_FMT_LBN_STEPSIZE_FUTURE.
Referenced by PSQ_Rheobase, PSQ_SquarePulse.
static wave PSQ_SearchForSpikes(string device, variable type, wave sweepWave, variable headstage, variable offset, variable level, variable searchEnd=defaultValue, variable numberOfSpikesReq=defaultValue, wave spikePositions=defaultValue, variable *numberOfSpikesFound=defaultValue)
Search the AD channel of the given headstage for spikes from the pulse onset until the end of the sweep or searchEnd if given.
device device type One of PatchSeqAnalysisFunctionTypes sweepWave sweep wave with acquired data headstage headstage in the range [0, NUM_HEADSTAGES[ offset offset in ms where the spike search should start, commonly the totalOnsetDelay level set the level for the spike search searchEnd [optional, defaults to inf] total length in ms of the spike search, relative to sweepWave start numberOfSpikesReq [optional, defaults to one] number of spikes to look for Positive finite value: Return value is 1 iff at least numberOfSpikes were found Inf: Return value is 1 if at least 1 spike was found spikePositions [optional] returns the position of the first numberOfSpikes found on success in ms numberOfSpikesFound [optional] returns the number of spikes found labnotebook value wave suitable for ED_AddEntryToLabnotebook()
References AFH_ExtractOneDimDataFromSweep, ASSERT, DATA_ACQUISITION_MODE, DEBUGPRINT, DEBUGPRINTw, GAIN_AFTER_DAQ, GetConfigWave, GetDAQConfigWave, GetDAQDataWave, GetMachineEpsilon, GetOverrideResults, IsFinite, LABNOTEBOOK_LAYER_COUNT, PA_SpikePositionsForNonVC, PSQ_CHIRP, PSQ_DA_SCALE, PSQ_RAMP, PSQ_RHEOBASE, PSQ_SQUARE_PULSE, ROWS, SWS_GetChannelGains, TestOverrideActive, WaveMinAndMaxWrapper, XOP_CHANNEL_TYPE_ADC, XOP_CHANNEL_TYPE_DAC.
Referenced by PSQ_Chirp, PSQ_DAScale, PSQ_Ramp, PSQ_Rheobase, PSQ_SquarePulse.
static variable PSQ_GetLastPassingLongRHSweep(string device, variable headstage, variable duration)
Return a sweep number of an existing sweep matching the following conditions.
Acquired with Rheobase analysis function Set QC passed for this SCI Pulse duration was longer than duration Spiked And as usual we want the last matching sweep. existing sweep number or -1 in case no such sweep could be found
References AFH_GetSweepsFromSameSCI, ASSERT, CreateAnaFuncLBNKey, GetLastSetting, GetLastSettingIndep, GetLastSettingSCI, GetLBNumericalValues, GetSweepsWithSetting, PSQ_FMT_LBN_PULSE_DUR, PSQ_FMT_LBN_SET_PASS, PSQ_FMT_LBN_SPIKE_DETECT, PSQ_RHEOBASE, ROWS, UNKNOWN_MODE.
Referenced by PSQ_DS_GetDAScaleOffset.
static variable PSQ_GetLastPassingDAScaleSub(string device, variable headstage)
Return the sweep number of the last sweep using the PSQ_DaScale() analysis function, where the set passes and was in subthreshold mode.
References CreateAnaFuncLBNKey, GetLastSettingIndep, GetLastSettingTextSCI, GetLBNumericalValues, GetLBTextualValues, GetSweepsWithSetting, INDEP_HEADSTAGE, PSQ_DA_SCALE, PSQ_DS_SUB, PSQ_FMT_LBN_DA_OPMODE, PSQ_FMT_LBN_SET_PASS, ROWS, UNKNOWN_MODE.
Referenced by PSQ_Chirp.
variable PSQ_DS_GetDAScaleOffset(string device, variable headstage, string opMode)
Return the DAScale offset for PSQ_DaScale()
DAScale value in pA or NaN on error
References ASSERT, DATA_ACQUISITION_MODE, GetLastSetting, GetLBNumericalValues, IsValidSweepNumber, PSQ_DS_OFFSETSCALE_FAKE, PSQ_DS_SUB, PSQ_DS_SUPRA, PSQ_GetLastPassingLongRHSweep, PSQ_RHEOBASE_DURATION, STIMSET_SCALE_FACTOR_KEY, TestOverrideActive.
Referenced by PSQ_DAScale.
variable PSQ_FoundAtLeastOneSpike(string device, variable sweepNo)
Check if the given sweep has at least one "spike detected" entry in the labnotebook.
1 if found at least one, zero if none and NaN if no such entry could be found
References CreateAnaFuncLBNKey, GetLastSetting, GetLBNumericalValues, PSQ_FMT_LBN_SPIKE_DETECT, PSQ_RAMP, UNKNOWN_MODE.
Referenced by PSQ_Ramp.
static variable PSQ_GetDefaultSamplingFrequency(variable type)
References ASSERT, PSQ_CHIRP, PSQ_DA_SCALE, PSQ_PIPETTE_BATH, PSQ_RAMP, PSQ_RHEOBASE, PSQ_SQUARE_PULSE.
Referenced by PSQ_CheckSamplingFrequencyAndStoreInLabnotebook, PSQ_GetHelpCommon.
variable PSQ_GetDefaultSamplingFrequencyForSingleHeadstage(string device)
Returns the sampling frequency in kHz of our supported NI and ITC hardware for one active headstage and no TTL channels.
References ASSERT, GetHardwareType, HARDWARE_ITC_DAC, HARDWARE_NI_DAC.
Referenced by PSQ_CheckSamplingFrequencyAndStoreInLabnotebook.
static variable PSQ_CheckSamplingFrequencyAndStoreInLabnotebook(string device, variable type, AnalysisFunction_V3 *s)
Return the QC state of the sampling interval/frequency check and store it also in the labnotebook.
References AFH_GetAnalysisParamNumerical, ASSERT, CheckIfClose, CreateAnaFuncLBNKey, ED_AddEntryToLabnotebook, INDEP_HEADSTAGE, LABNOTEBOOK_BINARY_UNIT, LABNOTEBOOK_LAYER_COUNT, AnalysisFunction_V3::params, PSQ_FMT_LBN_SAMPLING_PASS, PSQ_GetDefaultSamplingFrequency, PSQ_GetDefaultSamplingFrequencyForSingleHeadstage, ROWS, AnalysisFunction_V3::scaledDACWave, AnalysisFunction_V3::sweepNo.
Referenced by PSQ_Chirp, PSQ_DAScale, PSQ_PipetteInBath, PSQ_Ramp, PSQ_Rheobase, PSQ_SquarePulse.
static string PSQ_GetHelpCommon(variable type, string name)
References ASSERT, PSQ_GetDefaultSamplingFrequency, PSQ_RMS_LONG_THRESHOLD, PSQ_RMS_SHORT_THRESHOLD.
Referenced by PSQ_Chirp_GetHelp, PSQ_DAScale_GetHelp, PSQ_PipetteInBath_GetHelp, PSQ_Ramp_GetHelp, PSQ_Rheobase_GetHelp, PSQ_SquarePulse_GetHelp.
static string PSQ_CheckParamCommon(string name, string params)
References AFH_GetAnalysisParamNumerical, ASSERT, IsValidSamplingMultiplier.
Referenced by PSQ_Chirp_CheckParam, PSQ_DAScale_CheckParam, PSQ_PipetteInBath_CheckParam, PSQ_Ramp_CheckParam, PSQ_Rheobase_CheckParam, PSQ_SquarePulse_CheckParam.
string PSQ_DAScale_GetParams()
Require parameters from stimset.
string PSQ_DAScale_GetHelp(string name)
References ASSERT, PSQ_DA_SCALE, PSQ_GetHelpCommon.
string PSQ_DAScale_CheckParam(string name, CheckParametersStruct *s)
References AFH_GetAnalysisParamNumerical, AFH_GetAnalysisParamTextual, AFH_GetAnalysisParamWave, ASSERT, IsNaN, CheckParametersStruct::params, PSQ_CheckParamCommon, PSQ_DS_SUB, PSQ_DS_SUPRA.
variable PSQ_DAScale(string device, AnalysisFunction_V3 *s)
Patch Seq Analysis function to find a suitable DAScale.
Prerequisites: Does only work for one headstage Assumes that the stimset has 500ms of pre pulse baseline, a 1000ms (PSQ_DS_PULSE_DUR) pulse and at least 1000ms post pulse baseline. Each 500ms (PSQ_BL_EVAL_RANGE) of the baseline is a chunk Testing: For testing the spike detection logic, the results can be defined in the override wave, PSQ_CreateOverrideResults(). Reading the results from the labnotebook: embed:rst:leading-asterisk * .. code-block:: igorpro * * WAVE numericalValues = GetLBNumericalValues(device) * * // set properties * * key = CreateAnaFuncLBNKey(PSQ_DA_SCALE, PSQ_FMT_LBN_SET_PASSED, query = 1) * setPassed = GetLastSettingIndepSCI(numericalValues, sweepNo, key, headstage, UNKNOWN_MODE) * * if(setPassed) * // set passed * else * // set did not pass * endif * * // single sweep properties * key = CreateAnaFuncLBNKey(PSQ_DA_SCALE, PSQ_FMT_LBN_SWEEP_PASS, query = 1) * sweepPassed = GetLastSettingIndep(numericalValues, sweepNo, key, UNKNOWN_MODE) * * // chunk (500ms portions of the baseline) properties * key = CreateAnaFuncLBNKey(PSQ_DA_SCALE, PSQ_FMT_LBN_CHUNK_PASS, chunk = chunk, query = 1) * chunkPassed = GetLastSettingIndep(numericalValues, sweepNo, key, UNKNOWN_MODE) * * // single test properties * key = CreateAnaFuncLBNKey(PSQ_DA_SCALE, PSQ_FMT_LBN_RMS_SHORT_PASS, chunk = chunk, query = 1) * rmsShortPassed = GetLastSettingIndep(numericalValues, sweepNo, key, UNKNOWN_MODE) * key = CreateAnaFuncLBNKey(PSQ_DA_SCALE, PSQ_FMT_LBN_RMS_LONG_PASS, chunk = chunk, query = 1) * rmsLongPassed = GetLastSettingIndep(numericalValues, sweepNo, key, UNKNOWN_MODE) * key = CreateAnaFuncLBNKey(PSQ_DA_SCALE, PSQ_FMT_LBN_TARGETV_PASS, chunk = chunk, query = 1) * targetVPassed = GetLastSettingIndep(numericalValues, sweepNo, key, UNKNOWN_MODE) * * // get fitted resistance from last passing sweep * // resistance for the first headstage can be found in resistanceFitted[0] * WAVE/Z resistanceFitted = GetLastSettingSCI(numericalValues, sweepNo, LABNOTEBOOK_USER_PREFIX + "ResistanceFromFit", headstage, UNKNOWN_MODE) * Decision logic flowchart: embed:rst:leading-asterisk * .. image:: /dot/patch-seq-dascale.svg * /// /// Sketch of a stimset with inserted TP, pre pulse baseline (-), pulse (*), and post pulse baseline (-). /// /// |-| *********************************** /// | | | | /// | | | \WWW/ | /// | | | / \ | /// | | | /wwwww\ | /// | | | _| o_o |_ | /// | | | \WWWWWWW/ (_ / \ _) | /// | | | _/` o_o `\_ | \_/ | | /// | | | (_ (_) _) : ~~~~~ : | /// | | | \ '-...-' / \_____/ | /// | | | (`'-----'`) [ ] | /// | | | `"""""""` `"""""` | /// | | | | /// -| |-----------------| |-------------------------------------------- /// /// ascii art image from: http://ascii.co.uk/art/erniebert /// ///
References AD_UpdateAllDatabrowser, AFH_GetAnalysisParamNumerical, AFH_GetAnalysisParamTextual, AFH_GetAnalysisParamWave, ASSERT, AssertOnAndClearRTError, CalculateTPLikePropsFromSweep, CHANNEL_TYPE_HEADSTAGE, CHANNEL_TYPE_TTL, CheckIfSmall, ClearRTError, ControlWindowToFront, CreateAnaFuncLBNKey, DAG_GetChannelState, DAG_GetHeadstageMode, DAG_GetNumericalValue, DATA_ACQUISITION_MODE, DEBUGPRINT, DisableControls, ED_AddEntryToLabnotebook, EnableControls, AnalysisFunction_V3::eventType, FitResistance, FloatWithMinSigDigits, GetAnalysisFuncDAScaleDeltaI, GetAnalysisFuncDAScaleDeltaV, GetAnalysisFuncDAScaleFreqFit, GetAnalysisFuncDAScaleRes, GetAnalysisFuncDAScales, GetAnalysisFuncDAScaleSpikeFreq, GetAnalysisFuncIndexingHelper, GetLastSetting, GetLastSettingEachSCI, GetLastSettingIndepEachSCI, GetLBNumericalValues, GetLBTextualValues, GetSweepWave, GetValDisplayAsNum, I_CLAMP_MODE, IDX_NumberOfSweepsInSet, INDEP_HEADSTAGE, IsFinite, IsNaN, KillOrMoveToTrash, LABNOTEBOOK_BINARY_UNIT, LABNOTEBOOK_LAYER_COUNT, MID_SWEEP_EVENT, NUM_HEADSTAGES, AnalysisFunction_V3::params, PGC_SetAndActivateControl, POST_DAQ_EVENT, POST_SET_EVENT, POST_SWEEP_EVENT, PRE_DAQ_EVENT, PRE_SET_EVENT, PSQ_BL_EVAL_RANGE, PSQ_CheckSamplingFrequencyAndStoreInLabnotebook, PSQ_DA_SCALE, PSQ_DeterminePulseDuration, PSQ_DS_GetDAScaleOffset, PSQ_DS_PULSE_DUR, PSQ_DS_SPIKE_LEVEL, PSQ_DS_SUB, PSQ_DS_SUPRA, PSQ_EvaluateBaselineChunks, PSQ_EvaluateBaselinePassed, PSQ_FMT_LBN_BL_QC_PASS, PSQ_FMT_LBN_DA_fI_SLOPE, PSQ_FMT_LBN_DA_fI_SLOPE_REACHED, PSQ_FMT_LBN_DA_OPMODE, PSQ_FMT_LBN_PULSE_DUR, PSQ_FMT_LBN_SET_PASS, PSQ_FMT_LBN_SPIKE_COUNT, PSQ_FMT_LBN_SPIKE_DETECT, PSQ_FMT_LBN_SWEEP_PASS, PSQ_ForceSetEvent, PSQ_GetDAStimsetLength, PSQ_NumAcquiredSweepsInSet, PSQ_NumPassesInSet, PSQ_SearchForSpikes, PSQ_SetSamplingIntervalMultiplier, PSQ_PulseSettings::pulseDuration, RA_SkipSweeps, ROWS, SetAnalysisFunctionVersion, SetDAScale, SPIKE_FREQ_GRAPH, STIM_WAVE_NAME_KEY, STIMSET_SCALE_FACTOR_KEY, AnalysisFunction_V3::sweepNo, ToPassFail, UNKNOWN_MODE, WindowExists.
string PSQ_SquarePulse_GetParams()
Return a list of required parameters.
string PSQ_SquarePulse_GetHelp(string name)
References ASSERT, PSQ_GetHelpCommon, PSQ_SQUARE_PULSE.
string PSQ_SquarePulse_CheckParam(string name, CheckParametersStruct *s)
References ASSERT, CheckParametersStruct::params, PSQ_CheckParamCommon.
variable PSQ_SquarePulse(string device, AnalysisFunction_V3 *s)
Analysis function to find the smallest DAScale where the cell spikes.
Prerequisites: Does only work for one headstage Assumes that the stimset has a pulse Testing: For testing the spike detection logic, the results can be defined in the override wave, PSQ_CreateOverrideResults(). Decision logic flowchart: embed:rst:leading-asterisk * .. image:: /dot/patch-seq-squarepulse.svg * /// /// Sketch of a stimset with pre pulse baseline (-), pulse (*), and post pulse baseline (-). /// /// ******* /// | | /// | | /// | | /// | | /// | | /// | | /// | | /// | | /// | | /// | | /// | | /// | | /// ---| |-------------------------------------------- /// ///
References AD_UpdateAllDatabrowser, AFH_GetAnalysisParamNumerical, ASSERT, CHANNEL_TYPE_HEADSTAGE, CHANNEL_TYPE_TTL, CheckIfClose, CheckIfSmall, ControlWindowToFront, CreateAnaFuncLBNKey, DAG_GetChannelState, DAG_GetHeadstageMode, DATA_ACQUISITION_MODE, DEBUGPRINT, DisableControls, ED_AddEntryToLabnotebook, EnableControls, AnalysisFunction_V3::eventType, GetLastSetting, GetLastSettingIndepEachSCI, GetLastSettingIndepSCI, GetLBNumericalValues, GetSweepWave, GetTotalOnsetDelay, I_CLAMP_MODE, INDEP_HEADSTAGE, LABNOTEBOOK_BINARY_UNIT, LABNOTEBOOK_LAYER_COUNT, AnalysisFunction_V3::params, PGC_SetAndActivateControl, POST_DAQ_EVENT, POST_SET_EVENT, POST_SWEEP_EVENT, PRE_DAQ_EVENT, PRE_SET_EVENT, PSQ_CheckSamplingFrequencyAndStoreInLabnotebook, PSQ_FMT_LBN_FINAL_SCALE, PSQ_FMT_LBN_SET_PASS, PSQ_FMT_LBN_SPIKE_DASCALE_ZERO, PSQ_FMT_LBN_SPIKE_DETECT, PSQ_FMT_LBN_STEPSIZE, PSQ_FMT_LBN_SWEEP_PASS, PSQ_ForceSetEvent, PSQ_NUM_MAX_DASCALE_ZERO, PSQ_NumPassesInSet, PSQ_SearchForSpikes, PSQ_SetSamplingIntervalMultiplier, PSQ_SP_INIT_AMP_m50, PSQ_SP_INIT_AMP_p10, PSQ_SP_INIT_AMP_p100, PSQ_SPIKE_LEVEL, PSQ_SQUARE_PULSE, PSQ_StoreStepSizeInLBN, RA_SkipSweeps, ROWS, SetAnalysisFunctionVersion, SetDAScale, STIMSET_SCALE_FACTOR_KEY, AnalysisFunction_V3::sweepNo, ToPassFail, UNKNOWN_MODE, ZapNaNs.
string PSQ_Rheobase_GetParams()
Return a list of required parameters.
string PSQ_Rheobase_GetHelp(string name)
References ASSERT, PSQ_GetHelpCommon, PSQ_RHEOBASE.
string PSQ_Rheobase_CheckParam(string name, CheckParametersStruct *s)
References ASSERT, CheckParametersStruct::params, PSQ_CheckParamCommon.
variable PSQ_Rheobase(string device, AnalysisFunction_V3 *s)
Analysis function for finding the exact DAScale value between spiking and non-spiking.
Prerequisites: Does only work for one headstage Assumes that the stimset has a pulse of non-zero and arbitrary length Pre pulse baseline length is PSQ_BL_EVAL_RANGE Post pulse baseline length a multiple of PSQ_BL_EVAL_RANGE Testing: For testing the spike detection logic, the results can be defined in the override wave, PSQ_CreateOverrideResults(). Decision logic flowchart: embed:rst:leading-asterisk * .. image:: /dot/patch-seq-rheobase.svg * /// /// Sketch of a stimset with pre pulse baseline (-), pulse (*), and post pulse baseline (-). /// /// ******* /// | | /// | | /// | | /// | | /// | | /// | | /// | | /// | | /// | | /// | | /// | | /// | | /// ---| |-------------------------------------------- /// ///
References AD_UpdateAllDatabrowser, AFH_GetAnalysisParamNumerical, AFH_GetSweepsFromSameSCI, ASSERT, CHANNEL_TYPE_HEADSTAGE, CHANNEL_TYPE_TTL, CheckIfClose, CheckIfSmall, ControlWindowToFront, CreateAnaFuncLBNKey, DAG_GetChannelState, DAG_GetHeadstageMode, DAG_GetNumericalValue, DATA_ACQUISITION_MODE, DEBUGPRINT, DisableControls, ED_AddEntryToLabnotebook, EnableControls, AnalysisFunction_V3::eventType, GetLastSetting, GetLastSettingEachSCI, GetLastSettingIndep, GetLastSettingIndepSCI, GetLastSettingSCI, GetLastSweepWithSettingIndep, GetLBNumericalValues, GetSweepWave, GetTotalOnsetDelay, I_CLAMP_MODE, INDEP_HEADSTAGE, IsFinite, IsValidSweepNumber, LABNOTEBOOK_BINARY_UNIT, LABNOTEBOOK_LAYER_COUNT, MID_SWEEP_EVENT, AnalysisFunction_V3::params, PGC_SetAndActivateControl, POST_DAQ_EVENT, POST_SET_EVENT, POST_SWEEP_EVENT, PRE_DAQ_EVENT, PRE_SET_EVENT, PSQ_BL_EVAL_RANGE, PSQ_CheckSamplingFrequencyAndStoreInLabnotebook, PSQ_EvaluateBaselineChunks, PSQ_EvaluateBaselinePassed, PSQ_FMT_LBN_BL_QC_PASS, PSQ_FMT_LBN_FINAL_SCALE, PSQ_FMT_LBN_INITIAL_SCALE, PSQ_FMT_LBN_RB_DASCALE_EXC, PSQ_FMT_LBN_RB_LIMITED_RES, PSQ_FMT_LBN_SET_PASS, PSQ_FMT_LBN_SPIKE_DETECT, PSQ_FMT_LBN_STEPSIZE, PSQ_FMT_LBN_STEPSIZE_FUTURE, PSQ_ForceSetEvent, PSQ_GetDAStimsetLength, PSQ_GetFinalDAScaleFake, PSQ_RB_DASCALE_SMALL_BORDER, PSQ_RB_DASCALE_STEP_LARGE, PSQ_RB_DASCALE_STEP_SMALL, PSQ_RB_MAX_DASCALE_DIFF, PSQ_RHEOBASE, PSQ_SearchForSpikes, PSQ_SetSamplingIntervalMultiplier, PSQ_SPIKE_LEVEL, PSQ_SQUARE_PULSE, PSQ_StoreStepSizeInLBN, RA_SkipSweeps, ROWS, SetAnalysisFunctionVersion, SetDAScale, STIMSET_SCALE_FACTOR_KEY, AnalysisFunction_V3::sweepNo, TestOverrideActive, UNKNOWN_MODE.
variable PSQ_GetFinalDAScaleFake()
References ASSERT, GetNumberFromWaveNote, GetOverrideResults, IsFinite, PSQ_RB_FINALSCALE_FAKE_KEY, TestOverrideActive.
Referenced by PSQ_Rheobase.
string PSQ_Ramp_GetParams()
Return a list of required parameters.
string PSQ_Ramp_GetHelp(string name)
References ASSERT, PSQ_GetHelpCommon, PSQ_RAMP.
string PSQ_Ramp_CheckParam(string name, CheckParametersStruct *s)
References AFH_GetAnalysisParamNumerical, ASSERT, CheckParametersStruct::params, PSQ_CheckParamCommon.
variable PSQ_Ramp(string device, AnalysisFunction_V3 *s)
Analysis function for applying a ramp stim set and finding the position were it spikes.
Prerequisites: Does only work for one headstage Assumes that the stimset has a ramp of non-zero and arbitrary length Pre pulse baseline length is PSQ_BL_EVAL_RANGE Post pulse baseline length is at least two times PSQ_BL_EVAL_RANGE Testing: For testing the spike detection logic, the results can be defined in the override wave, PSQ_CreateOverrideResults(). Decision logic flowchart: embed:rst:leading-asterisk * .. image:: /dot/patch-seq-ramp.svg * /// /// Sketch of a stimset with pre pulse baseline (-), ramp (/|), and post pulse baseline (-). /// /// /| /// / | /// / | /// / | /// / | /// / | /// / | /// / | /// / | /// / | /// / | /// / | /// / | /// ---/ |-------------------------------------------- /// ///
References AD_UpdateAllDatabrowser, AFH_GetAnalysisParamNumerical, AFH_GetDACFromHeadstage, AFH_GetStimSetName, ASSERT, CHANNEL_TYPE_DAC, CHANNEL_TYPE_HEADSTAGE, CHANNEL_TYPE_TTL, CheckIfSmall, ControlWindowToFront, CreateAnaFuncLBNKey, DAG_GetChannelState, DAG_GetHeadstageMode, DAG_GetNumericalValue, DATA_ACQUISITION_MODE, DEBUGPRINT, DisableControls, ED_AddEntryToLabnotebook, EnableControls, AnalysisFunction_V3::eventType, GetDAQConfigWave, GetHardwareType, GetLastSetting, GetLBNumericalValues, GetLBTextualValues, GetNIFIFOName, GetValDisplayAsNum, HARDWARE_ITC_DAC, HARDWARE_NI_DAC, HW_ITC_PrepareAcq, HW_NI_StopDAC, HW_NI_ZeroDAC, HW_StartAcq, HW_StopAcq, I_CLAMP_MODE, IDX_NumberOfSweepsInSet, INDEP_HEADSTAGE, IsFinite, IsNaN, LABNOTEBOOK_BINARY_UNIT, LABNOTEBOOK_LAYER_COUNT, AnalysisFunction_V3::lastKnownRowIndex, MID_SWEEP_EVENT, NumericWaveToList, AnalysisFunction_V3::params, PGC_SetAndActivateControl, POST_DAQ_EVENT, POST_SET_EVENT, POST_SWEEP_EVENT, PRE_DAQ_EVENT, PRE_SET_EVENT, PSQ_BL_EVAL_RANGE, PSQ_CheckSamplingFrequencyAndStoreInLabnotebook, PSQ_EvaluateBaselineChunks, PSQ_EvaluateBaselinePassed, PSQ_FMT_LBN_BL_QC_PASS, PSQ_FMT_LBN_SET_PASS, PSQ_FMT_LBN_SPIKE_DETECT, PSQ_FMT_LBN_SPIKE_POSITIONS, PSQ_FMT_LBN_SWEEP_PASS, PSQ_ForceSetEvent, PSQ_FoundAtLeastOneSpike, PSQ_GetDAStimsetLength, PSQ_GetPulseDurations, PSQ_NumAcquiredSweepsInSet, PSQ_NumPassesInSet, PSQ_RA_DASCALE_DEFAULT, PSQ_RA_NUM_SWEEPS_PASS, PSQ_RAMP, PSQ_Ramp_AddEpoch, PSQ_SearchForSpikes, PSQ_SetSamplingIntervalMultiplier, PSQ_SPIKE_LEVEL, PSQ_PulseSettings::pulseDuration, RA_SkipSweeps, AnalysisFunction_V3::rawDACWave, ROWS, SetAnalysisFunctionVersion, SetDAScale, STIM_WAVE_NAME_KEY, AnalysisFunction_V3::sweepNo, TestOverrideActive, TFH_StartFIFOStopDaemon, TFH_StopFIFODaemon, ToPassFail, TS_GetNewestFromThreadQueue, UNKNOWN_MODE.
static variable PSQ_Ramp_AddEpoch(string device, variable headstage, wave wv, string tags, string shortName, variable first, variable last)
References AFH_GetDACFromHeadstage, ASSERT, EP_AddUserEpoch, ROWS, XOP_CHANNEL_TYPE_DAC.
Referenced by PSQ_Ramp.
std::tuple< variable, variable > PSQ_CR_SetHasPassed(wave numericalValues, variable sweepNo, variable headstage)
Determine if we have three passing sweeps with the same DAScale value.
result set passing state (0/1) maxOccurences maximum number of passing sets with the same DASCale value
References ASSERT, CreateAnaFuncLBNKey, DATA_ACQUISITION_MODE, GetLastSettingEachSCI, GetLastSettingIndepEachSCI, PSQ_CHIRP, PSQ_CR_NUM_SWEEPS_PASS, PSQ_FMT_LBN_SWEEP_PASS, ROWS, STIMSET_SCALE_FACTOR_KEY, UNKNOWN_MODE.
Referenced by AD_GetChirpFailMsg, PSQ_Chirp.
static std::tuple< ChirpBoundsInfo > PSQ_CR_DetermineBoundsState(variable baseline, variable minimum, variable maximum, variable value)
Returns the two letter states "AA", "BB" and "BA" for the value and the scaling factors to reach min/center/max.
We need the real baseline value (measured), whereas the center between minimum/maximum would be targetV, which the user entered together with an allowed ± range.
References ASSERT.
Referenced by PSQ_CR_DetermineBoundsAction.
string PSQ_CR_BoundsActionToString(variable boundsAction)
References ASSERT, PSQ_CR_DECREASE, PSQ_CR_INCREASE, PSQ_CR_PASS, PSQ_CR_RERUN.
Referenced by AD_GetPerSweepFailMessage, PSQ_CR_DetermineBoundsAction.
static variable PSQ_CR_DetermineBoundsActionHelper(wave wv, string state, variable action)
References GetNumberFromWaveNote, NOTE_INDEX, ROWS, SetNumberInWaveNote.
Referenced by PSQ_CR_DetermineBoundsActionFromState.
static variable PSQ_CR_DetermineBoundsActionFromState(string upperState, string lowerState)
Returns an action depending on the upper and lower states, see ChirpBoundsAction.
References ASSERT, IsFinite, NOTE_INDEX, PSQ_CR_DECREASE, PSQ_CR_DetermineBoundsActionHelper, PSQ_CR_INCREASE, PSQ_CR_PASS, PSQ_CR_RERUN, SetNumberInWaveNote.
Referenced by PSQ_CR_DetermineBoundsAction.
static variable PSQ_CR_DetermineScalingFactor(ChirpBoundsInfo *lowerInfo, ChirpBoundsInfo *upperInfo, variable boundsEvaluationMode)
Determine the scaling factor for DAScale which is required for being inside the bounds.
References ASSERT, ChirpBoundsInfo::centerFac, PSQ_CR_BEM_DEPOLARIZED, PSQ_CR_BEM_HYPERPOLARIZED, PSQ_CR_BEM_SYMMETRIC.
Referenced by PSQ_CR_DetermineBoundsAction.
static std::tuple< variable, variable > PSQ_CR_DetermineBoundsAction(string device, wave scaledDACWave, variable headstage, variable sweepNo, variable chirpStart, variable cycleEnd, variable innerRelativeBound, variable outerRelativeBound, variable boundsEvaluationMode)
Determine the bounds action given the requested chirp slice.
device device scaledDACWave DAQ data wave with correct units and scaling headstage headstage sweepNo sweep number chirpStart x-position relative to stimset start where the chirp starts cycleEnd x-position relative to stimset start where the requested number of cycles finish innerRelativeBound analysis parameter outerRelativeBound analysis parameter boundsEvaluationMode bounds evaluation mode, one of PSQChirpBoundsEvaluationMode boundsAction, one of ChirpBoundsAction scalingFactorDAScale, scaling factor to be inside the bounds for actions PSQ_CR_INCREASE/PSQ_CR_DECREASE
References AFH_ExtractOneDimDataFromSweep, ASSERT, CreateAnaFuncLBNKey, DAG_GetNumericalValue, DEBUGPRINT, DP_DebuggingEnabledForCaller, ED_AddEntryToLabnotebook, GetDAQConfigWave, GetLastSetting, GetLBNumericalValues, GetValDisplayAsNum, INDEP_HEADSTAGE, IsFinite, IsNaN, LABNOTEBOOK_LAYER_COUNT, PSQ_CHIRP, PSQ_CR_BASELINE_V_FAKE, PSQ_CR_BEM_DEPOLARIZED, PSQ_CR_BEM_HYPERPOLARIZED, PSQ_CR_BEM_SYMMETRIC, PSQ_CR_BoundsActionToString, PSQ_CR_BoundsEvaluationModeToString, PSQ_CR_DECREASE, PSQ_CR_DetermineBoundsActionFromState, PSQ_CR_DetermineBoundsState, PSQ_CR_DetermineScalingFactor, PSQ_CR_INCREASE, PSQ_CR_PASS, PSQ_CR_RERUN, PSQ_FMT_LBN_CR_BOUNDS_ACTION, PSQ_FMT_LBN_CR_BOUNDS_STATE, PSQ_FMT_LBN_TARGETV, TestOverrideActive, UNKNOWN_MODE, WaveMinAndMaxWrapper, XOP_CHANNEL_TYPE_ADC.
Referenced by PSQ_Chirp.
static variable PSQ_CR_GetXPosFromCycles(variable cycle, wave cycleXValues, variable totalOnsetDelay)
Return the x position of the end of the given cycle relative to the stimset start.
References ASSERT, ROWS.
Referenced by PSQ_Chirp.
static wave PSQ_CR_GetCycles(string device, variable sweepNo, wave rawDACWave, variable xstart)
References CreateAnaFuncLBNKey, ED_AddEntryToLabnotebook, GetLastSetting, GetLBTextualValues, PSQ_CHIRP, PSQ_CR_DetermineCycles, PSQ_FMT_LBN_CR_CYCLES, UNKNOWN_MODE.
Referenced by PSQ_Chirp.
static wave PSQ_CR_DetermineCycles(string device, wave rawDACWave, variable xstart)
Find all x values where DA channels have the same value as rawDACWave[xstart].
We search starting from xstart, where matches have a minimum of 1ms between them. device device rawDACWave unscaled DAQDataWave (aka GetHardwareDataWave(device)) xstart position of reference value and starting point for the search Labnotebook entry wave
References AFH_ExtractOneDimDataFromSweep, CHANNEL_TYPE_HEADSTAGE, DAG_GetChannelState, GAIN_AFTER_DAQ, GetDAQConfigWave, LABNOTEBOOK_LAYER_COUNT, NUM_HEADSTAGES, NumericWaveToList, SWS_GetChannelGains, XOP_CHANNEL_TYPE_DAC.
Referenced by PSQ_CR_GetCycles.
static string PSQ_CR_BoundsEvaluationModeToString(variable val)
References ASSERT, PSQ_CR_BEM_DEPOLARIZED, PSQ_CR_BEM_HYPERPOLARIZED, PSQ_CR_BEM_SYMMETRIC.
Referenced by PSQ_CR_DetermineBoundsAction.
static variable PSQ_CR_ParseBoundsEvaluationModeString(string str)
References ASSERT, PSQ_CR_BEM_DEPOLARIZED, PSQ_CR_BEM_HYPERPOLARIZED, PSQ_CR_BEM_SYMMETRIC.
Referenced by PSQ_Chirp.
string PSQ_Chirp_GetHelp(string name)
References ASSERT, PSQ_CHIRP, PSQ_GetHelpCommon.
string PSQ_Chirp_CheckParam(string name, CheckParametersStruct *s)
References AFH_GetAnalysisParamNumerical, AFH_GetAnalysisParamTextual, ASSERT, IDX_NumberOfSweepsInSet, IsFinite, IsInteger, CheckParametersStruct::params, PSQ_CheckParamCommon, PSQ_CR_BEM, PSQ_CR_LIMIT_BAND_HIGH, CheckParametersStruct::setName.
string PSQ_Chirp_GetParams()
Return a list of required analysis functions for PSQ_Chirp()
variable PSQ_Chirp(string device, AnalysisFunction_V3 *s)
Analysis function for determining the impedance of the cell using a sine chirp stim set.
Prerequisites: Does only work for one headstage Assumes that the stimset has a chirp of non-zero and arbitrary length Pre pulse baseline length is PSQ_BL_EVAL_RANGE Post pulse baseline length is at least two times PSQ_BL_EVAL_RANGE Testing: For testing the range detection logic, the results can be defined in the wave root:overrideResults. PSQ_CreateOverrideResults() Decision logic flowchart: embed:rst:leading-asterisk * .. image:: /dot/patch-seq-chirp.svg * The bounds action for Symmetric (Upper and Lower) is derived from the state according to the following sketch: embed:rst:leading-asterisk * .. image:: ../patch-seq-chirp-bounds-state-action.png * * Depolarized (Upper only): * * ======= ========== * State Action * ======= ========== * BA Pass * AA Decrease * BB Increase * ======= ========== * * Hyperpolarized (Lower only): * * ======= ========== * State Action * ======= ========== * BA Pass * AA Increase * BB Decrease * ======= ========== * * /// /// Sketch of a stimset with pre pulse baseline (-), sine chirp (~), and post pulse baseline (-). /// /// /// /// ~ ~ /// ~ ~ ~ ~ /// ~ ~ ~ ~ /// ~ ~ ~ ~ /// ---------------~ ~ ~ ~-------------------------------- /// ~ ~ /// ~ ~ /// ~ /// ///
References AD_UpdateAllDatabrowser, AFH_GetAnalysisParamNumerical, AFH_GetAnalysisParamTextual, AFH_GetDACFromHeadstage, AFH_GetStimSetName, ANALYSIS_FUNC_RET_EARLY_STOP, ASSERT, CHANNEL_TYPE_DAC, CHANNEL_TYPE_HEADSTAGE, CHANNEL_TYPE_TTL, ControlWindowToFront, CreateAnaFuncLBNKey, DAG_GetChannelState, DAG_GetHeadstageMode, DAG_GetNumericalValue, DATA_ACQUISITION_MODE, DEBUGPRINT, DisableControls, ED_AddEntryToLabnotebook, EnableControls, AnalysisFunction_V3::eventType, GetLastSetting, GetLastSettingIndep, GetLastSettingIndepSCI, GetLBNumericalValues, GetLBTextualValues, GetValDisplayAsNum, I_CLAMP_MODE, IDX_NumberOfSweepsInSet, INDEP_HEADSTAGE, IsFinite, IsNaN, IsValidSweepNumber, LABNOTEBOOK_BINARY_UNIT, LABNOTEBOOK_LAYER_COUNT, LABNOTEBOOK_USER_PREFIX, AnalysisFunction_V3::lastKnownRowIndex, ListToNumericWave, MID_SWEEP_EVENT, AnalysisFunction_V3::params, PGC_SetAndActivateControl, POST_DAQ_EVENT, POST_SET_EVENT, POST_SWEEP_EVENT, PRE_DAQ_EVENT, PRE_SET_EVENT, PSQ_BL_EVAL_RANGE, PSQ_CheckSamplingFrequencyAndStoreInLabnotebook, PSQ_CHIRP, PSQ_CR_DECREASE, PSQ_CR_DetermineBoundsAction, PSQ_CR_FindDependentAnalysisParameter, PSQ_CR_GetCycles, PSQ_CR_GetXPosFromCycles, PSQ_CR_INCREASE, PSQ_CR_NUM_SWEEPS_PASS, PSQ_CR_ParseBoundsEvaluationModeString, PSQ_CR_PASS, PSQ_CR_RERUN, PSQ_CR_RESISTANCE_FAKE, PSQ_CR_SetHasPassed, PSQ_CR_SPIKE_CHECK_DEFAULT, PSQ_DEFAULT_SAMPLING_MULTIPLIER, PSQ_EvaluateBaselineChunks, PSQ_EvaluateBaselinePassed, PSQ_FMT_LBN_BL_QC_PASS, PSQ_FMT_LBN_CR_INSIDE_BOUNDS, PSQ_FMT_LBN_CR_RESISTANCE, PSQ_FMT_LBN_CR_SPIKE_CHECK, PSQ_FMT_LBN_CR_SPIKE_PASS, PSQ_FMT_LBN_INITIAL_SCALE, PSQ_FMT_LBN_SET_PASS, PSQ_FMT_LBN_SWEEP_PASS, PSQ_ForceSetEvent, PSQ_GetDAStimsetLength, PSQ_GetLastPassingDAScaleSub, PSQ_GetPulseDurations, PSQ_NumAcquiredSweepsInSet, PSQ_NumPassesInSet, PSQ_SearchForSpikes, PSQ_SetSamplingIntervalMultiplier, RA_SkipSweeps, AnalysisFunction_V3::rawDACWave, ROWS, AnalysisFunction_V3::scaledDACWave, SetAnalysisFunctionVersion, SetDAScale, SetDAScaleModOp, STIM_WAVE_NAME_KEY, AnalysisFunction_V3::sweepNo, TestOverrideActive, ToPassFail, UNKNOWN_MODE.
static variable PSQ_CR_FindDependentAnalysisParameter(string device, string name, string params)
References AFH_GetAnalysisParameter, ControlWindowToFront, IsEmpty.
Referenced by PSQ_Chirp.
static variable PSQ_ForceSetEvent(string device, variable headstage)
Manually force the pre/post set events.
Required to do before skipping sweeps. Todothis hack must go away.
References AFH_GetDACFromHeadstage, GetSetEventFlag, POST_SET_EVENT, PRE_SET_EVENT.
Referenced by PSQ_Chirp, PSQ_DAScale, PSQ_PipetteInBath, PSQ_Ramp, PSQ_Rheobase, PSQ_SquarePulse.
static variable PSQ_SetSamplingIntervalMultiplier(string device, variable multiplier)
References ASSERT, DAG_GetTextualValue, PGC_SetAndActivateControl.
Referenced by PSQ_Chirp, PSQ_DAScale, PSQ_PipetteInBath, PSQ_Ramp, PSQ_Rheobase, PSQ_SquarePulse.
string PSQ_PipetteInBath_CheckParam(string name, CheckParametersStruct *s)
References AFH_GetAnalysisParamNumerical, AFH_GetAnalysisParamTextual, ASSERT, IDX_NumberOfSweepsInSet, IsFinite, IsInteger, CheckParametersStruct::params, PSQ_CheckParamCommon, CheckParametersStruct::setName, WB_CreateAndGetStimSet.
string PSQ_PipetteInBath_GetHelp(string name)
References ASSERT, PSQ_GetHelpCommon, PSQ_PIPETTE_BATH.
string PSQ_PipetteInBath_GetParams()
variable PSQ_PipetteInBath(string device, AnalysisFunction_V3 *s)
Analysis function for determining the pipette resistance while that is located in the bath.
Prerequisites: Does only work for one headstage We expect three epochs per test pulse in the stimset, plus one epoch before all TPs, and at the very end Assumes that the stimset has NumberOfTestpulses test pulses Pre pulse baseline length is PSQ_BL_EVAL_RANGE Post pulse baseline is not evaluated Testing: For testing the range detection logic, the results can be defined in the wave root:overrideResults. PSQ_CreateOverrideResults() Decision logic flowchart: embed:rst:leading-asterisk * .. image:: /dot/patch-seq-pipette-bath.svg * /// /// Sketch of a stimset with three test pulse like epochs /// /// +-----+ +-----+ +-----+ /// | | | | | | /// | | | | | | /// | | | | | | /// -------------------+ +-------+ +-------+ +------------------------ /// /// Epoch borders /// ------------- /// /// | | | | | | | | | | /// /// So for this stimset we have two epochs at the very beginning and end, plus /// three epochs per test pulse and three test pulses, which gives eleven in /// total. /// ///
References AD_UpdateAllDatabrowser, AFH_GetAnalysisParamNumerical, AFH_GetAnalysisParamTextual, AFH_GetDACFromHeadstage, ASSERT, BSP_GetLogbookWave, BSP_GetPanel, BSP_GetSFFormula, BSP_GetSweepControlsPanel, BSP_HasBoundDevice, CHANNEL_CONTROL_WAVE, CHANNEL_TYPE_DAC, CHANNEL_TYPE_HEADSTAGE, CHANNEL_TYPE_TTL, ControlWindowToFront, CreateAnaFuncLBNKey, DAG_GetChannelState, DAG_GetHeadstageMode, DATA_ACQUISITION_MODE, DB_FindDataBrowser, DB_OpenDataBrowser, DEBUGPRINT, DisableControls, ED_AddEntryToLabnotebook, EnableControls, AnalysisFunction_V3::eventType, GetLastSetting, GetLastSettingIndep, GetLastSettingTextIndep, GetLBNumericalValues, GetLBTextualValues, GetOverrideResults, GetPanelControl, IDX_NumberOfSweepsInSet, INDEP_HEADSTAGE, IsEmpty, IsFinite, LABNOTEBOOK_BINARY_UNIT, LABNOTEBOOK_LAYER_COUNT, LBN_TEXTUAL_VALUES, LBT_RESULTS, ListToNumericWave, MID_SWEEP_EVENT, AnalysisFunction_V3::params, PGC_SetAndActivateControl, POST_DAQ_EVENT, POST_SET_EVENT, POST_SWEEP_EVENT, PRE_DAQ_EVENT, PRE_SET_EVENT, PRE_SWEEP_CONFIG_EVENT, PSQ_CheckSamplingFrequencyAndStoreInLabnotebook, PSQ_EvaluateBaselineChunks, PSQ_EvaluateBaselinePassed, PSQ_FMT_LBN_BL_QC_PASS, PSQ_FMT_LBN_LEAKCUR_PASS, PSQ_FMT_LBN_PB_RESISTANCE, PSQ_FMT_LBN_PB_RESISTANCE_PASS, PSQ_FMT_LBN_SET_PASS, PSQ_FMT_LBN_SWEEP_PASS, PSQ_ForceSetEvent, PSQ_NumAcquiredSweepsInSet, PSQ_NumPassesInSet, PSQ_PB_CreateTestpulseEpochs, PSQ_PB_NUM_SWEEPS_PASS, PSQ_PB_Publish, PSQ_PIPETTE_BATH, PSQ_SetSamplingIntervalMultiplier, RA_SkipSweeps, ReplaceNotebookText, ROWS, SetAnalysisFunctionVersion, STIM_WAVE_NAME_KEY, SWEEP_FORMULA_RESULT, AnalysisFunction_V3::sweepNo, TestOverrideActive, ToPassFail, UNKNOWN_MODE, V_CLAMP_MODE.
static variable PSQ_PB_GetPrePulseBaselineDuration(string device, variable headstage)
References AFH_GetDACFromHeadstage, CHANNEL_CONTROL_WAVE, CHANNEL_TYPE_DAC, DAG_GetTextualValue, GetSpecialControlLabel, ST_GetStimsetParameterAsVariable.
Referenced by PSQ_GetNumberOfChunks.
static variable PSQ_PB_CreateTestpulseEpochs(string device, variable headstage)
Create user epochs for the testpulse like shapes in the stimset.
Assumes that all sweeps in the stimset are the same. number of found testpulses
References AFH_GetDACFromHeadstage, ASSERT, CHANNEL_CONTROL_SCALE, CHANNEL_CONTROL_WAVE, CHANNEL_TYPE_DAC, DAG_GetNumericalValue, DAG_GetTextualValue, EP_AddUserEpoch, GetSpecialControlLabel, GetValDisplayAsNum, IsInteger, ST_GetStimsetParameterAsVariable, XOP_CHANNEL_TYPE_DAC.
Referenced by PSQ_PipetteInBath.
static variable PSQ_AddLabnotebookEntriesToJSON(variable jsonID, wave values, wave keys, variable sweepNo, string key, variable headstage, variable labnotebookLayer)
References AFH_GetSweepsFromSameSCI, ASSERT, GetLastSettingEachSCI, GetLastSettingIndepEachSCI, INDEP_HEADSTAGE, IsNumericWave, LBN_GetEntryProperties, ROWS, UNKNOWN_MODE.
Referenced by PSQ_PB_Publish.
static variable PSQ_PB_Publish(string device, variable sweepNo, variable headstage)
Published message in POST_SET_EVENT for the analysis function PSQ_PipetteInBath()
Keys under /results are labnotebook keys. The arrays under /results/XXX/values are the values for each sweep in the stimset cycle. This array has currently always one entry as PSQ_PB_NUM_SWEEPS_PASS is one. The encoding is UTF-8. Example: embed:rst:leading-asterisk * .. code-block:: json * * { * "device": "my_device", * "headstage": 0, * "results": { * "USER_Pipette in Bath Chk0 Leak Current BL": { * "unit": "Amperes", * "value": [ * 123.0 * ] * }, * "USER_Pipette in Bath Chk0 Leak Current BL QC": { * "unit": "On/Off", * "value": [ * 0.0 * ] * }, * "USER_Pipette in Bath Set QC": { * "unit": "On/Off", * "value": [ * 1.0 * ] * }, * "USER_Pipette in Bath pipette resistance": { * "unit": "Ω", * "value": [ * 456.0 * ] * }, * "USER_Pipette in Bath pipette resistance QC": { * "unit": "On/Off", * "value": [ * 1.0 * ] * } * }, * "sweep number": "NaN", * "timestamp": "2022-02-10T20:48:22Z" * } * * .. Output created with Tests/CheckPipetteInBathPublishing. * *
References ANALYSIS_FUNCTION_PB, CreateAnaFuncLBNKey, FFI_GetJSONTemplate, FFI_Publish, GetLBNumericalKeys, GetLBNumericalValues, INDEP_HEADSTAGE, PSQ_AddLabnotebookEntriesToJSON, PSQ_FMT_LBN_LEAKCUR, PSQ_FMT_LBN_LEAKCUR_PASS, PSQ_FMT_LBN_PB_RESISTANCE, PSQ_FMT_LBN_PB_RESISTANCE_PASS, PSQ_FMT_LBN_SET_PASS, PSQ_PIPETTE_BATH.
Referenced by PSQ_PipetteInBath.