MIES_TestPulse_Multi.ipf
const double TPM_NI_TASKTIMEOUT
After this time in s the background task reading data from the ADC device.
will not read multiple TP data sets subsequently to keep up if late it will however still update once per device so the gui thread can update at least every ~0.5 seconds (default value here) however the fifo may run full if the timeout is hit too often
Referenced by TPM_BkrdTPFuncMD.
const double TPM_NI_FIFO_THRESHOLD_SIZE
Referenced by TPM_BkrdTPFuncMD.
variable TPM_StartTPMultiDeviceLow(string device, variable runModifier=defaultValue, variable fast=defaultValue)
Start the test pulse when MD support is activated.
Handles the TP initiation for all DAQ devices. Yoked ITC1600s are handled specially using the external trigger. The external trigger is assumed to be a arduino device using the arduino squencer.
References ASSERT, AssertOnAndClearRTError, ClearRTError, DeviceHasFollower, HARDWARE_DAC_EXTERNAL_TRIGGER, TEST_PULSE_BG_MULTI_DEVICE, TP_Setup, TP_Teardown, TPM_BkrdTPMD.
Referenced by RA_HandleITI_MD, TPM_StartTestPulseMultiDevice.
variable TPM_StartTestPulseMultiDevice(string device, variable fast=defaultValue)
Start a multi device test pulse, always done in background mode.
References DAP_CheckSettings, DQ_STOP_REASON_TP_STARTED, DQ_StopOngoingDAQ, P_InitBeforeTP, TEST_PULSE_MODE, TP_CheckIfTestpulseIsRunning, TPM_StartTPMultiDeviceLow.
Referenced by DAP_ButtonProc_TPDAQ, DAP_OneTimeCallAfterDAQ, TP_RestartTestPulse.
variable TPM_StopTestPulseMultiDevice(string device, variable fast=defaultValue)
Stop the TP on yoked devices simultaneously.
Handles also non-yoked devices in multi device mode correctly.
References DQM_CallFuncForDevicesYoked, TPM_StopTPMD, TPM_StopTPMDFast.
Referenced by DQ_StopOngoingDAQHelper, TP_StopTestPulseWrapper, TPM_BkrdTPFuncMD.
static variable TPM_BkrdTPMD(string device, variable triggerMode=defaultValue)
References GetHardwareType, HARDWARE_ABORT_ON_ERROR, HARDWARE_DAC_DEFAULT_TRIGGER, HARDWARE_ITC_DAC, HARDWARE_NI_DAC, HW_ITC_ResetFifo, HW_StartAcq, IsBackgroundTaskRunning, TASKNAME_TPMD, TFH_StartFIFOResetDeamon, TPM_AddDevice.
Referenced by TPM_StartTPMultiDeviceLow.
variable TPM_BkrdTPFuncMD(BackgroundStruct *s)
Background TP Multi Device.
References ASSERT, AssertOnAndClearRTError, ClearRTError, ControlWindowToFront, BackgroundStruct::count, DEBUG_TIMER_START, DEBUGPRINT, DEBUGPRINT_ELAPSED, DeviceHasFollower, DQ_STOP_REASON_ESCAPE_KEY, DQ_STOP_REASON_HW_ERROR, DQ_StopOngoingDAQ, ESCAPE_KEY, GetActiveDevicesTPMD, GetDAQDataWave, GetNIFIFOName, GetNumberFromWaveNote, HARDWARE_DAC_DEFAULT_TRIGGER, HARDWARE_ITC_DAC, HARDWARE_NI_DAC, HW_GetMainDeviceName, HW_NI_PrepareAcq, HW_NI_StartAcq, HW_NI_StopAcq, IsFinite, LOG_AddEntry, NOTE_INDEX, PACKAGE_MIES, ROWS, SCOPE_UpdateGraph, SCOPE_UpdateOscilloscopeData, TEST_PULSE_MODE, BackgroundStruct::threadDeadCount, TP_MD_THREAD_DEAD_MAX_RETRIES, TPM_NI_FIFO_THRESHOLD_SIZE, TPM_NI_TASKTIMEOUT, TPM_StopTestPulseMultiDevice, TS_GetNewestFromThreadQueue, TS_GetNewestFromThreadQueueMult, BackgroundStruct::wmbs.
Referenced by BWO_CheckAndClearPipettes, BWO_InitParaPipetteClear.
static variable TPM_StopTPMD(string device)
Wrapper for DQM_CallFuncForDevicesYoked()
References TPM_StopTPMDWrapper.
Referenced by TPM_StopTestPulseMultiDevice.
static variable TPM_StopTPMDFast(string device)
Wrapper for DQM_CallFuncForDevicesYoked()
References TPM_StopTPMDWrapper.
Referenced by TPM_StopTestPulseMultiDevice.
static variable TPM_StopTPMDWrapper(string device, variable fast=defaultValue)
References GetHardwareType, HARDWARE_ABORT_ON_ERROR, HARDWARE_ITC_DAC, HARDWARE_PREVENT_ERROR_MESSAGE, HARDWARE_PREVENT_ERROR_POPUP, HW_IsRunning, HW_SelectDevice, HW_StopAcq, TP_Teardown, TPM_HasActiveDevices, TPM_RemoveDevice.
Referenced by TPM_StopTPMD, TPM_StopTPMDFast.
static variable TPM_HasActiveDevices()
References GetActiveDevicesTPMD, GetNumberFromWaveNote, NOTE_INDEX.
Referenced by TPM_StopTPMDWrapper.
static variable TPM_RemoveDevice(string device)
References ASSERT, DEBUGPRINT, GetActiveDevicesTPMD, GetNumberFromWaveNote, NOTE_INDEX, SetNumberInWaveNote.
Referenced by TPM_StopTPMDWrapper.
static variable TPM_AddDevice(string device)
References DEBUGPRINT, EnsureLargeEnoughWave, GetActiveDevicesTPMD, GetHardwareType, GetNumberFromWaveNote, NOTE_INDEX, SetNumberInWaveNote.
Referenced by TPM_BkrdTPMD.