MIES_ThreadedFIFOHandling.ipf
const double TFH_RESTART_ACQ
Mode constants.
DAQ restarting for TP MP
Referenced by TFH_FifoLoop, TFH_StartFIFOResetDeamon.
const double TFH_STOP_ACQ
DAQ stopping.
Referenced by TFH_FifoLoop, TFH_StartFIFOStopDaemon.
const double TIMEOUT_IN_MS
Referenced by TFH_FifoLoop.
variable TFH_StartFIFOResetDeamon(variable hwType, variable deviceID, variable triggerMode)
Start the FIFO reset daemon used for TP MD.
References TFH_RESTART_ACQ, TFH_StartFIFODeamonInternal.
Referenced by TPM_BkrdTPMD.
variable TFH_StartFIFOStopDaemon(variable hwType, variable deviceID)
Start the FIFO stop daemon used for DAQ MD.
References TFH_StartFIFODeamonInternal, TFH_STOP_ACQ.
Referenced by DQM_BkrdDataAcq, PSQ_Ramp.
static variable TFH_StartFIFODeamonInternal(variable hwType, variable deviceID, variable mode, variable triggerMode=defaultValue)
Start the FIFO reset daemon used for TP MD.
We create one thread group for each device.
References BUG, GetDAQConfigWave, HARDWARE_DAC_DEFAULT_TRIGGER, HW_GetMainDeviceName, TFH_FifoLoop.
Referenced by TFH_StartFIFOResetDeamon, TFH_StartFIFOStopDaemon.
variable TFH_StopFIFODaemon(variable hwType, variable deviceID)
Stop the FIFO daemon if required.
Sets the global threadGroupIDFifo to NaN afterwards.
References HW_GetMainDeviceName, TS_StopThreadGroup.
Referenced by DAP_UnlockDevice, DQM_StopDataAcq, DQM_TerminateOngoingDAQHelper, PSQ_Ramp.
static variable TFH_FifoLoop(wave config, variable triggerMode, variable deviceID, variable stopCollectionPoint, variable ADChannelToMonitor, variable mode)
Worker function used for monitoring the FIFO position of the given device.
Actions depend on mode: TFH_RESTART_ACQ: Restart acquisition from the start TFH_STOP_ACQ: Stop acquisition and quit running Stops in the following cases: An error during ITC operation calls The input queue is not empty Pushes the following entries into the thread queue: fifoPos: fifo position (relative to offset) startSequence: (yoking only) inform the main thread that ARDStartSequence() commmand should be called
References ASSERT_TS, DataFolderExistsDFR, HARDWARE_ABORT_ON_ERROR, HARDWARE_DAC_DEFAULT_TRIGGER, HARDWARE_PREVENT_ERROR_POPUP, HW_ITC_DebugMode_TS, HW_ITC_MoreData_TS, HW_ITC_ResetFifo_TS, HW_ITC_StartAcq_TS, HW_ITC_StopAcq_TS, MAIN_THREAD, TFH_RESTART_ACQ, TFH_STOP_ACQ, TIMEOUT_IN_MS, TS_ThreadGroupPutVariable.
Referenced by TFH_StartFIFODeamonInternal.