MIES_GuiPopupMenuExt.ipf
const double MAX_SUBMENUS
Referenced by PEXT_SplitToSubMenus, PEXT_VerifyAndSetMenuWave.
const string WAVE_NOTE_PROCNAME
Referenced by PEXT_ButtonProc.
const string WAVE_NOTE_WINDOWNAME
Referenced by PEXT_ButtonProc, PEXT_Callback.
const string WAVE_NOTE_CTRLNAME
Referenced by PEXT_ButtonProc, PEXT_Callback.
const string MENUNAME_UNUSED
Referenced by PEXT_SubMenuName.
const string MENU_DISABLE_SPECIAL
Referenced by PEXT_SubMenuName, PEXT_VerifyAndSetMenuWave.
const string LSEP
Referenced by PEXT_VerifyAndSetMenuWave.
string PEXT_SubMenuName(variable subMenuNr)
Menu definition templates for up to MAX_SUBMENUS sub menus. The constant MAX_SUBMENUS stores the number of these definitions and must be updated if more definitions are added.
Returns sub menu names for all PEXT sub menus This is called on each menu click/compilation for all dynamic defined Menus where PEXT_SubMenuName is used. subMenuNr number of current sub menu
References GetPopupExtMenuWave, IsEmpty, MENU_DISABLE_SPECIAL, MENUNAME_UNUSED, ROWS.
string PEXT_PopupMenuItems(variable subMenuNr)
Returns menu items for all PEXT menus This is called on each menu click/compilation for all dynamic defined Menus where PEXT_PopupMenuItems is used.
Callled very often (MAX_SUBMENUS^2/2). subMenuNr number of current sub menu
References GetPopupExtMenuWave, ROWS.
variable PEXT_Callback(string popupStr, string text, variable itemNum)
This callback is executed when the user selected a PEXT dynamic menu item. It is not called if the user aborted the menu by clicking somewhere else.
popupStr popup string text selected menu item text itemNum selected item index in submenu
References ASSERT, FuncRefIsAssigned, GetPopupExtMenuWave, GetStringFromWaveNote, IsEmpty, WAVE_NOTE_CTRLNAME, WAVE_NOTE_WINDOWNAME.
Referenced by PEXT_ButtonProc.
string PEXT_ITEMGETTER_LIST_PROTO()
Prototype for the menu item getter that allows user defined sub menu attribution of menu items.
wave PEXT_ITEMGETTER_WAVE_PROTO(string device)
Prototype for the menu item getter that is compatible with the former popupmenu value=procedure definition.
variable PEXT_POPUPACTION_PROTO(WMPopupAction *pa)
Prototype for the former popupaction procedure, that is only called virtually now through the PopupContextualMenu callback.
pa WMPopupAction structure
variable PEXT_ButtonProc(WMButtonAction *ba)
Generic procedure for button actions from popup extension controls Fills the global popupExtMenuInfo wave with current menu setup information retrieved from the function defined in the buttons userdata through PEXT_UDATA_ITEMGETTER key. This getter function can either return a string or 1D text wave.
ba WMButtonAction structure
References ASSERT, FuncRefIsAssigned, GetPopupExtMenuWave, IsNull, PEXT_Callback, PEXT_GenerateSubMenuNames, PEXT_SplitToSubMenus, PEXT_UDATA_ITEMGETTER, PEXT_UDATA_POPUPPROC, PEXT_VerifyAndSetMenuWave, ROWS, SetStringInWaveNote, WAVE_NOTE_CTRLNAME, WAVE_NOTE_PROCNAME, WAVE_NOTE_WINDOWNAME.
static variable PEXT_VerifyAndSetMenuWave(WaveTextOrNull menuWave)
Verifies menu data input wave and transfers it to global.
References ASSERT, GetPopupExtMenuWave, IsEmpty, LSEP, MAX_SUBMENUS, MENU_DISABLE_SPECIAL, PEXT_SetDisabledMenu, ROWS.
Referenced by PEXT_ButtonProc.
static variable PEXT_SetDisabledMenu()
Sets the menu to show a non selectable "_none_" entry.
References GetPopupExtMenuWave, ROWS.
Referenced by PEXT_VerifyAndSetMenuWave.
wave PEXT_SplitToSubMenus(WaveTextOrNull menuList=defaultValue, variable method=defaultValue)
Automatically splits a 1D text wave with menu items to submenus This function does not name submenus.
menuList 1d text wave with menu items method [optional, default = PEXT_SUBSPLIT_DEFAULT] sets how the menu items are split to sub menus PEXT_SubMenuSplitting 1d text wave where each element contains a list of menu items. Each element represents a sub menu.
References ASSERT, MAX_SUBMENUS, PEXT_SUBSPLIT_ALPHA, PEXT_SUBSPLIT_DEFAULT, ROWS.
Referenced by LBV_PopupExtFormatEntries, PEXT_ButtonProc.
variable PEXT_GenerateSubMenuNames(WaveTextOrNull splitMenu=defaultValue, variable method=defaultValue)
Automatically generates submenu names and applies them on the given wave.
splitMenu 1d text wave with menu item lists for sub menus as returned by PEXT_SplitToSubMenus() method [optional, default = PEXT_SUBNAMEGEN_DEFAULT] sets how the sub menu names are generated PEXT_SubMenuNameGeneration
References ASSERT, IsEmpty, PEXT_SUBNAMEGEN_DEFAULT, ROWS.
Referenced by LBV_PopupExtFormatEntries, PEXT_ButtonProc.