MIES_PressureControl.ipf
const string PRESSURE_CONTROLS_BUTTON_LIST
Referenced by P_Disable, P_EnableButtonsIfValid, P_LoadPressureButtonState, P_MethodBreakIn, P_MethodClear, P_MethodSeal, P_ResetAll_P_ButtonsToBaseState, P_SetPressureMode, P_UpdatePressureMode, SetPressureButtonsToBaseState.
const string PRESSURE_CONTROL_TITLE_LIST
Referenced by P_EnableButtonsIfValid, P_LoadPressureButtonState, P_ResetAll_P_ButtonsToBaseState, P_UpdatePressureMode, SetPressureButtonsToBaseState.
const string PRESSURE_CONTROL_CHECKBOX_LIST
Referenced by P_CheckAll, P_Disable, P_Enable, P_EnableButtonsIfValid.
const string PRESSURE_CONTROL_PRESSURE_DISP
Referenced by P_SetAndGetPressure.
const string PRESSURE_CONTROL_LED_MODE_USER
Referenced by P_SetLEDValueAssoc.
const string PRESSURE_CONTROL_USER_CHECBOXES
Referenced by P_SetLEDValueAssoc.
const string LOW_COLOR_HILITE
Referenced by P_PressureDisplayHighlite.
const string ZERO_COLOR_HILITE
Referenced by P_PressureDisplayHighlite.
const string HIGH_COLOR_HILITE
Referenced by P_PressureDisplayHighlite.
const string LOW_COLOR
Referenced by P_PressureDisplayHighlite.
const string ZERO_COLOR
Referenced by P_PressureDisplayHighlite.
const string HIGH_COLOR
Referenced by P_PressureDisplayHighlite.
const double NEG_PRESSURE_PULSE_INCREMENT
const double POS_PRESSURE_PULSE_INCREMENT
Referenced by P_GetPressureForDA.
const double PRESSURE_PULSE_ENDpt
Referenced by P_GetPressureForDA, P_TTLforPpulse.
const double PRESSURE_TTL_HIGH_START
Referenced by P_DataAcq, P_GetPressureForDA, P_TTLforPpulse.
const double GIGA_SEAL
Referenced by P_MethodBreakIn, P_MethodSeal.
const double PRESSURE_OFFSET
Referenced by P_GetPressureForDA, P_OpenDevice, P_SetAndGetPressure.
const double MIN_NEG_PRESSURE_PULSE
Referenced by P_GetPressureForDA, P_GetPulseAmp, P_LastPulseCount.
const double MAX_POS_PRESSURE_PULSE
Referenced by P_GetPressureForDA.
const double ATMOSPHERIC_PRESSURE
Referenced by P_MethodAtmospheric, P_MethodSeal.
const double PRESSURE_CHANGE
Referenced by P_UpdateTPStorage.
const double P_NEGATIVE_PULSE
Referenced by P_DAforNegPpulse, P_GetPressureForDA.
const double P_POSITIVE_PULSE
Referenced by P_DAforPosPpulse, P_GetPressureForDA.
const double P_MANUAL_PULSE
Referenced by P_DAforManPpulse, P_GetPressureForDA.
const double SEAL_POTENTIAL
Referenced by P_ApplyNegV, P_MethodSeal.
const double SEAL_RESISTANCE_THRESHOLD
Referenced by P_ApplyNegV.
const double ACCESS_ATM
Referenced by P_GetUserAccess, P_MethodBreakIn, P_SetPressureValves.
const double ACCESS_REGULATOR
Referenced by P_GetUserAccess, P_SetPressureValves.
const double ACCESS_USER
Referenced by P_GetUserAccess, P_MethodBreakIn, P_MethodClear, P_MethodSeal, P_SetPressureValves, P_UpdatePressureType.
variable P_PressureControl(string device)
Applies pressure methods based on data in PressureDataWv.
This function gets called by TP_RecordTP. It also gets called when the approach button is pushed. A key point is that data acquisition used to run pressure pulses cannot be active if the TP is inactive.
References DAG_GetNumericalValue, DAP_DeviceIsUnlocked, NUM_HEADSTAGES, P_DACIsCollectingData, P_GetPressureDataWaveRef, P_ManSetPressure, P_MethodApproach, P_MethodAtmospheric, P_MethodBreakIn, P_MethodClear, P_MethodSeal, P_PressureMethodPossible, P_RecordUserPressure, P_UpdateTPStorage, P_ValidatePressureSetHeadstage, PRESSURE_METHOD_APPROACH, PRESSURE_METHOD_ATM, PRESSURE_METHOD_BREAKIN, PRESSURE_METHOD_CLEAR, PRESSURE_METHOD_MANUAL, PRESSURE_METHOD_SEAL.
Referenced by P_RunP_ControlIfTPOFF, P_SetAllHStoAtmospheric, TP_RecordTP.
static variable P_RecordUserPressure(string device)
References DateTimeInUTC, GetNumberFromWaveNote, GetPressureTypeWv, GetTPStorage, HARDWARE_ABORT_ON_ERROR, HW_ReadADC, IsNaN, NOTE_INDEX, NUM_HEADSTAGES, P_GetPressureDataWaveRef, PRESSURE_TYPE_USER.
Referenced by P_PressureControl.
static variable P_UpdateTPStorage(string device, variable headStage)
Record pressure in TPStorage wave.
References GetNumberFromWaveNote, GetTPStorage, NOTE_INDEX, P_FindLastSetEntry, P_GetPressureDataWaveRef, P_IsHSActiveAndInVClamp, P_PublishPressureMethodChange, P_ValidatePressureSetHeadstage, PRESSURE_CHANGE.
Referenced by P_PressureControl.
static variable P_FindLastSetEntry(wave wv, variable row, variable col, string name)
Return the last non-NaN entry from the wave's column col and layer name starting from the row row going to 0.
References IsNaN.
Referenced by P_UpdateTPStorage.
static variable P_AddSealedEntryToTPStorage(string device, variable headstage)
References GetNumberFromWaveNote, GetTPStorage, NOTE_INDEX, P_IsHSActiveAndInVClamp, P_ValidatePressureSetHeadstage, SetNumberInWaveNote, TPSTORAGE_SEALED.
Referenced by P_MethodSeal.
static variable P_PublishPressureMethodChange(string device, variable headstage, variable oldMethod, variable newMethod)
References EqualValuesOrBothNaN, FFI_GetJSONTemplate, FFI_Publish, P_PressureMethodToString, PRESSURE_STATE_FILTER.
Referenced by P_UpdateTPStorage.
static variable P_PublishSealedState(string device, variable headstage)
References FFI_GetJSONTemplate, FFI_Publish, PRESSURE_SEALED_FILTER.
Referenced by P_MethodSeal.
static variable P_PublishBreakin(string device, variable headstage)
References FFI_GetJSONTemplate, FFI_Publish, PRESSURE_BREAKIN_FILTER.
Referenced by P_MethodBreakIn.
static variable P_MethodAtmospheric(string device, variable headstage)
Sets the pressure to atmospheric.
References ATMOSPHERIC_PRESSURE, P_GetPressureDataWaveRef, P_GetUserAccess, P_SetAndGetPressure, P_SetPressureValves, PRESSURE_METHOD_ATM.
Referenced by P_MethodBreakIn, P_MethodClear, P_MethodSeal, P_PressureControl.
static variable P_MethodApproach(string device, variable headStage)
Applies approach pressures.
References AI_UpdateAmpModel, AI_ZeroAmps, GetAmplifierParamStorageWave, IsFinite, P_GetPressureDataWaveRef, P_GetUserAccess, P_SetAndGetPressure, P_SetPressureValves, PRESSURE_METHOD_APPROACH.
Referenced by P_PressureControl.
static variable P_MethodSeal(string device, variable headStage)
Applies seal methods.
References ACCESS_USER, ATMOSPHERIC_PRESSURE, GetTabID, GIGA_SEAL, IsFinite, P_AddSealedEntryToTPStorage, P_ApplyNegV, P_GetPressureDataWaveRef, P_GetUserAccess, P_MethodAtmospheric, P_PublishSealedState, P_ResetPressureData, P_SetAndGetPressure, P_SetPressureValves, P_UpdatePressureMode, P_UpdateSSRSlopeAndSSR, P_UpdateVcom, PRESSURE_CONTROLS_BUTTON_LIST, PRESSURE_METHOD_ATM, PRESSURE_METHOD_SEAL, SEAL_POTENTIAL.
Referenced by P_PressureControl.
static variable P_MethodBreakIn(string device, variable headStage)
Applies break-in method.
References ACCESS_ATM, ACCESS_USER, GetTabID, GIGA_SEAL, IsFinite, P_GetPressureDataWaveRef, P_GetUserAccess, P_MethodAtmospheric, P_NegPressurePulse, P_PublishBreakin, P_ResetPressureData, P_SetPressureValves, P_UpdatePressureMode, P_UpdateSSRSlopeAndSSR, PRESSURE_CONTROLS_BUTTON_LIST, PRESSURE_METHOD_ATM, PRESSURE_METHOD_BREAKIN.
Referenced by P_PressureControl.
static variable P_MethodClear(string device, variable headStage)
Applies pipette clearing method.
References ACCESS_USER, GetTabID, IsFinite, P_GetPressureDataWaveRef, P_GetUserAccess, P_MethodAtmospheric, P_PosPressurePulse, P_ResetPressureData, P_SetPressureValves, P_UpdatePressureMode, P_UpdateSSRSlopeAndSSR, PRESSURE_CONTROLS_BUTTON_LIST, PRESSURE_METHOD_ATM, PRESSURE_METHOD_CLEAR.
Referenced by P_PressureControl.
static variable P_ApplyNegV(string device, variable headStage)
Applies updates the command voltage to the SEAL_POTENTIAL when SEAL_RESISTANCE_THRESHOLD is crossed.
References CHECKBOX_UNSELECTED, DAG_GetNumericalValue, P_GetPressureDataWaveRef, P_UpdateVcom, PGC_SetAndActivateControl, SEAL_POTENTIAL, SEAL_RESISTANCE_THRESHOLD.
Referenced by P_MethodSeal.
static variable P_UpdateVcom(string device, variable vCom, variable headStage)
Updates the command voltage.
References AI_UpdateAmpModel.
Referenced by P_ApplyNegV, P_MethodSeal.
static variable P_CloseDevice(string device)
Determines which devices to close. Ensures all DA_Ephys panels using a particular device for pressure regulation are updated correctly.
References GetListOfLockedDevices, P_CloseDeviceLowLevel, P_GetListOfPressureCtrlDevices, P_HeadstageUsingDevice.
Referenced by P_Disable.
static variable P_OpenDevice(string mainDevice, string pressureDevice)
Open device used for pressure regulation.
References GetListOfLockedDevices, HARDWARE_ABORT_ON_ERROR, HARDWARE_DAC_TYPES, HARDWARE_ITC_DAC, HW_OpenDevice, HW_RegisterDevice, HW_WriteDAC, P_GetPressureDataWaveRef, P_HeadstageUsingDevice, P_PrepareITCWaves, P_PressureDataTxtWaveRef, PRESSURE_OFFSET.
Referenced by P_Enable.
static variable P_PrepareITCWaves(string mainDevice, string pressureDevice, variable deviceID)
Adapt the ITC DAQ waves for hardware specialities.
References ASSERT, COLS, GetDeviceInfoWave, HW_ITC_GetITCXOPChannelForRack, IsITC1600, P_GetITCChanConfig, P_GetITCData, RACK_ONE, RACK_ZERO, ROWS, XOP_CHANNEL_TYPE_TTL.
Referenced by P_OpenDevice.
static variable P_CloseDeviceLowLevel(string device, string deviceToClose, variable refHeadstage)
Used to close the device used for pressure regulation.
References GetListOfLockedDevices, HARDWARE_PREVENT_ERROR_MESSAGE, HARDWARE_PREVENT_ERROR_POPUP, HW_CloseDevice, HW_DeRegisterDevice, HW_ResetDevice, HW_SelectDevice, IsFinite, P_GetPressureDataWaveRef, P_HeadstageUsingDevice, P_SetAndGetPressure.
Referenced by P_CloseDevice.
static string P_HeadstageUsingDevice(string device, string pressureDevice)
Returns a list of rows that contain a particular string.
References NUM_HEADSTAGES, P_PressureDataTxtWaveRef.
Referenced by P_CloseDevice, P_CloseDeviceLowLevel, P_OpenDevice.
static string P_GetListOfPressureCtrlDevices(string device)
Returns a list of ITC/NI devices to open.
Pulls a non repeating list of ITC/NI devices to open from the device specific pressure data wave.
References isEmpty, NONE, NUM_HEADSTAGES, P_PressureDataTxtWaveRef.
Referenced by P_CloseDevice, P_Disable, P_Enable.
variable P_SetAndGetPressure(string device, variable headStage, variable psi)
Sets the pressure on a headStage.
References DEBUGPRINT, HW_WriteDAC, P_GetPressureDataWaveRef, PRESSURE_CONTROL_PRESSURE_DISP, PRESSURE_OFFSET, SetValDisplay.
Referenced by P_CloseDeviceLowLevel, P_ManSetPressure, P_MethodApproach, P_MethodAtmospheric, P_MethodSeal, P_SetPressureOffset.
variable P_GetUserAccess(string device, variable headStage, variable pressureMode)
Returns pressure access defined in PRESSURE_CONSTANTS of the headstage.
device The DAQ device for which user access is being queried headStage MIES headstage number, must be in the range [0, NUM_HEADSTAGES] pressureMode One of the pressure modes defined in PRESSURE_CONSTANTS
References ACCESS_ATM, ACCESS_REGULATOR, ACCESS_USER, ASSERT, DAG_GetNumericalValue, P_GetPressureDataWaveRef, PRESSURE_METHOD_APPROACH, PRESSURE_METHOD_ATM, PRESSURE_METHOD_BREAKIN, PRESSURE_METHOD_CLEAR, PRESSURE_METHOD_MANUAL, PRESSURE_METHOD_SEAL.
Referenced by DAP_CheckProc_Settings_PUser, P_ManSetPressure, P_MethodApproach, P_MethodAtmospheric, P_MethodBreakIn, P_MethodClear, P_MethodSeal, P_UpdatePressureType.
variable P_SetPressureValves(string device, variable headStage, variable Access)
Maps the access (defined in PRESSURE_CONSTANTS) to the TTL settings.
References ACCESS_ATM, ACCESS_REGULATOR, ACCESS_USER, ASSERT, P_GetPressureDataWaveRef, P_UpdateTTLstate.
Referenced by DAP_CheckProc_Settings_PUser, P_ManSetPressure, P_MethodApproach, P_MethodAtmospheric, P_MethodBreakIn, P_MethodClear, P_MethodSeal.
variable P_UpdateTTLstate(string device, variable headStage, variable ONorOFFA, variable ONorOFFB)
Updates the TTL channel associated with headStage while maintaining existing channel states.
When setting TTLs, all channels are set at once. To keep existing TTL state on some channels, active state must be known. This function queries the hardware to determine the active state. ITC hardware: This requires the TTL out to be looped back to the TTL in on the ITC DAC. NI hardware: There are no dedicated input or output channels for DIO. The last written value is read according to documentation.
References ASSERT, ClearBit, HARDWARE_ABORT_ON_ERROR, HARDWARE_ITC_DAC, HARDWARE_NI_DAC, HW_GetDeviceName, HW_ITC_ClipTTLBit, HW_ITC_GetRackForTTLBit, HW_ReadDigital, HW_WriteDigital, IsFinite, P_DecToBinary, P_GetPressureDataWaveRef, SetBit.
Referenced by P_SetPressureValves.
static variable P_UpdateSSRSlopeAndSSR(string device)
Updates resistance slope and the resistance in PressureDataWv from TPStorageWave param.
References GetNumberFromWaveNote, GetTPStorage, IsFinite, NOTE_INDEX, NUM_HEADSTAGES, P_GetPressureDataWaveRef.
Referenced by P_MethodBreakIn, P_MethodClear, P_MethodSeal.
variable P_UpdatePressureDataStorageWv(string device)
Updates the pressure state (approach, seal, break in, or clear) from DA_Ephys panel to the pressureData wave.
References DAG_GetNumericalValue, GetPopupMenuIndex, GetPopupMenuString, GetSetVariable, GetSetVariableString, P_GetPressureDataWaveRef, P_PressureDataTxtWaveRef.
Referenced by DAP_PopMenuProc_CAA, DAP_SetVarProc_CAA, P_ButtonProc_Enable, P_Check_ApproachNear, P_Check_SealAtm.
variable P_UpdatePressureControls(string device, variable headStageNo)
Retrieves the parameters stored in the PressureData wave and passes them to the GUI controls.
References IsFinite, P_GetPressureDataWaveRef, P_PressureDataTxtWaveRef, P_UpdatePopupDevices, SetPopupMenuIndex, SetSetVariable, SetSetVariableString.
Referenced by DAP_SyncDeviceAssocSettToGUI.
static variable P_UpdatePopupDevices(string device, variable headStageNo)
Updates the popupmenu popup_Settings_Pressure_dev.
References GetPopupMenuString, P_GetPressureDataWaveRef, P_PressureDataTxtWaveRef, SetPopupMenuIndex.
Referenced by P_UpdatePressureControls.
static variable P_ManPressurePulse(string device, variable headStage)
Initiates a pressure pulse who's settings are are controlled in the manual tab of the pressure regulation controls.
References P_DAforManPpulse, P_DataAcq, P_ITC_SetChannels, P_TTLforPpulse.
Referenced by ButtonProc_ManPP.
static variable P_NegPressurePulse(string device, variable headStage)
Sends a negative pressure pulse to the pressure regulator. Gates the TTLs apropriately to maintain the exisiting TTL state while opening the TTL on the channel with the pressure pulse.
References P_DAforNegPpulse, P_DataAcq, P_ITC_SetChannels, P_TTLforPpulse.
Referenced by P_MethodBreakIn.
static variable P_PosPressurePulse(string device, variable headStage)
Initiates a positive pressure pulse to the pressure regulator. Gates the TTLs apropriately to maintain the exisiting TTL state while opening the TTL on the channel with the pressure pulse.
References P_DAforPosPpulse, P_DataAcq, P_ITC_SetChannels, P_TTLforPpulse.
Referenced by P_MethodClear.
static variable P_ITC_SetChannels(string device, variable headstage)
References P_GetITCChanConfig, P_GetPressureDataWaveRef.
Referenced by P_ManPressurePulse, P_NegPressurePulse, P_PosPressurePulse.
variable P_DeviceIsUsedForPressureCtrl(string device, string pressureDevice)
Check wether the given device is used as pressure device already.
References HW_GetDeviceName, NUM_HEADSTAGES, P_GetPressureDataWaveRef.
Referenced by P_ButtonProc_UserPressure.
static variable P_DataAcq(string device, variable headStage)
Perform an acquisition cycle on the pressure device for pressure control.
References ASSERT, DoAbortNow, HARDWARE_ABORT_ON_ERROR, HARDWARE_ITC_DAC, HARDWARE_NI_DAC, HW_GetDeviceName, HW_ITC_PrepareAcq, HW_StartAcq, HW_StopAcq, HW_WriteDigital, P_GetITCChanConfig, P_GetITCData, P_GetPressureDataWaveRef, P_NI_GetADWave, P_NI_GetDAWave, PRESSURE_TTL_HIGH_START, UNKNOWN_MODE, WAVEBUILDER_MIN_SAMPINT.
Referenced by P_ManPressurePulse, P_NegPressurePulse, P_PosPressurePulse.
variable P_ITC_FIFOMonitorProc(WMBackgroundStruct *s)
Monitor the device FIFO and terminates acquisition when sufficient data has been collected.
References HARDWARE_ABORT_ON_ERROR, HARDWARE_ITC_MIN_SAMPINT, HW_ITC_MoreData, HW_StopAcq, P_FindDeviceExecutingPP, P_GetPressureDataWaveRef.
variable P_NI_StopDAQ(string device, variable headStage)
References HW_WriteDigital, P_GetPressureDataWaveRef.
static variable P_FindDeviceExecutingPP(string *device, variable *deviceID, variable *headStage)
Returns the device of the device associated with device conducting a pressure pulse.
References GetListOfLockedDevices, NUM_HEADSTAGES, P_GetPressureDataWaveRef.
Referenced by P_ITC_FIFOMonitorProc.
static variable P_GetPressureForDA(string device, variable headStage, variable pressureMode, P_PressureDA *p)
Fill the passed structure with pressure details for the DA wave.
device device headStage headstage pressureMode one of P_NEGATIVE_PULSE, P_POSITIVE_PULSE, P_MANUAL_PULSE p pressure details
References ASSERT, P_PressureDA::calPressure, P_PressureDA::calPressureOffset, P_PressureDA::first, HARDWARE_ITC_BITS_PER_VOLT, HARDWARE_ITC_DAC, HARDWARE_ITC_MIN_SAMPINT, HARDWARE_NI_6001_MIN_SAMPINT, HARDWARE_NI_DAC, IsFinite, P_PressureDA::last, MAX_POS_PRESSURE_PULSE, MAX_REGULATOR_PRESSURE, MIN_NEG_PRESSURE_PULSE, MIN_REGULATOR_PRESSURE, P_GetPressureDataWaveRef, P_GetPulseAmp, P_MANUAL_PULSE, P_NEGATIVE_PULSE, P_POSITIVE_PULSE, POS_PRESSURE_PULSE_INCREMENT, P_PressureDA::pressure, PRESSURE_OFFSET, PRESSURE_PULSE_ENDpt, PRESSURE_TTL_HIGH_START, WAVEBUILDER_MIN_SAMPINT.
Referenced by P_DAforManPpulse, P_DAforNegPpulse, P_DAforPosPpulse.
static wave P_NI_GetDAWave(string device, variable headStage)
References P_DeviceSpecificPressureDFRef, P_GetPressureDataWaveRef.
Referenced by P_DataAcq, P_FillDAQWaves.
static wave P_NI_GetADWave(string device, variable headStage)
References P_DeviceSpecificPressureDFRef, P_GetPressureDataWaveRef.
Referenced by P_DataAcq, P_FillDAQWaves.
static variable P_FillDAQWaves(string device, variable headStage, P_PressureDA *p)
References ASSERT, P_PressureDA::calPressure, P_PressureDA::calPressureOffset, P_PressureDA::first, HARDWARE_ITC_DAC, HARDWARE_NI_6001_MIN_SAMPINT, HARDWARE_NI_DAC, P_PressureDA::last, P_GetITCData, P_GetPressureDataWaveRef, P_NI_GetADWave, P_NI_GetDAWave, ROWS.
Referenced by P_DAforManPpulse, P_DAforNegPpulse, P_DAforPosPpulse.
static variable P_DAforNegPpulse(string device, variable headStage)
Updates the DA data used for ITC controlled pressure devices for a negative pressure pulse.
References P_FillDAQWaves, P_GetPressureDataWaveRef, P_GetPressureForDA, P_NEGATIVE_PULSE.
Referenced by P_NegPressurePulse.
static variable P_GetPulseAmp(string device, variable headStage)
Returns the negative pressure pulse amplitude.
References MIN_NEG_PRESSURE_PULSE, P_GetPressureDataWaveRef, P_LastPulseCount.
Referenced by P_GetPressureForDA.
static variable P_LastPulseCount(variable pulseAmp)
Returns the pulse count.
References MIN_NEG_PRESSURE_PULSE.
Referenced by P_GetPulseAmp.
static variable P_DAforPosPpulse(string device, variable headstage)
Updates the DA data used for ITC controlled pressure devices for a positive pressure pulse.
References P_FillDAQWaves, P_GetPressureDataWaveRef, P_GetPressureForDA, P_POSITIVE_PULSE.
Referenced by P_PosPressurePulse.
static variable P_DAforManPpulse(string device, variable Headstage)
Updates the DA data used for ITC controlled pressure devices for a manual pressure pulse.
References MAX_REGULATOR_PRESSURE, MIN_REGULATOR_PRESSURE, P_FillDAQWaves, P_GetPressureDataWaveRef, P_GetPressureForDA, P_MANUAL_PULSE.
Referenced by P_ManPressurePulse.
static variable P_TTLforPpulse(string device, variable headStage)
Updates the rack 0 and rack 1 TTL waves used for ITC controlled pressure devices.
References ASSERT, HARDWARE_NI_DAC, HW_ITC_GetRackForTTLBit, HW_ReadDigital, IsFinite, IsITC1600, P_GetITCData, P_GetPressureDataWaveRef, P_PressureDataTxtWaveRef, P_UpdateTTLdecimal, PRESSURE_PULSE_ENDpt, PRESSURE_TTL_HIGH_START, RACK_ONE, RACK_ZERO.
Referenced by P_ManPressurePulse, P_NegPressurePulse, P_PosPressurePulse.
static variable P_UpdateTTLdecimal(string pressureDevice, variable dec, variable ttlBit, variable ONorOFF)
returns the new TTL state based on the starting TTL state.
References ClearBit, HW_ITC_ClipTTLBit, P_DecToBinary, SetBit.
Referenced by P_TTLforPpulse.
variable P_UpdatePressureMode(string device, variable pressureMode, string pressureControlName, variable checkALL)
Updates the pressure mode button state in the DA_Ephys Data Acq tab.
References P_CheckAll, P_EnableButtonsIfValid, P_GetPressureDataWaveRef, P_PressureDisplayHighlite, P_PressureMethodPossible, P_ResetPressureData, P_UpdatePressureType, P_ValidatePressureSetHeadstage, PRESSURE_CONTROL_TITLE_LIST, PRESSURE_CONTROLS_BUTTON_LIST, PRESSURE_METHOD_APPROACH, PRESSURE_METHOD_ATM, PRESSURE_METHOD_MANUAL, SetControlTitle, SetControlTitleColor.
Referenced by ButtonProc_BreakIn, ButtonProc_Clear, ButtonProc_Seal, P_MethodBreakIn, P_MethodClear, P_MethodSeal, P_SetApproach, P_SetManual, P_SetPressureMode.
static variable P_ResetPressureData(string device, variable headStageNo=defaultValue)
Resets pressure data to base state.
References P_GetPressureDataWaveRef.
Referenced by P_InitBeforeTP, P_MethodBreakIn, P_MethodClear, P_MethodSeal, P_SetPressureMode, P_UpdatePressureMode.
static variable P_CheckAll(string device, variable pressureMode, variable SavedPressureMode)
Applies pressure mode to all headstages with valid pressure settings.
References DAG_GetNumericalValue, NUM_HEADSTAGES, P_GetPressureDataWaveRef, P_PressureMethodPossible, P_UpdatePressureType, P_ValidatePressureSetHeadstage, PRESSURE_CONTROL_CHECKBOX_LIST, PRESSURE_METHOD_ATM.
Referenced by P_UpdatePressureMode.
variable P_SetPressureOffset(string device, variable headstage, variable userOffset)
References ASSERT, DEBUGPRINT, IsFinite, P_GetPressureDataWaveRef, P_SetAndGetPressure, PRESSURE_METHOD_APPROACH, PRESSURE_METHOD_ATM, PRESSURE_METHOD_BREAKIN, PRESSURE_METHOD_CLEAR, PRESSURE_METHOD_MANUAL, PRESSURE_METHOD_SEAL, TP_CheckIfTestpulseIsRunning.
Referenced by DAP_WindowHook.
variable P_InitBeforeTP(string device)
References P_GetPressureDataWaveRef, P_LoadPressureButtonState, P_ResetPressureData, P_SaveUserSelectedHeadstage.
Referenced by DAP_OneTimeCallBeforeDAQ, TPM_StartTestPulseMultiDevice, TPS_StartTestPulseSingleDevice.
variable P_LoadPressureButtonState(string device)
Colors and changes the title of the pressure buttons based on the saved pressure mode.
References P_EnableButtonsIfValid, P_GetPressureDataWaveRef, P_PressureDisplayHighlite, P_PressureMethodPossible, P_ResetAll_P_ButtonsToBaseState, P_ValidatePressureSetHeadstage, PRESSURE_CONTROL_TITLE_LIST, PRESSURE_CONTROLS_BUTTON_LIST, PRESSURE_METHOD_APPROACH, PRESSURE_METHOD_ATM, PRESSURE_METHOD_MANUAL, SetControlTitle, SetControlTitleColor, SetPressureButtonsToBaseState.
Referenced by DAP_SliderProc_MIESHeadStage, P_Enable, P_InitBeforeTP, TP_TeardownCommon.
static variable SetPressureButtonsToBaseState(string device)
Sets the pressure toggle buttons to disabled, default color, default title.
References DisableControls, PRESSURE_CONTROL_TITLE_LIST, PRESSURE_CONTROLS_BUTTON_LIST, SetControlTitleColors, SetControlTitles.
Referenced by P_LoadPressureButtonState.
static variable P_EnableButtonsIfValid(string device, variable headStageNo)
Checks if the Approach button can be enabled or all pressure mode buttons can be enabled. Enables buttons that pass checks.
References DAG_GetNumericalValue, DisableControls, EnableControl, EnableControls, P_PressureMethodPossible, PRESSURE_CONTROL_CHECKBOX_LIST, PRESSURE_CONTROL_TITLE_LIST, PRESSURE_CONTROLS_BUTTON_LIST, PRESSURE_METHOD_CLEAR, SetControlTitleColors, SetControlTitles.
Referenced by P_LoadPressureButtonState, P_UpdatePressureMode.
variable P_UpdatePressureModeTabs(string device, variable headStage)
updates the tablabels for the pressure tabControl according to the pressure mode
References P_GetPressureDataWaveRef, PGC_SetAndActivateControl, PRESSURE_METHOD_ATM, PRESSURE_METHOD_MANUAL.
Referenced by DAP_SliderProc_MIESHeadStage.
variable P_ValidatePressureSetHeadstage(string device, variable headStageNo)
Checks if all the pressure settings for a headStage are valid.
1 if all settings are valid, 0 otherwise
References DEBUGPRINT, P_GetPressureDataWaveRef, P_PressureDataTxtWaveRef.
Referenced by BWO_CheckAndClearPipettes, DAP_CheckProc_Settings_PUser, P_AddSealedEntryToTPStorage, P_CheckAll, P_LoadPressureButtonState, P_PressureControl, P_UpdatePressureMode, P_UpdatePressureType, P_UpdateTPStorage.
static variable P_DACIsCollectingData(string device, variable headStage)
Determines if device is active (i.e. collecting data)
used to determine if pressure pulse has completed.
References HW_IsRunning, P_GetPressureDataWaveRef.
Referenced by P_PressureControl.
static variable P_PressureMethodPossible(string device, variable headstage)
Return true if pressure methods can be used on that headstage now.
Does not check if the headstage has valid settings, see P_ValidatePressureSetHeadstage(), or that no pressure pulse is currently ongoing, see P_DACIsCollectingData().
References DAQ_CHANNEL_TYPE_TP, DAQ_NOT_RUNNING, DC_GetChannelTypefromHS, P_IsHSActiveAndInVClamp, TP_CheckIfTestpulseIsRunning.
Referenced by CheckProc_ClearEnable, P_CheckAll, P_EnableButtonsIfValid, P_LoadPressureButtonState, P_PressureControl, P_UpdatePressureMode.
static variable P_IsHSActiveAndInVClamp(string device, variable headStage)
Determines headStage is on and in V-Clamp mode.
References DAG_GetHeadstageMode, DAG_GetHeadstageState, V_CLAMP_MODE.
Referenced by P_AddSealedEntryToTPStorage, P_PressureMethodPossible, P_UpdateTPStorage.
static variable P_ResetAll_P_ButtonsToBaseState(string device)
Returns the four pressure buttons to the base state (gray color; removes "Stop" string from button title)
References PRESSURE_CONTROL_TITLE_LIST, PRESSURE_CONTROLS_BUTTON_LIST, SetControlTitle, SetControlTitleColor.
Referenced by P_LoadPressureButtonState.
variable P_PressureDisplayHighlite(string device, variable hilite)
References ChangeControlValueColor, HIGH_COLOR, HIGH_COLOR_HILITE, LOW_COLOR, LOW_COLOR_HILITE, P_GetPressureDataWaveRef, ZERO_COLOR, ZERO_COLOR_HILITE.
Referenced by DAP_SliderProc_MIESHeadStage, P_LoadPressureButtonState, P_UpdatePressureMode.
static std::tuple< variable, string > P_CheckDeviceAndChannelSelection(string device)
References GetDeviceInfoWave, GetPopupMenuString, IsFinite, NONE, str2numSafe.
Referenced by P_ButtonProc_Enable, P_ButtonProc_UserPressure.
static variable P_Enable()
Enables devices for all locked DA_Ephys panels. Sets the correct pressure button state for all locked DA_Ephys panels.
References DAG_GetNumericalValue, DisableControl, EnableControl, EnableControls, GetListOfLockedDevices, LOG_AddEntry, P_Disable, P_GetListOfPressureCtrlDevices, P_LoadPressureButtonState, P_OpenDevice, P_SaveUserSelectedHeadstage, P_SetLEDValueAssoc, PACKAGE_MIES, PRESSURE_CONTROL_CHECKBOX_LIST.
Referenced by P_ButtonProc_Enable.
variable P_Disable()
Disables devices for all locked DA_Ephys panels. Sets the correct pressure button state for all locked DA_Ephys panels.
References DisableControl, DisableControls, EnableControl, EnableControls, GetListOfLockedDevices, P_CloseDevice, P_GetListOfPressureCtrlDevices, P_UpdatePressureType, PRESSURE_CONTROL_CHECKBOX_LIST, PRESSURE_CONTROLS_BUTTON_LIST.
Referenced by P_ButtonProc_Disable, P_Enable.
static wave P_DecToBinary(variable dec)
Decimal to binary in 8bit wave.
Wave is always 4 rows long so that each TTL channel on the front of the ITC DAC gets "encoded"
Referenced by P_UpdateTTLdecimal, P_UpdateTTLstate.
static variable P_ManSetPressure(string device, variable headStage, variable manPressureAll)
Manual pressure control.
References P_GetPressureDataWaveRef, P_GetUserAccess, P_SetAndGetPressure, P_SetPressureValves, PRESSURE_METHOD_MANUAL.
Referenced by P_PressureControl.
variable P_SaveUserSelectedHeadstage(string device, variable headStage)
Saves user seleted headstage in pressureData wave.
References P_GetPressureDataWaveRef.
Referenced by DAP_LockDevice, DAP_SliderProc_MIESHeadStage, P_Enable, P_InitBeforeTP.
variable P_SetAllHStoAtmospheric(string device)
Sets all headstage to atmospheric pressure.
References GetColfromWavewithDimLabel, NUM_HEADSTAGES, P_DeviceSpecificPressureDFRef, P_PressureControl, PRESSURE_METHOD_ATM.
Referenced by DAP_OneTimeCallBeforeDAQ.
variable P_GetPressureMode(string device, variable headStage)
Gets the pressure mode for a headstage.
References P_GetPressureDataWaveRef.
Referenced by P_SetPressureMode.
variable P_SetPressureMode(string device, variable headStage, variable pressureMode, variable pressure=defaultValue)
Sets the pressure mode.
Intended for use by other processes device device headStage MIES headstage number, must be in the range [0, NUM_HEADSTAGES] pressureMode One of the pressure modes defined in PressureModeConstants pressure [optional, ignored by default. Sets pressure of manual mode]
References ASSERT, MAX_REGULATOR_PRESSURE, MIN_REGULATOR_PRESSURE, P_GetPressureDataWaveRef, P_GetPressureMode, P_ResetPressureData, P_RunP_ControlIfTPOFF, P_UpdatePressureMode, PGC_SetAndActivateControl, PRESSURE_CONTROLS_BUTTON_LIST, PRESSURE_METHOD_ATM, PRESSURE_METHOD_MANUAL.
Referenced by DAP_ChangeHeadstageState.
variable ButtonProc_Approach(WMButtonAction *ba)
Approach button.
References P_SetApproach.
variable P_SetApproach(string device, string cntrlName)
Sets approach state.
Handles the TP depency of the approach pressure application
References P_RunP_ControlIfTPOFF, P_UpdatePressureMode, PRESSURE_METHOD_APPROACH.
Referenced by ButtonProc_Approach.
variable ButtonProc_Seal(WMButtonAction *ba)
Seal button.
References P_UpdatePressureMode, PRESSURE_METHOD_SEAL.
variable ButtonProc_BreakIn(WMButtonAction *ba)
Break in button.
References P_UpdatePressureMode, PRESSURE_METHOD_BREAKIN.
variable ButtonProc_Clear(WMButtonAction *ba)
Clear button.
References P_UpdatePressureMode, PRESSURE_METHOD_CLEAR.
static variable P_SetManual(string device, string cntrlName)
Handles the TP depency of the Manual pressure application.
References P_RunP_ControlIfTPOFF, P_UpdatePressureMode, PRESSURE_METHOD_MANUAL.
Referenced by ButtonProc_DataAcq_ManPressSet.
variable CheckProc_ClearEnable(WMCheckboxAction *cba)
Clear all check box.
References DAG_GetNumericalValue, DAG_Update, DisableControl, EnableControl, P_PressureMethodPossible.
variable ButtonProc_Hrdwr_P_UpdtDAClist(WMButtonAction *ba)
Update DAC list button.
References DAP_GetITCDeviceList, GetListOfLockedDevices, HW_NI_ListDevices, NONE, SetPopupMenuVal.
variable P_ButtonProc_Enable(WMButtonAction *ba)
Pressure control device Enable button in Hardware tab of DA_Ephys panel.
References ControlWindowToFront, DAP_AbortIfUnlocked, P_CheckDeviceAndChannelSelection, P_Enable, P_UpdatePressureDataStorageWv.
variable P_ButtonProc_Disable(WMButtonAction *ba)
Pressure control device Disable button in Hardware tab of DA_Ephys panel.
References P_Disable.
variable ButtonProc_DataAcq_ManPressSet(WMButtonAction *ba)
Set pressure button.
References P_SetManual.
variable ButtonProc_ManPP(WMButtonAction *ba)
Manual pressure pulse button.
References DAG_GetNumericalValue, P_ManPressurePulse.
variable P_Check_ApproachNear(WMCheckboxAction *cba)
References DAG_Update, DAP_AbortIfUnlocked, P_RunP_ControlIfTPOFF, P_UpdatePressureDataStorageWv.
variable P_Check_SealAtm(WMCheckboxAction *cba)
References DAG_Update, DAP_AbortIfUnlocked, P_UpdatePressureDataStorageWv.
variable P_ButtonProc_UserPressure(WMButtonAction *ba)
References ASSERT, ControlWindowToFront, DAG_GetTextualValue, DAP_AbortIfUnlocked, DisableControls, EnableControls, HARDWARE_PREVENT_ERROR_MESSAGE, HARDWARE_PREVENT_ERROR_POPUP, HW_CloseDevice, HW_DeRegisterDevice, HW_OpenDevice, HW_RegisterDevice, LOG_AddEntry, NONE, P_CheckDeviceAndChannelSelection, P_DeviceIsUsedForPressureCtrl, P_GetPressureDataWaveRef, PACKAGE_MIES.
variable P_RunP_ControlIfTPOFF(string device)
Runs P_PressureControl if the TP is OFF.
References P_PressureControl, TP_CheckIfTestpulseIsRunning.
Referenced by DAP_CheckProc_Settings_PUser, DAP_SliderProc_MIESHeadStage, P_Check_ApproachNear, P_SetApproach, P_SetManual, P_SetPressureMode.
variable P_GetAutoUserOff(string device)
If auto-user-OFF is checked, then user access is turned off this function is run by the active headstage slider control.
References CHECKBOX_UNSELECTED, DAG_GetNumericalValue, P_GetPressureDataWaveRef, PGC_SetAndActivateControl.
Referenced by DAP_SliderProc_MIESHeadStage.
static variable P_SetLEDValueAssoc(string device)
Sets the value of the headstage LED valDisplays to the correct cell in pressureType wave.
References COLS, GetDA_EphysGuiStateNum, GetPressureTypeWv, NUM_HEADSTAGES, PRESSURE_CONTROL_LED_DASHBOARD, PRESSURE_CONTROL_LED_MODE_USER, PRESSURE_CONTROL_USER_CHECBOXES, SetValDisplay.
Referenced by P_Enable.
variable P_UpdatePressureType(string device)
Encodes the pressure type for each headstage.
See also PressureTypeConstants
References ACCESS_USER, GetPressureTypeWv, P_GetPressureDataWaveRef, P_GetUserAccess, P_ValidatePressureSetHeadstage, PRESSURE_METHOD_APPROACH, PRESSURE_METHOD_ATM, PRESSURE_METHOD_CLEAR, PRESSURE_METHOD_MANUAL, PRESSURE_TYPE_ATM, PRESSURE_TYPE_AUTO, PRESSURE_TYPE_MANUAL, PRESSURE_TYPE_USER.
Referenced by DAP_ChangeHeadstageState, DAP_CheckProc_Settings_PUser, DAP_SliderProc_MIESHeadStage, P_CheckAll, P_Disable, P_UpdatePressureMode.
static string P_PressureMethodToString(variable method)
References ASSERT, IsNaN, PRESSURE_METHOD_APPROACH, PRESSURE_METHOD_ATM, PRESSURE_METHOD_BREAKIN, PRESSURE_METHOD_CLEAR, PRESSURE_METHOD_MANUAL, PRESSURE_METHOD_SEAL.
Referenced by P_PublishPressureMethodChange.