MIES_RepeatedAcquisition.ipf
static variable RA_RecalculateITI(string device)
Recalculate the Inter trial interval (ITI) for the given device.
References DAG_GetNumericalValue, DQ_StopDAQDeviceTimer.
Referenced by RA_HandleITI, RA_HandleITI_MD.
static variable RA_HandleITI_MD(string device)
References AS_HandlePossibleTransition, AS_ITI, DAG_GetNumericalValue, DAP_ApplyDelayedClampModeChange, DQM_StartBackgroundTimer, ExecuteListOfFunctions, IsBackgroundTaskRunning, RA_RecalculateITI, TEST_PULSE_DURING_RA_MOD, TPM_StartTPMultiDeviceLow.
Referenced by RA_BckgTPwithCallToRACounterMD, RA_StartMD.
static variable RA_WaitUntiIITIDone(string device, variable elapsedTime)
References ESCAPE_KEY, RelativeNowHighPrec, SCOPE_GetGraph, SetValDisplay.
Referenced by RA_HandleITI.
static variable RA_HandleITI(string device)
References AS_HandlePossibleTransition, AS_ITI, DAG_GetNumericalValue, DAP_ApplyDelayedClampModeChange, DQS_StartBackgroundTimer, ExecuteListOfFunctions, RA_FinishAcquisition, RA_RecalculateITI, RA_WaitUntiIITIDone, TEST_PULSE_BG_SINGLE_DEVICE, TEST_PULSE_DURING_RA_MOD, TEST_PULSE_FG_SINGLE_DEVICE, TP_Setup, TP_Teardown, TPS_StartBackgroundTestPulse, TPS_StartTestPulseForeground.
Referenced by RA_BckgTPwithCallToRACounter, RA_Start.
static variable RA_GetTotalNumberOfSweepsLowLev(string device)
Calculate the total number of sweeps for repeated acquisition.
Helper function for plain calculation without lead and follower logic
References DAG_GetNumericalValue, GetValDisplayAsNum, IDX_CalculcateActiveSetCount.
Referenced by RA_GetTotalNumberOfSweeps.
static variable RA_GetTotalNumberOfSweeps(string device)
Calculate the total number of sweeps for repeated acquisition.
References DeviceHasFollower, RA_GetTotalNumberOfSweepsLowLev.
Referenced by RA_BckgTPwithCallToRACounter, RA_BckgTPwithCallToRACounterMD, RA_Counter, RA_CounterMD, RA_SkipSweepCalc, RA_Start, RA_StartMD, RA_StepSweepsRemaining.
variable RA_StepSweepsRemaining(string device)
Update the "Sweeps remaining" control.
References DAG_GetNumericalValue, RA_GetTotalNumberOfSweeps, SetValDisplay.
Referenced by DAP_OneTimeCallBeforeDAQ, DC_CalculateChannelColumnNo, IDX_HandleIndexing, RA_Counter, RA_CounterMD, RA_SkipSweeps, RA_Start, RA_StartMD.
static variable RA_Start(string device)
Function gets called after the first sweep is already acquired and if repeated acquisition is on.
References RA_FinishAcquisition, RA_GetTotalNumberOfSweeps, RA_HandleITI, RA_PerfInitialize, RA_StepSweepsRemaining.
Referenced by RA_ContinueOrStop.
variable RA_Counter(string device)
References AssertOnAndClearRTError, ClearRTError, DAG_GetNumericalValue, DAP_ApplyDelayedClampModeChange, DAQ_NOT_RUNNING, DATA_ACQUISITION_MODE, DC_Configure, DEBUGPRINT, DQS_BkrdDataAcq, DQS_DataAcq, GetDataAcqRunMode, IDX_HandleIndexing, RA_FinishAcquisition, RA_GetTotalNumberOfSweeps, RA_PerfAddMark, RA_StepSweepsRemaining, ROVar.
static variable RA_FinishAcquisition(string device)
References DAP_OneTimeCallAfterDAQ, DQ_STOP_REASON_FINISHED, DQ_StopDAQDeviceTimer, GetListofLeaderAndPossFollower, RA_PerfFinish.
Referenced by RA_BckgTPwithCallToRACounter, RA_BckgTPwithCallToRACounterMD, RA_Counter, RA_CounterMD, RA_HandleITI, RA_Start, RA_StartMD.
static variable RA_BckgTPwithCallToRACounter(string device)
References RA_FinishAcquisition, RA_GetTotalNumberOfSweeps, RA_HandleITI.
Referenced by RA_ContinueOrStop.
static variable RA_StartMD(string device)
References DeviceHasFollower, RA_FinishAcquisition, RA_GetTotalNumberOfSweeps, RA_HandleITI_MD, RA_PerfInitialize, RA_StepSweepsRemaining.
Referenced by RA_YokedRAStartMD.
variable RA_CounterMD(string device)
References DAP_ApplyDelayedClampModeChange, DAQ_NOT_RUNNING, DEBUGPRINT, DQM_StartDAQMultiDevice, GetDataAcqRunMode, IDX_HandleIndexing, RA_FinishAcquisition, RA_GetTotalNumberOfSweeps, RA_PerfAddMark, RA_StepSweepsRemaining, ROVar.
static variable RA_BckgTPwithCallToRACounterMD(string device)
References RA_FinishAcquisition, RA_GetTotalNumberOfSweeps, RA_HandleITI_MD.
Referenced by RA_YokedRABckgTPCallRACounter.
static variable RA_AreLeaderAndFollowerFinished()
References DQM_GetActiveDeviceRow, GetDQMActiveDeviceList, GetListofLeaderAndPossFollower, IsFinite, ITC1600_FIRST_DEVICE, ROWS.
Referenced by RA_YokedRABckgTPCallRACounter, RA_YokedRAStartMD.
static variable RA_YokedRAStartMD(string device)
References DeviceCanFollow, DeviceHasFollower, ITC1600_FIRST_DEVICE, RA_AreLeaderAndFollowerFinished, RA_StartMD.
Referenced by RA_ContinueOrStop.
static variable RA_YokedRABckgTPCallRACounter(string device)
References DeviceCanFollow, DeviceHasFollower, ITC1600_FIRST_DEVICE, RA_AreLeaderAndFollowerFinished, RA_BckgTPwithCallToRACounterMD.
Referenced by RA_ContinueOrStop.
variable RA_IsFirstSweep(string device)
Return one if we are acquiring currently the very first sweep of a possible repeated acquisition cycle. Zero means that we acquire a later sweep than the first one in a repeated acquisition cycle.
Referenced by DC_CalculateChannelColumnNo, DQ_StopOngoingDAQHelper, RA_ContinueOrStop.
variable RA_SkipSweeps(string device, variable skipCount, variable limitToSetBorder=defaultValue, variable document=defaultValue)
Allows skipping forward or backwards the sweep count during data acquistion.
device device skipCount The number of sweeps to skip (forward or backwards) during repeated acquisition limitToSetBorder [optional, defaults to false] Limits skipCount so that we don't skip further than after the last sweep of the stimset with the most number of sweeps. document [optional, defaults to false] Add labnotebook entries to document the sweep skipping.
References DAQ_NOT_RUNNING, DEBUGPRINT, DeviceHasFollower, IDX_CalculcateActiveSetCount, RA_DocumentSweepSkipping, RA_SkipSweepCalc, RA_StepSweepsRemaining.
Referenced by DAP_ButtonProc_skipBack, DAP_ButtonProc_skipSweep, ED_createAsyncWaveNoteTags, MSQ_FastRheoEst, PSQ_Chirp, PSQ_DAScale, PSQ_PipetteInBath, PSQ_Ramp, PSQ_Rheobase, PSQ_SquarePulse, SC_SpikeControl.
static variable RA_DocumentSweepSkipping(string device, variable skipCount)
Document the number of skipped sweeps.
References AS_GetSweepNumber, ED_AddEntriesToLabnotebook, GetLastSettingIndep, GetLBNumericalValues, INDEP_HEADSTAGE, LABNOTEBOOK_LAYER_COUNT, SKIP_SWEEPS_KEY, UNKNOWN_MODE.
Referenced by RA_SkipSweeps.
static variable RA_SkipSweepCalc(string device, variable skipCount)
Returns valid count after adding skipCount.
device device skipCount The number of sweeps to skip (forward or backwards) during repeated acquisition.
References DAG_GetNumericalValue, DEBUGPRINT, DEBUGPRINTv, RA_GetTotalNumberOfSweeps.
Referenced by RA_SkipSweeps.
static variable RA_PerfInitialize(string device)
References GetRAPerfWave, KillOrMoveToTrash, RelativeNowHighPrec.
Referenced by RA_Start, RA_StartMD.
static variable RA_PerfAddMark(string device, variable idx)
References EnsureLargeEnoughWave, GetRAPerfWave, RelativeNowHighPrec.
Referenced by RA_Counter, RA_CounterMD.
static variable RA_PerfFinish(string device)
References GetRAPerfWave, ROWS.
Referenced by RA_FinishAcquisition.
variable RA_ContinueOrStop(string device, variable multiDevice=defaultValue)
Continue DAQ if requested or stop it.
device device multiDevice [optional, defaults to false] DAQ mode
References DAG_GetNumericalValue, DAP_OneTimeCallAfterDAQ, DQ_STOP_REASON_FINISHED, RA_BckgTPwithCallToRACounter, RA_IsFirstSweep, RA_Start, RA_YokedRABckgTPCallRACounter, RA_YokedRAStartMD.
Referenced by DQM_StopDataAcq, DQS_StopDataAcq.