MIES_MiesUtilities.ipf
const double DECIMATION_NONE
Referenced by DC_MakeHelperWaves, GetDecimatedWaveSize, SCOPE_ITC_UpdateOscilloscope, SCOPE_NI_UpdateOscilloscope.
const double DECIMATION_MINMAX
Referenced by DecimateWithMethod, GetDecimatedWaveSize.
const double ADC_SLOT_MULTIPLIER
Referenced by LayoutGraph.
const double EPOCH_SLOT_MULTIPLIER
Referenced by LayoutGraph.
const double NUM_CHANNEL_TYPES
Referenced by CreateTiledChannelGraph.
const double GET_LB_MODE_NONE
Referenced by GetLastSettingNoCache.
const double GET_LB_MODE_READ
Referenced by GetLastSettingNoCache.
const double GET_LB_MODE_WRITE
Referenced by GetLastSettingNoCache.
const string PSQ_PB_LBN_PREFIX
Referenced by CreateAnaFuncLBNKey.
const string PSQ_CR_LBN_PREFIX
Referenced by CreateAnaFuncLBNKey.
const string PSQ_SP_LBN_PREFIX
Referenced by CreateAnaFuncLBNKey.
const string PSQ_DS_LBN_PREFIX
Referenced by CreateAnaFuncLBNKey.
const string PSQ_RB_LBN_PREFIX
Referenced by CreateAnaFuncLBNKey.
const string PSQ_RA_LBN_PREFIX
Referenced by CreateAnaFuncLBNKey.
const string MSQ_FRE_LBN_PREFIX
Referenced by CreateAnaFuncLBNKey.
const string MSQ_DS_LBN_PREFIX
Referenced by CreateAnaFuncLBNKey.
const string MSQ_SC_LBN_PREFIX
Referenced by CreateAnaFuncLBNKey.
const string LBN_UNASSOC_REGEXP_LEGACY
Referenced by IsUnassocLBNKey, RemoveUnassocLBNKeySuffix.
const string LBN_UNASSOC_REGEXP
Referenced by IsUnassocLBNKey, RemoveUnassocLBNKeySuffix.
variable HorizExpandWithVisX()
Custom graph marquee.
Requires an existing marquee and a graph as current top window
References AutoscaleVertAxisVisXRange, AXIS_ORIENTATION_LEFT, AXIS_ORIENTATION_RIGHT, DEBUGPRINT, GetAxisOrientation, GetCurrentWindow.
variable GetLogbookType(wave wv)
Return the logbook type, one of LogbookTypes.
References ASSERT, LBT_LABNOTEBOOK, LBT_RESULTS, LBT_TPSTORAGE, TP_STORAGE_REGEXP.
Referenced by ExtractLogbookSliceDeltaTime, ExtractLogbookSliceEmpty, ExtractLogbookSliceSweep, ExtractLogbookSliceTimeStamp, LBV_AddTraceToLBGraph, LBV_SwitchLBGraphXAxis.
wave GetLogbookWaves(variable logbookType, variable logbookWaveType, string device=defaultValue)
Return the logbook waves.
device [optional only for LBT_RESULTS] device logbookType one of LogbookTypes logbookWaveType one of LabnotebookWaveTypes
References ASSERT, GetNumericalResultsKeys, GetNumericalResultsValues, GetTextualResultsKeys, GetTextualResultsValues, GetTPStorage, LBN_NUMERICAL_KEYS, LBN_NUMERICAL_VALUES, LBN_TEXTUAL_KEYS, LBN_TEXTUAL_VALUES, LBT_LABNOTEBOOK, LBT_RESULTS, LBT_TPSTORAGE.
Referenced by BSP_GetLogbookWave, DB_GetLBNWave, ED_createTextNotes, ED_createWaveNotes.
wave ExtractLogbookSliceTimeStamp(wave logbook)
Extract a date/time slice of the logbook wave.
References ASSERT, ExtractLogbookSlice, GetLogbookType, LAYERS, LBT_LABNOTEBOOK, LBT_RESULTS, LBT_TPSTORAGE.
Referenced by ED_createTextNotes, ED_createWaveNotes, LBV_AddTagsForTextualLBNEntries, LBV_AddTraceToLBGraph, LBV_AddTraceToLBGraphTPStorage, LBV_SwitchLBGraphXAxis, TP_RecordTP.
wave ExtractLogbookSliceDeltaTime(wave logbook)
Extract the delta time slice of the logbook wave.
References ASSERT, ExtractLogbookSlice, GetLogbookType, LAYERS, LBT_LABNOTEBOOK, LBT_RESULTS, LBT_TPSTORAGE.
wave ExtractLogbookSliceSweep(wave values)
Extract the sweep number slice of the labnotebook values wave.
References ExtractLogbookSlice, GetLogbookType.
Referenced by ED_createTextNotes, LBV_AddTagsForTextualLBNEntries, LBV_AddTraceToLBGraph, LBV_SwitchLBGraphXAxis.
wave ExtractLogbookSliceEmpty(wave values)
Extract a slice of the logbook wave and makes it empty.
References ExtractLogbookSlice, GetLogbookType.
Referenced by LBV_AddTraceToLBGraph.
static wave ExtractLogbookSlice(wave logbook, variable logbookType, variable colOrLayer, string suffix)
Extract a single column/layer of the labnotebook/TPStorage values wave.
This is useful if you want to plot values against e.g time and let Igor do the formatting of the date/time values. Always returns a numerical wave.
References ASSERT, CHUNKS, COLS, createDFWithAllParents, GetNumberFromWaveNote, isEmpty, IsFinite, IsTextWave, KillOrMoveToTrash, LAYERS, LBT_LABNOTEBOOK, LBT_RESULTS, LBT_TPSTORAGE, MakeWaveFree, NOTE_INDEX, ROWS, SetNumberInWaveNote.
Referenced by ExtractLogbookSliceDeltaTime, ExtractLogbookSliceEmpty, ExtractLogbookSliceSweep, ExtractLogbookSliceTimeStamp.
wave GetADCListFromConfig(wave config)
Return a list of the AD channels from the DAQ config.
References GetChanneListFromDAQConfigWave, XOP_CHANNEL_TYPE_ADC.
Referenced by CreateTiledChannelGraph, DC_Configure, DC_GetConfiguration, DC_MakeHelperWaves, NWB_AppendSweepLowLevel, SCOPE_CreateGraph, SCOPE_ITC_UpdateOscilloscope, SCOPE_SetADAxisLabel, SCOPE_UpdateGraph, SCOPE_UpdateOscilloscopeData, SWS_GetChannelGains.
wave GetDACListFromConfig(wave config)
Return a list of the DA channels from the DAQ config.
References GetChanneListFromDAQConfigWave, XOP_CHANNEL_TYPE_DAC.
Referenced by CreateTiledChannelGraph, DC_Configure, DC_GetConfiguration, DC_MakeHelperWaves, EP_WriteEpochInfoIntoSweepSettings, NWB_AppendSweepLowLevel, SCOPE_CreateGraph, SCOPE_ITC_UpdateOscilloscope, SCOPE_UpdateGraph, SCOPE_UpdateOscilloscopeData, SWS_GetChannelGains.
wave GetTTLListFromConfig(wave config)
Return a list of the TTL channels from the DAQ config.
References GetChanneListFromDAQConfigWave, XOP_CHANNEL_TYPE_TTL.
Referenced by CreateTiledChannelGraph, DC_GetConfiguration, DC_MakeHelperWaves, SWS_GetChannelGains.
static wave GetChanneListFromDAQConfigWave(wave config, variable channelType)
Return a wave with all active channels.
Todochange to return a 0/1 wave with constant size a la DAG_GetChannelState config DAQConfigWave as passed to the ITC XOP channelType DA/AD/TTL constants, see ChannelTypeAndControlConstants
References ASSERT_TS, IsValidConfigWave, ROWS.
Referenced by GetADCListFromConfig, GetDACListFromConfig, GetTTLListFromConfig.
variable GetNrOfTypedChannels(wave chanTypes, variable type)
Returns the number of given mode channels from channelType wave.
chanTypes a 1D wave containing DaqChannelTypeConstants, returned by GetADCTypesFromConfig() type to count, one of DaqChannelTypeConstants number of types present in chanTypes
References ASSERT, DAQ_CHANNEL_TYPE_DAQ, DAQ_CHANNEL_TYPE_TP, DAQ_CHANNEL_TYPE_UNKOWN, ROWS.
Referenced by SCOPE_UpdateOscilloscopeData.
wave GetTTLTypesFromConfig(wave config)
Return a types of the AD channels from the ITC config.
References GetTypeListFromITCConfig, XOP_CHANNEL_TYPE_TTL.
wave GetADCTypesFromConfig(wave config)
Return a types of the AD channels from the ITC config.
References GetTypeListFromITCConfig, XOP_CHANNEL_TYPE_ADC.
Referenced by GotTPChannelsOnADCs, SCOPE_CreateGraph, SCOPE_UpdateGraph, SCOPE_UpdateOscilloscopeData.
wave GetDACTypesFromConfig(wave config)
Return a types of the DA channels from the ITC config.
References GetTypeListFromITCConfig, XOP_CHANNEL_TYPE_DAC.
Referenced by DC_GetStopCollectionPoint.
static wave GetTypeListFromITCConfig(wave config, variable channelType)
Return a wave with all active channels.
Todochange to return a 0/1 wave with constant size a la DAG_GetChannelState config DAQConfigWave as passed to the ITC XOP channelType DA/AD/TTL constants, see ChannelTypeAndControlConstants
References ASSERT, IsValidConfigWave, ROWS.
Referenced by GetADCTypesFromConfig, GetDACTypesFromConfig, GetTTLTypesFromConfig.
variable GotTPChannelsOnADCs(string device)
Checks if a channel of TP type exists on ADCs.
device device 1 if TP type present, 0 otherwise
References DAQ_CHANNEL_TYPE_TP, GetADCTypesFromConfig, GetDAQConfigWave.
Referenced by DQM_FIFOMonitor, DQS_DataAcq, SCOPE_UpdateGraph.
string GetSpecialControlLabel(variable channelType, variable controlType)
Return the dimension label for the special, aka non-unique, controls.
References GetPanelControl.
Referenced by ASD_CheckAsynAlarmState, ASD_ReadChannel, DAG_RecordGuiStateNum, DAG_RecordGuiStateTxT, DAG_Update, DAP_AdaptAssocHeadstageState, DAP_CheckHeadStage, DAP_CheckProc_Channel_All, DAP_CheckSettings, DAP_CheckStimset, DAP_PopMenuChkProc_StimSetList, DC_GetConfiguration, DC_PlaceDataInDAQConfigWave, DC_PrepareLBNEntries, ED_createAsyncWaveNoteTags, IDX_GetCurrentSets, IDX_GetSetsInRange, IDX_IndexSingleChannel, PSQ_EvaluateBaselineProperties, PSQ_PB_CreateTestpulseEpochs, PSQ_PB_GetPrePulseBaselineDuration, SetDAScale.
string GetPanelControl(variable channelIndex, variable channelType, variable controlType)
Returns the name of a control from the DA_EPHYS panel.
Constants are defined at ChannelTypeAndControlConstants
References ASSERT, CHANNEL_CONTROL_ALARM_MAX, CHANNEL_CONTROL_ALARM_MIN, CHANNEL_CONTROL_CHECK, CHANNEL_CONTROL_GAIN, CHANNEL_CONTROL_INDEX_END, CHANNEL_CONTROL_SCALE, CHANNEL_CONTROL_SEARCH, CHANNEL_CONTROL_TITLE, CHANNEL_CONTROL_UNIT, CHANNEL_CONTROL_WAVE, CHANNEL_INDEX_ALL, CHANNEL_INDEX_ALL_I_CLAMP, CHANNEL_INDEX_ALL_V_CLAMP, CHANNEL_TYPE_ADC, CHANNEL_TYPE_ALARM, CHANNEL_TYPE_ASYNC, CHANNEL_TYPE_DAC, CHANNEL_TYPE_HEADSTAGE, CHANNEL_TYPE_TTL.
Referenced by AdjustDAScale, AFH_GetStimSetName, AFM_UpdateAnalysisFunctionWave, BWO_SetMIESSettings, DAG_ControlStatusWave, DAG_GetAllHSMode, DAP_AdaptAssocHeadstageState, DAP_AllChanDASettings, DAP_ApplyClmpModeSavdSettngs, DAP_ChangeHeadstageState, DAP_CheckProc_Channel_All, DAP_GetControlsForChannelIndex, DAP_OneTimeCallBeforeDAQ, DAP_PopMenuChkProc_StimSetList, DAP_RemoveClampModeSettings, DAP_ResetGUIAfterDAQ, DAP_SetVarProc_Channel_Search, DAP_SetVarProc_DA_Scale, DAP_TurnOffAllChannels, DAP_UpdateDaEphysStimulusSetPopups, GetAllDAEphysPopMenuIndex, GetAllDAEphysPopMenuString, GetAllDAEphysSetVarNum, GetAllDAEphysSetVarTxT, GetSpecialControlLabel, IDX_GetStimsets, IDX_IndexSingleChannel, IDX_ResetStartFinishForIndexing, IVS_runBaselineCheckQC, IVS_RunGigOhmSealQC, IVS_runInitAccessResisQC, IVS_runStimWave, MSQ_DAScale, MSQ_FastRheoEst, PSQ_PipetteInBath, ReachTargetVoltage, SetDAScale.
static variable FindRange(wave wv, variable col, variable val, variable forwardORBackward, variable entrySourceType, variable *first, variable *last)
Find the first and last point index of a consecutive range of values in the labnotebook.
wv wave to search col column to look for val value to search forwardORBackward find the first(1) or last(0) range entrySourceType type of the labnotebook entry, one of DataAcqModes first point index of the beginning of the range last point index of the end of the range
References COLS, DATA_ACQUISITION_MODE, FindIndizes, GetSetDifference, GetSetIntersection, IsFinite, IsNaN, IsNumericWave, LABNOTEBOOK_LAYER_COUNT, PROP_EMPTY, PROP_NON_EMPTY, ROWS, WaveMinAndMaxWrapper.
Referenced by GetLastSettingNoCache.
static variable EnforceIndependentSetting(wave settings)
Test helper to enforce that every query done for an INDEP_HEADSTAGE setting does not search an entry which is HEADSTAGE dependent. The additional check that not all entries are the same is for really old legacy entries which are INDEP but set for all headstages.
Does nothing outside of CI.
References ASSERT_TS, HasOneValidEntry, IsConstant, NUM_HEADSTAGES.
Referenced by GetLastSettingIndep, GetLastSettingIndepRAC, GetLastSettingIndepSCI, GetLastSettingTextIndep, GetLastSettingTextIndepRAC, GetLastSweepWithSettingIndep, GetLastSweepWithSettingTextI.
variable GetSweepColumn(wave labnotebookValues)
Returns the numerical index for the sweep number column in the settings history waves (numeric and text)
References COLS.
Referenced by AB_GetSweepsFromLabNotebook, AFH_GetSweepsFromSameRACycleNC, AFH_GetSweepsFromSameSCINC, GetLastSettingNoCache, GetLastSweepWithSetting, GetLastSweepWithSettingText, GetSweepsWithSetting, LBV_AddTagsForTextualLBNEntries, LBV_AddTraceToLBGraph, LBV_SwitchLBGraphXAxis.
variable GetLastSettingIndep(wave numericalValues, variable sweepNo, string setting, variable entrySourceType, variable defValue=defaultValue)
Return a headstage independent setting from the numerical labnotebook.
the headstage independent setting or defValue GetLastSetting()
References EnforceIndependentSetting, GetIndexForHeadstageIndepData, GetLastSetting.
Referenced by AD_FillWaves, AD_GetBaselineFailMsg, AD_GetPerSweepFailMessage, AFH_GetSweepsFromSameRACycleNC, CreateTiledChannelGraph, GetLastSettingIndepEachRAC, GetLastSettingIndepEachSCI, GetSamplingIntervalFromLBN, GetTotalOnsetDelay, LBV_LimitXRangeToSelected, MSQ_NumPassesInSet, NWB_AppendSweepLowLevel, NWB_GenerateDeviceDescription, PA_DiffPulseInfos, PSQ_Chirp, PSQ_EvaluateBaselineProperties, PSQ_GetLastPassingDAScaleSub, PSQ_GetLastPassingLongRHSweep, PSQ_NumPassesInSet, PSQ_PipetteInBath, PSQ_Rheobase, RA_DocumentSweepSkipping.
string GetLastSettingTextIndep(WaveText textualValues, variable sweepNo, string setting, variable entrySourceType, string defValue=defaultValue)
Return a headstage independent setting from the textual labnotebook.
the headstage independent setting or defValue GetLastSetting()
References ASSERT_TS, EnforceIndependentSetting, GetIndexForHeadstageIndepData, GetLastSetting, IsTextWave.
Referenced by DAP_CheckSettings, GetLastSettingTextIndepEachRAC, GetLastSettingTextIndepEachSCI, NWB_GenerateDeviceDescription, NWB_GetStartTimeOfSweep, PSQ_PipetteInBath.
variable GetLastSettingIndepRAC(wave numericalValues, variable sweepNo, string setting, variable entrySourceType, variable defValue=defaultValue)
Return a headstage independent setting from the numerical labnotebook of the sweeps in the same RA cycle.
the headstage independent setting or defValue GetLastSetting()
References EnforceIndependentSetting, GetIndexForHeadstageIndepData, GetLastSettingRAC.
variable GetLastSettingIndepSCI(wave numericalValues, variable sweepNo, string setting, variable headstage, variable entrySourceType, variable defValue=defaultValue)
Return a headstage independent setting from the numerical labnotebook of the sweeps in the same RA cycle.
the headstage independent setting or defValue GetLastSetting()
References EnforceIndependentSetting, GetIndexForHeadstageIndepData, GetLastSettingSCI.
Referenced by AD_FillWaves, AD_GetPerSweepFailMessage, AD_GetResultMessage, AD_GetSquarePulseFailMsg, IVS_GetSetQCForSweep, PSQ_Chirp, PSQ_Rheobase, PSQ_SquarePulse, SC_SpikeControl, SC_SpontaneousSpikingCheckQC.
string GetLastSettingTextIndepRAC(wave numericalValues, WaveText textualValues, variable sweepNo, string setting, variable entrySourceType, string defValue=defaultValue)
Return a headstage independent setting from the numerical labnotebook of the sweeps in the same RA cycle.
the headstage independent setting or defValue
References EnforceIndependentSetting, GetIndexForHeadstageIndepData, GetLastSettingTextRAC.
std::tuple< WaveOrNull, variable > GetLastSettingChannel(wave numericalValues, WaveTextOrNull textualValues, variable sweepNo, string setting, variable channelNumber, variable channelType, variable entrySourceType)
Return a numerical or text setting for the given channel.
It also returns headstage independent entries when the given channel refers to an active channel. the wave containing the setting and the index into it. GetLastSettingChannelInternal()
References GetLastSettingChannelInternal.
Referenced by AddChannelUnitFromLBN, AddDAQChannelTypeFromLBN, EP_GetEpochs, GetActiveChannels, GetHeadstageForChannel, NWB_FetchEpochs.
static std::tuple< WaveOrNull, variable > GetLastSettingChannelInternal(wave numericalValues, wave values, variable sweepNo, string setting, variable channelNumber, variable channelType, variable entrySourceType)
Return a numerical/textual setting for the given channel.
The function takes care of associated/unassociated channel properties and all other internals. numericalValues numerical labnotebook values labnotebook to read data from, either numerical or textual sweepNo sweep number setting name of the labnotebook entry to search channelNumber channel number channelType channel type, one of XopChannelConstants entrySourceType type of the labnotebook entry, one of DataAcqModes. If you don't care about the entry source type pass UNKNOWN_MODE. A tuple of the result wave and the index into it. GetLastSettingChannel
References ASSERT_TS, CreateLBNUnassocKey, FindIndizes, GetIndexForHeadstageIndepData, GetLastSetting, IsNaN, IsNumericWave, IsTextWave, ROWS, XOP_CHANNEL_TYPE_ADC, XOP_CHANNEL_TYPE_DAC.
Referenced by GetLastSettingChannel.
wave GetLastSetting(wave values, variable sweepNo, string setting, variable entrySourceType)
Return a numeric/textual wave with the latest value of a setting from the numerical/labnotebook labnotebook for the given sweep number.
values numerical/textual labnotebook sweepNo sweep number setting name of the setting to query entrySourceType type of the labnotebook entry, one of DataAcqModes. If you don't care about the entry source type pass UNKNOWN_MODE. a free wave with LABNOTEBOOK_LAYER_COUNT rows. In case the setting could not be found an invalid wave reference is returned.
References ASSERT_TS, COLS, EnsureLargeEnoughWave, EntrySourceTypeMapper, GetLastSettingNoCache, GetLBIndexCache, GetLBRowCache, IsNaN, IsTextWave, IsValidSweepNumber, LABNOTEBOOK_GET_RANGE, LABNOTEBOOK_MISSING_VALUE, LABNOTEBOOK_UNCACHED_VALUE, LAYERS, NUMBER_OF_LBN_DAQ_MODES, ROWS.
Referenced by AB_FillListWave, AB_GetSettingNumFiniteVals, AD_FillWaves, AD_GetBaselineChunkFailMsg, AD_GetBaselineFailMsg, AD_GetPerSweepFailMessage, AD_PlotBounds, AFH_GetSweepsFromSameSCINC, AR_ComputeRanges, BSP_RemoveDisabledChannels, CalculateTPLikePropsFromSweep, CreateTiledChannelGraph, ED_WriteChangedValuesToNote, ED_WriteChangedValuesToNoteText, FitResistance, GetLastSettingChannelInternal, GetLastSettingEachRAC, GetLastSettingEachSCI, GetLastSettingIndep, GetLastSettingRAC, GetLastSettingSCI, GetLastSettingTextEachRAC, GetLastSettingTextEachSCI, GetLastSettingTextIndep, GetLastSettingTextRAC, GetLastSettingTextSCI, GetTTLBits, GetTTLChannels, GetTTLChannelsOrBits, GetTTLLabnotebookEntry, IVS_GetSetQCForSweep, LastStimSetRun, LBV_AddTraceToLBGraphTPStorage, MSQ_FastRheoEst, MSQ_GetPulseDurations, NWB_AddSweepDataSets, NWB_AppendSweepLowLevel, NWB_GetStimsetFromSweepGeneric, NWB_GetTimeSeriesProperties, OVS_UpdateSweepSelectionChoices, PA_GetPulseInfos, PSQ_Chirp, PSQ_CR_DetermineBoundsAction, PSQ_CR_GetCycles, PSQ_DAScale, PSQ_DS_GetDAScaleOffset, PSQ_FoundAtLeastOneSpike, PSQ_GetLastPassingLongRHSweep, PSQ_GetPulseDurations, PSQ_PipetteInBath, PSQ_Ramp, PSQ_Rheobase, PSQ_SquarePulse, ReachTargetVoltage, SB_GetSweepPropertyFromNumLBN, SBE_AddMissingADTraceInfo, SBE_ExportSweepBrowser, SC_GetHeadstageQCForSetCount, SC_GetSetSweepCount, SC_GetTrials, SC_LastSweepInSet, SC_ReactToQCFailures, SC_SpontaneousSpikingCheckQC, WB_OpenStimulusSetInWaveBuilder.
wave GetLastSettingNoCache(wave values, variable sweepNo, string setting, variable entrySourceType, variable *first=defaultValue, variable *last=defaultValue, variable *rowIndex=defaultValue)
Return a wave with the latest value of a setting from the numerical/textual labnotebook for the given sweep number. Uncached version, general users should prefer GetLastSetting().
values numerical/textual labnotebook sweepNo sweep number setting name of the setting to query entrySourceType type of the labnotebook entry, one of DataAcqModes first [optional] Can be used to query and return the labnotebook row range. Useful for routines which must make a lot of queries to the same sweep and want to avoid the overhead of calculating first and last. Passing LABNOTEBOOK_GET_RANGE will set the calculated values of first and last after the function returns. Passing a value greater or equal zero will use these values instead. last [optional] see first rowIndex [optional] return the row where the setting could be found, otherwise it is set to LABNOTEBOOK_MISSING_VALUE a free wave with LABNOTEBOOK_LAYER_COUNT rows. In case the setting could not be found an invalid wave reference is returned.
References ASSERT_TS, COLS, DATA_ACQUISITION_MODE, DEBUGPRINT_TS, FindRange, GET_LB_MODE_NONE, GET_LB_MODE_READ, GET_LB_MODE_WRITE, GetSweepColumn, HasOneValidEntry, IsFinite, IsTextWave, LABNOTEBOOK_GET_RANGE, LABNOTEBOOK_MISSING_VALUE, LAYERS, TEST_PULSE_MODE, UNKNOWN_MODE.
Referenced by GetLastSetting.
wave GetLastSettingTextRAC(wave numericalValues, WaveText textualValues, variable sweepNo, string setting, variable entrySourceType)
Return the last textual value of the sweeps in the same RA cycle.
GetLastSetting()
References AFH_GetSweepsFromSameRACycle, GetLastSetting, ROWS.
Referenced by GetLastSettingTextIndepRAC.
wave GetLastSettingRAC(wave numericalValues, variable sweepNo, string setting, variable entrySourceType)
Return the last numerical value of the sweeps in the same RA cycle.
GetLastSetting()
References AFH_GetSweepsFromSameRACycle, GetLastSetting, ROWS.
Referenced by GetLastSettingIndepRAC.
wave GetLastSettingIndepEachRAC(wave numericalValues, variable sweepNo, string setting, variable entrySourceType, variable defValue=defaultValue)
Return the last numerical value for the given setting of each sweep in the same RA cycle.
The returned wave will have NaN for sweeps which do not have that entry. This is done in order to keep the indizes intact. GetLastSetting()
References AFH_GetSweepsFromSameRACycle, GetLastSettingIndep, HasOneValidEntry, ROWS.
wave GetLastSettingTextIndepEachRAC(wave numericalValues, WaveText textualValues, variable sweepNo, string setting, variable entrySourceType, string defValue=defaultValue)
Return the last textual value for the given setting of each sweep in the same RA cycle.
The returned wave will have NaN for sweeps which do not have that entry. This is done in order to keep the indizes intact. GetLastSetting()
References AFH_GetSweepsFromSameRACycle, GetLastSettingTextIndep, ROWS.
wave GetLastSettingEachRAC(wave numericalValues, variable sweepNo, string setting, variable headstage, variable entrySourceType)
Return the last numerical value for the given setting of each sweep for a given headstage in the same RA cycle.
The returned wave will have NaN for sweeps which do not have that entry. This is done in order to keep the indizes intact. GetLastSetting
References AFH_GetSweepsFromSameRACycle, ASSERT_TS, GetLastSetting, HasOneValidEntry, NUM_HEADSTAGES, ROWS.
wave GetLastSettingTextEachRAC(wave numericalValues, WaveText textualValues, variable sweepNo, string setting, variable headstage, variable entrySourceType)
Return the last textual value for the given setting of each sweep for a given headstage in the same RA cycle.
The returned wave will have NaN for sweeps which do not have that entry. This is done in order to keep the indizes intact. GetLastSetting()
References AFH_GetSweepsFromSameRACycle, ASSERT_TS, GetLastSetting, NUM_HEADSTAGES, ROWS.
Referenced by SC_ReactToQCFailures.
wave GetLastSettingTextSCI(wave numericalValues, WaveText textualValues, variable sweepNo, string setting, variable headstage, variable entrySourceType)
Return the last textual value of the sweeps in the same stimset cycle.
GetLastSetting()
References AFH_GetSweepsFromSameSCI, GetLastSetting, ROWS.
Referenced by AD_GetDAScaleFailMsg, PSQ_GetLastPassingDAScaleSub.
wave GetLastSettingSCI(wave numericalValues, variable sweepNo, string setting, variable headstage, variable entrySourceType)
Return the last numerical value of the sweeps in the same stimset cycle.
GetLastSetting()
References AFH_GetSweepsFromSameSCI, GetLastSetting, ROWS.
Referenced by AD_GetSquarePulseFailMsg, GetLastSettingIndepSCI, MSQ_DAScale, MSQ_FastRheoEst, MSQ_GetLastPassingLongRHSweep, MSQ_GetPulseDurations, PSQ_GetLastPassingLongRHSweep, PSQ_Rheobase, ReachTargetVoltage.
wave GetLastSettingIndepEachSCI(wave numericalValues, variable sweepNo, string setting, variable headstage, variable entrySourceType, variable defValue=defaultValue)
Return the last numerical value for the given setting of each sweep in the same stimset cycle.
The returned wave will have NaN for sweeps which do not have that entry. This is done in order to keep the indizes intact. GetLastSetting()
References AFH_GetSweepsFromSameSCI, GetLastSettingIndep, HasOneValidEntry, ROWS.
Referenced by AD_FillWaves, AD_GetChirpFailMsg, AD_GetDAScaleFailMsg, AD_GetPerSweepFailMessage, AD_GetSquarePulseFailMsg, PSQ_AddLabnotebookEntriesToJSON, PSQ_CR_SetHasPassed, PSQ_DAScale, PSQ_SquarePulse.
wave GetLastSettingTextIndepEachSCI(wave numericalValues, WaveText textualValues, variable sweepNo, variable headstage, string setting, variable entrySourceType, string defValue=defaultValue)
Return the last textual value for the given setting of each sweep in the same stimset cycle.
The returned wave will have NaN for sweeps which do not have that entry. This is done in order to keep the indizes intact. GetLastSetting()
References AFH_GetSweepsFromSameSCI, GetLastSettingTextIndep, ROWS.
wave GetLastSettingEachSCI(wave numericalValues, variable sweepNo, string setting, variable headstage, variable entrySourceType)
Return the last numerical value for the given setting of each sweep for a given headstage in the same stimset cycle.
The returned wave will have NaN for sweeps which do not have that entry. This is done in order to keep the indizes intact. GetLastSetting
References AFH_GetSweepsFromSameSCI, ASSERT_TS, GetLastSetting, HasOneValidEntry, NUM_HEADSTAGES, ROWS.
Referenced by AD_FillWaves, AD_GetChirpFailMsg, AD_GetDAScaleFailMsg, AD_GetFastRheoEstFailMsg, AD_GetRheobaseFailMsg, AD_GetSpikeControlFailMsg, MSQ_FastRheoEst, MSQ_GetLBNEntryForHeadstageSCI, MSQ_GetLBNEntryForHSSCIBool, PSQ_AddLabnotebookEntriesToJSON, PSQ_CR_SetHasPassed, PSQ_DAScale, PSQ_Rheobase, SC_GetTrials.
wave GetLastSettingTextEachSCI(wave numericalValues, WaveText textualValues, variable sweepNo, string setting, variable headstage, variable entrySourceType)
Return the last textual value for the given setting of each sweep for a given headstage in the same stimset cycle.
The returned wave will have NaN for sweeps which do not have that entry. This is done in order to keep the indizes intact. GetLastSetting()
References AFH_GetSweepsFromSameSCI, ASSERT_TS, GetLastSetting, NUM_HEADSTAGES, ROWS.
wave GetNonEmptyLBNRows(wave labnotebookValues, string setting)
Return a wave with all labnotebook rows which have a non-empty entry for setting.
References COLS, FindIndizes, LAYERS, PROP_NON_EMPTY.
Referenced by GetLastSweepWithSetting, GetLastSweepWithSettingText, GetSweepsWithSetting.
wave GetSweepsWithSetting(wave labnotebookValues, string setting)
Return a wave with all sweep numbers which have a non-empty entry for setting.
labnotebookValues numerical/textual labnotebook setting name of the value to search a 1D free wave with the matching sweep numbers. In case the setting could not be found an invalid wave reference is returned.
References GetNonEmptyLBNRows, GetSweepColumn, GetUniqueEntries, IsTextWave, ROWS, ZapNaNs.
Referenced by MSQ_GetLastPassingLongRHSweep, NWB_CheckForMissingSweeps, PSQ_GetLastPassingDAScaleSub, PSQ_GetLastPassingLongRHSweep, RecreateMissingSweepAndConfigWaves, SWS_DeleteDataWaves.
wave GetLastSweepWithSetting(wave numericalValues, string setting, variable *sweepNo)
Return the last numerical value of a setting from the labnotebook and the sweep it was set.
numericalValues numerical labnotebook setting name of the value to search sweepNo sweep number the value was last set a free wave with LABNOTEBOOK_LAYER_COUNT rows. In case the setting could not be found an invalid wave reference is returned.
References ASSERT_TS, GetNonEmptyLBNRows, GetSweepColumn, IsNumericWave, LAYERS, ROWS.
Referenced by GetLastSweepWithSettingIndep, GetLBIndexCache, GetLBRowCache, PA_GenerateAllPulseWaves.
variable GetLastSweepWithSettingIndep(wave numericalValues, string setting, variable *sweepNo, variable defValue=defaultValue)
Return the last numerical value of a headstage independent setting from the labnotebook and the sweep it was set.
numericalValues numerical labnotebook setting name of the value to search sweepNo sweep number the value was last set defValue [optional, defaults to NaN] value to return in case nothing could be found
References EnforceIndependentSetting, GetIndexForHeadstageIndepData, GetLastSweepWithSetting.
Referenced by DAP_CheckSettings, PSQ_Rheobase.
wave GetLastSweepWithSettingText(WaveText textualValues, string setting, variable *sweepNo)
Return the last textual value of a setting from the labnotebook and the sweep it was set.
textualValues textual labnotebook setting name of the value to search sweepNo sweep number the value was last set a free wave with LABNOTEBOOK_LAYER_COUNT rows. In case the setting could not be found an invalid wave reference is returned.
References ASSERT_TS, GetNonEmptyLBNRows, GetSweepColumn, IsTextWave, LAYERS, ROWS.
Referenced by GetLastSweepWithSettingTextI, GetLBIndexCache, GetLBRowCache.
string GetLastSweepWithSettingTextI(wave numericalValues, string setting, variable *sweepNo, string defValue=defaultValue)
Return the last textual value of a headstage independent setting from the labnotebook and the sweep it was set.
numericalValues numerical labnotebook setting name of the value to search sweepNo sweep number the value was last set defValue [optional, defaults to an empty string] value to return in case nothing could be found
References EnforceIndependentSetting, GetIndexForHeadstageIndepData, GetLastSweepWithSettingText.
string GetAllDevices()
Returns a list of all devices, e.g. "ITC18USB_Dev_0;..." which were locked at some point.
References COUNTOBJECTS_DATAFOLDER, GetDAQDevicesFolder, GetDAQDevicesFolderAsString, GetDevicePathAsString, GetListOfObjects, HW_ITC_BuildDeviceString, ITC_DEVICE_REGEXP, RemovePrefix.
Referenced by GetAllDevicesWithContent, SaveExperimentSpecial.
static variable DeviceHasUserComments(string device)
References DAG_GetTextualValue, DAP_GetCommentNotebook, GetNotebookText, GetUserComment, IsEmpty, ROStr, WindowExists.
Referenced by GetAllDevicesWithContent.
string GetAllDevicesWithContent(variable contentType=defaultValue)
Returns a list of all devices, e.g. "ITC18USB_Dev_0;", which have content.
contentType [optional, defaults to CONTENT_TYPE_SWEEP] type of content to look for, one of CONTENT_TYPES
References CONTENT_TYPE_COMMENT, CONTENT_TYPE_SWEEP, CONTENT_TYPE_TPSTORAGE, COUNTOBJECTS_WAVES, dataPath, DeviceHasUserComments, GetAllDevices, GetDeviceDataPathAsString, GetDeviceTestPulseAsString, GetListOfObjects, TP_STORAGE_REGEXP.
Referenced by DB_GetAllDevicesWithData, IsAppropriateExperiment, NWB_ExportAllData, NWB_FirstStartTimeOfAllSweeps, SaveExperimentSpecial.
variable KillOrMoveToTrash(WaveOrNull wv=defaultValue, dfref dfr=defaultValue)
Convenience wrapper for KillOrMoveToTrashPath()
References DataFolderExistsDFR, KillOrMoveToTrashPath.
Referenced by AB_LoadLabNotebook, AB_LoadLabNotebookFromIgor, AB_LoadLabNotebookFromNWB, AB_LoadStimsetRAW, AB_LoadStimsetTemplateWaves, AB_LoadSweepFromFile, AB_LoadSweepFromIgor, AB_LoadWave, AB_SplitSweepIntoComponents, AdjustDAScale, CA_FlushCache, DAP_LockDevice, DAP_UnlockDevice, DB_SplitSweepsIfReq, DB_WindowHook, DC_Configure, DC_UpdateGlobals, DownsampleWindowHook, ExtractLogbookSlice, FitResistance, GetLBNumericalDescription, GetTPResults, IH_RemoveAmplifierConnWaves, MoveWaveWithOverwrite, MSQ_CreateOverrideResults, NWB_LoadCustomWave, OOD_CalculateOffsetsYoked, PA_MakeAverageWavePermanent, PA_PreProcessPulses, PSQ_DAScale, RA_PerfInitialize, ReachTargetVoltage, ReplaceWaveWithBackup, SB_SweepBrowserWindowHook, StoreWaveOnDisk, TP_CreateOverrideResults, TP_ROAnalysis, TP_SetupCommon, UpgradeDataFolderLocation, WB_CreateAndGetStimSet, WB_FillWaveFromFormula, WB_KillParameterWaves, WB_KillStimset, WB_MakeStimsetThirdParty, WBP_ChangeWaveType, WBP_CreateWaveBuilderPanel, WBP_LoadSet, WBP_MainWindowHook, WBP_StartupSettings.
variable KillOrMoveToTrashPath(string path)
Delete a datafolder or wave. If this is not possible, because Igor has locked the file, the wave or datafolder is moved into a trash folder named root:mies:trash_$digit.
The trash folders will be removed, if possible, from KillTemporaries(). path absolute path to a datafolder or wave
References DEBUGPRINT_TS, MoveToTrash.
Referenced by AB_ClearAnalysisFolder, AB_LoadTPStorageFromIgor, AverageWavesFromSameYAxisIfReq, IH_KillStimSets, IH_KillTemporaries, KillOrMoveToTrash.
variable MoveToTrash(WaveOrNull wv=defaultValue, dfref dfr=defaultValue)
References DataFolderExistsDFR, GetUniqueTempPath.
Referenced by KillOrMoveToTrashPath, RecreateConfigWaveFromLBN, RecreateMissingSweepAndConfigWaves.
wave GetDAQDataSingleColumnWaves(dfref sweepDFR, variable channelType)
Return a wave reference wave with all single column waves of the given channel type.
Holds invalid wave refs for non-existing entries. sweepDFR datafolder reference with 1D sweep data channelType One of XopChannelConstants GetDAQDataSingleColumnWave() or SplitSweepIntoComponents()
References ASSERT, DataFolderExistsDFR, GetDAQDataSingleColumnWave, GetNumberFromType.
Referenced by AR_HandleRanges, GetSingleSweepWaves, SBE_AddMissingADTraceInfo.
wave GetDAQDataSingleColumnWave(dfref sweepDFR, variable channelType, variable channelNumber, variable splitTTLBits=defaultValue, variable ttlBit=defaultValue)
Return a 1D data wave previously created by SplitSweepIntoComponents()
Returned wave reference can be invalid. sweepDFR datafolder holding 1D waves channelType One of XopChannelConstants channelNumber channel number splitTTLBits [optional, defaults to false] return a single bit of the TTL wave ttlBit [optional] number specifying the TTL bit
References ASSERT, GetNumberFromType, XOP_CHANNEL_NAMES, XOP_CHANNEL_TYPE_TTL.
Referenced by AR_ComputeRanges, CreateTiledChannelGraph, GetDAQDataSingleColumnWaves, PA_GenerateAllPulseWaves, PA_GetPulseInfos.
variable IsValidSweepNumber(variable sweepNo)
Check if the given sweep number is valid.
References IsInteger.
Referenced by AB_LoadAllSweepsAndStimsets, AFH_GetSweepsFromSameRACycle, AFH_GetSweepsFromSameSCI, AS_GetSweepNumber, BSP_GetLogbookWave, DAP_SetVarProc_NextSweepLimit, ExtractSweepNumber, GetAnalysisSweepDataPathAS, GetLastSetting, GetSingleSweepFolderAsString, MSQ_DS_GetDAScaleOffset, NWB_FirstStartTimeOfAllSweeps, OVS_IgnoreHeadstageInOverlay, PA_GenerateAllPulseWaves, PSQ_Chirp, PSQ_DS_GetDAScaleOffset, PSQ_Rheobase, WB_GetWaveNoteEntry.
variable IsValidEpochNumber(variable epochNo)
Check if the given epoch number is valid.
References IsInteger, WB_TOTAL_NUMBER_OF_EPOCHS.
Referenced by PA_RetrievePulseInfosFromEpochs, WB_GetWaveNoteEntry, WBP_InitialTabHook, WBP_LoadSet.
wave GetConfigWave(wave sweepWave)
Returns the config wave for a given sweep wave.
References ExtractSweepNumber.
Referenced by AFH_ExtractOneDimDataFromSweep, AppendEntries, ButtonDoIt, ButtonRestoreBackup, CalculateTPLikePropsFromSweep, DB_AddSweepToGraph, DB_SplitSweepsIfReq, DB_UpdateSweepPlot, MSQ_DeterminePulseDuration, MSQ_SearchForSpikes, NWB_ExportAllData, PSQ_DeterminePulseDuration, PSQ_SearchForSpikes, SWS_SaveAcquiredData.
wave GetSweepWave(string device, variable sweepNo)
Returns the, possibly non existing, sweep data wave for the given sweep number.
References GetDeviceDataPath.
Referenced by AFH_GetLastSweepAcquired, AFH_GetLastSweepWaveAcquired, AFM_CallAnalysisFunctions, DB_SplitSweepsIfReq, ED_WriteChangedValuesToNote, ED_WriteChangedValuesToNoteText, MSQ_DeterminePulseDuration, MSQ_FastRheoEst, PSQ_DAScale, PSQ_DeterminePulseDuration, PSQ_Rheobase, PSQ_SquarePulse, SC_SpontaneousSpikingCheckQC, SWS_SaveAcquiredData.
string GetConfigWaveName(variable sweepNo)
Return the config wave name.
References GetSweepWaveName.
Referenced by GetAnalysisConfigWave, SWS_SaveAcquiredData.
string GetSweepWaveName(variable sweepNo)
Return the sweep wave name.
Referenced by GetConfigWaveName, SWS_SaveAcquiredData.
variable GetSamplingInterval(wave config)
Returns the sampling interval of the sweep in microseconds (1e-6s)
References ASSERT_TS, IsConstant, IsValidConfigWave.
Referenced by AppendEntries, CreateTiledChannelGraph, NWB_AppendSweepLowLevel.
variable GetDataOffset(wave config)
Returns the data offset of the sweep in points.
References ASSERT_TS, IsConstant, IsValidConfigWave.
Referenced by SCOPE_ITC_AdjustFIFOPos.
variable UpdateSweepConfig(wave config, variable samplingInterval=defaultValue)
Write the given property to the config wave.
Please add new properties as required config configuration wave samplingInterval sampling interval in microseconds (1e-6s)
References ASSERT, IsFinite.
Referenced by ButtonDoIt.
variable GetHardwareType(string device)
Return the hardware type of the device.
One of HardwareDACTypeConstants
References ASSERT_TS, DEVICE_TYPES_ITC, HARDWARE_ITC_DAC, HARDWARE_NI_DAC, HARDWARE_UNSUPPORTED_DAC, IsEmpty, ParseDeviceString.
Referenced by DAP_CheckHeadStage, DAP_CheckPressureSettings, DAP_CheckSettings, DAP_OneTimeCallAfterDAQ, DAP_OneTimeCallBeforeDAQ, DAP_UnlockDevice, DAP_UpdateDeviceInfoWaves, DC_CalculateDAQDataWaveLength, DC_ChannelCalcForDAQConfigWave, DC_CheckIfDataWaveHasBorderVals, DC_Configure, DC_GetConfiguration, DC_LongestOutputWave, DC_MakeHelperWaves, DC_PlaceDataInDAQConfigWave, DQM_AddDevice, DQM_BkrdDataAcq, DQM_StartDAQMultiDevice, DQM_StopDataAcq, DQM_TerminateOngoingDAQHelper, GetDAQDataWave, GetDevicePathAsString, GetDevSpecLabNBFolderAsString, GetTTLWave, HW_OpenDevice, PSQ_GetDefaultSamplingFrequencyForSingleHeadstage, PSQ_Ramp, SCOPE_UpdateOscilloscopeData, SI_CalculateMinSampInterval, SWS_GetChannelGains, TP_Setup, TPM_AddDevice, TPM_BkrdTPMD, TPM_StopTPMDWrapper.
variable ParseDeviceString(string device, string *deviceType, string *deviceNumber)
Parse a device string: for ITC devices of the form X_DEV_Y, where X is from DEVICE_TYPES_ITC and Y from DEVICE_NUMBERS. for NI devices of the form X, where X is from DAP_GetNIDeviceList()
Returns the result in deviceType and deviceNumber. Currently the parsing is successfull if for ITC devices X and Y are non-empty. for NI devices X is non-empty. deviceNumber is empty for NI devices as it does not apply device input device string X_DEV_Y deviceType returns the device type X deviceNumber returns the device number Y one on successfull parsing, zero on error
References isEmpty.
Referenced by DeviceCanFollow, GetDevicePathAsString, GetDevSpecLabNBFolderAsString, GetHardwareType, GetPopupMenuDeviceListWithData, HW_OpenDevice, IsITC1600, NWB_GenerateDeviceDescription, OOD_StorePreload, P_GetDevicePressureFolderAS, ParsePopupItem, SI_GetMinSampIntWave, SI_ITC_CalculateMinSampInterval.
variable LayoutGraph(string win, TiledGraphSettings *tgs)
Layout the DataBrowser/SweepBrowser graph.
Takes also care of adding free axis for the headstage display. Concept: Block [#]: One axis with surrounded GRAPH_DIV_SPACING space Slot [#]: Unit of vertical space, a block can occupy multiple slots We have 100% space for all axes AD axes should occupy four times the space of DA/TTL channels So DA/TTL occupy one slot, AD occupy four slots Between each axes we want GRAPH_DIV_SPACING clear space Count the number of vertical blocks and slots to be used Derive the space per slot For overlay channels we reserve only one slot times slot multiplier per channel The display order from top to bottom: Associated channels (above: DA, below: AD) with increasing headstage number Unassociated channels (above: DA, below: AD) TTL channels For overlayed channels we have up to three blocks (DA, AD, TTL) in that order.
References ADC_SLOT_MULTIPLIER, ASSERT, ConvertToUniqueNumber, EnableAxis, EPOCH_SLOT_MULTIPLIER, GetGraphUserData, GetMainWindow, GetUniqueEntries, GRAPH_DIV_SPACING, GrepWave, RemoveFreeAxisFromGraph, ROWS, TiledGraphSettings::splitTTLBits, TUD_GetUserDataAsWave, TweakAxes.
Referenced by PostPlotTransformations.
static variable TweakAxes(string graph, TiledGraphSettings *tgs, WaveText allVerticalAxes, WaveText allHorizontalAxes)
References TiledGraphSettings::dDAQDisplayMode, ROWS.
Referenced by LayoutGraph.
static variable EnableAxis(string graph, WaveText axes, variable spacePerSlot, variable *first, variable *last)
Helper function for LayoutGraph()
Enables the given axis between [last - spacePerSlot, last] and updates both on return. Expects last to be 1.0 on the first call.
References ASSERT, GRAPH_DIV_SPACING, ROWS.
Referenced by LayoutGraph.
variable GetNextTraceIndex(string graph)
Helper function for CreateTiledChannelGraph and friends.
Return the next trace index for a graph which uses our trace data storage wave.
References ASSERT, GetGraphUserData, IsFinite, TUD_GetTraceCount.
Referenced by DB_AddSweepToGraph, SB_AddSweepToGraph.
variable CreateTiledChannelGraph(string graph, wave config, variable sweepNo, wave numericalValues, WaveText textualValues, TiledGraphSettings *tgs, dfref sweepDFR, WaveText axisLabelCache, variable *traceIndex, string experiment, wave channelSelWave, BufferedDrawInfo *bdi=defaultValue)
Create a vertically tiled graph for displaying AD and DA channels.
For preservering the axis scaling callers should do the following: embed:rst:leading-asterisk * .. code-block:: igorpro * * WAVE ranges = GetAxesRanges(graph) * * CreateTiledChannelGraph() * * SetAxesRanges(graph, ranges) * graph window config DAQ config wave sweepNo number of the sweep numericalValues numerical labnotebook wave textualValues textual labnotebook wave tgs settings for tuning the display, see TiledGraphSettings sweepDFR top datafolder to splitted 1D sweep waves axisLabelCache store existing vertical axis labels traceIndex [internal use only] set to zero on the first call in a row of successive calls experiment name of the experiment the sweep stems from channelSelWave channel selection wave bdi [optional, default = n/a] initialized BufferedDrawInfo structure, when given draw calls are buffered instead for later execution OVS_EndIncrementalUpdate
References AFH_GetChannelUnit, ASSERT, ASSERT_TS, BSP_RemoveDisabledChannels, BUFFEREDDRAWAPPEND, BUFFEREDDRAWDDAQAXES, BUFFEREDDRAWHIDDENTRACES, BUFFEREDDRAWLABEL, CLAMPMODE_ENTRY_KEY, ControlWindowToFront, DAQ_CHANNEL_TYPE_DAQ, DATA_ACQUISITION_MODE, DataFolderExistsDFR, TiledGraphSettings::dDAQDisplayMode, TiledGraphSettings::dDAQHeadstageRegions, DEBUGPRINT, TiledGraphSettings::displayADC, TiledGraphSettings::displayDAC, TiledGraphSettings::displayTTL, EnsureLargeEnoughWave, FindIndizes, GetADCListFromConfig, GetDACListFromConfig, GetDAQDataSingleColumnWave, GetHeadstageColor, GetIndexForHeadstageIndepData, GetLastSetting, GetLastSettingIndep, GetNumberFromWaveNote, GetRowIndex, GetSamplingInterval, GetSingleSweepFolder, GetTraceNamePrefix, GetTTLListFromConfig, HARDWARE_ITC_DAC, TiledGraphSettings::hideSweep, HORIZ_AXIS_BASE_NAME, isEmpty, IsFinite, LABNOTEBOOK_LAYER_COUNT, NOTE_INDEX, NUM_CHANNEL_TYPES, NUM_HEADSTAGES, NUM_ITC_TTL_BITS_PER_RACK, TiledGraphSettings::overlayChannels, PopCount, PROP_NON_EMPTY, ROWS, SetNumberInWaveNote, TiledGraphSettings::splitTTLBits, TUD_SetUserDataFromWaves, VERT_AXIS_BASE_NAME, XOP_CHANNEL_TYPE_ADC, XOP_CHANNEL_TYPE_DAC, XOP_CHANNEL_TYPE_TTL.
Referenced by DB_AddSweepToGraph, DB_UpdateSweepPlot, SB_AddSweepToGraph, SB_UpdateSweepPlot.
string GetTraceNamePrefix(variable traceIndex)
Return a trace name prefix suitable for GetNextTraceIndex()
References TRACE_NAME_NUM_DIGITS.
Referenced by AR_HandleRanges, AverageWavesFromSameYAxisIfReq, CreateTiledChannelGraph, PA_ShowPulses.
variable TiledGraphAccelerateDraw(BufferedDrawInfo *bdi)
Runs through all graph groups in the json and appends them to the graph.
References AccelerateHideTraces, BUFFEREDDRAWAPPEND, BUFFEREDDRAWDDAQAXES, BUFFEREDDRAWHIDDENTRACES, BUFFEREDDRAWLABEL, BufferedDrawInfo::jsonID, ROWS, TiledGraphAccelerateAppendTracesImpl, BufferedDrawInfo::traceWaves.
Referenced by OVS_EndIncrementalUpdate.
static variable TiledGraphAccelerateAppendTracesImpl(string w, string v, string h, variable r, variable g, variable b, wave y, WaveText t, WaveRefWave d)
Appends a group of traces to a graph, properties w to b must be constant for the group.
w name of graph window v name of vertical axis h name of horizontal axis r red color component g green color component b blue color component y 1D wave with indices into wave d for the actual plot data t 1D wave with trace names, same size as y d wave reference wave with plot data
References ASSERT, ROWS.
Referenced by TiledGraphAccelerateDraw.
std::tuple< RGBColor > GetHeadstageColor(variable headstage, string channelType=defaultValue, variable activeChannelCount=defaultValue, variable channelSubNumber=defaultValue)
Return the color of the given headstage.
headstage Headstage, can be NaN for non-associated channels channelType [optional, empty by default] The channel type for non-associated channels, currently only "TTL" is supported activeChannelCount [optional, empty by default] For plotting "TTL" channels only channelSubNumber [optional, empty by default] For plotting "TTL" channels only, "TTL Bit" information when plotting each on its own
References DEBUGPRINT, GetTraceColor, IsFinite, NUM_HEADSTAGES.
Referenced by CreateRelevantColorsGraph, CreateTiledChannelGraph, LBV_AddTagsForTextualLBNEntries, LBV_AddTraceToLBGraph, LBV_AddTraceToLBGraphTPStorage, SCOPE_SetADAxisLabel.
variable EquallySpaceAxis(string graph, string axisRegExp=defaultValue, variable axisOffset=defaultValue, variable axisOrientation=defaultValue, variable sortOrder=defaultValue, string listForBegin=defaultValue, string listForEnd=defaultValue)
Space the matching axis in an equal manner.
graph graph axisRegExp [optional, defaults to ".*"] regular expression matching the axes names axisOffset [optional, defaults to 0] offset of first axis in parts of total width axisOrientation [optional, defaults to all] allows to apply equalization to all axis of one orientation sortOrder [optional, defaults to no sorting (NaN)] apply different sorting schemes to list of axes, see sortingOrder parameter of SortList listForBegin [optional, defaults to an empty list] list of axes to move to the front of the sorted axis list listForEnd [optional, defaults to an empty list] list of axes to move to the end of the sorted axis list
References ASSERT, DistributeElements, GetAllAxesWithOrientation, IsEmpty, IsFinite, SortAxisList.
Referenced by LBV_AddTraceToLBGraph, LBV_AddTraceToLBGraphTPStorage, SBE_ExportSweepBrowser.
variable EquallySpaceAxisPA(string graph, string allAxes, string distAxes, variable axisOffset=defaultValue)
This is a light weight adapted version of.
EquallySpaceAxis It allows to give a list of distAxes that do not require to exist. Non-existing axes are taken into account on the distribution, but are skipped when the graph is accessed. Also removing images from a graph does not update AxisList until the graph is updated, so we can not rely on Axislist here as we do the Layout after pending changes So with allAxes = "1;2;3;4;" and distAxes = "2;3;" axis 2 and 3 are set at 25% to 50% and 50% to 75% respectively. graph Name of graph where axes from distAxes list exist allAxes List of all axes, that should be distributed. May include non-existing axes. distAxes List of axes that are distributed. Only axes that appear in allAxes as well are modified. axisOffset [optional, default = 0] offset between 0 and 1 where distribution starts.
References ASSERT, DistributeElements.
Referenced by PA_LayoutGraphs.
variable SaveExperimentSpecial(variable mode)
Save the current experiment under a new name and clear all/some data.
mode mode for generating the experiment name, one of SaveExperimentModes
References ASSERT, CallFunctionForEachListItem, CallFunctionForEachListItem_TS, CleanupExperimentName, CloseNWBFile, COUNTOBJECTS_DATAFOLDER, CreateHistoryNotebook, DAP_ClearCommentNotebook, DateTimeInUTC, DB_ClearAllGraphs, GetAllDevices, GetAllDevicesWithContent, GetCacheFolderAS, GetDeviceDataPathAsString, GetDevicePath, GetDeviceTestPulse, GetExperimentName, GetLabNotebookFolderAsString, GetListOfLockedDevices, GetListOfObjects, GetTimeStamp, PACKED_FILE_EXPERIMENT_SUFFIX, PGC_SetAndActivateControl, RemoveTracesFromGraph, SAVE_AND_CLEAR, SAVE_AND_SPLIT, SaveExperimentWrapper, SCOPE_GetGraph, SIBLING_FILENAME_SUFFIX, UniqueFileOrFolder, UNTITLED_EXPERIMENT.
Referenced by DC_Configure.
string CleanupExperimentName(string expName)
Cleanup the experiment name.
References RemoveEndingRegExp, SIBLING_FILENAME_SUFFIX.
Referenced by NWB_GetFileForExport, SaveExperimentSpecial.
variable GetNumberFromType(variable var=defaultValue, string str=defaultValue, variable xopVar=defaultValue)
Return the maximum count of the given type.
var numeric channel types str string channel types xopVar numeric XOP channel types
References ASSERT_TS, CHANNEL_TYPE_ADC, CHANNEL_TYPE_ALARM, CHANNEL_TYPE_ASYNC, CHANNEL_TYPE_DAC, CHANNEL_TYPE_HEADSTAGE, CHANNEL_TYPE_TTL, NUM_AD_CHANNELS, NUM_ASYNC_CHANNELS, NUM_DA_TTL_CHANNELS, NUM_HEADSTAGES, XOP_CHANNEL_TYPE_ADC, XOP_CHANNEL_TYPE_DAC, XOP_CHANNEL_TYPE_TTL.
Referenced by BSP_GUIToChannelSelectionWave, CreateLBNUnassocKey, DAG_ControlStatusWave, DAG_GetChannelState, DAG_GetChannelTextual, DAP_CheckProc_Channel_All, DAP_PopMenuChkProc_StimSetList, DAP_SetVarProc_Channel_Search, DAP_SetVarProc_DA_Scale, DAP_TurnOffAllChannels, GetActiveChannels, GetAllDAEphysPopMenuIndex, GetAllDAEphysPopMenuString, GetAllDAEphysSetVarNum, GetAllDAEphysSetVarTxT, GetDAQDataSingleColumnWave, GetDAQDataSingleColumnWaves, PA_GeneratePulseWaveName.
wave ExtractOneDimDataFromSweep(wave config, wave sweep, variable index)
Extract an one dimensional wave from the given sweep/hardware data wave and column.
config config wave sweep sweep wave or hardware data wave from all hardware types index index into sweep, can be queried with AFH_GetDAQDataColumn a reference to a free wave with the single channel data
References AFH_GetChannelUnits, ASSERT_TS, COLS, IsValidSweepAndConfig, IsWaveRefWave, ROWS.
Referenced by AFH_ExtractOneDimDataFromSweep, CalculateTPLikePropsFromSweep, NWB_AppendSweepLowLevel, SplitSweepIntoComponents.
variable PostPlotTransformations(string win, variable mode, WaveOrNull additionalData=defaultValue)
Perform common transformations on the graphs traces.
Keeps track of all internal details wrt. to the order of the operations, backups, etc. Needs to be called after adding/removing/updating sweeps via AddSweepToGraph(), RemoveSweepFromGraph(), UpdateSweepInGraph(). win graph with sweep traces mode update mode, one of PostPlotUpdateModes additionalData [optional, defaults to invalid wave reference] additional data for subsequent users. Currently supported: POST_PLOT_REMOVED_SWEEPS -> OVS indizes of the removed sweep POST_PLOT_ADDED_SWEEPS -> OVS indizes of the added sweep Use OVS_GetSweepAndExperiment() to convert an index into a sweep/experiment pair.
References AR_HighlightArtefactsEntry, ASSERT, AverageWavesFromSameYAxisIfReq, BSP_AddTracesForEpochs, BSP_GatherTiledGraphSettings, BSP_ScaleAxes, GetAllSweepTraces, GetMainWindow, InitPostPlotSettings, LayoutGraph, LBV_Update, PA_Update, POST_PLOT_ADDED_SWEEPS, POST_PLOT_CONSTANT_SWEEPS, POST_PLOT_FULL_UPDATE, POST_PLOT_REMOVED_SWEEPS, SF_Update, TimeAlignMainWindow, ZeroTracesIfReq.
Referenced by BSP_DoTimeAlignment, DB_UpdateSweepPlot, OVS_EndIncrementalUpdate, OVS_MainListBoxProc, OVS_UpdateHeadstageRemoval, SB_UpdateSweepPlot.
static variable InitPostPlotSettings(string win, PostPlotSettings *pps)
References PostPlotSettings::averageDataFolder, PostPlotSettings::averageTraces, BSP_GetFolder, BSP_GetPanel, GetCheckBoxState, GetPopupMenuIndex, GetPopupMenuString, GetSetVariable, PostPlotSettings::hideSweep, MIES_BSP_PANEL_FOLDER, PostPlotSettings::timeAlignLevel, PostPlotSettings::timeAlignment, PostPlotSettings::timeAlignMode, PostPlotSettings::timeAlignRefTrace, PostPlotSettings::visualizeEpochs, PostPlotSettings::zeroTraces.
Referenced by PostPlotTransformations.
variable TimeAlignMainWindow(string graph, PostPlotSettings *pps)
Time Alignment for the BrowserSettingsPanel.
This function should work for any given reference trace in pps.timeAlignRefTrace in the popup menu. (DB and SB) graph graph with sweep traces pps settings
References GetCursorXPositionAB, PostPlotSettings::timeAlignLevel, PostPlotSettings::timeAlignment, TimeAlignmentIfReq, PostPlotSettings::timeAlignMode, PostPlotSettings::timeAlignRefTrace.
Referenced by PostPlotTransformations.
string TimeAlignGetAllTraces(string graph)
return a list of all traces relevant for TimeAlignment
References GetAllSweepTraces, TextWaveToList.
Referenced by TimeAlignCursorMovedHook, TimeAlignHandleCursorDisplay.
variable TimeAlignHandleCursorDisplay(string win)
Adds or removes the cursors from the graphs depending on the panel settings.
win main DB/SB graph or any subwindow panel.
References BSP_GetPanel, FindCursorInGraphs, GetCheckBoxState, GetMainWindow, GetPopupMenuString, isEmpty, KillCursorInGraphs, ROWS, TimeAlignGetAllTraces.
Referenced by TimeAlignUpdateControls.
variable TimeAlignUpdateControls(string win)
Enable/Disable TimeAlignment Controls and Cursors.
References BSP_GetPanel, DisableControl, DisableControls, EnableControl, EnableControls, GetCheckBoxState, GetMainWindow, GetPopupMenuIndex, TIME_ALIGNMENT_LEVEL_FALLING, TIME_ALIGNMENT_LEVEL_RISING, TimeAlignHandleCursorDisplay.
Referenced by UpdateSettingsPanel.
variable TimeAlignCursorMovedHook(WMWinHookStruct *s)
References BSP_GetPanel, GetCheckBoxState, GetMainWindow, isEmpty, PGC_SetAndActivateControl, ROWS, TimeAlignGetAllTraces, TUD_GetUserData, TUD_GetUserDataAsWave.
wave GetAllSweepTraces(string graphs, variable region=defaultValue, variable channelType=defaultValue, variable prefixTraces=defaultValue)
Get a textwave of all traces from a list of graphs.
graphs semicolon separated list of graph names region [optional] return only traces with the specified region userdata entry channelType [optional] return only the traces with the given channel type prefixTraces [optional, defaults to true] prefix the traces names with the graph name and a # graph::trace named patterns
References GetSweepUserData.
Referenced by PostPlotTransformations, SBE_GetSourceGraphADTraces, TimeAlignGetAllTraces, TimeAlignmentIfReq.
wave GetSweepUserData(string graph, string key, variable channelType=defaultValue, variable region=defaultValue)
References TUD_GetUserDataAsWave, XOP_CHANNEL_NAMES.
Referenced by GetAllSweepTraces.
static variable AverageWavesFromSameYAxisIfReq(string graph, variable averagingEnabled, dfref averageDataFolder, variable hideSweep)
Average traces in the graph from the same y-axis and append them to the graph.
graph graph with traces create by CreateTiledChannelGraph averagingEnabled switch if averaging is enabled or not averageDataFolder permanent datafolder where the average waves can be stored hideSweep are normal channel traces hidden or not
References AXIS_ORIENTATION_BOTTOM, AXIS_ORIENTATION_TOP, CalculateAverage, CallFunctionForEachListItem_TS, DEBUG_TIMER_START, DEBUGPRINT_ELAPSED, ExtractFromSubrange, GetAxisOrientation, GetListOfObjects, GetTraceColor, GetTraceNamePrefix, IsEmpty, IsFinite, KillOrMoveToTrashPath, ListHasOnlyOneUniqueEntry, NUM_HEADSTAGES, panel, RemoveEmptyDataFolder, RemovePrefix, ROWS, TUD_GetUserData, TUD_GetUserDataAsWave, TUD_RemoveUserData, TUD_SetUserData, VERT_AXIS_BASE_NAME, WaveListHasSameWaveNames.
Referenced by PostPlotTransformations.
wave CalculateAverage(WaveRefWave waveRefs, dfref averageDataFolder, string averageWaveName, variable skipCRC=defaultValue, variable writeSourcePaths=defaultValue, wave inputAverage=defaultValue)
Calculate the average of a list of waves, wrapper for MIES_fWaveAverage().
For performance enhancements: The average waves are cached References to existing average waves are returned in case they already exist waveRefs waves to average in a wave reference wave averageDataFolder folder where the data is to be stored averageWaveName base name of the averaged data skipCRC [optional, defaults to false] Add the average wave CRC as suffix to its name writeSourcePaths [optional, defaults to true] Write the full paths of the source waves into the average wave note inputAverage [optional, defaults to invalid wave ref] Override the average calculation and use the given wave as result. This is relevant for callers which want to leverage MultiThread statements together with MIES_fWaveAverage. wave reference to the average wave
References AddEntryIntoWaveNoteAsList, ASSERT, CA_AveragingKey, CA_OPTS_NO_DUPLICATE, CA_StoreEntryIntoCache, CA_TryFetchingEntryFromCache, ClearRTError, ConvertFreeWaveToPermanent, GetNumberFromWaveNote, IGOR_TYPE_64BIT_FLOAT, MIES_fWaveAverage, NOTE_KEY_WAVE_MAXIMUM, SetNumberInWaveNote.
Referenced by AverageWavesFromSameYAxisIfReq.
wave ConvertFreeWaveToPermanent(wave freeWave, dfref dfr, string wName)
Converts a free wave to a permanent wave with Overwrite.
freeWave wave that should be converted to a permanent wave dfr data folder where permanent wave is stored wName name of permanent wave that is created wave reference to the permanent wave
Referenced by CalculateAverage, PA_MakeAverageWavePermanent.
static variable ZeroTracesIfReq(string graph, WaveTextOrNull traces, variable zeroTraces)
Zero all given traces.
References ROWS, ZeroWave.
Referenced by PostPlotTransformations.
variable TimeAlignmentIfReq(string graphtrace, variable mode, variable level, variable pos1x, variable pos2x, variable force=defaultValue)
Perform time alignment of features in the sweep traces.
graphtrace reference trace in the form of graph::trace mode time alignment mode level level input to the FindLevel operation in CalculateFeatureLoc pos1x specify start range for feature position pos2x specify end range for feature position force [optional, defaults to false] redo time aligment regardless of wave note
References ASSERT, CalculateFeatureLoc, DEBUGPRINT, GetAllSweepTraces, GetNumberFromWaveNote, GetRowIndex, isEmpty, IsFinite, IsNaN, MinMax, NOTE_KEY_TIMEALIGN, NOTE_KEY_TIMEALIGN_TOTAL_OFFSET, ROWS, SetNumberInWaveNote, TIME_ALIGNMENT_NONE, TUD_GetUserData.
Referenced by TimeAlignMainWindow.
static variable CalculateFeatureLoc(wave wv, variable mode, variable level, variable first, variable last)
Find the given feature in the given wave range first and last are in x coordinates and clipped to valid values.
References ASSERT, TIME_ALIGNMENT_LEVEL_FALLING, TIME_ALIGNMENT_LEVEL_RISING, TIME_ALIGNMENT_MAX, TIME_ALIGNMENT_MIN, TIME_ALIGNMENT_NONE.
Referenced by TimeAlignmentIfReq.
variable EqualizeVerticalAxesRanges(string graph, variable ignoreAxesWithLevelCrossing=defaultValue, variable level=defaultValue, variable rangePerClampMode=defaultValue)
Equalize all vertical axes ranges so that they cover the same range.
graph graph ignoreAxesWithLevelCrossing [optional, defaults to false] ignore all vertical axis which cross the given level in the visible range level [optional, defaults to zero] level to be used for ignoreAxesWithLevelCrossing=1 rangePerClampMode [optional, defaults to false] use separate Y ranges per clamp mode
References ASSERT, AssertOnAndClearRTError, AXIS_ORIENTATION_LEFT, AXIS_ORIENTATION_RIGHT, COLS, GetAxisOrientation, IsFinite, NUM_CLAMP_MODES, ROWS, TUD_GetUserData, TUD_GetUserDataAsWave.
Referenced by BSP_ScaleAxes, SBE_ExportSweepBrowser.
variable ExtractSweepNumber(string str)
Extract the sweep number from a $something_* string.
References ASSERT_TS, IsValidSweepNumber, WAVE_BACKUP_SUFFIX.
Referenced by AB_LoadSweepsFromExperiment, AFH_GetLastSweepAcquired, CalculateTPLikePropsFromSweep, DB_GetPlainSweepList, GetConfigWave, NWB_CheckForMissingSweeps, NWB_ExportAllData, NWB_FirstStartTimeOfAllSweeps, ReachTargetVoltage, SB_GetIndexFromSweepDataPath, SWS_DeleteDataWaves.
string GetListOfUnlockedDevices()
Return the list of unlocked DA_Ephys panels.
Referenced by CONF_RestoreDAEphys, DAP_UpdateAllYokeControls.
string GetListOfLockedDevices()
Return the list of locked devices.
Referenced by ButtonProc_Hrdwr_P_UpdtDAClist, BWO_SelectDevice, CloseNWBFile, DAP_CheckSettings, DAP_DeviceIsUnlocked, DAP_LockDevice, DAP_SerializeAllCommentNBs, DAP_UnlockAllDevices, DAP_UnlockDevice, DAP_UpdateAllYokeControls, DAP_UpdateDaEphysStimulusSetPopups, DAP_UpdateListOfPressureDevices, DB_GetAllDevicesWithData, DQ_GetNumDevicesWithDAQRunning, FFI_ReturnTPValues, GetListOfLockedITC1600Devices, P_CloseDevice, P_CloseDeviceLowLevel, P_Disable, P_Enable, P_FindDeviceExecutingPP, P_OpenDevice, SaveExperimentSpecial, ST_RemoveStimSet, TP_GetNumDevicesWithTPRunning, TP_StopTestPulseOnAllDevices.
string GetListOfLockedITC1600Devices()
Return the list of locked ITC1600 devices.
References GetListOfLockedDevices.
Referenced by DAP_ListOfITCDevices, DAP_UpdateAllYokeControls.
variable GetStimSetType(string setName)
Return the type, CHANNEL_TYPE_DAC, CHANNEL_TYPE_TTL or CHANNEL_TYPE_UNKNOWN, of the stimset.
All callers must ensure that they can handle the unexpected CHANNEL_TYPE_UNKNOWN properly.
References WB_SplitStimsetName.
Referenced by AB_LoadStimsetRAW, AB_LoadStimsetTemplateWaves, DAP_DeleteStimulusSet, NWB_LoadStimset, ST_SetStimsetParameter, WB_CreateAndGetStimSet, WB_GetLastModStimSet, WB_GetSegWvTypeForSet, WB_GetStimSet, WB_GetWaveParamForSet, WB_GetWaveTextParamForSet, WB_KillStimset, WB_ParameterWvsNewerThanStim, WB_StimsetExists, WB_StimsetHasLatestNoteVersion, WB_UpgradeCustomWaves.
dfref GetSetFolder(variable channelType)
Return the stimset folder from the numeric channelType, CHANNEL_TYPE_DAC or CHANNEL_TYPE_TTL.
Data Folder reference to Stimset dataFolder
References ASSERT, CHANNEL_TYPE_DAC, CHANNEL_TYPE_TTL, GetWBSvdStimSetDAPath, GetWBSvdStimSetTTLPath.
Referenced by AB_LoadStimsetRAW, ST_GetStimsetList, WB_CreateAndGetStimSet, WB_FillWaveFromFormula, WB_GetLastModStimSet, WB_KillStimset, WB_ParameterWvsNewerThanStim, WB_StimsetExists, WB_StimsetHasLatestNoteVersion, WB_UpdateEpochCombineList, WB_UpgradeCustomWaveInWPT.
string GetSetFolderAsString(variable channelType)
Return the stimset folder from the numeric channelType, CHANNEL_TYPE_DAC or CHANNEL_TYPE_TTL.
String with full path to Stimset dataFolder
References ASSERT, CHANNEL_TYPE_DAC, CHANNEL_TYPE_TTL, GetWBSvdStimSetDAPathAsString, GetWBSvdStimSetTTLPathAsString.
Referenced by AB_LoadCustomWaves.
dfref GetSetParamFolder(variable channelType)
Get the stimset parameter folder.
channelType CHANNEL_TYPE_DAC or CHANNEL_TYPE_TTL dataFolder as DFREF
References ASSERT, CHANNEL_TYPE_DAC, CHANNEL_TYPE_TTL, GetWBSvdStimSetParamDAPath, GetWBSvdStimSetParamTTLPath.
Referenced by AB_LoadStimsetTemplateWaves, NWB_LoadStimset, ST_GetStimsetList, WB_GetSegWvTypeForSet, WB_GetWaveParamForSet, WB_GetWaveTextParamForSet, WB_SaveStimSet.
string GetSetParamFolderAsString(variable channelType)
Get the stimset parameter folder.
channelType CHANNEL_TYPE_DAC or CHANNEL_TYPE_TTL dataFolder as String
References ASSERT, CHANNEL_TYPE_DAC, CHANNEL_TYPE_TTL, GetWBSvdStimSetParamPathAS.
Referenced by AB_LoadStimsetTemplateWaves.
variable GetTTLBits(wave numericalValues, variable sweep, variable channel)
Get the TTL bit mask from the labnotebook.
numericalValues Numerical labnotebook values sweep Sweep number channel TTL hardware channel
References DATA_ACQUISITION_MODE, GetIndexForHeadstageIndepData, GetLastSetting.
Referenced by NWB_AppendSweepLowLevel, SplitSweepIntoComponents.
static wave GetTTLChannelsOrBits(wave numericalValues, wave textualValues, variable sweep)
Return a wave with the used TTL channels/bits which are indexed by DAEphys TTL channels.
numericalValues Numerical labnotebook values textualValues Text labnotebook values sweep Sweep number
References DATA_ACQUISITION_MODE, GetIndexForHeadstageIndepData, GetLastSetting, HW_ITC_GetRackRange, IGOR_TYPE_32BIT_FLOAT, ListToNumericWave, NUM_DA_TTL_CHANNELS, RACK_ONE, RACK_ZERO.
Referenced by GetActiveChannels.
static wave GetTTLChannels(wave numericalValues, wave textualValues, variable sweep)
Return a wave with the used TTL channels which are indexed by DAEphys TTL channels.
The returned wave is not hardware independent. For ITC hardware this will only ever return at most one active channel. numericalValues Numerical labnotebook values textualValues Text labnotebook values sweep Sweep number
References DATA_ACQUISITION_MODE, GetIndexForHeadstageIndepData, GetLastSetting, ListToNumericWave, NUM_DA_TTL_CHANNELS.
Referenced by GetActiveChannels.
wave GetActiveChannels(wave numericalValues, wave textualValues, variable sweepNo, variable channelType, variable TTLmode=defaultValue)
Return a fixed size wave with the the active channels for the given channel type.
The function takes into account unassociated DA/AD channels as well. It returns fixed size waves with the active entries having the same value as their index. This allows users to either remove unused entries and use the wave as active entries list or use the whole wave where not being NaN is active. With the following DAEphys setup (only the first four channels are shown) embed:rst:leading-asterisk * * +----+----+----+-----+ * | Nr | DA | AD | TTL | * +====+====+====+=====+ * | 0 | | • | | * +----+----+----+-----+ * | 1 | • | | | * +----+----+----+-----+ * | 2 | | | • | * +----+----+----+-----+ * | 3 | | | • | * +----+----+----+-----+ * * this function returns the following: * * - ``DA``: ``{NaN, 1, NaN, NaN, ...}`` * - ``AD``: ``{0, NaN, NaN, NaN, ...}`` * - ``TTL``: * * - NI hardware (regardless of TTLmode): ``{NaN, NaN, 2, 3, ...}`` * - ITC hardware (ITC18 specifically) with TTLmode: * * - ``TTL_DAEPHYS_CHANNEL``: ``{NaN, NaN, 2, 3, ...}`` * - ``TTL_HARDWARE_CHANNEL``: ``{NaN, 1, NaN, NaN, ...}`` * * HW_ITC_GetITCXOPChannelForRack numericalValues Numerical labnotebook values textualValues Text labnotebook values sweepNo Sweep number channelType One of XopChannelConstants TTLmode [optional, defaults to TTL_DAEPHYS_CHANNEL] One of ActiveChannelsTTLMode. Does only apply to TTL channels.
References ASSERT_TS, DATA_ACQUISITION_MODE, GetLastSettingChannel, GetNumberFromType, GetTTLChannels, GetTTLChannelsOrBits, TTL_DAEPHYS_CHANNEL, TTL_HARDWARE_CHANNEL, XOP_CHANNEL_TYPE_ADC, XOP_CHANNEL_TYPE_DAC, XOP_CHANNEL_TYPE_TTL.
Referenced by AddChannelPropertiesFromLBN, RecreateSweepWaveFromBackupAndLBN.
variable GetIndexForHeadstageIndepData(wave values)
Return the index for headstage independent data.
Before dfe2d862 (Make the function AB_SplitTTLWaveIntoComponents available for all, 2015-10-07) we stored headstage independent data in either all entries or only the first one. Since that commit we store the data in INDEP_HEADSTAGE.
References INDEP_HEADSTAGE, LAYERS, NUM_HEADSTAGES.
Referenced by CreateTiledChannelGraph, GetLastSettingChannelInternal, GetLastSettingIndep, GetLastSettingIndepRAC, GetLastSettingIndepSCI, GetLastSettingTextIndep, GetLastSettingTextIndepRAC, GetLastSweepWithSettingIndep, GetLastSweepWithSettingTextI, GetTTLBits, GetTTLChannels, GetTTLChannelsOrBits, GetTTLLabnotebookEntry.
wave GetTTLLabnotebookEntry(WaveText textualValues, string name, variable sweep)
Return a list of TTL stimsets which are indexed by DAEphys TTL channels.
The indexing here is hardware independent. For ITC hardware the assertion "log(ttlBit)/log(2) == DAEphys TTL channel" holds. textualValues Text labnotebook values name One of LabnotebookTTLNames sweep Sweep number
References DATA_ACQUISITION_MODE, GetIndexForHeadstageIndepData, GetLastSetting, NUM_DA_TTL_CHANNELS.
Referenced by NWB_AppendSweepLowLevel, NWB_GetStimsetFromSweepGeneric, OVS_UpdateSweepSelectionChoices.
string GetWaveBuilderParameterTypeName(variable type)
Return the name short String of the Parameter Wave used in the WaveBuilder.
type One of ParameterWaveTypes name as string
References STIMSET_PARAM_SEGWVTYPE, STIMSET_PARAM_WP, STIMSET_PARAM_WPT.
Referenced by NWB_LoadAllStimsets, WB_GetParameterWaveName.
wave GetAllDAEphysSetVarNum(string device, variable channelType, variable controlType)
Returns the mode of all setVars in the DA_Ephys panel of a controlType.
References GetNumberFromType, GetPanelControl, GetSetVariable.
Referenced by DAG_RecordGuiStateNum.
wave GetAllDAEphysSetVarTxT(string device, variable channelType, variable controlType)
Returns the mode of all setVars in the DA_Ephys panel of a controlType.
References GetNumberFromType, GetPanelControl, GetSetVariableString.
Referenced by DAG_RecordGuiStateTxT.
wave GetAllDAEphysPopMenuIndex(string device, variable channelType, variable controlType)
Returns the index of all popupmenus in the DA_Ephys panel of a controlType.
References GetNumberFromType, GetPanelControl, GetPopupMenuIndex.
Referenced by DAG_RecordGuiStateNum.
wave GetAllDAEphysPopMenuString(string device, variable channelType, variable controlType)
Returns the string contents of all popupmenus in the DA_Ephys panel of a controlType.
References GetNumberFromType, GetPanelControl, GetPopupMenuString.
Referenced by DAG_RecordGuiStateTxT.
string ExtractAnalysisFuncFromStimSet(wave stimSet, variable eventType)
Extract the analysis function name from the wave note of the stim set.
Analysis function for the given event type, empty string if none is set
References ASSERT, EVENT_NAME_LIST, IsEmpty, STIMSET_ENTRY, WB_GetWaveNoteEntry.
Referenced by AFM_UpdateAnalysisFunctionWave, DAP_CheckAnalysisFunctionAndParameter.
string ExtractAnalysisFunctionParams(wave stimSet)
Return the analysis function parameters as comma (,) separated list.
GetWaveBuilderWaveTextParam() for the exact format.
References ANALYSIS_FUNCTION_PARAMS_STIMSET, STIMSET_ENTRY, WB_GetWaveNoteEntry.
Referenced by AFM_UpdateAnalysisFunctionWave, DAP_CheckAnalysisFunctionAndParameter.
variable SplitTTLWaveIntoComponents(wave data, variable ttlBits, dfref targetDFR, string wavePrefix, variable rescale)
Split TTL data into a single wave for each bit.
This function is only for data from ITC hardware. data 1D channel data extracted by ExtractOneDimDataFromSweep ttlBits bit mask of the active TTL channels form e.g. GetTTLBits targetDFR datafolder where to put the waves, can be a free datafolder wavePrefix prefix of the created wave names rescale One of TTLRescalingOptions. Rescales the data to be in the range [0, 1] when on, does no rescaling when off. The created waves will be named TTL_3_3 so the final suffix is the running TTL Bit.
References ASSERT_TS, IsFinite, NUM_ITC_TTL_BITS_PER_RACK, TTL_RESCALE_OFF, TTL_RESCALE_ON.
Referenced by NWB_AppendSweepLowLevel, SplitSweepIntoComponents.
variable CloseNWBFile()
Close a possibly open export-into-NWB file.
We have only one NWB file open for all running devices
References CallFunctionForEachListItem, DEBUGPRINT, GetListOfLockedDevices, IsFinite, NWB_ASYNC_FinishWriting.
Referenced by DAP_UnlockDevice, NWB_ExportAllData, NWB_ExportAllStimsets, NWB_ExportWithDialog, SaveExperimentSpecial.
variable IsDeviceActiveWithBGTask(string device, string task)
Check wether the given background task is running and that the device is active in multi device mode.
References DEBUGPRINT, GetActiveDAQDevicesTimerFolder, GetActiveDevicesTPMD, GetDQMActiveDeviceList, IsBackgroundTaskRunning, TASKNAME_FIFOMON, TASKNAME_FIFOMONMD, TASKNAME_TIMER, TASKNAME_TIMERMD, TASKNAME_TP, TASKNAME_TPMD.
Referenced by AI_ZeroAmps, DQ_StopOngoingDAQHelper, TP_CheckIfTestpulseIsRunning.
string CalcHashForFile(string path, variable method=defaultValue)
Calculate a cryptographic hash for the file contents of path.
path absolute path to a file method [optional, defaults to SHA-2 with 256 bytes] Type of cryptographic hash function
References ASSERT, FileExists, LoadTextFile.
Referenced by CheckIfPathsRefIdenticalFiles, CHI_CheckXOP, CONF_AddConfigFileUserData.
variable CheckIfPathsRefIdenticalFiles(string list)
Check if the file paths referenced in list are pointing to identical files.
References CalcHashForFile.
Referenced by CHI_CheckXOP.
variable RemoveFreeAxisFromGraph(string graph)
Remove all free axis from the given graph.
Referenced by DB_ClearAllGraphs, DB_UpdateSweepPlot, LayoutGraph, LBV_ClearGraph, SB_UpdateSweepPlot.
variable RemoveImagesFromGraph(string graph)
Remove all images from a graph.
Referenced by PA_ClearGraphs.
variable RemoveDrawLayers(string graph)
Remove all draw layers from the graph.
References ASSERT, ROWS.
Referenced by LBV_ClearGraph.
variable RemoveTracesFromGraph(string graph, string trace=defaultValue, WaveOrNull wv=defaultValue, dfref dfr=defaultValue)
Remove traces from a graph and optionally try to kill their waves.
graph graph trace [optional, default: all] remove the given trace only wv [optional, default: ignored] remove all traces which stem from the given wave dfr [optional, default: ignored] remove all traces which stem from one of the waves in dfr Only one of trace/wv/dfr may be supplied.
References ASSERT, AssertOnAndClearRTError, DataFolderExistsDFR, GetListOfObjects, GetRowIndex.
Referenced by DB_ClearAllGraphs, DB_UpdateSweepPlot, LBV_ClearGraph, LBV_SwitchLBGraphXAxis, PA_ClearGraphs, PA_ShowPulses, SaveExperimentSpecial, SB_UpdateSweepPlot, SCOPE_CreateGraph, WBP_DisplaySetInPanel, WBP_ShowFFTSpectrumIfReq.
variable CreateBackupWavesForAll(dfref dfr)
Create backup waves for all waves in the datafolder.
References COUNTOBJECTS_WAVES, CreateBackupWave.
Referenced by SplitSweepIntoComponents.
wave CreateBackupWave(wave wv, variable forceCreation=defaultValue)
Create a backup of the wave wv if it does not already exist or if forceCreation is true.
The backup wave will be located in the same data folder and its name will be the original name with WAVE_BACKUP_SUFFIX appended.
References ASSERT, IsGlobalWave, WAVE_BACKUP_SUFFIX.
Referenced by AB_CollapseListEntry, AB_ExpandListEntry, AB_ListBoxProc_ExpBrowser, AB_LoadSweepFromNWBgeneric, AB_ResetListBoxWaves, ButtonDoIt, CreateBackupWavesForAll, PA_CreateAndFillPulseWaveIfReq, SI_CompressWave.
wave GetBackupWave(wave wv)
Return a wave reference to the possibly not existing backup wave.
References ASSERT, IsGlobalWave, WAVE_BACKUP_SUFFIX.
Referenced by ButtonRestoreBackup, ReplaceWaveWithBackup.
variable ReplaceWaveWithBackupForAll(dfref dfr)
Replace all waves from the datafolder with their backup.
References COUNTOBJECTS_WAVES, ReplaceWaveWithBackup.
Referenced by BSP_ButtonProc_RestoreData.
wave ReplaceWaveWithBackup(wave wv, variable nonExistingBackupIsFatal=defaultValue, variable keepBackup=defaultValue)
Replace the wave wv with its backup. If possible the backup wave will be killed afterwards.
wv wave to replace by its backup nonExistingBackupIsFatal [optional, defaults to true] behaviour for the case that there is no backup. Passing a non-zero value will abort if the backup wave does not exist, with zero it will just do nothing. keepBackup [optional, defaults to false] don't delete the backup after restoring from it wave reference to the restored data, in case of no backup an invalid wave reference
References DoAbortNow, GetBackupWave, KillOrMoveToTrash.
Referenced by AB_LoadSweepFromIgor, ButtonRestoreBackup, PA_ResetWavesIfRequired, ReplaceWaveWithBackupForAll.
variable SaveExperimentWrapper(string path, string filename, variable overrideInteractiveMode=defaultValue)
Returns 1 if the user cancelled, zero if SaveExperiment was called.
It is currently not possible to check if SaveExperiment was successfull (E-Mail from Howard Rodstein WaveMetrics, 30 Jan 2015) path Igor symbolic path where the experiment should be stored filename filename of the experiment including suffix, usually PACKED_FILE_EXPERIMENT_SUFFIX overrideInteractiveMode [optional, defaults to GetInteractiveMode()] Overrides the current setting of the interactive mode
References isEmpty.
Referenced by SaveExperimentSpecial.
variable SearchForDuplicates(wave wv)
Detects duplicate values in a 1d wave.
one if duplicates could be found, zero otherwise
References ASSERT, ROWS.
Referenced by CONF_JSONToWindow, CONF_WindowToJSON, DAP_CheckSettings.
variable DeviceCanFollow(string device)
Check that the device can act as a follower.
References ParseDeviceString.
Referenced by DAP_UpdateYokeControls, DeviceIsFollower, GetChanAmpAssign, RA_YokedRABckgTPCallRACounter, RA_YokedRAStartMD.
variable IsITC1600(string device)
Check that the device is of type ITC1600.
References ASSERT, ParseDeviceString.
Referenced by HW_ITC_CalculateDevChannelOff, HW_ITC_GetITCXOPChannelForRack, HW_ITC_GetRackForTTLBit, P_PrepareITCWaves, P_TTLforPpulse.
variable DeviceIsFollower(string device)
Check that the device is a follower.
References DeviceCanFollow, ITC1600_FIRST_DEVICE.
Referenced by DAP_GetRAAcquisitionCycleID, DAP_UpdateITIAcrossSets, DAP_UpdateSweepLimitsAndDisplay, DAP_UpdateYokeControls, OOD_CalculateOffsetsYoked, TP_GetTPCycleID.
variable DeviceCanLead(string device)
Check that the device can act as a leader.
References ITC1600_FIRST_DEVICE.
Referenced by DAP_ButtonProc_Lead, DAP_UpdateAllYokeControls, DC_PrepareLBNEntries, DeviceHasFollower, GetChanAmpAssign, GetListofLeaderAndPossFollower.
variable DeviceHasFollower(string device)
Check that the device is a leader and has followers.
References DeviceCanLead.
Referenced by AI_UpdateAmpModel, DAP_CheckSettings, DAP_UnlockDevice, DAP_UpdateSweepLimitsAndDisplay, DQM_StartDAQMultiDevice, GetPopupMenuDeviceListWithData, IDX_HandleIndexing, IDX_MaxNoOfSweeps, OOD_CalculateOffsetsYoked, RA_GetTotalNumberOfSweeps, RA_SkipSweeps, RA_StartMD, RA_YokedRABckgTPCallRACounter, RA_YokedRAStartMD, TPM_BkrdTPFuncMD, TPM_StartTPMultiDeviceLow.
string GetListofLeaderAndPossFollower(string device)
Convenience wrapper for GetFollowerList()
For iterating over a list of all followers and the leader. Returns just device if the device can not lead.
References DeviceCanLead.
Referenced by DAP_SyncGuiFromLeaderToFollower, DAP_UpdateSweepLimitsAndDisplay, DQ_StopOngoingDAQ, DQM_CallFuncForDevicesYoked, RA_AreLeaderAndFollowerFinished, RA_FinishAcquisition.
string GetProgramFilesFolder()
Return a path to the program folder with trailing dir separator.
Hardcoded as Igor does not allow to query that information. Distinguishes between i386 and x64 Igor versions
Referenced by AI_GetMCCWinFilePath.
string GetDefaultElectrodeName(variable headstage)
Return the default name of a electrode.
References ASSERT_TS, NUM_HEADSTAGES.
Referenced by GetCellElectrodeNames, NWB_AppendSweepLowLevel.
string CreateLBNUnassocKey(string setting, variable channelNumber, variable channelType)
Create a labnotebook key for unassociated channels.
We support two types of unassociated keys. Old style, prior to 403c8ec2 (Merge pull request #370 from AllenInstitute/feature/sweepformula_enable, 2019-11-13) but after its introduction in ad8dc8ec (Allow AD/DA channels not associated with a headstage again, 2015-10-22) are written as "$Name UNASSOC_$ChannelNumber". New style have the format "$Name u_(AD|DA)$ChannelNumber", these include the channel type to make them more self explaining.
References ASSERT_TS, GetNumberFromType, IsEmpty, IsFinite, IsInteger, IsNaN, XOP_CHANNEL_NAMES, XOP_CHANNEL_TYPE_ADC, XOP_CHANNEL_TYPE_DAC.
Referenced by DC_DocumentChannelProperty, GetLastSettingChannelInternal, NWB_AppendSweepLowLevel.
variable IsUnassocLBNKey(string name)
Check if the given labnotebook entry is from an unassociated DA/AD channel.
References LBN_UNASSOC_REGEXP, LBN_UNASSOC_REGEXP_LEGACY.
string RemoveUnassocLBNKeySuffix(string name)
Remove the unassociated, old and new, prefix of the given labnotebook entry name.
CreateLBNUnassocKey()
References LBN_UNASSOC_REGEXP, LBN_UNASSOC_REGEXP_LEGACY.
variable StartZeroMQSockets(variable forceRestart=defaultValue)
Start the ZeroMQ sockets and the message handler.
Debug note: Tracking the connection state can be done via netstat | grep $port. The binded port only shows up after a successfull connection with zeromq_client_connect() is established.
References ASSERT, AssertOnAndClearRTError, ConvertXOPErrorCode, DEBUGPRINT, DP_DebuggingEnabledForCaller, ZEROMQ_BIND_PUB_PORT, ZEROMQ_BIND_REP_PORT, ZeroMQ_HANDLER_ALREADY_RUNNING, ZEROMQ_NUM_BIND_TRIALS, ZeroMQ_SET_FLAGS_DEBUG, ZeroMQ_SET_FLAGS_DEFAULT, ZeroMQ_SET_FLAGS_LOGGING, ZeroMQ_SET_FLAGS_NOBUSYWAITRECV.
Referenced by IgorBeforeNewHook, IgorStartOrNewHook.
variable SplitSweepIntoComponents(wave numericalValues, variable sweep, wave sweepWave, wave configWave, variable rescale, dfref targetDFR=defaultValue)
Split an DAQDataWave into one 1D-wave per channel/ttlBit.
numericalValues numerical labnotebook sweep sweep number sweepWave DAQDataWave configWave DAQConfigWave targetDFR [optional, defaults to the sweep wave DFR] datafolder where to put the waves, can be a free datafolder rescale One of TTLRescalingOptions
References ASSERT, CreateBackupWavesForAll, ExtractOneDimDataFromSweep, GetTTLBits, isEmpty, IsFinite, IsGlobalDataFolder, IsValidSweepAndConfig, ROWS, SplitTTLWaveIntoComponents, XOP_CHANNEL_NAMES.
Referenced by AB_SplitSweepIntoComponents, DB_SplitSweepsIfReq.
variable AddVersionToPanel(string win, variable version)
Add user data "panelVersion" to the panel.
Referenced by AB_OpenAnalysisBrowser, BSP_DynamicStartupSettings, DAP_CreateDAEphysPanel, DB_OpenDataBrowser, DB_ResetAndStoreCurrentDBPanel, SB_OpenSweepBrowser, WBP_CreateWaveBuilderPanel.
variable HasPanelLatestVersion(string win, variable expectedVersion)
Return 1 if the panel is up to date, zero otherwise.
References GetMainWindow, GetPanelVersion.
Referenced by AB_CheckPanelVersion, AB_OpenAnalysisBrowser, AddSweepToGraph, BSP_CheckProc_ChangedSetting, BSP_GetFolder, BSP_IsActive, BSP_UnHideSettingsPanel, BSP_UpdateSweepControls, DAP_CheckSettings, DAP_LockDevice, DB_ResetAndStoreCurrentDBPanel, DB_UpdateSweepPlot, DB_UpdateToLastSweep, RemoveSweepFromGraph, SB_UpdateSweepPlot, WBP_DisplaySetInPanel.
variable GetPanelVersion(string win)
Get the user data "panelVersion".
win panel window as string numeric panel version greater 0 and -1 if no version is present or -2 if the windows does not exist
References IsNaN, str2numSafe, WindowExists.
Referenced by HasPanelLatestVersion.
variable UpdateSweepPlot(string win)
References BSP_IsDataBrowser, DB_UpdateSweepPlot, SB_UpdateSweepPlot.
Referenced by AR_ButtonProc_RemoveRanges, AR_CheckProc_Update, BSP_ButtonProc_ChangeSweep, BSP_ButtonProc_RestoreData, BSP_CheckBoxProc_ArtRemoval, BSP_CheckProc_ChangedSetting, BSP_SliderProc_ChangedSetting, DB_LockToDevice, DB_SetVarProc_SweepNo, DB_UpdateToLastSweep, OVS_EndIncrementalUpdate, SB_PopupMenuSelectSweep.
variable UpdateSettingsPanel(string win)
update of panel elements and related displayed graphs in BSP
References BSP_GetPanel, BSP_ScaleAxes, TimeAlignUpdateControls.
Referenced by BSP_DoTimeAlignment, BSP_TimeAlignmentLevel, BSP_TimeAlignmentPopup, BSP_TimeAlignmentProc.
wave GetPlainSweepList(string win)
References BSP_IsDataBrowser, DB_GetPlainSweepList, SB_GetPlainSweepList.
Referenced by AD_FillWaves, AD_SelectResult, BSP_ButtonProc_RestoreData, BSP_FirstAndLastSweepAcquired, BSP_GetLogbookWave, LBV_CheckIfXAxisIsTime, OVS_GetSelectedSweeps, OVS_UpdatePanel, OVS_UpdateSweepSelectionChoices.
string ConvertAmplifierModeShortStr(variable mode)
Stringified short version of the clamp mode.
References I_CLAMP_MODE, I_EQUAL_ZERO_MODE, V_CLAMP_MODE.
Referenced by OVS_UpdateSweepSelectionChoices.
string ConvertAmplifierModeToString(variable mode)
Stringified version of the clamp mode.
References I_CLAMP_MODE, I_EQUAL_ZERO_MODE, V_CLAMP_MODE.
Referenced by AI_UpdateAmpModel, DAP_ChangeHeadStageMode, DAP_CheckHeadStage, DAP_PublishClampModeChange.
variable UpdateLeftOverSweepTime(string device, variable fifoPos)
Update the repurposed sweep time global variable.
Currently only useful for handling mid sweep analysis functions.
References ASSERT, DATA_ACQUISITION_MODE, DEBUGPRINT, GetDAQDataWave, IsFinite, ROWS.
Referenced by DQM_FIFOMonitor, DQS_FIFOMonitor.
variable CalculateTPLikePropsFromSweep(wave numericalValues, wave textualValues, wave sweep, wave deltaI, wave deltaV, wave resistance)
Calculate deltaI/deltaV from a testpulse like stimset in "Current Clamp" mode.
Todounify with TP_Delta code add support for evaluating "inserted TP" only embed:rst:leading-asterisk * See :ref:`CalculateTPLikePropsFromSweep_doc` for the full documentation. *
References AFH_GetDAQDataColumn, ASSERT, DATA_ACQUISITION_MODE, DEBUGPRINT, ExtractOneDimDataFromSweep, ExtractSweepNumber, GetConfigWave, GetLastSetting, GetTotalOnsetDelay, NUM_HEADSTAGES, ROWS, WaveMinAndMaxWrapper, XOP_CHANNEL_TYPE_ADC, XOP_CHANNEL_TYPE_DAC.
Referenced by AdjustDAScale, PSQ_DAScale, ReachTargetVoltage.
variable MoveWaveWithOverwrite(wave dest, wave src, variable recursive=defaultValue)
Move the source wave to the location of the given destination wave. The destination wave must be a permanent wave.
Workaround for MoveWave having no /O flag. dest permanent wave src wave (free or permanent) recursive [optional, defaults to false] Overwrite referenced waves in dest with the ones from src (wave reference waves only with matching sizes)
References ASSERT, IsFreeWave, IsWaveRefWave, KillOrMoveToTrash.
Referenced by DC_FillDAQDataWaveForTP.
variable IsValidConfigWave(WaveOrNull config, variable version=defaultValue)
Check if the given wave is a valid ITCConfigWave.
The optional version parameter allows to check if the wave is at least comaptible with this version. The function assumes that higher versions are compatible with lower versions which is for most callers true. For a special case see AFH_GetChannelUnits. config wave reference to a ITCConfigWave version [optional, default=DAQ_CONFIG_WAVE_VERSION], check against a specific version current versions known are 0 (equals NaN), 1, 2
References COLS, DAQ_CONFIG_WAVE_VERSION, GetWaveVersion, ROWS.
Referenced by AB_SortConfigSweeps, AFH_GetChannelUnits, DC_MakeDAQConfigWave, GetChanneListFromDAQConfigWave, GetDataOffset, GetSamplingInterval, GetTypeListFromITCConfig, IsValidSweepAndConfig.
variable IsValidSweepWave(WaveOrNull sweep)
Check if the given wave is a valid DAQDataWave.
References COLS, IsWaveRefWave, ROWS.
Referenced by RecreateConfigWaveFromLBN, RecreateSweepWaveFromBackupAndLBN.
variable IsValidSweepAndConfig(WaveOrNull sweep, WaveOrNull config, variable configVersion=defaultValue)
Check if the two waves are valid and compatible.
sweep sweep wave config config wave configVersion [optional, defaults to DAQ_CONFIG_WAVE_VERSION] minimum required version of the config wave
References COLS, DAQ_CONFIG_WAVE_VERSION, IsValidConfigWave, IsWaveRefWave, ROWS.
Referenced by AB_SplitSweepIntoComponents, DB_AddSweepToGraph, DC_Configure, ExtractOneDimDataFromSweep, RecreateMissingSweepAndConfigWaves, SplitSweepIntoComponents, SWS_SaveAcquiredData.
variable GetNextRandomNumberForDevice(string device)
Return the next random number using the device specific RNG seed.
References ASSERT, GetReproducibleRandom, IsFinite.
Referenced by DAP_GetRAAcquisitionCycleID, DC_GetStimsetAcqCycleID, TP_AutoTPGenerateNewCycleID, TP_GetTPCycleID.
variable EntrySourceTypeMapper(variable entrySourceType)
Maps the labnotebook entry source type, one of DataAcqModes, to a valid wave index.
References IsFinite.
Referenced by GetLastSetting.
variable ReverseEntrySourceTypeMapper(variable mapped)
Rerverse the effect of EntrySourceTypeMapper()
string GetNIFIFOName(variable deviceID)
constructs a fifo name for NI device ADC operations from the deviceID
References HARDWARE_NI_ADC_FIFO.
Referenced by DQM_FIFOMonitor, PSQ_Ramp, SCOPE_NI_UpdateOscilloscope, TPM_BkrdTPFuncMD.
variable GetTotalOnsetDelay(wave numericalValues, variable sweepNo)
Return the total onset delay of the given sweep.
References DATA_ACQUISITION_MODE, GetLastSettingIndep.
Referenced by CalculateTPLikePropsFromSweep, MSQ_FastRheoEst, PA_GenerateAllPulseWaves, PA_GetPulseInfos, PSQ_Rheobase, PSQ_SquarePulse, SC_SpontaneousSpikingCheckQC.
variable IsValidSamplingMultiplier(variable multiplier)
Check if the given multiplier is a valid sampling interval multiplier.
References DAP_GetSamplingMultiplier, IsFinite.
Referenced by MSQ_FastRheoEst_CheckParam, PSQ_CheckParamCommon.
variable ToggleCheckBoxes(string win, string checkBoxIn, string checkBoxPartner, variable checkBoxInState)
Places paired checkboxes in opposite state.
win window name checkBoxIn ctrl checkbox ex. cba.ctrlName checkBoxPartner checkbox that will be placed in opposite state checkBoxInState state of the ctrl checkbox
References DAG_Update, SetCheckBoxState.
Referenced by DAP_CheckProc_IndexingState, DAP_CheckProc_LockedLogic.
variable EqualizeCheckBoxes(string win, string checkBoxIn, string checkBoxPartner, variable checkBoxInState)
Placed paired checkboxes in same state.
win window name checkBoxIn ctrl checkbox ex. cba.ctrlName checkBoxPartner checkbox that will be placed in the same state checkBoxInState state of the ctrl checkbox
References DAG_Update, SetCheckBoxState.
Referenced by DAP_CheckProc_IndexingState, DAP_CheckProc_LockedLogic.
string GetMIESVersionAsString()
Return the MIES version with canonical EOLs.
References NormalizeToEOL.
Referenced by DC_PrepareLBNEntries, NWB_AddGeneratorString.
variable SetupBackgroundTasks()
Referenced by DAP_LockDevice.
variable ZeroWave(wave wv)
Zero the wave using differentiation and integration.
Overwrites the input wave Preserves the WaveNote and adds the entry NOTE_KEY_ZEROED 2D waves are zeroed along each row 0 if nothing was done, 1 if zeroed
References GetNumberFromWaveNote, NOTE_KEY_ZEROED, SetNumberInWaveNote, ZeroWaveImpl.
Referenced by ZeroTracesIfReq.
variable ZeroWaveImpl(wave wv)
Zeroes a wave in place.
References ASSERT_TS, IsFloatingPointWave, ROWS.
Referenced by PA_ZeroWave, ZeroWave.
variable GetDecimatedWaveSize(variable numRows, variable decimationFactor, variable method)
Return the size of the decimated wave.
Query that to create the output wave before calling DecimateWithMethod(). numRows number of rows in the input wave decimationFactor decimation factor, must be an integer and larger than 1 method one of DecimationMethods
References ASSERT, DECIMATION_MINMAX, DECIMATION_NONE, IsEven, IsInteger.
Referenced by DC_MakeHelperWaves, DecimateWithMethod.
variable DecimateWithMethod(wave input, wave output, variable decimationFactor, variable method, variable firstRowInp=defaultValue, variable lastRowInp=defaultValue, variable firstColInp=defaultValue, variable lastColInp=defaultValue, variable firstColOut=defaultValue, variable lastColOut=defaultValue, WaveOrNull factor=defaultValue)
Decimate the the given input wave.
This allows to decimate a given input row range into output rows using the given method. The columns of input/output can be different. The input row coordinates can be used to do a chunked conversion, e.g. when receiving data from hardware. Incomplete chunks will be redone when necessary. Algorithm visualized: embed:rst:leading-asterisk * .. code-block:: text * * Input (16 entries): [ | | | | | | | | | | | | | | | ] * Decimation factor: 4 * Method: MinMax * Output (4 entries): [ min(input[0, 7]) | max(input[0, 7]) | min(input[8, 15]) | max(input[8, 15]) ] * * input wave to decimate output target wave which will be around decimationFactor smaller than input decimationFactor decimation factor, must be an integer and larger than 1 method one of DecimationMethods firstRowInp [optional, defaults to 0] first row input coordinates lastRowInp [optional, defaults to last element] last row in input coordinates firstColInp [optional, defaults to 0] first col in input coordinates lastColInp [optional, defaults to last element] last col in input coordinates firstColOut [optional, defaults to firstColInp] first col in output coordinates lastColOut [optional, defaults to lastColInp] last col in output coordinates factor [optional, defaults to none] factor which is applied to all input columns and written into the output columns
References ASSERT, CA_OPTS_NO_DUPLICATE, CA_StoreEntryIntoCache, CA_TemporaryWaveKey, CA_TryFetchingEntryFromCache, COLS, DEBUGPRINT, DecimateMinMax, DECIMATION_MINMAX, GetDecimatedWaveSize, IsEven, MinMax, ROWS.
Referenced by SCOPE_ITC_UpdateOscilloscope, SCOPE_NI_UpdateOscilloscope.
static variable DecimateMinMax(wave input, wave output, variable idx, variable firstRowInp, variable lastRowInp, variable colInp, variable colOut, variable decimationFactor)
Threadsafe helper function for DecimateWithMethod.
input input wave output output wave idx output pair index firstRowInp first row in input coordinates lastRowInp last row in input coordinates colInp column in input coordinates colOut column in output coordinates decimationFactor decimation factor
References ASSERT_TS.
Referenced by DecimateWithMethod.
variable NewExperiment()
Starts with a new experiment.
You have to manually save before, see SaveExperimentWrapper()
variable ConvertXOPErrorCode(variable xopError)
Remove the volatile part of the XOP error code.
The result is constant and can therefore be compared with constants. From http://www.igorexchange.com/node/7286
Referenced by StartZeroMQSockets.
wave FindIndizes(wave numericOrTextWave, variable col=defaultValue, string colLabel=defaultValue, variable var=defaultValue, string str=defaultValue, variable prop=defaultValue, variable startRow=defaultValue, variable endRow=defaultValue, variable startLayer=defaultValue, variable endLayer=defaultValue)
Extended version of FindValue
Allows to search only the specified column for a value and returns all matching row indizes in a wave. By defaults only looks into the first layer for backward compatibility reasons. When multiple layers are searched startLayer/endLayer the result contains matches from all layers, and this also means the resulting wave is still 1D. Exactly one of var/str/prop has to be given except for prop == PROP_MATCHES_VAR_BIT_MASK and prop == PROP_NOT_MATCHES_VAR_BIT_MASK which requires a var/str parameter as well. Exactly one of col/colLabel has to be given. numericOrTextWave wave to search in col [optional] column to search in only colLabel [optional] column label to search in only var [optional] numeric value to search str [optional] string value to search prop [optional] property to search, see FindIndizesProps startRow [optional] starting row to restrict the search to endRow [optional] ending row to restrict the search to startLayer [optional, defaults to zero] starting layer to restrict search to endLayer [optional, defaults to zero] ending layer to restrict search to A wave with the row indizes of the found values. An invalid wave reference if the value could not be found.
References ASSERT_TS, CA_OPTS_NO_DUPLICATE, CA_StoreEntryIntoCache, CA_TemporaryWaveKey, CA_TryFetchingEntryFromCache, CHUNKS, COLS, IsNaN, IsTextWave, LAYERS, PROP_EMPTY, PROP_MATCHES_VAR_BIT_MASK, PROP_NON_EMPTY, PROP_NOT_MATCHES_VAR_BIT_MASK, ROWS, str2numSafe, ZapNaNs.
Referenced by AB_AddExperimentNameIfReq, AB_AddMapEntry, AB_ButtonProc_OpenCommentNB, AB_ButtonProc_SelectStimSets, AB_CollapseListColumn, AB_ExpandListColumn, AB_GetExpandedIndices, AB_StoreChannelsBySweep, AD_PlotBounds, AD_SelectResult, AFH_GetSweepsFromSameRACycleNC, AFH_GetSweepsFromSameSCINC, CheckDimensionLabels, CreateTiledChannelGraph, EP_GetEpochs, FindRange, GetLastNonEmptyEntry, GetLastSettingChannelInternal, GetNonEmptyLBNRows, LBV_AddTraceToLBGraphTPStorage, NWB_AppendSweepLowLevel, OVS_ChangeSweepSelection, OVS_RemoveLowCountEntries, PA_GenerateAllPulseWaves, SB_GetChannelInfoFromGraph, SB_GetIndexFromSweepDataPath, SB_GetLogbookWave, SBE_ExportSweepBrowser, SBE_GetPulseStartTimesForSel, SC_GetPulseIndizes, SC_ReactToQCFailures, TUD_GetUserDataAsWave, WBP_ButtonProc_DeleteParam.
string GetLastNonEmptyEntry(WaveText wv, string colLabel, variable endRow)
Searches the column colLabel in wv for an non-empty entry with a row number smaller or equal to endRow.
Return an empty string if nothing could be found. wv text wave to search in colLabel column label from wv endRow maximum row index to consider
References FindIndizes, PROP_NON_EMPTY, ROWS.
Referenced by AB_ButtonProc_OpenCommentNB, AB_LoadFromExpandedRange, AB_LoadFromFile.
variable GenerateSettingsDefaults()
Generate a default settings file in JSON format.
embed:rst:leading-asterisk * .. code-block:: json * * { * "diagnostics": { * "last upload": "2020-03-05T13:43:32Z" * }, * "version": 1 * } * * Explanation: Window coordinates are stored as embed:rst:leading-asterisk * .. code-block:: json * * {"coordinates" : {"left" : 123, "top" : 456, "bottom" 789, "right" : 101112}} * * Entries: "version": Major version number to track breaking changes "diagnostics": Groups settings related to diagnostics and crash dump handling "diagnostics/last upload": ISO8601 timestamp when the last successfull upload of crash dumps was tried. This is also set when no crash dumps have been uploadad. "analysisbrowser": Groups settings related to the Analysisbrowser "analysisbrowser/directory": The directory initially opened for browsing existing NWB/PXP files "logfiles": Groups settings related to log files "logfiles/last upload": ISO8601 timestamp when the last successfull upload of log files was tried. This is also set when no log files have been uploadad. "*[/*]/coordinates": window coordinates JSONid Caller is responsible for releasing the document.
References UpgradeSettings.
Referenced by GetSettingsJSONid, MEN_ClearPackageSettings.
variable UpgradeSettings(variable JSONid)
Referenced by GenerateSettingsDefaults, GetSettingsJSONid.
variable UploadCrashDumpsDaily()
Call UploadCrashDumps() if we haven't called it since at least a day.
References AssertOnAndClearRTError, BUG, ClearRTError, DateTimeInUTC, ParseISO8601TimeStamp, UploadCrashDumps.
Referenced by DAP_LockDevice.
variable UploadLogFilesDaily()
Call UploadLogFiles() if we haven't called it since at least a day.
References ASSERT, AssertOnAndClearRTError, ClearRTError, DateTimeInUTC, IsEmpty, IsFinite, ParseISO8601TimeStamp, UploadLogFiles.
Referenced by CONF_RestoreDAEphys.
wave GetTraceInfos(string graph, WaveText addFilterKeys=defaultValue, WaveText addFilterValues=defaultValue)
Return the graph user data as 2D text wave.
Only returns infos for sweep traces without duplicates. Duplicates are present with oodDAQ display mode. graph Name of graph addFilterKeys [optional, default = $""] additional keys for filtering addFilterValues [optional, default = $""] additional values for filtering, must have same size as keys
References ASSERT, COLS, GetGraphUserData, ROWS, TUD_GetTraceCount, TUD_GetUserDataAsWave.
Referenced by PA_GenerateAllPulseWaves.
variable RemoveSweepFromGraph(string win, variable index)
Remove the given sweep from the Databrowser/Sweepbrowser.
Needs a manual call to PostPlotTransformations() afterwards. win graph index overlay sweeps listbox index
References BSP_HasBoundDevice, DATA_SWEEP_BROWSER_PANEL_VERSION, DEBUGPRINT, DoAbortNow, GetMainWindow, HasPanelLatestVersion, OVS_GetSweepAndExperiment, ROWS, TUD_GetUserDataAsWave, TUD_RemoveUserData.
Referenced by OVS_EndIncrementalUpdate, OVS_MainListBoxProc, UpdateSweepInGraph.
variable AddSweepToGraph(string win, variable index, BufferedDrawInfo *bdi=defaultValue)
Add the given sweep to the Databrowser/Sweepbrowser.
Needs a manual call to PostPlotTransformations() afterwards. win graph index overlay sweeps listbox index bdi [optional, default = n/a] BufferedDrawInfo structure, when given buffered draw is used.
References BSP_HasBoundDevice, BSP_IsDataBrowser, DATA_SWEEP_BROWSER_PANEL_VERSION, DB_AddSweepToGraph, DEBUGPRINT, DoAbortNow, HasPanelLatestVersion, SB_AddSweepToGraph.
Referenced by OVS_EndIncrementalUpdate, OVS_MainListBoxProc, UpdateSweepInGraph.
variable UpdateSweepInGraph(string win, variable index)
Update the given sweep in the Databrowser/Sweepbrowser plot.
Needs a manual call to PostPlotTransformations() afterwards. win graph index overlay sweeps listbox index
References AddSweepToGraph, GetAxesRanges, GetCursorInfos, GetMainWindow, RemoveSweepFromGraph, RestoreCursors, SetAxesRanges.
Referenced by OVS_EndIncrementalUpdate, OVS_UpdateHeadstageRemoval.
variable StoreWindowCoordinatesHook(WMWinHookStruct *s)
Generic window hooks for storing the window coordinates in the JSON settings file.
References PS_StoreWindowCoordinate.
variable MapAnaFuncToConstant(string anaFunc)
Map from analysis function name to numeric constant.
One of SpecialAnalysisFunctionTypes which includes INVALID_ANALYSIS_FUNCTION
References INVALID_ANALYSIS_FUNCTION, MSQ_DA_SCALE, MSQ_FAST_RHEO_EST, PSQ_CHIRP, PSQ_DA_SCALE, PSQ_PIPETTE_BATH, PSQ_RAMP, PSQ_RHEOBASE, PSQ_SQUARE_PULSE, SC_SPIKE_CONTROL.
Referenced by AD_FillWaves, IVS_GetSetQCForSweep.
string CreateAnaFuncLBNKey(variable type, string formatString, variable chunk=defaultValue, variable query=defaultValue)
Return labnotebook keys for patch seq analysis functions.
type One of SpecialAnalysisFunctionTypes formatString One of PatchSeqLabnotebookFormatStrings or MultiPatchSeqLabnotebookFormatStrings chunk [optional] Some format strings expect a chunk number query [optional, defaults to false] If the key is to be used for setting or querying the labnotebook
References LABNOTEBOOK_USER_PREFIX, MSQ_DA_SCALE, MSQ_DS_LBN_PREFIX, MSQ_FAST_RHEO_EST, MSQ_FRE_LBN_PREFIX, MSQ_SC_LBN_PREFIX, PSQ_CHIRP, PSQ_CR_LBN_PREFIX, PSQ_DA_SCALE, PSQ_DS_LBN_PREFIX, PSQ_PB_LBN_PREFIX, PSQ_PIPETTE_BATH, PSQ_RA_LBN_PREFIX, PSQ_RAMP, PSQ_RB_LBN_PREFIX, PSQ_RHEOBASE, PSQ_SP_LBN_PREFIX, PSQ_SQUARE_PULSE, SC_SPIKE_CONTROL.
Referenced by AD_FillWaves, AD_GetBaselineChunkFailMsg, AD_GetBaselineFailMsg, AD_GetChirpFailMsg, AD_GetDAScaleFailMsg, AD_GetFastRheoEstFailMsg, AD_GetPerSweepFailMessage, AD_GetRheobaseFailMsg, AD_GetSpikeControlFailMsg, AD_GetSquarePulseFailMsg, AD_PlotBounds, IVS_GetSetQCForSweep, LBV_PlotAllAnalysisFunctionLBNKeys, MSQ_DAScale, MSQ_FastRheoEst, MSQ_GetLastPassingLongRHSweep, MSQ_GetLBNEntryForHeadstageSCI, MSQ_GetLBNEntryForHSSCIBool, MSQ_GetPulseDurations, MSQ_NumPassesInSet, PSQ_CheckSamplingFrequencyAndStoreInLabnotebook, PSQ_Chirp, PSQ_CR_DetermineBoundsAction, PSQ_CR_GetCycles, PSQ_CR_SetHasPassed, PSQ_DAScale, PSQ_EvaluateBaselinePassed, PSQ_EvaluateBaselineProperties, PSQ_FoundAtLeastOneSpike, PSQ_GetLastPassingDAScaleSub, PSQ_GetLastPassingLongRHSweep, PSQ_GetPulseDurations, PSQ_NumPassesInSet, PSQ_PB_Publish, PSQ_PipetteInBath, PSQ_Ramp, PSQ_Rheobase, PSQ_SquarePulse, PSQ_StoreRMSThresholdsInLabnotebook, PSQ_StoreStepSizeInLBN, SC_DetermineQCState, SC_GetHeadstageQCForSetCount, SC_GetTrials, SC_ProcessPulses, SC_ReactToQCFailures, SC_SpikeControl, SC_SpontaneousSpikingCheckQC, SetAnalysisFunctionVersion.
variable GetAnalysisFunctionVersion(variable type)
Return the current version of the analysis functions.
References ASSERT, MSQ_DA_SCALE, MSQ_DA_SCALE_VERSION, MSQ_FAST_RHEO_EST, MSQ_FAST_RHEO_EST_VERSION, PSQ_CHIRP, PSQ_CHIRP_VERSION, PSQ_DA_SCALE, PSQ_DA_SCALE_VERSION, PSQ_PIPETTE_BATH, PSQ_PIPETTE_BATH_VERSION, PSQ_RAMP, PSQ_RAMP_VERSION, PSQ_RHEOBASE, PSQ_RHEOBASE_VERSION, PSQ_SQUARE_PULSE, PSQ_SQUARE_PULSE_VERSION, SC_SPIKE_CONTROL, SC_SPIKE_CONTROL_VERSION.
Referenced by SetAnalysisFunctionVersion.
variable SetAnalysisFunctionVersion(string device, variable type, variable headstage, variable sweepNo)
Add a labnotebook entry denoting the analysis function version.
References CreateAnaFuncLBNKey, ED_AddEntryToLabnotebook, FMT_LBN_ANA_FUNC_VERSION, GetAnalysisFunctionVersion, LABNOTEBOOK_LAYER_COUNT.
Referenced by MSQ_DAScale, MSQ_FastRheoEst, PSQ_Chirp, PSQ_DAScale, PSQ_PipetteInBath, PSQ_Ramp, PSQ_Rheobase, PSQ_SquarePulse, SC_SpikeControl.
variable GenerateJSONTemplateForUpload()
Return JSON text with default entries for upload.
Caller is responsible for releasing JSON text.
References AddPayloadEntries, GetISO8601TimeStamp, GetMiesVersion, ROStr.
Referenced by UploadCrashDumps, UploadLogFiles.
variable UploadCrashDumps()
Convert the Igor Pro crash dumps and the report file to JSON and upload them.
Does nothing if none of these files exists. The uploaded files are moved out of the way afterwards. See tools/http-upload/upload-json-payload-v1.php for the JSON format description. 1 if crash dumps had been uploaded, 0 otherwise
References AddPayloadEntriesFromFiles, ControlWindowToFront, DEBUG_TIMER_START, DEBUGPRINT_ELAPSED, GenerateJSONTemplateForUpload, GetAllFilesRecursivelyFromPath, GetSymbolicPathForDiagnosticsDirectory, GetUniqueSymbolicPath, ROWS, SaveTextFile, UniqueFileOrFolder, UploadJSONPayload.
Referenced by UploadCrashDumpsDaily.
variable UploadLogFiles(variable verbose=defaultValue, variable firstDate=defaultValue, variable lastDate=defaultValue)
Upload the MIES and ZeroMQ logfiles.
verbose [optional, defaults to true] Only in verbose mode the ticket ID is output to the history firstDate [optional, defaults to false] Allows to filter the logfiles to include entries within the given dates. Both firstDate and lastDate must be present for filtering. The timestamps are in seconds since Igor Pro epoch. lastDate [optional, defaults to false] See firstDate
References AddPayloadEntries, AddPayloadEntriesFromFiles, ASSERT, DP_DebuggingEnabledForCaller, FileExists, FilterLogfileByDate, GenerateJSONTemplateForUpload, GenerateRFC4122UUID, GetISO8601TimeStamp, GetUniqueSymbolicPath, GetZeroMQXOPLogfile, LOG_GetFile, PACKAGE_MIES, ROWS, SaveTextFile, UniqueFileOrFolder, UploadJSONPayload.
Referenced by UploadLogFilesDaily.
wave FilterByDate(WaveText entries, variable first, variable last)
Filter the entries text wave so that the result only includes entries between first and last.
entries 1D wave with a JSON document in each entry. Each JSON must contain a ts object with a ISO8601 timestamp. first Seconds since igor epoch in UTC of the first entry to include last Seconds since igor epoch in UTC of the last entry to include
References ASSERT, IsEmpty, IsNaN, ParseISO8601TimeStamp, ROWS.
Referenced by FilterLogfileByDate.
static std::tuple< WaveText, WaveText > FilterLogfileByDate(string file, variable firstDate, variable lastDate)
References ASSERT, FilterByDate, GetFile, LoadTextFile, NormalizeToEOL, TextWaveToList.
Referenced by UploadLogFiles.
variable UpdateZeroMQXOPLoggingTemplate()
Update the logging template used by the ZeroMQ-XOP.
References LOG_GenerateEntryTemplate.
Referenced by IgorStartOrNewHook.
string GetZeroMQXOPLogfile()
Return the disc location of the (possibly non-existing) ZeroMQ-XOP logfile.
References PACKAGE_MIES, PS_GetSettingsFolder.
Referenced by MEN_OpenZeroMQXOPLogFile, NWB_AppendIgorHistoryAndLogFile, UploadLogFiles.
variable RecreateMissingSweepAndConfigWaves(string device, dfref deviceDataDFR)
Tries to find deleted sweep and config waves which are still present due to 1D waves from databrowser backups or labnotebook entries.
The result is placed in root:reconstructed which is overwritten. For reconstructing single sweep or config waves, see RecreateSweepWaveFromBackupAndLBN() and RecreateConfigWaveFromLBN(). Example invocation: RecreateMissingSweepAndConfigWaves("ITC18USB_DEV_0", root:MIES:HardwareDevices:ITC18USB:Device0:Data:) Inspect the results in root:reconstructed If you are satisfied, move the waves from root:reconstructed into e.g. root:MIES:HardwareDevices:ITC18USB:Device0:Data: Proceed with the data as usual In case the routine throws an assertion, please open an issue so that we can investigate.
References ASSERT, createDFWithAllParents, GetLBNumericalKeys, GetLBNumericalValues, GetLBTextualKeys, GetLBTextualValues, GetSweepsWithSetting, IsValidSweepAndConfig, MoveToTrash, RecreateConfigWaveFromLBN, RecreateSweepWaveFromBackupAndLBN, ROWS.
Referenced by AB_ReExport.
wave RecreateSweepWaveFromBackupAndLBN(wave numericalValues, WaveText textualValues, variable sweepNo, dfref deviceDataDFR)
Try recreating a 2D DAQ sweep wave from its databrowser backup.
$"" if reconstruction failed or a free wave with the sweep data and correct metadata
References AddToSweepWave, ASSERT, GetActiveChannels, GetSamplingIntervalFromLBN, GetSingleSweepFolderAsString, GetSingleSweepWaves, IsValidSweepWave, ROWS, TTL_HARDWARE_CHANNEL, XOP_CHANNEL_TYPE_ADC, XOP_CHANNEL_TYPE_DAC, XOP_CHANNEL_TYPE_TTL, ZapNaNs.
Referenced by RecreateMissingSweepAndConfigWaves.
wave RecreateConfigWaveFromLBN(string device, wave numericalValues, wave textualValues, variable sweepNo)
Try recreating the DAQ config wave from labnotebook entries.
$"" if recreation failed or a free wave on success.
References AddChannelPropertiesFromLBN, AddChannelUnitFromLBN, AddDAQChannelTypeFromLBN, ASSERT, GetDAQConfigWave, GetSamplingIntervalFromLBN, GetWaveVersion, IsValidSweepWave, MoveToTrash, XOP_CHANNEL_TYPE_ADC, XOP_CHANNEL_TYPE_DAC, XOP_CHANNEL_TYPE_TTL.
Referenced by RecreateMissingSweepAndConfigWaves.
static variable GetSamplingIntervalFromLBN(wave numericalValues, variable sweepNo)
References DATA_ACQUISITION_MODE, GetLastSettingIndep.
Referenced by RecreateConfigWaveFromLBN, RecreateSweepWaveFromBackupAndLBN.
static variable AddChannelPropertiesFromLBN(wave numericalValues, wave textualValues, variable sweepNo, wave configWave, variable channelType)
Set ChannelNumber and ChannelType in configWave.
References GetActiveChannels, ROWS, TTL_HARDWARE_CHANNEL, ZapNaNs.
Referenced by RecreateConfigWaveFromLBN.
static variable AddDAQChannelTypeFromLBN(wave numericalValues, wave textualValues, variable sweepNo, wave configWave)
Set DAQChannelType in configWave.
References ASSERT, DAQ_CHANNEL_TYPE_DAQ, DAQ_CHANNEL_TYPE_TP, DAQ_CHANNEL_TYPE_UNKOWN, DATA_ACQUISITION_MODE, GetLastSettingChannel, GetRowIndex, IsFinite, ROWS, XOP_CHANNEL_TYPE_ADC, XOP_CHANNEL_TYPE_DAC, XOP_CHANNEL_TYPE_TTL.
Referenced by RecreateConfigWaveFromLBN.
static variable AddChannelUnitFromLBN(wave numericalValues, WaveText textualValues, variable sweepNo, wave configWave)
Add wave note entry CHANNEL_UNIT_KEY for the used channel units.
References AddEntryIntoWaveNoteAsList, CHANNEL_UNIT_KEY, DATA_ACQUISITION_MODE, GetLastSettingChannel, ROWS, XOP_CHANNEL_NAMES, XOP_CHANNEL_TYPE_TTL.
Referenced by RecreateConfigWaveFromLBN.
static std::tuple< WAVE, WaveRefWave > GetSingleSweepWaves(dfref singleSweepFolder, variable channelType)
Return waves with the channel numbers and references to 1D waves from the X_XXXX folders.
References GetDAQDataSingleColumnWaves, ROWS.
Referenced by RecreateSweepWaveFromBackupAndLBN.
static variable AddToSweepWave(WaveRefWave channelWaves, wave channelNumbers, wave sweepWave)
Add the returned 1D waves from GetSingleSweepWaves() into sweepWave.
References ROWS.
Referenced by RecreateSweepWaveFromBackupAndLBN.
variable TestOverrideActive()
Return if the function results are overriden for testing purposes.
References GetNumberFromWaveNote, GetOverrideResults, IsNaN, SetNumberInWaveNote.
Referenced by MSQ_DAScale, MSQ_DS_GetDAScaleOffset, MSQ_GetLastPassingLongRHSweep, MSQ_SearchForSpikes, PSQ_Chirp, PSQ_CR_DetermineBoundsAction, PSQ_DS_GetDAScaleOffset, PSQ_EvaluateBaselineProperties, PSQ_GetFinalDAScaleFake, PSQ_PipetteInBath, PSQ_Ramp, PSQ_Rheobase, PSQ_SearchForSpikes, SC_GetSpikeNumbersAndPositions, SC_SpontaneousSpikingCheckQC, TP_AutoAmplitudeAndBaseline, TP_AutoBaseline.
variable GetHeadstageForChannel(wave numericalValues, variable sweep, variable channelType, variable channelNumber, variable entrySourceType)
Returns the active headstage for a given sweep, channelType, channelNumber from the LBN.
numericalValues LBN wave with numerical values sweep sweep number channelType channel type number channelNumber channel number entrySourceType type of the labnotebook entry, one of DataAcqModes headstage number or NaN if no headstage was found
References GetLastSettingChannel.