MIES_AnalysisFunctionManagement.ipf
variable AFM_CallAnalysisFunctions(string device, variable eventType)
Call the analysis function associated with the stimset from the wavebuilder.
Valid analysis function return types, zero otherwise, see also AnalysisFunctionReturnTypes
References AFH_GetDACFromHeadstage, ANALYSIS_FUNC_RET_EARLY_STOP, ANALYSIS_FUNC_RET_REPURP_TIME, ANALYSIS_FUNCTION_PARAMS, ASSERT, AssertOnAndClearRTError, BUG, ChangeWaveLock, CHANNEL_CONTROL_WAVE, CHANNEL_TYPE_DAC, CHANNEL_TYPE_HEADSTAGE, ClearRTError, DAG_GetChannelState, DAG_GetChannelTextual, DAG_GetNumericalValue, DATA_ACQUISITION_MODE, DEBUGPRINT, EVENT_NAME_LIST, AnalysisFunction_V3::eventType, FuncRefIsAssigned, GENERIC_EVENT, GetAnalysisFunctionStorage, GetDAQDataWave, GetFifoPosition, GetScaledDataWave, GetSetEventFlag, GetSweepWave, isEmpty, AnalysisFunction_V3::lastKnownRowIndex, AnalysisFunction_V3::lastValidRowIndex, MID_SWEEP_EVENT, NUM_HEADSTAGES, AnalysisFunction_V3::params, POST_DAQ_EVENT, POST_SET_EVENT, POST_SWEEP_EVENT, PRE_DAQ_EVENT, PRE_SET_EVENT, PRE_SWEEP_CONFIG_EVENT, AnalysisFunction_V3::rawDACWave, ROVar, AnalysisFunction_V3::scaledDACWave, STIMSET_TP_WHILE_DAQ, AnalysisFunction_V3::sweepNo, AnalysisFunction_V3::sweepsInSet.
Referenced by AS_HandlePossibleTransition, DC_Configure, SWS_SaveAcquiredData.
variable AFM_UpdateAnalysisFunctionWave(string device)
Update the analysis function storage wave from the stimset waves notes.
We are called earlier than DAP_CheckSettings() so we can not rely on anything setup in a sane way.
References AFH_GetAnalysisFunctions, AFH_GetDACFromHeadstage, ANALYSIS_FUNCTION_PARAMS, ANALYSIS_FUNCTION_VERSION_ALL, CHANNEL_CONTROL_WAVE, CHANNEL_TYPE_DAC, CHANNEL_TYPE_HEADSTAGE, DAG_GetChannelState, ExtractAnalysisFuncFromStimSet, ExtractAnalysisFunctionParams, GetAnalysisFunctionStorage, GetPanelControl, GetPopupMenuString, IsFinite, NUM_HEADSTAGES, TOTAL_NUM_EVENTS, WB_CreateAndGetStimSet.
Referenced by DAP_CheckSettings, DAP_UpdateDAQControls, DC_UpdateGlobals.