MIES_DebugPanel.ipf
const string PANEL
Referenced by DP_DebuggingEnabledForFile, DP_OpenDebugPanel, DP_WindowHook.
variable DP_DebuggingEnabledForFile(string file)
References ASSERT, DP_FillDebugPanelWaves, GetDebugPanelListSelWave, GetDebugPanelListWave, LISTBOX_CHECKBOX_SELECTED, PANEL, WindowExists.
Referenced by DEBUGPRINT, DEBUGPRINTSTACKINFO, DP_DebuggingEnabledForCaller.
variable DP_DebuggingEnabledForCaller()
References ASSERT, DP_DebuggingEnabledForFile, IsEmpty.
Referenced by DAG_GetNumericalValue, DAG_GetTextualValue, OOD_CalculateOffsetsYoked, PSQ_CR_DetermineBoundsAction, SC_GetHeadstageQCForSetCount, SC_SpikeCountsQC, SCOPE_ITC_UpdateOscilloscope, SF_FormulaParser, StartZeroMQSockets, TP_AutoFitBaseline, UploadLogFiles, WB_NoiseSegment, WBP_MainWindowHook.
string DP_OpenDebugPanel()
References DP_FillDebugPanelWaves, GetDebugPanelListSelWave, GetDebugPanelListWave, PANEL, panel, QuerySetIgorOption, SetCheckBoxState.
void DP_DebugPanel()
static variable DP_FillDebugPanelWaves()
References GetAllFilesRecursivelyFromPath, GetDebugPanelListSelWave, GetDebugPanelListWave, GetFile, GetUniqueSymbolicPath, ROWS.
Referenced by DP_DebuggingEnabledForFile, DP_OpenDebugPanel.
variable DP_WindowHook(WMWinHookStruct *s)
References PANEL, QuerySetIgorOption, SetCheckBoxState.
variable DP_CheckProc_Debug(WMCheckboxAction *cba)
References DisableDebugMode, EnableDebugMode, HW_ITC_DebugMode.
variable DP_PopMenuProc_Selection(WMPopupAction *pa)
References ASSERT, ClearBit, GetDebugPanelListSelWave, LISTBOX_CHECKBOX_SELECTED, NONE, SetBit.