MIES_PackageSettings.ipf
const string PS_STORE_COORDINATES
Referenced by PS_StoreWindowCoordinates.
const string PS_WINDOW_NAME
Referenced by PS_ApplyStoredWindowCoordinate, PS_StoreWindowCoordinate.
variable PS_Initialize(string package)
Initialize the PackageFolder symbolic path.
References CreateFolderOnDisk, FolderExists.
Referenced by LOG_MarkSessionStart.
variable PS_GenerateSettingsDefaults()
This functions should return a JSON ID with the default settings.
References ASSERT.
variable PS_ReadSettings(string package, PS_GenerateSettingsDefaults generateDefaults)
Return a JSON ID with an opened JSON settings file.
Caller is responsible for releasing the document.
Referenced by GetSettingsJSONid.
variable PS_WriteSettings(string package, variable JSONid)
Write the settings from JSONid for package to disc.
Call this function in BeforeExperimentSaveHook to write the settings to disc
Referenced by MEN_ClearPackageSettings, PS_SerializeSettings.
string PS_GetSettingsFolder_TS(string package)
Return the absolute path to the settings folder for package
Threadsafe variant which requires the symbolic path `PackageFolder` created by PS_Initialize() to exist. The returned folder location includes a trailing colon (":")
Referenced by LOG_GetFile.
string PS_GetSettingsFolder(string package)
Return the absolute path to the settings folder for package creating it when necessary.
The returned folder location includes a trailing colon (":")
Referenced by GetZeroMQXOPLogfile, LOG_AddEntry, PS_FixPackageLocation.
static string PS_GetSettingsFile(string package)
Return the absolute path to the JSON settings file for package
Referenced by PS_OpenNotebook.
static variable PS_ApplyStoredWindowCoordinate(variable JSONid, string win)
Move the window to the stored location.
References ASSERT, AssertOnAndClearRTError, ClearRTError, IsEmpty, PS_WINDOW_NAME.
Referenced by PS_InitCoordinates.
static variable PS_RegisterForCoordinateSaving(string win, string name)
Add user data to mark the window as using coordinate saving.
Referenced by PS_InitCoordinates.
static variable PS_StoreWindowCoordinates(variable JSONid)
Store the coordinates of all registered windows in the JSON settings file.
The windows must have been registered beforehand with PS_InitCoordinates().
References AssertOnAndClearRTError, ClearRTError, IsNaN, PS_STORE_COORDINATES, PS_StoreWindowCoordinate.
Referenced by PS_SerializeSettings.
variable PS_StoreWindowCoordinate(variable JSONid, string win)
Store the window coordinates of win in the JSON settings file.
The window must have been registered beforehand with PS_InitCoordinates().
References ASSERT, IsEmpty, PS_WINDOW_NAME.
Referenced by DAP_WindowHook, DB_WindowHook, DownsampleWindowHook, PS_StoreWindowCoordinates, StoreWindowCoordinatesHook.
variable PS_InitCoordinates(variable JSONid, string win, string name, variable addHook=defaultValue)
Add support for window coordinate storing and loading.
Takes care of: Marking the window as using it with the given name Adding a hook to store the coordinates on window killing Read the current coordinates from the JSON settings file and applying them JSONid JSON document with settings win window name name name to store the window under (especially useful for windows which are renamed to their locked device) addHook [optional, defaults to true] Add a window hook to store the coordinates on window killing. Users with their own kill event handling must pass addHook=0.
References PS_ApplyStoredWindowCoordinate, PS_RegisterForCoordinateSaving.
Referenced by AB_OpenAnalysisBrowser, BSP_DynamicStartupSettings, CreateDownsamplePanel, DAP_CreateDAEphysPanel, PA_GetGraph, WBP_CreateWaveBuilderPanel.
variable PS_SerializeSettings(string package, variable JSONid)
Write the current JSON settings to disc.
Caller must invalidate JSONid after return.
References AssertOnAndClearRTError, ClearRTError, PS_StoreWindowCoordinates, PS_WriteSettings.
Referenced by IH_SerializeSettings, PS_OpenNotebook.
variable PS_OpenNotebook(string package, variable JSONid)
Caller must invalidate JSONid after return.
References PS_GetSettingsFile, PS_SerializeSettings, WindowExists.
Referenced by MEN_OpenPackageSettingsAsNotebook.
variable PS_FixPackageLocation(string package)
Fixup the settings and log file location for Igor Pro prior to 0855279d (Fix package folder location on disk, 2021-04-01). Package JSON: Incorrect is moved to the correct location JSONL logfile: Incorrect is moved to the correct location only if the correct does not exists If the correct does exist as well, the incorrect is read and appened to to the correct one
References ASSERT, FileExists, LoadTextFile, LOGFILE_NAME, PACKAGE_SETTINGS_JSON, PS_GetSettingsFolder, SaveTextFile.
Referenced by IgorStartOrNewHook.