MIES_DANDI.ipf
static string DND_GetDestinationIgorPath()
Referenced by DND_FetchAsset.
static string DND_ChooseAsset(WaveText props)
References ASSERT, GetDandiDialogWave, GetRowIndex, ID_AskUserForSettings, ID_POPUPMENU_SETTINGS, IsFinite.
Referenced by DND_FetchAssetFromSet.
static string DND_FetchAsset(variable setNumber, string assetID, string assetPath)
Download the given asset from the set.
The asset hash is checked before returning. absolute path to the downloaded asset
References ASSERT, DND_GetDestinationIgorPath, GetFile, LoadTextFile.
Referenced by DND_FetchAssetFromSet.
static wave DND_ParseSetReponse(string response)
Parse the REST API response and fill the DANDI set properties wave.
The returned wave will have the format as described at GetDandiSetProperties() and row dimension label with the asset ID. Example: https://api.dandiarchive.org/api/dandisets/000068/versions/draft/assets/
References COLS, GetDandiSetProperties, ROWS.
Referenced by DND_FetchAssetFromSet.
string DND_FetchAssetFromSet(variable setNumber)
References ASSERT, DND_ChooseAsset, DND_FetchAsset, DND_ParseSetReponse, IsEmpty.
Referenced by MEN_DownloadStimsets.