MIES_EnhancedWMRoutines.ipf
wave MIES_fWaveAverage(WaveOrNull yWaves, variable ignoreNaNs, variable averageWaveType, variable getComponents=defaultValue, WaveRefWave prevAvgData=defaultValue)
Average the given waves.
yWaves Y waves ignoreNaNs Ignoring NaNs means that the average does skip over NaNs. averageWaveType wave type of the average wave. Currently supported are IGOR_TYPE_64BIT_FLOAT and IGOR_TYPE_32BIT_FLOAT. getComponents [optional, default = 0] Return sum / count components as well prevAvgData [optional, default = $""] wave reference wave with data from previous averaging for incremental averaging. first entry refers to the sum per row wave and second to the counts per row wave. wave ref wave containing three free waves with the average per row, sums per row and counts per row. The latter two are only calculated when getComponents was set to 1. The latter two are undefined when getComponents is 0.
References ASSERT_TS, IGOR_TYPE_32BIT_FLOAT, IGOR_TYPE_64BIT_FLOAT, IsNaN, ROWS, x2pntWithFrac.
Referenced by CalculateAverage, PA_CalculateAllAverages.
static variable x2pntWithFrac(wave wv, variable scaledDim)
Referenced by MIES_fWaveAverage.