MIES_TestPulse.ipf
const double TP_MAX_VALID_RESISTANCE
Units MΩ
Referenced by TP_RecordTP.
const double TP_TPSTORAGE_EVAL_INTERVAL
Referenced by TP_AnalyzeTP.
const double TP_FIT_POINTS
Referenced by TP_AnalyzeTP.
const double TP_PRESSURE_INTERVAL
[s]
Referenced by TP_RecordTP.
const double TP_EVAL_POINT_OFFSET
Referenced by TP_TSAnalysis.
const double TP_BASELINE_FITTING_INSET
Referenced by TP_AutoFitBaseline.
const double TP_SET_PRECISION
Referenced by TP_AutoAmplitudeAndBaseline, TP_AutoBaseline.
variable TP_IsValidBaselineFraction(variable value)
Check if the value is a valid baseline fraction.
References TP_BASELINE_FRACTION_HIGH, TP_BASELINE_FRACTION_LOW.
Referenced by TP_CalculateTestPulseLength.
variable TP_CalculateTestPulseLength(variable pulseDuration, variable baselineFrac)
Return the total length of a single testpulse with baseline.
pulseDuration duration of the high portion of the testpulse in points or time baselineFrac fraction, not percentage, of the baseline
References ASSERT, TP_IsValidBaselineFraction.
Referenced by DAP_UpdateOnsetDelay, TP_UpdateTPSettingsCalculated.
variable TP_CalculateBaselineFraction(variable pulseDuration, variable totalLength)
Inverse function of TP_CalculateTestPulseLength.
Referenced by TP_AutoBaseline.
variable TP_StoreTP(string device, wave TPWave, variable tpMarker, string hsList)
Stores the given TP wave.
device device TPWave reference to wave holding the TP data, see GetOscilloscopeWave() tpMarker unique number for this set of TPs from all TP channels hsList list of headstage numbers in the same order as the columns of TPWave The stored test pulse waves will have column dimension labels in the format HS_X.
References AddPrefixToEachListItem, COLS, EnsureLargeEnoughWave, GetISO8601TimeStamp, GetNumberFromWaveNote, GetStoredTestPulseWave, GetTestpulseCycleID, NOTE_INDEX, SetDimensionLabels, SetNumberInWaveNote, SetStringInWaveNote.
Referenced by SCOPE_UpdateOscilloscopeData.
wave TP_GetStoredTPs(string device, variable tpMarker, variable number)
Return a number of consecutive test pulses ending with the TP identified by tpMarker.
The wave reference wave will have as many columns as active headstages were used.
References GetNumberFromWaveNote, GetStoredTestPulseWave, NOTE_INDEX.
Referenced by TP_GetTPWaveForAutoTP.
variable TP_SplitStoredTestPulseWave(string device)
Split the stored testpulse wave reference wave into single waves for easier handling.
References GetDeviceTestPulse, GetNumberFromWaveNote, GetStoredTestPulseWave, NOTE_INDEX.
variable TP_ROAnalysis(dfref dfr, variable err, string errmsg)
Receives data from the async function TP_TSAnalysis(), buffers partial results and puts complete results back to main thread, results are base line level, steady state resistance, instantaneous resistance and their positions collected results for all channels of a measurement are send to TP_RecordTP(), DQ_ApplyAutoBias() when complete.
dfr output data folder from ASYNC frame work with results from workloads associated with this registered function The output parameter in the data folder follow the definition as created in TP_TSAnalysis() err error code of TP_TSAnalysis() function errmsg error message of TP_TSAnalysis() function
References ASSERT, COLS, DQ_ApplyAutoBias, GetTPResultAsyncBuffer, GetTPResults, GetTPResultsBuffer, GetTPSettings, INDEP_HEADSTAGE, KillOrMoveToTrash, LAYERS, ROWS, TP_AutoAmplitudeAndBaseline, TP_CalculateAverage, TP_RecordTP.
static wave TP_CreateOverrideResults(string device, variable type)
References ASSERT, KillOrMoveToTrash, LAYERS, MINIMUM_WAVE_SIZE, NUM_HEADSTAGES, NumericWaveToList, SetDimensionLabels, SetStringInWaveNote, TP_OVERRIDE_RESULTS_AUTO_TP.
static wave TP_GetTPWaveForAutoTP(string device, variable marker)
Return a 2D wave with two testpulses concatenated.
Rows: TPs Columns: Active headstages
References TP_GetStoredTPs.
Referenced by TP_AutoAmplitudeAndBaseline.
static variable TP_AutoBaseline(string device, variable headstage, wave TPResults, wave TPs)
References ASSERT, CHANNEL_TYPE_HEADSTAGE, COLS, DAG_GetChannelState, DAP_TPSettingsToGUI, DEBUGPRINT, GetOverrideResults, GetStringFromWaveNote, GetTPSettings, INDEP_HEADSTAGE, ListToNumericWave, NUM_HEADSTAGES, NumericWaveToList, RoundNumber, ROWS, SetStringInWaveNote, TestOverrideActive, ToPassFail, ToTrueFalse, TP_AutoFitBaseline, TP_BASELINE_FIT_RESULT_ERROR, TP_BASELINE_FIT_RESULT_OK, TP_BASELINE_FIT_RESULT_TOO_NOISY, TP_BASELINE_FRACTION_HIGH, TP_BASELINE_FRACTION_LOW, TP_BASELINE_RATIO_HIGH, TP_BASELINE_RATIO_LOW, TP_BASELINE_RATIO_OPT, TP_CalculateBaselineFraction, TP_SET_PRECISION, ZapNaNs.
Referenced by TP_AutoAmplitudeAndBaseline.
static std::tuple< variable, variable, variable > TP_AutoFitBaseline(wave data, variable pulseLengthMS)
Fit the tail of the first TP with an expontential and return it's time constant.
/// /// +----+ +----+ /// | | | | /// | | | | /// | | | | /// | | | | /// ----+ +--------+ +---- /// /// <--------> /// Fitting range /// /// <------------> /// One TP /// /// <----> /// Pulse /// /// @param data input data @param pulseLengthMS length of the pulse (high part) of the testpulse [ms] @retval result One of @ref TPBaselineFitResults @retval tau time constant of the decay [ms] @retval baseline baseline length of one pulse (same as the fitting range) [ms]
References ASSERT, AssertOnAndClearRTError, ClearRTError, COLS, DEBUGPRINT, DP_DebuggingEnabledForCaller, IsFinite, IsFloatingPointWave, ROWS, TP_BASELINE_FIT_RESULT_ERROR, TP_BASELINE_FIT_RESULT_OK, TP_BASELINE_FIT_RESULT_TOO_NOISY, TP_BASELINE_FITTING_INSET, WindowExists.
Referenced by TP_AutoBaseline.
static variable TP_AutoAmplitudeAndBaseline(string device, wave TPResults, variable marker)
Automatically tune the Testpulse amplitude and baseline.
Decision logic flowchart: embed:rst:leading-asterisk * .. image:: /dot/auto-testpulse.svg *
References ASSERT, AUTOTP_LAST_INVOCATION_KEY, CHANNEL_TYPE_HEADSTAGE, DAG_GetChannelState, DAG_GetHeadstageMode, DAP_TPSettingsToGUI, DAQ_NOT_RUNNING, DEBUGPRINT, GetNumberFromWaveNote, GetOverrideResults, GetStringFromWaveNote, GetTPSettings, GetTPStorage, I_CLAMP_MODE, INDEP_HEADSTAGE, IsFinite, ListToNumericWave, NOISE_GEN_MERSENNE_TWISTER, NUM_HEADSTAGES, NumericWaveToList, RoundNumber, ROWS, SetNumberInWaveNote, SetStringInWaveNote, TestOverrideActive, TICKS_TO_SECONDS, TP_AutoBaseline, TP_GetTPWaveForAutoTP, TP_SET_PRECISION.
Referenced by TP_ROAnalysis.
variable TP_AutoTPActive(string device)
References DAG_GetActiveHeadstages, GetTPSettings, I_CLAMP_MODE, NUM_HEADSTAGES, ROWS.
Referenced by DAP_AdaptAutoTPColorAndDependent.
static variable TP_AutoTPTurnOff(string device, wave autoTPEnable, variable headstage, variable QC)
References GetTPSettingsLabnotebook, TP_AutoTPGenerateNewCycleID, TP_PublishAutoTPResult.
Referenced by TP_AutoDisableIfFinished.
static variable TP_AutoDisableIfFinished(string device, wave TPStorage)
Disable Auto TP if it passed TP_AUTO_TP_CONSECUTIVE_PASSES times in a row.
References CHANNEL_TYPE_HEADSTAGE, ControlWindowToFront, DAG_GetChannelState, DAG_GetHeadstageMode, DAP_TPSettingsToGUI, GetTPSettings, I_CLAMP_MODE, LABNOTEBOOK_LAYER_COUNT, NUM_HEADSTAGES, TP_AUTO_TP_BASELINE_RANGE_EXCEEDED_FAILS, TP_AUTO_TP_CONSECUTIVE_PASSES, TP_AutoTPTurnOff, TP_GETVALUES_LATEST_AUTOTPCYCLE, TP_GetValuesFromTPStorage, TP_RestartTestPulse, TP_StopTestPulse.
Referenced by TP_RecordTP.
static variable TP_PublishAutoTPResult(string device, variable headstage, variable result)
References ASSERT, AUTO_TP_FILTER, FFI_GetJSONTemplate, FFI_Publish, GetTPSettings, GetTPStorage, INDEP_HEADSTAGE, TP_GetValuesFromTPStorage.
Referenced by TP_AutoTPTurnOff.
variable TP_AutoTPGenerateNewCycleID(string device, variable headstage=defaultValue, variable first=defaultValue, variable last=defaultValue)
Generate new auto TP cycle IDs.
This is required everytime we lock a device or toggle Auto TP for a headstage device device headstage [optional, default to all headstages] only update it for a specific headstage first [optional, default to all headstages] only update the range [first, last] last [optional, default to all headstages] only update the range [first, last]
References GetNextRandomNumberForDevice, GetTPSettings, NUM_HEADSTAGES.
Referenced by DAP_LockDevice, DAP_TPGUISettingToWave, TP_AutoTPTurnOff.
wave TP_GetValuesFromTPStorage(wave TPStorage, variable headstage, string entry, variable numReqEntries, variable options=defaultValue)
Return the last numReqEntries non-NaN values from layer entry of headstage
TPStorage TP results wave, see GetTPStorage() headstage Headstage entry Name of the value to search numReqEntries Number of entries to return, supports integer values and inf options [optional, default to nothing] One of TPStorageQueryingOptions
References ASSERT, GetNumberFromWaveNote, IsFinite, IsInteger, IsNaN, LAYERS, NOTE_INDEX, TP_GETVALUES_DEFAULT, TP_GETVALUES_LATEST_AUTOTPCYCLE, ZapNaNs.
Referenced by TP_AutoDisableIfFinished, TP_PublishAutoTPResult.
dfref TP_TSAnalysis(dfref dfrInp)
This function analyses a TP data set. It is called by the ASYNC frame work in an own thread. currently six properties are determined.
dfrInp input data folder from the ASYNC framework, parameter input order therein follows the setup in TP_SendToAnalysis()
References DEBUGPRINT_TS, I_CLAMP_MODE, ROWS, TP_EVAL_POINT_OFFSET.
static variable TP_CalculateAverage(wave TPResultsBuffer, wave TPResults)
Calculates running average [box average] for all entries and all headstages.
References ASSERT, GetNumberFromWaveNote, LAYERS, NOTE_INDEX, SetNumberInWaveNote.
Referenced by TP_ROAnalysis.
static variable TP_RecordTP(string device, wave TPResults, variable now, variable tpMarker)
Records values from TPResults into TPStorage at defined intervals.
Used for analysis of TP over time.
References CHANNEL_TYPE_HEADSTAGE, ControlWindowToFront, DAG_GetChannelState, DateTimeInUTC, DIMENSION_SCALING_LAST_INVOC, DQ_STOP_REASON_OUT_OF_MEMORY, DQ_StopDAQ, EnsureLargeEnoughWave, ExtractLogbookSliceTimeStamp, GetHSProperties, GetNumberFromWaveNote, GetTestpulseCycleID, GetTPSettings, GetTPStorage, I_CLAMP_MODE, IsFinite, LOG_AddEntry, NOTE_INDEX, NUM_HEADSTAGES, P_PressureControl, PACKAGE_MIES, PRESSURE_CTRL_LAST_INVOC, ROWS, SetNumberInWaveNote, TP_AnalyzeTP, TP_AutoDisableIfFinished, TP_MAX_VALID_RESISTANCE, TP_PRESSURE_INTERVAL, TP_StopTestPulse, TP_UpdateHoldCmdInTPStorage, V_CLAMP_MODE.
Referenced by TP_ROAnalysis.
static variable TP_FitResistance(wave TPStorage, variable startRow, variable endRow, variable headstage)
Threadsafe wrapper for performing CurveFits on the TPStorage wave.
References AssertOnAndClearRTError, ClearRTError, IsFinite.
Referenced by TP_AnalyzeTP.
static variable TP_AnalyzeTP(string device, WaveOrNull TPStorage, variable endRow)
Determine the slope of the steady state resistance over a user defined window (in seconds)
device locked device string TPStorage test pulse storage wave endRow last valid row index in TPStorage
References DAQ_CHANNEL_TYPE_TP, DC_GetChannelTypefromHS, IsFinite, NUM_HEADSTAGES, ROWS, TP_FIT_POINTS, TP_FitResistance, TP_TPSTORAGE_EVAL_INTERVAL.
Referenced by TP_RecordTP.
variable TP_StopTestPulseOnAllDevices()
Stop running background testpulse on all locked devices.
References CallFunctionForEachListItem, GetListOfLockedDevices, TP_StopTestPulse.
variable TP_StopTestPulseFast(string device)
TP_StopTestPulseWrapper
References TP_StopTestPulseWrapper.
Referenced by AI_UpdateAmpModel.
variable TP_StopTestPulse(string device)
TP_StopTestPulseWrapper
References TP_StopTestPulseWrapper.
Referenced by DAP_ButtonProc_TPDAQ, DAP_ChangeHeadStageMode, DAP_ChangeHeadstageState, DAP_CheckProc_PowerSpectrum, DAP_TPGUISettingToWave, DAP_TPSettingsToGUI, DAP_UnlockDevice, TP_AutoDisableIfFinished, TP_RecordTP, TP_StopTestPulseOnAllDevices.
static variable TP_StopTestPulseWrapper(string device, variable fast=defaultValue)
Stop any running background test pulses.
device device fast [optional, defaults to false] Performs only the totally necessary steps for tear down. One of TestPulseRunModes
References TEST_PULSE_BG_MULTI_DEVICE, TEST_PULSE_BG_SINGLE_DEVICE, TEST_PULSE_FG_SINGLE_DEVICE, TEST_PULSE_NOT_RUNNING, TPM_StopTestPulseMultiDevice, TPS_StopTestPulseSingleDevice.
Referenced by TP_StopTestPulse, TP_StopTestPulseFast.
variable TP_RestartTestPulse(string device, variable testPulseMode, variable fast=defaultValue)
Restarts a test pulse previously stopped with TP_StopTestPulse.
References DEBUGPRINT, TEST_PULSE_BG_MULTI_DEVICE, TEST_PULSE_BG_SINGLE_DEVICE, TEST_PULSE_NOT_RUNNING, TPM_StartTestPulseMultiDevice, TPS_StartTestPulseSingleDevice.
Referenced by AI_UpdateAmpModel, DAP_ButtonProc_TPDAQ, DAP_ChangeHeadStageMode, DAP_ChangeHeadstageState, DAP_CheckProc_PowerSpectrum, DAP_TPGUISettingToWave, DAP_TPSettingsToGUI, TP_AutoDisableIfFinished.
variable TP_Setup(string device, variable runMode, variable fast=defaultValue)
Prepare device for TestPulse.
device device runMode Testpulse running mode, one of TestPulseRunModes fast [optional, defaults to false] Performs only the totally necessary steps for setup
References CONTROLS_DISABLE_DURING_DAQ_TP, DAP_AdaptAutoTPColorAndDependent, DAP_ToggleTestpulseButton, DC_Configure, DisableControls, GetHardwareType, HARDWARE_ABORT_ON_ERROR, HW_PrepareAcq, TEST_PULSE_BG_MULTI_DEVICE, TEST_PULSE_DURING_RA_MOD, TEST_PULSE_MODE, TESTPULSE_BUTTON_TO_STOP, TP_SetupCommon.
Referenced by RA_HandleITI, TPM_StartTPMultiDeviceLow, TPS_StartTestPulseSingleDevice.
variable TP_SetupCommon(string device)
Common setup calls for TP and TP during DAQ.
References AUTOBIAS_LAST_INVOCATION_KEY, AUTOTP_LAST_INVOCATION_KEY, DIMENSION_SCALING_LAST_INVOC, GetNumberFromWaveNote, GetTPResultAsyncBuffer, GetTPStorage, INDEX_ON_TP_START, KillOrMoveToTrash, NOTE_INDEX, PRESSURE_CTRL_LAST_INVOC, SetNumberInWaveNote, TICKS_TO_SECONDS, TP_GetTPCycleID.
Referenced by DAP_OneTimeCallBeforeDAQ, TP_Setup.
variable TP_Teardown(string device, variable fast=defaultValue)
Perform common actions after the testpulse.
References DAP_AdaptAutoTPColorAndDependent, DAP_HandleSingleDeviceDependentControls, DAP_ToggleTestpulseButton, ED_TPDocumentation, SCOPE_KillScopeWindowIfRequest, TEST_PULSE_DURING_RA_MOD, TEST_PULSE_NOT_RUNNING, TESTPULSE_BUTTON_TO_START, TP_TeardownCommon.
Referenced by RA_HandleITI, TPM_StartTPMultiDeviceLow, TPM_StopTPMDWrapper, TPS_StartTestPulseSingleDevice, TPS_StopTestPulseSingleDevice.
variable TP_TeardownCommon(string device)
Common teardown calls for TP and TP during DAQ.
References P_LoadPressureButtonState.
Referenced by DAP_OneTimeCallAfterDAQ, TP_Teardown.
variable TP_GetNumDevicesWithTPRunning()
Return the number of devices which have TP running.
References GetListOfLockedDevices, TP_CheckIfTestpulseIsRunning.
Referenced by WBP_ButtonProc_OpenAnaFuncs.
variable TP_CheckIfTestpulseIsRunning(string device)
Check if the testpulse is running.
Can not be used to check for foreground TP as during foreground TP/DAQ nothing else runs.
References IsDeviceActiveWithBGTask, TASKNAME_TP, TASKNAME_TPMD, TEST_PULSE_NOT_RUNNING.
Referenced by BWO_ConfigureTP, DAP_ButtonProc_TPDAQ, IVS_RunGigOhmSealQC, IVS_runInitAccessResisQC, P_PressureMethodPossible, P_RunP_ControlIfTPOFF, P_SetPressureOffset, TP_GetNumDevicesWithTPRunning, TP_UpdateHoldCmdInTPStorage, TPM_StartTestPulseMultiDevice, TPS_StartTestPulseSingleDevice.
variable TP_TestPulseHasCycled(string device, variable cycles)
See if the testpulse has run enough times to create valid measurements.
device DA_Ephys panel name cycles number of cycles that test pulse must run
References GetNumberFromWaveNote, GetTPStorage, INDEX_ON_TP_START, NOTE_INDEX.
Referenced by IVS_finishGigOhmSealQCCheck, IVS_finishInitAccessQCCheck.
variable TP_UpdateHoldCmdInTPStorage(string device, variable headStage)
Save the amplifier holding command in the TPStorage wave.
References AI_GetHoldingCommand, EnsureLargeEnoughWave, GetNumberFromWaveNote, GetTPStorage, IsFinite, NOTE_INDEX, ROWS, TP_CheckIfTestpulseIsRunning, V_CLAMP_MODE.
Referenced by AI_UpdateAmpModel, TP_RecordTP.
variable TP_CreateTestPulseWave(string device, variable dataAcqOrTP)
Create the testpulse wave with the current settings.
References GetTestPulse, TEST_PULSE_MODE.
Referenced by DC_Configure.
dfref TP_PrepareAnalysisDF(string device, TPAnalysisInput *tpInput)
Prepares a TP data set data folder to the asynchroneous analysis function TP_TSAnalysis.
device title of panel that ran this test pulse tpInput holds the parameters send to analysis data folder that can be pushed for execution by the async frame work
References TPAnalysisInput::activeADCs, ASYNC_AddParam, ASYNC_PrepareDF, TPAnalysisInput::baselineFrac, TPAnalysisInput::clampAmp, TPAnalysisInput::clampMode, TPAnalysisInput::data, TPAnalysisInput::device, TPAnalysisInput::duration, TPAnalysisInput::hsIndex, TPAnalysisInput::measurementMarker, TPAnalysisInput::readTimeStamp, TPAnalysisInput::tpLengthPoints, WORKLOADCLASS_TP.
Referenced by TP_SendToAnalysis.
variable TP_SendToAnalysis(string device, TPAnalysisInput *tpInput)
Send a TP data set to the asynchroneous analysis function TP_TSAnalysis.
device title of panel that ran this test pulse tpInput holds the parameters send to analysis
References ASYNC_Execute, TP_PrepareAnalysisDF.
Referenced by SCOPE_UpdateOscilloscopeData.
variable TP_UpdateTPSettingsCalculated(string device)
References DAP_GetSampInt, DATA_ACQUISITION_MODE, GetTPSettings, GetTPSettingsCalculated, INDEP_HEADSTAGE, TEST_PULSE_MODE, TP_CalculateTestPulseLength.
Referenced by DC_UpdateGlobals.
string TP_AutoTPLabelToLabnotebookName(string lbl)
Convert from row names of GetTPSettings()/GetTPSettingsCalculated() to GetTPSettingsLBN() column names.
References ASSERT.
Referenced by TP_UpdateTPLBNSettings.
variable TP_UpdateTPLBNSettings(string device)
Update the Testpulse labnotebook wave.
DAQ: TPSettings holds the current GUI values TPSettingsLabnotebook holds the settings which were active when the sweep started TP: TPSettings holds the current GUI values TPSettingsLabnotebook is cleared when TP is started and filled from TPSettings when TP is stopped This means we only have the latest values for the TP settings which don't restart TP. For entries which do restart TP we always have the current values. See also the DAEPHYS_TP_CONTROLS_XXX constants. DAP_TPGUISettingToWave() for the special auto TP entry handling.
References CHANNEL_TYPE_HEADSTAGE, DAG_GetChannelState, GetTestpulseCycleID, GetTPSettings, GetTPSettingsCalculated, GetTPSettingsLabnotebook, INDEP_HEADSTAGE, NUM_HEADSTAGES, ROVar, TP_AutoTPLabelToLabnotebookName.
Referenced by DC_UpdateGlobals, ED_TPDocumentation.
static variable TP_GetTPCycleID(string device)
Return the TP cycle ID for the given device.
Follower and leader will have the same TP cycle ID.
References DAP_AbortIfUnlocked, DeviceIsFollower, GetNextRandomNumberForDevice, ITC1600_FIRST_DEVICE.
Referenced by TP_SetupCommon.
variable TP_GetPowerSpectrumLength(variable tpLength)
Return the length in points of the power spectrum generated via FFT.
References FindNextPower.
Referenced by DC_MakeHelperWaves, DoFFT.