MIES_AnalysisFunctions_MultiPatchSeq_SpikeControl.ipf
const string SC_PULSE_PREFIX_RE
Pulse information in the labnotebook is stored as PX_RY:.... This regular expression can be used to match the prefix in order to remove it with RemovePrefix.
Referenced by SC_SpikeCountsQC, SC_SpikePositionQC.
static std::tuple< variable, variable > SC_GetTrials(string device, variable sweepNo, variable headstage)
Store the newly calculated rerun trials in the labnotebook and return the minimum and maximum of it.
References ASSERT, CreateAnaFuncLBNKey, DAG_GetActiveHeadstages, DATA_ACQUISITION_MODE, ED_AddEntryToLabnotebook, GetLastSetting, GetLastSettingEachSCI, GetLBNumericalValues, GetLBTextualValues, I_CLAMP_MODE, MSQ_FMT_LBN_RERUN_TRIAL, NUM_HEADSTAGES, NumericWaveToList, ROWS, SC_SPIKE_CONTROL, UNKNOWN_MODE, WaveMinAndMaxWrapper, ZapNaNs.
Referenced by SC_SpikeControl.
static wave SC_GetHeadstageQCForSetCount(string device, variable sweepNo)
Return a 2D wave with the headstage QC result as a function of the set sweep count.
This function does return the result for all active headstages. The headstage argument is needed for fetching all sweeps from the current SCI. Value: Cumulated headstage QC result Rows: Headstage Cols: Stimulus set sweep count
References AFH_GetDACFromHeadstage, AFH_GetStimSetName, AFH_GetSweepsFromSameSCI, ASSERT, CHANNEL_TYPE_DAC, CreateAnaFuncLBNKey, DAG_GetActiveHeadstages, DP_DebuggingEnabledForCaller, GetLastSetting, GetLBNumericalValues, GetRowIndex, I_CLAMP_MODE, IDX_NumberOfSweepsInSet, IsFinite, LABNOTEBOOK_LAYER_COUNT, MSQ_FMT_LBN_HEADSTAGE_PASS, NumericWaveToList, ROWS, SC_GetSetSweepCount, SC_SPIKE_CONTROL, UNKNOWN_MODE.
Referenced by SC_GetSetPassed, SC_GetSweepPassed.
static variable SC_GetSetSweepCount(wave numericalValues, variable sweepNo)
Return the stimulus set sweep count for the given sweep.
References ASSERT, DATA_ACQUISITION_MODE, GetLastSetting, IsConstant.
Referenced by SC_GetHeadstageQCForSetCount, SC_GetSweepPassed.
static variable SC_GetSetPassed(string device, variable sweepNo)
Return pass/fail state of the set.
This is true iff we have for very stimulus set sweep count a passing headstage
References SC_GetHeadstageQCForSetCount.
Referenced by SC_SpikeControl.
static variable SC_GetSweepPassed(string device, variable sweepNo)
Return pass/fail state of the sweep.
This is true iff we have for the current stimulus set sweep count a passing headstage
References GetLBNumericalValues, SC_GetHeadstageQCForSetCount, SC_GetSetSweepCount.
Referenced by SC_SpikeControl.
static variable SC_LastSweepInSet(string device, variable sweepNo, variable headstage)
Return 1 if we are currently acquiring the last sweep in the stimulus set, 0 otherwise.
References AFH_GetHeadstageFromDAC, AFH_GetStimSetName, CHANNEL_TYPE_DAC, DATA_ACQUISITION_MODE, GetLastSetting, GetLBNumericalValues, IDX_NumberOfSweepsInSet.
Referenced by SC_SpikeControl.
static wave SC_FilterPulses(WaveRefWave propertiesWaves, WaveOrNull indizesAll, WaveOrNull indizesSweep)
Given a list of pulses by their indizes, this function return only the diagonal ones which are matching the given sweep.
References GetNumberFromWaveNote, GetSetIntersection, NOTE_KEY_PULSE_IS_DIAGONAL, ROWS.
Referenced by SC_GetPulseIndizes.
static variable SC_AddPulseRegionLBNEntries(WaveText inputLBN, variable pulseIndex, variable region, variable headstage, WaveOrNull data=defaultValue)
Add a new PX_PY:.. entry in to the wave inputLBN
The value part after the : is only present if data is passed in
References ASSERT, IsNumericWave, IsTextWave, NumericWaveToList, TextWaveToList.
Referenced by SC_GetSpikeNumbersAndPositions.
static std::tuple< WAVE, WaveRefWave > SC_GetPulseAveragePropertiesWaves(string device)
Return the PA plot waves from the databrowser connected to the given device.
References BSP_GetFolder, DB_FindDataBrowser, GetDevicePulseAverageHelperFolder, GetPulseAverageProperties, GetPulseAveragePropertiesWaves, MIES_BSP_PANEL_FOLDER.
Referenced by SC_GetSpikeNumbersAndPositions.
static wave SC_GetPulseIndizes(wave properties, WaveRefWave propertiesWaves, variable sweepNo)
Return the diagonal pulses for the given sweep.
References ASSERT, FindIndizes, GetNumberFromWaveNote, NOTE_INDEX, NumericWaveToList, SC_FilterPulses, SelectWave.
Referenced by SC_GetSpikeNumbersAndPositions.
static std::tuple< WaveText, WaveText > SC_GetSpikeNumbersAndPositions(string device, variable sweepNo)
Return the spike numbers and positions in waves prepared for labnotebook writing.
References GetNumberFromWaveNote, GetOverrideResults, GetStringFromWaveNote, I_CLAMP_MODE, LABNOTEBOOK_LAYER_COUNT, ListToNumericWave, NOTE_KEY_PULSE_END, NOTE_KEY_PULSE_SPIKE_POSITIONS, NOTE_KEY_PULSE_START, PA_PROPERTIESWAVES_INDEX_PULSENOTE, ROWS, SC_AddPulseRegionLBNEntries, SC_GetPulseAveragePropertiesWaves, SC_GetPulseIndizes, TestOverrideActive, TextWaveToList.
Referenced by SC_ProcessPulses.
static variable SC_ProcessPulses(string device, variable sweepNo, variable minimumSpikePosition, variable idealNumberOfSpikes)
Fetch the pulses from the PA plot and write the results into the labnotebooks.
References CreateAnaFuncLBNKey, DAG_GetActiveHeadstages, ED_AddEntryToLabnotebook, HasOneValidEntry, I_CLAMP_MODE, MSQ_FMT_LBN_SPIKE_COUNTS, MSQ_FMT_LBN_SPIKE_POSITIONS, SC_DetermineQCState, SC_GetSpikeNumbersAndPositions, SC_SPIKE_CONTROL.
Referenced by SC_SpikeControl.
static string SC_SpikeCountStateToString(variable countState)
Convert a numeric spike counts state to its string.
Returns "" for unknown state variables
References SC_SPIKE_COUNT_NUM_GOOD, SC_SPIKE_COUNT_NUM_MIXED, SC_SPIKE_COUNT_NUM_TOO_FEW, SC_SPIKE_COUNT_NUM_TOO_MANY, SC_SPIKE_COUNT_STATE_STR_GOOD, SC_SPIKE_COUNT_STATE_STR_MIXED, SC_SPIKE_COUNT_STATE_STR_TOO_FEW, SC_SPIKE_COUNT_STATE_STR_TOO_MANY.
Referenced by SC_SpikeCountsQC.
static variable SC_SpikeCountsCalcDetail(variable minimum, variable maximum, variable idealNumberOfSpikes)
Determine the spike counts state.
Minimum[HS] == Maximum[HS] == idealNumberOfSpikes -> Pass idealNumberOfSpikes >= Maximum[HS] -> Too few idealNumberOfSpikes <= Mininum[HS] -> Too many If nothing else matched -> Mixed We assume: minimum < maximum idealNumberOfSpikes >= 1 All numbers are integers
References ASSERT, IsNaN, SC_SPIKE_COUNT_NUM_GOOD, SC_SPIKE_COUNT_NUM_MIXED, SC_SPIKE_COUNT_NUM_TOO_FEW, SC_SPIKE_COUNT_NUM_TOO_MANY.
Referenced by SC_SpikeCountsCalc.
static wave SC_SpikeCountsCalc(string device, wave minimum, wave maximum, variable idealNumberOfSpikes)
Determine the spike counts state for all headstages.
References DAG_GetActiveHeadstages, I_CLAMP_MODE, LABNOTEBOOK_LAYER_COUNT, NUM_HEADSTAGES, NumericWaveToList, SC_SpikeCountsCalcDetail.
Referenced by SC_SpikeCountsQC.
static wave SC_SpikeCountsQC(string device, WaveText spikeNumbersLBN, variable idealNumberOfSpikes)
Check that the we have found the expected number of spikes per pulse.
Spike counts state according to SpikeCountsStateConstants stringified
References ASSERT, DAG_GetActiveHeadstages, DP_DebuggingEnabledForCaller, I_CLAMP_MODE, IsInteger, LABNOTEBOOK_LAYER_COUNT, ListToNumericWave, NUM_HEADSTAGES, NumericWaveToList, RemovePrefixFromListItem, SC_PULSE_PREFIX_RE, SC_SpikeCountsCalc, SC_SpikeCountStateToString, TextWaveToList.
Referenced by SC_DetermineQCState.
static variable SC_SpikePositionsCalcDetail(wave spikePositions, variable minimumSpikePosition)
Calculate the QC state of a list of spike positions from one pulse.
All are in Pulse active coordinate system spikePositions spike position minimumSpikePosition minimum allowed spike position
References ASSERT.
Referenced by SC_SpikePositionQC.
static wave SC_SpikePositionQC(string device, WaveTextOrNull spikePositionsLBN, variable minimumSpikePosition)
Calculate the QC state of the spike positions of each pulse.
All values are in PA crd, see SC_SpikeControl(). device device spikePositionsLBN spike position of each pulse, ordered per headstage, for the current sweep minimumSpikePosition minimum allowed spike position
References DAG_GetActiveHeadstages, I_CLAMP_MODE, IsConstant, LABNOTEBOOK_LAYER_COUNT, ListToNumericWave, NUM_HEADSTAGES, NumericWaveToList, RemovePrefix, ROWS, SC_PULSE_PREFIX_RE, SC_SpikePositionsCalcDetail, TextWaveToList.
Referenced by SC_DetermineQCState.
static wave SC_RegionBlanked(wave data, variable totalOnsetDelay, WaveText oodDAQRegion)
Replace all points inside an oodDAQ region with NaN in the data wave.
References ROWS, ZapNaNs.
Referenced by SC_SpontaneousSpikingCheckQC.
static wave SC_SpontaneousSpikingCheckQC(string device, variable sweepNo)
Return a wave ready for the labnotebook with the spontaneous spike check QC entries.
References AFH_ExtractOneDimDataFromSweep, ASSERT, CreateAnaFuncLBNKey, DAG_GetActiveHeadstages, DATA_ACQUISITION_MODE, GetLastSetting, GetLastSettingIndepSCI, GetLBNumericalValues, GetLBTextualValues, GetOverrideResults, GetRowIndex, GetSweepWave, GetTotalOnsetDelay, I_CLAMP_MODE, IsFinite, LABNOTEBOOK_LAYER_COUNT, MSQ_FMT_LBN_FAILED_PULSE_LEVEL, NUM_HEADSTAGES, NumericWaveToList, SC_RegionBlanked, SC_SPIKE_CONTROL, TestOverrideActive, UNKNOWN_MODE, XOP_CHANNEL_TYPE_ADC.
Referenced by SC_DetermineQCState.
static wave SC_HeadstageQC(string device, WaveText spikeCountStateLBN, wave spontaneousSpikingCheckLBN)
Determine the headstage QC result.
References DAG_GetActiveHeadstages, I_CLAMP_MODE, LABNOTEBOOK_LAYER_COUNT, NUM_HEADSTAGES, NumericWaveToList, SC_SPIKE_COUNT_STATE_STR_GOOD.
Referenced by SC_DetermineQCState.
static variable SC_DetermineQCState(string device, variable sweepNo, wave spikeNumbersLBN, WaveOrNull spikePositionsLBN, variable minimumSpikePosition, variable idealNumberOfSpikes)
Determine and write the QC states to the labnotebook.
References CreateAnaFuncLBNKey, ED_AddEntryToLabnotebook, LABNOTEBOOK_BINARY_UNIT, MSQ_FMT_LBN_HEADSTAGE_PASS, MSQ_FMT_LBN_SPIKE_COUNTS_STATE, MSQ_FMT_LBN_SPIKE_POSITION_PASS, MSQ_FMT_LBN_SPONT_SPIKE_PASS, SC_HeadstageQC, SC_SPIKE_CONTROL, SC_SpikeCountsQC, SC_SpikePositionQC, SC_SpontaneousSpikingCheckQC.
Referenced by SC_ProcessPulses.
static variable SC_CanStillSkip(variable maxTrials, string params)
Check if we can still skip sweeps without running more than maxTrials
References AFH_GetAnalysisParamNumerical, DEBUGPRINTv.
Referenced by SC_SpikeControl.
static variable SC_SkipsExhausted(variable minTrials, string params)
Check if we have exhausted the available trials on all headstages.
References AFH_GetAnalysisParamNumerical, DEBUGPRINTv.
Referenced by SC_SpikeControl.
static variable SC_ReactToQCFailures(string device, variable sweepNo, string params)
Perform various actions on QC failures.
References AFH_GetAnalysisParamNumerical, AFH_GetAnalysisParamTextual, ASSERT, ControlWindowToFront, CreateAnaFuncLBNKey, DAG_GetActiveHeadstages, FindIndizes, GetLastSetting, GetLastSettingTextEachRAC, GetLBNumericalValues, GetLBTextualValues, GetSetVariable, GetSliderPositionIndex, I_CLAMP_MODE, MSQ_FMT_LBN_HEADSTAGE_PASS, MSQ_FMT_LBN_SPIKE_COUNTS_STATE, MSQ_FMT_LBN_SPIKE_POSITION_PASS, MSQ_FMT_LBN_SPONT_SPIKE_PASS, NUM_HEADSTAGES, PGC_SetAndActivateControl, ROWS, SC_SPIKE_CONTROL, SC_SPIKE_COUNT_STATE_STR_GOOD, SC_SPIKE_COUNT_STATE_STR_MIXED, SC_SPIKE_COUNT_STATE_STR_TOO_FEW, SC_SPIKE_COUNT_STATE_STR_TOO_MANY, SetDAScaleModOp, UNKNOWN_MODE.
Referenced by SC_SpikeControl.
string SC_SpikeControl_GetParams()
string SC_SpikeControl_GetHelp(string name)
References ASSERT.
string SC_SpikeControl_CheckParam(string name, CheckParametersStruct *s)
References AFH_GetAnalysisParamNumerical, AFH_GetAnalysisParamTextual, IsFinite, IsInteger, CheckParametersStruct::params.
variable SC_SpikeControl(string device, AnalysisFunction_V3 *s)
Analysis function to check sweeps for failed pulses and rerun them if the pulses failed.
Decision logic flowchart: embed:rst:leading-asterisk * .. image:: /dot/multi-patch-seq-spike-control.svg * For judging the quality of the spike positions we have introduced a new coordinate system which we call pulse active coordinate system (PA crd). Consider the following pulse on the DA wave and the response spike in the AD wave /// /// +---------+ /// | | /// | | /// | | /// | | /// | | /// | | /// -------+ +---------------------- /// /// X /// XXX /// X XX /// X XX /// X X /// X X /// X X /// X X /// X X /// X X /// X X /// -------X X-------- /// /// and the let pulse active start at 5ms and end at 15ms. We define the start as 0 and the end as 100. Therefore the spike position will be 110 in `PA crd` which is one point after the end of the pulse. The graphs were made with http://asciiflow.com.
References AD_UpdateAllDatabrowser, AFH_GetAnalysisParamNumerical, AFH_GetDACFromHeadstage, AFH_GetStimSetName, ASSERT, BSP_GetPanel, BSP_GetSweepControlsPanel, BSP_HasBoundDevice, CHANNEL_TYPE_DAC, CHANNEL_TYPE_TTL, ControlWindowToFront, CreateAnaFuncLBNKey, DAG_GetActiveHeadstages, DAG_GetChannelState, DAG_HeadstageIsHighestActive, DB_FindDataBrowser, DB_OpenDataBrowser, ED_AddEntryToLabnotebook, AnalysisFunction_V3::eventType, GetLastSettingIndepSCI, GetLBNumericalValues, GetSetVariable, GetUniqueTextEntriesFromList, I_CLAMP_MODE, INDEP_HEADSTAGE, IsEmpty, IsFinite, LABNOTEBOOK_BINARY_UNIT, LABNOTEBOOK_LAYER_COUNT, MSQ_CommonPreDAQ, MSQ_FMT_LBN_FAILED_PULSE_LEVEL, MSQ_FMT_LBN_IDEAL_SPIKE_COUNTS, MSQ_FMT_LBN_RERUN_TRIAL, MSQ_FMT_LBN_RERUN_TRIAL_EXC, MSQ_FMT_LBN_SET_PASS, MSQ_FMT_LBN_SWEEP_PASS, NUM_HEADSTAGES, AnalysisFunction_V3::params, PGC_SetAndActivateControl, POST_DAQ_EVENT, POST_SET_EVENT, POST_SWEEP_EVENT, PRE_DAQ_EVENT, PRE_SET_EVENT, RA_SkipSweeps, SC_CanStillSkip, SC_GetSetPassed, SC_GetSweepPassed, SC_GetTrials, SC_LastSweepInSet, SC_ProcessPulses, SC_ReactToQCFailures, SC_SkipsExhausted, SC_SPIKE_CONTROL, SetAnalysisFunctionVersion, AnalysisFunction_V3::sweepNo, UNKNOWN_MODE.