MIES_ForeignFunctionInterface.ipf
wave FFI_ReturnTPValues()
Function to return Peak Resistance, Steady State Resistance to ACQ4 (Neurophysiology Acquisition and Analysis System. See http://acq4.org/ for more details)
The function will pull the values (PeakResistance, SteadyStateResistance, and TimeStamp) out of the TP storage wave and put them in a 3x8 wave, in a designated location where ACQ4 can then find them
References GetAcqTPStorage, GetListOfLockedDevices, GetNumberFromWaveNote, GetTPStorage, NOTE_INDEX.
variable FFI_GetJSONTemplate(string device, variable headstage)
Get a template for publishing messages.
Publishers in MIES should in general supply additional information like device/sweep number/timestamp. This function allows to autofill these entries.
References AS_GetSweepNumber, GetISO8601TimeStamp.
Referenced by AI_PublishAutoBridgeBalance, DAP_PublishClampModeChange, P_PublishBreakin, P_PublishPressureMethodChange, P_PublishSealedState, PSQ_PB_Publish, TP_PublishAutoTPResult.
wave FFI_GetAvailableMessageFilters()
Return a text wave with all available message filters for Publisher/Subscriber ZeroMQ sockets.
See also ZeroMQMessageFilters. FFI_GetJSONTemplate
References AMPLIFIER_CLAMP_MODE_FILTER, ANALYSIS_FUNCTION_PB, AUTO_TP_FILTER, IVS_PUB_FILTER, PRESSURE_SEALED_FILTER, PRESSURE_STATE_FILTER, ZeroMQ_HEARTBEAT.
variable FFI_Publish(variable jsonID, string messageFilter)
Publish the given message as given by the JSON and the filter.
References AssertOnAndClearRTError, BUG, ClearRTError.
Referenced by AI_PublishAutoBridgeBalance, DAP_PublishClampModeChange, IVS_PublishQCState, P_PublishBreakin, P_PublishPressureMethodChange, P_PublishSealedState, PSQ_PB_Publish, TP_PublishAutoTPResult.