MIES_DataAcquisition.ipf
variable DQ_StopOngoingDAQAllLocked(variable stopReason)
Stop DAQ and TP on all locked devices.
References AssertOnAndClearRTError, DQ_StopOngoingDAQ.
Referenced by BeforeUncompiledHook.
variable DQ_StopOngoingDAQ(string device, variable stopReason, variable startTPAfterDAQ=defaultValue)
Stop the DAQ and testpulse.
Works with single/multi device mode and on yoked devices simultaneously. device device stopReason One of DAQStoppingFlags startTPAfterDAQ [optional, defaults to true] start "TP after DAQ" if enabled
References DQ_StopOngoingDAQHelper, GetListofLeaderAndPossFollower.
Referenced by DQ_StopDAQ, DQ_StopOngoingDAQAllLocked, DQM_FIFOMonitor, DQS_FIFOMonitor, DQS_StopDataAcq, TPM_BkrdTPFuncMD, TPM_StartTestPulseMultiDevice, TPS_StartTestPulseSingleDevice, TPS_TestPulseFunc.
static variable DQ_StopOngoingDAQHelper(string device, variable stopReason, variable startTPAfterDAQ)
Stop the testpulse and data acquisition.
References DAP_OneTimeCallAfterDAQ, DAQ_NOT_RUNNING, DQ_StopDAQDeviceTimer, DQM_StopBackgroundTimer, DQM_TerminateOngoingDAQHelper, DQS_StopBackgroundFifoMonitor, DQS_StopBackgroundTimer, GetValDisplayAsNum, HARDWARE_ITC_DAC, HW_StopAcq, IsDeviceActiveWithBGTask, RA_IsFirstSweep, SWS_SaveAcquiredData, TASKNAME_FIFOMON, TASKNAME_FIFOMONMD, TASKNAME_TIMER, TASKNAME_TIMERMD, TASKNAME_TP, TASKNAME_TPMD, TPM_StopTestPulseMultiDevice, TPS_StopTestPulseSingleDevice.
Referenced by DQ_StopOngoingDAQ.
variable DQ_StartDAQDeviceTimer(string device)
Start the per-device timer used for the ITI (inter trial interval)
This function and DQ_StopDAQDeviceTimer are used to correct the ITI for the time it took to collect data, and pre and post processing of data. It allows for a real time, start to start, ITI
References ASSERT, DEBUGPRINT, GetActiveDAQDevicesTimerFolder, MAX_NUM_MS_TIMERS.
Referenced by DQM_BkrdDataAcq, DQM_StartDAQMultiDevice, DQS_BkrdDataAcq, DQS_DataAcq.
variable DQ_StopDAQDeviceTimer(string device)
Stop the per-device timer associated with a particular device.
References DEBUGPRINT, GetActiveDAQDevicesTimerFolder.
Referenced by DQ_StopOngoingDAQHelper, DQM_StartDAQMultiDevice, RA_FinishAcquisition, RA_RecalculateITI.
variable DQ_StopDAQ(string device, variable stopReason, variable startTPAfterDAQ=defaultValue)
Stop any running background DAQ.
Assumes that single device and multi device do not run at the same time. One of DAQRunModes
References DAQ_BG_MULTI_DEVICE, DAQ_BG_SINGLE_DEVICE, DAQ_FG_SINGLE_DEVICE, DAQ_NOT_RUNNING, DQ_StopOngoingDAQ, GetDataAcqRunMode, ROVar.
Referenced by DAP_ButtonProc_TPDAQ, DAP_PopMenuChkProc_StimSetList, DAP_UnlockDevice, TP_RecordTP.
variable DQ_RestartDAQ(string device, variable dataAcqRunMode)
Todohow to handle yoked devices??
References AS_EARLY_CHECK, AS_HandlePossibleTransition, AS_PRE_DAQ, DAQ_BG_MULTI_DEVICE, DAQ_BG_SINGLE_DEVICE, DAQ_FG_SINGLE_DEVICE, DAQ_NOT_RUNNING, DEBUGPRINT, DQM_StartDAQMultiDevice, DQS_StartDAQSingleDevice.
Referenced by DAP_PopMenuChkProc_StimSetList.
variable DQ_ApplyAutoBias(string device, wave TPResults)
Handle automatic bias current injection.
device Locked panel with test pulse running occasionally TPResults Data from TP_ROAnalysis()
References AI_SendToAmp, AI_UpdateAmpModel, AUTOBIAS_LAST_INVOCATION_KEY, CHANNEL_TYPE_HEADSTAGE, ControlWindowToFront, DAG_GetChannelState, DAG_GetHeadstageMode, DAG_GetNumericalValue, DAP_DeviceIsUnlocked, DEBUGPRINT, GetAmplifierParamStorageWave, GetNumberFromWaveNote, GetTPStorage, I_CLAMP_MODE, IsFinite, MCC_GETHOLDING_FUNC, MCC_GETHOLDINGENABLE_FUNC, NUM_HEADSTAGES, SetNumberInWaveNote, TICKS_TO_SECONDS.
Referenced by TP_ROAnalysis.
variable DQ_GetNumDevicesWithDAQRunning()
Return the number of devices which have DAQ running.
References DAQ_NOT_RUNNING, GetListOfLockedDevices.