MIES_Async.ipf
const double ROWS
const double COLS
Referenced by GetWorkloadTracking.
const double LAYERS
const double CHUNKS
const string ASYNC_THREAD_MARKER_STR
const string ASYNC_WORKERFUNC_STR
const string ASYNC_READOUTFUNC_STR
const string ASYNC_WORKLOADCLASS_STR
const string ASYNC_PARAMCOUNT_STR
const string ASYNC_INORDER_STR
const string ASYNC_ABORTFLAG_STR
const string ASYNC_ERROR_STR
const string ASYNC_ERRORMSG_STR
const string ASYNC_WLCOUNTER_STR
const string ASYNC_BACKGROUND
const double MAX_OBJECT_NAME_LENGTH_IN_BYTES
Referenced by IsValidObjectName.
const double ASYNC_THREAD_MARKER
Referenced by isThreadDF.
const double ASYNC_MAX_THREADS
const double ASYNC_SLEEP_ON_WAIT
variable ASYNC_Start(variable numThreads, variable disableTask=defaultValue)
Starts the Async Framework with numThreads parallel threads.
numThreads number of threads to setup for processing data, must be >= 1 and <= ASYNC_MAX_THREADS disableTask [optional, default = 0] when set to 1 the background task processing readouts is not started 1 if ASYNC framework was started, 0 if ASYNC framework was already running, in this case the number of threads is not changed
References ASSERT, ASYNC_IsASYNCRunning, GetAsyncHomeDF.
Referenced by AfterCompiledHook.
dfref ASYNC_Worker(dfref dfr)
Prototype function for an async worker function.
dfr reference to thread data folder data folder reference to output data folder
variable ASYNC_ReadOut(dfref dfr, variable err, string errmsg)
Prototype function for an async readout function.
dfr reference to returned data folder from thread err error code, only set in the error case errmsg error message, only set in the error case
static variable ASYNC_Thread()
thread function that receives data folders from the thread input queue and calls the setup custom worker function. With :cpp:func:ASYNC_Start numThreads :cpp:func:ASYNC_Thread functions will be started in their own thread. Each will run until the framework is stopped. UTF_NOINSTRUMENTATION
static dfref ASYNC_Run_Worker(dfref dfr)
variable ASYNC_ThreadReadOut()
Receives data from finished workloads. Calls the user defined readout function. For in order readouts this function buffers pending result data folders until they can be processed in order.
Referenced by SCOPE_UpdateOscilloscopeData.
variable ASYNC_IsWorkloadClassDone(string workloadClass, variable removeClass=defaultValue)
Allows to check if all executed work loads of a specific work load class were read out. For that case, the work load class can optionally be removed from Async.
workloadClass work load class string removeClass [optional, default = 0] when set the specified work load class is removed from Async The parameter has no effect, if the work loads of the specified class are not done. 1 if work load class finished, 0 if work load class did not finish, NaN if work load class not known to ASYNC
variable ASYNC_WaitForWLCToFinishAndRemove(string workloadClass, variable timeout)
Wait for TP analysis from specific panel to finish and remove it.
workloadClass name of work load class timeout time out in seconds 0 if work load class is unknown or has finished and was removed, 1 if timeout was encountered.
Referenced by DAP_UnlockDevice, NWB_ASYNC_FinishWriting.
variable ASYNC_BackgroundReadOut(WMBackgroundStruct *s)
Background function that reads data folders from the thread output queue and calls the setup custom readout function The function takes care to buffer results if they should be processed in order.
s default structure for Igor background tasks
variable ASYNC_AddParam(dfref dfr, wave w=defaultValue, variable var=defaultValue, string str=defaultValue, variable move=defaultValue, string name=defaultValue)
Adds one parameter to a data folder for a threaded worker execution.
The parameters are globals in the threads data folder and named param0, param1, param2... in order of adding them. Only one parameter can be added per call. move is only allowed in combination with a wave. dfr data folder reference to thread df, prepared by calling ASYNC_PrepareDF w [optional, default = null] wave reference of wave to be added as parameter var [optional, default = 0] variable to be added as parameter str [optional, default = 0] string to be added as parameter move [optional, default = 0] if a wave was given as parameter and move is not zero then the wave is moved to the threads data folder name [optional, default = paramXXX] name of the added parameter
Referenced by NWB_ASYNC_SerializeStruct, TP_PrepareAnalysisDF.
wave ASYNC_FetchWave(dfref dfr, string name)
Fetch a wave from the DFREF in the worker function.
Referenced by NWB_ASYNC_DeserializeStruct.
variable ASYNC_FetchVariable(dfref dfr, string name)
Fetch a variable from the DFREF in the worker function.
Referenced by NWB_ASYNC_DeserializeStruct.
string ASYNC_FetchString(dfref dfr, string name)
Fetch a string from the DFREF in the worker function.
Referenced by NWB_ASYNC_DeserializeStruct.
variable ASYNC_Stop(variable timeout=defaultValue, variable fromAssert=defaultValue)
Stops the Async Framework.
timeout [optional, default = Inf] time in s to wait for running threads, the function waits for pending threads and pending readouts within this time. After a timeout happened the readout processing is stopped and threads are stopped. Any pending data is lost. If the threads have to be stopped forcefully, an assertion is raised. Using a finite timeout is strongly recommended. fromAssert [optional, default = 0] specified when called as cleanup function from ASSERT Suppresses further assertions such that all required cleanup routines such as ThreadGroupRelease are executed. 2 if ASYNC framework was not running, 1 if a timeout was encountered, 0 otherwise
Referenced by BeforeUncompiledHook.
dfref ASYNC_PrepareDF(string WorkerFunc, string ReadOutFunc, string workloadClass, variable inOrder=defaultValue)
Prepares a thread data folder for use with the AsyncFramework This function should be called first when setting up a worker with parameters.
WorkerFunc string naming a threadsafe worker function in the form of the ASYNC_Worker template ReadOutFunc string naming a readout function in the form of the ASYNC_ReadOut template workloadClass string naming a work load class for work load attribution like "TestPulse" The string must follow strict object naming rules. inOrder [optional, default = 1] flag that allows to disable in order readout of results data folder for thread, where parameters can be put to with :cpp:func:ASYNC_AddParam
Referenced by NWB_AppendSweepDuringDAQ, TP_PrepareAnalysisDF.
variable ASYNC_Execute(dfref dfr)
Puts a prepared thread data folder to parallel execution in another thread.
dfr data folder that is setup for thread and is to be deployed
Referenced by NWB_AppendSweepDuringDAQ, TP_SendToAnalysis.
static variable IsFinite(variable var)
Returns 1 if var is a finite/normal number, 0 otherwise.
UTF_NOINSTRUMENTATION
static variable IsEmpty(string *str)
Returns one if str is empty or null, zero otherwise.
str must not be a SVAR UTF_NOINSTRUMENTATION
static variable IsNaN(variable var)
Returns 1 if var is a NaN, 0 otherwise.
UTF_NOINSTRUMENTATION
static variable DataFolderExistsDFR(dfref dfr)
Checks if the datafolder referenced by dfr exists.
Unlike DataFolderExists() a dfref pointing to an empty ("") dataFolder is considered non-existing here. one if dfr is valid and references an existing or free datafolder, zero otherwise Taken from http://www.igorexchange.com/node/2055 UTF_NOINSTRUMENTATION
Referenced by GetDFREFbuffer, GetNVARAsString, GetSerialExecutionBuffer, GetSVARAsString, GetWorkloadTracking.
static string GetStackTrace(string prefix=defaultValue)
Return a nicely formatted multiline stacktrace.
static variable ASSERT(variable var, string errorMsg)
Low overhead function to check assertions.
var if zero an error message is printed into the history and procedure execution is aborted, nothing is done otherwise. If the debugger is enabled, it also steps into it. errorMsg error message to output in failure case Example usage: embed:rst:leading-asterisk * .. code-block:: igorpro * * ControlInfo/W = $device popup_MoreSettings_DeviceType * ASSERT(V_flag > 0, "Non-existing control or window") * do something with S_value * UTF_NOINSTRUMENTATION
static variable ASSERT_TS(variable var, string errorMsg)
Low overhead function to check assertions (threadsafe variant)
var if zero an error message is printed into the history and procedure execution is aborted, nothing is done otherwise. errorMsg error message to output in failure case Example usage: embed:rst:leading-asterisk * .. code-block:: igorpro * * ASSERT(DataFolderExistsDFR(dfr), "MyFunc: dfr does not exist") * do something with dfr * Unlike ASSERT() this function does not print a stacktrace or jumps into the debugger. The reasons are Igor Pro limitations. Therefore it is advised to prefix errorMsg with the current function name. UTF_NOINSTRUMENTATION
static variable FuncRefIsAssigned(string funcInfo)
Check wether the function reference points to the prototype function or to an assigned function.
Due to Igor Pro limitations you need to pass the function info from FuncRefInfo and not the function reference itself. 1 if pointing to prototype function, 0 otherwise
References ASSERT_TS, isEmpty, IsFinite.
static string GetNVARAsString(dfref dfr, string globalVarName, variable initialValue=defaultValue)
Returns the full path to a global variable.
dfr location of the global variable, must exist globalVarName name of the global variable initialValue initial value of the variable. Will only be used if it is created. 0 by default.
References ASSERT_TS, DataFolderExistsDFR.
Referenced by GetNumThreads, GetTaskDisableStatus, GetThreadGroupID.
static string GetSVARAsString(dfref dfr, string globalStrName, string initialValue=defaultValue)
Returns the full path to a global string.
dfr location of the global string, must exist globalStrName name of the global string initialValue initial value of the string. Will only be used if it is created. null by default.
References ASSERT_TS, DataFolderExistsDFR.
static dfref createDFWithAllParents(string dataFolder)
Create a datafolder and all its parents,.
Includes fast handling of the common case that the datafolder exists. reference to the datafolder
static string GetAsyncHomeStr()
Returns string path to async framework home data folder.
static dfref GetAsyncHomeDF()
Returns reference to async framework home data folder.
References createDFWithAllParents.
Referenced by ASYNC_Start.
static variable isThreadDF(dfref dfr)
test if data folder is marked for thread usage
References ASYNC_THREAD_MARKER.
static string GetThreadGroupID()
Returns string path to the thread group id.
References GetNVARAsString.
static string GetNumThreads()
Returns string path to the number of threads.
References GetNVARAsString.
static string GetTaskDisableStatus()
Returns string path to flag if background task was disabled.
References GetNVARAsString.
static wave GetDFREFbuffer(dfref dfr)
Return wave reference to wave with data folder reference buffer for delayed readouts 1d wave for data folder references, starts with size 0 when jobs should be read out in order, the waiting data folders are buffered in this wave e.g. if the next read out would be job 2, but a data folder from job 3 is returned the data folder is buffered until the one from job 2 appears from the output queue.
References ASSERT, DataFolderExistsDFR.
static wave GetWorkloadTracking(dfref dfr)
Returns wave ref for workload tracking 2d wave row stores work load classes named through dimension label column 0 stores how many work loads were pushed to Async column 1 stores how many work loads were read out from Async.
References ASSERT, COLS, DataFolderExistsDFR.
static wave GetSerialExecutionBuffer(dfref dfr)
Returns wave ref for buffering results when THREADING_DISABLED is defined 1D wave using NOTE_INDEX logic.
References ASSERT, DataFolderExistsDFR, MINIMUM_WAVE_SIZE, NOTE_INDEX, SetNumberInWaveNote.
static variable ASYNC_IsASYNCRunning()
returns 1 if ASYNC framework is running, 0 otherwise
References AssertOnAndClearRTError, IsNaN.
Referenced by ASYNC_Start.
static variable DeleteWavePoint(wave wv, variable dim, variable index)
Deletes one row, column, layer or chunk from a wave Advantages over DeletePoints: Keeps the dimensionality of the wave when deleting the last row, column, layer or chunk in a wave Implements range check Advantages over DeletePoints + KillWaves: The wave reference stays valid.
wv wave where the row, column, layer or chunk should be deleted dim dimension 0 - rows, 1 - column, 2 - layer, 3 - chunk index index where one point in the given dimension is deleted
References ASSERT.
static variable IsValidObjectName(string name)
Check if a name for an object adheres to the strict naming rules.
DisplayHelpTopic "ObjectName"
References MAX_OBJECT_NAME_LENGTH_IN_BYTES.