MIES_AcquisitionStateHandling.ipf
string AS_StateToString(variable acqState)
Get the acquisition state as string.
References AS_EARLY_CHECK, AS_INACTIVE, AS_ITI, AS_MID_SWEEP, AS_POST_DAQ, AS_POST_SWEEP, AS_PRE_DAQ, AS_PRE_SWEEP, AS_PRE_SWEEP_CONFIG, ASSERT.
Referenced by AS_GenerateEncounteredTransitions, AS_HandlePossibleTransition, GetValidAcqStateTransitions.
variable AS_HandlePossibleTransition(string device, variable newAcqState, variable call=defaultValue)
Takes care of (possible) acquisition state transitions.
We track the acquisition state so that we can perform actions for state transitions when required. device device newAcqState One of AcquisitionStates call [optional, defaults to false] Call analysis function which is connected to the state transition.
References AFM_CallAnalysisFunctions, AS_CheckStateTransition, AS_EARLY_CHECK, AS_INACTIVE, AS_ITI, AS_MID_SWEEP, AS_POST_DAQ, AS_POST_SWEEP, AS_PRE_DAQ, AS_PRE_SWEEP, AS_PRE_SWEEP_CONFIG, AS_RecordStateTransition, AS_StateToString, ASSERT, BUG, ED_MarkSweepStart, MID_SWEEP_EVENT, POST_DAQ_EVENT, POST_SWEEP_EVENT, PRE_DAQ_EVENT, PRE_SWEEP_CONFIG_EVENT.
Referenced by DAP_ButtonProc_TPDAQ, DAP_CheckSettings, DAP_OneTimeCallAfterDAQ, DC_Configure, DQ_RestartDAQ, DQM_BkrdDataAcq, DQM_FIFOMonitor, DQS_BkrdDataAcq, DQS_DataAcq, DQS_FIFOMonitor, RA_HandleITI, RA_HandleITI_MD, SWS_SaveAcquiredData.
static variable AS_CheckStateTransition(variable oldAcqState, variable newAcqState)
Check the acquisition state transition between old and new.
The following graph shows the allowed transitions for all states. embed:rst:leading-asterisk * .. image:: /dot/acquisition-state-transitions.svg * :width: 300 px * :align: center *
References GetValidAcqStateTransitions.
Referenced by AS_HandlePossibleTransition.
variable AS_GetSweepNumber(string device, variable allowFallback=defaultValue)
Return the sweep number of the currently active sweep.
The ITI between sweeps belongs to the earlier sweep. The main use is to add a labnotebook entry during data acquisition. The similiar named function AFH_GetLastSweepAcquired() returns the last acquired sweep in comparison.
References AFH_GetLastSweepAcquired, AS_EARLY_CHECK, AS_INACTIVE, AS_ITI, AS_MID_SWEEP, AS_POST_DAQ, AS_POST_SWEEP, AS_PRE_DAQ, AS_PRE_SWEEP, AS_PRE_SWEEP_CONFIG, ASSERT, DAG_GetNumericalValue, GetAcquisitionState, IsValidSweepNumber.
Referenced by DAP_DocumentStopReason, FFI_GetJSONTemplate, RA_DocumentSweepSkipping.
static variable AS_RecordStateTransition(variable oldAcqState, variable newAcqState)
References EnsureLargeEnoughWave, GetAcqStateTracking, GetNumberFromWaveNote, NOTE_INDEX, ROWS, SetNumberInWaveNote.
Referenced by AS_HandlePossibleTransition.
wave AS_GenerateEncounteredTransitions()
Return a wave with all encountered state transitions.
Requires that they were recorded with AS_RecordStateTransition().
References AS_NUM_STATES, AS_StateToString, GetAcqStateTracking, GetNumberFromWaveNote, GetValidAcqStateTransitions, NOTE_INDEX.