MIES_AnalysisFunctions.ipf
const string DEFAULT_DEVICE
device device
Referenced by InitoodDAQ, LastStimSetRun, setHolding, setIClampMode, SetStimParam, setVClampMode, StimParamGUI, switchHolding.
const string STIM_SET_LOCAL
Initial stimulus set.
Referenced by StimParamGUI.
const double VM1_LOCAL
Initial holding potential.
Referenced by StimParamGUI.
const double VM2_LOCAL
Second holding potential to switch to.
Referenced by ChangeHoldingPotential.
const double SCALE_LOCAL
Stimulus amplitude.
Referenced by StimParamGUI.
const double NUM_SWEEPS_LOCAL
Number of sweeps to acquire.
Referenced by StimParamGUI.
const double ITI_LOCAL
Inter-trial-interval.
Referenced by StimParamGUI.
const double POST_DELAY
Delay after stimulation event in which no other event can occur in ms.
Referenced by InitoodDAQ.
variable TestAnalysisFunction_V1(string device, variable eventType, wave DAQDataWave, variable headStage)
References DAG_GetNumericalValue, EVENT_NAME_LIST.
variable TestAnalysisFunction_V2(string device, variable eventType, wave DAQDataWave, variable headStage, variable realDataLength)
References EVENT_NAME_LIST.
variable TestAnalysisFunction_V3(string device, AnalysisFunction_V3 *s)
References AFH_GetAnalysisParamTextual, AFH_GetAnalysisParamTextWave, AFH_GetAnalysisParamType, AFH_GetAnalysisParamWave, AFH_GetListOfAnalysisParamNames, EVENT_NAME_LIST, AnalysisFunction_V3::eventType, AnalysisFunction_V3::headStage, MID_SWEEP_EVENT, AnalysisFunction_V3::params, POST_DAQ_EVENT, POST_SET_EVENT, POST_SWEEP_EVENT, PRE_DAQ_EVENT, PRE_SET_EVENT, PRE_SWEEP_CONFIG_EVENT.
variable MeasureMidSweepTiming_V3(string device, AnalysisFunction_V3 *s)
Measure the time between mid sweep calls.
Used mainly for debugging.
References AnalysisFunction_V3::eventType, GetElapsedTimeWave, GetReferenceTime, IsFinite, MID_SWEEP_EVENT, NOTE_INDEX, PRE_DAQ_EVENT, SetNumberInWaveNote, StoreElapsedTime.
variable Enforce_VC(string device, variable eventType, wave DAQDataWave, variable headStage, variable realDataLength)
References AFH_GetDACFromHeadstage, AFH_GetStimSetName, CHANNEL_TYPE_DAC, DAG_GetHeadstageMode, PRE_DAQ_EVENT, V_CLAMP_MODE.
variable Enforce_IC(string device, variable eventType, wave DAQDataWave, variable headStage, variable realDataLength)
References AFH_GetDACFromHeadstage, AFH_GetStimSetName, CHANNEL_TYPE_DAC, DAG_GetHeadstageMode, I_CLAMP_MODE, PRE_DAQ_EVENT.
variable SetStimConfig_Vclamp(string device, variable eventType, wave DAQDataWave, variable headStage)
Force active headstages into voltage clamp.
References setVClampMode.
variable SetStimConfig_Iclamp(string device, variable eventType, wave DAQDataWave, variable headStage)
Force active headstages into current clamp.
References setIClampMode.
variable ChangeHoldingPotential(string device, variable eventType, wave DAQDataWave, variable headStage)
Change holding potential midway through stim set.
References switchHolding, VM2_LOCAL.
variable LastStimSet(string device, variable eventType, wave DAQDataWave, variable headStage)
Print last Stim Set run and headstage mode and holding potential.
References CHECKBOX_SELECTED, LastStimSetRun, PGC_SetAndActivateControl.
variable StimParamGUI()
GUI to set initial stimulus parameters using SetStimParam() and begin data acquisition. NOTE: DATA ACQUISITION IS INTIATED AT THE END OF FUNCTION!
References CHANNEL_TYPE_DAC, DEFAULT_DEVICE, ITI_LOCAL, NUM_SWEEPS_LOCAL, PGC_SetAndActivateControl, SCALE_LOCAL, SetStimParam, ST_GetStimsetList, STIM_SET_LOCAL, VM1_LOCAL.
variable SetStimParam(string stimSet, variable Vm1, variable Scale, variable Sweeps, variable ITI)
Called by StimParamGUI to set initial stimulus parameters.
stimSet Stimulus set to run Vm1 Holding potential Scale Stimulus amplitude in mV Sweeps Number of sweeps ITI Inter-trial-interval
References CHECKBOX_SELECTED, DEFAULT_DEVICE, InitoodDAQ, PGC_SetAndActivateControl, setHolding.
Referenced by StimParamGUI.
variable setHolding(variable Vm1)
Set holding potential for active headstages.
Vm1 Holding potential
References CHANNEL_TYPE_HEADSTAGE, DAG_GetChannelState, DEFAULT_DEVICE, NUM_HEADSTAGES, PGC_SetAndActivateControl.
Referenced by SetStimParam.
variable setVClampMode()
Set active headstages into V-clamp.
References CHANNEL_TYPE_HEADSTAGE, CHECKBOX_SELECTED, DAG_GetChannelState, DAP_GetClampModeControl, DEFAULT_DEVICE, NUM_HEADSTAGES, PGC_SetAndActivateControl, V_CLAMP_MODE.
Referenced by SetStimConfig_Vclamp.
variable setIClampMode()
Set active headstages into I-clamp.
References CHANNEL_TYPE_HEADSTAGE, CHECKBOX_SELECTED, DAG_GetChannelState, DAP_GetClampModeControl, DEFAULT_DEVICE, I_CLAMP_MODE, NUM_HEADSTAGES, PGC_SetAndActivateControl.
Referenced by SetStimConfig_Iclamp.
variable switchHolding(variable Vm2)
Change holding potential on active headstages to Vm2. Switch occurs after X/2 number of data sweeps. If X!/2 switchSweep = floor(X/2)
Vm2 Holding potential to switch to
References ASSERT, CHANNEL_TYPE_HEADSTAGE, CHECKBOX_SELECTED, DAG_GetChannelState, DAG_GetHeadstageMode, DAG_GetNumericalValue, DEFAULT_DEVICE, GetValDisplayAsNum, I_CLAMP_MODE, NUM_HEADSTAGES, PGC_SetAndActivateControl, V_CLAMP_MODE.
Referenced by ChangeHoldingPotential.
variable InitoodDAQ()
Initialize oodDAQ settings.
References CHECKBOX_SELECTED, CHECKBOX_UNSELECTED, DEFAULT_DEVICE, PGC_SetAndActivateControl, POST_DELAY.
Referenced by SetStimParam.
variable LastStimSetRun()
Print last full stim set aqcuired.
References AFH_GetLastSweepAcquired, CHANNEL_TYPE_HEADSTAGE, CLAMPMODE_ENTRY_KEY, DAG_GetChannelState, DATA_ACQUISITION_MODE, DEFAULT_DEVICE, GetLastSetting, GetLBNumericalValues, GetLBTextualValues, I_CLAMP_MODE, NUM_HEADSTAGES, V_CLAMP_MODE.
Referenced by LastStimSet.
variable TestPrematureSweepStop(string device, variable eventType, wave DAQDataWave, variable headStage, variable realDataLength)
Mid sweep analysis function which stops the sweeps and repurposes the left over time at the 20th call.
This function needs to be set for Pre DAQ, Mid Sweep and Post Sweep Event.
References ANALYSIS_FUNC_RET_EARLY_STOP, ASSERT, IsFinite, MID_SWEEP_EVENT, POST_SWEEP_EVENT, PRE_DAQ_EVENT, str2numSafe.
variable preDAQ_MP_mainConfig(string device, variable eventType, wave DAQDataWave, variable headStage, variable realDataLength)
References ASSERT, PGC_SetAndActivateControl, PRE_DAQ_EVENT.
variable preDAQ_MP_IfMixed(string device, variable eventType, wave DAQDataWave, variable headStage, variable realDataLength)
References ASSERT, PGC_SetAndActivateControl, PRE_DAQ_EVENT.
variable preDAQ_MP_ChirpBlowout(string device, variable eventType, wave DAQDataWave, variable headStage, variable realDataLength)
References ASSERT, PGC_SetAndActivateControl, PRE_DAQ_EVENT.
variable AdjustDAScale(string device, variable eventType, wave DAQDataWave, variable headStage, variable realDataLength)
Analysis function to set different "DA Scale" values for a sweep.
Prerequisites: Stimset with multiple but identical sweeps and testpulse-like shape. The number of sweeps must be larger than the number of rows in the DAScales wave below. This stimset must have this analysis function set for the "Pre DAQ" and the "Post Sweep" Event Does currently nothing for "Mid Sweep" Event Does not support DA/AD channels not associated with a MIES headstage (aka unassociated DA/AD Channels) All active headstages must be in "Current Clamp"
References AFH_GetADCFromHeadstage, AFH_GetDACFromHeadstage, AFH_GetLastSweepWaveAcquired, AFH_GetStimSetName, ASSERT, CalculateTPLikePropsFromSweep, CHANNEL_CONTROL_SCALE, CHANNEL_TYPE_DAC, DAG_GetHeadstageMode, DAG_HeadstageIsHighestActive, DEBUGPRINT, ED_AddEntryToLabnotebook, FitResistance, GetAnalysisFuncDAScaleDeltaI, GetAnalysisFuncDAScaleDeltaV, GetAnalysisFuncDAScaleRes, GetAnalysisFuncIndexingHelper, GetLBNumericalValues, GetLBTextualValues, GetPanelControl, I_CLAMP_MODE, IsFinite, KillOrMoveToTrash, LABNOTEBOOK_LAYER_COUNT, PGC_SetAndActivateControl, POST_SWEEP_EVENT, PRE_DAQ_EVENT, ROWS.
variable FitResistance(string device, variable showPlot=defaultValue)
Plot the resistance of the sweeps of the same RA cycle Usually called by PSQ_AdjustDAScale().
References AFH_GetLastSweepAcquired, AFH_GetSweepsFromSameRACycle, CHANNEL_TYPE_HEADSTAGE, ControlWindowToFront, DAG_GetChannelState, ED_AddEntryToLabnotebook, EnsureLargeEnoughWave, GetAnalysisFuncDAScaleDeltaI, GetAnalysisFuncDAScaleDeltaV, GetAnalysisFuncDAScaleRes, GetAnalysisFuncDAScaleResFit, GetLastSetting, GetLBNumericalValues, GetNumberFromWaveNote, GetTraceColor, IsEmpty, IsFinite, KillOrMoveToTrash, LABNOTEBOOK_LAYER_COUNT, LABNOTEBOOK_USER_PREFIX, NOTE_INDEX, NUM_HEADSTAGES, RESISTANCE_GRAPH, ROWS, SetNumberInWaveNote, UNKNOWN_MODE, WindowExists.
Referenced by AdjustDAScale, PSQ_DAScale, ReachTargetVoltage.
variable SetDAScaleModOp(string device, variable headstage, variable modifier, string operator, variable invert=defaultValue, variable roundTopA=defaultValue)
Helper for setting the DAScale.
References ASSERT, SetDAScale.
Referenced by PSQ_Chirp, SC_ReactToQCFailures.
variable SetDAScale(string device, variable headstage, variable absolute=defaultValue, variable relative=defaultValue, variable offset=defaultValue, variable roundTopA=defaultValue)
Set the DAScale value of the given headstage.
device device headstage MIES headstage absolute (optional) DAScale value in A (Amperes) relative (optional) relative DAScale modifier offset (optional) offset DAScale value roundTopA (optional, defaults to false) round the set DAScale to integer pA values
References AFH_GetDACFromHeadstage, ASSERT, CHANNEL_CONTROL_SCALE, CHANNEL_CONTROL_UNIT, CHANNEL_TYPE_DAC, DAG_GetNumericalValue, DAG_GetTextualValue, GetPanelControl, GetSpecialControlLabel, IsFinite, PGC_SetAndActivateControl.
Referenced by MSQ_DAScale, MSQ_FastRheoEst, PSQ_Chirp, PSQ_DAScale, PSQ_Ramp, PSQ_Rheobase, PSQ_SquarePulse, ReachTargetVoltage, SetDAScaleModOp.
string ReachTargetVoltage_GetParams()
Return a list of required parameters.
string ReachTargetVoltage_GetHelp(string name)
References ASSERT.
string ReachTargetVoltage_CheckParam(string name, CheckParametersStruct *s)
References AFH_GetAnalysisParamNumerical, AFH_GetAnalysisParamTextual, ASSERT, IsEmpty, IsFinite, CheckParametersStruct::params.
variable ReachTargetVoltage(string device, AnalysisFunction_V3 *s)
Analysis function to experimentally determine the cell resistance by sweeping through a wave of target voltages.
Prerequisites: Stimset with multiple but identical sweeps and testpulse-like shape. The number of sweeps must be larger than the number of rows in the targetVoltages wave below. Does not support DA/AD channels not associated with a MIES headstage (aka unassociated DA/AD Channels) All active headstages must be in "Current Clamp" An inital DAScale of -20pA is used, a fixup value of -100pA is used on the next sweep if the measured resistance is smaller than 20MΩ
References AFH_GetAnalysisParamNumerical, AFH_GetAnalysisParamTextual, AFH_GetLastSweepWaveAcquired, ASSERT, CalculateTPLikePropsFromSweep, CHANNEL_CONTROL_INDEX_END, CHANNEL_INDEX_ALL_I_CLAMP, CHANNEL_TYPE_DAC, CHANNEL_TYPE_HEADSTAGE, CHECKBOX_UNSELECTED, CheckIfClose, ControlWindowToFront, DAG_GetChannelState, DAG_GetHeadstageMode, DAG_HeadstageIsHighestActive, DEBUGPRINT, ED_AddEntryToLabnotebook, AnalysisFunction_V3::eventType, ExtractSweepNumber, FitResistance, GetAmplifierParamStorageWave, GetAnalysisFuncDAScaleDeltaI, GetAnalysisFuncDAScaleDeltaV, GetAnalysisFuncDAScaleRes, GetAnalysisFuncIndexingHelper, GetCheckBoxState, GetLastSetting, GetLastSettingSCI, GetLBNumericalValues, GetLBTextualValues, GetPanelControl, GetSliderPositionIndex, GetUniqueTempPath, I_CLAMP_MODE, ID_AskUserForSettings, ID_HEADSTAGE_SETTINGS, IsFinite, KillOrMoveToTrash, LABNOTEBOOK_LAYER_COUNT, LABNOTEBOOK_USER_PREFIX, NUM_HEADSTAGES, AnalysisFunction_V3::params, PGC_SetAndActivateControl, POST_SET_EVENT, POST_SWEEP_EVENT, PRE_DAQ_EVENT, ROWS, SetDAScale, AnalysisFunction_V3::sweepNo, UNKNOWN_MODE, WB_CreateAndGetStimSet.
variable SetControlInEvent(string device, AnalysisFunction_V3 *s)
Analysis function to set GUI controls or notebooks in the events.
Usage: Add analysis parameters named like the control/notebook Their value must be a textwave with at least one tuple of event type and data. Valid number of rows are therefore 2, 4, 6, ... The first tuple element is the event type, one of EVENT_NAME_LIST without "Mid Sweep" and "Generic", and the second element the value to set For PopupMenus the passed value is the menu item and not its index The controls are searched in all open panels and graphs. The notebook can be a toplevel or subwindow notebook. For multiple matching panels or graphs we prefer the corresponding DAEphys panel and Databrowser. Examples: embed:rst:leading-asterisk * .. code-block:: none * * setvar_DataAcq_OnsetDelayUser -> Pre DAQ|20| * Popup_Settings_FixedFreq -> Pre Sweep|100|Post Sweep|Maximum| * sweepFormula_formula -> Pre Set|data(cursors(A,B), channels(AD), sweeps()) * *
References AFH_GetAnalysisParamTextWave, AFH_GetAnalysisParamType, AFH_GetListOfAnalysisParamNames, ASSERT, COLS, CONTROL_TYPE_CHART, CONTROL_TYPE_GROUPBOX, CONTROL_TYPE_POPUPMENU, CONTROL_TYPE_SETVARIABLE, CONTROL_TYPE_TITLEBOX, CONTROL_TYPE_VALDISPLAY, ControlExists, CONTROLS_DISABLE_DURING_DAQ, ControlWindowToFront, DAG_HeadstageIsHighestActive, DB_FindDataBrowser, DEBUGPRINT, EVENT_NAME_LIST, AnalysisFunction_V3::eventType, FindControl, FindNotebook, GetControlType, IsControlDisabled, IsEmpty, IsEven, MID_SWEEP_EVENT, NormalizeToEOL, AnalysisFunction_V3::params, PGC_SetAndActivateControl, PRE_SWEEP_CONFIG_EVENT, ReplaceNotebookText, ROWS, str2numSafe, WINTYPE_GRAPH, WINTYPE_NOTEBOOK, WINTYPE_PANEL.