MIES_OptimzedOverlapDistributedAcquisition.ipf
const double OOD_SIGNAL_THRESHOLD
Signal threshold level in parts of dynamic range above minimum OOD_GetThresholdLevel()
Referenced by OOD_GetThresholdLevel.
static variable OOD_GetThresholdLevel(wave stimset)
returns the threshold level for ood region detection from a single column stimset
stimset 1d wave containing stimset data threshold level defining signal above baseline
References OOD_SIGNAL_THRESHOLD, WaveMinAndMaxWrapper.
Referenced by OOD_GetRegionsFromStimset.
static wave OOD_GetRegionsFromStimset(wave stimset, variable prePoints, variable postPoints)
retrieves regions with signal from a 1D data wave, used for stimsets
stimset 1D wave containing stimset data prePoints oodDAQ pre delay in points the regions get expanded at the rising edge postPoints oodDAQ post delay in points the regions get expanded at the falling edge 2D wave with region information
References COLS, EnsureLargeEnoughWave, MINIMUM_WAVE_SIZE, OOD_GetThresholdLevel, ROWS.
Referenced by OOD_GetRegionsFromStimsets.
static wave OOD_CompactRegions(wave regions)
Reduces a 2D region wave by joining overlapping regions to one.
regions 2D wave containing region data 2D wave with compacted regions
References COLS, ROWS.
Referenced by OOD_CalculateOffsets, OOD_GetRegionsFromStimsets.
static wave OOD_GetRegionsFromStimsets(OOdDAQParams *params)
generates regions data waves from stimsets taking the pre and post delay into account
params OOdDAQParams structure wave reference wave holding the 2D region waves for each stimset
References COLS, DeepCopyWaveRefWave, OOD_CompactRegions, OOD_GetRegionsFromStimset, OOdDAQParams::postFeaturePoints, OOdDAQParams::preFeaturePoints, ROWS, OOdDAQParams::setColumns, OOdDAQParams::stimSets.
Referenced by OOD_CalculateOffsetsYoked.
static wave OOD_GetFeatureRegions(WaveRefWave setRegions, wave offsets)
returns a 1D wave with regions as lists from the input regions waves, is used for the LNB
setRegions wave reference wave of 2D region waves offsets offset wave storing the offsets per stimset 1D text wave with lists of regions
References OOD_AddToRegionList, ROWS.
Referenced by OOD_CalculateOffsetsYoked.
static wave OOD_CalculateOffsets(WaveRefWave setRegions, wave *baseRegions, variable yoked)
Calculates offsets for each stimset for OOD.
setRegions wave reference wave of 2D region waves for each stimset baseRegions 2D region wave that contains initial reserved regions, e.g. when using with yoking the caller function can preload from the previous device For the lead device where no previous regions are reserved, the wave can be 1D but must have zero rows yoked 1 if yoked operation, 0 if not 1D wave with offsets for each stimset in points
References OOD_CompactRegions, ROWS.
Referenced by OOD_CalculateOffsetsYoked.
static variable OOD_CalculateOffsetsYoked(string device, OOdDAQParams *params)
Calculated the offsets for normal acquisition and yoked mode.
device title of the device panel params OOdDAQParams structure with oodDAQ setup data
References ASSERT, DeviceHasFollower, DeviceIsFollower, DP_DebuggingEnabledForCaller, GetDistDAQFolder, KillOrMoveToTrash, OOdDAQParams::offsets, OOD_CalculateOffsets, OOD_Debugging, OOD_GetFeatureRegions, OOD_GetRegionsFromStimsets, OOD_LoadPreload, OOD_StorePreload, OOdDAQParams::preload, OOdDAQParams::regions.
Referenced by OOD_GetResultWaves.
static variable OOD_LoadPreload(string device, OOdDAQParams *params)
Load the preload data into params.preload
device title of the device panel params OOdDAQParams structure where the data is preloaded into
References GetDistDAQFolder, GetDistDAQPreloadWave, OOdDAQParams::preload.
Referenced by OOD_CalculateOffsetsYoked.
static variable OOD_StorePreload(string device, wave preload)
Store the preload data so that the next device can use it.
device title of the device panel preload wave that is stored containing the preload data
References GetDistDAQPreloadWave, HW_ITC_BuildDeviceString, ParseDeviceString.
Referenced by OOD_CalculateOffsetsYoked.
static string OOD_AddToRegionList(variable first, variable last, string list)
Return a list with $first-$last added at the end with ; as separator.
first sample point number in wavebuilder scale with start of region last sample point number in wavebuilder scale with end of region list list string where the element is added list string with added element
References WAVEBUILDER_MIN_SAMPINT.
Referenced by OOD_GetFeatureRegions.
static variable OOD_Debugging(OOdDAQParams *params)
Prints various internals useful for oodDAQ debugging, called when DEBUGGING_ENABLED is set.
params OOdDAQParams structure with oodDAQ internals
References COLS, DeepCopyWaveRefWave, GetUniqueTempPath, OOdDAQParams::offsets, OOD_CreateStimSet, OOdDAQParams::preload, OOdDAQParams::regions, ROWS, OOdDAQParams::setColumns, OOdDAQParams::stimSets.
Referenced by OOD_CalculateOffsetsYoked.
wave OOD_GetResultWaves(string device, OOdDAQParams *params)
Return the oodDAQ optimized stimsets.
The offsets and the regions are returned in params and all results are cached. device title of the device panel params OOdDAQParams structure with the initial settings one dimensional numberic wave with the offsets in points for each stimset
References CA_DistDAQCreateCacheKey, CA_StoreEntryIntoCache, CA_TryFetchingEntryFromCache, OOdDAQParams::offsets, OOD_CalculateOffsetsYoked, OOD_CreateStimSet, OOdDAQParams::regions, ROWS.
Referenced by DC_GetConfiguration.
static wave OOD_CreateStimSet(OOdDAQParams *params)
Generate a stimset for "overlapped dDAQ" from the calculated offsets by OOD_CalculateOffsets().
params OOdDAQParams structure with the stimsets and offset information stimsets with offsets, one wave per offset
References ASSERT, OOdDAQParams::offsets, OOdDAQParams::postFeaturePoints, ROWS, OOdDAQParams::setColumns, OOdDAQParams::stimSets.
Referenced by OOD_Debugging, OOD_GetResultWaves.