MIES_AnalysisBrowser.ipf
const double EXPERIMENT_TREEVIEW_COLUMN
Referenced by AB_ButtonProc_CollapseAll, AB_ButtonProc_ExpandAll, AB_ExpandIfCollapsed, AB_GetExpandedIndices, AB_LoadFromExpandedRange, AB_LoadFromFile.
const double DEVICE_TREEVIEW_COLUMN
Referenced by AB_ButtonProc_ExpandAll, AB_ExpandIfCollapsed, AB_GetExpandedIndices, AB_LoadFromExpandedRange, AB_LoadFromFile.
const double AB_LOAD_SWEEP
Referenced by AB_ButtonProc_LoadSweeps, AB_LoadFromExpandedRange, AB_LoadFromFile.
const double AB_LOAD_STIMSET
Referenced by AB_ButtonProc_LoadStimsets, AB_LoadFromExpandedRange, AB_LoadFromFile.
const double LOAD_CONFIG_CHUNK_SIZE
Referenced by AB_LoadSweepConfigData.
static variable AB_ResetListBoxWaves(variable newSize)
References ASSERT, COLS, CreateBackupWave, GetExperimentBrowserGUIList, GetExperimentBrowserGUISel, LISTBOX_TREEVIEW, LISTBOX_TREEVIEW_EXPANDED, ROWS.
Referenced by AB_BrowserStartupSettings, AB_ScanFolder, BeforeFileOpenHook.
static variable AB_ClearAnalysisFolder()
Clear all waves of the main experiment browser and delete all folders inside GetAnalysisFolder().
References CallFunctionForEachListItem_TS, GetAnalysisBrowserMap, GetAnalysisFolder, GetExperimentBrowserGUIList, GetExperimentBrowserGUISel, GetListOfDataFolders, KillOrMoveToTrashPath, NOTE_INDEX, SetNumberInWaveNote.
Referenced by AB_ScanFolder.
static variable AB_AddMapEntry(string baseFolder, string discLocation)
Create relation (map) between file on disk and datafolder in current experiment.
index into mapping wave of the newly added entry or -1 if the file is already in the map
References ANALYSISBROWSER_FILE_TYPE_IGOR, ANALYSISBROWSER_FILE_TYPE_NWBv1, ASSERT, DEBUGPRINT, EnsureLargeEnoughWave, FindIndizes, GetAnalysisBrowserMap, GetAnalysisFolder, GetFileSuffix, GetNumberFromWaveNote, GetNWBMajorVersion, H5_CloseFile, H5_OpenFile, NOTE_INDEX, ReadNWBVersion, RemovePrefix, ROWS, SetNumberInWaveNote, UniqueDataFolder.
Referenced by AB_AddFile.
static variable AB_RemoveMapEntry(variable index)
References ASSERT, GetAnalysisBrowserMap, GetNumberFromWaveNote, NOTE_INDEX, ROWS, SetNumberInWaveNote.
Referenced by AB_AddFile.
wave AB_GetMap(string discLocation)
Get single matching entry from GetAnalysisBrowserMap.
discLocation first column. Path to file on disc wave with 4 columns Columns: 0: DiscLocation: Path to Experiment on Disc 1: FileName: Name of File in experiment column in ExperimentBrowser 2: DataFolder Data folder inside current Igor experiment 3: FileType File Type identifier for routing to loader functions, one of AnalysisBrowserFileTypes
References ASSERT, GetAnalysisBrowserMap, ROWS.
Referenced by AB_HasCompatibleVersion, AB_LoadFile, AB_LoadLabNotebook, AB_LoadLabNotebookFromFile, AB_LoadLabNotebookFromIgor, AB_LoadLabNotebookFromIgorLow, AB_LoadLabNotebookFromNWB, AB_LoadSweepFromNWB, AB_LoadSweepsFromExperiment.
wave AB_SaveDeviceList(string deviceList, string dataFolder)
save deviceList to wave
created wave.
References EnsureLargeEnoughWave, GetAnalysisDeviceWave, NOTE_INDEX, ROWS, SetNumberInWaveNote.
Referenced by AB_LoadFile.
static variable AB_AddFile(string baseFolder, string discLocation)
general loader for pxp, uxp and nwb files
0 if the file was loaded, or 1 if not (usually due to an error or because it was already loaded)
References AB_AddMapEntry, AB_LoadFile, AB_RemoveMapEntry, GetExperimentBrowserGUIList, GetNumberFromWaveNote, NOTE_INDEX.
Referenced by AB_ScanFolder, BeforeFileOpenHook.
static variable AB_LoadFile(string discLocation)
function tries to load Data From discLocation.
References AB_FillListWave, AB_GetMap, AB_HasCompatibleVersion, AB_LoadLabNotebook, AB_LoadResultsFromIgor, AB_LoadResultsFromNWB, AB_LoadSweepsFromExperiment, AB_LoadSweepsFromNWB, AB_LoadTPStorageFromIgor, AB_LoadTPStorageFromNWB, AB_LoadUserCommentAndHistoryFromNWB, AB_LoadUserCommentFromFile, AB_SaveDeviceList, ANALYSISBROWSER_FILE_TYPE_IGOR, ANALYSISBROWSER_FILE_TYPE_NWBv1, ASSERT, GetAnalysisChannelSweepWave, GetNumberFromWaveNote, NOTE_INDEX.
Referenced by AB_AddFile.
static variable AB_HasCompatibleVersion(string discLocation)
Check if the given file has a compatible version which this version of the analysis browser can handle.
discLocation file to check, parameter to AB_GetMap()
References AB_GetMap, AB_LoadDataWrapper, ANALYSIS_BROWSER_SUPP_VERSION, ANALYSISBROWSER_FILE_TYPE_IGOR, ANALYSISBROWSER_FILE_TYPE_NWBv1, ASSERT, ControlWindowToFront, DEBUGPRINT, GetAnalysisExpFolder, GetMiesPathAsString, IsFinite, LOAD_DATA_TYPE_NUMBERS.
Referenced by AB_LoadFile.
static string AB_GetSettingNumFiniteVals(wave wv, string device, variable sweepNo, string name)
References DATA_ACQUISITION_MODE, GetLastSetting.
Referenced by AB_FillListWave.
static variable AB_AddExperimentNameIfReq(string expName, WaveText list, string fileType, variable index)
Add an experiment entry into the list if there is none yet.
References EnsureLargeEnoughWave, FindIndizes, ROWS.
Referenced by AB_FillListWave.
static variable AB_FillListWave(string fileName, string device, string dataFolder, string fileType, wave sweepNums)
Creates list-view for AnalysisBrowser.
Depends on LabNoteBook to be loaded prior to call. fileName current Project's filename device current device dataFolder current Project's Lab Notebook DataFolder reference fileType current Project's file type, one of AnalysisBrowserFileTypes sweepNums Wave containing all sweeps actually present for device
References AB_AddExperimentNameIfReq, AB_GetSettingNumFiniteVals, DATA_ACQUISITION_MODE, EnsureLargeEnoughWave, GetAnalysisLabNBFolder, GetAnalysLBNumericalValues, GetAnalysLBTextualValues, GetExperimentBrowserGUIList, GetLastSetting, GetNumberFromWaveNote, isEmpty, NOTE_INDEX, NUM_HEADSTAGES, ROWS, SetNumberInWaveNote.
Referenced by AB_LoadFile.
static variable AB_LoadDataWrapper(dfref tmpDFR, string expFilePath, string datafolderPath, string listOfNames, variable typeFlags=defaultValue)
Load waves from a packed/unpacked experiment file.
This function is special as it does change the CDF! tmpDFR Temporary work folder, function returns with that folder as CDF expFilePath full path to the experiment file on disc datafolderPath igor datafolder to look for the waves inside the experiment listOfNames list of names of waves/strings/numbers to load typeFlags [optional, defaults to 1 (waves)] data types to load, valid values are the same as for LoadData, see also LoadDataConstants number of loaded items
References ASSERT, AssertOnAndClearRTError, ClearRTError, ConvertListToRegexpWithAlternations, COUNTOBJECTS_DATAFOLDER, COUNTOBJECTS_STR, COUNTOBJECTS_VAR, COUNTOBJECTS_WAVES, DataFolderExistsDFR, DisableDebugOnError, FileExists, FolderExists, GetBaseName, GetFileSuffix, GetFolder, GetListOfObjects, isEmpty, RemoveAllEmptyDataFolders, ResetDebugOnError.
Referenced by AB_HasCompatibleVersion, AB_LoadLabNotebookFromIgor, AB_LoadResultsFromIgor, AB_LoadStimsetRAW, AB_LoadStimsetTemplateWaves, AB_LoadSweepConfigData, AB_LoadSweepFromIgor, AB_LoadTPStorageFromIgor, AB_LoadUserCommentFromFile, AB_LoadWave.
static wave AB_GetSweepsFromLabNotebook(string dataFolder, string device, variable clean=defaultValue)
Returns a wave containing all present sweep numbers.
dataFolder DataFolder of HDF5 or Experiment File where LabNoteBook is saved device device for which to get sweeps. clean Variable indicating if ouput can contain duplicate values
References GetAnalysisLabNBFolder, GetSweepColumn, GetUniqueEntries.
Referenced by AB_GetHighestPossibleSweepNum.
static variable AB_GetHighestPossibleSweepNum(string dataFolder, string device)
Returns the highest referenced sweep number from the labnotebook.
References AB_GetSweepsFromLabNotebook.
Referenced by AB_LoadSweepsFromExperiment.
static wave AB_LoadSweepsFromExperiment(string discLocation, string device)
Returns a wave containing all present sweep numbers.
Function uses Config Waves from Igor Experiment to determine present sweeps discLocation location of Experiment File on Disc. ID in AnalysisBrowserMap device device for which to get sweeps.
References AB_GetHighestPossibleSweepNum, AB_GetMap, AB_LoadSweepConfigData, EnsureLargeEnoughWave, ExtractSweepNumber, GetAnalysisChannelSweepWave, GetAnalysisDeviceConfigFolder, GetListOfObjects, IsFinite, NOTE_INDEX, ROWS, SetNumberInWaveNote.
Referenced by AB_LoadFile.
static variable AB_LoadSweepsFromNWB(string discLocation, string dataFolder, string device)
Analyse data in NWB file and sort as sweeps.
Todo: Update this function for the use with SweepTable discLocation location of NWB File on Disc. ID in AnalysisBrowserMap dataFolder datafolder of the project device device for which to get sweeps.
References AB_StoreChannelsBySweep, GetAnalysisChannelAcqWave, GetAnalysisChannelStimWave, GetAnalysisChannelSweepWave, GetNWBMajorVersion, H5_CloseFile, H5_OpenFile, ReadAcquisition, ReadNWBVersion, ReadStimulus.
Referenced by AB_LoadFile.
static variable AB_StoreChannelsBySweep(variable groupID, variable nwbVersion, string channelList, WaveInteger sweeps, WaveText storage)
Store channelList in storage wave according to index in sweeps wave.
TodoUpdate this function for the use with SweepTable
References ASSERT, EnsureLargeEnoughWave, FindIndizes, GetNumberFromWaveNote, LoadSweepNumber, LoadSweepTable, NOTE_INDEX, ROWS, SetNumberInWaveNote.
Referenced by AB_LoadSweepsFromNWB.
static variable AB_LoadTPStorageFromIgor(string expFilePath, string expFolder, string device)
References AB_LoadDataWrapper, AB_TranslatePath, CallFunctionForEachListItem_TS, GetAnalysisDeviceTestpulse, GetDeviceTestPulseAsString, GetListOfObjects, KillOrMoveToTrashPath, TP_STORAGE_REGEXP.
Referenced by AB_LoadFile.
variable AB_LoadTPStorageFromNWB(string nwbFilePath, string expFolder, string device)
References GetAnalysisDeviceTestpulse, H5_CloseFile, H5_ListGroupMembers, H5_LoadDataset, H5_OpenFile, H5_OpenGroup, TP_STORAGE_REGEXP.
Referenced by AB_LoadFile.
static variable AB_LoadStoredTestpulsesFromNWB(string nwbFilePath, string expFolder, string device)
References GetAnalysisStoredTestPulses, H5_CloseFile, H5_ListGroupMembers, H5_LoadDataset, H5_OpenFile, H5_OpenGroup, NOTE_INDEX, ROWS, SetNumberInWaveNote, STORED_TESTPULSES_REGEXP.
Referenced by AB_ReExport.
static variable AB_LoadResultsFromIgor(string expFilePath, string expFolder)
References AB_LoadDataWrapper, GetAnalysisResultsFolder, GetResultsFolderAsString.
Referenced by AB_LoadFile.
static variable AB_LoadResultsFromNWB(string nwbFilePath, string expFolder)
References GetAnalysisResultsFolder, H5_CloseFile, H5_ListGroupMembers, H5_LoadDataset, H5_OpenFile, H5_OpenGroup, IsDataFolderEmpty, IsNaN, NWB_RESULTS.
Referenced by AB_LoadFile.
static variable AB_LoadUserCommentFromFile(string expFilePath, string expFolder, string device)
References AB_LoadDataWrapper, AB_TranslatePath, GetAnalysisDeviceFolder, GetDevicePathAsString, LOAD_DATA_TYPE_STRING.
Referenced by AB_LoadFile.
static variable AB_LoadUserCommentAndHistoryFromNWB(string nwbFilePath, string expFolder, string device)
References GetAnalysisDeviceFolder, GetHistoryAndLogFileDatasetName, GetNWBMajorVersion, H5_CloseFile, H5_OpenFile, H5_OpenGroup, ReadNWBVersion, ReadTextDataSetAsString.
Referenced by AB_LoadFile.
static string AB_LoadLabNotebook(string discLocation)
References AB_checkLabNotebook, AB_GetMap, AB_updateLabelsInLabNotebook, DEBUGPRINT, GetAnalysisLabNBFolder, KillOrMoveToTrash.
Referenced by AB_LoadFile.
static string AB_LoadLabNotebookFromFile(string discLocation)
References AB_GetMap, AB_LoadLabNotebookFromIgor, AB_LoadLabNotebookFromNWB, ANALYSISBROWSER_FILE_TYPE_IGOR, ANALYSISBROWSER_FILE_TYPE_NWBv1.
static string AB_LoadLabNotebookFromIgor(string discLocation)
References AB_GetMap, AB_LoadDataWrapper, AB_LoadLabNotebookFromIgorLow, ANALYSISBROWSER_FILE_TYPE_IGOR, COUNTOBJECTS_DATAFOLDER, DEVICE_NUMBERS, GetAnalysisFolder, GetLabNotebookFolderAsString, HW_ITC_BuildDeviceString, ITC_DEVICE_REGEXP, KillOrMoveToTrash, UniqueDataFolder.
Referenced by AB_LoadLabNotebookFromFile.
static variable AB_LoadLabNotebookFromIgorLow(string discLocation, string path, string device, string *deviceList)
Try loading the four labnotebooks from path.
discLocation experiment location on disc path datafolder path which holds the labnotebooks (might not exist) device name of the device deviceList list of loaded devices, for successful loads we add to that list
References AB_GetMap, DEBUGPRINT, GetAnalysisLabNBFolder.
Referenced by AB_LoadLabNotebookFromIgor.
static string AB_LoadLabNotebookFromNWB(string discLocation)
References AB_GetMap, AssertOnAndClearRTError, ClearRTError, DEBUGPRINT, GetAnalysisLabNBFolder, H5_CloseFile, H5_OpenFile, H5_OpenGroup, KillOrMoveToTrash, NWB_LoadLabNoteBook, ReadLabNoteBooks.
Referenced by AB_LoadLabNotebookFromFile.
static variable AB_checkLabNotebook(dfref dfr)
function checks if LabNoteBook Waves do exist.
dfr path to labNoteBook dataFolder reference. 0 labNotebook does not exist. 1 labNoteBook exists. also update dimension lables
Referenced by AB_LoadLabNotebook.
static variable AB_updateLabelsInLabNotebook(dfref dfr)
add dimension labels in older versions of igor-MIES and hdf5-loaded data overwrite invalid dim labels (labnotebook waves created with versions prior to a8f0f43)
References COLS, isEmpty, LBN_SetDimensionLabels.
Referenced by AB_LoadLabNotebook.
static string AB_TranslatePath(string path, string expFolder)
References GetAnalysisExpFolder.
Referenced by AB_LoadSweepConfigData, AB_LoadSweepFromIgor, AB_LoadTPStorageFromIgor, AB_LoadUserCommentFromFile.
static variable AB_LoadSweepConfigData(string expFilePath, string expFolder, string device, variable highestSweepNumber)
Load all Config_Sweep_* waves from the given experiment file or folder and the given device.
The implementation here tries to load LOAD_CONFIG_CHUNK_SIZE number of config sweep waves at a time until there could not be loaded at least one config sweep wave and we have reached highestSweepNumber. The size of LOAD_CONFIG_CHUNK_SIZE is limited by a limitation of LoadData as this operations accepts only a stringlist of waves shorter than 400 characters.
References AB_LoadDataWrapper, AB_TranslatePath, ASSERT, BuildList, GetAnalysisDeviceConfigFolder, GetDeviceDataPathAsString, IsFinite, LOAD_CONFIG_CHUNK_SIZE.
Referenced by AB_LoadSweepsFromExperiment.
static variable AB_ExpandListColumn(variable col)
Expand all tree views in the given column.
References AB_ExpandListEntry, AB_ReturnAndClearGUISelBits, AB_SetGUISelBits, FindIndizes, GetExperimentBrowserGUISel, LISTBOX_TREEVIEW, LISTBOX_TREEVIEW_EXPANDED, ROWS, SetBit.
Referenced by AB_ButtonProc_ExpandAll.
static variable AB_CollapseListColumn(variable col)
Collapse all tree views in the given column.
References AB_CollapseListEntry, AB_ReturnAndClearGUISelBits, AB_SetGUISelBits, ClearBit, FindIndizes, GetExperimentBrowserGUISel, LISTBOX_TREEVIEW, LISTBOX_TREEVIEW_EXPANDED, ROWS.
Referenced by AB_ButtonProc_CollapseAll.
static variable AB_SetGUISelBits(wave selBits)
Set the selection bits of the experiment browser ListBox selection wave.
selBits wave returned by AB_ReturnAndClearGUISelBits
References GetExperimentBrowserGUISel.
Referenced by AB_CollapseListColumn, AB_ExpandListColumn.
static wave AB_ReturnAndClearGUISelBits()
Return the selection bits from the experiment browser ListBox selection wave and clear them.
References GetExperimentBrowserGUISel, LISTBOX_SELECTED, ROWS.
Referenced by AB_CollapseListColumn, AB_ExpandListColumn.
static variable AB_CollapseListEntry(variable row, variable col)
Collapse the given treeview.
References AB_GetRowWithNextTreeView, ASSERT, CreateBackupWave, DEBUGPRINT, GetExperimentBrowserGUIList, GetExperimentBrowserGUISel, LISTBOX_TREEVIEW, LISTBOX_TREEVIEW_EXPANDED, ROWS.
Referenced by AB_CollapseListColumn, AB_ListBoxProc_ExpBrowser.
static variable AB_ExpandListEntry(variable row, variable col)
Expand the given treeview.
References AB_GetRowWithNextTreeView, ASSERT, CreateBackupWave, DEBUGPRINT, GetExperimentBrowserGUIList, GetExperimentBrowserGUISel, GetRowWithSameContent, LISTBOX_TREEVIEW, LISTBOX_TREEVIEW_EXPANDED, ROWS.
Referenced by AB_ExpandIfCollapsed, AB_ExpandListColumn, AB_ListBoxProc_ExpBrowser.
static variable AB_ExpandIfCollapsed(variable row, variable subSectionColumn)
0 if the treeview could be expanded, zero otherwise
References AB_ExpandListEntry, ASSERT, DEVICE_TREEVIEW_COLUMN, EXPERIMENT_TREEVIEW_COLUMN, GetExperimentBrowserGUISel, LISTBOX_TREEVIEW, LISTBOX_TREEVIEW_EXPANDED.
Referenced by AB_GetExpandedIndices.
static wave AB_GetExpandedIndices()
get indizes from AB window while successive expanding all columns
valid indizes wave on success
References AB_ExpandIfCollapsed, DEVICE_TREEVIEW_COLUMN, EXPERIMENT_TREEVIEW_COLUMN, FindIndizes, GetExperimentBrowserGUISel, PROP_MATCHES_VAR_BIT_MASK, ROWS.
Referenced by AB_LoadFromFile.
static variable AB_LoadFromExpandedRange(variable row, variable subSectionColumn, variable AB_LoadType, variable overwrite=defaultValue, dfref sweepBrowserDFR=defaultValue)
0 if at least one sweep or stimset could be loaded, 1 otherwise
References AB_GetRowWithNextTreeView, AB_LOAD_STIMSET, AB_LOAD_SWEEP, AB_LoadStimsetFromFile, AB_LoadSweepFromFile, ASSERT, DEVICE_TREEVIEW_COLUMN, EXPERIMENT_TREEVIEW_COLUMN, GetAnalysisBrowserMap, GetExperimentBrowserGUIList, GetExperimentBrowserGUISel, GetLastNonEmptyEntry, IsFinite, LISTBOX_TREEVIEW, SB_AddToSweepBrowser.
Referenced by AB_LoadFromFile.
static variable AB_GetRowWithNextTreeView(wave selWave, variable startRow, variable col)
Return the row with treeview in the column col starting from startRow.
References COLS, LISTBOX_TREEVIEW, ROWS.
Referenced by AB_CollapseListEntry, AB_ExpandListEntry, AB_LoadFromExpandedRange.
static variable AB_LoadFromFile(variable AB_LoadType, dfref sweepBrowserDFR=defaultValue)
References AB_GetExpandedIndices, AB_LOAD_STIMSET, AB_LOAD_SWEEP, AB_LoadFromExpandedRange, AB_LoadStimsetFromFile, AB_LoadSweepFromFile, ASSERT, DEVICE_TREEVIEW_COLUMN, EXPERIMENT_TREEVIEW_COLUMN, GetAnalysisBrowserMap, GetCheckBoxState, GetExperimentBrowserGUIList, GetLastNonEmptyEntry, IsFinite, ROWS, SB_AddToSweepBrowser.
Referenced by AB_ButtonProc_LoadStimsets, AB_ButtonProc_LoadSweeps.
variable AB_LoadStimsetForSweep(string device, variable index, variable sweep)
References AB_LoadStimsetFromFile, GetAnalysisBrowserMap.
Referenced by WB_OpenStimulusSetInWaveBuilder.
static variable AB_LoadFromFileASSERT(string discLocation, string dataFolder, string fileType, string device, variable sweep, variable overwrite)
References ASSERT, isEmpty.
Referenced by AB_LoadStimsetFromFile, AB_LoadSweepFromFile.
static variable AB_LoadSweepFromFile(string discLocation, string dataFolder, string fileType, string device, variable sweep, variable overwrite=defaultValue)
0 if the sweeps could be loaded, or already exists, and 1 on error
References AB_LoadFromFileASSERT, AB_LoadSweepFromIgor, AB_LoadSweepFromNWB, AB_SplitSweepIntoComponents, ANALYSISBROWSER_FILE_TYPE_IGOR, ANALYSISBROWSER_FILE_TYPE_NWBv1, ASSERT, createDFWithAllParents, DEBUGPRINT, GetAnalysisConfigWave, GetAnalysisSweepDataPathAS, KillOrMoveToTrash.
Referenced by AB_LoadAllSweepsAndStimsets, AB_LoadFromExpandedRange, AB_LoadFromFile.
static variable AB_LoadStimsetFromFile(string discLocation, string dataFolder, string fileType, string device, variable sweep, variable overwrite=defaultValue)
References AB_LoadCustomWaves, AB_LoadFromFileASSERT, AB_LoadStimsets, AB_LoadStimsetsRAW, ANALYSISBROWSER_FILE_TYPE_IGOR, ANALYSISBROWSER_FILE_TYPE_NWBv1, ASSERT, DEBUGPRINT, GetListDifference, H5_CloseFile, H5_OpenFile, NWB_GetStimsetFromSpecificSweep, NWB_LoadCustomWaves, NWB_LoadStimsets, OpenStimset, StimsetPathExists.
Referenced by AB_LoadAllSweepsAndStimsets, AB_LoadFromExpandedRange, AB_LoadFromFile, AB_LoadStimsetForSweep.
static variable AB_LoadSweepFromNWB(string discLocation, dfref sweepDFR, string device, variable sweep)
References AB_GetMap, AB_LoadSweepFromNWBgeneric, ASSERT, EnsureLargeEnoughWave, GetAnalysisChannelAcqWave, GetAnalysisChannelStimWave, GetAnalysisChannelStorage, GetAnalysisChannelSweepWave, GetAnalysisConfigWave, GetAnalysisDeviceWave, GetNumberFromWaveNote, GetNWBMajorVersion, H5_CloseFile, H5_OpenFile, NOTE_INDEX, OpenAcquisition, OpenStimulus, ReadNWBVersion, ROWS.
Referenced by AB_LoadSweepFromFile.
static variable AB_LoadSweepFromNWBgeneric(variable h5_groupID, variable nwbVersion, string channelList, dfref sweepDFR, WaveInteger configSweep)
References AB_SortConfigSweeps, AnalyseChannelName, ASSERT, COLS, CreateBackupWave, IsFinite, LoadStimulus, LoadTimeseries, ROWS, SetNumberInWaveNote, XOP_CHANNEL_TYPE_ADC, XOP_CHANNEL_TYPE_DAC, XOP_CHANNEL_TYPE_TTL.
Referenced by AB_LoadSweepFromNWB.
static variable AB_SortConfigSweeps(WaveInteger config)
Sorts the faked Config Sweeps Wave to get correct display order in Sweep Browser.
function is oriented at MDSort()
References AFH_GetChannelUnits, ASSERT, COLS, IsValidConfigWave, ROWS, TextWaveToList, XOP_CHANNEL_TYPE_ADC.
Referenced by AB_LoadSweepFromNWBgeneric.
static string AB_LoadSweepFromIgor(string discLocation, string expFolder, dfref sweepDFR, string device, variable sweep)
Load specified device/sweep combination from Igor experiment file to sweepDFR.
name of loaded sweep
References AB_LoadDataWrapper, AB_TranslatePath, dataPath, GetAnalysisFolder, GetDeviceDataPathAsString, KillOrMoveToTrash, ReplaceWaveWithBackup, UniqueDataFolder, WAVE_BACKUP_SUFFIX.
Referenced by AB_LoadSweepFromFile.
static variable AB_LoadStimsetsRAW(string expFilePath, string stimsets, variable overwrite)
a failsave alternative for AB_LoadStimsets() to load RAW stimsets
If a stimset could not get loaded using AB_LoadStimsets() this function is used in addition to try to load the stimset without its corresponding Parameter Waves. overwrite is not supported expFilePath Path on disc to igor experiment stimsets ";" separated list of all stimsets overwrite overwrite flag 1 on error and 0 on success
References AB_LoadStimsetRAW.
Referenced by AB_LoadStimsetFromFile.
static string AB_LoadStimsets(string expFilePath, string stimsets, variable overwrite, string processedStimsets=defaultValue)
Load specified stimsets from Igor experiment file.
recurses into all dependent stimsets as soon as they have been loaded. the list of stimsets is extended "on the left side": new items are added left. use numEnd to indicate unto which item the list was already processed. see StimsetRecursion() for a similar structure expFilePath Path on disc to igor experiment stimsets ";" separated list of all stimsets of the current sweep. processedStimsets [optional] input a list of already processed stimsets overwrite overwrite flag 1 on error and 0 on success
References AB_LoadStimset, AB_LoadStimsets, ListFromList, WB_StimsetFamilyNames.
Referenced by AB_LoadStimsetFromFile, AB_LoadStimsets.
static variable AB_LoadStimset(string expFilePath, string stimset, variable overwrite)
Load specified stimset from Igor experiment file.
1 on error and 0 on success
References AB_LoadStimsetRAW, AB_LoadStimsetTemplateWaves, WB_KillParameterWaves, WB_KillStimset, WB_ParameterWavesExist, WB_StimsetExists.
Referenced by AB_LoadStimsets.
static variable AB_LoadStimsetRAW(string expFilePath, string stimset, variable overwrite)
References AB_LoadDataWrapper, CHANNEL_TYPE_UNKNOWN, dataPath, GetAnalysisFolder, GetSetFolder, GetStimSetType, KillOrMoveToTrash, UniqueDataFolder, WB_KillParameterWaves, WB_KillStimset.
Referenced by AB_LoadStimset, AB_LoadStimsetsRAW.
static variable AB_LoadStimsetTemplateWaves(string expFilePath, string stimset)
Load template waves for a specific stimset from Igor experiment file.
1 on error and 0 on success
References AB_LoadDataWrapper, CHANNEL_TYPE_UNKNOWN, dataPath, GetAnalysisFolder, GetSetParamFolder, GetSetParamFolderAsString, GetStimSetType, KillOrMoveToTrash, STIMSET_PARAM_SEGWVTYPE, STIMSET_PARAM_WP, STIMSET_PARAM_WPT, UniqueDataFolder, WB_GetParameterWaveName, WB_ParameterWavesExist.
Referenced by AB_LoadStimset.
static string AB_LoadCustomWaves(string expFilePath, string stimsets, variable overwrite)
Load custom waves for specified stimset from Igor experiment file.
1 on error and 0 on success
References AB_LoadWave, CHANNEL_TYPE_DAC, CHANNEL_TYPE_TTL, GetSetFolderAsString, isEmpty, ROWS, WB_CustomWavesPathFromStimSet.
Referenced by AB_LoadStimsetFromFile.
static variable AB_LoadWave(string expFilePath, string fullPath, variable overwrite)
Load specified wave from Igor Experiment file.
1 on error and 0 on success
References AB_LoadDataWrapper, createDFWithAllParents, GetAnalysisFolder, GetFolder, isEmpty, KillOrMoveToTrash, RemovePrefix, UniqueDataFolder.
Referenced by AB_LoadCustomWaves.
static variable AB_SplitSweepIntoComponents(string expFolder, string device, variable sweep, wave sweepWave)
References GetAnalysisConfigWave, GetAnalysisLabNBFolder, GetAnalysisSweepDataPath, IsValidSweepAndConfig, KillOrMoveToTrash, SplitSweepIntoComponents, TTL_RESCALE_ON.
Referenced by AB_LoadSweepFromFile.
static variable AB_ScanFolder(string win)
References AB_AddFile, AB_ClearAnalysisFolder, AB_ResetListBoxWaves, ControlWindowToFront, GetAllFilesRecursivelyFromPath, GetExperimentBrowserGUIList, GetNumberFromWaveNote, GetNWBFilePathExport, GetSetVariableString, NOTE_INDEX, ROStr.
Referenced by AB_ButtonProc_ScanFolder, AB_ButtonProc_SelectDirectory.
string AB_GetPanelName()
Referenced by AB_BrowserStartupSettings, AB_OpenAnalysisBrowser.
string AB_OpenAnalysisBrowser()
References AB_GetPanelName, AddVersionToPanel, ANALYSISBROWSER_PANEL_VERSION, GetExperimentBrowserGUIList, GetExperimentBrowserGUISel, GetMiesVersion, HasPanelLatestVersion, panel, PS_InitCoordinates, SetSetVariableString, WindowExists.
Referenced by BeforeFileOpenHook, ScreenShotsForAnalysisBrowser.
static variable AB_CheckPanelVersion(string panel)
References ANALYSISBROWSER_PANEL_VERSION, DoAbortNow, HasPanelLatestVersion, panel.
Referenced by AB_ButtonProc_CollapseAll, AB_ButtonProc_ExpandAll, AB_ButtonProc_LoadStimsets, AB_ButtonProc_LoadSweeps, AB_ButtonProc_OpenCommentNB, AB_ButtonProc_ResaveAsNWB, AB_ButtonProc_ScanFolder, AB_ButtonProc_SelectDirectory, AB_ButtonProc_SelectStimSets, AB_ListBoxProc_ExpBrowser.
void AnalysisBrowser()
variable AB_BrowserStartupSettings()
References AB_GetPanelName, AB_ResetListBoxWaves, CHECKBOX_UNSELECTED, panel, SearchForInvalidControlProcs, SetCheckBoxState, SetSetVariableString, StoreCurrentPanelsResizeInfo.
variable AB_ButtonProc_ExpandAll(WMButtonAction *ba)
Button "Expand all".
References AB_CheckPanelVersion, AB_ExpandListColumn, DEVICE_TREEVIEW_COLUMN, EXPERIMENT_TREEVIEW_COLUMN.
variable AB_ButtonProc_CollapseAll(WMButtonAction *ba)
Button "Collapse all".
References AB_CheckPanelVersion, AB_CollapseListColumn, EXPERIMENT_TREEVIEW_COLUMN.
variable AB_ButtonProc_LoadSweeps(WMButtonAction *ba)
Button "Load Sweeps".
References AB_CheckPanelVersion, AB_LOAD_SWEEP, AB_LoadFromFile, AD_Update, BSP_GetSweepControlsPanel, LBV_SelectExperimentAndDevice, panel, PGC_SetAndActivateControl, SB_OpenSweepBrowser.
variable AB_ButtonProc_LoadStimsets(WMButtonAction *ba)
Button "Load Stimsets".
References AB_CheckPanelVersion, AB_LOAD_STIMSET, AB_LoadFromFile, WBP_CreateWaveBuilderPanel.
variable AB_ButtonProc_ScanFolder(WMButtonAction *ba)
Button "Scan folder".
References AB_CheckPanelVersion, AB_ScanFolder.
variable AB_ButtonProc_SelectDirectory(WMButtonAction *ba)
Button "Select directory" Display dialog box for choosing a folder and call AB_ScanFolder()
References AB_CheckPanelVersion, AB_ScanFolder, AskUserForExistingFolder, GetSetVariableString, SetSetVariableString.
variable AB_ButtonProc_SelectStimSets(WMButtonAction *ba)
Button "Select same stim set sweeps".
References AB_CheckPanelVersion, ControlWindowToFront, FindIndizes, GetExperimentBrowserGUIList, GetExperimentBrowserGUISel, isEmpty, LISTBOX_SELECTED, ROWS.
variable AB_ListBoxProc_ExpBrowser(WMListboxAction *lba)
main ListBox list_experiment_contents
References AB_CheckPanelVersion, AB_CollapseListEntry, AB_ExpandListEntry, COLS, CreateBackupWave, GetExperimentBrowserGUIList, GetExperimentBrowserGUISel, LISTBOX_TREEVIEW, LISTBOX_TREEVIEW_EXPANDED, ROWS.
variable AB_ButtonProc_OpenCommentNB(WMButtonAction *ba)
Button "Open comment NB".
References AB_CheckPanelVersion, ControlWindowToFront, FindIndizes, GetAnalysisBrowserMap, GetAnalysisDeviceFolder, GetExperimentBrowserGUIList, GetExperimentBrowserGUISel, GetLastNonEmptyEntry, isEmpty, ReplaceNotebookText, ROWS.
variable AB_ButtonProc_ResaveAsNWB(WMButtonAction *ba)
References AB_CheckPanelVersion, AB_ReExport, ANALYSISBROWSER_FILE_TYPE_NWBv1, ControlWindowToFront, GetAnalysisBrowserMap, GetCheckBoxState, GetNumberFromWaveNote, NOTE_INDEX.
static variable AB_LoadAllSweepsAndStimsets(string discLocation, string dataFolder, string fileType, string device)
References AB_LoadStimsetFromFile, AB_LoadSweepFromFile, GetAnalysisChannelSweepWave, IsValidSweepNumber, ROWS.
Referenced by AB_ReExport.
static variable AB_ReExport(variable index, variable overwrite)
References AB_GetAllDevicesForExperiment, AB_LoadAllSweepsAndStimsets, AB_LoadStoredTestpulsesFromNWB, GetAnalysisBrowserMap, GetAnalysisDeviceConfigFolder, GetAnalysisDeviceFolder, GetAnalysisLabNBFolder, GetAnalysisSweepPath, GetDAQDevicesFolderAsString, GetDeviceDataPath, GetDeviceDataPathAsString, GetDeviceTestPulse, GetDeviceTestPulseAsString, GetDevSpecLabNBFolder, GetDevSpecLabNBFolderAsString, GetFile, GetFileSuffix, GetFolder, GetLabNotebookFolder, GetLabNotebookFolderAsString, GetNWBFolderAS, GetWindowsPath, IsDataFolderEmpty, NWB_ExportAllData, NWB_VERSION_LATEST, RecreateMissingSweepAndConfigWaves, RenameDataFolderToUniqueName.
Referenced by AB_ButtonProc_ResaveAsNWB.
static variable BeforeFileOpenHook(variable refNum, string file, string pathName, string type, string creator, variable kind)
Load dropped NWB files into the analysis browser.
References AB_AddFile, AB_OpenAnalysisBrowser, AB_ResetListBoxWaves, GetExperimentBrowserGUIList, GetFileSuffix, GetNumberFromWaveNote, LOG_AddEntry, NOTE_INDEX, PACKAGE_MIES, PGC_SetAndActivateControl.
string AB_GetAllDevicesForExperiment(string dataFolder)
References GetAnalysisExpFolder, GetListOfDataFolders.
Referenced by AB_ReExport.
string AB_GetAllExperiments()
Return all experiments the analysis browser knows about.
References GetAnalysisBrowserMap, GetNumberFromWaveNote, NOTE_INDEX.