MIES_Logging.ipf
string LOG_GetFile(string package)
Get the absolute path to the log file.
References LOGFILE_NAME, PS_GetSettingsFolder_TS.
Referenced by LOG_AddEntryWithoutChecks, MEN_OpenMIESLogFile, NWB_AppendIgorHistoryAndLogFile, UploadLogFiles.
static variable LOG_HasRequiredKeys(variable JSONid)
Check that the given JSON document has the required top level keys.
Currently we require: ts: ISO8601 timestamp source: Source of the log entry, usually the function issuing the add entry exp: Name of the Igor Pro experiment
References GetSetIntersection, ROWS.
Referenced by LOG_AddEntryImp.
variable LOG_GenerateEntryTemplate(string source)
Generate a JSON text with all required entries.
Caller is responsible for the JSON text memory.
References GetExperimentName, GetIgorInstanceID, GetISO8601TimeStamp.
Referenced by LOG_AddEntryImp, UpdateZeroMQXOPLoggingTemplate.
variable LOG_MarkSessionStart(string package)
Adds a special entry to the logfile to mark the start of a session.
Should be called from IgorBeforeNewHook().
References LOG_AddEntryWithoutChecks, PS_Initialize.
Referenced by IgorStartOrNewHook.
static variable LOG_AddEntryWithoutChecks(string package, variable JSONid)
Adds the JSONid text to the logfile without any checks.
References LOG_GetFile.
Referenced by LOG_AddEntryImp, LOG_MarkSessionStart.
variable LOG_AddEntry(string package, string action, WaveText keys=defaultValue, WaveText values=defaultValue)
Add entry for the current function into the log file.
Usage: embed:rst:leading-asterisk * .. code-block:: igorpro * * Function DoWork() * * LOG_AddEntry("my package", "start") * * // ... * * LOG_AddEntry("my package", "end") * End * Result: embed:rst:leading-asterisk * .. code-block:: js * * {"action":"start","exp":"HardwareTests","source":"DoWork","ts":"2021-03-09T17:20:10.252+01:00"} * {"action":"end","exp":"HardwareTests","source":"DoWork","ts":"2021-03-09T17:20:10.298+01:00"} * * package package name, this determines the log file action additional string, can be something like start or end keys [optional, defaults to $""] Additional key-value pairs to be written into the log file. Same size as values. Either both keys and values are present or none. values [optional, defaults to $""] Additional key-value pairs to be written into the log file. Same size as keys. Either both keys and values are present or none.
References LOG_AddEntryImp, PS_GetSettingsFolder.
Referenced by AfterCompiledHook, ASSERT, BeforeExperimentSaveHook, BeforeFileOpenHook, BeforeUncompiledHook, BUG, DAP_LockDevice, DQM_FIFOMonitor, IgorBeforeNewHook, IgorBeforeQuitHook, IgorQuitHook, IgorStartOrNewHook, IH_Cleanup, NWB_ExportAllData, NWB_ExportAllStimsets, NWB_LoadAllStimsets, P_ButtonProc_UserPressure, P_Enable, TP_RecordTP, TPM_BkrdTPFuncMD.
variable LOG_AddEntry_TS(string package, string action, string caller, WaveText keys=defaultValue, WaveText values=defaultValue)
Threadsafe version of LOG_AddEntry()
Callers need to write the calling function name into caller. TodoIP9-only: merge with LOG_AddEntry
References LOG_AddEntryImp.
Referenced by ASSERT_TS, BUG_TS.
static variable LOG_AddEntryImp(string package, string action, string caller, WaveTextOrNull keys, WaveTextOrNull values)
References ASSERT_TS, LOG_AddEntryWithoutChecks, LOG_GenerateEntryTemplate, LOG_HasRequiredKeys, ROWS.
Referenced by LOG_AddEntry, LOG_AddEntry_TS.