MIES_PulseAveraging.ipf
const string PA_DRAWLAYER_XZEROLINE
const string PA_DRAWLAYER_SCALEBAR
const string PA_DRAWLAYER_FAILED_PULSES
const double PA_PULSE_SORTING_ORDER_SWEEP
Referenced by PA_ApplyPulseSortingOrder, PA_ShowImage.
const double PA_PULSE_SORTING_ORDER_PULSE
Referenced by PA_ApplyPulseSortingOrder.
PA_HIDE_AXIS
PA_HIDE_EXECUTION_TIME
const string PA_GRAPH_PREFIX
Referenced by PA_GetGraphPrefix.
const string PA_SOURCE_WAVE_TIMESTAMP
Referenced by PA_CreateAndFillPulseWaveIfReq.
const string PA_SETTINGS
Referenced by PA_DeserializeSettings.
const string PA_USER_DATA_X_START_RELATIVE_PREFIX
Referenced by PA_DrawScaleBarsHelper, PA_GetSetXAxisUserData.
const string PA_USER_DATA_CALC_XLENGTH
Referenced by PA_DrawScaleBarsHelper.
const string PA_USER_DATA_CALC_YLENGTH
Referenced by PA_DrawScaleBarsHelper.
const string PA_USER_DATA_USER_YLENGTH
Referenced by PA_DrawScaleBarsHelper.
const double PA_USE_WAVE_SCALES
Referenced by PA_DrawScaleBarsHelper, PA_ShowImage, PA_ShowPulses.
const double PA_USE_AXIS_SCALES
Referenced by PA_DrawScaleBarsHelper, PA_UpdateScaleBars.
const double PA_X_AXIS_OFFSET
Referenced by PA_GetSetXAxisUserData, PA_LayoutGraphs.
const double PA_PLOT_STEPPING
Referenced by PA_ShowPulses.
const double PA_DISPLAYMODE_TRACES
Referenced by PA_DrawScaleBars, PA_DrawScaleBarsHelper, PA_GetGraph, PA_GetGraphPrefix, PA_IsDataOnSubPlot, PA_LayoutGraphs, PA_ShowPulses, PA_UpdateScaleBars.
const double PA_DISPLAYMODE_IMAGES
Referenced by PA_AddColorScales, PA_DrawScaleBars, PA_DrawScaleBarsHelper, PA_GetGraph, PA_GetGraphPrefix, PA_IsDataOnSubPlot, PA_LayoutGraphs, PA_SetColorScale, PA_ShowImage, PA_UpdateScaleBars.
const double PA_DISPLAYMODE_ALL
Referenced by PA_GetGraphPrefix, PA_PreProcessPulses, PA_Update.
const double PA_COLORSCALE_PANEL_WIDTH
Referenced by PA_GetGraph, PA_ResizeColorScalePanel.
const double PA_PEAK_BOX_AVERAGE
Referenced by PA_SpikePositionsForNonVC.
const double PA_AVGERAGE_PLOT_LSIZE
Referenced by PA_ShowPulses.
const double PA_DECONVOLUTION_PLOT_LSIZE
Referenced by PA_ShowPulses.
const string PA_PROPERTIES_KEY_REGIONS
Referenced by PA_GenerateAllPulseWaves, PA_GetSetIndicesHelper.
const string PA_PROPERTIES_KEY_CHANNELS
Referenced by PA_GenerateAllPulseWaves, PA_GetSetIndicesHelper.
const string PA_PROPERTIES_KEY_PREVREGIONS
Referenced by PA_GenerateAllPulseWaves, PA_GetSetIndicesHelper.
const string PA_PROPERTIES_KEY_PREVCHANNELS
Referenced by PA_GenerateAllPulseWaves, PA_GetSetIndicesHelper.
const string PA_PROPERTIES_KEY_SWEEPS
Referenced by PA_GenerateAllPulseWaves.
const string PA_PROPERTIES_KEY_LAYOUTCHANGE
Referenced by PA_GenerateAllPulseWaves, PA_ShowImage, PA_ShowPulses.
const string PA_PROPERTIES_STRLIST_SEP
Referenced by PA_GenerateAllPulseWaves, PA_GetSetIndicesHelper.
const string PA_SETINDICES_KEY_ACTIVECHANCOUNT
Referenced by PA_UpdateIndiceNotesImpl.
const string PA_SETINDICES_KEY_ACTIVEREGIONCOUNT
Referenced by PA_UpdateIndiceNotesImpl.
const string PA_SETINDICES_KEY_DISPCHANGE
Referenced by PA_UpdateIndiceNotesImpl.
const string PA_SETINDICES_KEY_DISPSTART
Referenced by PA_CopySetIndiceSizeDispRestart, PA_InitPASIInParts.
const double PA_UPDATEINDICES_TYPE_PREV
Referenced by PA_UpdateIndiceNotes, PA_UpdateIndiceNotesImpl.
const double PA_UPDATEINDICES_TYPE_CURR
Referenced by PA_UpdateIndiceNotes, PA_UpdateIndiceNotesImpl.
const double PA_INDICESCHANGE_NONE
Referenced by PA_UpdateIndiceNotesImpl.
const double PA_INDICESCHANGE_MOVED
Referenced by PA_UpdateIndiceNotesImpl.
const double PA_INDICESCHANGE_REMOVED
Referenced by PA_UpdateIndiceNotesImpl.
const double PA_INDICESCHANGE_ADDED
Referenced by PA_UpdateIndiceNotesImpl.
const double PA_PASIINIT_BASE
Referenced by PA_GenerateAllPulseWaves, PA_InitPASIInParts, PA_PreProcessPulses, PA_UpdateScaleBars.
const double PA_PASIINIT_INDICEMETA
Referenced by PA_GenerateAllPulseWaves, PA_InitPASIInParts, PA_PreProcessPulses, PA_UpdateScaleBars.
const double PA_MINIMUM_SPIKE_WIDTH
Referenced by PA_SpikePositionsForNonVC.
static string PA_GetGraphs(string win, variable displayMode)
Return a list of all graphs.
References GetMainWindow, PA_GetGraphPrefix.
Referenced by PA_PreProcessPulses, PA_SetColorScale, PA_ShowImage, PA_ShowPulses, PA_Update.
static string PA_GetGraphName(string win, PulseAverageSettings *pa, variable displayMode, variable channelNumber, variable activeRegionCount)
References PulseAverageSettings::multipleGraphs, PA_GetGraphPrefix.
Referenced by PA_AddColorScales, PA_GetGraph, PA_LayoutGraphs.
static string PA_GetGraphPrefix(string win, variable displayMode)
References ASSERT, GetMainWindow, PA_DISPLAYMODE_ALL, PA_DISPLAYMODE_IMAGES, PA_DISPLAYMODE_TRACES, PA_GRAPH_PREFIX.
Referenced by PA_GetGraphName, PA_GetGraphs.
string PA_GetColorScalePanel(string win)
Return the subwindow path to the panel which holds the graphs with the color scales.
Only present for PA_DISPLAYMODE_IMAGES graphs.
Referenced by PA_GetColorScaleGraph, PA_ResizeColorScalePanel.
string PA_GetColorScaleGraph(string win)
Return the subwindow path to the graph which holds the color scales.
Only present for PA_DISPLAYMODE_IMAGES graphs.
References PA_GetColorScalePanel.
Referenced by PA_AddColorScales, PA_ResizeColorScalePanel, PA_SetColorScale.
static string PA_GetGraph(string mainWin, PulseAverageSettings *pa, variable displayMode, variable channelNumber, variable region, variable activeRegionCount, variable activeChanCount, variable numRegions)
Return the name of the pulse average graph.
This function takes care of creating a graph if it does not exist, and laying it out correctly Layout scheme for multiple graphs turned on: Positions the graphs right to mainWin in matrix form Columns: Regions (aka headstages with pulse starting time information respecting region selection in GUI) Rows: Active unique channels
References ASSERT, PulseAverageSettings::multipleGraphs, PA_COLORSCALE_PANEL_WIDTH, PA_DISPLAYMODE_IMAGES, PA_DISPLAYMODE_TRACES, PA_GetGraphName, PA_GetTraceCountFromGraphData, PS_InitCoordinates, WindowExists.
Referenced by PA_DrawScaleBars, PA_DrawXZeroLines, PA_ShowImage, PA_ShowPulses.
static wave PA_GetAxes(PulseAverageSettings *pa, variable channel, variable region)
Return the names of the vertical and horizontal axes.
References PulseAverageSettings::multipleGraphs.
Referenced by PA_InitPASIInParts.
static wave PA_CalculatePulseInfos(wave DA, string fullPath, variable channelNumber, variable totalOnsetDelay)
Derive the pulse infos from a DA wave.
Uses plain FindLevels after the onset delay using 10% of the full range above the minimum as threshold pulse info wave or if nothing could be found, an invalid wave reference
References ASSERT, CA_PulseTimes, CA_StoreEntryIntoCache, CA_TryFetchingEntryFromCache, FINDLEVEL_EDGE_BOTH, GetPulseInfoWave, IsInteger, IsOdd, ROWS.
Referenced by PA_GetPulseInfos.
static wave PA_GetUniqueHeadstages(WaveText traceData)
Return a wave with headstage numbers, duplicates replaced with NaN so that the indizes still correspond the ones in traceData.
References GetUniqueEntries, ROWS.
Referenced by PA_GenerateAllPulseWaves.
wave PA_GetPulseInfos(WaveText traceData, variable idx, variable region, string channelTypeStr)
Return pulse infos.
traceData 2D wave with trace information, from GetTraceInfos() idx Index into traceData, used for determining sweep numbers, labnotebooks, etc. region Region (headstage) to get pulse starting times for channelTypeStr Type of the channel, one of XOP_CHANNEL_NAMES invalid wave reference if no pulses could be found or 2D wave see GetPulseInfoWave()
References ASSERT, DATA_ACQUISITION_MODE, DataFolderExistsDFR, DEBUGPRINT, EPOCHS_ENTRY_KEY, GetDAQDataSingleColumnWave, GetLastSetting, GetTotalOnsetDelay, IsNaN, PA_CalculatePulseInfos, PA_DiffPulseInfos, PA_RetrievePulseInfosFromEpochs, XOP_CHANNEL_TYPE_DAC.
Referenced by PA_GenerateAllPulseWaves, SBE_GetPulseStartTimesForSel.
static variable PA_DiffPulseInfos(wave numericalValues, variable sweepNo, WaveOrNull pulseInfosEpochs, WaveOrNull pulseInfosCalc)
Compare epoch and calculated pulse infos.
References COLS, DATA_ACQUISITION_MODE, GetLastSettingIndep, ROWS.
Referenced by PA_GetPulseInfos.
static wave PA_RetrievePulseInfosFromEpochs(string epochInfo)
Extracts the pulse info from the lab notebook and returns them as wave.
epochInfo epoch data to extract pulse starting times pulse info, see GetPulseInfoWave() or an invalid wave reference on error
References ASSERT, EP_EpochStrToWave, EPOCH_COL_ENDTIME, EPOCH_COL_STARTTIME, EPOCH_COL_TAGS, EPOCH_COL_TREELEVEL, GetPulseInfoWave, IsEmpty, IsNaN, IsValidEpochNumber, ROWS, WB_TOTAL_NUMBER_OF_EPOCHS.
Referenced by PA_GetPulseInfos.
static variable PA_GetPulseLength(wave pulseInfos, variable pulseIndex, variable overridePulseLength, variable fixedPulseLength)
References ASSERT, COLS, ROWS.
Referenced by PA_GenerateAllPulseWaves.
static std::tuple< WAVE, WAVE > PA_CreateAndFillPulseWaveIfReq(WaveOrNull wv, dfref singleSweepFolder, variable channelType, variable channelNumber, variable clampMode, variable region, variable pulseIndex, variable first, variable length, wave pulseInfos)
Single pulse wave creator.
The wave note for the pulse waves is stored in a separate empty wave. This speeds up the caching logic for the pulse waves a lot. The wave note is used for documenting the applied operations: $NOTE_KEY_FAILED_PULSE_LEVEL: Level used for failed pulse search $NOTE_KEY_NUMBER_OF_SPIKES: Number of spikes used for failed pulse search $NOTE_KEY_PULSE_LENGTH: Length in points of the pulse wave (before any operations) $NOTE_KEY_SEARCH_FAILED_PULSE: Checkbox state of "Search failed pulses" $NOTE_KEY_TIMEALIGN: Time alignment was active and applied $NOTE_KEY_TIMEALIGN_TOTAL_OFFSET: Calculated offset from time alignment $NOTE_KEY_ZEROED: Zeroing was active and applied $NOTE_KEY_WAVE_MINIMUM: Minimum value of the data $NOTE_KEY_WAVE_MAXIMUM: Maximum value of the data $NOTE_KEY_TIMEALIGN_FEATURE_POS: Position where the feature for time alignment was found $NOTE_KEY_PULSE_IS_DIAGONAL: Stores if pulse is shown in the diagonal of the output layout $PA_SOURCE_WAVE_TIMESTAMP: Last modification time of the pulse wave before creation. $NOTE_KEY_PULSE_START: ms coordinates where the pulse starts $NOTE_KEY_PULSE_END: ms coordinates where the pulse ends $NOTE_KEY_PULSE_CLAMPMODE: Clamp mode of the pulse data, one of AmplifierClampModes Diagonal pulses only with failed pulse search enabled: $NOTE_KEY_PULSE_HAS_FAILED: Pulse has failed $NOTE_KEY_PULSE_SPIKE_POSITIONS: Comma separated list of spike positions in ms. 0 is the start of the pulse.
References ClearWaveNoteExceptWaveVersion, CreateBackupWave, GetNumberFromWaveNote, GetPulseAverageWave, GetPulseAverageWaveNoteWave, NOTE_KEY_CLAMP_MODE, NOTE_KEY_PULSE_END, NOTE_KEY_PULSE_LENGTH, NOTE_KEY_PULSE_START, NOTE_KEY_SEARCH_FAILED_PULSE, NOTE_KEY_TIMEALIGN, NOTE_KEY_ZEROED, PA_SOURCE_WAVE_TIMESTAMP, PA_UpdateMinAndMax, ROWS, SetNumberInWaveNote.
Referenced by PA_GenerateAllPulseWaves.
static variable PA_UpdateMinAndMax(wave wv, wave noteWave)
References NOTE_KEY_WAVE_MAXIMUM, NOTE_KEY_WAVE_MINIMUM, SetNumberInWaveNote, WaveMinAndMaxWrapper.
Referenced by PA_CreateAndFillPulseWaveIfReq, PA_ZeroWave.
static string PA_GenerateFailedPulseKey(variable sweep, variable region, variable pulse)
Generate a key for a pulse.
All pulses with that key are either failing or passing.
Referenced by PA_MarkFailedPulses.
static std::tuple< WaveDouble, WaveText > PA_GetSweepsAndExperimentsFromIndices(string win, WaveOrNull additionalData)
References OVS_GetSweepAndExperiment, ROWS.
Referenced by PA_GenerateAllPulseWaves, PA_ShowImage.
static std::tuple< PulseAverageSetIndices > PA_GenerateAllPulseWaves(string win, PulseAverageSettings *pa, variable mode, WaveOrNull additionalData)
Create all single pulse waves.
This function needs to be called when ever traces in the databrowser/sweepbrowser are removed or added. Idea: Gather all AD sweep traces in the databrowser/sweepbrowser (skipping duplicates from oodDAQ) Iterate over all regions (there are as many regions as unique headstages) Now gather the pulse starting time from the region and create single pulse waves for all of them The result is feed into GetPulseAverageProperties() and GetPulseAveragepropertiesWaves() for further consumption. Fast path for incremental update: The previous list of regions/channels is saved We get the indizes of the new sweep (from additionalData) Only these indizes are added to the properties wave, as well as the setIndice waves at the end information is stored where the new data begins The region/channels of the new Sweep(s) are merged with the old ones. In case the layout changed compared to the old regions/channels it is calculated again.
References ASSERT, COLS, DataFolderExistsDFR, PulseAverageSettings::dfr, PulseAverageSettings::endingPulse, EnsureLargeEnoughWave, FindIndizes, PulseAverageSettings::fixedPulseLength, GetDAQDataSingleColumnWave, GetDevicePulseAverageFolder, GetDevicePulseAverageHelperFolder, GetLastSweepWithSetting, GetMachineEpsilon, GetMainWindow, GetNumberFromWaveNote, GetPulseAverageDisplayMapping, GetPulseAverageProperties, GetPulseAveragePropertiesWaves, GetPulseAverageSetIndizes, GetSingleSweepFolder, GetStringFromWaveNote, GetTotalOnsetDelay, GetTraceInfos, IsNaN, IsValidSweepNumber, LAYERS, MergeLists, MINIMUM_WAVE_SIZE, NOTE_INDEX, NOTE_PA_NEW_PULSES_START, PulseAverageSettings::overridePulseLength, OVS_GetHeadstageRemoval, PA_CopySetIndiceSizeDispRestart, PA_CreateAndFillPulseWaveIfReq, PA_GetPulseInfos, PA_GetPulseLength, PA_GetSetIndicesHelper, PA_GetSweepsAndExperimentsFromIndices, PA_GetUniqueHeadstages, PA_InitPASIInParts, PA_PASIINIT_BASE, PA_PASIINIT_INDICEMETA, PA_PROPERTIES_INDEX_CHANNELNUMBER, PA_PROPERTIES_INDEX_CLAMPMODE, PA_PROPERTIES_INDEX_HEADSTAGE, PA_PROPERTIES_INDEX_LASTSWEEP, PA_PROPERTIES_INDEX_PULSE, PA_PROPERTIES_INDEX_REGION, PA_PROPERTIES_INDEX_SWEEP, PA_PROPERTIES_KEY_CHANNELS, PA_PROPERTIES_KEY_LAYOUTCHANGE, PA_PROPERTIES_KEY_PREVCHANNELS, PA_PROPERTIES_KEY_PREVREGIONS, PA_PROPERTIES_KEY_REGIONS, PA_PROPERTIES_KEY_SWEEPS, PA_PROPERTIES_STRLIST_SEP, PA_PROPERTIESWAVES_INDEX_PULSE, PA_PROPERTIESWAVES_INDEX_PULSENOTE, PA_SetDiagonalityNote, PA_UpdateIndiceNotes, POST_PLOT_ADDED_SWEEPS, ROWS, SetNumberInWaveNote, SetStringInWaveNote, PulseAverageSettings::startingPulse, XOP_CHANNEL_NAMES, XOP_CHANNEL_TYPE_ADC.
Referenced by PA_PreProcessPulses.
static variable PA_SetDiagonalityNote(wave indices, variable startIndex, variable numEntries, WaveRefWave propertiesWaves, variable isDiagonal)
References NOTE_KEY_PULSE_IS_DIAGONAL, SetNumberInWaveNote.
Referenced by PA_GenerateAllPulseWaves.
static std::tuple< PulseAverageSetIndices > PA_InitPASIInParts(PulseAverageSettings *pa, variable part, variable disableIncremental)
This function fills a structure with information we need in most further processing functions, e.g. PA DFs, references to properties, setIndice waves, regions, channels, axes, a.s.o. Since not every information might be available at the time this structure is filled there are two steps defined, that are enabled by setting 'part' with PA_PASIINIT_BASE and/or PA_PASIINIT_INDICEMETA.
pa PulseAverageSettings structure part filling step for the returned structure, set depending on available data disableIncremental When set then the meta information for incremental updates is just initialized with zero.
References PulseAverageSettings::dfr, DuplicateWaveToFree, GetDevicePulseAverageFolder, GetDevicePulseAverageHelperFolder, GetNumberFromWaveNote, GetPulseAverageProperties, GetPulseAveragePropertiesWaves, IsNaN, NOTE_INDEX, PA_GetAxes, PA_GetSetIndicesHelper, PA_GetSetWaves, PA_PASIINIT_BASE, PA_PASIINIT_INDICEMETA, PA_SETINDICES_KEY_DISPSTART, ROWS.
Referenced by PA_GenerateAllPulseWaves, PA_PreProcessPulses, PA_UpdateScaleBars.
static variable PA_CopySetIndiceSizeDispRestart(WaveRefWave setIndices)
For incremental display update copy current size of of setIndices to new display start.
References GetNumberFromWaveNote, IsNaN, NOTE_INDEX, PA_SETINDICES_KEY_DISPSTART, SetNumberInWaveNote.
Referenced by PA_GenerateAllPulseWaves.
static std::tuple< WaveRefWave, WAVE, WAVE, WAVE > PA_GetSetIndicesHelper(dfref pulseAverageHelperDFR, variable prevIndices)
Retrieve setIndices, channels and regions of the current or the previous layout, as is saved in the properties wave wave note.
pulseAverageHelperDFR Reference to pulse average helper DF prevIndices When set then the indices, channels and regions of the previous layout are returned, otherwise the current layout is returned. Note that only the layout is considered, the returned indices always contain the current indices for each channel/region at the time of calling this function.
References GetPulseAverageProperties, GetPulseAverageSetIndizes, GetStringFromWaveNote, ListToNumericWave, PA_PROPERTIES_KEY_CHANNELS, PA_PROPERTIES_KEY_PREVCHANNELS, PA_PROPERTIES_KEY_PREVREGIONS, PA_PROPERTIES_KEY_REGIONS, PA_PROPERTIES_STRLIST_SEP, ROWS.
Referenced by PA_GenerateAllPulseWaves, PA_InitPASIInParts, PA_UpdateIndiceNotes.
static variable PA_UpdateIndiceNotes(wave currentDisplayMapping, wave prevDisplayMapping, PulseAverageSetIndices *pasi, variable layoutChanged)
Updates the setIndices notes with information about the layout and layout changes. Therefore the function compares the previous display mapping and the current display mapping for each region/channel in the layout and determines if the setIndices at this region/channel are added as new/moved/stayed at the same position or were removed. In the setIndices wave note the following keys are set: '$PA_SETINDICES_KEY_DISPCHANGE': change in the layout for this set '$PA_SETINDICES_KEY_ACTIVEREGIONCOUNT': grid location on the vertical where this set is displayed '$PA_SETINDICES_KEY_ACTIVECHANCOUNT': grid location on the horizontal where this set is displayed (this data is currently not used, but created for further PA plot extension)
currentDisplayMapping 3D wave, rows and columns map the region/channels, in the two layers the associated activeRegion and activeChannel are stored. The layer information is the position in the grid of the layout. prevDisplayMapping Technically the same wave as currentDisplayMapping, but it stores the information about the previous layout. pasi Pulse Average structure storing PA information layoutChanged when set then the layout has changed compared to the previous one displayed. This is directly related to a region/channel change.
References PulseAverageSetIndices::channels, PulseAverageSetIndices::indexHelper, PA_GetSetIndicesHelper, PA_UpdateIndiceNotesImpl, PA_UPDATEINDICES_TYPE_CURR, PA_UPDATEINDICES_TYPE_PREV, PulseAverageSetIndices::pulseAverageHelperDFR, PulseAverageSetIndices::regions, PulseAverageSetIndices::setIndices.
Referenced by PA_GenerateAllPulseWaves.
static variable PA_UpdateIndiceNotesImpl(wave indices, wave currentMap, wave oldMap, variable channel, variable region, variable layoutChanged, variable indiceType)
Evaluate the previous and current mapping and set the display change in the wave note of the indice sets as well as activeChanCount, activeRegionCount. IMPORTANT: To have a consistent state for the case the layout changed the function must be called with the current and the previous indices. Otherwise removed sets wont be flagged properly.
References ASSERT_TS, DEBUGPRINT, NOTE_KEY_PULSE_SORT_ORDER, PA_INDICESCHANGE_ADDED, PA_INDICESCHANGE_MOVED, PA_INDICESCHANGE_NONE, PA_INDICESCHANGE_REMOVED, PA_SETINDICES_KEY_ACTIVECHANCOUNT, PA_SETINDICES_KEY_ACTIVEREGIONCOUNT, PA_SETINDICES_KEY_DISPCHANGE, PA_UPDATEINDICES_TYPE_CURR, PA_UPDATEINDICES_TYPE_PREV, SetNumberInWaveNote.
Referenced by PA_UpdateIndiceNotes.
static variable PA_ApplyPulseSortingOrder(wave setIndices, variable channelNumber, variable region, wave properties, PulseAverageSettings *pa)
References ASSERT_TS, GetNumberFromWaveNote, IsFinite, NOTE_INDEX, NOTE_KEY_PULSE_SORT_ORDER, PA_PROPERTIES_INDEX_PULSE, PA_PROPERTIES_INDEX_SWEEP, PA_PULSE_SORTING_ORDER_PULSE, PA_PULSE_SORTING_ORDER_SWEEP, PulseAverageSettings::pulseSortOrder, SetNumberInWaveNote.
Referenced by PA_PreProcessPulses.
static variable PA_GatherSettings(string win, PulseAverageSettings *s)
Populates pps.pulseAverSett with the user selection from the panel.
References PulseAverageSettings::autoTimeAlignment, BSP_GetFolder, BSP_GetPanel, BSP_IsActive, PulseAverageSettings::deconvolution, PulseAverageSettings::dfr, PulseAverageSettings::drawXZeroLine, PulseAverageSettings::enabled, PulseAverageSettings::endingPulse, PulseAverageSettings::failedNumberOfSpikes, PulseAverageSettings::failedPulsesLevel, PulseAverageSettings::fixedPulseLength, GetMainWindow, GetPopupMenuIndex, GetPopupMenuString, GetSetVariable, GetSliderPositionIndex, PulseAverageSettings::hideFailedPulses, PulseAverageSettings::imageColorScale, InitPulseAverageSettings, MIES_BSP_PA, MIES_BSP_PANEL_FOLDER, PulseAverageSettings::multipleGraphs, PulseAverageSettings::overridePulseLength, PA_DeconvGatherSettings, PulseAverageSettings::pulseSortOrder, PulseAverageSettings::regionSlider, PulseAverageSettings::searchFailedPulses, PulseAverageSettings::showAverage, PulseAverageSettings::showImages, PulseAverageSettings::showIndividualPulses, PulseAverageSettings::showTraces, PulseAverageSettings::startingPulse, PulseAverageSettings::yScaleBarLength, PulseAverageSettings::zeroPulses.
Referenced by PA_Update, PA_UpdateScaleBars.
static variable PA_DeconvGatherSettings(string win, PulseAverageDeconvSettings *deconvolution)
gather deconvolution settings from PA section in BSP
References BSP_GetPanel, PulseAverageDeconvSettings::enable, GetSetVariable, PulseAverageDeconvSettings::range, PulseAverageDeconvSettings::smth, PulseAverageDeconvSettings::tau.
Referenced by PA_GatherSettings.
variable PA_Update(string win, variable mode, WaveOrNull additionalData=defaultValue)
Update the PA plot to accomodate changed settings.
References DEBUGPRINT, GetMainWindow, KillWindows, PA_DetermineConstantSettings, PA_DISPLAYMODE_ALL, PA_GatherSettings, PA_GetGraphs, PA_PreProcessPulses, PA_SerializeSettings, PA_ShowImage, PA_ShowPulses.
Referenced by BSP_CheckBoxProc_PerPulseAver, PA_CheckProc_Common, PA_PopMenuProc_Common, PA_SetVarProc_Common, PostPlotTransformations.
static wave PA_GetSetWaves(dfref dfr, variable channelNumber, variable region, variable removeFailedPulses=defaultValue)
Returns the two column setWave with pulse/pulsenote.
References GetPulseAverageProperties, GetPulseAveragePropertiesWaves, GetPulseAverageSetIndizes, PA_GETSETWAVES_ALL, PA_GetSetWaves_TS, WaveRef.
Referenced by PA_InitPASIInParts, PA_ShowImage.
static wave PA_GetSetWaves_TS(wave properties, WaveRefWave propertiesWaves, wave setIndizes, variable getMode, variable removeFailedPulses)
Returns a 1D wave ref wave containing the refs to the setwave2 refs of {all, new, old} sets, depending on the mode constant given in getModes. For mode constants.
PAGetSetWavesModes, they can be combined by ORing the bits. Each setWave2 component wave entry in the returned wave is a 2D wave ref wave that refrences the pulse data in col 0, and the pulse note in col 1. The rows count the pulses.
References GetNumberFromWaveNote, NOTE_INDEX, NOTE_PA_NEW_PULSES_START, PA_GETSETWAVES_ALL, PA_GETSETWAVES_NEW, PA_GETSETWAVES_OLD, PA_PROPERTIES_INDEX_PULSEHASFAILED, PA_PROPERTIESWAVES_INDEX_PULSE, PA_PROPERTIESWAVES_INDEX_PULSENOTE.
Referenced by PA_CalculateAllAverages, PA_GetSetWaves.
static variable PA_MarkFailedPulses(PulseAverageSettings *pa, PulseAverageSetIndices *pasi)
Handle marking pulses as failed/passed if required.
References PulseAverageSetIndices::channels, GetNumberFromWaveNote, IsNaN, NOTE_INDEX, NOTE_KEY_SEARCH_FAILED_PULSE, PulseAverageSetIndices::numEntries, PA_GenerateFailedPulseKey, PA_PROPERTIES_INDEX_PULSE, PA_PROPERTIES_INDEX_PULSEHASFAILED, PA_PROPERTIES_INDEX_SWEEP, PA_PROPERTIESWAVES_INDEX_PULSE, PA_PROPERTIESWAVES_INDEX_PULSENOTE, PA_PulseHasFailed, PA_TagSearchedPulses, PulseAverageSetIndices::properties, PulseAverageSetIndices::propertiesWaves, PulseAverageSetIndices::regions, ROWS, PulseAverageSettings::searchFailedPulses, PulseAverageSetIndices::setIndicesUnsorted, SetNumberInWaveNote, PulseAverageSetIndices::startEntry.
Referenced by PA_PreProcessPulses.
static variable PA_TagSearchedPulses(PulseAverageSettings *pa, wave wv)
References PulseAverageSettings::failedNumberOfSpikes, PulseAverageSettings::failedPulsesLevel, NOTE_KEY_FAILED_PULSE_LEVEL, NOTE_KEY_NUMBER_OF_SPIKES, SetNumberInWaveNote.
Referenced by PA_MarkFailedPulses.
static variable PA_GetTraceCountFromGraphData(string graph, variable clear=defaultValue)
This function returns data from the light-weight data storage for PA graph data.
graph name of PA graph clear [optional, default = 0] when set reinitializes the data for the given graph row index of the wave where the graph data is stored
References GetPAGraphData, ROWS.
Referenced by PA_ClearGraphs, PA_GetGraph, PA_ShowImage, PA_ShowPulses.
static string PA_ShowPulses(string win, PulseAverageSettings *pa, PA_ConstantSettings *cs, PulseAverageSetIndices *pasi, variable mode)
References AccelerateHideTraces, AccelerateModLineSizeTraces, PulseAverageSetIndices::axesNames, PulseAverageSetIndices::channels, COLS, PA_ConstantSettings::deconvolution, PulseAverageSettings::deconvolution, PulseAverageDeconvSettings::enable, PA_ConstantSettings::failedPulses, GetNumberFromWaveNote, GetPAGraphData, GetPAPermanentAverageWave, GetTraceColor, GetTraceNamePrefix, GrepTextWave, PA_ConstantSettings::hideFailedPulses, PulseAverageSettings::hideFailedPulses, IsEmpty, IsNaN, IsNull, PA_ConstantSettings::multipleGraphs, PulseAverageSettings::multipleGraphs, NOTE_INDEX, NOTE_PA_NEW_PULSES_START, NUM_HEADSTAGES, PulseAverageSetIndices::numEntries, PulseAverageSetIndices::ovlTracesAvg, PulseAverageSetIndices::ovlTracesDeconv, PA_AccelerateAppendTraces, PA_AVERAGE_WAVE_PREFIX, PA_AVGERAGE_PLOT_LSIZE, PA_Deconvolution, PA_DECONVOLUTION_PLOT_LSIZE, PA_DECONVOLUTION_WAVE_PREFIX, PA_DISPLAYMODE_TRACES, PA_DrawScaleBars, PA_DrawXZeroLines, PA_GetGraph, PA_GetGraphs, PA_GetTraceCountFromGraphData, PA_LayoutGraphs, PA_PLOT_STEPPING, PA_PROPERTIES_INDEX_HEADSTAGE, PA_PROPERTIES_INDEX_LASTSWEEP, PA_PROPERTIES_INDEX_PULSEHASFAILED, PA_PROPERTIES_INDEX_SWEEP, PA_PROPERTIES_KEY_LAYOUTCHANGE, PA_PROPERTIESWAVES_INDEX_PULSE, PA_USE_WAVE_SCALES, POST_PLOT_ADDED_SWEEPS, POST_PLOT_CONSTANT_SWEEPS, PulseAverageSetIndices::properties, PulseAverageSetIndices::propertiesWaves, PulseAverageSetIndices::pulseAverageDFR, PulseAverageSetIndices::regions, PulseAverageSettings::regionSlider, RemoveAnnotationsFromGraph, RemoveTracesFromGraph, ROWS, PulseAverageSetIndices::setIndicesUnsorted, PA_ConstantSettings::showAverage, PulseAverageSettings::showAverage, PA_ConstantSettings::showIndividualPulses, PulseAverageSettings::showIndividualPulses, PA_ConstantSettings::showTraces, PulseAverageSettings::showTraces, PA_ConstantSettings::singlePulse, PulseAverageSetIndices::startEntry, PA_ConstantSettings::traces.
Referenced by PA_Update.
static variable PA_ClearGraphs(string graphs)
Remove all traces, image and annotations from the graph and clears its trace user data.
References PA_GetTraceCountFromGraphData, RemoveAnnotationsFromGraph, RemoveImagesFromGraph, RemoveTracesFromGraph.
Referenced by PA_PreProcessPulses.
static std::tuple< PA_ConstantSettings > PA_DetermineConstantSettings(PulseAverageSettings *pa, PulseAverageSettings *paOld, variable mode)
Returns a filled structure PA_ConstantSettings which has 1 for all constant entries of the given category.
References PulseAverageSettings::autoTimeAlignment, PulseAverageSettings::deconvolution, PulseAverageSettings::drawXZeroLine, PulseAverageDeconvSettings::enable, PulseAverageSettings::enabled, PulseAverageSettings::endingPulse, EqualValuesOrBothNaN, PulseAverageSettings::failedNumberOfSpikes, PulseAverageSettings::failedPulsesLevel, PulseAverageSettings::fixedPulseLength, PulseAverageSettings::hideFailedPulses, PulseAverageSettings::multipleGraphs, PulseAverageSettings::overridePulseLength, POST_PLOT_CONSTANT_SWEEPS, PulseAverageSettings::pulseSortOrder, PulseAverageDeconvSettings::range, PulseAverageSettings::regionSlider, PulseAverageSettings::searchFailedPulses, PulseAverageSettings::showAverage, PulseAverageSettings::showImages, PulseAverageSettings::showIndividualPulses, PulseAverageSettings::showTraces, PulseAverageDeconvSettings::smth, PulseAverageSettings::startingPulse, PulseAverageDeconvSettings::tau, PulseAverageSettings::yScaleBarLength, PulseAverageSettings::zeroPulses.
Referenced by PA_Update.
static std::tuple< PulseAverageSetIndices, variable > PA_PreProcessPulses(string win, PulseAverageSettings *pa, PA_ConstantSettings *cs, variable mode, WaveOrNull additionalData)
Gather and pre-process the single pulses for display.
This function is display-type agnostic and only does preparational steps. No graphs are created or killed. The work with pulses is done in the following order: Gather pulses Sort pulses (in setIndizes) Reset pulses to backup Failed pulse marking Zeroing Time alignment Averaging pasi structure keeping references to current PA data set needsPlotting dest boolean denoting if there are pulses to plot
References PulseAverageSettings::autoTimeAlignment, DataFolderExistsDFR, DEBUGPRINT, PulseAverageSettings::dfr, PA_ConstantSettings::dontResetWaves, PulseAverageSettings::enabled, PA_ConstantSettings::failedPulses, GetDevicePulseAverageHelperFolder, GetMainWindow, PA_ConstantSettings::images, KillOrMoveToTrash, KillWindows, PA_ApplyPulseSortingOrder, PA_AutomaticTimeAlignment, PA_CalculateAllAverages, PA_ClearGraphs, PA_DISPLAYMODE_ALL, PA_GenerateAllPulseWaves, PA_GetGraphs, PA_InitPASIInParts, PA_MarkFailedPulses, PA_PASIINIT_BASE, PA_PASIINIT_INDICEMETA, PA_ResetWavesIfRequired, PA_ZeroPulses, POST_PLOT_CONSTANT_SWEEPS, PulseAverageSettings::searchFailedPulses, PA_ConstantSettings::singlePulse, PulseAverageSettings::zeroPulses.
Referenced by PA_Update.
static variable PA_CalculateAllAverages(PulseAverageSettings *pa, PulseAverageSetIndices *pasi, variable mode)
References PulseAverageSettings::autoTimeAlignment, CA_AveragingWaveModKey, CA_OPTS_NO_DUPLICATE, CA_StoreEntryIntoCache, CA_TryFetchingEntryFromCache, PulseAverageSetIndices::channels, DEBUGPRINT, IGOR_TYPE_32BIT_FLOAT, PulseAverageSetIndices::indexHelper, MIES_fWaveAverage, PA_ExtractPulseSetFromSetWaves2, PA_ExtractSumsCountsOnly, PA_GETSETWAVES_ALL, PA_GETSETWAVES_NEW, PA_GETSETWAVES_OLD, PA_GetSetWaves_TS, PA_MakeAverageWavePermanent, PA_StoreMaxAndUnitsInWaveNote, PA_TAAdaptAverageWave, POST_PLOT_ADDED_SWEEPS, PulseAverageSetIndices::properties, PulseAverageSetIndices::propertiesWaves, PulseAverageSetIndices::pulseAverageDFR, PulseAverageSetIndices::regions, ROWS, PulseAverageSetIndices::setIndices, WaveRef.
Referenced by PA_PreProcessPulses.
static variable PA_TAAdaptAverageWave(WaveOrNull avg, WaveRefWave set)
References IsInteger, ROWS.
Referenced by PA_CalculateAllAverages.
static variable PA_MakeAverageWavePermanent(dfref dfr, WaveOrNull avg, variable channel, variable region)
References ConvertFreeWaveToPermanent, GetPAPermanentAverageWave, KillOrMoveToTrash, PA_AVERAGE_WAVE_PREFIX, PA_BaseName.
Referenced by PA_CalculateAllAverages.
static wave PA_ExtractPulseSetFromSetWaves2(WaveOrNull setWave2)
Referenced by PA_CalculateAllAverages.
static variable PA_StoreMaxAndUnitsInWaveNote(WaveOrNull w, WaveOrNull unitSource)
Stores the WaveMaximum in the wave note of the given wave and sets the wave unit to the same as from unitSource.
w Wave where the maximum is determined and written to the wave note, the wave unit determiend from unitSource is also set for w unitSource a source wave for wave unit information for w
References ASSERT_TS, NOTE_KEY_WAVE_MAXIMUM, SetNumberInWaveNote.
Referenced by PA_CalculateAllAverages.
static wave PA_ExtractSumsCountsOnly(WaveRefWave w)
Referenced by PA_CalculateAllAverages.
variable PA_UpdateScaleBars(string win, variable resetToUserLength)
Update the scale bars of the passed plot.
win PA trace or image plot resetToUserLength Reset the scale bars to the user upplied values This functions is non-statc as it is called from the operation queue. This is necessary as the window hooks listen to the mouse wheel event, and we want to update only after the mouse wheel triggered the axis range change. And that is only possible with the operation queue.
References DEBUGPRINT, MIES_BSP_PA_MAINPANEL, PA_DISPLAYMODE_IMAGES, PA_DISPLAYMODE_TRACES, PA_DrawScaleBars, PA_GatherSettings, PA_InitPASIInParts, PA_PASIINIT_BASE, PA_PASIINIT_INDICEMETA, PA_USE_AXIS_SCALES, WindowExists.
static variable PA_DrawScaleBars(string win, PulseAverageSettings *pa, PulseAverageSetIndices *pasi, variable displayMode, variable axisMode, variable resetToUserLength=defaultValue)
References PulseAverageSetIndices::axesNames, PulseAverageSetIndices::channels, PulseAverageSettings::deconvolution, PulseAverageDeconvSettings::enable, GetNumberFromWaveNote, GetPAPermanentAverageWave, IsFinite, IsNaN, PulseAverageSettings::multipleGraphs, NOTE_KEY_WAVE_MAXIMUM, PA_DISPLAYMODE_IMAGES, PA_DISPLAYMODE_TRACES, PA_DrawScaleBarsHelper, PA_GetGraph, PA_IsDataOnSubPlot, PulseAverageSetIndices::pulseAverageDFR, PulseAverageSetIndices::regions, ROWS, PulseAverageSetIndices::setWaves2Unsorted, PulseAverageSettings::showAverage, PulseAverageSettings::showImages, PulseAverageSettings::showIndividualPulses, PulseAverageSettings::showTraces, PulseAverageSettings::yScaleBarLength.
Referenced by PA_ShowImage, PA_ShowPulses, PA_UpdateScaleBars.
static std::tuple< variable, variable, variable, variable > PA_GetMinAndMax(WaveRefWave setWaves2)
References GetNumberFromWaveNote, NOTE_KEY_WAVE_MAXIMUM, NOTE_KEY_WAVE_MINIMUM, ROWS.
Referenced by PA_DrawScaleBarsHelper, PA_ShowImage.
static std::tuple< variable, variable > PA_NeedsForcedScaleBar(string win, string userDataName, variable physicalLength, variable axisMinimum, variable axisMaximum, variable userLength=defaultValue, string userLengthName=defaultValue, variable resetToUserLength=defaultValue)
Determine if we need a scale bar label.
Without any optional parameters we always need a label if we have a stored entry userDataName and that differs from physicalLength. With the optional parameters we prioritize userLength if it has changed compared to the stored value userLengthName or if it needs resetting on a new plot. Otherwise we use the same approach as above.
References CheckIfClose, DEBUGPRINT, IsNaN.
Referenced by PA_DrawScaleBarsHelper.
static variable PA_DrawScaleBarsHelper(string win, variable axisMode, variable displayMode, WaveRefWave setWaves2, string vertAxis, string horizAxis, variable ylength, string xUnit, string yUnit, variable activeChanCount, variable activeRegionCount, variable numActive, variable resetToUserLength)
References ASSERT, AXIS_RANGE_INC_AUTOSCALED, CalculateNiceLength, DEBUGPRINT, DrawScaleBar, GetAxisRange, GetMainWindow, PA_DISPLAYMODE_IMAGES, PA_DISPLAYMODE_TRACES, PA_GetMinAndMax, PA_NeedsForcedScaleBar, PA_USE_AXIS_SCALES, PA_USE_WAVE_SCALES, PA_USER_DATA_CALC_XLENGTH, PA_USER_DATA_CALC_YLENGTH, PA_USER_DATA_USER_YLENGTH, PA_USER_DATA_X_START_RELATIVE_PREFIX.
Referenced by PA_DrawScaleBars.
wave PA_SpikePositionsForNonVC(wave wv, variable failedPulsesLevel)
Calculate the number of spikes in the given wave for IC and I=0 data.
References ASSERT_TS, AssertOnAndClearRTError, FINDLEVEL_EDGE_BOTH, FINDLEVEL_MODE_MULTI, FindLevelWrapper, IsFinite, IsInteger, IsOdd, PA_MINIMUM_SPIKE_WIDTH, PA_PEAK_BOX_AVERAGE, ROWS.
Referenced by PA_PulseHasFailed, PSQ_SearchForSpikes.
static variable PA_PulseHasFailed(wave pulseWave, wave noteWave, PulseAverageSettings *s)
References ASSERT_TS, EqualValuesOrBothNaN, PulseAverageSettings::failedNumberOfSpikes, PulseAverageSettings::failedPulsesLevel, GetNumberFromWaveNote, I_CLAMP_MODE, I_EQUAL_ZERO_MODE, IsFinite, IsNaN, NOTE_KEY_CLAMP_MODE, NOTE_KEY_FAILED_PULSE_LEVEL, NOTE_KEY_NUMBER_OF_SPIKES, NOTE_KEY_PULSE_FOUND_SPIKES, NOTE_KEY_PULSE_HAS_FAILED, NOTE_KEY_PULSE_SPIKE_POSITIONS, NOTE_KEY_ZEROED, NumericWaveToList, PA_SpikePositionsForNonVC, ROWS, PulseAverageSettings::searchFailedPulses, SetNumberInWaveNote, SetStringInWaveNote, V_CLAMP_MODE.
Referenced by PA_MarkFailedPulses.
string PA_GeneratePulseWaveName(variable channelType, variable channelNumber, variable region, variable pulseIndex)
Generate the wave name for a single pulse.
References ASSERT, GetNumberFromType, IsInteger, XOP_CHANNEL_NAMES.
Referenced by GetPulseAverageWave, GetPulseAverageWaveNoteWave.
string PA_BaseName(variable channelNumber, variable headStage)
Generate a static base name for objects in the current averaging folder.
Referenced by GetPAPermanentAverageWave, PA_MakeAverageWavePermanent, PA_ShowImage.
static variable PA_ZeroPulses(WaveOrNull setWave2)
Zero single pulses using ZeroWave.
References PA_ZeroWave, ROWS.
Referenced by PA_PreProcessPulses.
static variable PA_ZeroWave(wave wv, wave noteWave)
Zero the wave using differentiation and integration.
Overwrites the input wave Preserves the WaveNote and adds the entry NOTE_KEY_ZEROED 2D waves are zeroed along each row
References GetNumberFromWaveNote, NOTE_KEY_ZEROED, PA_UpdateMinAndMax, SetNumberInWaveNote, ZeroWaveImpl.
Referenced by PA_ZeroPulses.
static wave PA_SmoothDeconv(wave input, PulseAverageDeconvSettings *deconvolution)
References CA_OPTS_NO_DUPLICATE, CA_SmoothDeconv, CA_StoreEntryIntoCache, CA_TryFetchingEntryFromCache, PulseAverageDeconvSettings::range, ROWS, PulseAverageDeconvSettings::smth.
Referenced by PA_Deconvolution.
static wave PA_Deconvolution(wave average, dfref outputDFR, string outputWaveName, PulseAverageDeconvSettings *deconvolution)
References CA_Deconv, CA_OPTS_NO_DUPLICATE, CA_StoreEntryIntoCache, CA_TryFetchingEntryFromCache, PA_SmoothDeconv, ROWS, PulseAverageDeconvSettings::tau.
Referenced by PA_ShowImage, PA_ShowPulses.
variable PA_CheckProc_Common(WMCheckboxAction *cba)
References PA_Update, POST_PLOT_CONSTANT_SWEEPS.
variable PA_SetVarProc_Common(WMSetVariableAction *sva)
References IsNaN, PA_Update, POST_PLOT_CONSTANT_SWEEPS, SetSetVariable.
variable PA_PopMenuProc_ColorScale(WMPopupAction *pa)
References PA_SetColorScale.
variable PA_PopMenuProc_Common(WMPopupAction *pa)
References PA_Update, POST_PLOT_CONSTANT_SWEEPS.
static variable PA_AutomaticTimeAlignment(PulseAverageSetIndices *pasi)
Time alignment for PA single pulses.
embed:rst:leading-asterisk * See :ref:`db_paplot_timealignment` for an explanation of the algorithm. *
References PulseAverageSetIndices::channels, PulseAverageSetIndices::numEntries, PA_GetFeaturePosition, PA_PROPERTIES_INDEX_PULSE, PA_PROPERTIES_INDEX_SWEEP, PA_PROPERTIESWAVES_INDEX_PULSE, PA_PROPERTIESWAVES_INDEX_PULSENOTE, PA_SetFeaturePosition, PulseAverageSetIndices::properties, PulseAverageSetIndices::propertiesWaves, ROWS, PulseAverageSetIndices::setIndices.
Referenced by PA_PreProcessPulses.
static variable PA_GetFeaturePosition(wave wv, wave noteWave)
References GetNumberFromWaveNote, IsFinite, NOTE_KEY_TIMEALIGN_FEATURE_POS, SetNumberInWaveNote.
Referenced by PA_AutomaticTimeAlignment.
static variable PA_SetFeaturePosition(wave wv, wave noteWave, variable featurePos)
References DEBUGPRINT_TS, GetNumberFromWaveNote, IsNaN, NOTE_KEY_TIMEALIGN, NOTE_KEY_TIMEALIGN_TOTAL_OFFSET, ROWS, SetNumberInWaveNote.
Referenced by PA_AutomaticTimeAlignment.
static variable PA_ResetWavesIfRequired(WaveOrNull setWave2, PulseAverageSettings *pa, variable mode)
Reset All pulse and pulse note waves from a set to its original state if they are outdated.
References PulseAverageSettings::autoTimeAlignment, EqualValuesOrBothNaN, PulseAverageSettings::failedNumberOfSpikes, PulseAverageSettings::failedPulsesLevel, GetNumberFromWaveNote, NOTE_KEY_FAILED_PULSE_LEVEL, NOTE_KEY_NUMBER_OF_SPIKES, NOTE_KEY_SEARCH_FAILED_PULSE, NOTE_KEY_TIMEALIGN, NOTE_KEY_ZEROED, ReplaceWaveWithBackup, ROWS, PulseAverageSettings::searchFailedPulses, PulseAverageSettings::zeroPulses.
Referenced by PA_PreProcessPulses.
static variable PA_LayoutGraphs(string win, PulseAverageSettings *pa, PulseAverageSetIndices *pasi, variable displayMode)
References ASSERT, PulseAverageSetIndices::axesNames, PulseAverageSetIndices::channels, EquallySpaceAxisPA, GetTraceColor, GetUniqueEntries, PulseAverageSettings::multipleGraphs, NOTE_INDEX, PA_DISPLAYMODE_IMAGES, PA_DISPLAYMODE_TRACES, PA_GetGraphName, PA_GetSetXAxisUserData, PA_PROPERTIES_INDEX_HEADSTAGE, PA_PROPERTIES_INDEX_PULSE, PA_PROPERTIES_INDEX_SWEEP, PA_X_AXIS_OFFSET, PulseAverageSetIndices::properties, PulseAverageSetIndices::regions, ROWS, PulseAverageSetIndices::setIndices, TextWaveToList.
Referenced by PA_ShowImage, PA_ShowPulses.
static variable PA_GetSetXAxisUserData(string graph, string horizAxis)
References GetNumFromModifyStr, PA_USER_DATA_X_START_RELATIVE_PREFIX, PA_X_AXIS_OFFSET.
Referenced by PA_LayoutGraphs.
static variable PA_AddColorScales(string win, PulseAverageSettings *pa, PulseAverageSetIndices *pasi)
References ASSERT, PulseAverageSetIndices::axesNames, PulseAverageSetIndices::channels, DEBUGPRINT, GetNumberFromWaveNote, GetPulseAverageSetImageWave, PulseAverageSettings::imageColorScale, IsFinite, IsNaN, PulseAverageSettings::multipleGraphs, NOTE_INDEX, NOTE_KEY_IMG_PMAX, NOTE_KEY_IMG_PMIN, PA_AddColorScale, PA_DISPLAYMODE_IMAGES, PA_GetColorScaleGraph, PA_GetGraphName, PA_PROPERTIES_INDEX_HEADSTAGE, PA_ResizeColorScalePanel, PulseAverageSetIndices::properties, PulseAverageSetIndices::pulseAverageDFR, PulseAverageSetIndices::regions, RemoveAnnotationsFromGraph, ROWS, PulseAverageSetIndices::setIndices, PulseAverageSettings::showIndividualPulses, SymmetrizeRangeAroundZero, WindowExists, PulseAverageSettings::zeroPulses.
Referenced by PA_ShowImage.
static variable PA_AddColorScale(string graph, string colorScaleGraph, string name, string text, variable index, variable numSlots, string traceName)
References DistributeElements.
Referenced by PA_AddColorScales.
static variable PA_SerializeSettings(string win, PulseAverageSettings *pa)
Write the PA settings pa to the panel user data and return a JSON id with the settings.
Valid JSON id, caller must release memory.
References PulseAverageSettings::autoTimeAlignment, DataFolderExistsDFR, PulseAverageSettings::deconvolution, PulseAverageSettings::dfr, PulseAverageSettings::drawXZeroLine, PulseAverageDeconvSettings::enable, PulseAverageSettings::enabled, PulseAverageSettings::endingPulse, PulseAverageSettings::failedNumberOfSpikes, PulseAverageSettings::failedPulsesLevel, PulseAverageSettings::fixedPulseLength, PulseAverageSettings::hideFailedPulses, PulseAverageSettings::imageColorScale, PulseAverageSettings::multipleGraphs, PulseAverageSettings::overridePulseLength, PA_SETTINGS_STRUCT_VERSION, PulseAverageSettings::pulseSortOrder, PulseAverageDeconvSettings::range, PulseAverageSettings::regionSlider, PulseAverageSettings::searchFailedPulses, PulseAverageSettings::showAverage, PulseAverageSettings::showImages, PulseAverageSettings::showIndividualPulses, PulseAverageSettings::showTraces, PulseAverageDeconvSettings::smth, PulseAverageSettings::startingPulse, PulseAverageDeconvSettings::tau, PulseAverageSettings::yScaleBarLength, PulseAverageSettings::zeroPulses.
Referenced by PA_Update.
static variable PA_DeserializeSettings(string win, PulseAverageSettings *pa)
Read the PA settings from the panel user data into pa and return a JSON id with the settings.
Valid JSON id, caller must release memory, or NaN on error/incompatible struct
References PulseAverageSettings::autoTimeAlignment, PulseAverageSettings::deconvolution, PulseAverageSettings::dfr, PulseAverageSettings::drawXZeroLine, PulseAverageDeconvSettings::enable, PulseAverageSettings::enabled, PulseAverageSettings::endingPulse, PulseAverageSettings::failedNumberOfSpikes, PulseAverageSettings::failedPulsesLevel, PulseAverageSettings::fixedPulseLength, PulseAverageSettings::hideFailedPulses, PulseAverageSettings::imageColorScale, InitPulseAverageSettings, IsNaN, PulseAverageSettings::multipleGraphs, PulseAverageSettings::overridePulseLength, PA_SETTINGS, PA_SETTINGS_STRUCT_VERSION, PulseAverageSettings::pulseSortOrder, PulseAverageDeconvSettings::range, PulseAverageSettings::regionSlider, PulseAverageSettings::searchFailedPulses, PulseAverageSettings::showAverage, PulseAverageSettings::showImages, PulseAverageSettings::showIndividualPulses, PulseAverageSettings::showTraces, PulseAverageDeconvSettings::smth, PulseAverageSettings::startingPulse, PulseAverageDeconvSettings::tau, PulseAverageSettings::yScaleBarLength, PulseAverageSettings::zeroPulses.
static string PA_ShowImage(string win, PulseAverageSettings *pa, PA_ConstantSettings *cs, PulseAverageSetIndices *pasi, variable mode, WaveOrNull additionalData)
References AddPrefixToEachListItem, AssertOnAndClearRTError, PulseAverageSetIndices::axesNames, PulseAverageSetIndices::channels, COLS, DEBUGPRINT, PulseAverageSettings::deconvolution, PulseAverageDeconvSettings::enable, EnsureLargeEnoughWave, GetNumberFromWaveNote, GetPAGraphData, GetPAPermanentAverageWave, GetPulseAverageSetImageWave, PulseAverageSetIndices::imageAvgDataPresent, PulseAverageSetIndices::imageDeconvDataPresent, PA_ConstantSettings::images, MAX_DIMENSION_COUNT, PulseAverageSettings::multipleGraphs, NOTE_INDEX, NOTE_KEY_IMG_PMAX, NOTE_KEY_IMG_PMIN, PulseAverageSetIndices::numEntries, PA_AddColorScales, PA_BaseName, PA_Deconvolution, PA_DECONVOLUTION_WAVE_PREFIX, PA_DISPLAYMODE_IMAGES, PA_DrawScaleBars, PA_DrawXZeroLines, PA_GetGraph, PA_GetGraphs, PA_GetMinAndMax, PA_GetSetWaves, PA_GetSweepsAndExperimentsFromIndices, PA_GetTraceCountFromGraphData, PA_HighligthFailedPulsesInImage, PA_IMAGE_SPECIAL_ENTRIES_RANGE, PA_LayoutGraphs, PA_PROPERTIES_INDEX_SWEEP, PA_PROPERTIES_KEY_LAYOUTCHANGE, PA_PULSE_SORTING_ORDER_SWEEP, PA_USE_WAVE_SCALES, POST_PLOT_ADDED_SWEEPS, PulseAverageSetIndices::properties, PulseAverageSetIndices::pulseAverageDFR, PulseAverageSetIndices::pulseAverageHelperDFR, PulseAverageSettings::pulseSortOrder, PulseAverageSetIndices::regions, ROWS, ScaleToIndexWrapper, PulseAverageSetIndices::setIndices, SetNumberInWaveNote, PulseAverageSetIndices::setWaves2Unsorted, PulseAverageSettings::showAverage, PulseAverageSettings::showImages, PulseAverageSettings::showIndividualPulses, WaveRef.
Referenced by PA_Update.
static variable PA_HighligthFailedPulsesInImage(string graph, PulseAverageSettings *pa, string vertAxis, string horizAxis, wave img, wave properties, wave setIndizes, variable numPulses)
References PulseAverageSettings::hideFailedPulses, PA_IMAGE_FAILEDMARKERSTART, PA_PROPERTIES_INDEX_PULSEHASFAILED, ROWS, PulseAverageSettings::searchFailedPulses, PulseAverageSettings::showIndividualPulses.
Referenced by PA_ShowImage.
static variable PA_SetColorScale(string win, string colScale)
Apply the given color scale to all PA plot images.
References PA_DISPLAYMODE_IMAGES, PA_GetColorScaleGraph, PA_GetGraphs.
Referenced by PA_PopMenuProc_ColorScale.
static variable PA_ResizeColorScalePanel(string imageGraph)
Adjust the size of the panel with the color scale graph.
References PA_COLORSCALE_PANEL_WIDTH, PA_GetColorScaleGraph, PA_GetColorScalePanel, WindowExists.
Referenced by PA_AddColorScales, PA_ImageWindowHook.
variable PA_TraceWindowHook(WMWinHookStruct *s)
variable PA_ImageWindowHook(WMWinHookStruct *s)
References PA_ResizeColorScalePanel.
static variable PA_IsDataOnSubPlot(PulseAverageSettings *pa, PulseAverageSetIndices *pasi, variable xLoc, variable yLoc, variable displayMode)
Returns 1 if data is displayed on the given layout grid location. When data is displayed in PA_ShowPulses and PA_ShowImage then in PulseAverageSetIndices this is tagged.
pa Pulse Average Setting information pasi Pulse Average Set Indices information xLoc x location on display grid, typically the channel index yLoc y location on display grid, typically the region index displayMode Return data for either trace plot (PA_DISPLAYMODE_TRACES) or image plot (PA_DISPLAYMODE_IMAGES) 1 if data is displayed on this grid location, 0 if no data is displayed
References ASSERT, PulseAverageSetIndices::imageAvgDataPresent, PulseAverageSetIndices::imageDeconvDataPresent, PulseAverageSetIndices::numEntries, PulseAverageSetIndices::ovlTracesAvg, PulseAverageSetIndices::ovlTracesDeconv, PA_DISPLAYMODE_IMAGES, PA_DISPLAYMODE_TRACES, PulseAverageSettings::showIndividualPulses.
Referenced by PA_DrawScaleBars, PA_DrawXZeroLines.
static variable PA_DrawXZeroLines(string win, PulseAverageSettings *pa, PulseAverageSetIndices *pasi, variable displayMode)
References PulseAverageSetIndices::axesNames, PulseAverageSetIndices::channels, PulseAverageSettings::drawXZeroLine, PulseAverageSettings::multipleGraphs, PA_GetGraph, PA_IsDataOnSubPlot, PulseAverageSetIndices::regions, ROWS.
Referenced by PA_ShowImage, PA_ShowPulses.
static variable PA_AccelerateAppendTraces(variable jsonID, WaveRefWave plotWaves)
Runs through all graph groups in the json and appends them to the graph.
References PA_AccelerateAppendTracesImpl, ROWS.
Referenced by PA_ShowPulses.
static variable PA_AccelerateAppendTracesImpl(string w, string v, string h, variable r, variable g, variable b, variable a, variable s, wave y, WaveText t, WaveRefWave d)
Appends a group of traces to a graph, properties v to s must be constant for the group.
w name of graph window v name of vertical axis h name of horizontal axis r red color component g green color component b blue color component a alpha component s step width of graph display y 1D wave with indices into wave d for the actual plot data t 1D wave with trace names, same size as y d wave reference wave with plot data
References ASSERT, ROWS.
Referenced by PA_AccelerateAppendTraces.