MIES_Blowout.ipf
const double BWO_MAX_RESISTANCE
Referenced by BWO_CheckAndClearPipettes.
const double BWO_INIT_PRESSURE
Referenced by BWO_CheckAndClearPipettes, BWO_InitParaPipetteClear.
const double BWO_PRESSURE_INCREMENT
Referenced by BWO_CheckAndClearPipettes.
const double TWO_SECONDS
Referenced by BWO_CheckAndClearPipettes.
const double FIFTEEN_SECONDS
Referenced by BWO_CheckAndClearPipettes.
variable BWO_SelectDevice()
Initiates blowout protocol on single locked device.
References BWO_Go, GetListOfLockedDevices.
variable BWO_Go(string device)
Executes blowout protocol.
References BWO_AcquireSweep, BWO_AllMCCCtrlsOFF, BWO_CheckAndClearPipettes, BWO_CheckGlobalSettings, BWO_ConfigureTP, BWO_InitParaPipetteClear, BWO_SetMIESSettings.
Referenced by BWO_SelectDevice.
static variable BWO_CheckGlobalSettings(string device)
Checks that MIES is correctly configured for automated blowout protocol.
one if settings are valid, zero otherwise
References AI_SelectMultiClamp, AMPLIFIER_CONNECTION_SUCCESS, CHANNEL_TYPE_DAC, COLS, DAG_GetNumericalValue, DAQ_NOT_RUNNING, NUM_HEADSTAGES, P_GetPressureDataWaveRef, PRESSURE_METHOD_ATM, ST_GetStimsetList.
Referenced by BWO_Go.
static variable BWO_ConfigureTP(string device)
Initates test pulse.
References PGC_SetAndActivateControl, TP_CheckIfTestpulseIsRunning.
Referenced by BWO_Go.
static variable BWO_SetMIESSettings(string device)
Configures data acquisition settings for blowout.
References CHANNEL_CONTROL_WAVE, CHANNEL_INDEX_ALL, CHANNEL_INDEX_ALL_I_CLAMP, CHANNEL_TYPE_DAC, CHECKBOX_UNSELECTED, GetPanelControl, PGC_SetAndActivateControl.
Referenced by BWO_Go.
static variable BWO_InitParaPipetteClear(string device)
Applies a pressure pulse to all headstages with valid pressure settings.
References BWO_INIT_PRESSURE, CHECKBOX_SELECTED, CHECKBOX_UNSELECTED, PGC_SetAndActivateControl, TPM_BkrdTPFuncMD, BackgroundStruct::wmbs.
Referenced by BWO_Go.
static variable BWO_CheckAndClearPipettes(string device)
Attempts to clear pipettes that have a resistance larger than MAX_RESISTANCE.
References BWO_INIT_PRESSURE, BWO_MAX_RESISTANCE, BWO_PRESSURE_INCREMENT, FIFTEEN_SECONDS, GetTPResults, MAX_REGULATOR_PRESSURE, NUM_HEADSTAGES, P_GetPressureDataWaveRef, P_ValidatePressureSetHeadstage, PGC_SetAndActivateControl, TPM_BkrdTPFuncMD, TWO_SECONDS, BackgroundStruct::wmbs.
Referenced by BWO_Go.
static variable BWO_AllMCCCtrlsOFF(string device)
Turns OFF all relevant MCC amplifier controls in I- and V-clamp modes.
References BWO_DisableMCCIClampCtrls, BWO_DisableMCCVClampCtrls, BWO_SetClampModeAll, CHECKBOX_SELECTED, CHECKBOX_UNSELECTED, I_CLAMP_MODE, PGC_SetAndActivateControl, V_CLAMP_MODE.
Referenced by BWO_Go.
static variable BWO_SetClampModeAll(string device, variable mode)
Wrapper function for setting the clamp mode on all headstages (T̶h̶o̶m̶a̶s̶ ̶p̶r̶o̶b̶a̶b̶l̶y̶ ̶w̶o̶n̶'̶t̶ ̶l̶i̶k̶e̶ ̶i̶t̶ He liked it!! :/ ).
References ASSERT, CHECKBOX_SELECTED, I_CLAMP_MODE, I_EQUAL_ZERO_MODE, PGC_SetAndActivateControl, V_CLAMP_MODE.
Referenced by BWO_AllMCCCtrlsOFF.
static variable BWO_DisableMCCIClampCtrls(string device)
Turns OFF I-clamp controls.
References CHECKBOX_UNSELECTED, PGC_SetAndActivateControl.
Referenced by BWO_AllMCCCtrlsOFF.
static variable BWO_DisableMCCVClampCtrls(string device)
Turns OFF V-clamp controls.
References CHECKBOX_UNSELECTED, PGC_SetAndActivateControl.
Referenced by BWO_AllMCCCtrlsOFF.
static variable BWO_AcquireSweep(string device)
Acquires blowout sweep.
References CHECKBOX_SELECTED, PGC_SetAndActivateControl.
Referenced by BWO_Go.