MIES_StimsetAPI.ipf
string ST_GetStimsetList(variable channelType=defaultValue, string searchString=defaultValue, string *WBstimSetList=defaultValue, string *thirdPartyStimSetList=defaultValue)
Return a sorted list of all DA/TTL stim set waves.
channelType [optional, defaults to all] CHANNEL_TYPE_DAC or CHANNEL_TYPE_TTL searchString [optional, defaults to "*"] search string in wildcard syntax WBstimSetList [optional] returns the list of stim sets built with the wavebuilder thirdPartyStimSetList [optional] returns the list of third party stim sets not built with the wavebuilder
References CHANNEL_TYPE_DAC, CHANNEL_TYPE_TTL, GetListDifference, GetListOfObjects, GetSetFolder, GetSetParamFolder, MATCH_WILDCARD, RemovePrefixFromListItem, ROWS, STIMSET_TP_WHILE_DAQ.
Referenced by BWO_CheckGlobalSettings, DAP_SetVarProc_Channel_Search, DAP_UpdateDaEphysStimulusSetPopups, IH_KillStimSets, NWB_ExportAllStimsets, NWB_PrepareExport, StimParamGUI, WB_UpdateEpochCombineList, WBP_ReturnListSavedSets.
string ST_CreateStimSet(string baseName, variable stimulusType, variable setNumber=defaultValue, variable saveAsBuiltin=defaultValue)
Create a new empty stimset.
baseName user choosable part of the stimset name stimulusType one of CHANNEL_TYPE_DAC or CHANNEL_TYPE_TTL setNumber [optional, defaults to 0] stimset number, allows for convenient alphabetic increasing names used in indexing saveAsBuiltin [optional, defaults to false] allows to create builtin stimsets when enabled
References ASSERT, GetSegmentTypeWaveAsFree, GetWaveBuilderWaveParamAsFree, GetWaveBuilderWaveTextParamAsFree, IsInteger, WB_SaveStimSet.
variable ST_RemoveStimSet(string setName)
Remove the given stimulus set and update all relevant GUIs.
References DAP_DeleteStimulusSet, GetListOfLockedDevices, IsEmpty.
Referenced by WB_SaveStimSet, WBP_ButtonProc_DeleteSet.
wave ST_GetStimsetParameters(string setName, variable epochType=defaultValue)
Returns the available stimsets parameters.
Return the epoch-independent parameters when epochType is not present.
References ControlWindowToFront.
variable ST_GetStimsetParameterAsVariable(string setName, string entry, variable epochIndex=defaultValue)
Return the given stimset numeric parameter.
setName name of the stimset entry name of the parameter, can be global or epoch epochIndex [optional, when not given this sets global parameters] epoch index (0-based)
References IsNumericWave.
Referenced by PSQ_PB_CreateTestpulseEpochs, PSQ_PB_GetPrePulseBaselineDuration.
string ST_GetStimsetParameterAsString(string setName, string entry, variable epochIndex=defaultValue)
Return the given stimset string parameter.
setName name of the stimset entry name of the parameter, can be global or epoch epochIndex [optional, when not given this sets global parameters] epoch index (0-based)
References IsEmpty, IsTextWave.
variable ST_SetStimsetParameter(string setName, string entry, variable epochIndex=defaultValue, variable var=defaultValue, string str=defaultValue)
Set the given stimset parameter.
If you use this function in analysis functions be sure to use an event which happens before the stimset is read, for example PRE_DAQ_EVENT, PRE_SET_EVENT or PRE_SWEEP_CONFIG_EVENT. The last one is always called for each sweep before it is configured. setName name of the stimset entry name of the parameter, can be global or epoch epochIndex [optional, when not given this sets global parameters] epoch index (0-based) var [optional, one of var/str must be present] numeric parameter to set str [optional, one of var/str must be present] string parameter to set 0 on success, 1 on error
References ASSERT, ControlWindowToFront, GetStimSetType, IsEmpty, IsNaN, IsNumericWave, IsTextWave, WB_SetAnalysisFunctionGeneric.