MIES_Epochs.ipf
const string EPOCH_SHORTNAME_KEY
Referenced by EP_AddEpoch, EP_GetShortName.
const string EPOCH_TYPE_KEY
Referenced by EP_AdaptEpochInfo, EP_AddEpochsFromOodDAQRegions, EP_AddEpochsFromStimSetNote, EP_AddEpochsFromTP, EP_CollectEpochInfo.
const string EPOCH_SUBTYPE_KEY
Referenced by EP_AddEpochsFromStimSetNote, EP_AddEpochsFromTP.
const string EPOCH_AMPLITUDE_KEY
Referenced by EP_AddEpochsFromStimSetNote, EP_AddEpochsFromTP.
const string EPOCH_PULSE_KEY
Referenced by EP_AddEpochsFromStimSetNote, EP_AddEpochsFromTP.
const string EPOCHNAME_SEP
Referenced by EP_AdaptEpochInfo, EP_AddEpochsFromOodDAQRegions, EP_AddEpochsFromStimSetNote, EP_AddEpochsFromTP, EP_CollectEpochInfo.
const string STIMSETKEYNAME_SEP
Referenced by EP_AdaptEpochInfo, EP_AddEpochsFromOodDAQRegions, EP_AddEpochsFromStimSetNote, EP_AddEpochsFromTP, EP_CollectEpochInfo.
const string SHORTNAMEKEY_SEP
Referenced by EP_AddEpoch, EP_GetShortName.
const string EPOCH_SN_BL_ONSETDELAYUSER
Referenced by EP_CollectEpochInfo.
const string EPOCH_SN_BL_DDAQ
Referenced by EP_CollectEpochInfo.
const string EPOCH_SN_BL_TERMINATIONDELAY
Referenced by EP_CollectEpochInfo.
const string EPOCH_SN_BL_DDAQOPT
Referenced by EP_CollectEpochInfo.
const string EPOCH_SN_BL_DDAQTRAIL
Referenced by EP_CollectEpochInfo.
const string EPOCH_SN_TP
Referenced by EP_AddEpochsFromTP.
const string EPOCH_SN_TP_PULSE
Referenced by EP_AddEpochsFromTP.
const string EPOCH_SN_TP_BLFRONT
Referenced by EP_AddEpochsFromTP.
const string EPOCH_SN_TP_BLBACK
Referenced by EP_AddEpochsFromTP.
const string EPOCH_SN_OODAQ
Referenced by EP_AddEpochsFromOodDAQRegions.
const string EPOCH_SN_STIMSET
Referenced by EP_AddEpochsFromStimSetNote.
const string EPOCH_SN_STIMSETBLTRAIL
Referenced by EP_AddEpochsFromStimSetNote.
const string EPOCH_SN_EPOCH
Referenced by EP_AddEpochsFromStimSetNote.
const string EPOCH_SN_PULSETRAIN
Referenced by EP_AddEpochsFromStimSetNote.
const string EPOCH_SN_PULSETRAIN_FULLPULSE
Referenced by EP_AddEpochsFromStimSetNote.
const string EPOCH_SN_PULSETRAIN_PULSEAMP
Referenced by EP_AddEpochsFromStimSetNote.
const string EPOCH_SN_PULSETRAIN_PULSEBASE
Referenced by EP_AddEpochsFromStimSetNote.
const string EPOCH_SN_PULSETRAIN_PULSEBASETRAIL
Referenced by EP_AddEpochsFromStimSetNote.
const string EPOCH_SN_PULSETRAINBASETRAIL
Referenced by EP_AddEpochsFromStimSetNote.
const string EPOCH_SN_UNACQUIRED
Referenced by EP_AdaptEpochInfo.
variable EP_ClearEpochs(string device)
Clear the list of epochs.
References GetEpochsWave.
Referenced by DC_Configure.
variable EP_CollectEpochInfo(string device, DataConfigurationResult *s)
Fill the epoch wave with epochs before DAQ/TP.
device device s struct holding all input
References DataConfigurationResult::DACAmp, DataConfigurationResult::DACList, DATA_ACQUISITION_MODE, DataConfigurationResult::dataAcqOrTP, DataConfigurationResult::distributedDAQ, DataConfigurationResult::distributedDAQOptOv, EP_AddEpoch, EP_AddEpochsFromOodDAQRegions, EP_AddEpochsFromStimSetNote, EP_AddEpochsFromTP, EPOCH_BASELINE_REGION_KEY, EPOCH_SN_BL_DDAQ, EPOCH_SN_BL_DDAQOPT, EPOCH_SN_BL_DDAQTRAIL, EPOCH_SN_BL_ONSETDELAYUSER, EPOCH_SN_BL_TERMINATIONDELAY, EPOCH_TYPE_KEY, EPOCHNAME_SEP, GetDAQConfigWave, GetStopCollectionPoint, DataConfigurationResult::globalTPInsert, DataConfigurationResult::headstageDAC, DataConfigurationResult::insertStart, DataConfigurationResult::numDACEntries, DataConfigurationResult::offsets, DataConfigurationResult::onsetDelay, DataConfigurationResult::onsetDelayAuto, DataConfigurationResult::onsetDelayUser, DataConfigurationResult::regions, ROVar, DataConfigurationResult::samplingInterval, DataConfigurationResult::setColumn, DataConfigurationResult::setLength, DataConfigurationResult::setName, DataConfigurationResult::stimSet, STIMSET_TP_WHILE_DAQ, STIMSETKEYNAME_SEP, DataConfigurationResult::terminationDelay, DataConfigurationResult::testPulseLength, WB_StimsetIsFromThirdParty.
Referenced by DC_PlaceDataInDAQDataWave.
static variable EP_AddEpochsFromTP(string device, variable channel, variable baselinefrac, variable testPulseLength, variable offset, variable amplitude)
Adds four epochs for a test pulse and three sub epochs for test pulse components.
device title of device panel channel number of DA channel baselinefrac base line fraction of testpulse testPulseLength test pulse length in micro seconds offset start time of test pulse in micro seconds amplitude amplitude of the TP in the DA wave without gain
References EP_AddEpoch, EPOCH_AMPLITUDE_KEY, EPOCH_BASELINE_REGION_KEY, EPOCH_PULSE_KEY, EPOCH_SN_TP, EPOCH_SN_TP_BLBACK, EPOCH_SN_TP_BLFRONT, EPOCH_SN_TP_PULSE, EPOCH_SUBTYPE_KEY, EPOCH_TYPE_KEY, EPOCHNAME_SEP, STIMSETKEYNAME_SEP.
Referenced by EP_CollectEpochInfo.
static variable EP_AddEpochsFromOodDAQRegions(string device, variable channel, string oodDAQRegions, variable stimsetBegin, variable stimsetEnd)
Adds epochs for oodDAQ regions.
device title of device panel channel number of DA channel oodDAQRegions string containing list of oodDAQ regions as d-d;... stimsetBegin offset time in micro seconds where stim set begins stimsetEnd offset time in micro seconds where stim set ends
References EP_AddEpoch, EPOCH_OODDAQ_REGION_KEY, EPOCH_SN_OODAQ, EPOCH_TYPE_KEY, EPOCHNAME_SEP, ROWS, STIMSETKEYNAME_SEP.
Referenced by EP_CollectEpochInfo.
static variable EP_AddEpochsFromStimSetNote(string device, variable channel, wave stimset, variable stimsetBegin, variable setLength, variable sweep, variable scale)
Adds epochs for a stimset and sub epochs for stimset components currently adds also sub sub epochs for pulse train components.
device title of device panel channel number of DA channel stimset stimset wave stimsetBegin offset time in micro seconds where stim set begins setLength length of stimset in micro seconds sweep number of sweep scale scale factor between the stimsets internal amplitude to the DA wave without gain
References ASSERT, DEBUGPRINT, EP_AddEpoch, EPOCH_AMPLITUDE_KEY, EPOCH_BASELINE_REGION_KEY, EPOCH_ENTRY, EPOCH_PULSE_KEY, EPOCH_SN_EPOCH, EPOCH_SN_PULSETRAIN, EPOCH_SN_PULSETRAIN_FULLPULSE, EPOCH_SN_PULSETRAIN_PULSEAMP, EPOCH_SN_PULSETRAIN_PULSEBASE, EPOCH_SN_PULSETRAIN_PULSEBASETRAIL, EPOCH_SN_PULSETRAINBASETRAIL, EPOCH_SN_STIMSET, EPOCH_SN_STIMSETBLTRAIL, EPOCH_SUBTYPE_KEY, EPOCH_TYPE_KEY, EPOCH_TYPE_PULSE_TRAIN, EPOCHNAME_SEP, isEmpty, IsEmpty, IsFinite, ROWS, STIMSET_ENTRY, STIMSETKEYNAME_SEP, WB_GetPulsesFromPTSweepEpoch, WB_GetWaveNoteEntry, WB_GetWaveNoteEntryAsNumber, WB_ToEpochType.
Referenced by EP_CollectEpochInfo.
static variable EP_SortEpochs(string device)
Sorts all epochs per channel in EpochsWave.
Removes epochs marked for removal, those with NaN as StartTime and EndTime, as well. Sorting: Ascending starting time Descending ending time Ascending tree level device title of device panel
References ASSERT, EP_GetEpochCount, EPOCH_COL_ENDTIME, EPOCH_COL_STARTTIME, EPOCH_COL_TREELEVEL, EPOCHTIME_PRECISION, GetEpochsWave, LAYERS, num2strHighPrec, RemoveTextWaveEntry1D, ROWS.
Referenced by EP_WriteEpochInfoIntoSweepSettings.
static variable EP_GetEpochCount(string device, variable channel)
Returns the number of epoch in the epochsWave for the given channel.
device title of device panel channel number of DA channel number of epochs for channel
References GetEpochsWave, ROWS.
Referenced by EP_AdaptEpochInfo, EP_AddEpoch, EP_AddUserEpoch, EP_SortEpochs.
variable EP_AddUserEpoch(string device, variable channelType, variable channelNumber, variable epBegin, variable epEnd, string tags, string shortName=defaultValue)
Add user epochs.
Allows to add user epochs for not yet finished sweeps. The tree level is fixed to EPOCH_USER_LEVEL to not collide with stock entries. device device channelType channel type, currently only XOP_CHANNEL_TYPE_DAC is supported channelNumber channel number epBegin start time of the epoch in seconds epEnd end time of the epoch in seconds tags tags for the epoch shortName [optional, defaults to auto-generated] user defined short name for the epoch, will be prefixed with EPOCH_SHORTNAME_USER_PREFIX
References ASSERT, EP_AddEpoch, EP_GetEpochCount, EPOCH_SHORTNAME_USER_PREFIX, EPOCH_USER_LEVEL, XOP_CHANNEL_TYPE_DAC.
Referenced by PSQ_EvaluateBaselineProperties, PSQ_PB_CreateTestpulseEpochs, PSQ_Ramp_AddEpoch.
static variable EP_AddEpoch(string device, variable channel, variable epBegin, variable epEnd, string epTags, string epShortName, variable level=defaultValue, variable lowerlimit=defaultValue, variable upperlimit=defaultValue)
Adds a epoch to the epochsWave.
device title of device panel channel number of DA channel epBegin start time of the epoch in micro seconds epEnd end time of the epoch in micro seconds epTags tags of the epoch epShortName short name of the epoch, should be unique level level of epoch lowerlimit [optional, default = -Inf] epBegin is limited between lowerlimit and Inf, epEnd must be > this limit upperlimit [optional, default = Inf] epEnd is limited between -Inf and upperlimit, epBegin must be < this limit
References ASSERT, EnsureLargeEnoughWave, EP_GetEpochCount, EPOCH_SHORTNAME_KEY, EPOCH_TAG_INVALID_CHARS_REGEXP, EPOCHTIME_PRECISION, GetEpochsWave, isEmpty, isNull, num2strHighPrec, NUM_DA_TTL_CHANNELS, ROWS, SHORTNAMEKEY_SEP.
Referenced by EP_AdaptEpochInfo, EP_AddEpochsFromOodDAQRegions, EP_AddEpochsFromStimSetNote, EP_AddEpochsFromTP, EP_AddUserEpoch, EP_CollectEpochInfo.
variable EP_WriteEpochInfoIntoSweepSettings(string device, wave sweepWave, wave configWave)
Write the epoch info into the sweep settings wave.
device device sweepWave sweep wave configWave config wave
References AFH_GetHeadstageFromDAC, ASSERT, DC_DocumentChannelProperty, EP_AdaptEpochInfo, EP_EpochWaveToStr, EP_SortEpochs, EPOCHS_ENTRY_KEY, GetDACListFromConfig, GetEpochsWave, INDEP_HEADSTAGE, IsNaN, ROWS, SWEEP_EPOCH_VERSION, XOP_CHANNEL_TYPE_DAC.
Referenced by SWS_SaveAcquiredData.
string EP_EpochWaveToStr(wave epochsWave, variable channel)
Convert the epochs wave layer given by channel to a string suitable for storing the labnotebook.
epochsWave wave with epoch information channel DA channel
References EPOCH_LIST_COL_SEP, EPOCH_LIST_ROW_SEP, TextWaveToList.
Referenced by EP_WriteEpochInfoIntoSweepSettings.
wave EP_EpochStrToWave(string epochStr)
Converts a string containing epoch information in the format that is stored in the Labnotebook to a 2D epoch wave.
GetEpochsWave epochStr string with epoch information in the format as stored in the labnotebook 2D text wave with epoch information, use EPOCH_COL_ constants for column access
References ASSERT_TS, EPOCH_LIST_COL_SEP, EPOCH_LIST_ROW_SEP, IsEmpty, ListToTextWaveMD.
Referenced by EP_GetEpochs, NWB_FetchEpochs, PA_RetrievePulseInfosFromEpochs.
string EP_GetShortName(string name)
Returns the ShortName from a epoch name string, empty string if no ShortName is present.
References EPOCH_SHORTNAME_KEY, SHORTNAMEKEY_SEP.
Referenced by EP_GetEpochs.
static variable EP_AdaptEpochInfo(string device, wave configWave, variable acquiredTime, variable plannedTime)
Adapt epoch information.
Adjust epoch end time to the acquired time Blanks out which are then too small or lie outside the acquired region Add an unacquired epoch device device configWave DAQ config wave acquiredTime Last acquired time point [s] plannedTime Last time point in the sweep [s]
References ASSERT, DAQ_CHANNEL_TYPE_DAQ, EP_AddEpoch, EP_GetEpochCount, EPOCH_SN_UNACQUIRED, EPOCH_TYPE_KEY, EPOCHNAME_SEP, EPOCHTIME_PRECISION, GetEpochsWave, num2strHighPrec, ROWS, STIMSETKEYNAME_SEP, XOP_CHANNEL_TYPE_DAC.
Referenced by EP_WriteEpochInfoIntoSweepSettings.
wave EP_GetEpochs(wave numericalValues, wave textualValues, variable sweepNo, variable channelType, variable channelNumber, string shortname, variable treelevel=defaultValue)
Get epochs from the LBN filtered by given parameters.
numericalValues Numerical values from the labnotebook textualValues Textual values from the labnotebook sweepNo Number of sweep channelType type of channel XopChannelConstants channelNumber number of channel shortname short name filter, can be a regular expression which is matched caseless treelevel [optional: default = not set] tree level of epochs, if not set then treelevel is ignored Text wave with epoch information, only rows fitting the input parameters are returned. Can also be a null wave.
References ASSERT, COLS, DATA_ACQUISITION_MODE, EP_EpochStrToWave, EP_GetShortName, EPOCH_COL_STARTTIME, EPOCH_COL_TAGS, EPOCH_COL_TREELEVEL, EPOCHS_ENTRY_KEY, FindIndizes, GetLastSettingChannel, GetSetIntersection, IsNaN, ROWS, XOP_CHANNEL_TYPE_DAC.