MIES_MassExperimentProcessing.ipf
const string INPUT_FOLDER
Referenced by StartMultiExperimentProcessWrapper.
const string OUTPUT_FOLDER
Referenced by StartMultiExperimentProcessWrapper.
const string kPackageName
Referenced by LoadPackagePrefs, SavePackagePrefs.
const string kPreferencesFileName
Referenced by LoadPackagePrefs, SavePackagePrefs.
const double kPrefsRecordID
Referenced by LoadPackagePrefs, SavePackagePrefs.
const double kPrefsVersionNumber
Referenced by LoadPackagePrefs.
static variable LoadPackagePrefs(MultiExperimentProcessPrefs *prefs)
References kPackageName, kPreferencesFileName, kPrefsRecordID, kPrefsVersionNumber, MultiExperimentProcessPrefs::processRunning, SavePackagePrefs, MultiExperimentProcessPrefs::settingsFile, MultiExperimentProcessPrefs::version.
Referenced by AfterFileOpenHook, StartMultiExperimentProcessWrapper.
static variable SavePackagePrefs(MultiExperimentProcessPrefs *prefs)
References kPackageName, kPreferencesFileName, kPrefsRecordID.
Referenced by AfterFileOpenHook, LoadPackagePrefs, StartMultiExperimentProcessWrapper.
static variable ProcessCurrentExperiment(MultiExperimentProcessPrefs *prefs)
References ClearRTError, GetExperimentName, GetJSON, IsAppropriateExperiment, PerformMiesTasks, StoreJSON.
Referenced by AfterFileOpenHook.
static variable PerformMiesTasks(string outputFilePath)
References ASSERT, ClearRTError, CreateFolderOnDisk, FolderExists, GetFolder, GetFreeMemory, NWB_ExportAllData.
Referenced by ProcessCurrentExperiment.
static variable IsAppropriateExperiment()
References GetAllDevicesWithContent.
Referenced by ProcessCurrentExperiment.
static string FindNextExperiment(MultiExperimentProcessPrefs *prefs)
References GetJSON, ROWS.
Referenced by AfterFileOpenHook, StartMultiExperimentProcessWrapper.
static variable GetJSON(MultiExperimentProcessPrefs *prefs)
References LoadTextFile, MultiExperimentProcessPrefs::settingsFile.
Referenced by FindNextExperiment, ProcessCurrentExperiment.
static variable StoreJSON(MultiExperimentProcessPrefs *prefs, variable jsonID)
References ASSERT, SaveTextFile, MultiExperimentProcessPrefs::settingsFile.
Referenced by ProcessCurrentExperiment, StartMultiExperimentProcessWrapper.
static variable PostLoadNextExperiment(string nextExperimentFullPath)
References ASSERT, FileExists.
Referenced by AfterFileOpenHook, StartMultiExperimentProcessWrapper.
static variable AfterFileOpenHook(variable refNum, string file, string pathName, string type, string creator, variable kind)
References FindNextExperiment, LoadPackagePrefs, PostLoadNextExperiment, ProcessCurrentExperiment, SavePackagePrefs.
variable StartMultiExperimentProcess()
variable StartMultiExperimentProcessWrapper()
References ASSERT, FindNextExperiment, GetAllFilesRecursivelyFromPath, INPUT_FOLDER, LoadPackagePrefs, OUTPUT_FOLDER, PostLoadNextExperiment, ROWS, SavePackagePrefs, StoreJSON.