MIES_AnalysisFunctions_MultiPatchSeq.ipf
const double MSQ_BL_PRE_PULSE
const double MSQ_BL_POST_PULSE
const double MSQ_RMS_SHORT_TEST
const double MSQ_RMS_LONG_TEST
const double MSQ_TARGETV_TEST
static variable MSQ_GetPulseSettingsForType(variable type, MSQ_PulseSettings *s)
Fills s according to the analysis function type.
References ASSERT, DEBUGPRINT, MSQ_PulseSettings::postPulseChunkLength, MSQ_PulseSettings::prePulseChunkLength, MSQ_PulseSettings::pulseDuration.
static wave MSQ_GetPulseDurations(string device, variable type, variable sweepNo, variable totalOnsetDelay, variable headstage, variable useSCI=defaultValue, variable forceRecalculation=defaultValue)
Return the pulse durations from the labnotebook or calculate them before if required. For convenience unused headstages will have 0 instead of NaN in the returned wave.
References CreateAnaFuncLBNKey, ED_AddEntryToLabnotebook, GetLastSetting, GetLastSettingSCI, GetLBNumericalValues, IsNaN, MSQ_DeterminePulseDuration, MSQ_FMT_LBN_PULSE_DUR, UNKNOWN_MODE.
Referenced by MSQ_FastRheoEst.
static wave MSQ_DeterminePulseDuration(string device, variable sweepNo, variable totalOnsetDelay)
Determine the pulse duration on each headstage.
Returns the labnotebook wave as well.
References AFH_ExtractOneDimDataFromSweep, ASSERT, CHANNEL_TYPE_HEADSTAGE, DAG_GetChannelState, DATA_ACQUISITION_MODE, GetConfigWave, GetDAQConfigWave, GetDAQDataWave, GetMachineEpsilon, GetSweepWave, LABNOTEBOOK_LAYER_COUNT, NUM_HEADSTAGES, ROWS, XOP_CHANNEL_TYPE_DAC.
Referenced by MSQ_GetPulseDurations.
static variable MSQ_CalculateAvg(wave wv, variable column, variable startTime, variable rangeTime)
References ASSERT, IsFinite, ROWS.
static variable MSQ_CalculateRMS(wave wv, variable column, variable startTime, variable rangeTime)
References ASSERT, IsFinite, ROWS.
static variable MSQ_NumAcquiredSweepsInSet(string device, variable sweepNo, variable headstage)
Return the number of already acquired sweeps of the given stimset cycle ID.
References AFH_GetSweepsFromSameSCI, GetLBNumericalValues, ROWS.
static variable MSQ_NumPassesInSet(wave numericalValues, variable type, variable sweepNo, variable headstage)
Return the number of passed sweeps in all sweeps from the given repeated acquisition cycle.
References AFH_GetSweepsFromSameSCI, CreateAnaFuncLBNKey, GetLastSettingIndep, MSQ_FMT_LBN_SWEEP_PASS, ROWS, UNKNOWN_MODE.
Referenced by MSQ_FastRheoEst.
static variable MSQ_GetDAStimsetLength(string device, variable headstage)
Return the DA stimset length in ms of the given headstage.
stimset length or -1 on error
References AFH_GetDACFromHeadstage, AFH_GetStimSetName, CHANNEL_TYPE_DAC, ROWS, WB_CreateAndGetStimSet.
wave MSQ_CreateOverrideResults(string device, variable headstage, variable type)
MSQ_PSQ_CreateOverrideResults("ITC18USB_DEV_0", 0, $type) where type is one of: MSQ_FAST_RHEO_EST Type: Double wave Value: x position in ms where the spike is in each sweep/step For convenience the values 0 always means no spike and 1 spike detected (at the appropriate position). Rows: Sweeps in set Cols: IC headstages MSQ_DA_SCALE Nothing SC_SPIKE_CONTROL Type: Text wave Value: Key-Valuse pairs in format key1:value1;key2:value2; where value can be a comma separated list SpontaneousSpikeMax: single value denoting the maximum value for the spontaneous spiking check SpikePosition_ms: comma separated list with the spike positions in ms. Zero is the start of each pulse Rows: Sweeps in set Cols (NUM_HEADSTAGES): Headstage Layers (10): Pulse index, 0-based Chunks (10): Region, 0-based
References AFH_GetDACFromHeadstage, AFH_GetStimSetName, ASSERT, CHANNEL_TYPE_DAC, DAG_GetActiveHeadstages, GetOverrideResults, I_CLAMP_MODE, IDX_NumberOfSweepsInSet, IGOR_TYPE_64BIT_FLOAT, KillOrMoveToTrash, MSQ_DA_SCALE, MSQ_FAST_RHEO_EST, NUM_HEADSTAGES, SC_SPIKE_CONTROL, WB_CreateAndGetStimSet.
static wave MSQ_SearchForSpikes(string device, variable type, wave sweepWave, variable headstage, variable totalOnsetDelay, variable numberOfSpikes=defaultValue, variable defaultValue=defaultValue, wave spikePositions=defaultValue)
Search the AD channel of the given headstage for spikes from the pulse onset until the end of the sweep.
device device type One of MultiPatchSeqAnalysisFunctionTypes sweepWave sweep wave with acquired data headstage headstage in the range [0, NUM_HEADSTAGES[ totalOnsetDelay total delay in ms until the stimset data starts numberOfSpikes [optional, defaults to one] number of spikes to look for spikePositions [optional] returns the position of the first numberOfSpikes found on success in ms defaultValue [optiona, defaults to NaN] the value of the other headstages in the returned wave labnotebook value wave suitable for ED_AddEntryToLabnotebook()
References AFH_ExtractOneDimDataFromSweep, ASSERT, DATA_ACQUISITION_MODE, DEBUGPRINT, DEBUGPRINTw, GetConfigWave, GetDAQConfigWave, GetDAQDataWave, GetMachineEpsilon, GetOverrideResults, IsFinite, LABNOTEBOOK_LAYER_COUNT, MSQ_FAST_RHEO_EST, MSQ_SPIKE_LEVEL, TestOverrideActive, WaveMinAndMaxWrapper, XOP_CHANNEL_TYPE_ADC, XOP_CHANNEL_TYPE_DAC.
Referenced by MSQ_FastRheoEst.
static variable MSQ_GetLBNEntryForHSSCIBool(wave numericalValues, variable sweepNo, variable type, string str, variable headstage)
Return true if one of the entries is true for the given headstage. False otherwise. Searches in the complete SCI and assumes that the entries are either 0/1/NaN.
Todomerge with LBN functions once these are reworked.
References CreateAnaFuncLBNKey, GetLastSettingEachSCI, UNKNOWN_MODE, ZapNaNs.
Referenced by MSQ_DAScale, MSQ_FastRheoEst.
static variable MSQ_GetLBNEntryForHeadstageSCI(wave numericalValues, variable sweepNo, variable type, string str, variable headstage)
Return the last entry for a given headstage from the full SCI.
This differs from GetLastSettingSCI as specifically the setting for the passed headstage must be valid. Todomerge with LBN functions once these are reworked.
References CreateAnaFuncLBNKey, GetLastSettingEachSCI, ROWS, UNKNOWN_MODE.
Referenced by MSQ_DS_GetDAScaleOffset.
string MSQ_FastRheoEst_GetParams()
Return a list of required parameters for MSQ_FastRheoEst()
string MSQ_FastRheoEst_GetHelp(string name)
References ASSERT.
string MSQ_FastRheoEst_CheckParam(string name, CheckParametersStruct *s)
References AFH_GetAnalysisParamNumerical, IsFinite, IsValidSamplingMultiplier, CheckParametersStruct::params.
variable MSQ_FastRheoEst(string device, AnalysisFunction_V3 *s)
Analysis function to find the smallest DAScale where the cell spikes.
Prerequisites: Assumes that the stimset has a square pulse Testing: For testing the spike detection logic, the results can be defined in the override wave, MSQ_CreateOverrideResults(). Decision logic flowchart: embed:rst:leading-asterisk * .. image:: /dot/multi-patch-seq-fast-rheo-estimate.svg * /// /// Sketch of a stimset with pre pulse baseline (-), square pulse (*), and post pulse baseline (-). /// /// ******* /// | | /// | | /// | | /// | | /// | | /// | | /// | | /// | | /// | | /// | | /// | | /// | | /// ---| |-------------------------------------------- /// ///
References AD_UpdateAllDatabrowser, AFH_GetAnalysisParamNumerical, AFH_GetDACFromHeadstage, AFH_GetStimSetName, ASSERT, CHANNEL_CONTROL_CHECK, CHANNEL_TYPE_DAC, CHANNEL_TYPE_HEADSTAGE, CHANNEL_TYPE_TTL, CHECKBOX_SELECTED, CHECKBOX_UNSELECTED, CheckIfClose, ControlWindowToFront, CreateAnaFuncLBNKey, DAG_GetActiveHeadstages, DAG_GetChannelState, DAG_HeadstageIsHighestActive, DATA_ACQUISITION_MODE, DEBUGPRINT, DisableControls, ED_AddEntryToLabnotebook, EnableControls, AnalysisFunction_V3::eventType, GetLastSetting, GetLastSettingEachSCI, GetLastSettingSCI, GetLBNumericalValues, GetPanelControl, GetSweepWave, GetTotalOnsetDelay, GetUniqueTextEntriesFromList, HasOneValidEntry, I_CLAMP_MODE, INDEP_HEADSTAGE, IsFinite, LABNOTEBOOK_BINARY_UNIT, LABNOTEBOOK_LAYER_COUNT, MSQ_CommonPreDAQ, MSQ_FAST_RHEO_EST, MSQ_FMT_LBN_ACTIVE_HS, MSQ_FMT_LBN_DASCALE_EXC, MSQ_FMT_LBN_FINAL_SCALE, MSQ_FMT_LBN_HEADSTAGE_PASS, MSQ_FMT_LBN_SET_PASS, MSQ_FMT_LBN_SPIKE_DETECT, MSQ_FMT_LBN_STEPSIZE, MSQ_FMT_LBN_SWEEP_PASS, MSQ_ForceSetEvent, MSQ_FRE_INIT_AMP_m50, MSQ_FRE_INIT_AMP_p10, MSQ_FRE_INIT_AMP_p100, MSQ_GetLBNEntryForHSSCIBool, MSQ_GetPulseDurations, MSQ_NumPassesInSet, MSQ_SearchForSpikes, NUM_HEADSTAGES, AnalysisFunction_V3::params, PGC_MODE_FORCE_ON_DISABLED, PGC_SetAndActivateControl, POST_DAQ_EVENT, POST_SET_EVENT, POST_SWEEP_EVENT, PRE_DAQ_EVENT, PRE_SET_EVENT, RA_SkipSweeps, ROWS, SetAnalysisFunctionVersion, SetDAScale, STIMSET_SCALE_FACTOR_KEY, AnalysisFunction_V3::sweepNo, ToPassFail, UNKNOWN_MODE, ZapNaNs.
static wave MSQ_DS_GetDAScaleOffset(string device, variable headstage)
Return the DAScale offset [pA] for MSQ_DaScale()
wave with LABNOTEBOOK_LAYER_COUNT entries, each holding the final DA Scale entry from the previous fast rheo estimate run.
References GetLBNumericalValues, IsValidSweepNumber, LABNOTEBOOK_LAYER_COUNT, MSQ_DS_OFFSETSCALE_FAKE, MSQ_FAST_RHEO_EST, MSQ_FMT_LBN_FINAL_SCALE, MSQ_GetLastPassingLongRHSweep, MSQ_GetLBNEntryForHeadstageSCI, NUM_HEADSTAGES, TestOverrideActive.
Referenced by MSQ_DAScale.
static variable MSQ_GetLastPassingLongRHSweep(string device, variable headstage)
Return a sweep number of an existing sweep matching the following conditions.
Acquired with Rheobase analysis function Sweep set was passing Pulse duration was longer than 500ms And as usual we want the last matching sweep. existing sweep number or -1 in case no such sweep could be found
References CreateAnaFuncLBNKey, GetLastSettingSCI, GetLBNumericalValues, GetSweepsWithSetting, MSQ_DS_SWEEP_FAKE, MSQ_FAST_RHEO_EST, MSQ_FMT_LBN_PULSE_DUR, MSQ_FMT_LBN_SET_PASS, ROWS, TestOverrideActive, UNKNOWN_MODE.
Referenced by MSQ_DS_GetDAScaleOffset.
static variable MSQ_ForceSetEvent(string device, variable headstage)
Manually force the pre/post set events.
Required to do before skipping sweeps. Todothis hack must go away.
References AFH_GetDACFromHeadstage, GetSetEventFlag, POST_SET_EVENT, PRE_SET_EVENT.
Referenced by MSQ_FastRheoEst.
variable MSQ_CommonPreDAQ(string device, variable headstage, variable clampMode=defaultValue)
Common pre DAQ calls for all multipatch analysis functions.
References ControlWindowToFront, DAG_GetNumericalValue, DAG_HeadstageIsHighestActive, PGC_SetAndActivateControl.
Referenced by MSQ_DAScale, MSQ_FastRheoEst, SC_SpikeControl.
string MSQ_DAScale_GetParams()
Require parameters from stimset.
string MSQ_DAScale_GetHelp(string name)
References ASSERT.
string MSQ_DAScale_CheckParam(string name, CheckParametersStruct *s)
References AFH_GetAnalysisParamWave, CheckParametersStruct::params.
variable MSQ_DAScale(string device, AnalysisFunction_V3 *s)
Analysis function to apply a list of DAScale values to a range of sweeps.
Decision logic flowchart: embed:rst:leading-asterisk * .. image:: /dot/multi-patch-seq-dascale.svg *
References AD_UpdateAllDatabrowser, AFH_GetAnalysisParamWave, ASSERT, CHANNEL_CONTROL_CHECK, CHANNEL_TYPE_HEADSTAGE, CHANNEL_TYPE_TTL, CHECKBOX_SELECTED, CHECKBOX_UNSELECTED, CheckIfSmall, ControlWindowToFront, CreateAnaFuncLBNKey, DAG_GetActiveHeadstages, DAG_GetChannelState, DAG_GetNumericalValue, DAG_HeadstageIsHighestActive, DisableControls, ED_AddEntryToLabnotebook, EnableControls, AnalysisFunction_V3::eventType, GetAnalysisFuncIndexingHelper, GetLastSettingSCI, GetLBNumericalValues, GetPanelControl, HasOneValidEntry, I_CLAMP_MODE, INDEP_HEADSTAGE, IsFinite, LABNOTEBOOK_BINARY_UNIT, LABNOTEBOOK_LAYER_COUNT, MSQ_CommonPreDAQ, MSQ_DA_SCALE, MSQ_DS_GetDAScaleOffset, MSQ_FMT_LBN_ACTIVE_HS, MSQ_FMT_LBN_HEADSTAGE_PASS, MSQ_FMT_LBN_SET_PASS, MSQ_FMT_LBN_SWEEP_PASS, MSQ_GetLBNEntryForHSSCIBool, NUM_HEADSTAGES, AnalysisFunction_V3::params, PGC_SetAndActivateControl, POST_DAQ_EVENT, POST_SET_EVENT, POST_SWEEP_EVENT, PRE_DAQ_EVENT, PRE_SET_EVENT, ROWS, SetAnalysisFunctionVersion, SetDAScale, AnalysisFunction_V3::sweepNo, TestOverrideActive, UNKNOWN_MODE.