MIES_AnalysisBrowser_SweepBrowser_Export.ipf
const string SBE_EXPORT_PANEL
Referenced by SBE_GetPulseStartTimesForSel, SBE_GetSelectedAxis, SBE_GetSourceGraphADTraces, SBE_ShowExportPanel.
static variable SBE_FillExportSettings(string win, SBE_ExportSettings *sett)
References SBE_ExportSettings::ADC, AXIS_ORIENTATION_HORIZ, AXIS_ORIENTATION_VERT, SBE_ExportSettings::axisEqualizing, SBE_ExportSettings::bottomAxis, SBE_ExportSettings::dataFolder, SBE_ExportSettings::equalYRange, GetCheckBoxState, GetPopupMenuString, GetSetVariable, GetSetVariableString, GetUniqueAxisName, IsControlDisabled, SBE_ExportSettings::leftAxis, SBE_ExportSettings::manualRangeBegin, SBE_ExportSettings::manualRangeEnd, SBE_ExportSettings::numPulses, SBE_ExportSettings::postLastPulse, SBE_ExportSettings::preFirstPulse, SBE_ExportSettings::resetWaveZero, SBE_ExportSettings::sourceGraph, SBE_ExportSettings::targetGraph, SBE_ExportSettings::useCursorRange, SBE_ExportSettings::usePulses, WindowExists.
Referenced by SBE_ButtonProc_PerformExport.
string SBE_GetSelectedAxis(string graphPopup, variable axisOrientation)
Return a list of possible axes for the export panel.
References ASSERT, AXIS_ORIENTATION_HORIZ, AXIS_ORIENTATION_VERT, GetAllAxesWithOrientation, GetPopupMenuString, SBE_EXPORT_PANEL, WindowExists.
static variable SBE_AddMissingADTraceInfo(WaveText traceData)
Add all available sweep data to traceData.
This function can fill in the available data for traces which are not shown.
References DATA_ACQUISITION_MODE, EnsureLargeEnoughWave, GetDAQDataSingleColumnWaves, GetLastSetting, GetRowIndex, IsFinite, ROWS, XOP_CHANNEL_NAMES, XOP_CHANNEL_TYPE_ADC.
Referenced by SBE_GetPulseStartTimesForSel.
static wave SBE_GetPulseStartTimesForSel()
References FindIndizes, GetGraphUserData, GetPopupMenuString, GetSetIntersection, PA_GetPulseInfos, ROWS, SBE_AddMissingADTraceInfo, SBE_EXPORT_PANEL, WindowExists.
Referenced by SBE_ExportSweepBrowser, SBE_PopMenuProc_PulsesADTrace.
variable SBE_ShowExportPanel(string sourceWindow)
Display the export panel.
References GetMainWindow, panel, SBE_EXPORT_PANEL, WindowExists.
Referenced by SB_ButtonProc_ExportTraces.
string SBE_ListOfGraphsAndNew()
Return a list of possible target graphs for the export panel.
string SBE_ListOfSweepGraphs()
Return a list of possible source graphs for the export panel.
string SBE_GetSourceGraphADTraces()
Return a list of all AD traces from the selected target graph.
References GetAllSweepTraces, GetPopupMenuString, SBE_EXPORT_PANEL, TextWaveToList, XOP_CHANNEL_TYPE_ADC.
static variable SBE_ExportSweepBrowser(SBE_ExportSettings *sett)
Export the sweep browser traces to a user given folder.
Creates a new graph from it or appends to an existing one. Only duplicates the main graph without external subwindows
References SBE_ExportSettings::ADC, AddEntryIntoWaveNoteAsList, ASSERT, AXIS_ORIENTATION_HORIZ, AXIS_ORIENTATION_VERT, SBE_ExportSettings::axisEqualizing, SBE_ExportSettings::bottomAxis, ControlWindowToFront, createDFWithAllParents, DATA_ACQUISITION_MODE, SBE_ExportSettings::dataFolder, DEBUGPRINT, EqualizeVerticalAxesRanges, EquallySpaceAxis, SBE_ExportSettings::equalYRange, FindIndizes, GetAllAxesWithOrientation, GetAnalysisFolderAS, GetLastSetting, IsFinite, SBE_ExportSettings::leftAxis, ListHasOnlyOneUniqueEntry, SBE_ExportSettings::manualRangeBegin, SBE_ExportSettings::manualRangeEnd, MinMax, SBE_ExportSettings::numPulses, SBE_ExportSettings::postLastPulse, SBE_ExportSettings::preFirstPulse, RemovePrefix, ReplaceWordInString, SBE_ExportSettings::resetWaveZero, ROWS, SB_GetSweepBrowserFolder, SBE_GetPulseStartTimesForSel, SBE_ExportSettings::sourceGraph, STIM_WAVE_NAME_KEY, SBE_ExportSettings::targetGraph, TUD_GetUserData, UniqueDataFolder, UniqueTraceName, UniqueWaveName, SBE_ExportSettings::useCursorRange, SBE_ExportSettings::usePulses, WindowExists.
Referenced by SBE_ButtonProc_PerformExport.
void SBE_ExportSettingsPanel()
variable SBE_PopMenu_ExportTargetAxis(WMPopupAction *pa)
References DisableControls, EnableControls.
variable SBE_PopMenu_ExportTargetGraph(WMPopupAction *pa)
References DisableControl, EnableControl.
variable SBE_ButtonProc_PerformExport(WMButtonAction *ba)
References SBE_ExportSweepBrowser, SBE_FillExportSettings.
variable SBE_CheckProc_UsePulseForXRange(WMCheckboxAction *cba)
References DisableControls, EnableControls, GetPopupMenuIndex, PGC_SetAndActivateControl.
variable SBE_PopMenuProc_PulsesADTrace(WMPopupAction *pa)
References ROWS, SBE_GetPulseStartTimesForSel.