MIES_Regenerate-Screenshots.ipf
static string GetSavePath()
References CreateFolderOnDisk, GetFolder, GetUniqueSymbolicPath.
Referenced by ScreenShotsForAnalysisBrowser, ScreenShotsForDAEphys, ScreenShotsForDataBrowser, ScreenShotsForWaveBuilder.
variable run()
References ScreenShotsForDataBrowser.
variable RestrictScreenshotToControl(string path, string filename, string panel, string control)
References ASSERT.
Referenced by ScreenShotsForWaveBuilder.
static variable ScreenShotsForAnalysisBrowser()
References AB_OpenAnalysisBrowser, GetSavePath, panel.
static variable ScreenShotsForWaveBuilder()
References EPOCH_TYPES_TOTAL_NUMBER, GetSavePath, panel, PGC_SetAndActivateControl, RestrictScreenshotToControl, SanitizeFilename, WB_ToEpochTypeString, WBP_CreateWaveBuilderPanel.
static Function ScreenShotsForDAEphys()
References DAP_CreateDAEphysPanel, GetSavePath, panel, PGC_SetAndActivateControl, ROWS, SanitizeFilename, SCOPE_GetPanel.
static variable ScreenShotsForDataBrowser()
References AssembleOneDataBrowserImage, ASSERT, BSP_GetPanel, BSP_GetSweepControlsPanel, GetSavePath, PGC_SetAndActivateControl, ROWS, SanitizeFilename, WindowExists.
Referenced by run.
variable AssembleOneDataBrowserImage(string path)
References COLS, ROWS.
Referenced by ScreenShotsForDataBrowser.
variable CreateRelevantColorsGraph()
References GetHeadstageColor, NUM_HEADSTAGES.