MIES_SweepSaving.ipf
variable SWS_SaveAcquiredData(string device, variable forcedStop=defaultValue)
Save the acquired sweep permanently.
device device forcedStop [optional, defaults to false] if DAQ was aborted (true) or stopped by itself (false)
References AFM_CallAnalysisFunctions, AS_HandlePossibleTransition, AS_POST_SWEEP, ASSERT, BUG, DAG_GetNumericalValue, DAG_GetTextualValue, DAG_Update, DATA_ACQUISITION_MODE, ED_createWaveNoteTags, EP_WriteEpochInfoIntoSweepSettings, GetConfigWave, GetConfigWaveName, GetDAQConfigWave, GetDAQDataWave, GetDeviceDataPath, GetScaledDataWave, GetSweepWave, GetSweepWaveName, IsValidSweepAndConfig, NWB_AppendSweepDuringDAQ, POST_SET_EVENT, SetSetVariable, SetSetVariableLimits, SWS_AfterSweepDataChangeHook.
Referenced by DQ_StopOngoingDAQHelper, DQM_StopDataAcq, DQS_StopDataAcq.
static variable SWS_AfterSweepDataChangeHook(string device)
General hook function which gets always executed after sweep data was added or removed.
device device name
References AssertOnAndClearRTError, BSP_GetSweepControlsPanel, ClearRTError, DB_FindDataBrowser, DB_UpdateToLastSweep, GetCheckBoxState, IsEmpty.
Referenced by SWS_DeleteDataWaves, SWS_SaveAcquiredData.
wave SWS_GetChannelGains(string device, variable timing=defaultValue)
Return a free wave with all channel gains.
Rows: Active channels only (same as DAQConfigWave) Different hardware has different requirements how the DA, AD and TLL channels are scaled. As general rule use data * SWS_GetChannelGains for GAIN_BEFORE_DAQ and data / SWS_GetChannelGains for GAIN_AFTER_DAQ, i.e. before_gain * data(before_DAQ) == after_gain * data(after_DAQ). embed:rst:leading-asterisk * * ========== ========= =============================================== * Hardware Channel Specialities * ========== ========= =============================================== * ITC DA None * ITC AD None * ITC TTL Multiple TTL bits are combined. See SplitTTLWaveIntoComponents() for details. * NI DA None * NI AD Scaled directly on acquisition. * NI TTL One channel per TTL bit. * ========== ========= =============================================== * * device device timing One of GainTimeParameter GetDAQDataWave()
References ASSERT, CHANNEL_CONTROL_GAIN, CHANNEL_TYPE_ADC, CHANNEL_TYPE_DAC, GAIN_AFTER_DAQ, GAIN_BEFORE_DAQ, GetADCListFromConfig, GetDA_EphysGuiStateNum, GetDACListFromConfig, GetDAQConfigWave, GetHardwareType, GetTTLListFromConfig, HARDWARE_ITC_BITS_PER_VOLT, HARDWARE_ITC_DAC, HARDWARE_NI_DAC, ROWS.
Referenced by DC_GetConfiguration, PSQ_CR_DetermineCycles, PSQ_SearchForSpikes, SCOPE_NI_UpdateOscilloscope.
variable SWS_DeleteDataWaves(string device)
Delete all sweep and config waves having a sweep number of sweepNo and higher.
References ASSERT, COUNTOBJECTS_DATAFOLDER, DAG_GetNumericalValue, DATA_CONFIG_REGEXP, DATA_CONFIG_REGEXP_BAK, DATA_SWEEP_REGEXP, DATA_SWEEP_REGEXP_BAK, DataFolderExistsDFR, DEBUG_TIMER_START, DEBUGPRINT_ELAPSED, ExtractSweepNumber, GetDeviceDataPath, GetDeviceDataPathAsString, GetLBNumericalValues, GetListOfObjects, GetSweepsWithSetting, IsDataFolderEmpty, ROWS, SWEEP_ROLLBACK_KEY, SWS_AfterSweepDataChangeHook, UniqueDataFolder, ZapNaNs.
Referenced by DAP_CheckSettings.
variable SWS_GetRawDataFPType(string device)
Return the floating point type for storing the raw data.
The returned values are the same as for WaveType
References DAG_GetNumericalValue, IGOR_TYPE_32BIT_FLOAT, IGOR_TYPE_64BIT_FLOAT.
Referenced by DC_MakeAndGetDAQDataWave, DC_MakeHelperWaves, GetScaledDataWave.