MIES_SamplingInterval.ipf
const double MIN_CONSECUTIVE_SAMPINT
The consecutive check in SI_TestSampInt enforces not only one sucessfull sampling interval but also the multiples 2^x where x ranges from 1 to MIN_CONSECUTIVE_SAMPINT Set to 0 to deactivate
static variable SI_FillITCConfig(wave wv, wave results, variable idx, variable totalNumDA, variable totalNumAD, variable totalNumTTL)
Fill the passed wave to be used as DAQConfigWave.
References XOP_CHANNEL_TYPE_ADC, XOP_CHANNEL_TYPE_DAC, XOP_CHANNEL_TYPE_TTL.
static variable SI_FillITCConfigWithPerms(wave wv, variable start, variable value, variable channelType)
Fill the passed wave to be used as DAQConfigWave for the exhaustive search.
static variable SI_CompressWave(wave wv)
Removes invalid and duplicated entries from the generated table from SI_CreateLookupWave.
References CreateBackupWave, ROWS, SI_SortWave.
static variable SI_SortWave(wave wv)
Sort the lookup wave.
References ROWS.
Referenced by SI_CompressWave.
static variable SI_FindMatchingTableEntry(wave wv, ActiveChannels *ac)
Search the given active channel combination in the lookup wave.
References ASSERT, CA_SamplingIntervalKey, CA_StoreEntryIntoCache, CA_TryFetchingEntryFromCache, ControlWindowToFront, ActiveChannels::numADRack1, ActiveChannels::numADRack2, ActiveChannels::numDARack1, ActiveChannels::numDARack2, ActiveChannels::numTTLRack1, ActiveChannels::numTTLRack2, ROWS, SAMPLING_INTERVAL_FALLBACK.
Referenced by SI_ITC_CalculateMinSampInterval.
static wave SI_LoadMinSampIntFromDisk(string deviceType)
Try to load the lookup wave for the minimum sampling interval from disk for the given deviceType.
a lookup wave or an invalid wave ref if it could not be loaded from disk
References LoadWaveFromDisk.
Referenced by SI_GetMinSampIntWave.
wave SI_StoreMinSampIntOnDisk(wave wv, string deviceType)
Store the lookup wave on disc.
References GetFolder.
static variable SI_FillActiveChannelsStruct(string device, ActiveChannels *ac)
Query the DA_EPhys panel for the active channels and fill it in the passed structure.
number of active channels
References ASSERT, CHANNEL_TYPE_ADC, CHANNEL_TYPE_DAC, CHANNEL_TYPE_TTL, DAG_GetChannelState, IsEven, NUM_AD_CHANNELS, NUM_DA_TTL_CHANNELS, ActiveChannels::numADRack1, ActiveChannels::numADRack2, ActiveChannels::numDARack1, ActiveChannels::numDARack2, ActiveChannels::numTTLRack1, ActiveChannels::numTTLRack2.
Referenced by SI_ITC_CalculateMinSampInterval.
variable SI_CreateLookupWave(string device, variable ignoreChannelOrder=defaultValue)
References DEBUGPRINT.
static variable SI_TestSampInt(string device)
References DEBUGPRINT.
variable SI_CalculateMinSampInterval(string device, variable dataAcqOrTP)
Calculate the minimum sampling interval.
device device dataAcqOrTP one of DataAcqModes, ignores TTL channels for TEST_PULSE_MODE sampling interval in microseconds (1e-6)
References GetHardwareType, HARDWARE_ITC_DAC, HARDWARE_NI_DAC, SI_ITC_CalculateMinSampInterval, SI_NI_CalculateMinSampInterval.
Referenced by DAP_GetSampInt, DAP_LockDevice.
static variable SI_NI_CalculateMinSampInterval(string device)
Calculate the minimum sampling interval for NI hardware.
SI_CalculateMinSampInterval sampling interval in microseconds (1e-6)
References CHANNEL_TYPE_ADC, DAG_GetChannelState, HARDWARE_NI_DAC_MIN_SAMPINT.
Referenced by SI_CalculateMinSampInterval.
static variable SI_ITC_CalculateMinSampInterval(string device, variable dataAcqOrTP)
Calculate the minimum sampling interval for ITC hardware using the lookup waves on disk.
device device dataAcqOrTP one of DataAcqModes, ignores TTL channels for TEST_PULSE_MODE SI_CalculateMinSampInterval sampling interval in microseconds (1e-6)
References ASSERT, HARDWARE_ITC_MIN_SAMPINT, ParseDeviceString, SAMPLING_INTERVAL_FALLBACK, SI_FillActiveChannelsStruct, SI_FindMatchingTableEntry, SI_GetMinSampIntWave, TEST_PULSE_MODE.
Referenced by SI_CalculateMinSampInterval.
static wave SI_GetMinSampIntWave(string device)
Return a wave ref with the lookup wave for the sampling interval.
This functions tries to load the wave from disk on the first call so this function might take a while to execute.
References ASSERT, DEBUGPRINT, GetStaticDataFolder, ParseDeviceString, SI_LoadMinSampIntFromDisk.
Referenced by SI_ITC_CalculateMinSampInterval.