MIES_DAEphys.ipf
variable DAP_EphysPanelStartUpSettings()
Restores the base state of the DA_Ephys panel. Useful when adding controls to GUI. Facilitates use of auto generation of GUI code. Useful when template experiment file has been overwritten.
References BASE_WINDOW_TITLE, CHANNEL_TYPE_DAC, CHANNEL_TYPE_TTL, ControlWindowToFront, DAP_AdaptPanelForDeviceSpecifics, DAP_FormatStimSetPopupValue, DAP_GetOsciUpdModes, DAP_GUIListOfYokedDevices, DAP_UnlockDevice, DisableControl, EnableControl, EnableControls, GetCurrentWindow, GetMainWindow, GetTPSettingsFree, NONE, PGC_SetAndActivateControl, SCOPE_KillScopeWindowIfRequest, SearchForInvalidControlProcs, SetControlUserData, SetPopupMenuIndex, SetPopupMenuVal, SetSetVariable, SetSetVariableString.
const double DATA_ACQU_TAB_NUM
Referenced by DAP_WindowHook.
const double HARDWARE_TAB_NUM
Referenced by DAP_UpdateYokeControls.
const string YOKE_LIST_OF_CONTROLS
Referenced by DAP_UpdateAllYokeControls, DAP_UpdateYokeControls.
const string YOKE_CONTROLS_DISABLE
Referenced by DAP_ButtonProc_Follow, DAP_RemoveYokedDAC.
const string YOKE_CONTROLS_DISABLE_AND_LINK
Synced with desc in DAP_CheckSettingsAcrossYoked()
Referenced by DAP_ButtonProc_Follow, DAP_CheckSettingsAcrossYoked, DAP_RemoveYokedDAC, DAP_SyncGuiFromLeaderToFollower.
const string FOLLOWER
Referenced by DAP_UpdateFollowerControls.
const string LEADER
Referenced by DAP_ButtonProc_Lead, DAP_DeviceIsLeader.
const string COMMENT_PANEL
Referenced by DAP_GetCommentPanel, DAP_LockCommentNotebook, DAP_UnlockCommentNotebook.
const string COMMENT_PANEL_NOTEBOOK
Referenced by DAP_GetCommentNotebook.
const string AMPLIFIER_DEF_FORMAT
Referenced by DAP_GetAmplifierDef, DAP_ParseAmplifierDef.
const string GUI_CONTROLSAVESTATE_DISABLED
Referenced by DAP_OneTimeCallAfterDAQ, DAP_OneTimeCallBeforeDAQ.
const string NI_DAC_PATTERNS
Referenced by DAP_GetNIDeviceList.
const double DAP_WAITFORTPANALYSIS_TIMEOUT
Referenced by DAP_UnlockDevice.
wave DAP_GetRadioButtonCoupling()
Creates meta information about coupled CheckBoxes (Radio Button) controls Used for saving/restoring the GUI state.
Free text wave with lists of coupled CheckBox controls
string DAP_GetNIDeviceList()
Returns a list of DAC devices for NI devices.
list of NI DAC devices
References DAP_UpdateDeviceInfoWaves, HARDWARE_MAX_DEVICES, HARDWARE_NI_DAC, HW_NI_GetPropertyListOfDevices, HW_NI_ListDevices, isEmpty, IsEmpty, IsValidObjectName, NI_DAC_PATTERNS.
Referenced by ButtonProc_Hardware_rescan, DAP_CreateDAEphysPanel, DAP_GetDACDeviceList, DAP_UpdateListOfLockedDevices.
string DAP_GetITCDeviceList()
Returns a list of ITC devices for DAC.
References DAP_UpdateDeviceInfoWaves, HARDWARE_ITC_DAC, HW_ITC_ListDevices, isEmpty.
Referenced by ButtonProc_Hardware_rescan, ButtonProc_Hrdwr_P_UpdtDAClist, DAP_CreateDAEphysPanel, DAP_GetDACDeviceList.
string DAP_GetDACDeviceList()
Returns a list of available ITC and NI devices.
list of DAC devices
References DAP_GetITCDeviceList, DAP_GetNIDeviceList, IsEmpty, NONE.
variable DAP_WindowHook(WMWinHookStruct *s)
References AssertOnAndClearRTError, ClearRTError, DAP_UnlockDevice, DATA_ACQU_TAB_NUM, EVENT_KILL_WINDOW_HOOK, GetControlCoordinates, GetTabID, IsInsideRect, NUM_HEADSTAGES, P_SetPressureOffset, PRESSURE_CONTROL_LED_DASHBOARD, PS_StoreWindowCoordinate.
string DAP_FormatStimSetPopupValue(variable channelType, string searchString=defaultValue)
Return a popValue string suitable for stimsets.
Todorework the code to have a fixed popValue
References NONE.
Referenced by DAP_EphysPanelStartUpSettings, DAP_SetVarProc_Channel_Search.
static variable DAP_DeviceIsLeader(string device)
Check by querying the GUI if the device is a leader.
Outside callers should use DeviceHasFollower() instead.
References DAG_GetTextualValue, LEADER.
Referenced by DAP_SyncGuiFromLeaderToFollower, DAP_UpdateAllYokeControls, DAP_UpdateITIAcrossSets, DAP_UpdateSweepLimitsAndDisplay.
static variable DAP_UpdateAllYokeControls()
Updates the yoking controls on all locked/unlocked panels.
References DAP_DeviceIsLeader, DAP_UpdateYokeControls, DeviceCanLead, DisableControls, EnableControl, GetListOfLockedDevices, GetListOfLockedITC1600Devices, GetListOfUnlockedDevices, YOKE_LIST_OF_CONTROLS.
Referenced by DAP_ButtonProc_Independent, DAP_LockDevice, DAP_UnlockDevice.
string DAP_GUIListOfYokedDevices()
References GetDevicePathAsString, ITC1600_FIRST_DEVICE.
Referenced by DAP_EphysPanelStartUpSettings, DAP_UpdateYokeControls.
variable DAP_UpdateYokeControls(string device)
References DAP_GUIListOfYokedDevices, DeviceCanFollow, DeviceIsFollower, GetTabID, HARDWARE_TAB_NUM, HideControls, ShowControls, YOKE_LIST_OF_CONTROLS.
Referenced by DAP_ButtonProc_YokeRelease, DAP_TabControlFinalHook, DAP_UnlockDevice, DAP_UpdateAllYokeControls, DAP_UpdateFollowerControls.
static variable DAP_UpdateDrawElements(string device, variable tab)
Referenced by DAP_TabControlFinalHook.
variable DAP_TabControlFinalHook(WMTabControlAction *tca)
Called by ACL tab control after the tab is updated. see line 257 of ACL_TabUtilities.ipf.
References ControlWindowToFront, DAP_UpdateDrawElements, DAP_UpdateYokeControls.
variable DAP_SetVarProc_Channel_Search(WMSetVariableAction *sva)
References ASSERT, CHANNEL_CONTROL_INDEX_END, CHANNEL_CONTROL_SEARCH, CHANNEL_CONTROL_WAVE, DAG_Update, DAP_DACHasExpectedClampMode, DAP_FormatStimSetPopupValue, DAP_IsAllControl, DAP_ParsePanelControl, GetNumberFromType, GetPanelControl, GetPopupMenuString, isEmpty, PGC_MODE_SKIP_ON_DISABLED, PGC_SetAndActivateControl, ST_GetStimsetList, USER_DATA_MENU_EXP.
variable DAP_DAorTTLCheckProc(WMCheckboxAction *cba)
References AssertOnAndClearRTError, ClearRTError, DAG_Update, DAP_AdaptAssocHeadstageState, DAP_UpdateDAQControls, REASON_HEADSTAGE_CHANGE, REASON_STIMSET_CHANGE, SetCheckBoxState.
variable DAP_CheckProc_Channel_All(WMCheckboxAction *cba)
References ASSERT, CHANNEL_CONTROL_CHECK, DAG_GetNumericalValue, DAG_Update, DAP_DACHasExpectedClampMode, DAP_ParsePanelControl, GetNumberFromType, GetPanelControl, GetSpecialControlLabel, PGC_SetAndActivateControl.
variable DAP_IsAllControl(variable channelIndex)
Determines if the control refers to an "All" control.
References CHANNEL_INDEX_ALL, CHANNEL_INDEX_ALL_I_CLAMP, CHANNEL_INDEX_ALL_V_CLAMP.
Referenced by DAP_DACHasExpectedClampMode, DAP_PopMenuChkProc_StimSetList, DAP_SetVarProc_Channel_Search, DAP_SetVarProc_DA_Scale.
variable DAP_DACHasExpectedClampMode(string device, variable controlChannelIndex, variable channelNumber, variable channelType)
Helper for "All" controls in the DA tab.
0 if the given channel is a DA channel and not in the expected clamp mode as determined by controlChannelIndex, 1 otherwise
References AFH_GetHeadstageFromDAC, ASSERT, CHANNEL_INDEX_ALL, CHANNEL_INDEX_ALL_I_CLAMP, CHANNEL_INDEX_ALL_V_CLAMP, CHANNEL_TYPE_DAC, DAG_GetHeadstageMode, DAP_IsAllControl, I_CLAMP_MODE, IsFinite, V_CLAMP_MODE.
Referenced by DAP_CheckProc_Channel_All, DAP_PopMenuChkProc_StimSetList, DAP_SetVarProc_Channel_Search, DAP_SetVarProc_DA_Scale.
variable DAP_CheckProc_AD(WMCheckboxAction *cba)
References AssertOnAndClearRTError, ClearRTError, DAG_Update, DAP_AdaptAssocHeadstageState, SetCheckBoxState.
variable GetHeadstageFromSettings(string device, variable channelType, variable channelNumber, variable clampMode)
Get the headstage for the given channel number and type from the amplifier settings.
This is different from what GetChannelClampMode holds as we here hold the setup information and GetChannelClampMode holds what is currently active.
References AI_IsValidClampMode, ASSERT, GetChanAmpAssign, NUM_HEADSTAGES, V_CLAMP_MODE, XOP_CHANNEL_TYPE_ADC, XOP_CHANNEL_TYPE_DAC.
Referenced by DAP_AdaptAssocHeadstageState, GetChannelClampMode.
static variable DAP_AdaptAssocHeadstageState(string device, string checkboxCtrl)
Adapt the state of the associated headstage on DA/AD channel change.
References AFH_GetHeadstageFromADC, AFH_GetHeadstageFromDAC, ASSERT, CHANNEL_CONTROL_CHECK, CHANNEL_TYPE_ADC, CHANNEL_TYPE_DAC, CHANNEL_TYPE_HEADSTAGE, CHANNEL_TYPE_TTL, DAG_GetNumericalValue, DAP_AbortIfUnlocked, DAP_ParsePanelControl, GetHeadstageFromSettings, GetPanelControl, GetSpecialControlLabel, I_CLAMP_MODE, IsFinite, PGC_SetAndActivateControl, V_CLAMP_MODE, XOP_CHANNEL_TYPE_ADC, XOP_CHANNEL_TYPE_DAC.
Referenced by DAP_CheckProc_AD, DAP_DAorTTLCheckProc.
static variable DAP_GetRAAcquisitionCycleID(string device)
Return the repeated acquisition cycle ID for the given devide.
Follower and leader will have the same repeated acquisition cycle ID.
References DAP_AbortIfUnlocked, DeviceIsFollower, GetNextRandomNumberForDevice, ITC1600_FIRST_DEVICE.
Referenced by DAP_OneTimeCallBeforeDAQ.
variable DAP_OneTimeCallBeforeDAQ(string device, variable runMode)
One time initialization before data acquisition.
device device runMode One of DAQRunModes except DAQ_NOT_RUNNING
References AFH_GetDACFromHeadstage, ASSERT, CHANNEL_CONTROL_CHECK, CHANNEL_CONTROL_GAIN, CHANNEL_CONTROL_UNIT, CHANNEL_TYPE_ADC, CHANNEL_TYPE_DAC, CHANNEL_TYPE_HEADSTAGE, CONTROLS_DISABLE_DURING_DAQ, CONTROLS_DISABLE_DURING_DAQ_TP, CONTROLS_DISABLE_DURING_IDX, DAG_GetChannelState, DAG_GetNumericalValue, DAP_ClearDelayedClampModeChange, DAP_GetRAAcquisitionCycleID, DAP_ToggleAcquisitionButton, DAQ_NOT_RUNNING, DATA_ACQ_BUTTON_TO_STOP, DC_GotTPChannelWhileDAQ, DisableControl, DisableControls, GetHardwareType, GetPanelControl, GetSetEventFlag, GetStimsetAcqIDHelperWave, GUI_CONTROLSAVESTATE_DISABLED, HARDWARE_NI_DAC, HW_NI_ResetTaskIDs, IDX_CalculcateActiveSetCount, IDX_StoreStartFinishForIndexing, IsControlDisabled, NUM_HEADSTAGES, P_InitBeforeTP, P_SetAllHStoAtmospheric, PRE_SET_EVENT, RA_StepSweepsRemaining, SetControlUserData, TP_SetupCommon.
Referenced by DQM_StartDAQMultiDevice, DQS_StartDAQSingleDevice.
static variable DAP_ResetClampModeTitle(string device, string ctrl)
References SetControlTitle, SetControlTitleColor.
Referenced by DAP_ResetGUIAfterDAQ, DAP_SetAmpModeControls.
static variable DAP_ResetGUIAfterDAQ(string device)
Enable all controls which were disabled before DAQ by DAP_OneTimeCallBeforeDAQ.
References AFH_GetDACFromHeadstage, CHANNEL_CONTROL_CHECK, CHANNEL_CONTROL_GAIN, CHANNEL_CONTROL_UNIT, CHANNEL_TYPE_ADC, CHANNEL_TYPE_DAC, CHANNEL_TYPE_HEADSTAGE, CONTROLS_DISABLE_DURING_DAQ, CONTROLS_DISABLE_DURING_IDX, DAP_GetClampModeControl, DAP_HandleSingleDeviceDependentControls, DAP_ResetClampModeTitle, DAP_ToggleAcquisitionButton, DATA_ACQ_BUTTON_TO_DAQ, EnableControl, EnableControls, GetPanelControl, I_CLAMP_MODE, I_EQUAL_ZERO_MODE, IsFinite, NUM_HEADSTAGES, V_CLAMP_MODE.
Referenced by DAP_OneTimeCallAfterDAQ, DAP_UnlockDevice.
variable DAP_OneTimeCallAfterDAQ(string device, variable stopReason, variable forcedStop=defaultValue, variable startTPAfterDAQ=defaultValue)
One time cleaning up after data acquisition.
device device stopReason One of DAQStoppingFlags forcedStop [optional, defaults to false] if DAQ was aborted (true) or stopped by itself (false) startTPAfterDAQ [optional, defaults to true] start "TP after DAQ" if enabled at the end
References AS_HandlePossibleTransition, AS_INACTIVE, AS_POST_DAQ, ASSERT, DAG_GetNumericalValue, DAP_ApplyDelayedClampModeChange, DAP_DocumentStopReason, DAP_ResetGUIAfterDAQ, DAQ_NOT_RUNNING, DC_GotTPChannelWhileDAQ, DisableControl, GetHardwareType, GUI_CONTROLSAVESTATE_DISABLED, HARDWARE_NI_DAC, HW_NI_ResetTaskIDs, IDX_ResetStartFinishForIndexing, SetValDisplay, TP_TeardownCommon, TPM_StartTestPulseMultiDevice, TPS_StartTestPulseSingleDevice.
Referenced by DQ_StopOngoingDAQHelper, DQM_StartDAQMultiDevice, DQS_StartDAQSingleDevice, RA_ContinueOrStop, RA_FinishAcquisition.
static variable DAP_DocumentStopReason(string device, variable stopReason)
References AS_GetSweepNumber, ED_AddEntriesToLabnotebook, INDEP_HEADSTAGE, LABNOTEBOOK_LAYER_COUNT, LABNOTEBOOK_NO_TOLERANCE, UNKNOWN_MODE.
Referenced by DAP_OneTimeCallAfterDAQ.
variable DAP_CheckProc_IndexingState(WMCheckboxAction *cba)
References DAG_Update, DAP_UpdateDAQControls, EqualizeCheckBoxes, REASON_STIMSET_CHANGE, ToggleCheckBoxes.
variable DAP_CheckProc_ShowScopeWin(WMCheckboxAction *cba)
References DAG_Update, SCOPE_KillScopeWindowIfRequest, SCOPE_OpenScopeWindow.
static variable DAP_TurnOffAllChannels(string device, variable channelType)
References CHANNEL_CONTROL_CHECK, CHANNEL_INDEX_ALL, CHANNEL_TYPE_ADC, CHANNEL_TYPE_DAC, CHANNEL_TYPE_TTL, CHECKBOX_UNSELECTED, GetNumberFromType, GetPanelControl, PGC_SetAndActivateControl.
Referenced by DAP_ButtonProc_AllChanOff.
variable DAP_ButtonProc_AllChanOff(WMButtonAction *ba)
References CHANNEL_TYPE_ADC, CHANNEL_TYPE_DAC, CHANNEL_TYPE_HEADSTAGE, CHANNEL_TYPE_TTL, DAP_TurnOffAllChannels.
variable DAP_UpdateITIAcrossSets(string device, variable maxITI)
Update the ITI for the given device, takes care of handling yoked devices.
References DAG_GetNumericalValue, DAP_DeviceIsLeader, DAP_SyncGuiFromLeaderToFollower, DAP_UpdateITIAcrossSets, DeviceIsFollower, ITC1600_FIRST_DEVICE, PGC_SetAndActivateControl.
Referenced by DAP_UpdateITIAcrossSets, DQM_StartDAQMultiDevice.
variable DAP_PopMenuChkProc_StimSetList(WMPopupAction *pa)
Procedure for DA/TTL popupmenus including indexing wave popupmenus.
References ASSERT, CHANNEL_CONTROL_CHECK, CHANNEL_CONTROL_INDEX_END, CHANNEL_CONTROL_WAVE, DAG_GetNumericalValue, DAG_Update, DAP_AbortIfUnlocked, DAP_DACHasExpectedClampMode, DAP_IsAllControl, DAP_ParsePanelControl, DAP_UpdateDaEphysStimulusSetPopups, DAP_UpdateDAQControls, DQ_RestartDAQ, DQ_STOP_REASON_STIMSET_SELECTION, DQ_StopDAQ, GetNumberFromType, GetPanelControl, GetSpecialControlLabel, REASON_STIMSET_CHANGE, SetPopupMenuIndex, USER_DATA_MENU_EXP.
variable DAP_SetVarProc_DA_Scale(WMSetVariableAction *sva)
References ASSERT, DAG_Update, DAP_DACHasExpectedClampMode, DAP_IsAllControl, DAP_ParsePanelControl, GetNumberFromType, GetPanelControl, SetSetVariable, ShowSetVariableLimitsSelectionPopup.
variable DAP_SetVarProc_NextSweepLimit(WMSetVariableAction *sva)
References AFH_GetLastSweepAcquired, DAG_Update, DAP_SweepRollback, DAP_UpdateSweepLimitsAndDisplay, IsValidSweepNumber.
variable DAP_SweepRollback(string device, variable sweepNo, variable newSweepNo)
References ASSERT, ED_AddEntriesToLabnotebook, GetLBNumericalKeys, GetLBNumericalValues, GetLBTextualKeys, GetLBTextualValues, GetNumberFromWaveNote, INDEP_HEADSTAGE, LABNOTEBOOK_LAYER_COUNT, LABNOTEBOOK_ROLLBACK_COUNT, SetNumberInWaveNote, SWEEP_ROLLBACK_KEY, UNKNOWN_MODE.
Referenced by DAP_SetVarProc_NextSweepLimit.
static variable DAP_UpdateSweepLimitsAndDisplay(string device, variable initial=defaultValue)
References AFH_GetLastSweepAcquired, DAG_GetNumericalValue, DAG_Update, DAP_DeviceIsLeader, DeviceHasFollower, DeviceIsFollower, GetControlSettingVar, GetListofLeaderAndPossFollower, IsFinite, PGC_SetAndActivateControl, SetSetVariable.
Referenced by DAP_LockDevice, DAP_SetVarProc_NextSweepLimit, DAP_SyncGuiFromLeaderToFollower.
variable DAP_GetSampInt(string device, variable dataAcqOrTP, variable *valid=defaultValue)
Return the sampling interval with taking the mode, the multiplier and the fixed frequency selection into account.
device device dataAcqOrTP one of DataAcqModes valid [optional] returns if the choosen sampling interval is valid or not (DAQ only) SI_CalculateMinSampInterval()
References ASSERT, DAG_GetTextualValue, DATA_ACQUISITION_MODE, SI_CalculateMinSampInterval, TEST_PULSE_MODE.
Referenced by DAP_CheckSettings, DAP_UpdateDAQControls, DC_GetConfiguration, DC_GetDecimationFactor, DC_GetStopCollectionPoint, DC_PlaceDataInDAQConfigWave, DC_ReturnTotalLengthIncrease, SCOPE_CreateGraph, TP_UpdateTPSettingsCalculated.
variable DAP_UpdateSweepSetVariables(string device)
Tododisplay correct values for yoked devices
References DAG_GetNumericalValue, IDX_MaxNoOfSweeps, IDX_MaxSweepsLockedIndexing, SetValDisplay.
Referenced by DAP_CheckProc_RepeatedAcq, DAP_SetVarProc_TotSweepCount, DAP_UpdateDAQControls.
variable DAP_SetVarProc_TotSweepCount(WMSetVariableAction *sva)
References DAG_Update, DAP_SyncGuiFromLeaderToFollower, DAP_UpdateSweepSetVariables.
variable DAP_ButtonCtrlFindConnectedAmps(WMButtonAction *ba)
References AI_FindConnectedAmps.
string DAP_GetNiceAmplifierChannelList()
Return a nicely layouted list of amplifier channels.
References ControlWindowToFront, DAP_GetAmplifierDef, GetAmplifierTelegraphServers, NONE, ROWS.
Referenced by CONF_FindAmpInList, DAP_UpdateChanAmpAssignPanel.
string DAP_GetAmplifierDef(variable ampSerial, variable ampChannel)
References AMPLIFIER_DEF_FORMAT.
Referenced by DAP_CheckSettings, DAP_GetNiceAmplifierChannelList, DAP_UpdateChanAmpAssignPanel.
variable DAP_ParseAmplifierDef(string amplifierDef, variable *ampSerial, variable *ampChannelID)
Parse the entries which DAP_GetAmplifierDef() created.
References AMPLIFIER_DEF_FORMAT, ASSERT, NONE.
Referenced by CONF_FindAmpInList, DAP_UpdateChanAmpAssignStorWv.
variable DAP_SyncDeviceAssocSettToGUI(string device, variable headStage)
References DAP_AbortIfUnlocked, DAP_UpdateChanAmpAssignPanel, P_UpdatePressureControls.
Referenced by DAP_LockDevice, DAP_PopMenuProc_Headstage.
variable DAP_PopMenuProc_Headstage(WMPopupAction *pa)
References DAG_Update, DAP_SyncDeviceAssocSettToGUI.
variable DAP_PopMenuProc_CAA(WMPopupAction *pa)
References DAP_AbortIfUnlocked, DAP_UpdateChanAmpAssignStorWv, P_UpdatePressureDataStorageWv.
variable DAP_SetVarProc_CAA(WMSetVariableAction *sva)
References DAG_Update, DAP_AbortIfUnlocked, DAP_UpdateChanAmpAssignStorWv, P_UpdatePressureDataStorageWv, ShowSetVariableLimitsSelectionPopup.
variable DAP_ButtonProc_ClearChanCon(WMButtonAction *ba)
References DAP_AbortIfUnlocked, DAP_UpdateChanAmpAssignPanel, GetChanAmpAssign, GetPopupMenuString.
static variable DAP_CheckSettingsAcrossYoked(string listOfFollowerDevices, variable mode)
Check the settings across yoked devices.
References ASSERT, ControlWindowToFront, GetGuiControlValue, GetValDisplayAsString, IsControlDisabled, ITC1600_FIRST_DEVICE, PGC_SetAndActivateControl, ROWS, TEST_PULSE_MODE, WindowExists, YOKE_CONTROLS_DISABLE_AND_LINK.
Referenced by DAP_CheckSettings.
variable DAP_CheckSettings(string device, variable mode)
Check if all settings are valid to send a test pulse or acquire data.
For invalid settings an informative message is printed into the history area. Callers must ensure to set the acquisition state back to AS_INACTIVE when calling with DATA_ACQUISITION_MODE. device device mode One of DataAcqModes 0 for valid settings, 1 for invalid settings
References AFH_GetDACFromHeadstage, AFH_GetHeadstageFromDAC, AFM_UpdateAnalysisFunctionWave, AS_EARLY_CHECK, AS_HandlePossibleTransition, AS_PRE_DAQ, ASSERT, BUG, ChangeWaveLock, CHANNEL_CONTROL_ALARM_MAX, CHANNEL_CONTROL_ALARM_MIN, CHANNEL_CONTROL_CHECK, CHANNEL_CONTROL_GAIN, CHANNEL_CONTROL_WAVE, CHANNEL_TYPE_ADC, CHANNEL_TYPE_ALARM, CHANNEL_TYPE_ASYNC, CHANNEL_TYPE_DAC, CHANNEL_TYPE_HEADSTAGE, CHANNEL_TYPE_TTL, ControlWindowToFront, DA_EPHYS_PANEL_VERSION, DAG_GetChannelState, DAG_GetChannelTextual, DAG_GetHeadstageMode, DAG_GetNumericalValue, DAG_GetTextualValue, DAP_CheckAnalysisFunctionAndParameter, DAP_CheckHeadStage, DAP_CheckPressureSettings, DAP_CheckSettingsAcrossYoked, DAP_CheckStimset, DAP_DeviceIsUnlocked, DAP_GetAmplifierDef, DAP_GetSampInt, DATA_ACQUISITION_MODE, DateTimeInUTC, DC_GetFilteredChannelState, DC_GotTPChannelWhileDAQ, DEBUGPRINT, DeviceHasFollower, GetChanAmpAssign, GetDAQDataWave, GetDrive, GetHardwareType, GetLastSettingTextIndep, GetLastSweepWithSettingIndep, GetLBNumericalValues, GetLBTextualValues, GetListOfLockedDevices, GetLockState, GetSpecialControlLabel, GetValDisplayAsNum, HARDWARE_NI_DAC, HARDWARE_PREVENT_ERROR_MESSAGE, HARDWARE_PREVENT_ERROR_POPUP, HasEnoughDiskspaceFree, HasPanelLatestVersion, HIGH_PREC_SWEEP_START_KEY, HW_ITC_CalculateDevChannelOff, HW_SelectDevice, I_CLAMP_MODE, I_EQUAL_ZERO_MODE, IDX_GetSetsInRange, isEmpty, IsEmpty, IsFinite, MINIMUM_FREE_DISK_SPACE, NUM_ASYNC_CHANNELS, NUM_HEADSTAGES, NWB_PrepareExport, ParseISO8601TimeStamp, ROWS, SearchForDuplicates, STIMSET_TP_WHILE_DAQ, SWS_DeleteDataWaves, TEST_PULSE_MODE, V_CLAMP_MODE.
Referenced by DAP_ButtonProc_TPDAQ, TPM_StartTestPulseMultiDevice, TPS_StartTestPulseSingleDevice.
static variable DAP_CheckPressureSettings(string device)
References ControlWindowToFront, GetHardwareType, GetPopupMenuString, HARDWARE_NI_DAC, HW_NI_AnalogInputToString, HW_NI_CONFIG_DIFFERENTIAL, HW_NI_GetAnalogInputConfig, NONE.
Referenced by DAP_CheckSettings.
static variable DAP_CheckHeadStage(string device, variable headStage, variable mode)
Returns zero if everything is okay, 1 if a non-recoverable error was found and 2 on recoverable errors.
References AFH_GetHeadstageFromADC, AFH_GetHeadstageFromDAC, AI_EnsureCorrectMode, AI_IsValidClampMode, AI_QueryGainsUnitsForClampMode, AI_SelectMultiClamp, AI_UpdateChanAmpAssign, AMPLIFIER_CONNECTION_MCC_FAILED, AMPLIFIER_CONNECTION_SUCCESS, CHANNEL_CONTROL_GAIN, CHANNEL_CONTROL_SCALE, CHANNEL_CONTROL_UNIT, CHANNEL_TYPE_ADC, CHANNEL_TYPE_DAC, CheckIfClose, CheckIfSmall, COLS, ControlWindowToFront, ConvertAmplifierModeToString, DAG_GetHeadstageMode, DAG_GetNumericalValue, DAG_GetTextualValue, DAP_ApplyClmpModeSavdSettngs, DAP_CheckStimset, DAP_DeviceIsUnlocked, DAP_SyncChanAmpAssignToActiveHS, DAP_UpdateChanAmpAssignPanel, DATA_ACQUISITION_MODE, GetChanAmpAssign, GetChanAmpAssignUnit, GetChannelClampMode, GetHardwareType, GetSpecialControlLabel, HARDWARE_NI_DAC, HW_NI_AnalogInputToString, HW_NI_CONFIG_DIFFERENTIAL, HW_NI_GetAnalogInputConfig, I_CLAMP_MODE, I_EQUAL_ZERO_MODE, isEmpty, IsFinite, V_CLAMP_MODE.
Referenced by DAP_CheckSettings.
static variable DAP_CheckAnalysisFunctionAndParameter(string device, string setName)
References AFH_CheckAnalysisParameter, AFH_GetAnalysisFunctions, AFH_GetAnalysisParamTextWave, AFH_GetAnalysisParamType, AFH_GetAnalysisParamWave, AFH_GetListOfAnalysisParamNames, AFH_GetListOfAnalysisParams, AFH_IsValidAnalysisParameter, ANALYSIS_FUNCTION_PARAMS_TYPES, ANALYSIS_FUNCTION_VERSION_ALL, ControlWindowToFront, DAG_GetNumericalValue, EVENT_NAME_LIST, ExtractAnalysisFuncFromStimSet, ExtractAnalysisFunctionParams, FuncRefIsAssigned, GENERIC_EVENT, GetListDifference, isEmpty, IsEmpty, MID_SWEEP_EVENT, CheckParametersStruct::params, REQUIRED_PARAMS, ROWS, STIMSET_TP_WHILE_DAQ, TOTAL_NUM_EVENTS, WB_CreateAndGetStimSet.
Referenced by DAP_CheckSettings, DAP_CheckStimset.
static variable DAP_CheckStimset(string device, variable channelType, variable channel, variable headstage)
References ASSERT, CHANNEL_CONTROL_INDEX_END, CHANNEL_CONTROL_WAVE, CHANNEL_TYPE_DAC, CHANNEL_TYPE_TTL, ControlWindowToFront, DAG_GetNumericalValue, DAG_GetTextualValue, DAP_CheckAnalysisFunctionAndParameter, DEBUGPRINT, GetSpecialControlLabel, IDX_GetSetsInRange, NONE, ROWS, STIMSET_TP_WHILE_DAQ, WAVEBUILDER_MIN_SAMPINT, WB_CreateAndGetStimSet.
Referenced by DAP_CheckHeadStage, DAP_CheckSettings.
static variable DAP_SyncChanAmpAssignToActiveHS(string device)
Synchronizes the contents of ChanAmpAssign and ChanAmpAssignUnit to all active headstages.
References CHANNEL_TYPE_HEADSTAGE, DAG_GetChannelState, DAG_GetHeadstageMode, DAP_ApplyClmpModeSavdSettngs, NUM_HEADSTAGES.
Referenced by DAP_ButtonProc_AutoFillGain, DAP_CheckHeadStage.
static variable DAP_ApplyClmpModeSavdSettngs(string device, variable headStage, variable clampMode)
Reads the channel amp waves and inserts that info into the DA_EPHYS panel.
References CHANNEL_CONTROL_CHECK, CHANNEL_CONTROL_GAIN, CHANNEL_CONTROL_UNIT, CHANNEL_TYPE_ADC, CHANNEL_TYPE_DAC, CHECKBOX_SELECTED, GetChanAmpAssign, GetChanAmpAssignUnit, GetChannelClampMode, GetDA_EphysGuiStateNum, GetDA_EphysGuiStateTxT, GetPanelControl, I_CLAMP_MODE, I_EQUAL_ZERO_MODE, IsFinite, SetCheckBoxState, SetSetVariable, SetSetVariableString, V_CLAMP_MODE.
Referenced by DAP_ChangeHeadstageState, DAP_CheckHeadStage, DAP_SetHeadstageChanControls, DAP_SyncChanAmpAssignToActiveHS.
static variable DAP_RemoveClampModeSettings(string device, variable headStage, variable clampMode)
References CHANNEL_CONTROL_CHECK, CHANNEL_TYPE_ADC, CHANNEL_TYPE_DAC, CHECKBOX_UNSELECTED, GetChanAmpAssign, GetChannelClampMode, GetDA_EphysGuiStateNum, GetPanelControl, I_CLAMP_MODE, I_EQUAL_ZERO_MODE, IsFinite, SetCheckBoxState, V_CLAMP_MODE.
Referenced by DAP_ChangeHeadstageState, DAP_SetHeadstageChanControls.
string DAP_GetClampModeControl(variable mode, variable headstage)
Returns the name of the checkbox control (radio button) handling the clamp mode of the given headstage or all headstages.
mode One of the amplifier modes AmplifierClampModes headstage number of the headstage or one of AllHeadstageModeConstants
References ASSERT, CHANNEL_INDEX_ALL_I_ZERO, I_CLAMP_MODE, I_EQUAL_ZERO_MODE, NUM_HEADSTAGES, V_CLAMP_MODE.
Referenced by DAP_ChangeHeadstageState, DAP_GetInfoFromControl, DAP_ResetGUIAfterDAQ, DAP_SetAmpModeControls, IVS_ConfigureMCC, setIClampMode, setVClampMode.
variable DAP_GetInfoFromControl(string device, string ctrl, variable *mode, variable *headStage)
Return information readout from headstage and clamp mode controls.
Users interested in the clamp mode of a known headstage should prefer DAG_GetHeadstageMode() instead. device panel ctrl control can be either Radio_ClampMode_* or Check_DataAcqHS_* referring to an existing control mode I_CLAMP_MODE, V_CLAMP_MODE or I_EQUAL_ZERO_MODE, the currently active mode for headstage controls and the clamp mode of the control for clamp mode controls headStage number of the headstage or one of AllHeadstageModeConstants
References AI_AssertOnInvalidClampMode, ASSERT, CHANNEL_INDEX_ALL_I_CLAMP, CHANNEL_INDEX_ALL_I_ZERO, CHANNEL_INDEX_ALL_V_CLAMP, DAP_GetClampModeControl, GetCheckBoxState, I_CLAMP_MODE, I_EQUAL_ZERO_MODE, isEmpty, IsEven, IsFinite, V_CLAMP_MODE.
Referenced by DAG_GetAllHSMode, DAP_CheckProc_ClampMode.
variable DAP_CheckProc_ClampMode(WMCheckboxAction *cba)
References AssertOnAndClearRTError, ClearRTError, DAP_ChangeHeadStageMode, DAP_GetInfoFromControl, DAP_SetAmpModeControls, DAQ_NOT_RUNNING, DO_MCC_MIES_SYNCING, GetDA_EphysGuiStateNum, SetCheckBoxState.
variable DAP_CheckProc_HedstgeChck(WMCheckboxAction *cba)
References AssertOnAndClearRTError, ClearRTError, DAG_Update, DAP_ChangeHeadstageState, SetCheckBoxState.
variable DAP_ChangeHeadStageMode(string device, variable clampMode, variable headstage, variable options)
Change the clamp mode of the given headstage.
device Device clampMode Clamp mode to activate headstage Headstage [0, 8[ or use one of AllHeadstageModeConstants options One of ClampModeChangeOptions
References AI_AssertOnInvalidClampMode, AI_SetClampMode, ASSERT, ConvertAmplifierModeToString, DAG_GetHeadstageState, DAG_GetNumericalValue, DAP_AbortIfUnlocked, DAP_PublishClampModeChange, DAP_SetAmpModeControls, DAP_SetHeadstageChanControls, DAP_UpdateDAQControls, DO_MCC_MIES_SYNCING, GetChanAmpAssign, GetDA_EphysGuiStateNum, GetTabID, I_CLAMP_MODE, I_EQUAL_ZERO_MODE, IsFinite, MCC_SKIP_UPDATES, NO_SLIDER_MOVEMENT, NUM_HEADSTAGES, PGC_SetAndActivateControl, REASON_HEADSTAGE_CHANGE, TP_RestartTestPulse, TP_StopTestPulse, V_CLAMP_MODE.
Referenced by AI_UpdateAmpModel, CONF_GetAmplifierSettings, CONF_RestoreAmplifierSettings, DAP_ApplyDelayedClampModeChange, DAP_CheckProc_ClampMode.
static variable DAP_PublishClampModeChange(string device, variable headstage, variable oldClampMode, variable newClampMode)
References AMPLIFIER_CLAMP_MODE_FILTER, ConvertAmplifierModeToString, FFI_GetJSONTemplate, FFI_Publish.
Referenced by DAP_ChangeHeadStageMode.
static variable DAP_SetAmpModeControls(string device, variable headstage, variable clampMode, variable delayed=defaultValue)
Sets the control state of the radio buttons used for setting the clamp mode on the Data Acquisition Tab of the DA_Ephys panel.
device device headstage controls associated with headstage are set clampMode clamp mode to activate delayed indicate on the control that the change is delayed
References CHECKBOX_SELECTED, CHECKBOX_UNSELECTED, DAP_GetClampModeControl, DAP_ResetClampModeTitle, I_CLAMP_MODE, I_EQUAL_ZERO_MODE, SetControlTitle, SetControlTitleColor, V_CLAMP_MODE.
Referenced by DAP_ChangeHeadStageMode, DAP_CheckProc_ClampMode.
static variable DAP_SetHeadstageChanControls(string device, variable headstage, variable clampMode, variable delayed=defaultValue)
Sets the DA and AD channel settings according to the headstage mode.
device Device (used for data acquisition) headstage Channels associated with headstage are set clampMode Clamp mode to activate delayed [optional, defaults to false] Indicate that this is a delayed clamp mode change
References DAG_GetHeadstageState, DAP_AllChanDASettings, DAP_ApplyClmpModeSavdSettngs, DAP_RemoveClampModeSettings, I_CLAMP_MODE, I_EQUAL_ZERO_MODE, V_CLAMP_MODE.
Referenced by DAP_ChangeHeadStageMode.
static variable DAP_UpdateClampmodeTabs(string device, variable headStage, variable clampMode)
References AI_AssertOnInvalidClampMode, AI_SyncAmpStorageToGUI, AI_SyncGUIToAmpStorageAndMCCApp, DAG_GetNumericalValue, I_CLAMP_MODE, I_EQUAL_ZERO_MODE, PGC_SetAndActivateControl, V_CLAMP_MODE.
Referenced by DAP_SliderProc_MIESHeadStage.
static variable DAP_ChangeHeadstageState(string device, string headStageCtrl, variable enabled)
References ASSERT, CHANNEL_CONTROL_CHECK, CHANNEL_TYPE_HEADSTAGE, CHECKBOX_SELECTED, DAG_GetChannelState, DAG_GetNumericalValue, DAP_AbortIfUnlocked, DAP_ApplyClmpModeSavdSettngs, DAP_GetClampModeControl, DAP_ParsePanelControl, DAP_RemoveClampModeSettings, DAP_UpdateDAQControls, GetCheckBoxState, GetDA_EphysGuiStateNum, GetPanelControl, I_CLAMP_MODE, I_EQUAL_ZERO_MODE, NUM_HEADSTAGES, P_SetPressureMode, P_UpdatePressureType, PGC_SetAndActivateControl, PRESSURE_METHOD_ATM, REASON_HEADSTAGE_CHANGE, REASON_STIMSET_CHANGE, SetCheckBoxState, TP_RestartTestPulse, TP_StopTestPulse, V_CLAMP_MODE.
Referenced by DAP_CheckProc_HedstgeChck.
variable DAP_ToggleAcquisitionButton(string device, variable mode)
Set the acquisition button text.
device device mode One of ToggleAcquisitionButtonConstants
References ASSERT, DATA_ACQ_BUTTON_TO_DAQ, DATA_ACQ_BUTTON_TO_STOP.
Referenced by DAP_LockDevice, DAP_OneTimeCallBeforeDAQ, DAP_ResetGUIAfterDAQ.
variable DAP_ToggleTestpulseButton(string device, variable mode)
Set the testpulse button text.
device device mode One of ToggleTestpulseButtonConstants
References ASSERT, TESTPULSE_BUTTON_TO_START, TESTPULSE_BUTTON_TO_STOP.
Referenced by DAP_UnlockDevice, TP_Setup, TP_Teardown.
string DAP_ListOfITCDevices()
Returns the list of potential followers for yoking. Used by popup_Hardware_AvailITC1600s from the hardware tab
References GetListOfLockedITC1600Devices, ITC1600_FIRST_DEVICE.
variable DAP_ButtonProc_Lead(WMButtonAction *ba)
The Lead button in the yoking controls sets the attached ITC1600 as the device that will trigger all the other devices yoked to it.
References ASSERT, createDFWithAllParents, DeviceCanLead, DisableControl, EnableControls, LEADER, PGC_SetAndActivateControl.
variable DAP_ButtonProc_Independent(WMButtonAction *ba)
References DAP_RemoveAllYokedDACs, DAP_UpdateAllYokeControls, DisableControls, EnableControl, PGC_SetAndActivateControl.
variable DAP_ButtonProc_Follow(WMButtonAction *ba)
References ASSERT, DAP_SetITCDACasFollower, DAP_UpdateFollowerControls, DisableControls, EnableControl, ITC1600_FIRST_DEVICE, PGC_SetAndActivateControl, YOKE_CONTROLS_DISABLE, YOKE_CONTROLS_DISABLE_AND_LINK.
static variable DAP_SyncGuiFromLeaderToFollower(string device)
References DAP_DeviceIsLeader, DAP_UpdateSweepLimitsAndDisplay, GetGuiControlValue, GetListofLeaderAndPossFollower, SetGuiControlValue, YOKE_CONTROLS_DISABLE_AND_LINK.
Referenced by DAP_CheckProc_RepeatedAcq, DAP_CheckProc_SyncCtrl, DAP_SetVarProc_SyncCtrl, DAP_SetVarProc_TotSweepCount, DAP_UpdateITIAcrossSets.
variable DAP_ButtonProc_YokeRelease(WMButtonAction *ba)
References DAP_RemoveYokedDAC, DAP_UpdateYokeControls.
variable DAP_RemoveYokedDAC(string panelToDeYoke)
References DisableControl, EnableControls, HARDWARE_ITC_DAC, HW_DisableYoking, ITC1600_FIRST_DEVICE, PGC_SetAndActivateControl, YOKE_CONTROLS_DISABLE, YOKE_CONTROLS_DISABLE_AND_LINK.
Referenced by DAP_ButtonProc_YokeRelease, DAP_RemoveAllYokedDACs, DAP_UnlockDevice.
variable DAP_RemoveAllYokedDACs(string device)
References DAP_RemoveYokedDAC, ITC1600_FIRST_DEVICE.
Referenced by DAP_ButtonProc_Independent.
variable DAP_UpdateFollowerControls(string device, string panelToYoke)
Sets the lists and buttons on the follower device actively being yoked.
References DAP_UpdateYokeControls, EnableControl, FOLLOWER, PGC_SetAndActivateControl.
Referenced by DAP_ButtonProc_Follow.
variable DAP_ButtonProc_AutoFillGain(WMButtonAction *ba)
References AI_QueryGainsFromMCC, DAP_AbortIfUnlocked, DAP_SyncChanAmpAssignToActiveHS, DAP_UpdateChanAmpAssignPanel.
variable DAP_SliderProc_MIESHeadStage(WMSliderAction *sc)
References DAG_GetHeadstageMode, DAG_Update, DAP_AbortIfUnlocked, DAP_TPSettingsToGUI, DAP_UpdateClampmodeTabs, P_GetAutoUserOff, P_LoadPressureButtonState, P_PressureDisplayHighlite, P_RunP_ControlIfTPOFF, P_SaveUserSelectedHeadstage, P_UpdatePressureModeTabs, P_UpdatePressureType, SCOPE_SetADAxisLabel, UNKNOWN_MODE.
variable DAP_SetVarProc_AmpCntrls(WMSetVariableAction *sva)
References AI_UpdateAmpModel, DAG_GetNumericalValue, DAG_Update.
variable DAP_ButtonProc_AmpCntrls(WMButtonAction *ba)
References AI_UpdateAmpModel, DAG_GetNumericalValue.
variable DAP_CheckProc_AmpCntrls(WMCheckboxAction *cba)
References AI_UpdateAmpModel, DAG_GetNumericalValue, DAG_Update.
variable DAP_CheckProc_MDEnable(WMCheckboxAction *cba)
Check box procedure for multiple device (MD) support.
References AdaptDependentControls, DAG_Update.
variable DAP_HandleSingleDeviceDependentControls(string device)
Enable controls post DAQ/TP in single device mode.
device device
References ASSERT, CONTROLS_DISABLE_DURING_DAQ_TP, DAG_GetNumericalValue, EnableControls.
Referenced by DAP_ResetGUIAfterDAQ, TP_Teardown.
variable DAP_CheckProc_InsertTP(WMCheckBoxAction *cba)
Controls TP Insertion into set sweeps before the sweep begins.
References DAG_Update, DAP_UpdateOnsetDelay.
variable DAP_UpdateOnsetDelay(string device)
Update the onset delay due to the Insert TP setting.
References DAG_GetNumericalValue, SetValDisplay, TP_CalculateTestPulseLength.
Referenced by DAP_CheckProc_InsertTP, DAP_LockDevice, DAP_TPGUISettingToWave.
variable DAP_SetVarProc_TestPulseSett(WMSetVariableAction *sva)
References DAG_Update, DAP_AbortIfUnlocked, DAP_TPGUISettingToWave.
variable DAP_CheckProc_TestPulseSett(WMCheckboxAction *cba)
References DAG_Update, DAP_AbortIfUnlocked, DAP_TPGUISettingToWave.
variable DAP_AdaptAutoTPColorAndDependent(string device)
References AdaptDependentControls, CHECKBOX_SELECTED, CHECKBOX_UNSELECTED, GetTestpulseRunMode, IsControlDisabled, TEST_PULSE_DURING_RA_MOD, TEST_PULSE_NOT_RUNNING, TP_AutoTPActive.
Referenced by DAP_TPGUISettingToWave, TP_Setup, TP_Teardown.
variable DAP_UnlockAllDevices()
References DAP_UnlockDevice, GetListOfLockedDevices, ITC1600_FIRST_DEVICE.
Referenced by IH_Cleanup, MEN_CloseMies.
variable DAP_CheckProc_RepeatedAcq(WMCheckboxAction *cba)
References DAG_Update, DAP_SyncGuiFromLeaderToFollower, DAP_UpdateSweepSetVariables.
static variable DAP_ToggleCheckBoxes(string win, string ctrl, string list, variable checked)
Allows two checkboxes to be treated as a group where only one can be checked at a time.
Write into the GUI state wave as well
References ASSERT, DAG_Update, IsEmpty, SetCheckBoxState.
Referenced by DAP_CheckProc_SyncCtrl.
variable DAP_CheckProc_SyncCtrl(WMCheckboxAction *cba)
References DAG_Update, DAP_SyncGuiFromLeaderToFollower, DAP_ToggleCheckBoxes.
variable DAP_SetVarProc_SyncCtrl(WMSetVariableAction *sva)
References DAG_Update, DAP_SyncGuiFromLeaderToFollower.
variable DAP_ButtonProc_TPDAQ(WMButtonAction *ba)
References AS_HandlePossibleTransition, AS_INACTIVE, ASSERT, DAG_GetNumericalValue, DAP_AbortIfUnlocked, DAP_CheckSettings, DAQ_NOT_RUNNING, DATA_ACQUISITION_MODE, DQ_STOP_REASON_DAQ_BUTTON, DQ_StopDAQ, DQM_StartDAQMultiDevice, DQS_StartDAQSingleDevice, TP_CheckIfTestpulseIsRunning, TP_RestartTestPulse, TP_StopTestPulse, TPM_StartTestPulseMultiDevice, TPS_StartTestPulseSingleDevice.
string DAP_GetCommentPanel(string device)
Return the comment panel name.
References COMMENT_PANEL.
Referenced by DAP_ClearCommentNotebook, DAP_GetCommentNotebook, DAP_LockCommentNotebook, DAP_OpenCommentPanel, DAP_SerializeCommentNotebook, DAP_UnlockCommentNotebook.
string DAP_GetCommentNotebook(string device)
Return the full window path to the comment notebook.
References COMMENT_PANEL_NOTEBOOK, DAP_GetCommentPanel.
Referenced by DAP_AddUserComment, DAP_ClearCommentNotebook, DAP_FormatCommentString, DAP_LockCommentNotebook, DAP_OpenCommentPanel, DAP_SerializeCommentNotebook, DAP_UnlockCommentNotebook, DeviceHasUserComments.
static variable DAP_OpenCommentPanel(string device)
Create the comment panel.
References DAP_AbortIfUnlocked, DAP_GetCommentNotebook, DAP_GetCommentPanel, ReplaceNotebookText.
Referenced by DAP_AddUserComment, DAP_ButtonProc_OpenCommentNB, DAP_FormatCommentString.
variable DAP_ButtonProc_OpenCommentNB(WMButtonAction *ba)
References DAP_AddUserComment, DAP_OpenCommentPanel.
static string DAP_FormatCommentString(string device, string comment, variable sweepNo)
References ASSERT, DAP_GetCommentNotebook, DAP_OpenCommentPanel, GetNotebookText, GetTimeStamp, IsEmpty, IsNaN.
Referenced by DAP_AddUserComment.
static variable DAP_AddUserComment(string device)
Add the current user comment of the previous sweep to the comment notebook and to the labnotebook.
The SetVariable for the user comment is also cleared
References AFH_GetLastSweepAcquired, AppendToNotebookText, DAG_GetTextualValue, DAP_FormatCommentString, DAP_GetCommentNotebook, DAP_OpenCommentPanel, ED_WriteUserCommentToLabNB, isEmpty, NotebookSelectionAtEnd, PGC_SetAndActivateControl, WindowExists.
Referenced by DAP_ButtonProc_OpenCommentNB, DAP_SerializeCommentNotebook.
variable DAP_LockCommentNotebook(string device)
Make the comment notebook read-only.
References COMMENT_PANEL, DAP_GetCommentNotebook, DAP_GetCommentPanel.
Referenced by DAP_UnlockDevice.
variable DAP_UnlockCommentNotebook(string device)
Make the comment notebook writeable.
References COMMENT_PANEL, DAP_GetCommentNotebook, DAP_GetCommentPanel.
Referenced by DAP_LockDevice.
variable DAP_ClearCommentNotebook(string device)
Clear the comment notebook's content and the serialized string.
References DAP_GetCommentNotebook, DAP_GetCommentPanel, ReplaceNotebookText.
Referenced by SaveExperimentSpecial.
variable DAP_SerializeAllCommentNBs()
Serialize all comment notebooks.
References CallFunctionForEachListItem, DAP_SerializeCommentNotebook, GetListOfLockedDevices.
Referenced by BeforeExperimentSaveHook.
variable DAP_SerializeCommentNotebook(string device)
Copy the contents of the comment notebook to the user comment string.
References DAP_AddUserComment, DAP_GetCommentNotebook, DAP_GetCommentPanel, GetNotebookText, isEmpty, NotebookSelectionAtEnd.
Referenced by DAP_CommentPanelHook, DAP_SerializeAllCommentNBs, DAP_UnlockDevice, NWB_AppendSweepDuringDAQ, NWB_ExportAllData.
variable DAP_CommentPanelHook(WMWinHookStruct *s)
References DAP_DeviceIsUnlocked, DAP_SerializeCommentNotebook, GetMainWindow.
string DAP_CreateDAEphysPanel()
Create a new DA_Ephys panel.
panel name
References AddVersionToPanel, CreateHistoryNotebook, DA_EPHYS_PANEL_VERSION, DAP_GetITCDeviceList, DAP_GetNIDeviceList, GetCurrentWindow, GetDAQDevicesFolder, panel, PS_InitCoordinates, SCOPE_OpenScopeWindow, WindowExists.
Referenced by CONF_RestoreDAEphys, ScreenShotsForDAEphys.
variable DAP_CheckProc_LockedLogic(WMCheckboxAction *cba)
Sets the locked indexing logic checkbox states.
References DAG_GetNumericalValue, DAG_Update, EqualizeCheckBoxes, PGC_SetAndActivateControl, ToggleCheckBoxes.
variable DAP_ParsePanelControl(string ctrl, variable *channelIndex, variable *channelType, variable *controlType)
Extracts channelType, controlType and channelIndex from ctrl
Counterpart to GetPanelControl() 0 if the control name could be parsed, one otherwise
References CHANNEL_CONTROL_ALARM_MAX, CHANNEL_CONTROL_ALARM_MIN, CHANNEL_CONTROL_CHECK, CHANNEL_CONTROL_GAIN, CHANNEL_CONTROL_INDEX_END, CHANNEL_CONTROL_SCALE, CHANNEL_CONTROL_SEARCH, CHANNEL_CONTROL_TITLE, CHANNEL_CONTROL_UNIT, CHANNEL_CONTROL_WAVE, CHANNEL_INDEX_ALL, CHANNEL_INDEX_ALL_I_CLAMP, CHANNEL_INDEX_ALL_V_CLAMP, CHANNEL_TYPE_ADC, CHANNEL_TYPE_ALARM, CHANNEL_TYPE_ASYNC, CHANNEL_TYPE_DAC, CHANNEL_TYPE_HEADSTAGE, CHANNEL_TYPE_TTL, isEmpty, IsFinite, str2numSafe.
Referenced by DAG_GetUniqueCtrlList, DAG_Update, DAP_AdaptAssocHeadstageState, DAP_ChangeHeadstageState, DAP_CheckProc_Channel_All, DAP_PopMenuChkProc_StimSetList, DAP_SetVarProc_Channel_Search, DAP_SetVarProc_DA_Scale.
variable DAP_UpdateListOfPressureDevices()
Update the list of available pressure devices on all locked device panels.
References GetListOfLockedDevices, PGC_SetAndActivateControl.
Referenced by DAP_LockDevice.
variable DAP_DeviceIsUnlocked(string device)
Query the device lock status.
device lock status, 1 if unlocked, 0 if locked
References GetListOfLockedDevices.
Referenced by DAP_AbortIfUnlocked, DAP_CheckHeadStage, DAP_CheckSettings, DAP_CommentPanelHook, DAP_UnlockDevice, DQ_ApplyAutoBias, P_PressureControl.
variable DAP_AbortIfUnlocked(string device)
References DAP_DeviceIsUnlocked, DoAbortNow.
Referenced by AI_SyncGUIToAmpStorageAndMCCApp, AI_UpdateAmpModel, AI_UpdateAmpView, DAP_AdaptAssocHeadstageState, DAP_ButtonProc_AutoFillGain, DAP_ButtonProc_ClearChanCon, DAP_ButtonProc_TPDAQ, DAP_ChangeHeadStageMode, DAP_ChangeHeadstageState, DAP_CheckProc_Settings_PUser, DAP_CheckProc_TestPulseSett, DAP_GetRAAcquisitionCycleID, DAP_OpenCommentPanel, DAP_PopMenuChkProc_StimSetList, DAP_PopMenuProc_CAA, DAP_SetVarProc_CAA, DAP_SetVarProc_TestPulseSett, DAP_SliderProc_MIESHeadStage, DAP_SyncDeviceAssocSettToGUI, P_ButtonProc_Enable, P_ButtonProc_UserPressure, P_Check_ApproachNear, P_Check_SealAtm, TP_GetTPCycleID.
variable DAP_CheckProc_UpdateGuiState(WMCheckboxAction *cba)
GUI procedure which has the only purpose of storing the control state in the GUI state wave.
References DAG_Update.
variable DAP_SetVar_SetScale(WMSetVariableAction *sva)
References DAG_Update, ShowSetVariableLimitsSelectionPopup.
variable DAP_SetVar_UpdateGuiState(WMSetVariableAction *sva)
References DAG_Update.
variable DAP_CheckProc_Settings_PUser(WMCheckboxAction *cba)
References DAG_Update, DAP_AbortIfUnlocked, P_GetPressureDataWaveRef, P_GetUserAccess, P_RunP_ControlIfTPOFF, P_SetPressureValves, P_UpdatePressureType, P_ValidatePressureSetHeadstage.
variable DAP_ButtonProc_LockDev(WMButtonAction *ba)
References DAP_LockDevice.
variable DAP_ButProc_Hrdwr_UnlckDev(WMButtonAction *ba)
References DAP_UnlockDevice.
static variable DAP_UpdateDataFolderDisplay(string device, variable locked)
References GetDevicePathAsString.
Referenced by DAP_LockDevice, DAP_UnlockDevice.
variable DAP_LockDevice(string win)
References AI_FindConnectedAmps, AS_INACTIVE, ControlWindowToFront, DA_EPHYS_PANEL_VERSION, DAG_RecordGuiStateNum, DAG_RecordGuiStateTxT, DAP_AdaptPanelForDeviceSpecifics, DAP_LoadBuiltinStimsets, DAP_SyncDeviceAssocSettToGUI, DAP_ToggleAcquisitionButton, DAP_TPSettingsToWave, DAP_UnlockCommentNotebook, DAP_UpdateAllYokeControls, DAP_UpdateDaEphysStimulusSetPopups, DAP_UpdateDAQControls, DAP_UpdateDataFolderDisplay, DAP_UpdateListOfLockedDevices, DAP_UpdateListOfPressureDevices, DAP_UpdateOnsetDelay, DAP_UpdateSweepLimitsAndDisplay, DATA_ACQ_BUTTON_TO_DAQ, DATA_ACQUISITION_MODE, DateTimeInUTC, DEBUGPRINT_OR_ABORT, DisableControls, DoAbortNow, EnableControl, GetAmplifierParamStorageWave, GetDA_EphysGuiStateNum, GetDA_EphysGuiStateTxT, GetDQMActiveDeviceList, GetLBNumericalKeys, GetLBNumericalValues, GetLBTextualKeys, GetLBTextualValues, GetListOfLockedDevices, GetPopupMenuString, GetPxPVersion, GetReproducibleRandom, GetSliderPositionIndex, GetTPSettings, HARDWARE_MAX_DEVICES, HasPanelLatestVersion, HW_OpenDevice, HW_RegisterDevice, KillOrMoveToTrash, LOG_AddEntry, NewRandomSeed, NONE, P_SaveUserSelectedHeadstage, PACKAGE_MIES, REASON_HEADSTAGE_CHANGE, REASON_STIMSET_CHANGE, SetupBackgroundTasks, SI_CalculateMinSampInterval, TP_AutoTPGenerateNewCycleID, UNKNOWN_MIES_VERSION, UploadCrashDumpsDaily.
Referenced by DAP_ButtonProc_LockDev.
static variable DAP_AdaptPanelForDeviceSpecifics(string device, variable forceEnable=defaultValue)
References CHANNEL_TYPE_ADC, CHANNEL_TYPE_ASYNC, CHANNEL_TYPE_DAC, CHANNEL_TYPE_TTL, DAP_GetControlsForChannelIndex, DisableControls, EnableControls, GetDeviceInfoWave, NUM_AD_CHANNELS, NUM_ASYNC_CHANNELS, NUM_DA_TTL_CHANNELS.
Referenced by DAP_EphysPanelStartUpSettings, DAP_LockDevice.
static string DAP_GetControlsForChannelIndex(variable channelIndex, variable channelType)
References CHANNEL_CONTROL_ALARM_MAX, CHANNEL_CONTROL_ALARM_MIN, CHANNEL_CONTROL_CHECK, CHANNEL_CONTROL_GAIN, CHANNEL_CONTROL_INDEX_END, CHANNEL_CONTROL_SCALE, CHANNEL_CONTROL_SEARCH, CHANNEL_CONTROL_TITLE, CHANNEL_CONTROL_UNIT, CHANNEL_CONTROL_WAVE, CHANNEL_TYPE_ADC, CHANNEL_TYPE_ALARM, CHANNEL_TYPE_ASYNC, CHANNEL_TYPE_DAC, CHANNEL_TYPE_TTL, GetPanelControl.
Referenced by DAP_AdaptPanelForDeviceSpecifics.
static variable DAP_LoadBuiltinStimsets()
References GetAllFilesRecursivelyFromPath, GetFolder, GetUniqueSymbolicPath, NWB_LoadAllStimsets.
Referenced by DAP_LockDevice.
static variable DAP_ClearWaveIfExists(WaveOrNull wv)
Referenced by DAP_UnlockDevice.
static variable DAP_UnlockDevice(string device)
References ASSERT, ASYNC_WaitForWLCToFinishAndRemove, BASE_WINDOW_TITLE, CHECKBOX_UNSELECTED, CloseNWBFile, CONTROL_PANEL_TYPE, DAG_GetNumericalValue, DAP_ClearWaveIfExists, DAP_DeviceIsUnlocked, DAP_LockCommentNotebook, DAP_RemoveYokedDAC, DAP_ResetGUIAfterDAQ, DAP_SerializeCommentNotebook, DAP_ToggleTestpulseButton, DAP_UpdateAllYokeControls, DAP_UpdateDataFolderDisplay, DAP_UpdateListOfLockedDevices, DAP_UpdateYokeControls, DAP_WAITFORTPANALYSIS_TIMEOUT, DAQ_NOT_RUNNING, DEBUGPRINT, DeviceHasFollower, DisableControl, DQ_STOP_REASON_UNLOCKED_DEVICE, DQ_StopDAQ, EnableControls, GetActiveDAQDevicesFolder, GetActiveDAQDevicesTimerFolder, GetActiveDevicesTPMD, GetDA_EphysGuiStateNum, GetDA_EphysGuiStateTxT, GetDeviceMapping, GetDevicePath, GetDevicePathAsString, GetHardwareType, GetListOfLockedDevices, HARDWARE_ABORT_ON_ERROR, HARDWARE_PREVENT_ERROR_POPUP, HW_CloseDevice, HW_DeRegisterDevice, HW_ResetDevice, IsControlDisabled, IsEmpty, ITC1600_FIRST_DEVICE, KillOrMoveToTrash, NOTE_INDEX, NUM_HEADSTAGES, NWB_ASYNC_FinishWriting, PGC_SetAndActivateControl, SetNumberInWaveNote, TEST_PULSE_NOT_RUNNING, TESTPULSE_BUTTON_TO_START, TFH_StopFIFODaemon, TP_StopTestPulse, WORKLOADCLASS_TP.
Referenced by DAP_ButProc_Hrdwr_UnlckDev, DAP_EphysPanelStartUpSettings, DAP_UnlockAllDevices, DAP_WindowHook.
static variable DAP_UpdateListOfLockedDevices()
Update the list of locked devices.
References DAP_GetNIDeviceList.
Referenced by DAP_LockDevice, DAP_UnlockDevice.
static variable DAP_UpdateChanAmpAssignStorWv(string device)
References DAP_ParseAmplifierDef, GetChanAmpAssign, GetChanAmpAssignUnit, GetPopupMenuString, GetSetVariable, GetSetVariableString, IsFinite.
Referenced by DAP_PopMenuProc_CAA, DAP_SetVarProc_CAA.
static variable DAP_UpdateChanAmpAssignPanel(string device)
References DAP_GetAmplifierDef, DAP_GetNiceAmplifierChannelList, GetChanAmpAssign, GetChanAmpAssignUnit, GetPopupMenuString, IsFinite, NONE, NUM_MAX_CHANNELS.
Referenced by DAP_ButtonProc_AutoFillGain, DAP_ButtonProc_ClearChanCon, DAP_CheckHeadStage, DAP_SyncDeviceAssocSettToGUI.
static variable DAP_SetITCDACasFollower(string leadDAC, string followerDAC)
This function sets a ITC1600 device as a follower, ie. The internal clock is used to synchronize 2 or more PCI-1600.
References HARDWARE_ITC_DAC, HW_EnableYoking.
Referenced by DAP_ButtonProc_Follow.
variable DAP_UpdateDAQControls(string device, variable updateFlag)
Helper function to update all DAQ related controls after something changed.
device device updateFlag One of UpdateControlsFlags
References AFM_UpdateAnalysisFunctionWave, DAP_CheckSkipAhead, DAP_GetSampInt, DAP_UpdateSweepSetVariables, DATA_ACQUISITION_MODE, DEBUGPRINT, IDX_MaxNoOfSweeps, REASON_HEADSTAGE_CHANGE, REASON_STIMSET_CHANGE, REASON_STIMSET_CHANGE_DUR_DAQ, SetValDisplay.
Referenced by DAP_ChangeHeadStageMode, DAP_ChangeHeadstageState, DAP_CheckProc_IndexingState, DAP_DAorTTLCheckProc, DAP_LockDevice, DAP_PopMenuChkProc_StimSetList, DAP_PopMenuProc_FixedSampInt, DAP_PopMenuProc_SampMult, DAP_UpdateDaEphysStimulusSetPopups, IDX_ApplyUnLockedIndexing, IDX_IndexingDoIt, IDX_ResetStartFinishForIndexing.
static variable DAP_AllChanDASettings(string device, variable headStage, variable delayed=defaultValue)
Applies user settings for the clamp mode stimulus sets (DA Set and Indexing End Set) on mode switch.
device device headStage MIES headstage number, must be in the range [0, NUM_HEADSTAGES] delayed [optional, defaults to false] On a delayed clamp mode change the stimulus set is not set.
References AFH_GetDACFromHeadstage, CHANNEL_CONTROL_INDEX_END, CHANNEL_CONTROL_SCALE, CHANNEL_CONTROL_WAVE, CHANNEL_INDEX_ALL_I_CLAMP, CHANNEL_INDEX_ALL_V_CLAMP, CHANNEL_TYPE_DAC, DAG_GetHeadstageMode, DAG_GetNumericalValue, GetPanelControl, I_CLAMP_MODE, PGC_SetAndActivateControl, V_CLAMP_MODE.
Referenced by DAP_SetHeadstageChanControls.
variable DAP_ButtonProc_skipSweep(WMButtonAction *ba)
References RA_SkipSweeps.
variable DAP_ButtonProc_skipBack(WMButtonAction *ba)
References RA_SkipSweeps.
variable DAP_GetskipAhead(string device)
References GetDA_EphysGuiStateNum.
Referenced by DC_CalculateChannelColumnNo.
variable DAP_ResetskipAhead(string device)
References GetDA_EphysGuiStateNum, PGC_SetAndActivateControl.
variable DAP_getFilteredSkipAhead(string device, variable skipAhead)
References IDX_MinNoOfSweeps.
Referenced by DAP_CheckSkipAhead.
variable DAP_setSkipAheadLimit(string device, variable filteredSkipAhead)
References SetSetVariableLimits.
Referenced by DAP_CheckSkipAhead, DAP_SetVarProc_skipAhead.
variable DAP_SetVarProc_skipAhead(WMSetVariableAction *sva)
References DAG_Update, DAP_setSkipAheadLimit, IDX_MinNoOfSweeps.
variable DAP_CheckProc_RandomRA(WMCheckboxAction *cba)
References DAG_Update, PGC_SetAndActivateControl.
variable DAP_CheckSkipAhead(string device)
References DAG_GetNumericalValue, DAP_getFilteredSkipAhead, DAP_setSkipAheadLimit, PGC_SetAndActivateControl.
Referenced by DAP_UpdateDAQControls.
variable DAP_PopMenuProc_UpdateGuiState(WMPopupAction *pa)
References DAG_Update.
string DAP_GetSamplingMultiplier()
Return the list of available sampling multipliers.
Has no NONE element as 1 means no multiplier.
Referenced by IsValidSamplingMultiplier.
variable DAP_PopMenuProc_SampMult(WMPopupAction *pa)
References DAG_Update, DAP_UpdateDAQControls, DisableControl, EnableControl, REASON_HEADSTAGE_CHANGE.
string DAP_GetSamplingFrequencies()
Return the list of available fixed sampling frequencies.
variable DAP_PopMenuProc_FixedSampInt(WMPopupAction *pa)
References DAG_Update, DAP_UpdateDAQControls, DisableControl, EnableControl, REASON_HEADSTAGE_CHANGE.
string DAP_GetOsciUpdModes()
Return the list of available Oscilloscope Update Modes.
References GUI_SETTING_OSCI_SCALE_AUTO, GUI_SETTING_OSCI_SCALE_FIXED, GUI_SETTING_OSCI_SCALE_INTERVAL.
Referenced by DAP_EphysPanelStartUpSettings.
variable DAP_PopMenuProc_OsciUpdMode(WMPopupAction *pa)
References DAG_Update, DAQ_NOT_RUNNING, DATA_ACQUISITION_MODE, IsFinite, SCOPE_CreateGraph, TEST_PULSE_MODE, TEST_PULSE_NOT_RUNNING.
variable DAP_ApplyDelayedClampModeChange(string device)
References DAP_ChangeHeadStageMode, DAP_ClearDelayedClampModeChange, GetDA_EphysGuiStateNum, IsNaN, NO_SLIDER_MOVEMENT, NUM_HEADSTAGES.
Referenced by DAP_OneTimeCallAfterDAQ, RA_Counter, RA_CounterMD, RA_HandleITI, RA_HandleITI_MD.
variable DAP_ClearDelayedClampModeChange(string device)
References GetDA_EphysGuiStateNum.
Referenced by DAP_ApplyDelayedClampModeChange, DAP_OneTimeCallBeforeDAQ.
variable ButtonProc_Hardware_rescan(WMButtonAction *ba)
References DAP_GetITCDeviceList, DAP_GetNIDeviceList.
variable DAP_UpdateDeviceInfoWaves(string deviceList, variable hardwareType)
Update the device info waves for all passed devices.
Usually only called once during startup deviceList list of devices usable for DAQ and pressure hardwareType One of HardwareDACTypeConstants
References GetDeviceInfoWave, GetHardwareType, HW_GetDeviceInfoUnregistered, HW_WriteDeviceInfo.
Referenced by DAP_GetITCDeviceList, DAP_GetNIDeviceList.
variable DAP_CheckProc_PowerSpectrum(WMCheckboxAction *cba)
References DAG_Update, TP_RestartTestPulse, TP_StopTestPulse.
variable DAP_UpdateDaEphysStimulusSetPopups(string device=defaultValue)
Update the popup menus and its USER_DATA_MENU_EXP user data after stim set changes.
device [optional, defaults to all locked devices] device
References CHANNEL_CONTROL_INDEX_END, CHANNEL_CONTROL_WAVE, CHANNEL_INDEX_ALL, CHANNEL_INDEX_ALL_I_CLAMP, CHANNEL_TYPE_DAC, CHANNEL_TYPE_TTL, DAP_UpdateDAQControls, DAP_UpdateStimulusSetPopup, DEBUGPRINT, GetListOfLockedDevices, GetPanelControl, isEmpty, NUM_DA_TTL_CHANNELS, REASON_STIMSET_CHANGE, SetControlUserData, ST_GetStimsetList, USER_DATA_MENU_EXP, WindowExists.
Referenced by DAP_DeleteStimulusSet, DAP_LockDevice, DAP_PopMenuChkProc_StimSetList, NWB_LoadAllStimsets, WB_SaveStimSet, WBP_ButtonProc_SaveSet.
static variable DAP_UpdateStimulusSetPopup(string device, string ctrl, string stimsets)
References DAG_Update, GetPopupMenuString, NONE, SetPopupMenuIndex.
Referenced by DAP_UpdateDaEphysStimulusSetPopups.
variable DAP_DeleteStimulusSet(string setName, string device=defaultValue)
Delete the stimulus set in the given DAEphys.
Internal use only, outside callers should use ST_RemoveStimSet()
References CHANNEL_TYPE_UNKNOWN, DAP_UpdateDaEphysStimulusSetPopups, GetStimSetType, WB_KillParameterWaves, WB_KillStimset.
Referenced by ST_RemoveStimSet.
variable DAP_TPSettingsToWave(string device, wave TPSettings)
Write all TP settings from the data acquisition/settings tab to the settings wave.
References ASSERT, DAEPHYS_TP_CONTROLS_ALL, DAEPHYS_TP_CONTROLS_DEPEND, DAEPHYS_TP_CONTROLS_INDEP, DAG_GetNumericalValue, DAP_TPControlToLabel, INDEP_HEADSTAGE, ROWS.
Referenced by DAP_LockDevice, GetTPSettings.
static string DAP_TPControlToLabel(string ctrl)
Convert the control name to a dimension label for GetTPSettings()
References ASSERT.
Referenced by DAP_TPGUISettingToWave, DAP_TPSettingsToGUI, DAP_TPSettingsToWave.
static variable DAP_TPGUISettingToWave(string device, string ctrl, variable val)
Write a new TP setting value to the wave.
References DAEPHYS_TP_CONTROLS_INDEP, DAEPHYS_TP_CONTROLS_NO_RESTART, DAG_GetNumericalValue, DAP_AdaptAutoTPColorAndDependent, DAP_TPControlToLabel, DAP_UpdateOnsetDelay, DAQ_NOT_RUNNING, GetTPSettings, INDEP_HEADSTAGE, NUM_HEADSTAGES, TEST_PULSE_NOT_RUNNING, TP_AutoTPGenerateNewCycleID, TP_RestartTestPulse, TP_StopTestPulse.
Referenced by DAP_CheckProc_TestPulseSett, DAP_SetVarProc_TestPulseSett.
variable DAP_TPSettingsToGUI(string device, string entry=defaultValue)
Synchronize the TP settings from the wave into the GUI.
Needs to be done when the selected headstage changes or the TPsettings wave contents. This function ignores "Send To All HS" as this does not make sense to respect here. device device entry [optional, defaults to all] Only update one of the entries TPSettings. Accepted strings are the labels from DAP_TPControlToLabel().
References ASSERT, DAEPHYS_TP_CONTROLS_ALL, DAEPHYS_TP_CONTROLS_INDEP, DAG_GetNumericalValue, DAP_TPControlToLabel, GetTPSettings, INDEP_HEADSTAGE, IsFinite, PGC_SetAndActivateControl, ROWS, TP_RestartTestPulse, TP_StopTestPulse.
Referenced by DAP_SliderProc_MIESHeadStage, TP_AutoAmplitudeAndBaseline, TP_AutoBaseline, TP_AutoDisableIfFinished.