MIES_TestPulse_Single.ipf
variable TPS_StartBackgroundTestPulse(string device)
Referenced by RA_HandleITI, TPS_StartTestPulseSingleDevice.
variable TPS_StopTestPulseSingleDevice(string device, variable fast=defaultValue)
References TP_Teardown.
Referenced by DQ_StopOngoingDAQHelper, TP_StopTestPulseWrapper.
variable TPS_TestPulseFunc(BackgroundStruct *s)
Background TP Single Device.
References BackgroundStruct::count, DQ_STOP_REASON_ESCAPE_KEY, DQ_StopOngoingDAQ, ESCAPE_KEY, HARDWARE_ABORT_ON_ERROR, HARDWARE_ITC_DAC, HW_ITC_MoreData, HW_ITC_ResetFifo, HW_StartAcq, HW_StopAcq, SCOPE_UpdateGraph, SCOPE_UpdateOscilloscopeData, TEST_PULSE_MODE, BackgroundStruct::wmbs.
variable TPS_StartTestPulseSingleDevice(string device, variable fast=defaultValue)
Start a single device test pulse, either in background or in foreground mode depending on the settings.
device device fast [optional, defaults to false] Starts TP without any checks or setup. Can be called after stopping it with TP_StopTestPulseFast().
References AssertOnAndClearRTError, ClearRTError, DAG_GetNumericalValue, DAP_CheckSettings, DQ_STOP_REASON_TP_STARTED, DQ_StopOngoingDAQ, P_InitBeforeTP, TEST_PULSE_BG_SINGLE_DEVICE, TEST_PULSE_FG_SINGLE_DEVICE, TEST_PULSE_MODE, TP_CheckIfTestpulseIsRunning, TP_Setup, TP_Teardown, TPS_StartBackgroundTestPulse, TPS_StartTestPulseForeground.
Referenced by DAP_ButtonProc_TPDAQ, DAP_OneTimeCallAfterDAQ, TP_RestartTestPulse.
variable TPS_StartTestPulseForeground(string device, variable elapsedTime=defaultValue)
Start the single device foreground test pulse.
device device elapsedTime [defaults to infinity] allow to run the testpulse for the given amount of seconds only. zero if time elapsed, one if the Testpulse was manually stopped
References ESCAPE_KEY, HARDWARE_ABORT_ON_ERROR, HARDWARE_ITC_DAC, HW_ITC_MoreData, HW_ITC_ResetFifo, HW_StartAcq, HW_StopAcq, IsFinite, RelativeNowHighPrec, SCOPE_GetGraph, SCOPE_UpdateGraph, SCOPE_UpdateOscilloscopeData, SetValDisplay, TEST_PULSE_MODE.
Referenced by RA_HandleITI, TPS_StartTestPulseSingleDevice.