MIES_Indexing.ipf
variable IDX_StoreStartFinishForIndexing(string device)
References CHANNEL_CONTROL_INDEX_END, CHANNEL_CONTROL_WAVE, CHANNEL_TYPE_DAC, CHANNEL_TYPE_TTL, GetIndexingStorageWave, IDX_GetCurrentSets, NUM_DA_TTL_CHANNELS.
Referenced by DAP_OneTimeCallBeforeDAQ.
variable IDX_ResetStartFinishForIndexing(string device)
Resets the selected set popupmenus stored by IDX_StoreStartFinishForIndexing.
References CHANNEL_CONTROL_WAVE, CHANNEL_TYPE_DAC, CHANNEL_TYPE_TTL, DAG_Update, DAP_UpdateDAQControls, GetIndexingStorageWave, GetPanelControl, IDX_GetSingleStimset, IDX_GetStimsets, NUM_DA_TTL_CHANNELS, REASON_STIMSET_CHANGE, SetPopupMenuIndex.
Referenced by DAP_OneTimeCallAfterDAQ.
static variable IDX_IndexingDoIt(string device)
Locked indexing, indexes all active channels at once.
References CHANNEL_TYPE_DAC, CHANNEL_TYPE_TTL, DAP_UpdateDAQControls, DAQ_CHANNEL_TYPE_DAQ, DATA_ACQUISITION_MODE, DC_GetFilteredChannelState, GetSetEventFlag, IDX_CalculcateActiveSetCount, IDX_IndexSingleChannel, NUM_DA_TTL_CHANNELS, PRE_SET_EVENT, REASON_STIMSET_CHANGE_DUR_DAQ.
Referenced by IDX_HandleIndexing.
static variable IDX_IndexSingleChannel(string device, variable channelType, variable channel)
Indexes a single channel - used when indexing is unlocked.
Callers need to call DAP_UpdateDAQControls() with REASON_STIMSET_CHANGE_DUR_DAQ.
References CHANNEL_CONTROL_CHECK, CHANNEL_CONTROL_INDEX_END, CHANNEL_CONTROL_WAVE, DAG_GetNumericalValue, DAG_Update, GetIndexingStorageWave, GetPanelControl, GetSpecialControlLabel, IDX_GetCurrentSets, IDX_GetSingleStimset, IDX_GetStimsets, SetPopupMenuIndex.
Referenced by IDX_ApplyUnLockedIndexing, IDX_IndexingDoIt.
variable IDX_MaxSweepsLockedIndexing(string device)
Sum of the largest sets for each indexing step.
References CHANNEL_TYPE_DAC, CHANNEL_TYPE_TTL, IDX_MaxSets, IDX_StepsInSetWithMaxSweeps.
Referenced by DAP_UpdateSweepSetVariables.
static variable IDX_StepsInSetWithMaxSweeps(string device, variable IndexNo, variable channelType)
Return the number of steps in the largest set for a particular index number.
References DAG_GetChannelState, IDX_GetCurrentSets, IDX_GetSingleStimset, IDX_GetStimsets, IDX_NumberOfSweepsInSet, NUM_DA_TTL_CHANNELS.
Referenced by IDX_MaxSweepsLockedIndexing.
static std::tuple< variable, variable > IDX_GetCurrentSets(string device, variable channelType, variable channelNumber)
Return the 0-based popup menu indizes of the current WAVE/INDEX_END stimsets.
References CHANNEL_CONTROL_INDEX_END, CHANNEL_CONTROL_WAVE, DAG_GetNumericalValue, GetSpecialControlLabel.
Referenced by IDX_IndexSingleChannel, IDX_MaxSets, IDX_StepsInSetWithMaxSweeps, IDX_StoreStartFinishForIndexing.
static variable IDX_MaxSets(string device, variable channelType)
Return the number of sets on the active channel with the most sets.
References DAG_GetChannelState, IDX_GetCurrentSets, NUM_DA_TTL_CHANNELS.
Referenced by IDX_MaxSweepsLockedIndexing.
variable IDX_MaxNoOfSweeps(string device, variable IndexOverRide)
determine the max number of sweeps in the largest start set on active (checked) DA or TTL channels works for unlocked (independent) indexing
device device IndexOverRide index override is the same as indexing off. some Functions that call this function only want the max number of steps in the start (active) set, when indexing is on. 1 = over ride ON
References CHANNEL_TYPE_DAC, CHANNEL_TYPE_TTL, DAQ_CHANNEL_TYPE_DAQ, DAQ_CHANNEL_TYPE_TP, DATA_ACQUISITION_MODE, DC_GetFilteredChannelState, DEBUGPRINTv, DeviceHasFollower, IDX_MaxNoOfSweeps, IDX_NumberOfSweepsAcrossSets, NUM_DA_TTL_CHANNELS.
Referenced by DAP_UpdateDAQControls, DAP_UpdateSweepSetVariables, IDX_MaxNoOfSweeps.
variable IDX_MinNoOfSweeps(string device)
Returns the number of sweeps in the stimulus set with the smallest number of sweeps (across all active stimulus sets).
device device
References CHANNEL_TYPE_DAC, CHANNEL_TYPE_TTL, DAQ_CHANNEL_TYPE_DAQ, DATA_ACQUISITION_MODE, DC_GetFilteredChannelState, IDX_NumberOfSweepsAcrossSets, NUM_DA_TTL_CHANNELS.
Referenced by DAP_getFilteredSkipAhead, DAP_SetVarProc_skipAhead.
wave IDX_GetSetsInRange(string device, variable channel, variable channelType, variable lockedIndexing)
Returns a 1D textwave of selected set names.
device panel channel channel channelType CHANNEL_TYPE_DAC or CHANNEL_TYPE_TTL lockedIndexing defaults to false, true returns just the DAC/TTL setname Constants are defined at ChannelTypeAndControlConstants
References CHANNEL_CONTROL_INDEX_END, CHANNEL_CONTROL_WAVE, DAG_GetNumericalValue, DEBUGPRINT, DuplicateSubRange, GetSpecialControlLabel, IDX_GetStimsets, MinMax.
Referenced by DAP_CheckSettings, DAP_CheckStimset, IDX_NumberOfSweepsAcrossSets.
static variable IDX_NumberOfSweepsAcrossSets(string device, variable channel, variable channelType, variable lockedIndexing)
Determine the number of sweeps for a DA or TTL channel.
References DEBUGPRINTv, IDX_GetSetsInRange, IDX_NumberOfSweepsInSet, ROWS.
Referenced by IDX_MaxNoOfSweeps, IDX_MinNoOfSweeps.
variable IDX_NumberOfSweepsInSet(string setName)
Return the number of sweeps.
References COLS, isEmpty, STIMSET_TP_WHILE_DAQ, WB_CreateAndGetStimSet.
Referenced by DC_CalculateChannelColumnNo, DC_FillSetEventFlag, IDX_DetIfCountIsAtSetBorder, IDX_NumberOfSweepsAcrossSets, IDX_StepsInSetWithMaxSweeps, IDX_TotalIndexingListSteps, IDX_UnlockedIndexingStepNo, MSQ_CreateOverrideResults, PSQ_Chirp, PSQ_Chirp_CheckParam, PSQ_CreateOverrideResults, PSQ_DAScale, PSQ_PipetteInBath, PSQ_PipetteInBath_CheckParam, PSQ_Ramp, SC_GetHeadstageQCForSetCount, SC_LastSweepInSet.
static variable IDX_ApplyUnLockedIndexing(string device, variable count)
References CHANNEL_TYPE_DAC, CHANNEL_TYPE_TTL, DAP_UpdateDAQControls, DAQ_CHANNEL_TYPE_DAQ, DATA_ACQUISITION_MODE, DC_GetFilteredChannelState, IDX_CalculcateActiveSetCount, IDX_DetIfCountIsAtSetBorder, IDX_IndexSingleChannel, NUM_DA_TTL_CHANNELS, REASON_STIMSET_CHANGE_DUR_DAQ.
Referenced by IDX_HandleIndexing.
static variable IDX_TotalIndexingListSteps(string device, variable channelNumber, variable channelType)
References ASSERT, CHANNEL_CONTROL_INDEX_END, CHANNEL_CONTROL_WAVE, GetIndexingStorageWave, IDX_GetSingleStimset, IDX_GetStimsets, IDX_NumberOfSweepsInSet, MinMax.
Referenced by IDX_DetIfCountIsAtSetBorder, IDX_UnlockedIndexingStepNo.
variable IDX_UnlockedIndexingStepNo(string device, variable channelNumber, variable channelType, variable count)
References ASSERT, CHANNEL_CONTROL_INDEX_END, CHANNEL_CONTROL_WAVE, GetIndexingStorageWave, IDX_GetSingleStimset, IDX_GetStimsets, IDX_NumberOfSweepsInSet, IDX_TotalIndexingListSteps.
Referenced by DC_CalculateChannelColumnNo.
static variable IDX_DetIfCountIsAtSetBorder(string device, variable count, variable channelNumber, variable channelType)
References ASSERT, CHANNEL_CONTROL_INDEX_END, CHANNEL_CONTROL_WAVE, GetIndexingStorageWave, IDX_GetSingleStimset, IDX_GetStimsets, IDX_NumberOfSweepsInSet, IDX_TotalIndexingListSteps.
Referenced by IDX_ApplyUnLockedIndexing.
variable IDX_CalculcateActiveSetCount(string device)
Calculate the active set count.
References DAG_GetNumericalValue, GetValDisplayAsNum.
Referenced by DAP_OneTimeCallBeforeDAQ, DC_CalculateChannelColumnNo, IDX_ApplyUnLockedIndexing, IDX_HandleIndexing, IDX_IndexingDoIt, RA_GetTotalNumberOfSweepsLowLev, RA_SkipSweeps.
static wave IDX_GetStimsets(string device, variable channelIdx, variable channelType)
Extract the list of stimsets from the control user data.
References CHANNEL_CONTROL_WAVE, GetPanelControl, USER_DATA_MENU_EXP.
Referenced by IDX_DetIfCountIsAtSetBorder, IDX_GetSetsInRange, IDX_IndexSingleChannel, IDX_ResetStartFinishForIndexing, IDX_StepsInSetWithMaxSweeps, IDX_TotalIndexingListSteps, IDX_UnlockedIndexingStepNo.
static string IDX_GetSingleStimset(WaveText listWave, variable idx, variable allowNone=defaultValue)
Return the stimset from the list of stimsets returned by IDX_GetStimsets()
listWave list of stim sets returned by IDX_GetStimsets() idx 0-based index allowNone [optional, defaults to false] Return the NONE stimset for idx 0. Not allowed during DAQ.
References ASSERT, IsEmpty, NONE.
Referenced by IDX_DetIfCountIsAtSetBorder, IDX_IndexSingleChannel, IDX_ResetStartFinishForIndexing, IDX_StepsInSetWithMaxSweeps, IDX_TotalIndexingListSteps, IDX_UnlockedIndexingStepNo.
variable IDX_HandleIndexing(string device)
References DAG_GetNumericalValue, DeviceHasFollower, IDX_ApplyUnLockedIndexing, IDX_CalculcateActiveSetCount, IDX_IndexingDoIt, RA_StepSweepsRemaining.
Referenced by RA_Counter, RA_CounterMD.