MIES_ThreadsafeUtilities.ipf
const double TS_GET_REPEAT_TIMEOUT_IN_MS
Referenced by TS_GetNewestFromThreadQueue, TS_GetNewestFromThreadQueueMult.
const double TS_ERROR_INVALID_TGID
Referenced by TS_GetNewestFromThreadQueue, TS_GetNewestFromThreadQueueMult, TS_ThreadGroupGetVariable.
variable TS_GetNewestFromThreadQueue(variable tgID, string varName)
Return the newest variable named varName from the thread queue.
Return NaN if the thread is not running anymore. Throws away anything else in the datafolder from the thread queue.
References ASSERT, ASSERT_TS, AssertOnAndClearRTError, isEmpty, IsFinite, IsNaN, TS_ERROR_INVALID_TGID, TS_GET_REPEAT_TIMEOUT_IN_MS, TS_ThreadGroupFinished.
Referenced by DQM_FIFOMonitor, PSQ_Ramp, TPM_BkrdTPFuncMD.
wave TS_GetNewestFromThreadQueueMult(variable tgID, WaveText varNames)
Return the newest variables from the thread queue.
The function returns if it received at least one variable from the thread queue. Return an invalid wave reference if the thread is not running anymore. Throws away anything else in the datafolder from the thread queue.
References ASSERT, ASSERT_TS, AssertOnAndClearRTError, COLS, isEmpty, IsNaN, IsTextWave, ROWS, TS_ERROR_INVALID_TGID, TS_GET_REPEAT_TIMEOUT_IN_MS, TS_ThreadGroupFinished.
Referenced by TPM_BkrdTPFuncMD.
variable TS_ThreadGroupGetVariable(variable tgID, string varName)
Return the variable named varName from the thread queue or NaN if there is none.
Throws away anything else in the datafolder from the thread queue.
References ASSERT_TS, DataFolderExistsDFR, isEmpty, TS_ERROR_INVALID_TGID.
variable TS_ThreadGroupPutVariable(variable tgID, string varName, variable varValue)
Push a single variable named varName with value varValue to the thread queue.
Referenced by TFH_FifoLoop, TS_StopThreadGroup.
variable TS_ThreadGroupPutDFR(variable tgID, dfref dfr)
Push a datafolder to the thread queue.
Works on a duplicate of the input DF to remove all references. dfr can be a free DF
References ASSERT_TS, COUNTOBJECTS_DATAFOLDER, DataFolderExistsDFR.
variable TS_ThreadGroupFinished(variable tgID)
Returns 1 if all worker threads have finished.
References AssertOnAndClearRTError.
Referenced by TS_GetNewestFromThreadQueue, TS_GetNewestFromThreadQueueMult, TS_StopThreadGroup.
variable TS_StopThreadGroup(variable tgID)
Stop the given thread group.
Assumes that the running worker functions finish on getting the abort variable sent.
References ControlWindowToFront, DEBUGPRINT, IsFinite, TS_ThreadGroupFinished, TS_ThreadGroupPutVariable.
Referenced by TFH_StopFIFODaemon.