MIES_ArtefactRemoval.ipf
const double AR_MIN_RANGE_FACTOR
Referenced by AR_ComputeRanges.
static wave AR_ComputeRanges(dfref sweepDFR, variable sweepNo, wave numericalValues)
Return a free 2D wave with artefact positions and the corresponding DA channel from which it originated.
Columns: Artefact position [ms] DAC ADC Headstage
References AR_MIN_RANGE_FACTOR, CA_ArtefactRemovalRangesKey, CA_StoreEntryIntoCache, CA_TryFetchingEntryFromCache, DATA_ACQUISITION_MODE, EnsureLargeEnoughWave, GetDAQDataSingleColumnWave, GetLastSetting, GetNumberFromWaveNote, MakeWaveFree, MINIMUM_WAVE_SIZE, NOTE_INDEX, NUM_HEADSTAGES, SetNumberInWaveNote, XOP_CHANNEL_TYPE_DAC.
Referenced by AR_UpdateTracesIfReq.
static variable AR_UpdatePanel(string device, wave ranges, dfref sweepDFR)
References AR_GetFolder, AR_SetSweepFolder, AR_UpdateListBoxWave, GetArtefactRemovalDataWave, GetArtefactRemovalListWave, ROWS.
Referenced by AR_UpdateTracesIfReq.
static variable AR_UpdateListBoxWave(string device)
References AR_GetFolder, BSP_GetPanel, GetArtefactRemovalDataWave, GetArtefactRemovalListWave, GetSetVariable.
Referenced by AR_SetVarProcCutoffLength, AR_UpdatePanel.
static variable AR_RemoveTraces(string graph)
Remove the traces used for highlightning the to-be-removed ranges.
References AR_GetHighlightTraces, TUD_RemoveUserData.
Referenced by AR_HandleRanges.
static string AR_GetHighlightTraces(string graph)
Return a list of the traces used for highlightning the to-be-removed ranges.
References TextWaveToList, TUD_GetUserDataAsWave.
Referenced by AR_HighlightArtefactsEntry, AR_RemoveTraces.
variable AR_HighlightArtefactsEntry(string graph)
References AR_GetFolder, AR_GetHighlightTraces, AR_IsActive, BSP_GetPanel, GetArtefactRemovalDataWave, GetArtefactRemovalListWave, GetCheckBoxState, GetListBoxSelRow, IsInteger, ROWS, TUD_GetUserData.
Referenced by AR_MainListBoxProc, PostPlotTransformations.
static variable AR_HandleRanges(string graph, variable removeRange=defaultValue)
References AddEntryIntoWaveNoteAsList, AR_GetFolder, AR_GetSweepFolder, AR_RemoveTraces, ASSERT, BSP_GetPanel, GetArtefactRemovalDataWave, GetArtefactRemovalListWave, GetCheckBoxState, GetDAQDataSingleColumnWaves, GetTraceNamePrefix, NOTE_KEY_ARTEFACT_REMOVAL, NUM_AD_CHANNELS, ROWS, TUD_GetUserDataAsWave, TUD_SetUserData, XOP_CHANNEL_TYPE_ADC.
Referenced by AR_SetVarProcCutoffLength, AR_UpdateTracesIfReq.
static dfref AR_GetFolder(string device)
Return the datafolder reference to the folder storing the listbox wave and the artefact data wave.
Requires the user data PANEL_FOLDER of the external artefact removal panel.
References AR_IsActive, BSP_GetFolder, MIES_BSP_PANEL_FOLDER.
Referenced by AR_HandleRanges, AR_HighlightArtefactsEntry, AR_UpdateListBoxWave, AR_UpdatePanel.
static dfref AR_GetSweepFolder(string device)
Return the datafolder reference to the folder storing the single 1D sweep waves.
Requires the user data AR_SWEEPFOLDER of the external artefact removal panel.
References AR_IsActive, BSP_GetFolder, MIES_BSP_AR_SWEEPFOLDER.
Referenced by AR_HandleRanges.
static variable AR_SetSweepFolder(string device, dfref sweepDFR)
Updates the AR_SWEEPFOLDER user data of the artefact removal panel.
References BSP_SetFolder, MIES_BSP_AR_SWEEPFOLDER.
Referenced by AR_UpdatePanel.
variable AR_MainListBoxProc(WMListboxAction *lba)
References AR_HighlightArtefactsEntry, GetMainWindow.
variable AR_SetVarProcCutoffLength(WMSetVariableAction *sva)
References AR_HandleRanges, AR_UpdateListBoxWave, GetMainWindow.
variable AR_ButtonProc_RemoveRanges(WMButtonAction *ba)
References CHECKBOX_SELECTED, CHECKBOX_UNSELECTED, GetMainWindow, SetCheckBoxState, UpdateSweepPlot.
variable AR_UpdateTracesIfReq(string graph, dfref sweepFolder, variable sweepNo)
References AR_ComputeRanges, AR_HandleRanges, AR_IsActive, AR_UpdatePanel, ASSERT, BSP_GetLogbookWave, GetMainWindow, GetSingleSweepFolder, LBN_NUMERICAL_VALUES, LBT_LABNOTEBOOK.
Referenced by DB_AddSweepToGraph, DB_UpdateSweepPlot, SB_AddSweepToGraph, SB_UpdateSweepPlot.
variable AR_CheckProc_Update(WMCheckboxAction *cba)
References UpdateSweepPlot.
variable AR_IsActive(string win)
checks if AR is active.
References BSP_IsActive, MIES_BSP_AR.
Referenced by AR_GetFolder, AR_GetSweepFolder, AR_HighlightArtefactsEntry, AR_UpdateTracesIfReq, BSP_SetARControlStatus.