MIES_Utilities.ipf
const double DEBUGGER_ENABLED
Referenced by DisableDebugger, ResetDebuggerState.
const double DEBUGGER_DEBUG_ON_ERROR
Referenced by DisableDebugger, ResetDebuggerState.
const double DEBUGGER_NVAR_CHECKING
Referenced by DisableDebugger, ResetDebuggerState.
const double PROPRIETARY_HEADER_SIZE
The size in bytes of a wave with zero points. Experimentally determined in Igor Pro 6.34 under windows.
Referenced by GetWaveSizeImplementation.
variable IsFinite(variable var)
Returns 1 if var is a finite/normal number, 0 otherwise.
UTF_NOINSTRUMENTATION
variable IsNaN(variable var)
Returns 1 if var is a NaN, 0 otherwise.
UTF_NOINSTRUMENTATION
variable IsNull(string *str)
Returns 1 if str is null, 0 otherwise.
str must not be a SVAR UTF_NOINSTRUMENTATION
variable IsEmpty(string str)
Returns one if str is empty, zero otherwise.
str any non-null string variable or text wave element UTF_NOINSTRUMENTATION
variable ASSERT(variable var, string errorMsg, variable extendedOutput=defaultValue)
Low overhead function to check assertions.
var if zero an error message is printed into the history and procedure execution is aborted, nothing is done otherwise. If the debugger is enabled, it also steps into it. errorMsg error message to output in failure case extendedOutput [optional, defaults to true] Output additional information on failure Example usage: embed:rst:leading-asterisk * .. code-block:: igorpro * * ControlInfo/W = $device popup_MoreSettings_DeviceType * ASSERT(V_flag > 0, "Non-existing control or window") * do something with S_value * UTF_NOINSTRUMENTATION
variable ASSERT_TS(variable var, string errorMsg, variable extendedOutput=defaultValue)
Low overhead function to check assertions (threadsafe variant)
var if zero an error message is printed into the history and procedure execution is aborted, nothing is done otherwise. errorMsg error message to output in failure case extendedOutput [optional, defaults to true] Output additional information on failure Example usage: embed:rst:leading-asterisk * .. code-block:: igorpro * * ASSERT_TS(DataFolderExistsDFR(dfr), "dfr does not exist") * do something with dfr * Unlike ASSERT() this function does not jump into the debugger (Igor Pro limitation). UTF_NOINSTRUMENTATION
variable WindowExists(string win)
Checks if the given name exists as window.
UTF_NOINSTRUMENTATION
string GetListOfObjects(dfref dfr, string matchExpr, variable typeFlag=defaultValue, variable fullPath=defaultValue, variable recursive=defaultValue, variable exprType=defaultValue)
Alternative implementation for WaveList/VariableList/etc. which honours a dfref and thus does not require SetDataFolder calls.
dfr datafolder reference to search for the objects matchExpr expression matching the objects, either a regular (exprType == MATCH_REGEXP) or wildcard (exprType == MATCH_WILDCARD) expression typeFlag [optional, default: COUNTOBJECTS_WAVES] One of TypeFlags fullPath [optional, default: false] should only the object name or the absolute path of the object be returned recursive [optional, default: false] descent into all subfolders recursively exprType [optional, defaults: MATCH_REGEXP] convention used for matchExpr, one of MatchExpressions list of object names matching matchExpr
References AddPrefixToEachListItem, ASSERT, COUNTOBJECTS_DATAFOLDER, COUNTOBJECTS_WAVES, DataFolderExistsDFR, GetAllObjects, GetListOfObjects, isEmpty, IsEmpty, ListMatchesExpr, MATCH_REGEXP, MATCH_WILDCARD.
Referenced by AB_LoadDataWrapper, AB_LoadSweepsFromExperiment, AB_LoadTPStorageFromIgor, AFH_GetLastSweepAcquired, AppendEntries, AverageWavesFromSameYAxisIfReq, CheckAllDimensionLabels, DB_GetPlainSweepList, GetAllDevices, GetAllDevicesWithContent, GetListOfObjects, GetSizeOfAllWavesInExperiment, ID_GetWave, IH_KillTemporaries, IsWaveDisplayedOnGraph, LBV_AddTraceToLBGraphTPStorage, LBV_GetTPStorageEntries, NWB_ExportAllData, NWB_FirstStartTimeOfAllSweeps, NWB_WriteTestpulseData, RemoveTracesFromGraph, SaveExperimentSpecial, SB_GetChannelInfoFromGraph, ST_GetStimsetList, SWS_DeleteDataWaves, WBP_ReturnFoldersList.
static string GetAllObjects(dfref dfr, variable typeFlag)
Return a list of all objects of the given type from dfr.
Does not work for datafolders which have a comma (,) in them.
References ASSERT, COUNTOBJECTS_DATAFOLDER, COUNTOBJECTS_STR, COUNTOBJECTS_VAR, COUNTOBJECTS_WAVES.
Referenced by GetListOfObjects.
string GetAllObjects_TS(dfref dfr, variable typeFlag)
Return a list of all objects of the given type from dfr.
Todomerge with GetAllObjects once IP9 is mandatory as then VariableList and StringList are threadsafe Does not work for datafolders which have a comma (,) in them.
References ASSERT_TS, COUNTOBJECTS_DATAFOLDER, COUNTOBJECTS_STR, COUNTOBJECTS_VAR, COUNTOBJECTS_WAVES.
Referenced by NWB_AppendSweepLowLevel.
string ListMatchesExpr(string list, string matchExpr, variable exprType)
Matches list against the expression matchExpr using the given convention in exprType
References ASSERT, MATCH_REGEXP, MATCH_WILDCARD.
Referenced by GetListOfObjects.
variable EnsureLargeEnoughWave(wave wv, variable minimumSize=defaultValue, variable dimension=defaultValue, variable initialValue=defaultValue, variable checkFreeMemory=defaultValue)
Redimension the wave to at least the given size.
The redimensioning is only done if it is required. Can be used to fill a wave one at a time with the minimum number of redimensions. In the following example NOTE_INDEX is the index of the next free row and the total number of rows filled with data. embed:rst:leading-asterisk * .. code-block:: igorpro * * Make/FREE/N=(MINIMUM_WAVE_SIZE) data * SetNumberInWaveNote(data, NOTE_INDEX, 0) * // ... * for(...) * index = GetNumberFromWaveNote(data, NOTE_INDEX) * // ... * EnsureLargeEnoughWave(data, dimension = ROWS, minimumSize = index) * data[index] = ... * // ... * SetNumberInWaveNote(data, NOTE_INDEX, ++index) * endfor * wv wave to redimension minimumSize [optional, default is implementation defined] the minimum size of the wave. The actual size of the wave after the function returns might be larger. dimension [optional, defaults to ROWS] dimension to resize, all other dimensions are left untouched. initialValue [optional, defaults to zero] initialValue of the new wave points checkFreeMemory [optional, defaults to false] check if the free memory is enough for increasing the size 0 on success, (only for checkFreeMemory = True) 1 if increasing the wave's size would fail due to little memory
References ASSERT_TS, CHUNKS, COLS, GetFreeMemory, GetWaveSize, IsFinite, LAYERS, MAX_DIMENSION_COUNT, MINIMUM_WAVE_SIZE, ROWS, ValueCanBeWritten.
Referenced by AB_AddExperimentNameIfReq, AB_AddMapEntry, AB_FillListWave, AB_LoadSweepFromNWB, AB_LoadSweepsFromExperiment, AB_SaveDeviceList, AB_StoreChannelsBySweep, AD_FillWaves, AFH_GetSweepsFromSameRACycle, AFH_GetSweepsFromSameSCI, AppendEntries, AR_ComputeRanges, AS_RecordStateTransition, CA_MakeSpaceForNewEntry, CONF_GetControlArrayList, CreateTiledChannelGraph, ED_createTextNotes, ED_createWaveNotes, ED_FindIndizesAndRedimension, EP_AddEpoch, FitResistance, GetLastSetting, GetLBIndexCache, GetLBRowCache, GetUserdataKeys, LoadEpochTable, OOD_GetRegionsFromStimset, PA_GenerateAllPulseWaves, PA_ShowImage, PGC_ShowControlInTab, RA_PerfAddMark, SB_AddToSweepBrowser, SB_GetChannelInfoFromGraph, SBE_AddMissingADTraceInfo, StoreElapsedTime, TP_RecordTP, TP_StoreTP, TP_UpdateHoldCmdInTPStorage, TPM_AddDevice, TUD_AddTrace, WB_PulseTrainSegment, WBP_ListControlsPerStimulusType.
variable ValueCanBeWritten(WaveOrNull wv, variable value)
Check that the given value can be stored in the wave.
Does currently ignore floating point precision and ranges for integer waves
References IGOR_TYPE_32BIT_FLOAT, IGOR_TYPE_64BIT_FLOAT, IsFinite, IsNumericWave.
Referenced by EnsureLargeEnoughWave.
variable EnsureSmallEnoughWave(wave wv, variable maximumSize=defaultValue)
Resize the number of rows to maximumSize if it is larger than that.
wv wave to redimension maximumSize maximum number of the rows, defaults to MAXIMUM_SIZE
References MAX_DIMENSION_COUNT, MAXIMUM_WAVE_SIZE, ROWS.
variable ConvertFromBytesToMiB(variable var)
Convert Bytes to MiBs, a mebibyte being 2^20.
Referenced by UpdateCurrentSize, UpdateEstimatedSizeAfterwards.
static variable GetWaveSizeImplementation(wave wv)
Returns the size of the wave in bytes.
References GetSizeOfType, PROPRIETARY_HEADER_SIZE.
Referenced by GetWaveSize.
variable GetSizeOfType(wave wv)
Return the size in bytes of a given type.
Inspired by http://www.igorexchange.com/node/1845
References ASSERT_TS, IGOR_TYPE_16BIT_INT, IGOR_TYPE_32BIT_FLOAT, IGOR_TYPE_32BIT_INT, IGOR_TYPE_64BIT_FLOAT, IGOR_TYPE_64BIT_INT, IGOR_TYPE_8BIT_INT, IGOR_TYPE_COMPLEX.
Referenced by GetWaveSizeImplementation.
variable GetWaveSize(WaveOrNull wv, variable recursive=defaultValue)
Returns the size of the wave in bytes.
References GetWaveSize, GetWaveSizeImplementation, IsWaveRefWave, ROWS.
Referenced by CA_StoreEntryIntoCache, EnsureLargeEnoughWave, GetSizeOfAllWavesInExperiment, GetWaveSize, UpdateCurrentSize, UpdateEstimatedSizeAfterwards.
variable GetLockState(wave wv)
Return the lock state of the passed wave.
References ASSERT_TS.
Referenced by DAP_CheckSettings, DC_InitDataHoldingWave, GetLBIndexCache, GetLBNidCache, GetLBRowCache.
variable ConvertSamplingIntervalToRate(variable val)
Convert the sampling interval in microseconds (1e-6s) to the rate in kHz.
Referenced by AppendEntries, NWB_AppendSweepLowLevel.
variable ConvertRateToSamplingInterval(variable val)
Convert the rate in kHz to the sampling interval in microseconds (1e-6s)
Referenced by ButtonDoIt.
variable DataFolderExistsDFR(dfref dfr)
Checks if the datafolder referenced by dfr exists.
dfr data folder to test one if dfr is valid and references an existing or free datafolder, zero otherwise UTF_NOINSTRUMENTATION
Referenced by GetListOfObjects, IsDataFolderEmpty, IsGlobalDataFolder, IsWaveDisplayedOnGraph, RecursiveRemoveEmptyDataFolder, RemoveAllEmptyDataFolders, RemoveEmptyDataFolder, UniqueDataFolderName, UniqueWaveName.
variable IsGlobalDataFolder(dfref dfr)
Check if the passed datafolder reference is a global/permanent datafolder.
References DataFolderExistsDFR.
Referenced by SplitSweepIntoComponents.
dfref createDFWithAllParents(string dataFolder)
Create a datafolder and all its parents,.
Includes fast handling of the common case that the datafolder exists. reference to the datafolder UTF_NOINSTRUMENTATION
variable IsInteger(variable var)
Returns one if var is an integer and zero otherwise UTF_NOINSTRUMENTATION.
References IsFinite.
Referenced by Downsample, ElideText, FindLevelWrapper, GetISO8601TimeStamp, IsEven, IsOdd, NumberToHex, RemoveUnusedRows, TextWaveToList.
variable IsEven(variable var)
UTF_NOINSTRUMENTATION.
References IsInteger.
Referenced by DAP_GetInfoFromControl, DecimateWithMethod, GetDecimatedWaveSize, SetControlInEvent, SI_FillActiveChannelsStruct.
variable IsOdd(variable var)
UTF_NOINSTRUMENTATION.
References IsInteger.
Referenced by PA_CalculatePulseInfos, PA_SpikePositionsForNonVC.
variable Downsample(WaveOrNull wv, variable downsampleFactor, variable upsampleFactor, variable mode, string winFunction=defaultValue)
Downsample data.
Downsampling is performed on each column of the input wave. Edge-points of the output wave are by default set to zero. wv numeric wave, its row must hold more points than downsampleFactor. Will hold the downsampled data on successfull return, in the error case the contents are undetermined downsampleFactor positive non-zero integer by which the wave should be downsampled upsampleFactor positive non-zero integer by which the wave should be upsampled mode decimation mode, one of DECIMATION_BY_OMISSION, DECIMATION_BY_AVERAGING or DECIMATION_BY_SMOOTHING. winFunction Windowing function for DECIMATION_BY_SMOOTHING mode, must be one of ALL_WINDOW_FUNCTIONS. One on error, zero otherwise
References ALL_WINDOW_FUNCTIONS, ControlWindowToFront, DECIMATION_BY_AVERAGING, DECIMATION_BY_OMISSION, DECIMATION_BY_SMOOTHING, IsInteger, ROWS.
variable CalculateLCM(variable a, variable b)
Compute the least common multiplier of two variables.
Referenced by CalculateLCMOfWave.
variable CalculateLCMOfWave(wave wv)
Compute the least common multiplier of all entries in the 1D-wave.
References CalculateLCM, ROWS.
Referenced by GetPopupMenuRates.
wave GetUniqueEntries(wave wv, variable caseSensitive=defaultValue)
Returns an unsorted free wave with all unique entries from wv.
uses built-in igor function FindDuplicates. Entries are deleted from left to right.
References ASSERT, GetUniqueTextEntries, IsTextWave, ROWS.
Referenced by ConvertToUniqueNumber.
string GetUniqueTextEntriesFromList(string list, string sep=defaultValue, variable caseSensitive=defaultValue)
Convenience wrapper around GetUniqueTextEntries() for string lists.
References ASSERT, GetUniqueTextEntries, TextWaveToList.
static wave GetUniqueTextEntries(WaveText wv, variable caseSensitive=defaultValue)
Search and Remove Duplicates from Text Wave wv.
Duplicates are removed from left to right wv text wave reference caseSensitive [optional] Indicates whether comparison should be case sensitive. defaults to True free wave with unique entries
References ASSERT, ROWS.
Referenced by GetUniqueEntries, GetUniqueTextEntriesFromList.
variable RemoveEmptyDataFolder(dfref dfr)
Removes the datafolder reference if there are no objects in it anymore.
dfr data folder reference to kill 1 in case the folder was removed and 0 in all other cases
References DataFolderExistsDFR, IsDataFolderEmpty.
Referenced by AverageWavesFromSameYAxisIfReq, IH_KillTemporaries, RecursiveRemoveEmptyDataFolder, RemoveAllEmptyDataFolders, StoreWaveOnDisk, UpgradeWaveLocationAndGetIt.
variable IsDataFolderEmpty(dfref dfr)
Return 1 if the datafolder is empty, zero if not.
References ASSERT, COUNTOBJECTS_DATAFOLDER, COUNTOBJECTS_STR, COUNTOBJECTS_VAR, COUNTOBJECTS_WAVES, DataFolderExistsDFR.
Referenced by AB_LoadResultsFromNWB, AB_ReExport, RemoveEmptyDataFolder, SWS_DeleteDataWaves.
variable RemoveAllEmptyDataFolders(dfref sourceDFR)
Removes all empty datafolders in the passed datafolder reference.
References COUNTOBJECTS_DATAFOLDER, DataFolderExistsDFR, RemoveEmptyDataFolder.
Referenced by AB_LoadDataWrapper.
variable RecursiveRemoveEmptyDataFolder(dfref dfr)
Recursively remove all folders from the datafolder path, if and only if all are empty.
References DataFolderExistsDFR, RemoveEmptyDataFolder.
Referenced by DownsampleWindowHook.
variable DisableDebugger()
Disable the debugger.
the full debugger state binary encoded. first bit: on/off, second bit: debugOnError on/off, third bit: nvar/svar/wave checking on/off
References DEBUGGER_DEBUG_ON_ERROR, DEBUGGER_ENABLED, DEBUGGER_NVAR_CHECKING.
Referenced by IH_Cleanup.
variable ResetDebuggerState(variable debuggerState)
Reset the debugger to the given state.
Useful in conjunction with DisableDebugger() to temporarily disable the debugger embed:rst:leading-asterisk * .. code-block:: igorpro * * variable debuggerState = DisableDebugger() * // code which might trigger the debugger, e.g. CurveFit * ResetDebuggerState(debuggerState) * // now the debugger is in the same state as before *
References DEBUGGER_DEBUG_ON_ERROR, DEBUGGER_ENABLED, DEBUGGER_NVAR_CHECKING.
Referenced by IH_Cleanup.
variable DisableDebugOnError()
Disable Debug on Error.
1 if it was enabled, 0 if not, pass this value to ResetDebugOnError()
Referenced by AB_LoadDataWrapper.
variable ResetDebugOnError(variable debugOnError)
Reset Debug on Error state.
debugOnError state before, usually the same value as DisableDebugOnError() returned
Referenced by AB_LoadDataWrapper.
variable GetNumberFromWaveNote(wave wv, string key)
Returns the numeric value of key found in the wave note, returns NaN if it could not be found.
The expected wave note format is: key1:val1;key2:val2; UTF_NOINSTRUMENTATION
References ASSERT_TS, IsEmpty.
Referenced by RemoveUnusedRows, StoreElapsedTime.
variable SetNumberInWaveNote(wave wv, string key, variable val, string format=defaultValue)
Updates the numeric value of key found in the wave note to val
wv wave key key of the Key/Value pair val value of the Key/Value pair format [optional] printf compatible format string to set the conversion to string for val The expected wave note format is: key1:val1;key2:val2;
References ASSERT_TS, IsEmpty.
Referenced by StoreElapsedTime.
string GetStringFromWaveNote(wave wv, string key, string keySep=defaultValue, string listSep=defaultValue)
Return the string value of key found in the wave note default expected wave note format: key1:val1;key2:str2; counterpart of AddEntryIntoWaveNoteAsList when supplied with keySep = "=".
wv wave reference where the WaveNote is taken from key search for the value at key:value; keySep [optional, defaults to :] separation character for (key, value) pairs listSep [optional, defaults to ;] list separation character the value on success. An empty string is returned if it could not be found
References ExtractStringFromPair.
Referenced by AFH_GetChannelUnits, DC_FillDAQDataWaveForTP, PA_GenerateAllPulseWaves, PA_GetSetIndicesHelper, PEXT_Callback, SC_GetSpikeNumbersAndPositions, TP_AutoAmplitudeAndBaseline, TP_AutoBaseline, WB_ParameterWvsNewerThanStim.
string ExtractStringFromPair(string str, string key, string keySep=defaultValue, string listSep=defaultValue)
Same functionality as GetStringFromWaveNote() but accepts a string.
GetStringFromWaveNote()
References ASSERT_TS, IsEmpty.
Referenced by GetStringFromWaveNote, WB_GetWaveNoteEntry.
variable SetStringInWaveNote(wave wv, string key, string str)
Update the string value of key found in the wave note to str
The expected wave note format is: key1:val1;key2:str2;
References ASSERT_TS, IsEmpty.
Referenced by DC_FillDAQDataWaveForTP, GetDAQDataWave, PA_GenerateAllPulseWaves, PA_PulseHasFailed, PEXT_ButtonProc, TP_AutoAmplitudeAndBaseline, TP_AutoBaseline, TP_CreateOverrideResults, TP_StoreTP.
string PossiblyUnquoteName(string name, string quote)
Remove the surrounding quotes from the string if they are present.
References ASSERT, isEmpty.
Referenced by GetControlSettingStr.
variable AddEntryIntoWaveNoteAsList(wave wv, string key, variable var=defaultValue, string str=defaultValue, variable appendCR=defaultValue, variable replaceEntry=defaultValue, string format=defaultValue)
Structured writing of numerical values with names into wave notes.
The general layout is key1 = var;key2 = str; and the note is never prefixed with a carriage return ("\r"). wv wave to add the wave note to key string identifier var variable to output str string to output appendCR 0 (default) or 1, should a carriage return ("\r") be appended to the note replaceEntry 0 (default) or 1, should existing keys named key be replaced (does only work reliable in wave note lists without carriage returns). format [optional, defaults to g] format string used for converting var to str
References ASSERT, IsEmpty.
Referenced by AddChannelUnitFromLBN, AR_HandleRanges, CalculateAverage, DC_PlaceDataInDAQConfigWave, GetDAQConfigWave, SBE_ExportSweepBrowser, WB_GetStimSet, WB_MakeWaveBuilderWave.
variable HasEntryInWaveNoteList(wave wv, string key, string value)
Checks if key = value; can be found in the wave note.
Ignores spaces around the equal ("=") sign. AddEntryIntoWaveNoteAsList()
variable IsWaveDisplayedOnGraph(string win, WaveOrNull wv=defaultValue, dfref dfr=defaultValue)
Check if a given wave, or at least one wave from the dfr, is displayed on a graph.
one if one is displayed, zero otherwise
References ASSERT, COUNTOBJECTS_WAVES, DataFolderExistsDFR, GetListOfObjects, GetRowIndex, ROWS.
variable KillCursorInGraphs(string graphs, string cursorName)
Kill all cursors in a given list of graphs.
graphs semicolon separated list of graph names cursorName name of cursor as string
References ASSERT, WindowExists.
Referenced by TimeAlignHandleCursorDisplay.
string FindCursorInGraphs(string graphs, string cursorName)
Find the first match for a given cursor in a list of graph names.
graphs semicolon separated list of graph names cursorName name of cursor as string graph where cursor was found
References ASSERT, IsEmpty, WindowExists.
Referenced by TimeAlignHandleCursorDisplay.
variable GetCursorXPositionAB(string graph, variable *csrAx, variable *csrBx)
get the x value of the cursors A and B
Todomake this a generic cursor getter function and merge with cursors() in SF_FormulaExecutor graph where the cursor are csrAx Position of cursor A csrBx Position of cursor B
References ASSERT, isEmpty, WindowExists.
Referenced by TimeAlignMainWindow.
variable RemoveAnnotationsFromGraph(string graph)
Removes all annotations from the graph.
Referenced by PA_AddColorScales, PA_ClearGraphs, PA_ShowPulses, SCOPE_CreateGraph.
string LineBreakingIntoPar(string str, variable minimumWidth=defaultValue)
Break a string into multiple lines.
All spaces and tabs which are not followed by numbers are replace by carriage returns (\r) if the minimum width was reached. A generic solution would either implement the real deal Knuth, Donald E.; Plass, Michael F. (1981), Breaking paragraphs into lines Software: Practice and Experience 11 (11): 1119-1184, doi:10.1002/spe.4380111102. or translate 1 from C++ to Igor Pro. str string to break into lines minimumWidth [optional, defaults to zero] Each line, except the last one, will have at least this length
References ASSERT, IsFinite, IsNaN, str2numSafe.
Referenced by LBV_GenerateTraceNames, WBP_UpdateParameterWave.
dfref UniqueDataFolder(dfref dfr, string baseName)
Returns a reference to a newly created datafolder.
Basically a datafolder aware version of UniqueName for datafolders dfr datafolder reference where the new datafolder should be created baseName first part of the datafolder, might be shortend due to Igor Pro limitations
References ASSERT_TS, isEmpty, UniqueDataFolderName.
Referenced by AB_AddMapEntry, AB_LoadLabNotebookFromIgor, AB_LoadStimsetRAW, AB_LoadStimsetTemplateWaves, AB_LoadSweepFromIgor, AB_LoadWave, DB_SetUserData, GetUniqueTempPath, SB_SetUserData, SBE_ExportSweepBrowser, SWS_DeleteDataWaves.
string UniqueDataFolderName(dfref dfr, string baseName)
Return an absolute unique data folder name which does not exist in dfr.
dfr datafolder to search baseName first part of the datafolder, must be a valid Igor Pro object name
References ASSERT_TS, DataFolderExistsDFR, DEBUGPRINT_TS, isEmpty, MAX_OBJECT_NAME_LENGTH_IN_BYTES.
Referenced by RenameDataFolderToUniqueName, UniqueDataFolder, UpgradeDataFolderLocation.
string UniqueWaveName(dfref dfr, string baseName)
Returns a wave name not used in the given datafolder.
Basically a datafolder aware version of UniqueName for datafolders dfr datafolder reference where the new datafolder should be created baseName first part of the wave name, might be shorted due to Igor Pro limitations
References ASSERT, DataFolderExistsDFR, DEBUGPRINT, isEmpty, MAX_OBJECT_NAME_LENGTH_IN_BYTES.
string RemovePrefix(string str, string start=defaultValue, variable regExp=defaultValue)
Remove a prefix from a string.
Same semantics as the RemoveEnding builtin for regExp == 0. str string to potentially remove something from its beginning start [optional, defaults to the first character] Remove this from the begin of str regExp [optional, defaults to false] If start is a simple string (false) or a regular expression (true)
References AssertOnAndClearRTError.
Referenced by AB_AddMapEntry, AB_LoadWave, AverageWavesFromSameYAxisIfReq, GetAllDevices, MEN_OpenAboutDialog, NWB_LoadCustomWave, NWB_WriteStimsetCustomWave, ParsePopupMenuValue, RemovePrefixFromListItem, SB_GetChannelInfoFromGraph, SBE_ExportSweepBrowser, SC_SpikePositionQC.
string UniqueFileOrFolder(string symbPath, string baseName, string suffix=defaultValue)
Returns a unique and non-existing file or folder name.
This function must not be used for security relevant purposes, as for that the check-and-file-creation must be an atomic operation. symbPath symbolic path baseName base name of the file, must not be empty suffix file/folder suffix
References ASSERT, isEmpty.
Referenced by SaveExperimentSpecial, UploadCrashDumps, UploadLogFiles.
string GetExperimentName()
Return the name of the experiment without the file suffix.
Referenced by ASSERT, ASSERT_TS, GetExperimentFileType.
string GetExperimentFileType()
Return the experiment file type.
References GetExperimentName, UNTITLED_EXPERIMENT.
Referenced by ASSERT, ASSERT_TS.
string GetTimeStamp(variable secondsSinceIgorEpoch=defaultValue, variable humanReadable=defaultValue)
Return a formatted timestamp of the form YY_MM_DD_HHMMSS
Uses the local time zone and not UTC. humanReadable [optional, default to false] Return a format viable for display in a GUI secondsSinceIgorEpoch [optional, defaults to number of seconds until now] Seconds since the Igor Pro epoch (1/1/1904)
Referenced by CONF_RestoreDAEphys, DAP_FormatCommentString, NWB_ExportWithDialog, NWB_GetFileForExport, SaveExperimentSpecial.
variable CALL_FUNCTION_LIST_PROTOTYPE(string str)
Function prototype for use with CallFunctionForEachListItem.
variable CALL_FUNCTION_LIST_PROTOTYPE_TS(string str)
Function prototype for use with CallFunctionForEachListItem.
variable CallFunctionForEachListItem(CALL_FUNCTION_LIST_PROTOTYPE f, string list, string sep=defaultValue)
Convenience function to call the function f with each list item.
The function's type must be CALL_FUNCTION_LIST_PROTOTYPE where the return type is ignored.
Referenced by CloseNWBFile, DAP_SerializeAllCommentNBs, DQM_CallFuncForDevicesYoked, SaveExperimentSpecial, TP_StopTestPulseOnAllDevices, WBP_FinalTabHook, WBP_StartupSettings.
variable CallFunctionForEachListItem_TS(CALL_FUNCTION_LIST_PROTOTYPE_TS f, string list, string sep=defaultValue)
Compatibility wrapper for threadsafe functions f CallFunctionForEachListItem()
Referenced by AB_ClearAnalysisFolder, AB_LoadTPStorageFromIgor, AverageWavesFromSameYAxisIfReq, IH_KillStimSets, IH_KillTemporaries, SaveExperimentSpecial.
variable IsDriveValid(string absPath)
Return true if the given absolute path refers to an existing drive letter.
References FolderExists, GetDrive.
Referenced by CONF_RestoreDAEphys.
string GetDrive(string path)
Return the windows drive letter of the given path.
References ASSERT, GetHFSPath.
Referenced by CreateFolderOnDisk, DAP_CheckSettings, IsDriveValid.
variable CreateFolderOnDisk(string absPath)
Create a folder recursively on disk given an absolute path.
If you pass windows style paths using backslashes remember to always double them.
References ASSERT, FileExists, FolderExists, GetDrive, GetHFSPath.
Referenced by CONF_GetSettingsPath, CONF_RestoreDAEphys, GetSavePath, GetSymbolicPathForDiagnosticsDirectory, PerformMiesTasks, PS_Initialize.
variable GetRowIndex(wave wv, variable val=defaultValue, string str=defaultValue, WaveOrNull refWave=defaultValue)
Return the row index of the given value, string converted to a variable, or wv.
Assumes wv being one dimensional
References ASSERT_TS, IsNumericWave, IsTextWave, IsWaveRefWave, ROWS.
Referenced by AddDAQChannelTypeFromLBN, CreateTiledChannelGraph, DND_ChooseAsset, IsWaveDisplayedOnGraph, NWB_AppendSweepLowLevel, OVS_HighlightSweep, OVS_UpdatePanel, RemoveTracesFromGraph, SB_GetIndexFromSweepDataPath, SBE_AddMissingADTraceInfo, SC_GetHeadstageQCForSetCount, SC_SpontaneousSpikingCheckQC, TimeAlignmentIfReq.
string ListFromList(string list, variable itemBegin, variable itemEnd, string listSep=defaultValue)
return a subset of the input list
list input list itemBegin first item itemEnd last item listSep [optional] list Separation character. default is ";" a list with elements ranging from itemBegin to itemEnd of the input list
References ASSERT.
Referenced by AB_LoadStimsets, NWB_LoadStimsets.
std::tuple< variable, variable > MinMax(variable a, variable b)
Return the minimum and maximum of both values.
Referenced by DecimateWithMethod, IDX_GetSetsInRange, IDX_TotalIndexingListSteps, SBE_ExportSweepBrowser, TimeAlignmentIfReq.
wave DuplicateSubRange(wave wv, variable first, variable last)
Return a new wave from the subrange of the given 1D wave.
References ASSERT, COLS.
Referenced by IDX_GetSetsInRange.
string GetListDifference(string list1, string list2)
calculates the relative complement of list2 in list1
Every list item of list1 must be in list2. also called the set-theoretic difference of list1 and list2 difference as list
Referenced by AB_LoadStimsetFromFile, DAP_CheckAnalysisFunctionAndParameter, ST_GetStimsetList, WBP_UpdateParameterWave.
string GetListOfDataFolders(dfref dfr, variable absolute=defaultValue)
Return a list of datafolders located in dfr
dfr base folder absolute [optional, defaults to false] return absolute paths
References AddPrefixToEachListItem.
Referenced by AB_ClearAnalysisFolder, AB_GetAllDevicesForExperiment.
string GetBaseName(string filePathWithSuffix, string sep=defaultValue)
Return the base name of the file.
Given path/file.suffix this gives file. filePathWithSuffix full path sep [optional, defaults to ":"] character separating the path components
Referenced by WaveListHasSameWaveNames.
string GetFileSuffix(string filePathWithSuffix, string sep=defaultValue)
Return the file extension (suffix)
Given path/file.suffix this gives suffix. filePathWithSuffix full path sep [optional, defaults to ":"] character separating the path components
string GetFolder(string filePathWithSuffix, string sep=defaultValue)
Return the folder of the file.
Given path/file.suffix this gives path. filePathWithSuffix full path sep [optional, defaults to ":"] character separating the path components
Referenced by LoadWaveFromDisk, StoreWaveOnDisk, TurnOffASLR.
string GetFile(string filePathWithSuffix, string sep=defaultValue)
Return the filename with extension.
Given path/file.suffix this gives file.suffix. filePathWithSuffix full path sep [optional, defaults to ":"] character separating the path components
Referenced by AddPayloadEntriesFromFiles, RenameDataFolderToUniqueName.
string GetWindowsPath(string path)
Return the path converted to a windows style path.
Referenced by HasEnoughDiskspaceFree, TurnOffASLR.
string GetHFSPath(string path)
Return the path converted to a HFS style (aka ":" separated) path.
Referenced by CreateFolderOnDisk, GetDrive.
variable SetBit(variable var, variable bit)
Set the given bit mask in var.
Referenced by AB_ExpandListColumn, DP_PopMenuProc_Selection, OVS_ChangeSweepSelectionState, OVS_CheckBoxProc_HS_Select, OVS_UpdatePanel, P_UpdateTTLdecimal, P_UpdateTTLstate.
variable ClearBit(variable var, variable bit)
Clear the given bit mask in var.
Referenced by AB_CollapseListColumn, DP_PopMenuProc_Selection, OVS_ChangeSweepSelectionState, OVS_CheckBoxProc_HS_Select, OVS_UpdatePanel, P_UpdateTTLdecimal, P_UpdateTTLstate.
string BuildList(string format, variable start, variable step, variable stop)
Create a list of strings using the given format in the given range.
format formatting string, must have exactly one specifier which accepts a number start first point of the range step step size for iterating over the range stop last point of the range
References ASSERT.
Referenced by AB_LoadSweepConfigData.
variable GetFreeMemory()
Return the amount of free memory in GB.
Due to memory fragmentation you can not assume that you can still create a wave occupying as much space as returned.
Referenced by DC_Configure, EnsureLargeEnoughWave, PerformMiesTasks.
string RemoveEndingRegExp(string str, string endingRegExp)
Remove the given reguluar expression from the end of the string.
In case the regular expression does not match, the string is returned unaltered. See also DisplayHelpTopic "Regular Expressions".
References ASSERT_TS, isEmpty.
Referenced by CleanupExperimentName, LBV_UpdateLBGraphLegend.
variable SearchWordInString(string str, string word, string *prefix=defaultValue, string *suffix=defaultValue)
Search for a Word inside a String.
str input text in which word should be searched word searchpattern (non-regex-sensitive) prefix (optional) string preceding word. ("" for unmatched pattern) suffix (optional) string succeeding word. example of the usage of SearchStringBase (basically the same as WM GrepString()) embed:rst:leading-asterisk * .. code-block:: igorpro * * Function SearchString(str, substring) * string str, substring * * ASSERT(!IsEmpty(substring), "supplied substring is empty") * WAVE/Z/T wv = SearchStringBase(str, "(.*)\\Q" + substring + "\\E(.*)") * * return WaveExists(wv) * End * 1 if word was found in str and word was not "". 0 if not.
References SearchStringBase.
Referenced by WB_FormulaSwitchToStimset.
wave SearchStringBase(string str, string regex)
More advanced version of SplitString.
supports 6 subpatterns, specified by curly brackets in regex text wave containing subpatterns of regex call
References ASSERT, CountSubstrings.
Referenced by SearchWordInString, WB_StimsetChildren.
variable CountSubstrings(string str, string pattern)
Search for the occurence of pattern in string.
number of occurences
Referenced by SearchStringBase, SF_FormulaPreParser, WB_ParseCombinerFormula, WB_StimsetChildren.
variable GetRowWithSameContent(WaveText refWave, WaveText sourceWave, variable row)
Search the row in refWave which has the same contents as the given row in the sourceWave.
References ASSERT, COLS, ROWS.
Referenced by AB_ExpandListEntry, SB_AddToSweepBrowser.
variable InPlaceRandomShuffle(wave inwave, variable noiseGenMode=defaultValue)
Random shuffle of the wave contents.
Function was taken from: http://www.igorexchange.com/node/1614 author s.r.chinn inwave The wave that will have its rows shuffled. noiseGenMode [optional, defaults to NOISE_GEN_LINEAR_CONGRUENTIAL] type of RNG to use
References NOISE_GEN_LINEAR_CONGRUENTIAL, ROWS.
Referenced by DC_CalculateChannelColumnNo, WB_PulseTrainSegment.
string UniqueTraceName(string graph, string baseName)
Return a unique trace name in the graph.
Remember that it might be necessary to call DoUpdate if you added possibly colliding trace names in the current function run. graph existing graph baseName base name of the trace, must not be empty
References ASSERT, isEmpty.
Referenced by LBV_MakeTraceNameUnique, SBE_ExportSweepBrowser.
variable WaveListHasSameWaveNames(string listOfWaves, string *baseName)
Checks wether the wave names of all waves in the list are equal Returns 1 if true, 0 if false and NaN for empty lists.
listOfWaves list of waves with full path baseName Returns the common baseName if the list has one, otherwise this will be an empty string.
References GetBaseName.
Referenced by AverageWavesFromSameYAxisIfReq.
variable IsBackgroundTaskRunning(string task)
Check wether the given background task is currently running.
Note: Background functions which are currently waiting for their period to be reached are also running. task Named background task identifier, this is not the function set with proc=
Referenced by DQM_BkrdDataAcq, DQM_StartBackgroundTimer, IsDeviceActiveWithBGTask, RA_HandleITI_MD, TPM_BkrdTPMD.
variable PopCount(variable value)
Count the number of ones in value
value will be truncated to an integer value
Referenced by CreateTiledChannelGraph.
variable NewRandomSeed()
Initializes the random number generator with a new seed between (0,1] The time base is assumed to be at least 0.1 microsecond precise, so a new seed is available every 0.1 microsecond.
Usage example for the case that one needs n non reproducible random numbers. Whenever the following code block is executed a new seed is set, resulting in a different series of numbers embed:rst:leading-asterisk * .. code-block:: igorpro * * Make/D/N=(n) newRandoms * NewRandomSeed() // Initialize random number series with a new seed * newRandoms[] = GetReproducibleRandom() // Get n randoms from the new series * *
Referenced by GetUniqueSymbolicPath.
variable GetReproducibleRandom()
Return a random value in the range (0,1] which can be used as a seed for SetRandomSeed
Return a reproducible random number depending on the RNG seed.
References NOISE_GEN_MERSENNE_TWISTER.
Referenced by GenerateRFC4122UUID, GetUniqueInteger, GetUniqueSymbolicPath.
variable GetUniqueInteger()
Return a unique integer.
The returned values can not be used for statistical purposes as the distribution is not uniform anymore.
References GetReproducibleRandom.
Referenced by CONF_JSONToWindow, CONF_RestoreDAEphys, SCOPE_UpdateOscilloscopeData.
string AddPrefixToEachListItem(string prefix, string list, string sep=defaultValue)
Add a string prefix to each list item and return the new list.
Referenced by GetListOfDataFolders, GetListOfObjects.
string AddSuffixToEachListItem(string suffix, string list, string sep=defaultValue)
Add a string suffix to each list item and return the new list.
string RemovePrefixFromListItem(string prefix, string list, string listSep=defaultValue, variable regExp=defaultValue)
Remove a string prefix from each list item and return the new list.
References RemovePrefix.
variable FuncRefIsAssigned(string funcInfo)
Check wether the function reference points to the prototype function or to an assigned function.
Due to Igor Pro limitations you need to pass the function info from FuncRefInfo and not the function reference itself. 1 if pointing to prototype function, 0 otherwise
References ASSERT_TS, isEmpty, IsFinite.
Referenced by AFH_CheckAnalysisParameter, AFH_GetAnalysisFunctions, AFH_GetHelpForAnalysisParameter, AFH_GetListOfAnalysisParams, AFM_CallAnalysisFunctions, DAP_CheckAnalysisFunctionAndParameter, PEXT_ButtonProc, PEXT_Callback.
variable DateTimeInUTC()
Return the seconds, including fractional part, since Igor Pro epoch (1/1/1904) in UTC time zone.
Referenced by GetISO8601TimeStamp.
string GetISO8601TimeStamp(variable secondsSinceIgorEpoch=defaultValue, variable numFracSecondsDigits=defaultValue, variable localTimeZone=defaultValue)
Return a string in ISO 8601 format with timezone UTC.
secondsSinceIgorEpoch [optional, defaults to number of seconds until now] Seconds since the Igor Pro epoch (1/1/1904) in UTC (or local time zone depending on localTimeZone) numFracSecondsDigits [optional, defaults to zero] Number of sub-second digits localTimeZone [optional, defaults to false] Use the local time zone instead of UTC
References ASSERT_TS, DateTimeInUTC, IsInteger.
variable ParseUnit(string unitWithPrefix, string *prefix, variable *numPrefix, string *unit)
Parses a simple unit with prefix into its prefix and unit.
Note: The currently allowed units are the SI base units [1] and other common derived units. And in accordance to SI definitions, "kg" is a base unit. unitWithPrefix string to parse, examples are "ms" or "kHz" prefix symbol of decimal multipler of the unit, see below or [1] chapter 3 for the full list numPrefix numerical value of the decimal multiplier unit unit embed:rst:leading-asterisk * * ===== ====== =============== * Name Symbol Numerical value * ===== ====== =============== * yotta Y 1e24 * zetta Z 1e21 * exa E 1e18 * peta P 1e15 * tera T 1e12 * giga G 1e9 * mega M 1e6 * kilo k 1e3 * hecto h 1e2 * deca da 1e1 * deci d 1e-1 * centi c 1e-2 * milli m 1e-3 * micro mu 1e-6 * nano n 1e-9 * pico p 1e-12 * femto f 1e-15 * atto a 1e-18 * zepto z 1e-21 * yocto y 1e-24 * ===== ====== =============== * * [1]: 8th edition of the SI Brochure (2014), http://www.bipm.org/en/publications/si-brochure
References ASSERT_TS, GetDecimalMultiplierValue, isEmpty, IsEmpty.
variable GetDecimalMultiplierValue(string prefix)
Return the numerical value of a SI decimal multiplier.
ParseUnit
References ASSERT_TS, isEmpty, ROWS.
Referenced by ParseUnit.
variable QuerySetIgorOption(string name, variable globalSymbol=defaultValue)
Query a numeric option settable with SetIgorOption
name name of the keyword/setting globalSymbol [optional, defaults to false] name refers to a global symbol set via poundDefine
Referenced by DP_OpenDebugPanel, DP_WindowHook, MEN_OpenBackgroundWatcherPanel.
variable ForceRecompile()
Force recompilation of all procedure files.
Uses the "Operation Queue".
variable ParseISO8601TimeStamp(string timestamp)
Parse a ISO8601 timestamp, e.g. created by GetISO8601TimeStamp(), and returns the number of seconds, including fractional parts, since Igor Pro epoch (1/1/1904) in UTC time zone.
Accepts also the following specialities: no UTC timezone specifier (UTC timezone is still used) /T between date and time fractional seconds ,/. as decimal separator
References ASSERT_TS, IsEmpty.
string GetIgorExtensionFolderName()
Return the disc folder name where the XOPs are located.
Distinguishes between i386 and x64 Igor versions
Referenced by CHI_CheckInstallation.
string GetIgorExecutable()
Return an Igor-style path to the Igor Pro executable.
string ResolveAlias(string path, string pathName=defaultValue)
Recursively resolve shortcuts to files/directories.
full path or an empty string if the file does not exist or the shortcut points to a non existing file/folder
References ResolveAlias.
Referenced by FileExists, FolderExists, GetAllFilesRecursivelyFromPath, GetFileSize, GetFileVersion, ResolveAlias.
variable GetArchitectureBits()
Return the number of bits of the architecture Igor Pro was built for.
Referenced by CHI_CheckInstallation, DC_PrepareLBNEntries, NWB_AddGeneratorString.
string GetIgorProVersion()
Return the Igor Pro version string.
Referenced by ASSERT, ASSERT_TS, GetSymbolicPathForDiagnosticsDirectory.
string GetIgorProBuildVersion()
Return the Igor Pro build version string.
This allows to distinguish different builds from the same major/minor version.
Referenced by DC_PrepareLBNEntries, NWB_AddGeneratorString.
string GetUniqueSymbolicPath(string prefix=defaultValue)
Return a unique symbolic path name.
embed:rst:leading-asterisk * .. code-block:: igorpro * * string symbPath = GetUniqueSymbolicPath() * NewPath/Q/O $symbPath, "C:" *
References GetReproducibleRandom, NewRandomSeed.
Referenced by CHI_CheckInstallation, DAP_LoadBuiltinStimsets, DP_FillDebugPanelWaves, GetAllFilesRecursivelyFromPath, GetSavePath, UploadCrashDumps, UploadLogFiles.
string GetAllFilesRecursivelyFromPath(string pathName, string extension=defaultValue)
Return a list of all files from the given symbolic path and its subfolders. The list is pipe (|) separated as the semicolon (;) is a valid character in filenames.
Note: This function does not work on MacOSX as there filenames are allowed to have pipe symbols in them. pathName igor symbolic path to search recursively extension [optional, defaults to all files] file suffixes to search for
References ASSERT, GetAllFilesRecursivelyFromPath, GetUniqueSymbolicPath, isEmpty, ResolveAlias.
Referenced by AB_ScanFolder, CHI_CheckInstallation, CONF_GetConfigFiles, DAP_LoadBuiltinStimsets, DP_FillDebugPanelWaves, GetAllFilesRecursivelyFromPath, StartMultiExperimentProcessWrapper, UploadCrashDumps.
string TextWaveToList(WaveTextOrNull txtWave, string rowSep, string colSep=defaultValue, string layerSep=defaultValue, string chunkSep=defaultValue, variable stopOnEmpty=defaultValue, variable maxElements=defaultValue)
Convert a text wave to string list.
txtWave input text wave rowSep separator for row entries colSep [optional, default = ","] separator for column entries layerSep [optional, default = ":"] separator for layer entries chunkSep [optional, default = "/"] separator for chunk entries stopOnEmpty [optional, default = 0] when 1 stops generating the list when an empty string entry in txtWave is encountered maxElements [optional, defaults to inf] output only the first maxElements entries string with wave entries separated as list using given separators Counterpart ConvertListToTextWave NumericWaveToList
References ASSERT_TS, CHUNKS, COLS, IsEmpty, IsInteger, IsTextWave, LAYERS, ROWS.
Referenced by ASSERT, GetCodeForWaveContents, GetUniqueTextEntriesFromList.
wave ListToTextWaveMD(string list, variable dims, string rowSep=defaultValue, string colSep=defaultValue, string laySep=defaultValue, string chuSep=defaultValue)
Converts a list to a multi dimensional text wave, treating it row major order The output wave does not contain unused dimensions, so if dims = 4 is specified but no chunk separator is found then the returned wave is 3 dimensional. An empty list results in a zero dimensional wave.
list input string with list dims number of dimensions the output text wave should have rowSep [optional, default = ";"] row separator colSep [optional, default = ","] column separator laySep [optional, default = ":"] layer separator chuSep [optional, default = "/"] chunk separator text wave with at least dims dimensions The following call ListToTextWaveMD("1/5/6/:8/:,;2/:,;3/7/:,;4/:,;", 4, rowSep=";", colSep=",",laySep=":", chuSep="/") returns 'free'[0][0][0][0]= {"1","2","3","4"} 'free'[0][0][1][0]= {"8","","",""} 'free'[0][0][0][1]= {"5","","7",""} 'free'[0][0][1][1]= {"","","",""} 'free'[0][0][0][2]= {"6","","",""} 'free'[0][0][1][2]= {"","","",""}
References ASSERT_TS, isNull.
Referenced by EP_EpochStrToWave.
string ReplicateString(string str, variable numTotalCopies)
string NumericWaveToList(WaveOrNull wv, string sep, string format=defaultValue, string colSep=defaultValue)
Convert a numeric wave to string list.
Counterpart ListToNumericWave TextWaveToList wv numeric wave sep separator colSep [optional, default = ,] separator for column entries format [optional, defaults to g] sprintf conversion specifier
Referenced by AD_FillWaves, AD_GetDAScaleFailMsg, AD_GetRheobaseFailMsg, CA_WaveCRCs, CONF_GetDAEphysActiveHeadstages, DEBUGPRINT, FindLevelWrapper, PA_PulseHasFailed, PSQ_CR_DetermineCycles, PSQ_Ramp, SC_AddPulseRegionLBNEntries, SC_GetHeadstageQCForSetCount, SC_GetPulseIndizes, SC_GetTrials, SC_HeadstageQC, SC_SpikeCountsCalc, SC_SpikeCountsQC, SC_SpikePositionQC, SC_SpontaneousSpikingCheckQC, ShowSetVariableLimitsSelectionPopup, TP_AutoAmplitudeAndBaseline, TP_AutoBaseline, TP_CreateOverrideResults, WB_AddAnalysisParameterIntoWPT, WB_MakeWaveBuilderWave, WBP_ListBoxProc_AnalysisParams.
wave ListToNumericWave(string list, string sep, variable type=defaultValue)
Convert a list to a numeric wave.
Counterpart NumericWaveToList(). TextWaveToList list list with numeric entries sep separator type [optional, defaults to double precision float (IGOR_TYPE_64BIT_FLOAT)] type of the created numeric wave
Referenced by AD_SelectResult, AFH_GetAnalysisParamWave, GetTTLChannels, GetTTLChannelsOrBits, PA_GetSetIndicesHelper, PSQ_Chirp, PSQ_PipetteInBath, SC_GetSpikeNumbersAndPositions, SC_SpikeCountsQC, SC_SpikePositionQC, TP_AutoAmplitudeAndBaseline, TP_AutoBaseline, WB_GetPulsesFromPTSweepEpoch, WBP_ButtonProc_AddParam.
wave GetColfromWavewithDimLabel(wave wv, string dimLabel)
Returns the column from a multidimensional wave using the dimlabel.
Referenced by P_SetAllHStoAtmospheric.
wave MakeWaveFree(wave wv)
Turn a persistent wave into a free wave.
variable SetDimensionLabels(wave wv, string list, variable dim, variable startPos=defaultValue)
Sets the dimension labels of a wave.
wv Wave to add dim labels list List of dimension labels, semicolon separated. dim Wave dimension, see, WaveDimensions startPos [optional, defaults to 0] First dimLabel index
Referenced by FindLevelWrapper, GetDA_EphysGuiStateNum, GetDA_EphysGuiStateTxT, GetDandiDialogWave, GetDandiSetProperties, GetLBNumericalDescription, GetOverlaySweepSelectionChoices, GetTPResults, GetTPSettings, GetTPSettingsCalculated, GetTPSettingsFree, GetValidAcqStateTransitions, TP_CreateOverrideResults, TP_StoreTP, TUD_SetUserData, TUD_SetUserDataFromWaves.
variable CheckIfClose(variable var1, variable var2, variable tol=defaultValue, variable strong_or_weak=defaultValue)
Compare two variables and determines if they are close.
Based on the implementation of "Floating-point comparison algorithms" in the C++ Boost unit testing framework. Literature: The art of computer programming (Vol II). Donald. E. Knuth. 0-201-89684-2. Addison-Wesley Professional; 3 edition, page 234 equation (34) and (35). var1 first variable var2 second variable tol [optional, defaults to 1e-8] tolerance strong_or_weak [optional, defaults to strong] type of condition, can be zero for weak or 1 for strong
Referenced by DAG_GetNumericalValue, DAP_CheckHeadStage, ED_createWaveNoteTags, MSQ_FastRheoEst, PA_NeedsForcedScaleBar, PSQ_CheckSamplingFrequencyAndStoreInLabnotebook, PSQ_Rheobase, PSQ_SquarePulse, ReachTargetVoltage.
variable CheckIfSmall(variable var, variable tol=defaultValue)
Test if a variable is small using the inequality $ | var | < | tol | $.
var variable tol [optional, defaults to 1e-8] tolerance
Referenced by DAP_CheckHeadStage, MSQ_DAScale, PSQ_DAScale, PSQ_Ramp, PSQ_Rheobase, PSQ_SquarePulse.
variable ListHasOnlyOneUniqueEntry(string list, string sep=defaultValue)
Check if all elements of the string list are the same.
Returns true for lists with less than one element
Referenced by AverageWavesFromSameYAxisIfReq, SBE_ExportSweepBrowser.
wave ExtractFromSubrange(string listOfRanges, variable dim)
Extract the values of a list of subrange specifications See also DisplayHelpTopic "Subrange Display".
Example invocations: embed:rst:leading-asterisk * .. code-block:: igorpro * * WAVE ranges = ExtractFromSubrange("[3,4]_[*]_[1, *;4]_[]_[5][]", 0) * listOfRanges list of subrange specifications separated by **_** dim dimension to extract 2-dim wave with the start, stop, step as columns and rows as number of elements. Returns -1 instead of * or ``. An invalid wave reference is returned on parsing errors.
Referenced by AverageWavesFromSameYAxisIfReq, OVS_ParseIgnoreList.
variable IsValidObjectName(string name)
Check if a name for an object adheres to the strict naming rules.
DisplayHelpTopic "Standard Object Names"
Referenced by AFH_IsValidAnalysisParameter, createDFWithAllParents, DAP_GetNIDeviceList, StoreWaveOnDisk, TUD_ConvertTraceNameToRowIndex, UpgradeDataFolderLocation, UpgradeWaveLocationAndGetIt.
variable IsValidLiberalObjectName(string name)
Check if a name for an object adheres to the liberal naming rules.
DisplayHelpTopic "Liberal Object Names"
Referenced by CheckDimensionLabels, ED_FindIndizesAndRedimension.
static variable NameChecker(string name, variable liberal)
variable FindNextPower(variable a, variable p)
Find an integer x which is larger than a but the smallest possible power of p.
$ x > a $ where $ x = c^p $ holds and $ x $ is the smallest possible value.
Referenced by DC_CalculateDAQDataWaveLength, TP_GetPowerSpectrumLength.
variable FindPreviousPower(variable a, variable p)
Find an integer x which is smaller than a but the largest possible power of p.
$ x < a $ where $ x = c^p $ holds and $ x $ is the largest possible value.
Referenced by DC_MakeHelperWaves.
wave DeepCopyWaveRefWave(WaveRefWave src, variable dimension=defaultValue, variable index=defaultValue, wave indexWave=defaultValue)
Return a wave with deep copies of all referenced waves.
The deep copied waves will be free waves. Does not allow invalid wave references in src. src wave reference wave dimension [optional] copy only a single dimension, requires index or indexWave as well index [optional] specifies the index into dimension indexWave [optional] specifies the indizes into dimension, allows for differing indizes per src entry
Referenced by CA_StoreEntryIntoCache, CA_TryFetchingEntryFromCache, OOD_Debugging, OOD_GetRegionsFromStimsets.
variable IsTextWave(wave wv)
Return 1 if the wave is a text wave, zero otherwise UTF_NOINSTRUMENTATION.
Referenced by BinarySearchText, GetRowIndex, GetUniqueEntries, RemoveTextWaveEntry1D, TextWaveToList.
variable IsNumericWave(wave wv)
Return 1 if the wave is a numeric wave, zero otherwise UTF_NOINSTRUMENTATION.
Referenced by FindLevelWrapper, GetRowIndex, ValueCanBeWritten.
variable IsWaveRefWave(wave wv)
Return 1 if the wave is a wave reference wave, zero otherwise UTF_NOINSTRUMENTATION.
Referenced by CA_RecursiveWavemodCRC, CA_StoreEntryIntoCache, CA_TryFetchingEntryFromCache, CheckDimensionLabels, DC_CheckIfDataWaveHasBorderVals, DC_FillDAQDataWaveForTP, ExtractOneDimDataFromSweep, GetRowIndex, GetWaveSize, IsValidSweepAndConfig, IsValidSweepWave, MoveWaveWithOverwrite.
variable IsFloatingPointWave(wave wv)
Return 1 if the wave is a floating point wave UTF_NOINSTRUMENTATION.
Referenced by DC_InitDataHoldingWave, ED_AddEntryToLabnotebook, TP_AutoFitBaseline, ZapNaNs, ZeroWaveImpl.
variable IsGlobalWave(wave wv)
Return 1 if the wave is a global wave (not a null wave and not a free wave)
Referenced by CreateBackupWave, GetBackupWave.
variable IsComplexWave(wave wv)
Return 1 if the wave is a complex wave.
string GetSystemUserName()
Return the user name of the running user.
Referenced by CreateMiesVersion, GetSymbolicPathForDiagnosticsDirectory.
variable ControlWindowToFront()
Bring the control window (the window with the command line) to the front of the desktop.
Referenced by AB_ButtonProc_OpenCommentNB, AB_ButtonProc_ResaveAsNWB, AB_ButtonProc_SelectStimSets, AB_HasCompatibleVersion, AB_ScanFolder, AD_SelectResult, AI_OpenMCCs, ASSERT, BSP_CheckProc_ChangedSetting, BUG, ButtonRestoreBackup, CA_OutputCacheStatistics, CHI_CheckInstallation, CONF_AutoLoader, CONF_OpenConfigInNotebook, CONF_SaveWindow, CreateMiesVersion, CreateTiledChannelGraph, DAP_CheckAnalysisFunctionAndParameter, DAP_CheckHeadStage, DAP_CheckPressureSettings, DAP_CheckSettings, DAP_CheckSettingsAcrossYoked, DAP_CheckStimset, DAP_EphysPanelStartUpSettings, DAP_GetNiceAmplifierChannelList, DAP_LockDevice, DAP_TabControlFinalHook, DB_LockToDevice, DB_ResetAndStoreCurrentDBPanel, DB_UpdateToLastSweep, DC_Configure, DC_PlaceDataInDAQDataWave, Downsample, DQ_ApplyAutoBias, ED_createAsyncWaveNoteTags, FitResistance, LBV_PlotAllAnalysisFunctionLBNKeys, MSQ_CommonPreDAQ, MSQ_DAScale, MSQ_FastRheoEst, NWB_CheckForMissingSweeps, NWB_ExportAllData, NWB_ExportAllStimsets, NWB_LoadStimset, NWB_WriteStimsetTemplateWaves, OVS_IgnoreHeadstageInOverlay, OVS_ParseIgnoreList, P_ButtonProc_Enable, P_ButtonProc_UserPressure, PSQ_Chirp, PSQ_CR_FindDependentAnalysisParameter, PSQ_DAScale, PSQ_PipetteInBath, PSQ_Ramp, PSQ_Rheobase, PSQ_SquarePulse, ReachTargetVoltage, SaveHistoryLog, SBE_ExportSweepBrowser, SC_ReactToQCFailures, SC_SpikeControl, SearchForInvalidControlProcs, SetAnalysisFunctionIfFuncExists, SetControlInEvent, SI_FindMatchingTableEntry, ST_GetStimsetParameters, ST_SetStimsetParameter, SyncJSON, TP_AutoDisableIfFinished, TP_RecordTP, TPM_BkrdTPFuncMD, TS_StopThreadGroup, UploadCrashDumps, WB_OpenStimulusSetInWaveBuilder, WB_ParseCombinerFormula, WB_SaveStimSet, WBP_ButtonProc_AddParam, WBP_ButtonProc_DeleteSet, WBP_ButtonProc_OpenAnaFuncs, WBP_StartupSettings.
variable GetAlignment(variable val)
Return the alignment of the decimal number (usually a 32bit/64bit pointer)
variable RemoveAllDimLabels(WaveOrNull wv)
Remove the dimlabels of all dimensions with data.
Due to no better solutions the dim labels are actually overwritten with an empty string
Referenced by AddDimLabelsToWP, AddDimLabelsToWPT, SaveLBNumericalDescription.
variable GetMarkerSkip(variable numPoints, variable numMarkers)
Calculate the value for mskip of ModifyGraph
numPoints number of points shown numMarkers desired number of markers
wave GetSetUnion(wave wave1, wave wave2)
Return a wave of the union of all entries from both waves with duplicates removed.
Given {1, 2, 10} and {2, 5, 11} this will return {1, 2, 5, 10, 11}. The order of the returned entries is not defined. TodoIP9 make it threadsafe
Referenced by LBV_GetAllLogbookKeys.
wave GetSetDifference(wave wave1, wave wave2)
Return a wave were all elements which are in both wave1 and wave2 have been removed from wave1.
GetListDifference for string lists
Referenced by FindRange, LBV_GetLogbookKeys, LBV_PlotAllAnalysisFunctionLBNKeys.
static std::tuple< WAVE, variable > GetSetDifferenceNumeric(wave wave1, wave wave2)
static std::tuple< WAVE, variable > GetSetDifferenceText(WaveText wave1, WaveText wave2)
wave GetSetIntersection(wave wave1, wave wave2)
Return a wave with the set theory style intersection of wave1 and wave2.
Given {1, 2, 4, 10} and {2, 5, 11} this will return {2}. Inspired by http://www.igorexchange.com/node/366 but adapted to modern Igor Pro It does work with text waves as well, there it performs case sensitive comparions free wave with the set intersection or an invalid wave reference if the intersection is an empty set
Referenced by AD_SelectResult, EP_GetEpochs, FindRange, LBV_GetTPStorageEntries, LOG_HasRequiredKeys, SBE_GetPulseStartTimesForSel, SC_FilterPulses, TUD_GetUserDataAsWave.
variable KillWindows(string list)
Kill all passed windows.
Silently ignore errors.
Referenced by PA_PreProcessPulses, PA_Update.
variable str2numSafe(string str)
str2num variant with no runtime error on invalid conversions
Referenced by BSP_ParseChannelSelectionControl, DAP_ParsePanelControl, DC_PrepareLBNEntries, ED_WriteChangedValuesToNote, FindIndizes, GetControlSettingVar, GetPanelVersion, LineBreakingIntoPar, P_CheckDeviceAndChannelSelection, PGC_SetAndActivateControl, SetControlInEvent, ShowSetVariableLimitsSelectionPopup, TestPrematureSweepStop, WB_CalculateParameterWithDelta, WBP_ButtonProc_AddParam.
string AskUserForExistingFolder(string baseFolder=defaultValue)
Open a folder selection dialog.
a string denoting the selected folder, or an empty string if nothing was supplied.
Referenced by AB_ButtonProc_SelectDirectory.
string GetAllAxesWithOrientation(string graph, variable axisOrientation)
Return all axes with the given orientation.
graph graph axisOrientation One of AxisOrientationConstants
Referenced by EquallySpaceAxis, SBE_ExportSweepBrowser, SBE_GetSelectedAxis.
variable GetNumFromModifyStr(string info, string key, string listChar, variable item)
Polished version of GetNumFromModifyStr from Readback ModifyStr.ipf
info string as returned by AxisInfo or TraceInfo key keyword listChar empty, { or ( depending on keyword style item return the given element from the extracted list
Referenced by LBV_EntryDescription, PA_GetSetXAxisUserData.
string SortAxisList(string graph, string list)
Return the list of axis sorted from highest to lowest starting value of the axisEnab keyword.
list must be from one orientation, usually something returned by GetAllAxesWithOrientation()
Referenced by EquallySpaceAxis.
string ReplaceWordInString(string word, string str, string replacement)
Replaces all occurences of the string word, treated as regexp word, in str with replacement. Does not ignore case.
Referenced by RestoreCursors, SBE_ExportSweepBrowser.
variable ExecuteListOfFunctions(string funcList)
Execute a list of functions via the Operation Queue.
Special purpose function. Not intended for normal use.
Referenced by DQM_Timer, DQS_Timer, RA_HandleITI, RA_HandleITI_MD.
variable DoAbortNow(string msg)
Wrapper function for Abort which honours our interactive mode setting.
Referenced by AB_CheckPanelVersion, AddSweepToGraph, BSP_CheckProc_ChangedSetting, BSP_GetFolder, BSP_IsActive, BSP_UnHideSettingsPanel, BSP_UpdateSweepControls, DAP_AbortIfUnlocked, DAP_LockDevice, DB_UpdateSweepPlot, GetAxisOrientation, GetSegmentWave, P_DataAcq, RemoveSweepFromGraph, ReplaceWaveWithBackup, SB_UpdateSweepPlot, WBP_DisplaySetInPanel.
string FloatWithMinSigDigits(variable var, variable numMinSignDigits=defaultValue)
Return a floating point value as string rounded to the given number of minimum significant digits.
This allows to specify the minimum number of significant digits. The normal printf/sprintf specifier only allows the maximum number of significant digits for g.
Referenced by PSQ_DAScale.
string NormalizeToEOL(string str, string eol)
Normalize the line endings in the given string to either classic Mac OS/Igor Pro EOLs (\r) or Unix EOLs (\n)
string GetStackTrace(string prefix=defaultValue)
Return a nicely formatted multiline stacktrace.
Referenced by ASSERT, ASSERT_TS.
variable StopAllMSTimers()
Stop all millisecond Igor Pro timers.
variable RelativeNowHighPrec()
Return a time in seconds with high precision, microsecond resolution, using an arbitrary zero point.
Referenced by DQM_StartBackgroundTimer, DQM_Timer, DQS_StartBackgroundTimer, DQS_Timer, RA_PerfAddMark, RA_PerfInitialize, RA_WaitUntiIITIDone, TPS_StartTestPulseForeground.
variable SleepHighPrecision(variable var)
High precision version of the builtin Sleep command.
var time in seconds to busy-sleep (current precision is around 0.1ms)
variable GetMachineEpsilon(variable type)
Return the machine epsilon for the given wave type.
Experimentally determined with Igor Pro 7.08
Referenced by MSQ_DeterminePulseDuration, MSQ_SearchForSpikes, PA_GenerateAllPulseWaves, PSQ_DeterminePulseDuration, PSQ_SearchForSpikes.
variable IsFreeWave(wave wv)
Return true if wv is a free wave, false otherwise.
Referenced by CA_SamplingIntervalKey, GetLBNumericalDescription, ID_AskUserForSettings, MoveWaveWithOverwrite.
variable WaveModCountWrapper(wave wv)
Return the modification count of the (permanent) wave.
Returns NaN when running in a preemptive thread
Referenced by CA_GetWaveModCRC, CA_PulseTimes, GetLBIndexCache, GetLBNidCache, GetLBRowCache, WB_GetStimSet, WB_ParameterWvsNewerThanStim.
string ToPassFail(variable passedOrFailed)
Referenced by AD_GetBaselineChunkFailMsg, AD_GetChirpFailMsg, MSQ_FastRheoEst, PSQ_Chirp, PSQ_DAScale, PSQ_EvaluateBaselinePassed, PSQ_EvaluateBaselineProperties, PSQ_PipetteInBath, PSQ_Ramp, PSQ_SquarePulse, TP_AutoBaseline.
string ToTrueFalse(variable var)
Referenced by CHI_CheckInstallation, TP_AutoBaseline, WB_MakeWaveBuilderWave, WBP_UpdateParameterWave.
variable HasOneValidEntry(wave wv)
Return true if not all wave entries are NaN, false otherwise.
Referenced by CheckDimensionLabels, EnforceIndependentSetting, GetLastSettingEachRAC, GetLastSettingEachSCI, GetLastSettingIndepEachRAC, GetLastSettingIndepEachSCI, GetLastSettingNoCache, MSQ_DAScale, MSQ_FastRheoEst, PSQ_EvaluateBaselineProperties, SC_ProcessPulses.
wave MergeTwoWaves(wave wv1, wave wv2)
Merge two floating point waves labnotebook waves.
The result will hold the finite row entry of either wv1 or wv2.
variable CreateHistoryNotebook()
Create the special Notebook "HistoryCarbonCopy" which will hold a readable copy of the history starting from the time of the notebook creation.
Referenced by DAP_CreateDAEphysPanel, SaveExperimentSpecial.
string GetHistoryNotebookText()
Return the text of the history notebook.
Referenced by NWB_AppendIgorHistoryAndLogFile.
variable AssertOnAndClearRTError()
Helper function to ensure that there is no pending RTE before entering a critical section. If there is a pending RTE then a BUG message is output (which is a CI error).
Not catching any pending RTE would clear this condition silently and valid errors would be suppressed. This is dangerous in regards of data consistency. Not clearing the RTE before calling AbortOnRTE will always trigger the RTE no matter what you do in that line. Any call to GetRTErrMessage() must be done prior to clearing the runtime error in the catch block. Usage: embed:rst:leading-asterisk * .. code-block:: igorpro * * AssertOnAndClearRTError() * try * CriticalFunc(); AbortOnRTE * catch * msg = GetRTErrMessage() * err = ClearRTError() * endtry * *
Referenced by AB_LoadDataWrapper, AB_LoadLabNotebookFromNWB, AFH_CheckAnalysisParameter, AFH_GetHelpForAnalysisParameter, AFM_CallAnalysisFunctions, AI_UpdateAmpModel, ASYNC_IsASYNCRunning, CONF_AllWindowsToJSON, CONF_ControlToJSON, CONF_JSONToWindow, CONF_ParseJSON, CONF_RestoreDAEphys, CONF_RestoreWindow, CONF_SaveDAEphys, CONF_SaveWindow, CONF_WindowToJSON, DAP_CheckProc_AD, DAP_CheckProc_ClampMode, DAP_CheckProc_HedstgeChck, DAP_DAorTTLCheckProc, DAP_WindowHook, DB_WindowHook, DC_PlaceDataInDAQDataWave, DQ_StopOngoingDAQAllLocked, DQM_FIFOMonitor, DQM_StartDAQMultiDevice, DQS_StartDAQSingleDevice, EqualizeVerticalAxesRanges, FFI_Publish, IH_Cleanup, IVS_finishGigOhmSealQCCheck, IVS_SaveExperiment, PA_ShowImage, PA_SpikePositionsForNonVC, PS_ApplyStoredWindowCoordinate, PS_SerializeSettings, PS_StoreWindowCoordinates, PSQ_DAScale, RA_Counter, RemovePrefix, RemoveTracesFromGraph, SaveHistoryLog, SCOPE_ITC_UpdateOscilloscope, SCOPE_NI_UpdateOscilloscope, StartZeroMQSockets, SWS_AfterSweepDataChangeHook, TP_AutoFitBaseline, TP_FitResistance, TPM_BkrdTPFuncMD, TPM_StartTPMultiDeviceLow, TPS_StartTestPulseSingleDevice, TS_GetNewestFromThreadQueue, TS_GetNewestFromThreadQueueMult, TS_ThreadGroupFinished, UploadCrashDumpsDaily, UploadLogFilesDaily.
variable ClearRTError()
Helper function to unconditionally clear a RTE condition It is generally strongly recommended to use.
AssertOnAndClearRTError before critical code sections. For detailed description of the implications AssertOnAndClearRTError
string DAQRunModeToString(variable runMode)
Convert the DAQ run mode to a string.
runMode One of DAQRunModes
Referenced by ASSERT.
string TestPulseRunModeToString(variable runMode)
Convert the Testpulse run mode to a string.
runMode One of TestPulseRunModes
Referenced by ASSERT.
variable ChangeWaveLock(WaveRefWave wv, variable val)
Adapt the wave lock status on the wave and its contained waves.
Referenced by AFM_CallAnalysisFunctions, DAP_CheckSettings, DC_InitDataHoldingWave, NWB_ASYNC_DeserializeStruct.
variable DeleteWavePoint(wave wv, variable dim, variable index)
Deletes one row, column, layer or chunk from a wave Advantages over DeletePoints: Keeps the dimensionality of the wave when deleting the last row, column, layer or chunk in a wave Implements range check Advantages over DeletePoints + KillWaves: The wave reference stays valid.
wv wave where the row, column, layer or chunk should be deleted dim dimension 0 - rows, 1 - column, 2 - layer, 3 - chunk index index where one point in the given dimension is deleted
Referenced by DQM_RemoveDevice, GetDQMActiveDeviceList.
string num2strHighPrec(variable val, variable precision=defaultValue, variable shorten=defaultValue)
Converts a number to a string with specified precision (digits after decimal dot). This function is an extension for the regular num2str that is limited to 5 digits. Input numbers are rounded using the "round-half-to-even" rule to the given precision. The default precision is 5. If val is complex only the real part is converted to a string.
val number that should be converted to a string precision [optional, default 5] number of precision digits after the decimal dot using "round-half-to-even" rounding rule. Precision must be in the range 0 to MAX_DOUBLE_PRECISION. shorten [optional, defaults to false] Remove trailing zeros and optionally the decimal dot to get a minimum length string string with textual number representation
Referenced by GenerateRFC4122UUID.
variable RoundNumber(variable val, variable precision)
Round the given number to the given number of decimal digits.
Referenced by TP_AutoAmplitudeAndBaseline, TP_AutoBaseline.
variable GetASLREnabledState()
Return the per application setting of ASLR for the Igor Pro executable.
See https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-exploit-guard/enable-exploit-protection for the powershell cmdlet documentation. 0 or 1
Referenced by CHI_CheckInstallation.
variable TurnOffASLR()
Turn off ASLR.
Requires administrative privileges via UAC. Only required once for ITC hardware.
References ASSERT, FileExists, GetFolder, GetWindowsPath.
variable IsWindows10()
Check if we are running on Windows 10.
Referenced by CHI_CheckInstallation.
variable GetReferenceTime()
Start a timer for performance measurements.
Usage: embed:rst:leading-asterisk * .. code-block:: igorpro * * variable referenceTime = GetReferenceTime() * // part one to benchmark * print GetReferenceTime(referenceTime) * // part two to benchmark * print GetReferenceTime(referenceTime) * // you can also store all times via * StoreElapsedTime(referenceTime) *
Referenced by DEBUG_TIMER_START, MeasureMidSweepTiming_V3.
variable GetElapsedTime(variable referenceTime)
Get the elapsed time in seconds.
Referenced by DEBUGPRINT_ELAPSED, StoreElapsedTime.
variable StoreElapsedTime(variable referenceTime)
Store the elapsed time in a wave.
References DEBUGPRINT, EnsureLargeEnoughWave, GetElapsedTime, GetElapsedTimeWave, GetNumberFromWaveNote, NOTE_INDEX, SetNumberInWaveNote.
Referenced by DEBUGPRINT_ELAPSED_WAVE, MeasureMidSweepTiming_V3.
variable GetPlotArea(string win, RectD *s)
References RectD::bottom, InitRectD, RectD::left, RectD::right, RectD::top, WindowExists.
Referenced by DC_MakeHelperWaves.
variable HasEnoughDiskspaceFree(string diskPath, variable requiredFreeSpace)
Check that the given path on disk has enough free space.
diskPath path on disk to check requiredFreeSpace required free space in GB
References ASSERT, FolderExists, GetWindowsPath, IsFinite.
Referenced by DAP_CheckSettings.
static variable FindLevelSingle(wave data, variable level, variable edge, variable first, variable last)
References ROWS.
Referenced by FindLevelWrapper.
static wave FindLevelsMult(wave data, variable level, variable edge, variable first, variable last, variable maxNumLevels)
References ROWS.
Referenced by FindLevelWrapper.
wave FindLevelWrapper(wave data, variable level, variable edge, variable mode, variable maxNumLevels=defaultValue)
FindLevel wrapper which handles 2D data without copying data.
data input data, can be either 1D or 2D level level to search edge type of the edge, one of FindLevelEdgeTypes mode mode, one of FindLevelModes maxNumLevels [optional, defaults to number of points/rows] maximum number of levels to find The returned levels are in the wave's row units. FINDLEVEL_MODE_SINGLE: Return a 1D wave with as many rows as columns in the input data Contents are the x values of the first level or NaN if none could be found FINDLEVEL_MODE_MULTI: Returns a 2D WAVE rows being the number of columns in the input data and columns holding all found x values of the levels per data column. In both cases the dimension label of the each column holds the number of found levels in each data colum. This will be always 1 for FINDLEVEL_MODE_SINGLE.
References ASSERT_TS, COLS, FINDLEVEL_EDGE_BOTH, FINDLEVEL_EDGE_DECREASING, FINDLEVEL_EDGE_INCREASING, FINDLEVEL_MODE_MULTI, FINDLEVEL_MODE_SINGLE, FindLevelSingle, FindLevelsMult, IsFinite, IsInteger, IsNumericWave, LAYERS, NumericWaveToList, ROWS, SetDimensionLabels, WaveRef.
Referenced by PA_SpikePositionsForNonVC.
variable GetOpenZFlag()
Return a /Z flag value for the Open operation which works with automated testing.
Referenced by LoadTextFile.
variable SaveTextFile(string data, string fileName, variable=defaultValue, string fileFilter=defaultValue, string message=defaultValue)
Saves string data to a file.
data string containing data to save fileName fileName to use. If the fileName is empty or invalid a file save dialog will be shown. fileFilter [optional, default = "Plain Text Files (*.txt):.txt;All Files:.*;"] file filter string in Igor specific notation. message [optional, default = "Create file"] window title of the save file dialog. NaN if file open dialog was aborted or an error was encountered, 0 otherwise
References ASSERT, IsEmpty.
Referenced by CONF_SaveDAEphys, CONF_SaveWindow, PS_FixPackageLocation, StoreJSON, UploadCrashDumps, UploadLogFiles.
std::tuple< string, string > LoadTextFile(string fileName, string fileFilter=defaultValue, string message=defaultValue)
Load string data from file.
fileName fileName to use. If the fileName is empty or invalid a file load dialog will be shown. fileFilter [optional, default = "Plain Text Files (*.txt):.txt;All Files:.*;"] file filter string in Igor specific notation. message [optional, default = "Select file"] window title of the save file dialog. loaded string data and full path fileName
References GetOpenZFlag, IsEmpty.
Referenced by AddPayloadEntriesFromFiles, CalcHashForFile, CONF_JoinRigFile, CONF_RestoreWindow, DND_FetchAsset, FilterLogfileByDate, GetJSON, NWB_AppendLogFileToString, PS_FixPackageLocation.
variable RemoveTextWaveEntry1D(WaveText w, string entry, variable options=defaultValue, variable all=defaultValue)
Removes found entry from a text wave.
w text wave entry element content to compare options [optional, defaults to "whole wave element"] FindValue/TXOP options all [optional, defaults to false] removes all entries 0 if at least one entry was found, 1 otherwise
References ASSERT, IsTextWave, ROWS.
Referenced by CONF_GetWindowNames, EP_SortEpochs, OVS_RemoveLowCountEntries.
variable StringEndsWith(string str, string suffix)
Checks if a string ends with a specific suffix.
str string to check for suffix suffix to check for 1 if str ends with suffix, 0 otherwise. If str and/or suffix are empty or null 0 is returned.
References IsNull.
Referenced by CONF_WindowToJSON, SplitTextWaveBySuffix.
std::tuple< WaveText, WaveText > SplitTextWaveBySuffix(WaveText source, string suffix)
Splits a 1d text wave into two waves. The first contains elements with a suffix, the second elements without.
source 1d text wave suffix string suffix to distinguish elements two 1d text waves, the first contains all elements with the suffix, the second all elements without
References IsNull, ROWS, StringEndsWith.
Referenced by CONF_AutoLoader, CONF_GatherControlsFromJSON, CONF_TraversalFinder.
variable FileExists(string filepath)
Check wether the given path points to an existing file.
Resolves shortcuts and symlinks recursively.
References ResolveAlias.
Referenced by CreateFolderOnDisk, TurnOffASLR.
variable FolderExists(string folderpath)
Check wether the given path points to an existing folder.
References ResolveAlias.
Referenced by CreateFolderOnDisk, GetSymbolicPathForDiagnosticsDirectory, HasEnoughDiskspaceFree, IsDriveValid.
string GetFileVersion(string filepath)
Return the file version.
References ResolveAlias.
Referenced by CHI_CheckXOP.
variable GetFileSize(string filepath)
Return the file size in bytes.
References ResolveAlias.
Referenced by NWB_GetExportedFileSize.
variable ScaleToIndexWrapper(wave wv, variable scale, variable dim)
wrapper to ScaleToIndex
ScaleToIndex treats input inf to scale always as the last point in a wave. -inf on the other hand is undefined. This wrapper function respects the scaled point wave. -inf refers to the negative end of the scaled wave and +inf is the positive end of the scaled wave. This means that this wrapper function also respects the DimDelta direction of the wave scaling. and always returns the closest matching (existing) point in the wave. This also means that the returned values cannot be negative or larger than the numer of points in the wave. an existing index in wv between 0 and DimSize(wv, dim) - 1
References ASSERT, IsFinite.
Referenced by PA_ShowImage.
variable SyncJSON(variable srcJsonID, variable tgtJsonID, string srcPath, string tgtPath, string srcFile)
Syncs data from a source json into a target json.
srcJsonID json Id of source object tgtJsonID json Id of target object srcPath root path for sync in source object tgtPath root path for sync in target srcFile file name of source JSON rig file, used for more specific error message in case of conflict. If "" is given then a more unspecific error message is given.
References ASSERT, ControlWindowToFront, IsEmpty, IsJsonParentArray, IsNull, JsonSetEmptyArray, ROWS, SyncJSON.
Referenced by CONF_JoinRigFile, SyncJSON.
static variable IsJsonParentArray(variable jsonID, string path)
Returns true if the parent path is an array.
jsonID Id of json path location where parent is checked, for path "/parent/data" the location "/parent" is checked. For path "" the location "" is checked.
Referenced by SyncJSON.
static variable JsonSetEmptyArray(variable jsonID, string path)
Sets an empty array in a json.
jsonID Id of json path location where empty array is placed
Referenced by SyncJSON.
string GetSymbolicPathForDiagnosticsDirectory()
Return the name of a symbolic path which points to the crash dump directory on windows.
References CreateFolderOnDisk, FolderExists, GetIgorProVersion, GetSystemUserName.
Referenced by ShowDiagnosticsDirectory, UploadCrashDumps.
variable ShowDiagnosticsDirectory()
References GetSymbolicPathForDiagnosticsDirectory.
string GenerateRFC4122UUID()
Generate a version 4 UUID according to https://tools.ietf.org/html/rfc4122.
embed:rst:leading-asterisk * .. code-block:: text * * 4.4. Algorithms for Creating a UUID from Truly Random or * Pseudo-Random Numbers * * The version 4 UUID is meant for generating UUIDs from truly-random or * pseudo-random numbers. * * The algorithm is as follows: * * o Set the two most significant bits (bits 6 and 7) of the * clock_seq_hi_and_reserved to zero and one, respectively. * * o Set the four most significant bits (bits 12 through 15) of the * time_hi_and_version field to the 4-bit version number from * Section 4.1.3. * * o Set all the other bits to randomly (or pseudo-randomly) chosen * values. * * See Section 4.5 for a discussion on random numbers. * * [...] * * In the absence of explicit application or presentation protocol * specification to the contrary, a UUID is encoded as a 128-bit object, * as follows: * * The fields are encoded as 16 octets, with the sizes and order of the * fields defined above, and with each field encoded with the Most * Significant Byte first (known as network byte order). Note that the * field names, particularly for multiplexed fields, follow historical * practice. * * 0 1 2 3 * 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 * +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ * | time_low | * +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ * | time_mid | time_hi_and_version | * +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ * |clk_seq_hi_res | clk_seq_low | node (0-1) | * +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ * | node (2-5) | * +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+ * * [...] * * 4.1.3. Version * * The version number is in the most significant 4 bits of the time * stamp (bits 4 through 7 of the time_hi_and_version field). * * The following table lists the currently-defined versions for this * UUID variant. * * Msb0 Msb1 Msb2 Msb3 Version Description * * 0 0 0 1 1 The time-based version * specified in this document. * * 0 0 1 0 2 DCE Security version, with * embedded POSIX UIDs. * * 0 0 1 1 3 The name-based version * specified in this document * that uses MD5 hashing. * * 0 1 0 0 4 The randomly or pseudo- * randomly generated version * specified in this document. * * 0 1 0 1 5 The name-based version * specified in this document * that uses SHA-1 hashing. * * The version is more accurately a sub-type; again, we retain the term * for compatibility. * * See also https://www.rfc-editor.org/errata/eid3546 and https://www.rfc-editor.org/errata/eid1957 for some clarifications.
References GetReproducibleRandom, HexToBinary, num2strHighPrec.
variable HexToNumber(string ch)
Convert a hexadecimal character into a number.
References ASSERT_TS.
Referenced by HexToBinary.
string NumberToHex(variable var)
Convert a number into hexadecimal.
References ASSERT_TS, IsInteger.
wave HexToBinary(string str)
Convert a string in hex format to an unsigned binary wave.
This function works on a byte level so it does not care about endianess.
References ASSERT_TS, HexToNumber.
Referenced by GenerateRFC4122UUID.
string ConvertListToRegexpWithAlternations(string list)
Turn a list of entries into a regular expression with alternations.
Can be used for GetListOfObjects() if you know in advance which entries to filter out.
Referenced by AB_LoadDataWrapper.
variable AddPayloadEntriesFromFiles(variable jsonID, WaveText paths, variable isBinary=defaultValue)
Helper function for UploadCrashDumps.
Fill payload array with content from files
References AddPayloadEntries, GetFile, LoadTextFile, ROWS.
Referenced by UploadCrashDumps, UploadLogFiles.
variable AddPayloadEntries(variable jsonID, WaveText keys, WaveText values, variable isBinary=defaultValue)
Helper function for UploadCrashDumps.
Fill payload array
References ASSERT, ROWS.
Referenced by AddPayloadEntriesFromFiles, GenerateJSONTemplateForUpload, UploadLogFiles.
variable UploadJSONPayload(variable jsonID)
Upload the given JSON document.
See tools/http-upload/upload-json-payload-v1.php for the JSON format description.
References ASSERT.
Referenced by UploadCrashDumps, UploadLogFiles.
wave ConvertToUniqueNumber(WaveText wv, variable doZapNaNs=defaultValue, variable doSort=defaultValue)
Convert a text wave to a double wave with optional support for removing NaNs and sorting.
References GetUniqueEntries, ROWS, ZapNaNs.
Referenced by LayoutGraph.
wave GrepWave(WaveText wv, string regex)
Wrapper for Grep which uses a textwave for input and ouput.
References ROWS.
Referenced by LayoutGraph.
std::tuple< RGBAColor > ParseColorSpec(string str)
Parse a color specification as used by ModifyGraph having an optionl translucency part.
References ASSERT.
Referenced by OVS_HighlightSweep.
std::tuple< variable, variable > WaveMinAndMaxWrapper(wave wv, variable x1=defaultValue, variable x2=defaultValue)
Determine min and max.
References ASSERT_TS.
Referenced by ApplyConstantRateChanges, CalculateTPLikePropsFromSweep, FindRange, GetPopupMenuRates, IsConstant, LBV_LimitXRangeToSelected, MSQ_SearchForSpikes, OOD_GetThresholdLevel, PA_UpdateMinAndMax, PSQ_CR_DetermineBoundsAction, PSQ_SearchForSpikes, SC_GetTrials, WB_PSCSegment, WBP_DisplaySetInPanel.
wave WaveRef(WaveOrNull w, variable row=defaultValue, variable col=defaultValue, variable layer=defaultValue, variable chunk=defaultValue)
Helper function to be able to index waves stored in wave reference waves in wave assignment statements.
The case where wv contains wave references is also covered by the optional parameters. While returned regular waves can be indexed within the assignment as shown in the first example, this does not work for wave reference waves. Thus, the parameters allow to index through the function call. Example for source containing regular waves: embed:rst:leading-asterisk * .. code-block:: igorpro * * Make/FREE data1 = p * Make/FREE data2 = p^2 * Make/FREE/WAVE source = {data1, data2} * * Make/FREE dest * dest[] = WaveRef(source[0])[p] + WaveRef(source[1])[p] // note the direct indexing [p] following WaveRef(...) here * * Example for source containing wave ref waves: embed:rst:leading-asterisk * .. code-block:: igorpro * * Make/FREE data1 = p * Make/FREE/WAVE interm = {data1, data1} * Make/FREE/WAVE source = {interm, interm} * * Make/FREE/WAVE/N=2 dest * dest[] = WaveRef(source[p], row = 0) // direct indexing does not work here, so we index through the optional function parameter * * row, col, layer, chunk are evaluated in this order until one argument is not given. w input wave ref wave row [optional, default = n/a] when param set returns wv[row] typed col [optional, default = n/a] when param row and this set returns wv[row][col] typed layer [optional, default = n/a] when param row, col and this set returns wv[row][col][layer] typed chunk [optional, default = n/a] when param row, col, layer and this set returns wv[row][layer][chunk] typed untyped waveref of wv or typed wave ref of wv when indexed UTF_NOINSTRUMENTATION
Referenced by FindLevelWrapper, PA_CalculateAllAverages, PA_GetSetWaves, PA_ShowImage.
wave GrepTextWave(WaveText in, string regexp, variable invert=defaultValue)
Grep the given regular expression in the text wave.
References ROWS.
Referenced by LBV_GetTPStorageEntries, LBV_PlotAllAnalysisFunctionLBNKeys, PA_ShowPulses.
std::tuple< variable, variable > SymmetrizeRangeAroundZero(variable minimum, variable maximum)
Given a range [a, b] this returns a symmetric range around zero including both elements.
Referenced by PA_AddColorScales.
wave SelectWave(variable condition, WaveOrNull waveIfFalse, WaveOrNull waveIfTrue)
Helper function for multithread statements where ? : does not work with wave references.
The order of arguments is modelled after SelectString/SelectNumber.
Referenced by SC_GetPulseIndizes.
std::tuple< WaveDouble, WaveDouble > DistributeElements(variable numElements, variable offset=defaultValue)
Distribute N elements over a range from 0.0 to 1.0 with spacing.
References ASSERT, GRAPH_DIV_SPACING, IsFinite.
Referenced by EquallySpaceAxis, EquallySpaceAxisPA, PA_AddColorScale.
variable CalculateNiceLength(variable range, variable multiple)
Calculate a nice length which is an integer number of multiple long.
For small values $ 10^{-x} $ times multiple are returned
Referenced by PA_DrawScaleBarsHelper.
wave RemoveUnusedRows(wave wv)
Remove unused rows from the passed wave and return a copy of it.
If the wave is empty with index being zero, we return a wave with one point so that we: can store something non-empty preserve the dimension labels (this can get lost for empty waves when duplication/saving) EnsureLargeEnoughWave()
References ASSERT_TS, GetNumberFromWaveNote, IsInteger, IsNaN, NOTE_INDEX.
Referenced by NWB_WriteLabnoteBooksAndComments, NWB_WriteResultsWaves, NWB_WriteTestpulseData.
variable EqualValuesOrBothNaN(variable left, variable right)
Check wether val1 and val2 are equal or both NaN.
References IsNaN.
Referenced by DAG_GetNumericalValue, P_PublishPressureMethodChange, PA_DetermineConstantSettings, PA_PulseHasFailed, PA_ResetWavesIfRequired.
variable IsConstant(wave wv, variable val, variable ignoreNaN=defaultValue)
Checks wether wv is constant and has the value val
wv wave to check val value to check ignoreNaN [optional, defaults to true] ignore NaN in wv
References IsNaN, ROWS, WaveMinAndMaxWrapper.
Referenced by BSP_RemoveDisabledChannels, DC_PrepareLBNEntries, ED_createAsyncWaveNoteTags, EnforceIndependentSetting, GetDataOffset, GetSamplingInterval, SC_GetSetSweepCount, SC_SpikePositionQC.
string SanitizeFilename(string name)
Sanitize the given name so that it is a nice file name.
References ASSERT.
Referenced by ScreenShotsForDAEphys, ScreenShotsForDataBrowser, ScreenShotsForWaveBuilder.
string MergeLists(string l1, string l2, string sep=defaultValue)
Merges list l1 into l2. Double entries in l2 are kept. "a;b;c;" with "a;d;d;f;" -> "a;d;d;f;b;c;".
References ASSERT, IsEmpty.
Referenced by PA_GenerateAllPulseWaves.
wave DuplicateWaveToFree(wave w)
Duplicates the input wave to a free wave and returns the free wave reference.
Referenced by PA_InitPASIInParts.
wave ZapNaNs(wave data)
Removes all NaNs from the input wave.
References ASSERT_TS, IsFloatingPointWave, ROWS.
Referenced by AD_FillWaves, AD_GetSquarePulseFailMsg, AD_LabnotebookEntryExistsAndIsTrue, AddChannelPropertiesFromLBN, ConvertToUniqueNumber, FindIndizes, GetSweepsWithSetting, MSQ_FastRheoEst, MSQ_GetLBNEntryForHSSCIBool, PSQ_SquarePulse, RecreateSweepWaveFromBackupAndLBN, SB_GetIndexFromSweepDataPath, SC_GetTrials, SC_RegionBlanked, SWS_DeleteDataWaves, TP_AutoBaseline, TP_GetValuesFromTPStorage.
variable BinarySearchText(WaveText theWave, string theText, variable caseSensitive=defaultValue, variable startPos=defaultValue, variable endPos=defaultValue)
Finds the first occurrence of a text within a range of points in a SORTED text wave.
From https://www.wavemetrics.com/code-snippet/binary-search-pre-sorted-text-waves by Jamie Boyd Completely reworked, fixed and removed unused features
References ASSERT_TS, COLS, IsTextWave, ROWS.
string GetIgorInstanceID()
Returns a hex string which is unique for the given Igor Pro session.
It allows to distinguish multiple Igor instances, but is not globally unique.
Referenced by LOG_GenerateEntryTemplate.
variable RenameDataFolderToUniqueName(string path, string suffix)
Rename the given datafolder path to a unique name.
With path root:a:b:c and suffix _old the datafolder is renamed to root:a:b:c_old or if that exists root:a:b:c_old_1 and so on.
References ASSERT_TS, GetFile, UniqueDataFolderName.
Referenced by AB_ReExport.
string GetCodeForWaveContents(WaveText wv)
Prepare wave for inline definition.
Outputs a wave in a format so that it can be initialized with these contents in an Igor Pro procedure file.
References ASSERT, COLS, ROWS, TextWaveToList.
Referenced by WBP_RegenerateEpochParameterNamesCode.
variable StoreCurrentPanelsResizeInfo(string panel)
If the layout of an panel was changed, this function calls the ResizeControlsPanel module functions of the Igor Pro native package to store the changed resize info. The original inteded way to do this was through the Packages GUI, which is clunky for some workflows.
References ASSERT, IsEmpty, panel.
Referenced by AB_BrowserStartupSettings, DB_ResetAndStoreCurrentDBPanel.
string ElideText(string str, variable returnLength)
Elide the given string to the requested length.
References ASSERT, IsInteger.
wave LoadWaveFromDisk(string name)
Load the wave $name.itx from the folder of this procedure file and store it in the static data folder.
References ASSERT, GetFolder, GetStaticDataFolder.
Referenced by GetLBNumericalDescription, SI_LoadMinSampIntFromDisk.
variable StoreWaveOnDisk(wave wv, string name)
Store the given wave as $name.itx in the same folder as this procedure file on disk.
References ASSERT, GetFolder, GetUniqueTempPath, IsValidObjectName, KillOrMoveToTrash, RemoveEmptyDataFolder.
Referenced by SaveLBNumericalDescription.