MIES_Oscilloscope.ipf
const double SCOPE_TIMEAXIS_RESISTANCE_RANGE
Referenced by SCOPE_CreateGraph, SCOPE_GetTPTopAxisStart, SCOPE_UpdateGraph.
const double SCOPE_GREEN
Referenced by SCOPE_CreateGraph.
const double SCOPE_BLUE
Referenced by SCOPE_CreateGraph.
const string RES_FORMAT_STR
Referenced by SCOPE_CreateGraph.
const double PRESSURE_SPECTRUM_PERCENT
Referenced by SCOPE_CreateGraph.
string SCOPE_GetGraph(string device)
References SCOPE_GetPanel.
Referenced by DC_MakeHelperWaves, DQS_DataAcq, RA_WaitUntiIITIDone, SaveExperimentSpecial, SCOPE_CreateGraph, SCOPE_GetTPTopAxisStart, SCOPE_OpenScopeWindow, SCOPE_SetADAxisLabel, SCOPE_UpdateGraph, TPS_StartTestPulseForeground.
string SCOPE_GetPanel(string device)
Referenced by SCOPE_GetGraph, SCOPE_KillScopeWindowIfRequest, SCOPE_OpenScopeWindow, ScreenShotsForDAEphys.
variable SCOPE_OpenScopeWindow(string device)
References SCOPE_GetGraph, SCOPE_GetPanel.
Referenced by DAP_CheckProc_ShowScopeWin, DAP_CreateDAEphysPanel, SCOPE_CreateGraph.
variable SCOPE_KillScopeWindowIfRequest(string device)
References DAG_GetNumericalValue, SCOPE_GetPanel.
Referenced by DAP_CheckProc_ShowScopeWin, DAP_EphysPanelStartUpSettings, TP_Teardown.
variable SCOPE_GetTPTopAxisStart(string device, variable *axisMin)
References GetNumberFromWaveNote, GetTPStorage, NOTE_INDEX, SCOPE_GetGraph, SCOPE_TIMEAXIS_RESISTANCE_RANGE.
Referenced by SCOPE_CreateGraph, SCOPE_UpdateGraph.
variable SCOPE_UpdateGraph(string device, variable dataAcqOrTP)
References ASSERT, AXIS_SCOPE_AD, DAG_GetNumericalValue, DAQ_CHANNEL_TYPE_TP, DATA_ACQUISITION_MODE, GetADCListFromConfig, GetADCTypesFromConfig, GetDACListFromConfig, GetDAQConfigWave, GetOscilloscopeWave, GetTPOscilloscopeWave, GotTPChannelsOnADCs, GUI_SETTING_OSCI_SCALE_INTERVAL, IsNaN, ROWS, SCOPE_GetCheckBoxesForAddons, SCOPE_GetGraph, SCOPE_GetTPTopAxisStart, SCOPE_TIMEAXIS_RESISTANCE_RANGE.
Referenced by DQM_FIFOMonitor, DQS_DataAcq, DQS_FIFOMonitor, TPM_BkrdTPFuncMD, TPS_StartTestPulseForeground, TPS_TestPulseFunc.
static std::tuple< variable, variable, variable > SCOPE_GetCheckBoxesForAddons(string device, variable dataAcqOrTP)
References DAG_GetNumericalValue, TEST_PULSE_MODE.
Referenced by SCOPE_CreateGraph, SCOPE_UpdateGraph.
variable SCOPE_CreateGraph(string device, variable dataAcqOrTP)
References AFH_GetHeadstageFromADC, ASSERT, AXIS_ORIENTATION_LEFT, AXIS_RANGE_INC_AUTOSCALED, AXIS_RANGE_USE_MINMAX, AXIS_SCOPE_AD, AXIS_SCOPE_AD_REGEXP, AXIS_SCOPE_TP_TIME, DAG_GetNumericalValue, DAP_GetSampInt, DAQ_CHANNEL_TYPE_TP, DATA_ACQUISITION_MODE, GetADCListFromConfig, GetADCTypesFromConfig, GetAxesRanges, GetAxisRange, GetDACListFromConfig, GetDAQConfigWave, GetOscilloscopeWave, GetTPOscilloscopeWave, GetTPResults, GetTPSettings, GetTPSettingsCalculated, GetTPStorage, GUI_SETTING_OSCI_SCALE_FIXED, MAX_REGULATOR_PRESSURE, MIN_REGULATOR_PRESSURE, P_GetPressureDataWaveRef, PRESSURE_SPECTRUM_PERCENT, RemoveAnnotationsFromGraph, RemoveTracesFromGraph, RES_FORMAT_STR, ROWS, SCOPE_BLUE, SCOPE_GetCheckBoxesForAddons, SCOPE_GetGraph, SCOPE_GetTPTopAxisStart, SCOPE_GREEN, SCOPE_OpenScopeWindow, SCOPE_SetADAxisLabel, SCOPE_TIMEAXIS_RESISTANCE_RANGE, SetAxesRanges, TEST_PULSE_MODE.
Referenced by DAP_PopMenuProc_OsciUpdMode, DC_Configure.
variable SCOPE_SetADAxisLabel(string device, variable dataAcqOrTP, variable activeHeadStage)
References AFH_GetChannelUnit, AFH_GetHeadstageFromADC, AXIS_SCOPE_AD, DAG_GetNumericalValue, GetADCListFromConfig, GetDAQConfigWave, GetHeadstageColor, ROWS, SCOPE_GetGraph, TEST_PULSE_MODE, XOP_CHANNEL_TYPE_ADC.
Referenced by DAP_SliderProc_MIESHeadStage, SCOPE_CreateGraph.
static variable DoFFT(wave input, wave output, variable col)
Perform FFT on input[col] and write the result into output[col].
References ROWS, TP_GetPowerSpectrumLength.
Referenced by SCOPE_UpdatePowerSpectrum.
static variable SCOPE_UpdatePowerSpectrum(string device)
References COLS, DAG_GetNumericalValue, DoFFT, GetADChannelToMonitor, GetOscilloscopeWave, GetTPOscilloscopeWave, ROVar, ROWS.
Referenced by SCOPE_ITC_UpdateOscilloscope, SCOPE_NI_UpdateOscilloscope.
variable SCOPE_UpdateOscilloscopeData(string device, variable dataAcqOrTP, variable chunk=defaultValue, variable fifoPos=defaultValue, variable deviceID=defaultValue)
Prepares a subset/copy of DAQDataWave for displaying it in the oscilloscope panel.
device panel title dataAcqOrTP One of DATA_ACQUISITION_MODE or TEST_PULSE_MODE chunk Only for TEST_PULSE_MODE and multi device mode; Selects the testpulse to extract fifoPos Position of the hardware DAQ fifo to keep track of the position which will be written next deviceID device ID
References AFH_GetHeadstageFromADC, ASSERT, ASYNC_ThreadReadOut, DAG_GetNumericalValue, DAQ_CHANNEL_TYPE_TP, DATA_ACQUISITION_MODE, DEBUGPRINT, GetADCListFromConfig, GetADCTypesFromConfig, GetDACListFromConfig, GetDAQConfigWave, GetHardwareType, GetHSProperties, GetNrOfTypedChannels, GetScaledDataWave, GetTPOscilloscopeWave, GetTPSettings, GetTPSettingsCalculated, GetUniqueInteger, HARDWARE_ITC_DAC, HARDWARE_NI_DAC, I_CLAMP_MODE, IsFinite, NewRandomSeed, ROWS, SCOPE_ITC_AdjustFIFOPos, SCOPE_ITC_UpdateOscilloscope, SCOPE_NI_UpdateOscilloscope, TEST_PULSE_MODE, TICKS_TO_SECONDS, TP_SendToAnalysis, TP_StoreTP.
Referenced by DQM_FIFOMonitor, DQS_DataAcq, DQS_FIFOMonitor, TPM_BkrdTPFuncMD, TPS_StartTestPulseForeground, TPS_TestPulseFunc.
static variable SCOPE_NI_UpdateOscilloscope(string device, variable dataAcqOrTP, variable deviceiD, variable fifoPos)
References ASSERT, AssertOnAndClearRTError, COLS, DATA_ACQUISITION_MODE, DecimateWithMethod, DECIMATION_NONE, GAIN_AFTER_DAQ, GetDAQDataWave, GetNIFIFOName, GetNumberFromWaveNote, GetOscilloscopeWave, GetScaledDataWave, GetStopCollectionPoint, ROWS, SCOPE_UpdatePowerSpectrum, SWS_GetChannelGains, TEST_PULSE_MODE.
Referenced by SCOPE_UpdateOscilloscopeData.
static variable SCOPE_ITC_UpdateOscilloscope(string device, variable dataAcqOrTP, variable chunk, variable fifoPos)
References ASSERT, AssertOnAndClearRTError, DATA_ACQUISITION_MODE, DecimateWithMethod, DECIMATION_NONE, DP_DebuggingEnabledForCaller, GAIN_AFTER_DAQ, GetADCListFromConfig, GetDACListFromConfig, GetDAQConfigWave, GetDAQDataWave, GetNumberFromWaveNote, GetOscilloscopeWave, GetScaledDataWave, GetStopCollectionPoint, GetTPSettingsCalculated, ROWS, SCOPE_UpdatePowerSpectrum, TEST_PULSE_MODE, WindowExists.
Referenced by SCOPE_UpdateOscilloscopeData.
static variable SCOPE_ITC_AdjustFIFOPos(string device, variable fifopos)
Adjusts the fifo position when using ITC.
device device fifopos fifo position adjusted fifo position
References GetDAQConfigWave, GetDataOffset, GetScaledDataWave, GetStopCollectionPoint, IsNaN, ROWS.
Referenced by SCOPE_UpdateOscilloscopeData.