MIES_OverlaySweeps.ipf
const string OVS_FULL_UPDATE_NOTE
Referenced by OVS_BeginIncrementalUpdate, OVS_EndIncrementalUpdate.
variable OVS_IgnoreHeadstageInOverlay()
This user trace menu function allows the user to select a trace in overlay sweeps mode which should be ignored.
References BSP_GetPanel, ControlWindowToFront, DEBUGPRINT, IsEmpty, IsFinite, IsValidSweepNumber, OVS_AddToIgnoreList, SB_GetIndexFromSweepDataPath, TUD_GetUserData, WindowExists.
string OVS_GetSweepSelectionChoices(string win)
Return a list of choices for the sweep selection popup.
Includes a unique list of the DA stimsets of all available sweeps
References GetOverlaySweepSelectionChoices, GetUniqueEntries, NONE, OVS_GetFolder, OVS_IsActive, OVS_RemoveLowCountEntries, TextWaveToList.
static variable OVS_RemoveLowCountEntries(WaveText stimsets, WaveText setSweepCounts, WaveText dupsRemovedSetSweepCounts, WaveText dupsRemovedSetCycleCounts)
Remove all stimsets which were only acquired once, disregaring RAC/SCI, this means we just look at all sweeps.
References FindIndizes, IsEmpty, NUM_HEADSTAGES, RemoveTextWaveEntry1D, ROWS.
Referenced by OVS_GetSweepSelectionChoices.
dfref OVS_GetFolder(string win)
Return the datafolder reference to the folder storing the listbox and selection wave.
Requires the user data PANEL_FOLDER of the BrowserSettings panel a valid DFREF or an invalid one in case the external panel could not be found
References BSP_GetFolder, DataFolderExistsDFR, MIES_BSP_PANEL_FOLDER.
Referenced by OVS_AddToIgnoreList, OVS_ChangeSweepSelection, OVS_ChangeSweepSelectionState, OVS_CheckBoxProc_HS_Select, OVS_GetHeadstageRemoval, OVS_GetSelectedSweeps, OVS_GetSweepSelectionChoices, OVS_UpdateHeadstageRemoval.
variable OVS_UpdatePanel(string win, variable fullUpdate=defaultValue)
Update the overlay sweep waves.
win databrowser panel or graph fullUpdate [optional, defaults to false] Performs a full update instead of an incremental one. Selects the first sweep if nothing is selected as well. Must be called after the sweeps changed.
References AFH_GetSweepsFromSameRACycle, AFH_GetSweepsFromSameSCI, ASSERT, BSP_GetFolder, BSP_GetLogbookWave, BSP_GetPanel, BSP_GetSweepControlsPanel, BSP_IsDataBrowser, ClearBit, GetCheckBoxState, GetOverlaySweepHeadstageRemoval, GetOverlaySweepSelectionChoices, GetOverlaySweepsListSelWave, GetOverlaySweepsListWave, GetPlainSweepList, GetPopupMenuIndex, GetRowIndex, GetSetVariable, IsFinite, LBN_NUMERICAL_VALUES, LBT_LABNOTEBOOK, LISTBOX_CELL_EDITABLE, LISTBOX_CHECKBOX, LISTBOX_CHECKBOX_SELECTED, MIES_BSP_PANEL_FOLDER, NOTE_NEEDS_UPDATE, NUM_HEADSTAGES, OVS_BeginIncrementalUpdate, OVS_EndIncrementalUpdate, OVS_IsActive, ROWS, SetBit, SetNumberInWaveNote.
Referenced by BSP_CheckProc_OverlaySweeps, DB_UpdateLastSweepControls.
variable OVS_UpdateSweepSelectionChoices(string win, WaveText sweepSelectionChoices)
Update the sweep selection choices for the popup menu.
This function is expensive as it iterates over all sweeps.
References ASSERT, BSP_GetLogbookWave, CLAMPMODE_ENTRY_KEY, ConvertAmplifierModeShortStr, DATA_ACQUISITION_MODE, GetLastSetting, GetNumberFromWaveNote, GetPlainSweepList, GetTTLLabnotebookEntry, IsFinite, LABNOTEBOOK_TTL_SETCYCLECOUNTS, LABNOTEBOOK_TTL_SETSWEEPCOUNTS, LABNOTEBOOK_TTL_STIMSETS, LBN_NUMERICAL_VALUES, LBN_TEXTUAL_VALUES, LBT_LABNOTEBOOK, NOTE_NEEDS_UPDATE, ROWS, SetNumberInWaveNote, STIM_WAVE_NAME_KEY.
Referenced by GetOverlaySweepSelectionChoices.
wave OVS_GetSelectedSweeps(string win, variable mode)
Return the selected sweeps (either indizes or the real sweep numbers)
win window (databrowser or sweepbrowser) mode sweep property OVS_SWEEP_SELECTION_INDEX OVS_SWEEP_SELECTION_SWEEPNO OVS_SWEEP_ALL_SWEEPNO invalid wave reference in case nothing is selected or numeric indizes/sweep numbers depending on mode parameter
References ASSERT, GetOverlaySweepsListSelWave, GetOverlaySweepsListWave, GetPlainSweepList, LISTBOX_CHECKBOX_SELECTED, OVS_GetFolder, OVS_IsActive, OVS_SWEEP_ALL_SWEEPNO, OVS_SWEEP_SELECTION_INDEX, OVS_SWEEP_SELECTION_SWEEPNO, ROWS.
Referenced by DB_UpdateSweepPlot, LBV_LimitXRangeToSelected, SB_UpdateSweepPlot.
variable OVS_ChangeSweepSelectionState(string win, variable newState, variable sweepNo=defaultValue, variable index=defaultValue, WaveOrNull sweeps=defaultValue, variable invertOthers=defaultValue)
Change the selection state of the the given sweep in the listbox wave.
Triggers a update for the affected sweep. win panel sweepNo [optional] sweep number sweeps [optional] sweeps to change, can be $"" index [optional] index into the listbox wave newState new checkbox state of the given sweeps invertOthers [optional, default to false] set the other sweeps to !newState if true One of sweepNo/index is required.
References ASSERT, ClearBit, GetOverlaySweepsListSelWave, GetOverlaySweepsListWave, LISTBOX_CHECKBOX_SELECTED, OVS_BeginIncrementalUpdate, OVS_EndIncrementalUpdate, OVS_GetFolder, OVS_IsActive, ROWS, SetBit.
Referenced by AD_SelectResult, BSP_ButtonProc_ChangeSweep, DB_SetVarProc_SweepNo, DB_UpdateToLastSweep, SB_PopupMenuSelectSweep.
variable OVS_IsActive(string win)
checks if OVS is active.
References BSP_IsActive, MIES_BSP_OVS.
Referenced by BSP_ButtonProc_ChangeSweep, BSP_SetOVSControlStatus, DB_SetVarProc_SweepNo, DB_UpdateToLastSweep, OVS_AddToIgnoreList, OVS_BeginIncrementalUpdate, OVS_ChangeSweepSelection, OVS_ChangeSweepSelectionState, OVS_GetHeadstageRemoval, OVS_GetSelectedSweeps, OVS_GetSweepSelectionChoices, OVS_HighlightSweep, OVS_UpdatePanel, SB_PopupMenuSelectSweep.
static variable OVS_AddToIgnoreList(string win, variable headstage, variable sweepNo=defaultValue, variable index=defaultValue)
Add headstage to the ignore list of the given sweepNo/index
References ASSERT, GetOverlaySweepsListWave, IsFinite, OVS_GetFolder, OVS_IsActive, OVS_UpdateHeadstageRemoval, ROWS.
Referenced by OVS_IgnoreHeadstageInOverlay.
static variable OVS_UpdateHeadstageRemoval(string win, variable index)
Update the OVS headstage removal wave from the listbox entry.
References GetOverlaySweepHeadstageRemoval, GetOverlaySweepsListWave, OVS_GetFolder, OVS_ParseIgnoreList, POST_PLOT_FULL_UPDATE, PostPlotTransformations, UpdateSweepInGraph.
Referenced by OVS_AddToIgnoreList, OVS_MainListBoxProc.
wave OVS_GetHeadstageRemoval(string win, variable sweepNo=defaultValue, variable index=defaultValue)
References ASSERT, BSP_GetPanel, GetCheckBoxState, GetOverlaySweepHeadstageRemoval, GetOverlaySweepsListWave, IsFinite, NUM_HEADSTAGES, OVS_GetFolder, OVS_IsActive, ROWS.
Referenced by BSP_FetchSelectedChannels, PA_GenerateAllPulseWaves.
static wave OVS_ParseIgnoreList(string ignoreList, variable sweepNo)
Parse the headstage removal list.
The expected format of the list entries is a semicolon (";") separated list of subranges (without the possibility of denoting the step size). Examples: 0 (ignore HS 0) 1,3;0 (ignore HS 0 to 3) * (ignore all headstages) ignoreList list of entries to parse sweepNo sweep number free wave of size NUM_HEADSTAGES denoting with 0/1 the active state of the headstage
References ControlWindowToFront, ExtractFromSubrange, NUM_HEADSTAGES, ROWS.
Referenced by OVS_UpdateHeadstageRemoval.
variable OVS_CheckBoxProc_HS_Select(WMCheckboxAction *cba)
References ClearBit, GetOverlaySweepsListSelWave, LISTBOX_CELL_EDITABLE, OVS_BeginIncrementalUpdate, OVS_EndIncrementalUpdate, OVS_GetFolder, SetBit.
static variable OVS_HighlightSweep(string win, variable index)
References ASSERT, DEBUGPRINT, GetMainWindow, GetRowIndex, IsFinite, IsNaN, OVS_GetSweepAndExperiment, OVS_IsActive, ParseColorSpec, ROWS, TUD_GetUserData, TUD_GetUserDataAsWave.
Referenced by OVS_MainListBoxProc.
std::tuple< variable, string > OVS_GetSweepAndExperiment(string win, variable index)
Return the sweep number and experiment name for the given list index.
References BSP_GetFolder, BSP_HasBoundDevice, BSP_IsDataBrowser, GetExperimentName, GetMainWindow, GetOverlaySweepsListWave, GetSweepBrowserMap, IsFinite, MIES_BSP_PANEL_FOLDER, ROWS, SB_GetSweepBrowserFolder.
Referenced by DB_AddSweepToGraph, OVS_HighlightSweep, PA_GetSweepsAndExperimentsFromIndices, RemoveSweepFromGraph.
static variable OVS_ChangeSweepSelection(string win, string choiceString)
Change the selected sweep according to one of the popup menu options.
References ASSERT, BSP_GetPanel, FindIndizes, GetOverlaySweepSelectionChoices, GetOverlaySweepsListSelWave, GetSetVariable, LAYERS, LISTBOX_CHECKBOX_SELECTED, NONE, NUM_HEADSTAGES, OVS_BeginIncrementalUpdate, OVS_EndIncrementalUpdate, OVS_GetFolder, OVS_IsActive, ROWS.
Referenced by OVS_PopMenuProc_Select, OVS_SetVarProc_SelectionRange.
static wave OVS_BeginIncrementalUpdate(string win, variable fullUpdate=defaultValue)
Incremental sweep plot updates for overlay sweeps.
When modifying the listbox selection and contents wave this function can be called before doing so. After the modifications OVS_EndIncrementalUpdate() will take care of updating all sweeps which got changed. The returned wave should be considered an opaque handle and not modified. Usage: embed:rst:leading-asterisk * .. code-block:: igorpro * * WAVE updateHandle = OVS_BeginIncrementalUpdate(win) * * // modify list waves * // ... * * OVS_EndIncrementalUpdate(win, updateHandle) * * By setting fullUpdate to true a conventional full, that means non-incremental, update will be performed. win graph fullUpdate [optional, defaults to true when OVS is off, false otherwise] allows to force a full update in OVS_EndIncrementalUpdate()
References BSP_GetFolder, GetOverlaySweepsListSelWave, GetOverlaySweepsListWave, MIES_BSP_PANEL_FOLDER, OVS_FULL_UPDATE_NOTE, OVS_IsActive, ROWS, SetNumberInWaveNote.
Referenced by OVS_ChangeSweepSelection, OVS_ChangeSweepSelectionState, OVS_CheckBoxProc_HS_Select, OVS_UpdatePanel.
static variable OVS_EndIncrementalUpdate(string win, WaveRefWave updateHandle)
Perform the update of all changed sweeps.
Counterpart to OVS_BeginIncrementalUpdate().
References AddSweepToGraph, ASSERT, BSP_GetFolder, DEBUGPRINT, GetNumberFromWaveNote, GetOverlaySweepsListSelWave, GetOverlaySweepsListWave, InitBufferedDrawInfo, IsEmpty, LISTBOX_CELL_EDITABLE, LISTBOX_CHECKBOX_SELECTED, MIES_BSP_PANEL_FOLDER, OVS_FULL_UPDATE_NOTE, POST_PLOT_ADDED_SWEEPS, POST_PLOT_FULL_UPDATE, POST_PLOT_REMOVED_SWEEPS, PostPlotTransformations, RemoveSweepFromGraph, ROWS, TiledGraphAccelerateDraw, UpdateSweepInGraph, UpdateSweepPlot.
Referenced by OVS_ChangeSweepSelection, OVS_ChangeSweepSelectionState, OVS_CheckBoxProc_HS_Select, OVS_UpdatePanel.
variable OVS_MainListBoxProc(WMListboxAction *lba)
References AddSweepToGraph, LISTBOX_CHECKBOX_SELECTED, OVS_HighlightSweep, OVS_UpdateHeadstageRemoval, POST_PLOT_ADDED_SWEEPS, POST_PLOT_REMOVED_SWEEPS, PostPlotTransformations, RemoveSweepFromGraph.
variable OVS_PopMenuProc_Select(WMPopupAction *pa)
References OVS_ChangeSweepSelection.
variable OVS_SetVarProc_SelectionRange(WMSetVariableAction *sva)
References GetPopupMenuString, OVS_ChangeSweepSelection.