MIES_DataAcquisition_Single.ipf
variable DQS_StartDAQSingleDevice(string device, variable useBackground=defaultValue)
Start data acquisition using single device mode.
This is the high level function usable for all external users. device device useBackground [optional, defaults to background checkbox setting in the DA_Ephys panel]
References ASSERT, AssertOnAndClearRTError, ClearRTError, DAG_GetNumericalValue, DAP_OneTimeCallAfterDAQ, DAP_OneTimeCallBeforeDAQ, DAQ_ALLOWED_FUNCTIONS, DAQ_BG_SINGLE_DEVICE, DAQ_FG_SINGLE_DEVICE, DATA_ACQUISITION_MODE, DC_Configure, DQ_STOP_REASON_CONFIG_FAILED, DQS_BkrdDataAcq, DQS_DataAcq.
Referenced by DAP_ButtonProc_TPDAQ, DQ_RestartDAQ.
variable DQS_DataAcq(string device)
References AS_HandlePossibleTransition, AS_MID_SWEEP, DAG_GetNumericalValue, DATA_ACQUISITION_MODE, DQ_StartDAQDeviceTimer, DQ_STOP_REASON_ESCAPE_KEY, DQ_STOP_REASON_FINISHED, DQS_StopDataAcq, ESCAPE_KEY, GotTPChannelsOnADCs, HARDWARE_ABORT_ON_ERROR, HARDWARE_ITC_DAC, HW_ITC_MoreData, HW_PrepareAcq, HW_StartAcq, SCOPE_GetGraph, SCOPE_UpdateGraph, SCOPE_UpdateOscilloscopeData.
Referenced by DQS_StartDAQSingleDevice, RA_Counter.
variable DQS_BkrdDataAcq(string device)
Fifo monitor for DAQ Single Device.
References AS_HandlePossibleTransition, AS_MID_SWEEP, DAG_GetNumericalValue, DATA_ACQUISITION_MODE, DQ_StartDAQDeviceTimer, DQS_StartBackgroundFifoMonitor, HARDWARE_ABORT_ON_ERROR, HARDWARE_ITC_DAC, HW_PrepareAcq, HW_StartAcq.
Referenced by DQS_StartDAQSingleDevice, RA_Counter.
static variable DQS_StopDataAcq(string device, variable stopReason, variable forcedStop=defaultValue)
Stop single device data acquisition.
References DQ_StopOngoingDAQ, HARDWARE_ABORT_ON_ERROR, HARDWARE_ITC_DAC, HW_StopAcq, RA_ContinueOrStop, SWS_SaveAcquiredData.
Referenced by DQS_DataAcq, DQS_FIFOMonitor.
variable DQS_StartBackgroundFifoMonitor()
Referenced by DQS_BkrdDataAcq.
variable DQS_FIFOMonitor(WMBackgroundStruct *s)
Fifo monitor for DAQ Single Device.
References ANALYSIS_FUNC_RET_EARLY_STOP, ANALYSIS_FUNC_RET_REPURP_TIME, AS_HandlePossibleTransition, AS_MID_SWEEP, DATA_ACQUISITION_MODE, DQ_STOP_REASON_ESCAPE_KEY, DQ_STOP_REASON_FINISHED, DQ_StopOngoingDAQ, DQS_StopDataAcq, ESCAPE_KEY, HARDWARE_ABORT_ON_ERROR, HW_ITC_MoreData, SCOPE_UpdateGraph, SCOPE_UpdateOscilloscopeData, UpdateLeftOverSweepTime.
variable DQS_StopBackgroundFifoMonitor()
Referenced by DQ_StopOngoingDAQHelper.
variable DQS_StartBackgroundTimer(string device, variable runTime, string funcList)
Start the background timer for the inter trial interval (ITI)
device device runTime left over time to wait in seconds funcList list of functions to execute at the end of the ITI
References ASSERT, isEmpty, RelativeNowHighPrec.
Referenced by RA_HandleITI.
variable DQS_StopBackgroundTimer()
Stop the background timer used for ITI tracking.
Referenced by DQ_StopOngoingDAQHelper.
variable DQS_Timer(WMBackgroundStruct *s)
Keep track of time during ITI.
References ExecuteListOfFunctions, RelativeNowHighPrec, SetValDisplay.