MIES_AnalysisFunctionHelpers.ipf
variable AFH_GetHeadstageFromADC(string device, variable AD)
Return the headstage the AD channel is assigned to.
device device AD AD channel in the range [0,8[ or [0,16[ depending on the hardware headstage or NaN (for non-associated channels)
References GetChannelClampMode.
Referenced by AFH_GetADCFromHeadstage, DAP_AdaptAssocHeadstageState, DAP_CheckHeadStage, DC_GetFilteredChannelState, DC_PlaceDataInDAQConfigWave, DC_UpdateHSProperties, SCOPE_CreateGraph, SCOPE_SetADAxisLabel, SCOPE_UpdateOscilloscopeData.
variable AFH_GetHeadstageFromDAC(string device, variable DA)
Return the headstage the DA channel is assigned to.
device device DA DA channel in the range [0,4[ or [0,8[ depending on the hardware headstage or NaN (for non-associated channels)
References GetChannelClampMode.
Referenced by AFH_GetDACFromHeadstage, DAP_AdaptAssocHeadstageState, DAP_CheckHeadStage, DAP_CheckSettings, DAP_DACHasExpectedClampMode, DC_GetFilteredChannelState, EP_WriteEpochInfoIntoSweepSettings, SC_LastSweepInSet.
variable AFH_GetADCFromHeadstage(string device, variable headstage)
Return the AD channel assigned to the headstage.
device device headstage headstage in the range [0,8[ AD channel or NaN (for non-associated channels)
References AFH_GetHeadstageFromADC, NUM_AD_CHANNELS.
Referenced by AdjustDAScale, AFH_ExtractOneDimDataFromSweep, PSQ_EvaluateBaselineProperties.
variable AFH_GetDACFromHeadstage(string device, variable headstage)
Return the DA channel assigned to the headstage.
device device headstage headstage in the range [0,8[ DA channel or NaN (for non-associated channels)
References AFH_GetHeadstageFromDAC, NUM_DA_TTL_CHANNELS.
Referenced by AdjustDAScale, AFH_ExtractOneDimDataFromSweep, AFM_CallAnalysisFunctions, AFM_UpdateAnalysisFunctionWave, DAP_AllChanDASettings, DAP_CheckSettings, DAP_OneTimeCallBeforeDAQ, DAP_ResetGUIAfterDAQ, DC_GetChannelTypefromHS, DC_UpdateHSProperties, Enforce_IC, Enforce_VC, MSQ_CreateOverrideResults, MSQ_FastRheoEst, MSQ_ForceSetEvent, MSQ_GetDAStimsetLength, PSQ_Chirp, PSQ_CreateOverrideResults, PSQ_EvaluateBaselineProperties, PSQ_ForceSetEvent, PSQ_GetDAStimsetLength, PSQ_PB_CreateTestpulseEpochs, PSQ_PB_GetPrePulseBaselineDuration, PSQ_PipetteInBath, PSQ_Ramp, PSQ_Ramp_AddEpoch, SC_GetHeadstageQCForSetCount, SC_SpikeControl, SetDAScale.
variable AFH_GetDAQDataColumn(wave DAQConfigWave, variable channelNumber, variable channelType)
Return the column index into DAQDataWave for the given channel/type combination.
DAQConfigWave DAQ configuration wave, most users need to call GetDAQConfigWave(device) to get that wave. channelNumber channel number (0-based) channelType channel type, one of XopChannelConstants
References ASSERT_TS, DEBUGPRINT_TS, IsFinite, ROWS.
Referenced by AFH_ExtractOneDimDataFromSweep, AFH_GetChannelUnit, CalculateTPLikePropsFromSweep, DC_GetChannelTypefromHS, NWB_AppendSweepLowLevel, PSQ_EvaluateBaselineProperties.
wave AFH_GetChannelUnits(wave DAQConfigWave)
Return all channel units as free text wave.
DAQConfigWave DAQ configuration wave, most users need to call GetDAQConfigWave(device) to get that wave.
References CHANNEL_UNIT_KEY, GetStringFromWaveNote, IsValidConfigWave.
Referenced by AB_SortConfigSweeps, AFH_GetChannelUnit, ExtractOneDimDataFromSweep.
string AFH_GetChannelUnit(wave DAQConfigWave, variable channelNumber, variable channelType)
Return the channel unit.
DAQConfigWave DAQ configuration wave, most users need to call GetDAQConfigWave(device) to get that wave. channelNumber channel number (0-based) channelType channel type, one of XopChannelConstants
References AFH_GetChannelUnits, AFH_GetDAQDataColumn, ROWS.
Referenced by CreateTiledChannelGraph, SCOPE_SetADAxisLabel.
variable AFH_GetLastSweepAcquired(string device)
Return the sweep number of the last acquired sweep.
Handles sweep number rollback properly. a non-negative integer sweep number or NaN if there is no data
References DATA_SWEEP_REGEXP, ExtractSweepNumber, GetDeviceDataPath, GetListOfObjects, GetSweepWave.
Referenced by AFH_GetLastSweepWaveAcquired, AS_GetSweepNumber, ASSERT, DAP_AddUserComment, DAP_SetVarProc_NextSweepLimit, DAP_UpdateSweepLimitsAndDisplay, ED_AddEntryToLabnotebook, ED_TPDocumentation, FitResistance, LastStimSetRun.
wave AFH_GetLastSweepWaveAcquired(string device)
Return the sweep wave of the last acquired sweep.
an existing sweep wave or an invalid wave reference if there is no data
References AFH_GetLastSweepAcquired, GetSweepWave.
Referenced by AdjustDAScale, ReachTargetVoltage.
string AFH_GetStimSetName(string device, variable chanNo, variable channelType)
Return the stimset for the given channel.
device device chanNo channel number (0-based) channelType one of the type constants from ChannelTypeAndControlConstants an existing stimulus set name for a DA channel
References ASSERT, CHANNEL_CONTROL_WAVE, GetPanelControl, isEmpty.
Referenced by AdjustDAScale, Enforce_IC, Enforce_VC, MSQ_CreateOverrideResults, MSQ_FastRheoEst, MSQ_GetDAStimsetLength, PSQ_Chirp, PSQ_CreateOverrideResults, PSQ_GetDAStimsetLength, PSQ_Ramp, SC_GetHeadstageQCForSetCount, SC_LastSweepInSet, SC_SpikeControl.
static wave AFH_GetSweepsFromSameRACycleNC(wave numericalValues, variable sweepNo)
Return a free wave with all sweep numbers (in ascending order) which belong to the same RA cycle. Uncached version, general users should prefer AFH_GetSweepsFromSameRACycle().
Return an invalid wave reference if not all required labnotebook entries are available
References ASSERT_TS, DATA_ACQUISITION_MODE, FindIndizes, GetLastSettingIndep, GetSweepColumn, INDEP_HEADSTAGE, RA_ACQ_CYCLE_ID_KEY, ROWS.
Referenced by AFH_GetSweepsFromSameRACycle.
wave AFH_GetSweepsFromSameRACycle(wave numericalValues, variable sweepNo)
Return a free wave with all sweep numbers (in ascending order) which belong to the same RA cycle.
Return an invalid wave reference if not all required labnotebook entries are available
References AFH_GetSweepsFromSameRACycleNC, EnsureLargeEnoughWave, GetLBNidCache, IsValidSweepNumber, ROWS.
Referenced by FitResistance, GetLastSettingEachRAC, GetLastSettingIndepEachRAC, GetLastSettingRAC, GetLastSettingTextEachRAC, GetLastSettingTextIndepEachRAC, GetLastSettingTextRAC, OVS_UpdatePanel.
wave AFH_GetSweepsFromSameSCI(wave numericalValues, variable sweepNo, variable headstage)
Return a free wave with all sweep numbers (in ascending order) which belong to the same stimset cycle.
Return an invalid wave reference if not all required labnotebook entries are available
References AFH_GetSweepsFromSameSCINC, EnsureLargeEnoughWave, GetLBNidCache, IsValidSweepNumber, ROWS.
Referenced by AD_FillWaves, AD_GetPerSweepFailMessage, GetLastSettingEachSCI, GetLastSettingIndepEachSCI, GetLastSettingSCI, GetLastSettingTextEachSCI, GetLastSettingTextIndepEachSCI, GetLastSettingTextSCI, MSQ_NumAcquiredSweepsInSet, MSQ_NumPassesInSet, OVS_UpdatePanel, PSQ_AddLabnotebookEntriesToJSON, PSQ_GetLastPassingLongRHSweep, PSQ_NumAcquiredSweepsInSet, PSQ_NumPassesInSet, PSQ_Rheobase, SC_GetHeadstageQCForSetCount.
static wave AFH_GetSweepsFromSameSCINC(wave numericalValues, variable sweepNo, variable headstage)
Return a free wave with all sweep numbers (in ascending order) which belong to the same stimset cycle id. Uncached version, general users should prefer AFH_GetSweepsFromSameSCI().
Return an invalid wave reference if not all required labnotebook entries are available
References ASSERT_TS, DATA_ACQUISITION_MODE, FindIndizes, GetLastSetting, GetSweepColumn, IsNaN, ROWS, STIMSET_ACQ_CYCLE_ID_KEY.
Referenced by AFH_GetSweepsFromSameSCI.
wave AFH_ExtractOneDimDataFromSweep(string device, wave sweep, variable headstageOrChannelNum, variable channelType, wave config=defaultValue)
Return a free 1D wave from the given sweep.
Extract the AD channel data from headstage 1: embed:rst:leading-asterisk * .. code-block:: igorpro * * variable sweepNo = 5 * WAVE sweep = GetSweepWave(device, sweepNo) * variable headstage = 1 * WAVE data = AFH_ExtractOneDimDataFromSweep(device, sweep, headstage, XOP_CHANNEL_TYPE_ADC) * Extract the TTL channel 1: embed:rst:leading-asterisk * .. code-block:: igorpro * * variable sweepNo = 6 * WAVE sweep = GetSweepWave(device, sweepNo) * variable ttlChannel = 1 * WAVE data = AFH_ExtractOneDimDataFromSweep(device, sweep, ttlChannel, XOP_CHANNEL_TYPE_TTL) * device device sweep sweep wave headstageOrChannelNum headstage [0, NUM_HEADSTAGES[ or channel number for TTL channels [0, NUM_DA_TTL_CHANNELS] channelType One of XopChannelConstants config [optional, defaults to config wave of the sweep returned by GetConfigWave()] config wave
References AFH_GetADCFromHeadstage, AFH_GetDACFromHeadstage, AFH_GetDAQDataColumn, ASSERT, ExtractOneDimDataFromSweep, GetConfigWave, IsFinite, XOP_CHANNEL_TYPE_ADC, XOP_CHANNEL_TYPE_DAC, XOP_CHANNEL_TYPE_TTL.
Referenced by MSQ_DeterminePulseDuration, MSQ_SearchForSpikes, PSQ_CR_DetermineBoundsAction, PSQ_CR_DetermineCycles, PSQ_DeterminePulseDuration, PSQ_SearchForSpikes, SC_SpontaneousSpikingCheckQC.
string AFH_GetAnalysisFunctions(variable versionBitMask)
Get list of possible analysis functions.
versionBitMask bitmask of different analysis function versions which should be returned, one of AnalysisFunctionVersions
References ANALYSIS_FUNCTION_VERSION_V1, ANALYSIS_FUNCTION_VERSION_V2, ANALYSIS_FUNCTION_VERSION_V3, FuncRefIsAssigned.
Referenced by AFM_UpdateAnalysisFunctionWave, DAP_CheckAnalysisFunctionAndParameter, WBP_GetAnalysisFunctions.
string AFH_GetListOfAnalysisParams(string func, variable mode)
Return the list of required/optional analysis function parameters, possibly including the type, as specified by the function $func_GetParams
func Analysis function V3 which must be valid and existing mode Bit mask values from GetListOfParamsModeFlags
References ASSERT, FuncRefIsAssigned, OPTIONAL_PARAMS, REQUIRED_PARAMS.
Referenced by AFH_CheckAnalysisParameter, DAP_CheckAnalysisFunctionAndParameter, WBP_UpdateParameterWave.
string AFH_GetHelpForAnalysisParameter(string func, string name)
Get help string from optional $func_GetHelp
func Analysis function V3 name Parameter name
References AssertOnAndClearRTError, ClearRTError, FuncRefIsAssigned.
Referenced by WBP_UpdateParameterWave.
string AFH_GetListOfAnalysisParamNames(string params)
Return a semicolon separated list of user parameters.
params serialized parameters, usually just AnalysisFunction_V3.params
Referenced by AFH_CheckAnalysisParameter, AFH_GetAnalysisParamNumerical, AFH_GetAnalysisParamTextual, AFH_GetAnalysisParamTextWave, AFH_GetAnalysisParamWave, DAP_CheckAnalysisFunctionAndParameter, SetControlInEvent, TestAnalysisFunction_V3, UpgradeWaveTextParam, WB_AddAnalysisParameterIntoWPT, WBP_GetAnalysisParameterNames, WBP_UpdateParameterWave.
string AFH_GetAnalysisParamType(string name, string params, variable typeCheck=defaultValue, string expectedType=defaultValue)
Return the type of the user parameter.
name parameter name params serialized parameters, usually just AnalysisFunction_V3.params typeCheck [optional, defaults to true] Check with an assertion that the readout type is one of ANALYSIS_FUNCTION_PARAMS_TYPES expectedType [optional, defaults to nothing] Expected type, one of ANALYSIS_FUNCTION_PARAMS_TYPES, aborts if the type does not match. Implies typeCheck = true. one of AnalysisFunctionParameterTypes or an empty string
References AFH_IsValidAnalysisParamType, ASSERT, IsEmpty.
Referenced by AFH_GetAnalysisParameter, DAP_CheckAnalysisFunctionAndParameter, SetControlInEvent, TestAnalysisFunction_V3, UpgradeWaveTextParam, WBP_UpdateParameterWave.
variable AFH_GetAnalysisParamNumerical(string name, string params, variable defValue=defaultValue)
Return a numerical user parameter.
name parameter name params serialized parameters, usually just AnalysisFunction_V3.params defValue [optional, defaults to NaN] return this value if the parameter could not be found
References AFH_GetAnalysisParameter, AFH_GetListOfAnalysisParamNames, AFH_IsValidAnalysisParameter, ASSERT.
Referenced by AD_GetDAScaleFailMsg, AD_PlotBounds, MSQ_FastRheoEst, MSQ_FastRheoEst_CheckParam, PSQ_CheckParamCommon, PSQ_CheckSamplingFrequencyAndStoreInLabnotebook, PSQ_Chirp, PSQ_Chirp_CheckParam, PSQ_DAScale, PSQ_DAScale_CheckParam, PSQ_EvaluateBaselineProperties, PSQ_GetBaselineRMSThresholds, PSQ_PipetteInBath, PSQ_PipetteInBath_CheckParam, PSQ_Ramp, PSQ_Ramp_CheckParam, PSQ_Rheobase, PSQ_SquarePulse, ReachTargetVoltage, ReachTargetVoltage_CheckParam, SC_CanStillSkip, SC_ReactToQCFailures, SC_SkipsExhausted, SC_SpikeControl, SC_SpikeControl_CheckParam, UpgradeWaveTextParam, WBP_ListBoxProc_AnalysisParams.
string AFH_GetAnalysisParamTextual(string name, string params, string defValue=defaultValue, variable percentDecoded=defaultValue)
Return a textual user parameter.
name parameter name params serialized parameters, usually just AnalysisFunction_V3.params defValue [optional, defaults to an empty string] return this value if the parameter could not be found percentDecoded [optional, defaults to true] if the return value should be percent decoded or not.
References AFH_GetAnalysisParameter, AFH_GetListOfAnalysisParamNames, AFH_IsValidAnalysisParameter, ASSERT.
Referenced by PSQ_Chirp, PSQ_Chirp_CheckParam, PSQ_DAScale, PSQ_DAScale_CheckParam, PSQ_PipetteInBath, PSQ_PipetteInBath_CheckParam, ReachTargetVoltage, ReachTargetVoltage_CheckParam, SC_ReactToQCFailures, SC_SpikeControl_CheckParam, TestAnalysisFunction_V3, UpgradeWaveTextParam, WBP_ListBoxProc_AnalysisParams.
wave AFH_GetAnalysisParamWave(string name, string params, wave defValue=defaultValue)
Return a numerical wave user parameter.
name parameter name params serialized parameters, usually just AnalysisFunction_V3.params defValue [optional, defaults to an invalid wave ref] return this value if the parameter could not be found wave reference to free numeric wave, or invalid wave ref in case the parameter could not be found.
References AFH_GetAnalysisParameter, AFH_GetListOfAnalysisParamNames, AFH_IsValidAnalysisParameter, ASSERT, ListToNumericWave.
Referenced by AD_GetDAScaleFailMsg, DAP_CheckAnalysisFunctionAndParameter, MSQ_DAScale, MSQ_DAScale_CheckParam, PSQ_DAScale, PSQ_DAScale_CheckParam, TestAnalysisFunction_V3, UpgradeWaveTextParam, WBP_ListBoxProc_AnalysisParams.
wave AFH_GetAnalysisParamTextWave(string name, string params, WaveText defValue=defaultValue, variable percentDecoded=defaultValue)
Return a textual wave user parameter.
name parameter name params serialized parameters, usually just AnalysisFunction_V3.params defValue [optional, defaults to an invalid wave ref] return this value if the parameter could not be found percentDecoded [optional, defaults to true] if the return value should be percent decoded or not. wave reference to free text wave, or invalid wave ref in case the parameter could not be found.
References AFH_GetAnalysisParameter, AFH_GetListOfAnalysisParamNames, AFH_IsValidAnalysisParameter, ASSERT.
Referenced by DAP_CheckAnalysisFunctionAndParameter, SetControlInEvent, TestAnalysisFunction_V3, UpgradeWaveTextParam, WBP_ListBoxProc_AnalysisParams.
variable AFH_IsValidAnalysisParameter(string name)
Check if the given name is a valid user parameter name.
References IsValidObjectName.
Referenced by AFH_GetAnalysisParamNumerical, AFH_GetAnalysisParamTextual, AFH_GetAnalysisParamTextWave, AFH_GetAnalysisParamWave, AFH_RemoveAnalysisParameter, DAP_CheckAnalysisFunctionAndParameter, WB_AddAnalysisParameterIntoWPT, WBP_ButtonProc_AddParam.
variable AFH_IsValidAnalysisParamType(string type)
Check if the given type is a valid user parameter type.
References ANALYSIS_FUNCTION_PARAMS_TYPES, IsEmpty.
Referenced by AFH_GetAnalysisParamType, WB_AddAnalysisParameterIntoWPT.
string AFH_GetAnalysisParameter(string name, string params, string expectedType=defaultValue)
Return an user parameter's value as string.
name parameter name params serialized parameters, usually just AnalysisFunction_V3.params expectedType [optional, defaults to nothing] Expected type, one of ANALYSIS_FUNCTION_PARAMS_TYPES, aborts if the type does not match.
References AFH_GetAnalysisParamType.
Referenced by AFH_GetAnalysisParamNumerical, AFH_GetAnalysisParamTextual, AFH_GetAnalysisParamTextWave, AFH_GetAnalysisParamWave, PSQ_CR_FindDependentAnalysisParameter, WBP_UpdateParameterWave.
string AFH_RemoveAnalysisParameter(string name, string params)
Delete the given user parameter name.
name parameter name params serialized parameters, usually just AnalysisFunction_V3.params serialized parameters with name removed
References AFH_IsValidAnalysisParameter, ASSERT.
Referenced by WBP_DeleteAnalysisParameter.
string AFH_CheckAnalysisParameter(string genericFunc, CheckParametersStruct *s)
Check the analysis parameters according to the optionally present check function.
genericFunc Name of an analysis V3 function s struct CheckParametersStruct with additional info multiline error messages, an empty string on success
References AFH_GetListOfAnalysisParamNames, AFH_GetListOfAnalysisParams, ASSERT, AssertOnAndClearRTError, ClearRTError, FuncRefIsAssigned, IsEmpty, IsNull, OPTIONAL_PARAMS, CheckParametersStruct::params, REQUIRED_PARAMS.
Referenced by DAP_CheckAnalysisFunctionAndParameter, WB_SaveStimSet.
variable AFH_AddAnalysisParameter(string setName, string name, variable var=defaultValue, string str=defaultValue, wave wv=defaultValue)
Add an analysis function parameter to the given stimset.
This function adds the parameter to the WPT wave and checks that it is valid. Exactly one of var/str/wv must be given. setName stimset name name name of the parameter var [optional] numeric parameter str [optional] string parameter wv [optional] wave parameter can be numeric or text
References ASSERT, WB_AddAnalysisParameterIntoWPT, WB_GetWaveTextParamForSet.
variable AFH_GetHeadstageFromActiveADC(WaveOrNull statusADC, variable activeADCount)
Return the headstage from the given active AD count.
statusADC channel status as returned by GetLastSetting() activeADCount running number of active ADC's, starting at zero headstage in the range [0, NUM_HEADSTAGES], or NaN if nothing could be found
References ASSERT, IsFinite, IsInteger, LABNOTEBOOK_LAYER_COUNT, NUM_AD_CHANNELS, NUM_HEADSTAGES, ROWS.
Referenced by LBV_AddTraceToLBGraphTPStorage.