MIES_IgorHooks.ipf
static variable IH_KillTemporaries()
Remove all strings/variables/waves which should not survive experiment reload/quit/saving.
Mainly useful for temporaries which you want to recreate on initialization
References CallFunctionForEachListItem_TS, GetDAQDevicesFolder, GetListOfObjects, GetMiesPath, GetWaveBuilderDataPath, KillOrMoveToTrashPath, RemoveEmptyDataFolder, SEGMENTWAVE_SPECTRUM_PREFIX, TRASH_FOLDER_PREFIX.
Referenced by BeforeExperimentSaveHook, IH_Cleanup.
variable IH_RemoveAmplifierConnWaves()
Remove the amplifier connection waves.
References GetAmplifierMultiClamps, GetAmplifierTelegraphServers, KillOrMoveToTrash.
Referenced by IH_Cleanup.
static variable IH_KillStimSets()
Delete all wavebuilder stim sets to save memory.
References AddPrefixToEachListItem, CallFunctionForEachListItem_TS, CHANNEL_TYPE_DAC, CHANNEL_TYPE_TTL, GetWBSvdStimSetDAPath, GetWBSvdStimSetTTLPath, KillOrMoveToTrashPath, ST_GetStimsetList.
Referenced by IH_Cleanup.
static variable IH_SerializeSettings()
Write the current JSON settings to disc.
We also invalidate the stored json ID, so that on the next access it is read again.
References PACKAGE_MIES, PS_SerializeSettings.
Referenced by BeforeExperimentSaveHook, IH_Cleanup.
static variable BeforeExperimentSaveHook(variable rN, string fileName, string path, string type, string creator, variable kind)
References DAP_SerializeAllCommentNBs, GetMiesPathAsString, H5_IsFileOpen, IH_KillTemporaries, IH_SerializeSettings, LOG_AddEntry, NWB_Flush, PACKAGE_MIES.
static variable IH_Cleanup()
Cleanup before closing or starting a new experiment.
Takes care of unlocking the hardware, removing any data which is stale on reload anyway (amplifier connection details) and removes temporary waves.
References AssertOnAndClearRTError, BUG, CA_FlushCache, ClearRTError, DAP_UnlockAllDevices, DisableDebugger, GetMiesPathAsString, GetNWBFolder, IH_KillStimSets, IH_KillTemporaries, IH_RemoveAmplifierConnWaves, IH_SerializeSettings, LOG_AddEntry, PACKAGE_MIES, ResetDebuggerState.
Referenced by IgorBeforeNewHook, IgorBeforeQuitHook, IgorQuitHook.
static variable IgorBeforeQuitHook(variable unsavedExp, variable unsavedNotebooks, variable unsavedProcedures)
References GetExperimentName, IH_Cleanup, LOG_AddEntry, PACKAGE_MIES, UNTITLED_EXPERIMENT.
static variable IgorQuitHook(string igorApplicationNameStr)
References IH_Cleanup, LOG_AddEntry, PACKAGE_MIES.
static variable IgorBeforeNewHook(string igorApplicationNameStr)
Called before a new experiment is opened, in response to the New Experiment, Revert Experiment, or Open Experiment menu items in the File menu.
References GetExperimentName, IH_Cleanup, LOG_AddEntry, PACKAGE_MIES, StartZeroMQSockets, UNTITLED_EXPERIMENT.
static variable IgorStartOrNewHook(string igorApplicationNameStr)
Called when Igor is first launched and then whenever a new experiment is being created.
References GetMiesVersion, LOG_AddEntry, LOG_MarkSessionStart, PACKAGE_MIES, PS_FixPackageLocation, ROStr, StartZeroMQSockets, UpdateZeroMQXOPLoggingTemplate.
static variable BeforeUncompiledHook(variable changeCode, string procedureWindowTitleStr, string textChangeStr)
References ASYNC_Stop, DQ_STOP_REASON_UNCOMPILED, DQ_StopOngoingDAQAllLocked, LOG_AddEntry, PACKAGE_MIES.
static variable AfterCompiledHook()
References ASYNC_Start, ClearRTError, LOG_AddEntry, PACKAGE_MIES.
variable IH_ResetScaling(WMWinHookStruct *s)
References GetAllWindows, GetMainWindow, WINTYPE_GRAPH.