MIES_TraceUserData.ipf
variable TUD_RemoveUserDataWave(WMWinHookStruct *s)
Window hook for clearing the user data of the attached graph.
References TUD_Clear.
variable TUD_Clear(string graph, variable recursive=defaultValue)
Clear the user data wave and release the indexing JSON document.
Works recursively on all child windows and calls TUD_ClearImpl on each graph.
References GetAllWindows, TUD_ClearImpl.
Referenced by DB_UpdateSweepPlot, LBV_ClearGraph, SB_UpdateSweepPlot, TUD_RemoveUserDataWave.
static variable TUD_ClearImpl(string graph)
References COLS, GetGraphUserData, GetNumberFromWaveNote, NOTE_INDEX, SetNumberInWaveNote, TUD_GraphIsManaged, TUD_INDEX_JSON.
Referenced by TUD_Clear.
string TUD_GetUserData(string graph, string trace, string key)
Return the user data the given graph and trace named key
References GetGraphUserData, TUD_ConvertTraceNameToRowIndex.
Referenced by AR_HighlightArtefactsEntry, AverageWavesFromSameYAxisIfReq, EqualizeVerticalAxesRanges, LBV_SwitchLBGraphXAxis, LBV_UpdateLBGraphLegend, LBV_UpdateTagsForTextualLBNEntries, OVS_HighlightSweep, OVS_IgnoreHeadstageInOverlay, SBE_ExportSweepBrowser, TimeAlignCursorMovedHook, TimeAlignmentIfReq, WB_OpenStimulusSetInWaveBuilder.
wave TUD_GetUserDataAsWave(string graph, string key, WaveText keys=defaultValue, WaveText values=defaultValue, variable returnIndizes=defaultValue)
Return the user data for key of all traces in graph in a 1D text wave.
graph existing graph key key value to gather data for keys [optional] Either both keys and values are present or none of them. These allow to further restrict the returned result to traces having all of the additional key/value pairs values [optional] See key returnIndizes [optional, default to false] Return the indizes of the matches instead of the values
References ASSERT, COLS, FindIndizes, GetGraphUserData, GetNumberFromWaveNote, GetSetIntersection, NOTE_INDEX, ROWS, TUD_GetTraceCount.
Referenced by AD_PlotBounds, AR_GetHighlightTraces, AR_HandleRanges, AverageWavesFromSameYAxisIfReq, EqualizeVerticalAxesRanges, GetSweepUserData, GetTraceInfos, LayoutGraph, LBV_AddTraceToLBGraphTPStorage, LBV_EntryDescription, OVS_HighlightSweep, RemoveSweepFromGraph, TimeAlignCursorMovedHook.
variable TUD_SetUserData(string graph, string trace, string key, string value)
Set the given user data for the trace of the graph.
References COLS, GetGraphUserData, SetDimensionLabels, TUD_ConvertTraceNameToRowIndex, TUD_GetTraceCount.
Referenced by AR_HandleRanges, AverageWavesFromSameYAxisIfReq.
variable TUD_SetUserDataFromWaves(string graph, string trace, WaveText keys, WaveText values)
Set the given user data for the trace of the graph.
The keys/values must span a consecutive range.
References ASSERT, COLS, GetGraphUserData, ROWS, SetDimensionLabels, TextWaveToList, TUD_ConvertTraceNameToRowIndex, TUD_GetTraceCount.
Referenced by CreateTiledChannelGraph, LBV_AddTraceToLBGraph, LBV_AddTraceToLBGraphTPStorage.
static variable TUD_GraphIsManaged(string graph)
References GetGraphUserDataAsString.
Referenced by TUD_ClearImpl.
variable TUD_GetTraceCount(string graph)
Return the number of traces in the user data.
References GetGraphUserData, GetNumberFromWaveNote, NOTE_INDEX.
Referenced by GetNextTraceIndex, GetTraceInfos, LBV_LimitXRangeToSelected, TUD_GetUserDataAsWave, TUD_SetUserData, TUD_SetUserDataFromWaves.
variable TUD_RemoveUserData(string graph, string trace)
Remove all user data from the given trace.
References GetGraphUserData, TUD_RemoveTrace.
Referenced by AR_RemoveTraces, AverageWavesFromSameYAxisIfReq, LBV_SwitchLBGraphXAxis, RemoveSweepFromGraph.
variable TUD_TraceIsOnGraph(string graph, string trace)
Check if the given trace is displayed on the graph.
References GetGraphUserData, TUD_ConvertTraceNameToRowIndex.
Referenced by LBV_MakeTraceNameUnique.
variable TUD_Init(string graph)
Initialize the graph for our user trace data handling.
This is done implicitly after the user data wave is created. Once that is cleared with TUD_Clear() and the window is gone, this function can be used to reattach the cleanup hook to the newly created graph.
References ASSERT, GetMainWindow.
Referenced by BSP_InitPanel, GetGraphUserData.
static variable TUD_AddTrace(variable jsonID, WaveText graphUserData, string trace)
References EnsureLargeEnoughWave, GetNumberFromWaveNote, NOTE_INDEX, SetNumberInWaveNote, TUD_GetIndexJSON.
Referenced by TUD_ConvertTraceNameToRowIndex.
static variable TUD_RemoveTrace(WaveText graphUserData, string trace)
References GetNumberFromWaveNote, NOTE_INDEX, ROWS, SetNumberInWaveNote, TUD_ConvertTraceNameToRowIndex, TUD_GetIndexJSON.
Referenced by TUD_RemoveUserData.
static variable TUD_ConvertTraceNameToRowIndex(WaveText graphUserData, string trace, variable create=defaultValue, variable allowMissing=defaultValue)
References ASSERT, IsNaN, IsValidObjectName, TUD_AddTrace, TUD_GetIndexJSON.
Referenced by TUD_GetUserData, TUD_RemoveTrace, TUD_SetUserData, TUD_SetUserDataFromWaves, TUD_TraceIsOnGraph.
static variable TUD_GetIndexJSON(WaveText graphUserData)
References GetNumberFromWaveNote, IsFinite, SetNumberInWaveNote, TUD_INDEX_JSON, TUD_RegenerateJSONIndex.
Referenced by TUD_AddTrace, TUD_ConvertTraceNameToRowIndex, TUD_RemoveTrace.
static variable TUD_RegenerateJSONIndex(variable jsonID, WaveText graphUserData)
References GetNumberFromWaveNote, NOTE_INDEX.
Referenced by TUD_GetIndexJSON.