MIES_Debugging.ipf
const string functionReturnMessage
Referenced by DEBUGPRINTs, DEBUGPRINTv, DEBUGPRINTw.
static variable FindFirstOutsideCaller(string *func, string *line, string *file)
Return the first function from the stack trace not located in this file.
Referenced by BUG, DEBUGPRINT, DEBUGPRINTSTACKINFO.
variable DEBUGPRINTv(variable var, string format=defaultValue)
Output debug information and return the parameter var.
Debug function especially designed for usage in return statements. For example calling the following function embed:rst:leading-asterisk * .. code-block:: igorpro * * Function doStuff() * variable var = 1 + 2 * return DEBUGPRINTv(var) * End * will output DEBUG doStuff(...)#L5: return value 3 to the history. var numerical argument for debug output format optional format string to override the default of "%g"
wave DEBUGPRINTw(WaveOrNull wv, string format=defaultValue)
Output debug information and return the wave wv.
Debug function especially designed for usage in return statements. For example calling the following function embed:rst:leading-asterisk * .. code-block:: igorpro * * Function/WAVE doStuff() * Make/D/N=5 data = p * return DEBUGPRINTw(data) * End * will output DEBUG doStuff(...)#L5: return value {0, 1, 2, 3, 4} to the history. wv wave argument for debug output format optional format string to override the default of "%g"
string DEBUGPRINTs(string str, string format=defaultValue)
Output debug information and return the parameter str.
Debug function especially designed for usage in return statements. For example calling the following function embed:rst:leading-asterisk * .. code-block:: igorpro * * Function/s doStuff() * variable str= "a" + "b" * return DEBUGPRINTs(str) * End * will output DEBUG doStuff(...)#L5: return value ab to the history. str string argument for debug output format optional format string to override the default of "%s"
variable DEBUGPRINT(string msg, variable var=defaultValue, string str=defaultValue, WaveOrNull wv=defaultValue, string format=defaultValue)
Generic debug output function.
Outputs variables and strings with optional format argument. Examples: embed:rst:leading-asterisk * .. code-block:: igorpro * * DEBUGPRINT("before a possible crash") * DEBUGPRINT("some variable", var=myVariable) * DEBUGPRINT("my string", str=myString) * DEBUGPRINT("Current state", var=state, format="%.5f") * msg descriptive string for the debug message var variable str string wv wave (can be null) format format string overrides the default of "%g" for variables and "%s" for strings
variable DEBUGPRINT_TS(string msg, variable var=defaultValue, string str=defaultValue, string format=defaultValue)
Generic debug output function (threadsafe variant)
Outputs variables and strings with optional format argument. Examples: embed:rst:leading-asterisk * .. code-block:: igorpro * * DEBUGPRINT("before a possible crash") * DEBUGPRINT("some variable", var=myVariable) * DEBUGPRINT("my string", str=myString) * DEBUGPRINT("Current state", var=state, format="%.5f") * msg descriptive string for the debug message var variable str string format format string overrides the default of "%g" for variables and "%s" for strings
variable DEBUGPRINTSTACKINFO()
Print a nicely formatted stack trace to the history.
References CreateHistoryLog, DP_DebuggingEnabledForFile, FindFirstOutsideCaller, GetExperimentName, GetStackTrace, IsEmpty, SaveHistoryLog, UNTITLED_EXPERIMENT.
static variable CreateHistoryLog()
Creates a notebook with the special name "HistoryCarbonCopy" which will hold a copy of the history
Referenced by DEBUGPRINTSTACKINFO.
static variable SaveHistoryLog()
Save the contents of the history notebook on disk in the same folder as this experiment as timestamped file "run_*_*.log"
References ASSERT, AssertOnAndClearRTError, ControlWindowToFront, GetExperimentName, UNTITLED_EXPERIMENT.
Referenced by DEBUGPRINTSTACKINFO.
variable DEBUGPRINT_OR_ABORT(string msg)
Prints a message to the command history in debug mode, aborts with dialog in release mode.
References DEBUGPRINT.
Referenced by DAP_LockDevice.
variable DEBUG_TIMER_START()
Start a timer for performance measurements.
Usage: embed:rst:leading-asterisk * .. code-block:: igorpro * * variable referenceTime = DEBUG_TIMER_START() * // part one to benchmark * DEBUGPRINT_ELAPSED(referenceTime) * // part two to benchmark * DEBUGPRINT_ELAPSED(referenceTime) *
References GetReferenceTime.
variable DEBUGPRINT_ELAPSED(variable referenceTime)
Print the elapsed time for performance measurements in seconds.
DEBUG_TIMER_START()
References DEBUGPRINT, GetElapsedTime.
variable DEBUGPRINT_ELAPSED_WAVE(variable referenceTime)
Print and store the elapsed time for performance measurements.
DEBUG_TIMER_START()
References StoreElapsedTime.
variable EnableDebugMode()
Enable debug mode.
variable DisableDebugMode()
Disable debug mode.
variable EnableEvilMode()
Enable evil mode.
variable DisableEvilMode()
Disable evil mode.
variable DisableThreadsafeSupport()
Disable threadsafe support.
variable EnableThreadsafeSupport()
Enable threadsafe support again (default on IP startup)
variable BUG(string msg)
Complain and ask the user to report the error.
In nearly all cases ASSERT() is the more appropriate method to use. If a testcase wants to trigger a BUG message and needs to treat that as non-fatal, it needs to set bugCount to NaN before.
References ASSERT, ControlWindowToFront, FindFirstOutsideCaller, GetStackTrace, isEmpty, IsNaN, LOG_AddEntry, PACKAGE_MIES.
Referenced by AD_GetBaselineFailMsg, AD_GetChirpFailMsg, AD_GetDAScaleFailMsg, AD_GetPerSweepFailMessage, AD_GetResultMessage, AD_GetSquarePulseFailMsg, AFM_CallAnalysisFunctions, AS_HandlePossibleTransition, BSP_AddTracesForEpochs, DAG_GetNumericalValue, DAG_GetTextualValue, DAP_CheckSettings, DC_InitDataHoldingWave, ED_FindIndizesAndRedimension, FFI_Publish, IH_Cleanup, LBV_AddTraceToLBGraphTPStorage, NWB_ASYNC_FinishWriting, NWB_ASYNC_Readout, SWS_SaveAcquiredData, TFH_StartFIFODeamonInternal, UploadCrashDumpsDaily.
variable BUG_TS(string msg)
Threadsafe variant of BUG()
TodoIP9: Unify with BUG
References ASSERT_TS, GetStackTrace, IsNaN, LOG_AddEntry_TS, PACKAGE_MIES, TSDS_BUGCOUNT.
variable GetSizeOfAllWavesInExperiment()
Debug helper which creates a textwave which will hold the names of all waves and their size in MiB.
References GetListOfObjects, GetUniqueTextEntriesFromList, GetWaveSize.
variable CheckAllDimensionLabels()
Check that all stored waves (permanent and free) adhere to the liberal naming rules.
These are only enforced since IP9 beta9 or later. Number of waves not matching
References CheckDimensionLabels, GetListOfObjects, GetUniqueEntries, IsEmpty, ROWS.
static string CheckDimensionLabels(WaveOrNull wv)
References CheckDimensionLabels, FindIndizes, HasOneValidEntry, IsEmpty, IsValidLiberalObjectName, IsWaveRefWave, PROP_NON_EMPTY, ROWS.
Referenced by CheckAllDimensionLabels, CheckDimensionLabels.
variable DEBUG_STOREFUNCTION()