MIES_DataAcquisition_Multi.ipf
variable DQM_FIFOMonitor(WMBackgroundStruct *s)
Fifo monitor for DAQ Multi Device.
References ANALYSIS_FUNC_RET_EARLY_STOP, ANALYSIS_FUNC_RET_REPURP_TIME, AS_HandlePossibleTransition, AS_MID_SWEEP, ASSERT, AssertOnAndClearRTError, ClearRTError, DATA_ACQUISITION_MODE, DQ_STOP_REASON_ESCAPE_KEY, DQ_STOP_REASON_HW_ERROR, DQ_StopOngoingDAQ, DQM_RemoveDevice, DQM_StopDataAcq, ESCAPE_KEY, GetDAQDataWave, GetDQMActiveDeviceList, GetNIFIFOName, GetTPSettingsCalculated, GotTPChannelsOnADCs, HARDWARE_ITC_DAC, HARDWARE_NI_DAC, HW_GetMainDeviceName, IsNaN, LOG_AddEntry, PACKAGE_MIES, ROWS, SCOPE_UpdateGraph, SCOPE_UpdateOscilloscopeData, TS_GetNewestFromThreadQueue, UpdateLeftOverSweepTime.
variable DQM_TerminateOngoingDAQHelper(string device)
Stop ongoing multi device DAQ.
Follower handling for yoked devices is done by the caller.
References DQM_RemoveDevice, GetDQMActiveDeviceList, GetHardwareType, HARDWARE_ABORT_ON_ERROR, HARDWARE_ITC_DAC, HW_StopAcq, ROWS, TFH_StopFIFODaemon.
Referenced by DQ_StopOngoingDAQHelper.
variable DQM_StartDAQMultiDevice(string device, variable initialSetupReq=defaultValue)
Handles function calls for data acquistion. These include calls for starting Yoked ITC1600s.
Handles the calls to the data configurator (DC) functions and BackgroundMD it is required because of the special handling syncronous ITC1600s require device device initialSetupReq [optional, defaults to true] performs initialization routines at the very beginning of DAQ, turn off for RA
References ASSERT, AssertOnAndClearRTError, ClearRTError, DAG_GetNumericalValue, DAP_OneTimeCallAfterDAQ, DAP_OneTimeCallBeforeDAQ, DAP_UpdateITIAcrossSets, DAQ_ALLOWED_FUNCTIONS, DAQ_BG_MULTI_DEVICE, DATA_ACQUISITION_MODE, DC_Configure, DeviceHasFollower, DQ_StartDAQDeviceTimer, DQ_STOP_REASON_CONFIG_FAILED, DQ_StopDAQDeviceTimer, DQM_BkrdDataAcq, GetHardwareType, HARDWARE_ABORT_ON_ERROR, HARDWARE_DAC_EXTERNAL_TRIGGER, HW_ITC_PrepareAcq, HW_PrepareAcq.
Referenced by DAP_ButtonProc_TPDAQ, DQ_RestartDAQ, RA_CounterMD.
variable DQM_CallFuncForDevicesYoked(string device, CALL_FUNCTION_LIST_PROTOTYPE func)
Call a function for a device and if this device is a leader with followers for all follower too.
Handles also non-yoked devices in multi device mode correctly.
References CallFunctionForEachListItem, GetListofLeaderAndPossFollower.
Referenced by TPM_StopTestPulseMultiDevice.
variable DQM_StartBackgroundTimer(string device, variable runTime, string funcList)
Start the background timer for the inter trial interval (ITI)
Multi device variant device device runTime left over time to wait in seconds funcList list of functions to execute at the end of the ITI
References ASSERT, DQM_MakeOrUpdateTimerParamWave, IsBackgroundTaskRunning, isEmpty, RelativeNowHighPrec, TASKNAME_TIMERMD.
Referenced by RA_HandleITI_MD.
variable DQM_StopBackgroundTimer(string device)
Stop the background timer used for ITI tracking.
References DQM_MakeOrUpdateTimerParamWave, GetActiveDAQDevicesTimerFolder.
Referenced by DQ_StopOngoingDAQHelper.
variable DQM_Timer(WMBackgroundStruct *s)
Background function for tracking ITI.
References DQM_MakeOrUpdateTimerParamWave, ExecuteListOfFunctions, GetActiveDAQDevicesTimerFolder, RelativeNowHighPrec, ROWS, SetValDisplay.
static variable DQM_StartBckrdFIFOMonitor()
Referenced by DQM_BkrdDataAcq.
static variable DQM_StopDataAcq(string device, variable deviceID)
References GetHardwareType, HARDWARE_ABORT_ON_ERROR, HARDWARE_ITC_DAC, HW_StopAcq, RA_ContinueOrStop, SWS_SaveAcquiredData, TFH_StopFIFODaemon.
Referenced by DQM_FIFOMonitor.
static variable DQM_BkrdDataAcq(string device, variable triggerMode=defaultValue)
References AS_HandlePossibleTransition, AS_MID_SWEEP, DAG_GetNumericalValue, DQ_StartDAQDeviceTimer, DQM_AddDevice, DQM_StartBckrdFIFOMonitor, GetHardwareType, HARDWARE_ABORT_ON_ERROR, HARDWARE_DAC_DEFAULT_TRIGGER, HARDWARE_ITC_DAC, HW_StartAcq, IsBackgroundTaskRunning, TASKNAME_FIFOMONMD, TFH_StartFIFOStopDaemon.
Referenced by DQM_StartDAQMultiDevice.
static variable DQM_RemoveDevice(string device, variable deviceID)
Removes a device from the ActiveDeviceList.
device panel title deviceID id of the device to be removed
References DeleteWavePoint, DQM_GetActiveDeviceRow, GetDQMActiveDeviceList, ROWS.
Referenced by DQM_FIFOMonitor, DQM_TerminateOngoingDAQHelper.
variable DQM_GetActiveDeviceRow(variable deviceID)
Return the row into ActiveDeviceList for the given deviceID.
References COLS, GetDQMActiveDeviceList.
Referenced by DQM_RemoveDevice, RA_AreLeaderAndFollowerFinished.
static variable DQM_AddDevice(string device)
Adds a device to the ActiveDeviceList.
device panel title
References GetDQMActiveDeviceList, GetHardwareType, ROWS.
Referenced by DQM_BkrdDataAcq.
static variable DQM_MakeOrUpdateTimerParamWave(string device, string listOfFunctions, variable startTime, variable RunTime, variable EndTime, variable addOrRemoveDevice)
References ASSERT, DQM_MakeOrUpdtDevTimerTxtWv, GetActiveDAQDevicesTimerFolder, ROWS.
Referenced by DQM_StartBackgroundTimer, DQM_StopBackgroundTimer, DQM_Timer.
static variable DQM_MakeOrUpdtDevTimerTxtWv(string device, string listOfFunctions, variable rowToRemove, variable addOrRemoveDevice)
References ASSERT, GetActiveDAQDevicesTimerFolder, ROWS.
Referenced by DQM_MakeOrUpdateTimerParamWave.