MIES_WaveDataFolderGetters.ipf
const double LBN_NUMERICAL_DESCRIPTION_VERSION
Referenced by SaveLBNumericalDescription.
const double SWEEP_SETTINGS_WAVE_VERSION
Referenced by GetSweepSettingsKeyWave, GetSweepSettingsTextKeyWave, GetSweepSettingsTextWave, GetSweepSettingsWave.
dfref GetLabNotebookFolder()
Return the datafolder reference to the lab notebook.
References createDFWithAllParents, GetLabNotebookFolderAsString.
Referenced by AB_ReExport.
string GetLabNotebookFolderAsString()
Return the full path to the lab notebook, e.g. root:MIES:LabNoteBook.
References GetMiesPathAsString.
Referenced by AB_LoadLabNotebookFromIgor, AB_ReExport, GetDevSpecLabNBFolderAsString, GetLabNotebookFolder, SaveExperimentSpecial.
dfref GetDevSpecLabNBFolder(string device)
Return the data folder reference to the device specific lab notebook.
References createDFWithAllParents, GetDevSpecLabNBFolderAsString.
Referenced by AB_ReExport, GetLBNumericalKeys, GetLBNumericalValues, GetLBTextualKeys, GetLBTextualValues, UpgradeLabNotebook.
string GetDevSpecLabNBFolderAsString(string device)
Return the full path to the device specific lab notebook, e.g. root:MIES:LabNoteBook:ITC18USB:Device0.
References ASSERT, GetHardwareType, GetLabNotebookFolderAsString, HARDWARE_ITC_DAC, HARDWARE_NI_DAC, ParseDeviceString.
Referenced by AB_ReExport, GetDevSpecLabNBFolder, GetDevSpecLabNBTempFolderAS, GetLBNumericalKeys, GetLBNumericalValues, GetLBTextualKeys, GetLBTextualValues, GetSweepSettingsKeyWave, GetSweepSettingsTextKeyWave, GetSweepSettingsTextWave, GetSweepSettingsWave.
wave DAQ_LBN_GETTER_PROTO(string win)
References ASSERT.
wave GetLBTextualValues(string device)
Returns a wave reference to the text labnotebook.
Rows: Filled at runtime Columns: Filled at runtime Layers: 0-7: data for a particular headstage using the layer index 8: headstage independent data
References COLS, WaveLocationMod::dfr, GetDevSpecLabNBFolder, GetDevSpecLabNBFolderAsString, INITIAL_KEY_WAVE_COL_COUNT, LABNOTEBOOK_LAYER_COUNT, LABNOTEBOOK_ROLLBACK_COUNT, MINIMUM_WAVE_SIZE, NOTE_INDEX, SetNumberInWaveNote, UpgradeWaveLocationAndGetIt.
Referenced by AdjustDAScale, DAP_CheckSettings, DAP_LockDevice, DAP_SweepRollback, ED_WriteChangedValuesToNoteText, IVS_GetSetQCForSweep, LastStimSetRun, NWB_AppendSweepDuringDAQ, NWB_ExportAllData, NWB_FirstStartTimeOfAllSweeps, NWB_GetStimsetFromPanel, PSQ_Chirp, PSQ_CR_GetCycles, PSQ_DAScale, PSQ_EvaluateBaselineProperties, PSQ_GetLastPassingDAScaleSub, PSQ_PipetteInBath, PSQ_Ramp, ReachTargetVoltage, RecreateMissingSweepAndConfigWaves, SC_GetTrials, SC_ReactToQCFailures, SC_SpontaneousSpikingCheckQC, UpgradeLabNotebook.
static variable UpgradeLabNotebook(string device)
Handle upgrades of the numerical/textual labnotebooks in one step.
This function is idempotent and must stay that way. Supported upgrades: Addition of the third column "TimeStampSinceIgorEpochUTC" Addition of nineth layer for headstage independent data Conversion of numeric labnotebook to 64bit floats Removal of invalid units for "Stim Scale Factor", "DA Gain" and "AD Gain" Addition of fourth column "EntrySourceType" Fix unit and tolerance of "Repeat Sets" Reapplying the dimension labels as the old ones were cut off after 31 bytes Making dimension labels valid liberal object names Extending the row dimension to 6 for the key waves
References ASSERT, COLS, DEBUGPRINT, FixInvalidLabnotebookKey, GetDevSpecLabNBFolder, GetLBNumericalKeys, GetLBNumericalValues, GetLBTextualKeys, GetLBTextualValues, GetSweepSettingsKeyWave, IGOR_TYPE_32BIT_FLOAT, IGOR_TYPE_64BIT_FLOAT, LABNOTEBOOK_LAYER_COUNT, LABNOTEBOOK_ROLLBACK_COUNT, LAYERS, LBN_SetDimensionLabels, NUM_HEADSTAGES, SetNumberInWaveNote, WaveVersionIsSmaller.
Referenced by GetLBNumericalKeys, GetLBTextualKeys.
static string FixInvalidLabnotebookKey(string name)
Referenced by UpgradeLabNotebook.
static variable SetLBKeysRowDimensionLabels(wave wv)
References ROWS.
Referenced by GetLBNumericalDescription, GetLBNumericalKeys, GetLBTextualKeys.
wave GetLBTextualKeys(string device)
Return a wave reference to the text labnotebook keys.
Rows: 0: Parameter Name 1: Parameter Unit 2: Parameter Tolerance Columns: 0: Sweep Number 1: Time Stamp in local time zone 2: Time Stamp in UTC 3: Source entry type, one of DataAcqModes 4: Acquisition state, one of AcquisitionStates other columns are filled at runtime
References ASSERT, WaveLocationMod::dfr, ExistsWithCorrectLayoutVersion, GetDevSpecLabNBFolder, GetDevSpecLabNBFolderAsString, INITIAL_KEY_WAVE_COL_COUNT, LABNOTEBOOK_KEYS_INITIAL, LABNOTEBOOK_VERSION, SetLBKeysRowDimensionLabels, SetWaveVersion, UpgradeLabNotebook, UpgradeWaveLocationAndGetIt.
Referenced by DAP_LockDevice, DAP_SweepRollback, ED_WriteChangedValuesToNoteText, NWB_AppendSweepDuringDAQ, NWB_ExportAllData, RecreateMissingSweepAndConfigWaves, UpgradeLabNotebook.
wave GetLBNumericalKeys(string device)
Return a wave reference to the numeric labnotebook keys.
Rows: 0: Name 1: Units 2: Tolerance 3: Description 4: Headstage Contingency 5: ClampMode Columns: 0: Sweep Number 1: Time Stamp in local time zone 2: Time Stamp in UTC 3: Source entry type, one of DataAcqModes 4: Acquisition state, one of AcquisitionStates other columns are filled at runtime
References ASSERT, COLS, WaveLocationMod::dfr, ExistsWithCorrectLayoutVersion, GetDevSpecLabNBFolder, GetDevSpecLabNBFolderAsString, GetLBNumericalDescription, INITIAL_KEY_WAVE_COL_COUNT, LABNOTEBOOK_VERSION, ROWS, SetLBKeysRowDimensionLabels, SetWaveVersion, UpgradeLabNotebook, UpgradeWaveLocationAndGetIt.
Referenced by DAP_LockDevice, DAP_SweepRollback, ED_WriteChangedValuesToNote, NWB_AppendSweepDuringDAQ, NWB_ExportAllData, PSQ_PB_Publish, RecreateMissingSweepAndConfigWaves, UpgradeLabNotebook.
wave GetLBNumericalDescription(variable forceReload=defaultValue)
Return a wave reference to the static and read-only labnotebook descriptions for the numerical entries.
Requirements for each entry [CheckLBNDescriptions()]: 0: Parameter Not empty 1: Units Something ParseUnit() can grok or degC, bitMask, % or On/Off 2: Tolerance LABNOTEBOOK_NO_TOLERANCE or a positive number including zero 3: Description Not empty 4: Headstage Contingency One of ALL, DEPEND, INDEP 5: Clamp Mode One of IC, VC, IC;I=0, IC;VC, IC;VC;I=0 or empty
References ASSERT, COLS, GetStaticDataFolder, IsFreeWave, KillOrMoveToTrash, LoadWaveFromDisk, SetDimensionLabels, SetLBKeysRowDimensionLabels, TextWaveToList.
Referenced by ED_FindIndizesAndRedimension, GetLBNumericalKeys.
variable SaveLBNumericalDescription()
References ASSERT, GetStaticDataFolder, LBN_NUMERICAL_DESCRIPTION_VERSION, RemoveAllDimLabels, SetWaveVersion, StoreWaveOnDisk.
wave GetLBNumericalValues(string device)
Return a wave reference to the numeric labnotebook keys.
Rows: Filled at runtime Columns: Filled at runtime Layers: 0-7: data for a particular headstage using the layer index 8: headstage independent data
References COLS, WaveLocationMod::dfr, GetDevSpecLabNBFolder, GetDevSpecLabNBFolderAsString, INITIAL_KEY_WAVE_COL_COUNT, LABNOTEBOOK_LAYER_COUNT, LABNOTEBOOK_ROLLBACK_COUNT, MINIMUM_WAVE_SIZE, NOTE_INDEX, SetNumberInWaveNote, UpgradeWaveLocationAndGetIt.
Referenced by AdjustDAScale, DAP_CheckSettings, DAP_LockDevice, DAP_SweepRollback, ED_WriteChangedValuesToNote, FitResistance, IVS_GetSetQCForSweep, LastStimSetRun, MSQ_DAScale, MSQ_DS_GetDAScaleOffset, MSQ_FastRheoEst, MSQ_GetLastPassingLongRHSweep, MSQ_GetPulseDurations, MSQ_NumAcquiredSweepsInSet, NWB_AppendSweepDuringDAQ, NWB_CheckForMissingSweeps, NWB_ExportAllData, NWB_GetStimsetFromPanel, PSQ_Chirp, PSQ_CR_DetermineBoundsAction, PSQ_DAScale, PSQ_DS_GetDAScaleOffset, PSQ_EvaluateBaselineProperties, PSQ_FoundAtLeastOneSpike, PSQ_GetLastPassingDAScaleSub, PSQ_GetLastPassingLongRHSweep, PSQ_GetPulseDurations, PSQ_NumAcquiredSweepsInSet, PSQ_PB_Publish, PSQ_PipetteInBath, PSQ_Ramp, PSQ_Rheobase, PSQ_SquarePulse, RA_DocumentSweepSkipping, ReachTargetVoltage, RecreateMissingSweepAndConfigWaves, SC_GetHeadstageQCForSetCount, SC_GetSweepPassed, SC_GetTrials, SC_LastSweepInSet, SC_ReactToQCFailures, SC_SpikeControl, SC_SpontaneousSpikingCheckQC, SWS_DeleteDataWaves, UpgradeLabNotebook.
wave GetNumericalResultsKeys()
Return a wave reference to the numerical results keys.
Rows: 0: Parameter Name 1: Parameter Unit 2: Parameter Tolerance Columns: 0: Sweep Number (always NaN) 1: Time Stamp in local time zone 2: Time Stamp in UTC 3: Source entry type, one of DataAcqModes 4: Acquisition state, one of AcquisitionStates other columns are filled at runtime
References ASSERT, ExistsWithCorrectLayoutVersion, GetResultsFolder, INITIAL_KEY_WAVE_COL_COUNT, LABNOTEBOOK_KEYS_INITIAL, RESULTS_VERSION, ROWS, SetWaveVersion.
Referenced by GetLogbookWaves, NWB_AppendSweepDuringDAQ, NWB_ExportAllData.
wave GetNumericalResultsValues()
Return a wave reference to the numerical results values.
Rows: Filled at runtime Columns: Filled at runtime Layers: 0-7: data for a particular headstage using the layer index 8: headstage independent data
References COLS, GetResultsFolder, INITIAL_KEY_WAVE_COL_COUNT, LABNOTEBOOK_LAYER_COUNT, MINIMUM_WAVE_SIZE, NOTE_INDEX, SetNumberInWaveNote.
Referenced by GetLogbookWaves, NWB_AppendSweepDuringDAQ, NWB_ExportAllData.
wave GetTextualResultsKeys()
Return a wave reference to the textual results keys.
Rows: 0: Parameter Name 1: Parameter Unit 2: Parameter Tolerance Columns: 0: Sweep Number (always NaN) 1: Time Stamp in local time zone 2: Time Stamp in UTC 3: Source entry type, one of DataAcqModes 4: Acquisition state, one of AcquisitionStates other columns are filled at runtime
References ASSERT, ExistsWithCorrectLayoutVersion, GetResultsFolder, INITIAL_KEY_WAVE_COL_COUNT, LABNOTEBOOK_KEYS_INITIAL, RESULTS_VERSION, ROWS, SetWaveVersion.
Referenced by GetLogbookWaves, NWB_AppendSweepDuringDAQ, NWB_ExportAllData.
wave GetTextualResultsValues()
Return a wave reference to the numerical results values.
Rows: Filled at runtime Columns: Filled at runtime Layers: 0-7: data for a particular headstage using the layer index 8: headstage independent data
References COLS, GetResultsFolder, INITIAL_KEY_WAVE_COL_COUNT, LABNOTEBOOK_LAYER_COUNT, MINIMUM_WAVE_SIZE, NOTE_INDEX, SetNumberInWaveNote.
Referenced by GetLogbookWaves, NWB_AppendSweepDuringDAQ, NWB_ExportAllData.
wave GetLBRowCache(wave values)
Return the labnotebook cache wave holding the first and last rows into values of each sweep number.
Uses the values wave modification count to reset itself upon a change. The stored information is the returned first/last parameter from GetLastSettingNoCache(). Rows: Sweep numbers (only existing sweeps) Columns: 0: First row 1: Last row Layers: One for each entrySourceType, mapped via EntrySourceTypeMapper()
References ASSERT_TS, CA_OPTS_NO_DUPLICATE, CA_StoreEntryIntoCache, CA_TryFetchingEntryFromCache, COLS, EnsureLargeEnoughWave, ExistsWithCorrectLayoutVersion, GetLastSweepWithSetting, GetLastSweepWithSettingText, GetLockState, GetNumberFromWaveNote, isEmpty, IsFinite, IsNumericWave, IsTextWave, LABNOTEBOOK_GET_RANGE, LABNOTEBOOK_MOD_COUNT, LABNOTEBOOK_ROLLBACK_COUNT, MINIMUM_WAVE_SIZE, NUMBER_OF_LBN_DAQ_MODES, ROWS, SetNumberInWaveNote, SetWaveVersion, WaveModCountWrapper.
Referenced by GetLastSetting.
wave GetLBIndexCache(wave values)
Index wave which serves as a labnotebook cache.
Rows: Sweep numbers Columns: One for each LBN key Layers: One for each entrySourceType, mapped via EntrySourceTypeMapper() The wave can be indexed with sweepNumber, settings column and entrySourceType to return the row index of the labnotebok wave where the desired value can be found. Contents: row index if the entry could be found, LABNOTEBOOK_MISSING_VALUE if it could not be found, and LABNOTEBOOK_UNCACHED_VALUE if the cache is empty.
References ASSERT_TS, CA_OPTS_NO_DUPLICATE, CA_StoreEntryIntoCache, CA_TryFetchingEntryFromCache, EnsureLargeEnoughWave, ExistsWithCorrectLayoutVersion, GetLastSweepWithSetting, GetLastSweepWithSettingText, GetLockState, GetNumberFromWaveNote, isEmpty, IsFinite, IsNumericWave, IsTextWave, LABNOTEBOOK_MOD_COUNT, LABNOTEBOOK_ROLLBACK_COUNT, LABNOTEBOOK_UNCACHED_VALUE, MINIMUM_WAVE_SIZE, NUMBER_OF_LBN_DAQ_MODES, ROWS, SetNumberInWaveNote, SetWaveVersion, WaveModCountWrapper.
Referenced by GetLastSetting.
wave GetLBNidCache(wave numericalValues)
Free wave to cache the sweeps of one RAC/SCI ID.
Type of content: valid wave invalid wave reference (uncached entry) wave of size zero (non-existant entry) Rows: One for each sweep number Columns: RAC (repeated acquisition cycle IDs) sweeps SCI (simset cycle IDs) sweeps
References ASSERT_TS, CA_OPTS_NO_DUPLICATE, CA_StoreEntryIntoCache, CA_TryFetchingEntryFromCache, COLS, ExistsWithCorrectLayoutVersion, GetLockState, GetNumberFromWaveNote, isEmpty, IsTextWave, LABNOTEBOOK_MOD_COUNT, LABNOTEBOOK_ROLLBACK_COUNT, MINIMUM_WAVE_SIZE, NUM_HEADSTAGES, SetNumberInWaveNote, SetWaveVersion, WaveModCountWrapper.
Referenced by AFH_GetSweepsFromSameRACycle, AFH_GetSweepsFromSameSCI.
static variable SetSweepSettingsDimLabels(wave dest, WaveText sourceKey)
Uses the parameter names from the sourceKey columns and write them as dimension into the columns of dest.
References ASSERT, COLS, ROWS.
Referenced by GetSweepSettingsKeyWave, GetSweepSettingsTextKeyWave, GetSweepSettingsTextWave, GetSweepSettingsWave, GetTPSettingsLabnotebook.
wave GetSweepSettingsWave(string device)
Returns a wave reference to the sweepSettingsWave.
sweepSettingsWave is used to save stimulus settings for each data sweep and create waveNotes for tagging data sweeps Additional columns, necessary for unassociated channels, are created on runtime. Rows: One row Columns: Same as GetSweepSettingsKeyWave Layers: 0-7: data for a particular headstage using the layer index 8: headstage independent data
References COLS, WaveLocationMod::dfr, ExistsWithCorrectLayoutVersion, GetDevSpecLabNBFolderAsString, GetDevSpecLabNBTempFolder, GetSweepSettingsKeyWave, LABNOTEBOOK_LAYER_COUNT, SetSweepSettingsDimLabels, SetWaveVersion, SWEEP_SETTINGS_WAVE_VERSION, UpgradeWaveLocationAndGetIt.
Referenced by DC_Configure, DC_DocumentChannelProperty, DC_ITC_MakeTTLWave, DC_PlaceDataInDAQConfigWave, ED_createWaveNoteTags.
wave GetSweepSettingsKeyWave(string device)
Returns a wave reference to the sweepSettingsKeyWave.
sweepSettingsKeyWave is used to index save stimulus settings for each data sweep and create waveNotes for tagging data sweeps Rows: 0: Parameter 1: Units 2: Tolerance Factor Columns: 0: Stim Scale Factor 1: DAC 2: ADC 3: DA Gain 4: AD Gain 5: Set sweep count 6: Insert TP on/off 7: Inter-trial interval (used after the sweep it is documented for) 8: TTL rack zero bits (ITC hardware), bit sum in INDEP_HEADSTAGE layer of the active DAEphys TTL channels (called TTLBit) 9: TTL rack one bits, same for the second rack 10: TTL rack zero channel (ITC hardware), device type dependent hardware channel used for acquisition in INDEP_HEADSTAGE layer 11: TTL rack one channel (ITC hardware), same for the second rack 12: Delay onset user 13: Delay onset auto 14: Delay termination 15: Delay distributed DAQ 16: Distributed DAQ 17: Repeat Sets 18: Scaling zero 19: Indexing 20: Locked indexing 21: Repeated Acquisition 22: Random Repeated Acquisition 23: Sampling interval 24: Sampling interval multiplier 25: Stim set length 26: oodDAQ Pre Feature 27: oodDAQ Post Feature 28: oodDAQ Resolution 29: Optimized Overlap dDAQ 30: Delay onset oodDAQ 31: Repeated Acquisition Cycle ID 32: Stim Wave Checksum (can be used to disambiguate cases where two stimsets are named the same but have different contents) 33: Multi Device mode 34: Background Testpulse 35: Background DAQ 36: Sampling interval multiplier 37: TP during ITI 38: Amplifier change via I=0 39: Skip analysis functions 40: Repeat sweep on async alarm 41: Set Cycle Count 42: Stimset cycle ID 43: Digitizer Hardware Type, one of HardwareDACTypeConstants 44: Fixed frequency acquisition 45: Headstage Active, binary flag that indicates the enabled headstage(s), the index is the headstage number 46: Clamp Mode 47: Igor Pro bitness 48: DA ChannelType, one of DaqChannelTypeConstants 49: AD ChannelType, one of DaqChannelTypeConstants 50: oodDAQ member, true if headstage takes part in oodDAQ mode, false otherwise 51: Autobias % (DAEphys->Settings->Amplifier) 52: Autobias Interval (DAEphys->Settings->Amplifier) 53: TP after DAQ 54: Epochs version
References CLAMPMODE_ENTRY_KEY, WaveLocationMod::dfr, ExistsWithCorrectLayoutVersion, GetDevSpecLabNBFolderAsString, GetDevSpecLabNBTempFolder, LABNOTEBOOK_BINARY_UNIT, LABNOTEBOOK_NO_TOLERANCE, RA_ACQ_CYCLE_ID_KEY, SetSweepSettingsDimLabels, SetWaveVersion, STIMSET_ACQ_CYCLE_ID_KEY, STIMSET_SCALE_FACTOR_KEY, SWEEP_SETTINGS_WAVE_VERSION, UpgradeWaveLocationAndGetIt.
Referenced by DC_Configure, DC_DocumentChannelProperty, ED_createWaveNoteTags, GetSweepSettingsWave, UpgradeLabNotebook.
wave GetSweepSettingsTextWave(string device)
Returns a wave reference to SweepSettingsTxtData.
SweepSettingsTxtData is passed to ED_AddEntriesToLabnotebook to add entries to the labnotebook. Rows: Only one Columns: Same as GetSweepSettingsTextKeyWave Layers: 0-7: data for a particular headstage using the layer index 8: headstage independent data
References COLS, WaveLocationMod::dfr, ExistsWithCorrectLayoutVersion, GetDevSpecLabNBFolderAsString, GetDevSpecLabNBTempFolder, GetSweepSettingsTextKeyWave, LABNOTEBOOK_LAYER_COUNT, SetSweepSettingsDimLabels, SetWaveVersion, SWEEP_SETTINGS_WAVE_VERSION, UpgradeWaveLocationAndGetIt.
Referenced by DC_Configure, DC_DocumentChannelProperty, DC_ITC_MakeTTLWave, DC_NI_MakeTTLWave, ED_createWaveNoteTags, ED_MarkSweepStart.
wave GetSweepSettingsTextKeyWave(string device)
Returns a wave reference to the SweepSettingsKeyTxtData.
SweepSettingsKeyTxtData is used to index SweepSettingsTxtData. Rows: Only one Columns: 0: Stim set 1: DA unit 2: AD unit 3: TTL rack zero stim sets (ITC hardware), string list in INDEP_HEADSTAGE layer with empty entries indexed by [0, NUM_DA_TTL_CHANNELS[ 4: TTL rack one stim sets (ITC hardware), same for the second rack 5: Analysis function pre daq 6: Analysis function mid sweep 7: Analysis function post sweep 8: Analysis function post set 9: Analysis function post daq 10: Analysis function pre sweep 11: Analysis function generic 12: Analysis function pre set 13: Analysis function parameters 14: oodDAQ regions list Format: $begin1-$end1;$begin2-$end2;.... Unit: stimset build ms. 15: Electrode 16: High precision sweep start timestamp in ISO8601 format 17: Stimset wave note 18: TTL rack zero set sweep counts (ITC hardware) 19: TTL rack one set sweep counts (ITC hardware) 20: TTL set sweep counts (NI hardware), string list in INDEP_HEADSTAGE layer with empty entries indexed by [0, NUM_DA_TTL_CHANNELS[ 21: TTL stim sets (NI hardware), string list in INDEP_HEADSTAGE layer with empty entries indexed by [0, NUM_DA_TTL_CHANNELS[ 22: TTL channels (NI hardware), string list in INDEP_HEADSTAGE layer with empty entries indexed by [0, NUM_DA_TTL_CHANNELS[ 23: Follower Device, list of follower devices 24: MIES version, multi line mies version string 25: Igor Pro version 26: Digitizer Hardware Name 27: Digitizer Serial Numbers 28: Epochs 29: JSON config file [path] (| separated list of full file paths) 30: JSON config file [SHA-256 hash] (| separated list of hashes) 31: JSON config file [stimset nwb file path] 32: Igor Pro build 33: Indexing End Stimset 34: TTL Indexing End Stimset (hardware agnostic), string list in INDEP_HEADSTAGE layer with empty entries indexed by [0, NUM_DA_TTL_CHANNELS[ 35: TTL Stimset wave note (hardware agnostic), same string list formatting 36: TTL Stim Wave Checksum (hardware agnostic) URL-encoded payload, see URL-encoding for background information, same string list formatting 37: TTL Stim set length (hardware agnostic), same string list formatting 38: TTL rack zero set cycle counts (ITC hardware) 39: TTL rack one set cycle counts (ITC hardware) 40: TTL set cycle counts (NI hardware), string list in INDEP_HEADSTAGE layer with empty entries indexed by [0, NUM_DA_TTL_CHANNELS[
References ANALYSIS_FUNCTION_PARAMS_LBN, WaveLocationMod::dfr, EPOCHS_ENTRY_KEY, EVENT_NAME_LIST_LBN, ExistsWithCorrectLayoutVersion, GENERIC_EVENT, GetDevSpecLabNBFolderAsString, GetDevSpecLabNBTempFolder, HIGH_PREC_SWEEP_START_KEY, LABNOTEBOOK_TTL_SETSWEEPCOUNTS, LABNOTEBOOK_TTL_STIMSETS, MID_SWEEP_EVENT, POST_DAQ_EVENT, POST_SET_EVENT, POST_SWEEP_EVENT, PRE_DAQ_EVENT, PRE_SET_EVENT, PRE_SWEEP_CONFIG_EVENT, ROWS, SetSweepSettingsDimLabels, SetWaveVersion, STIM_WAVE_NAME_KEY, STIMSET_WAVE_NOTE_KEY, SWEEP_SETTINGS_WAVE_VERSION, UpgradeWaveLocationAndGetIt.
Referenced by DC_Configure, DC_DocumentChannelProperty, ED_createWaveNoteTags, GetSweepSettingsTextWave.
const double WP_WAVE_LAYOUT_VERSION
Referenced by GetWaveBuilderWaveParamAsFree, GetWPVersion, UpgradeWaveParam.
const double WPT_WAVE_LAYOUT_VERSION
Referenced by GetWaveBuilderWaveTextParamAsFree, GetWPTVersion, UpgradeWaveTextParam.
const double SEGWVTYPE_WAVE_LAYOUT_VERSION
Referenced by GetSegmentTypeWaveAsFree, GetSegWvTypeVersion, UpgradeSegWvType.
dfref GetWaveBuilderPath()
Returns a data folder reference to the base.
References createDFWithAllParents, GetWaveBuilderPathAsString.
string GetWaveBuilderPathAsString()
Returns the full path to the base path, e.g. root:MIES:WaveBuilder.
References GetMiesPathAsString.
Referenced by GetWaveBuilderDataPathAsString, GetWaveBuilderPath, GetWBSvdStimSetParamPathAS, GetWBSvdStimSetPathAsString.
dfref GetWaveBuilderDataPath()
Returns a data folder reference to the data.
References createDFWithAllParents, GetWaveBuilderDataPathAsString.
Referenced by GetEpochID, GetEpochParameterNames, GetSegmentTypeWave, GetSegmentWave, GetWaveBuilderDispWave, GetWaveBuilderWaveParam, GetWaveBuilderWaveTextParam, GetWBEpochCombineList, IH_KillTemporaries, WBP_DisplaySetInPanel, WBP_GetAnalysisParamGUIHelpWave, WBP_GetAnalysisParamGUIListWave, WBP_GetAnalysisParamGUISelWave, WBP_LoadSet, WBP_MainWindowHook, WBP_ShowFFTSpectrumIfReq.
string GetWaveBuilderDataPathAsString()
Returns the full path to the data folder, e.g root:MIES:WaveBuilder:Data.
References GetWaveBuilderPathAsString.
Referenced by GetWaveBuilderDataPath.
dfref GetWBSvdStimSetParamPath()
Returns a data folder reference to the stimulus set parameter.
References createDFWithAllParents, GetWBSvdStimSetParamPathAS.
Referenced by WBP_CreateWaveBuilderPanel.
string GetWBSvdStimSetParamPathAS()
Returns the full path to the stimulus set parameter folder, e.g. root:MIES:WaveBuilder:SavedStimulusSetParameters.
References GetWaveBuilderPathAsString.
Referenced by GetSetParamFolderAsString, GetWBSvdStimSetParamDAPathAS, GetWBSvdStimSetParamPath, GetWBSvdStimSetParamTTLAsString.
dfref GetWBSvdStimSetPath()
Returns a data folder reference to the stimulus set.
References createDFWithAllParents, GetWBSvdStimSetPathAsString.
Referenced by WBP_CreateWaveBuilderPanel.
string GetWBSvdStimSetPathAsString()
Returns the full path to the stimulus set, e.g. root:MIES:WaveBuilder:SavedStimulusSets.
References GetWaveBuilderPathAsString.
Referenced by GetWBSvdStimSetDAPathAsString, GetWBSvdStimSetPath, GetWBSvdStimSetTTLPathAsString.
dfref GetWBSvdStimSetParamDAPath()
Returns a data folder reference to the stimulus set parameters of DA type.
References createDFWithAllParents, GetWBSvdStimSetParamDAPathAS.
Referenced by GetSetParamFolder, WBP_CreateWaveBuilderPanel.
string GetWBSvdStimSetParamDAPathAS()
Returns the full path to the stimulus set parameters of DA type, e.g. root:MIES:WaveBuilder:SavedStimulusSetParameters:DA.
References GetWBSvdStimSetParamPathAS.
Referenced by GetWBSvdStimSetParamDAPath.
dfref GetWBSvdStimSetParamTTLPath()
Returns a data folder reference to the stimulus set parameters of TTL type.
References createDFWithAllParents, GetWBSvdStimSetParamTTLAsString.
Referenced by GetSetParamFolder, WBP_CreateWaveBuilderPanel.
string GetWBSvdStimSetParamTTLAsString()
Returns the full path to the stimulus set parameters of TTL type, e.g. root:MIES:WaveBuilder:SavedStimulusSetParameters:TTL.
References GetWBSvdStimSetParamPathAS.
Referenced by GetWBSvdStimSetParamTTLPath.
dfref GetWBSvdStimSetDAPath()
Returns a data folder reference to the stimulus set of DA type.
References createDFWithAllParents, GetWBSvdStimSetDAPathAsString.
Referenced by GetSetFolder, GetTestPulse, IH_KillStimSets, WBP_CreateWaveBuilderPanel.
string GetWBSvdStimSetDAPathAsString()
Returns the full path to the stimulus set of DA type, e.g. root:MIES:WaveBuilder:SavedStimulusSet:DA.
References GetWBSvdStimSetPathAsString.
Referenced by GetSetFolderAsString, GetWBSvdStimSetDAPath.
dfref GetWBSvdStimSetTTLPath()
Returns a data folder reference to the stimulus set of TTL type.
References createDFWithAllParents, GetWBSvdStimSetTTLPathAsString.
Referenced by GetSetFolder, IH_KillStimSets, WBP_CreateWaveBuilderPanel.
string GetWBSvdStimSetTTLPathAsString()
Returns the full path to the stimulus set of TTL type, e.g. root:MIES:WaveBuilder:SavedStimulusSet:TTL.
References GetWBSvdStimSetPathAsString.
Referenced by GetSetFolderAsString, GetWBSvdStimSetTTLPath.
wave GetTestPulse()
Return the testpulse wave.
This wave will be written in TP_CreateTestPulseWave() and will use the real sampling interval.
References GetWBSvdStimSetDAPath.
Referenced by DC_GetConfiguration, DC_LongestOutputWave, TP_CreateTestPulseWave.
static variable GetWPVersion()
Automated testing helper.
References WP_WAVE_LAYOUT_VERSION.
variable UpgradeWaveParam(wave wv)
Upgrade the wave layout of WP to the most recent one as defined in WP_WAVE_LAYOUT_VERSION
References AddDimLabelsToWP, EPOCH_TYPE_CUSTOM, EPOCH_TYPE_NOISE, EPOCH_TYPES_TOTAL_NUMBER, ExistsWithCorrectLayoutVersion, SetWaveVersion, WaveVersionIsSmaller, WP_WAVE_LAYOUT_VERSION.
Referenced by GetWaveBuilderWaveParam, WB_GetWaveParamForSet.
static variable AddDimLabelsToWP(wave wv)
References COLS, LAYERS, RemoveAllDimLabels, ROWS, WB_TOTAL_NUMBER_OF_EPOCHS.
Referenced by GetWaveBuilderWaveParamAsFree, UpgradeWaveParam.
wave GetWaveBuilderWaveParam()
Return the parameter wave for the wave builder panel.
Rows: Variables synced to GUI controls, see e.g. WB_MakeWaveBuilderWave in MIES_WaveBuilder for an up to date list Columns: Segment/Epoch Layers hold different stimulus wave form types: Square pulse Ramp Noise Sin Saw tooth Pulse train PSC Load custom wave Combine
References GetWaveBuilderDataPath, GetWaveBuilderWaveParamAsFree, UpgradeWaveParam.
Referenced by WB_GetStimSet, WB_StimsetChildren, WBP_AdjustDeltaControls, WBP_ButtonProc_SaveSet, WBP_ChangeWaveType, WBP_ConvertDeltaLblToCtrlNames, WBP_CreateWaveBuilderPanel, WBP_ListControlsPerStimulusType, WBP_LoadSet, WBP_MainWindowHook, WBP_ParameterWaveToPanel, WBP_StartupSettings, WBP_UpdateControlAndWave.
wave GetWaveBuilderWaveParamAsFree()
Return a free wave version of GetWaveBuilderWaveParam()
GetWaveBuilderWaveParam()
References AddDimLabelsToWP, EPOCH_TYPE_NOISE, EPOCH_TYPES_TOTAL_NUMBER, SetWaveVersion, WP_WAVE_LAYOUT_VERSION.
Referenced by GetWaveBuilderWaveParam, ST_CreateStimSet.
static variable GetWPTVersion()
Automated testing helper.
References WPT_WAVE_LAYOUT_VERSION.
variable UpgradeWaveTextParam(WaveText wv)
Upgrade the wave layout of WPT to the most recent one as defined in WPT_WAVE_LAYOUT_VERSION
References AddDimLabelsToWPT, AFH_GetAnalysisParamNumerical, AFH_GetAnalysisParamTextual, AFH_GetAnalysisParamTextWave, AFH_GetAnalysisParamType, AFH_GetAnalysisParamWave, AFH_GetListOfAnalysisParamNames, ASSERT, EPOCH_TYPE_COMBINE, EPOCH_TYPE_CUSTOM, EPOCH_TYPES_TOTAL_NUMBER, ExistsWithCorrectLayoutVersion, INDEP_EPOCH_TYPE, SetWaveVersion, WaveVersionIsSmaller, WB_AddAnalysisParameterIntoWPT, WPT_WAVE_LAYOUT_VERSION.
Referenced by GetWaveBuilderWaveTextParam, WB_GetWaveTextParamForSet.
static variable AddDimLabelsToWPT(wave wv)
Add dimension labels to the WaveBuilder WPT wave.
References COLS, LAYERS, RemoveAllDimLabels, ROWS, WB_TOTAL_NUMBER_OF_EPOCHS.
Referenced by GetWaveBuilderWaveTextParamAsFree, UpgradeWaveTextParam.
wave GetWaveBuilderWaveTextParam()
Return the parameter text wave for the wave builder panel.
Rows: 0: Name of the custom wave for EPOCH_TYPE_CUSTOM (legacy format: wave name only, current format: absolute path including the wave name) 1: Analysis function, pre daq (deprecated) 2: Analysis function, mid sweep (deprecated) 3: Analysis function, post sweep (deprecated) 4: Analysis function, post set (deprecated) 5: Analysis function, post daq (deprecated) 6: Formula 7: Formula version: "[[:digit:]]+" 8: Analysis function, pre sweep (deprecated) 9: Analysis function, generic 10: Unused 11-26: Explicit delta values. ; separated list as long as the number of sweeps. 27: Analysis function, pre set (deprecated) 28: Explicit delta value for "Inter trial interval" 29: Analysis function parameters. See below for a detailed explanation. 30-50: unused Formula and Formula Version are in the EPOCH_TYPE_COMBINE layer, the custom wave name is in the EPOCH_TYPE_CUSTOM layer. 11 to 26 are for all epoch types. The rest is layer independent (aka a setting for the full set) in INDEP_EPOCH_TYPE. Columns: Segment/Epoch, the very last index is reserved for textual settings for the complete set Layers hold different stimulus wave form types: Square pulse/Set specific settings Ramp Noise Sin Saw tooth Pulse train PSC Load custom wave Combine Analysis function parameters Format of a single parameter: name:(variable|string|wave|textwave)=value For these building blocks the following restrictions hold name: Must be a valid non-liberal igor object name value: URL-encoded payload, see URL-encoding for background information. Decoding is done by AFH_GetAnalysisParamTextual() and AFH_GetAnalysisParamNumerical(). Multiple entries are separated by comma (,).
References GetWaveBuilderDataPath, GetWaveBuilderWaveTextParamAsFree, UpgradeWaveTextParam.
Referenced by WB_CustomWavesPathFromStimSet, WB_GetStimSet, WB_StimsetChildren, WB_UpgradeCustomWaves, WBP_AnaFuncsToWPT, WBP_ButtonProc_AddParam, WBP_ButtonProc_SaveSet, WBP_ConvertDeltaLblToCtrlNames, WBP_CreateWaveBuilderPanel, WBP_DeleteAnalysisParameter, WBP_GetAnalysisGenericFunction, WBP_GetAnalysisParameters, WBP_ListControlsPerStimulusType, WBP_LoadSet, WBP_MainWindowHook, WBP_ParameterWaveToPanel, WBP_PopMenuProc_WaveToLoad, WBP_SetVarCombineEpochFormula, WBP_StartupSettings, WBP_UpdateControlAndWave.
wave GetWaveBuilderWaveTextParamAsFree()
Return a free wave version of GetWaveBuilderWaveTextParam()
GetWaveBuilderWaveTextParam()
References AddDimLabelsToWPT, EPOCH_TYPES_TOTAL_NUMBER, SetWaveVersion, WPT_WAVE_LAYOUT_VERSION.
Referenced by GetWaveBuilderWaveTextParam, ST_CreateStimSet.
static variable GetSegWvTypeVersion()
Automated testing helper.
References SEGWVTYPE_WAVE_LAYOUT_VERSION.
variable UpgradeSegWvType(wave wv)
Upgrade the wave layout of SegWvType to the most recent one as defined in SEGWVTYPE_WAVE_LAYOUT_VERSION
References AddDimLabelsToSegWvType, ExistsWithCorrectLayoutVersion, SEGWVTYPE_WAVE_LAYOUT_VERSION, SetWaveVersion.
Referenced by GetSegmentTypeWave, WB_GetSegWvTypeForSet.
static variable AddDimLabelsToSegWvType(wave wv)
Add dimension labels to the WaveBuilder SegWvType wave.
References ASSERT, ROWS, WB_TOTAL_NUMBER_OF_EPOCHS.
Referenced by GetSegmentTypeWaveAsFree, UpgradeSegWvType.
wave GetSegmentTypeWave()
Returns the segment type wave used by the wave builder panel Remember to change WB_TOTAL_NUMBER_OF_EPOCHS if changing the wave layout.
Rows: 0 - 93: epoch types using one of WaveBuilderEpochTypes 94: Inter trial interval delta operation, one of WaveBuilderDeltaOperationModes 95: Inter trial interval delta multiplier/exponent [a. u.] 96: Inter trial interval delta [s] 97: Stimset global RNG seed 98: Data flipping (1 or 0) 99: Inter trial interval [s] 100: total number of segments/epochs 101: total number of steps
References GetSegmentTypeWaveAsFree, GetWaveBuilderDataPath, UpgradeSegWvType.
Referenced by WB_CustomWavesPathFromStimSet, WB_GetStimSet, WB_StimsetChildren, WB_UpgradeCustomWaves, WBP_AdjustDeltaControls, WBP_ButtonProc_SaveSet, WBP_ChangeWaveType, WBP_ConvertDeltaLblToCtrlNames, WBP_CreateWaveBuilderPanel, WBP_DisplaySetInPanel, WBP_HighPassDeltaLimits, WBP_InitialTabHook, WBP_LoadSet, WBP_LowPassDeltaLimits, WBP_MainWindowHook, WBP_SetVarProc_EpochToEdit, WBP_StartupSettings, WBP_UpdateControlAndWave, WBP_UpdateEpochControls.
wave GetSegmentTypeWaveAsFree()
Return a free wave version of GetSegmentTypeWave()
GetSegmentTypeWave()
References AddDimLabelsToSegWvType, SEGWVTYPE_WAVE_LAYOUT_VERSION, SetWaveVersion.
Referenced by GetSegmentTypeWave, ST_CreateStimSet.
wave GetEpochID()
Return the wave identifiying the begin and end times of the current epoch.
References COLS, GetWaveBuilderDataPath.
Referenced by WB_MakeWaveBuilderWave, WB_UpdateEpochID, WBP_AddEpochHLTraces, WBP_MainWindowHook.
wave GetWaveBuilderDispWave()
Return the wave for visualization of the stim set in the wavebuilder panel.
References GetWaveBuilderDataPath.
Referenced by WBP_DisplaySetInPanel.
wave GetWBEpochCombineList()
References GetWaveBuilderDataPath.
Referenced by WB_FormulaSwitchToShorthand, WB_FormulaSwitchToStimset, WB_UpdateEpochCombineList, WBP_CreateWaveBuilderPanel.
wave GetSegmentWave(variable duration=defaultValue)
Returns the segment wave which stores the stimulus set of one segment/epoch.
duration time of the stimulus in ms
References DoAbortNow, GetWaveBuilderDataPath, MAX_SWEEP_DURATION_IN_MS, ROWS, WAVEBUILDER_MIN_SAMPINT.
Referenced by WB_ApplyOffset, WB_CustomWaveSegment, WB_MakeWaveBuilderWave, WB_NoiseSegment, WB_PSCSegment, WB_PulseTrainSegment, WB_RampSegment, WB_SawToothSegment, WB_SquareSegment, WB_TrigSegment.
wave GetEpochParameterNames()
References GetWaveBuilderDataPath, ROWS.
wave GetTPStorage(string device)
Return a wave reference for TPStorage.
Stores properties of the testpulse during TP ROWS: One entry per step COLS: NUM_HEADSTAGES LAYERS: 0: Amplifier holding command (Voltage Clamp) 1: Amplifier bias current (Current Clamp) 2: (Peak/Instantaneous) Resistance 3: (Steady State) Resistance 4: Time in s (arbitrary zero) 5: Delta time in s relative to the entry in the first row of layer 3 6: (Steady State) Resistance slope 7: Pressure in psi 8: Timestamp since igor epoch (with timezone offsets) 9: Timestamp in UTC since igor epoch 10: Pressure changed 11: Holding current (pA, Voltage Clamp) 12: Vrest (mV, Current Clamp) 13: AD channel 14: DA channel 15: Headstage 16: ClampMode 17: UserPressure 18: PressureMethod (see PressureModeConstants) 19: ValidState (true if the entry is considered valid, false otherwise) 20: UserPressureType (see PressureTypeConstants) 21: UserPressureTimeStampUTC timestamp since Igor Pro epoch in UTC where the user pressure was acquired 22: TPMarker unique number identifying this set of TPs 23: Cell state: Pressure control values defining the cell state, one of CellStateValues 24: Testpulse Cycle Id (changes whenever TP is started, allows to group TPs together) 25: Auto TP Amplitude: success/fail state 26: Auto TP Baseline: success/fail state 27: Auto TP Baseline Range Exceeded: True/False 28: Auto TP Cycle ID: Unique number which is constant until the "Auto TP" state is switched (aka on->off or off->on) 29: Auto TP Baseline Fit result: One of TPBaselineFitResults 30: Auto TP Delta V [mV]
References AUTOBIAS_LAST_INVOCATION_KEY, COLS, DIMENSION_SCALING_LAST_INVOC, ExistsWithCorrectLayoutVersion, GetDeviceTestPulse, INDEX_ON_TP_START, LAYERS, MINIMUM_WAVE_SIZE_LARGE, NOTE_INDEX, NUM_HEADSTAGES, PRESSURE_CTRL_LAST_INVOC, SetNumberInWaveNote, SetWaveVersion, WaveVersionIsSmaller.
Referenced by DQ_ApplyAutoBias, FFI_ReturnTPValues, GetLogbookWaves, P_AddSealedEntryToTPStorage, P_RecordUserPressure, P_UpdateSSRSlopeAndSSR, P_UpdateTPStorage, SCOPE_CreateGraph, SCOPE_GetTPTopAxisStart, TP_AutoAmplitudeAndBaseline, TP_PublishAutoTPResult, TP_RecordTP, TP_SetupCommon, TP_TestPulseHasCycled, TP_UpdateHoldCmdInTPStorage.
wave GetAcqTPStorage()
Return a free wave reference for AcqTPStorage wave for passing to ACQ4.
The wave stores PeakResistance, SteadyStateResistance, and TimeStamp in rows and headstages in cols
References COLS, HARDWARE_MAX_DEVICES, NUM_HEADSTAGES, ROWS.
Referenced by FFI_ReturnTPValues.
dfref GetDeviceTestPulse(string device)
Return a datafolder reference to the test pulse folder.
References createDFWithAllParents, GetDeviceTestPulseAsString.
Referenced by AB_ReExport, GetFIFOFileRef, GetLastAcqHookCallTimeStamp, GetNITestPulseCounter, GetStoredTestPulseWave, GetTestpulseCycleID, GetTestpulseRunMode, GetTPResultAsyncBuffer, GetTPResults, GetTPResultsBuffer, GetTPSettings, GetTPSettingsCalculated, GetTPStorage, LBV_GetTPStorageLocation, NWB_WriteTestpulseData, SaveExperimentSpecial, TP_SplitStoredTestPulseWave.
string GetDeviceTestPulseAsString(string device)
Return the path to the test pulse folder, e.g. root:mies:HardwareDevices:ITC1600:Device0:TestPulse.
References GetDevicePathAsString.
Referenced by AB_LoadTPStorageFromIgor, AB_ReExport, GetAllDevicesWithContent, GetDeviceTestPulse.
wave GetScaledDataWave(string device)
Return a wave which holds undecimated and scaled data.
Rows: StopCollectionPoint Columns: Number of active channels Type: FP32 or FP64, as returned by SWS_GetRawDataFPType()
References GetDevicePath, NUM_DA_TTL_CHANNELS, SWS_GetRawDataFPType.
Referenced by AFM_CallAnalysisFunctions, DC_MakeHelperWaves, SCOPE_ITC_AdjustFIFOPos, SCOPE_ITC_UpdateOscilloscope, SCOPE_NI_UpdateOscilloscope, SCOPE_UpdateOscilloscopeData, SWS_SaveAcquiredData.
wave GetOscilloscopeWave(string device)
Return a wave for displaying scaled data in the oscilloscope window.
Contents can be decimated for faster display.
References GetDevicePath, NUM_DA_TTL_CHANNELS.
Referenced by DC_MakeHelperWaves, SCOPE_CreateGraph, SCOPE_ITC_UpdateOscilloscope, SCOPE_NI_UpdateOscilloscope, SCOPE_UpdateGraph, SCOPE_UpdatePowerSpectrum.
wave GetTPOscilloscopeWave(string device)
Return a wave for displaying scaled TP data in the oscilloscope window for the "TP during DAQ" channels or for TP power spectrum during Test Pulse.
Rows: Holds exactly one TP Columns: DA/AD/TTLs data, same order as GetDAQDataWave()
References GetDevicePath, NUM_DA_TTL_CHANNELS.
Referenced by DC_MakeHelperWaves, SCOPE_CreateGraph, SCOPE_UpdateGraph, SCOPE_UpdateOscilloscopeData, SCOPE_UpdatePowerSpectrum.
wave GetStoredTestPulseWave(string device)
Return a wave reference wave for storing the full test pulses.
References GetDeviceTestPulse, MINIMUM_WAVE_SIZE, NOTE_INDEX, SetNumberInWaveNote.
Referenced by NWB_AppendStoredTestPulses, TP_GetStoredTPs, TP_SplitStoredTestPulseWave, TP_StoreTP.
wave GetTPResults(string device)
Return the testpulse results wave.
Rows: 0: Resistance Instantaneous: [MΩ] 1: Baseline Steady State: [mV] for IC, [pA] for VC 2: Resistance Steady State: [MΩ] 3: Elevated Steady State: [mV] for IC, [pA] for VC 4: Elevated Instantaneous: [mV] for IC, [pA] for VC 5: Auto TP Amplitude: Pass/Fail 6: Auto TP Baseline: Pass/Fail 7: Auto TP Baseline range exceeded: True/False 8: Auto TP Baseline fit result: One of TPBaselineFitResults 9: Auto TP Delta V: [mV] Columns: NUM_HEADSTAGES
References ExistsWithCorrectLayoutVersion, GetDeviceTestPulse, KillOrMoveToTrash, NUM_HEADSTAGES, ROWS, SetDimensionLabels, SetWaveVersion.
Referenced by AI_MIESAutoPipetteOffset, AI_ZeroAmps, BWO_CheckAndClearPipettes, ED_TPDocumentation, GetTPResultsBuffer, IVS_finishGigOhmSealQCCheck, IVS_finishInitAccessQCCheck, SCOPE_CreateGraph, TP_ROAnalysis.
wave GetTPResultsBuffer(string device)
Return the testpulse results buffer wave.
Same layout as GetTPResults() but as many layers as the buffer size.
References ExistsWithCorrectLayoutVersion, GetDeviceTestPulse, GetTPResults, GetTPSettings, INDEP_HEADSTAGE, NOTE_INDEX, SetNumberInWaveNote, SetWaveVersion.
Referenced by DC_Configure, TP_ROAnalysis.
dfref GetAmplifierFolder()
Return the datafolder reference to the amplifier.
References createDFWithAllParents, GetAmplifierFolderAsString.
Referenced by GetAmplifierMultiClamps, GetAmplifierParamStorageWave, GetAmplifierTelegraphServers.
string GetAmplifierFolderAsString()
Return the path to the amplifierm e.g. root:mies:Amplifiers".
References GetMiesPathAsString.
Referenced by GetAmplifierFolder, GetAmplifierParamStorageWave.
wave GetAmplifierParamStorageWave(string device)
Return a wave reference to the amplifier parameter storage wave.
Rows: 0-31: Amplifier settings identified by dimension labels Columns: Only one Layers: 0-7: Headstage identifier Contents: numerical amplifier settings
References ExistsWithCorrectLayoutVersion, GetAmplifierFolder, GetAmplifierFolderAsString, LAYERS, NUM_HEADSTAGES, ROWS, SetWaveVersion, UpgradeWaveLocationAndGetIt.
Referenced by AI_UpdateAmpModel, AI_UpdateAmpView, DAP_LockDevice, DQ_ApplyAutoBias, P_MethodApproach, ReachTargetVoltage.
wave GetAmplifierSettingsWave()
Return a free wave reference for the amplifier settings, data wave.
Rows: Only one Columns: Amplifier parameters as described in the amplifier settings key wave Layers: 0-7: data for a particular headstage using the layer index 8: headstage independent data
References LABNOTEBOOK_LAYER_COUNT.
wave GetAmplifierSettingsKeyWave()
Return a free wave reference for the amplifier settings, key wave.
Rows: 0: Parameter 1: Units 2: Tolerance factor Columns: Various settings
References LABNOTEBOOK_BINARY_UNIT, LABNOTEBOOK_NO_TOLERANCE, ROWS.
wave GetAmplifierSettingsTextWave()
Return a free wave for the amplifier text settings, data wave.
Rows: Only one Columns: Amplifier parameters as described in the amplifier settings text key wave Layers: 0-7: data for a particular headstage using the layer index 8: headstage independent data
References LABNOTEBOOK_LAYER_COUNT.
wave GetAmplifierSettingsTextKeyWave()
Return a free wave for the amplifier text settings, key wave.
Rows: 0: Parameter 1: Units 2: Tolerance factor Columns: Various settings
References LABNOTEBOOK_NO_TOLERANCE, ROWS.
wave GetAmplifierTelegraphServers()
Return wave reference to the W_TelegraphServers wave.
Call AI_FindConnectedAmps() to create that wave, otherwise an empty wave is returned.
References GetAmplifierFolder.
Referenced by AI_GetMCCSerialNumbers, CONF_RestoreHeadstageAssociation, DAP_GetNiceAmplifierChannelList, IH_RemoveAmplifierConnWaves.
wave GetAmplifierMultiClamps()
Return wave reference to the W_MultiClamps wave.
Call AI_FindConnectedAmps() to create that wave, if that was not done an empty wave is returned.
References GetAmplifierFolder.
Referenced by IH_RemoveAmplifierConnWaves.
wave GetAsyncSettingsWave()
Return a free wave for the asyncSettingsWave, data wave.
asyncSettingsWave is used to save async settings for each data sweep and create waveNotes for tagging data sweeps Rows: One row Columns: Same as GetAsyncSettingsWave Layers: 0 - LABNOTEBOOK_LAYER_COUNT: headstage dependent and independent entries
References COLS, LABNOTEBOOK_LAYER_COUNT.
Referenced by ED_createAsyncWaveNoteTags.
wave GetAsyncSettingsKeyWave(wave settingsWave, variable channel, string title, string unit)
Return a free wave for the asyncSettingsKeyWave.
asyncSettingsKeyWave is used to index async settings for each data sweep and create waveNotes for tagging data sweeps Rows: 0: Parameter 1: Units 2: Tolerance Factor Columns: 0: Async AD $Channel OnOff 1: Async AD $Channel Gain 2: Async Alarm $Channel OnOff 3: Async Alarm $Channel Min 4: Async Alarm $Channel Max 5: Async AD $Channel [$Title]
References LABNOTEBOOK_BINARY_UNIT, LABNOTEBOOK_NO_TOLERANCE, ROWS.
Referenced by ED_createAsyncWaveNoteTags.
wave GetAsyncSettingsTextWave()
Return a free wave for the AsyncSettingsTxtWave.
AsyncSettingsTxtData is used to store the async text settings used on a particular headstage and then create waveNotes for the sweep data Rows: Only one Columns: Same as GetAsyncSettingsTextKeyWave Layers: 0 - LABNOTEBOOK_LAYER_COUNT: headstage dependent and independent entries
References COLS, LABNOTEBOOK_LAYER_COUNT.
Referenced by ED_createAsyncWaveNoteTags.
wave GetAsyncSettingsTextKeyWave(WaveText settingsWave, variable channel)
Return a free wave for the AsyncSettingsKeyTxtData.
AsyncSettingsKeyTxtData is used to index Txt Key Wave Rows: Just one Columns: 0: Async $Channel Title 1: Async $Channel Unit
Referenced by ED_createAsyncWaveNoteTags.
string P_GetDevicePressureFolderAS(string device)
Returns device specific pressure folder as string.
References GetMiesPathAsString, ParseDeviceString.
Referenced by P_DeviceSpecificPressureDFRef.
dfref P_DeviceSpecificPressureDFRef(string device)
Creates device specific pressure folder - used to store data for pressure regulators.
References P_GetDevicePressureFolderAS.
Referenced by GetPressureTypeWv, P_GetITCChanConfig, P_GetITCData, P_GetPressureDataWaveRef, P_NI_GetADWave, P_NI_GetDAWave, P_PressureDataTxtWaveRef, P_SetAllHStoAtmospheric.
string P_GetPressureFolderAS(string device)
Returns pressure folder as string.
References GetMiesPathAsString.
Referenced by P_PressureFolderReference.
dfref P_PressureFolderReference(string device)
Returns the data folder reference for the main pressure folder "root:MIES:Pressure".
References P_GetPressureFolderAS.
wave P_GetITCData(string device)
Returns a wave reference to the DAQ data wave used for pressure pulses.
Rows: data points, see P_GetITCChanConfig() for the sampling interval Columns: 0: DA data 1: AD data 2: TTL data rack 0 3: TTL data rack 1 (available if supported by the device)
References COLS, MINIMUM_ITCDATAWAVE_EXPONENT, P_DeviceSpecificPressureDFRef.
Referenced by P_DataAcq, P_FillDAQWaves, P_PrepareITCWaves, P_TTLforPpulse.
wave P_GetITCChanConfig(string device)
Returns a wave reference to the DAQ config wave used for pressure pulses.
Rows: 0: DA channel specifications 1: AD channel specifications 2: TTL rack 0 specifications 3: TTL rack 1 specifications (available if supported by the device) Columns: 0: Channel Type 1: Channel number 2: Sampling interval 3: Decimation
References COLS, P_DeviceSpecificPressureDFRef, ROWS, WAVEBUILDER_MIN_SAMPINT, XOP_CHANNEL_TYPE_ADC, XOP_CHANNEL_TYPE_DAC, XOP_CHANNEL_TYPE_TTL.
Referenced by P_DataAcq, P_ITC_SetChannels, P_PrepareITCWaves.
static variable SetPressureWaveDimLabels(wave wv)
Set the dimension labels for the numeric pressure wave.
References COLS, ROWS.
Referenced by P_GetPressureDataWaveRef.
wave P_GetPressureDataWaveRef(string device)
Returns wave reference of wave used to store data used in functions that run pressure regulators creates the wave if it does not exist.
Rows: 0 - 7: Headstage 0 through 7 Columns: 0: Pressure method. -1 = none, 0 = Approach, 1 = Seal, 2 = Break In, 3 = Clear 1: List position of DAC (used for presssure control) selected for headstage 2: Type of DAC, index into HARDWARE_DAC_TYPES 3: Device ID used by Instrutech DACs or index into HW_NI_ListDevices depending on column 2 4: DA channel used for pressure regulation. 5: Gain of DA channel used for presssure regulation. 6: AD channel used for pressure regulation. 7: Gain of AD channel used for pressure regulation. 8: TTL channel A used for pressure regulation. 9: Pipette pressure setting while pipette is positioned in air/outside of bath. 10: Pipette pressure setting for pipette positioned in the bath. 11: Pipette pressure setting for pipette positioned in the slice. 12: Pipette pressure setting for pipette positioned near the target cell. 13: Pipette pressure setting for pipette at the initialization of seal formation. 14: Maximum Pipette pressure setting for seal formation. 15: Distance between the bottom of the recording chamber to the surface of the bath solution. 16: Distance between the bottom of the recording chamber and the top of the tissue slice. 17: Distance between the bottom of the recording chamber and the soma of the target cell. 18: X position (in the stage frame) of the soma of the target cell. 19: Y position (in the stage frame) of the soma of the target cell. 20: Place holder for future data. 21: Realtime pressure 22: Last steady state resistance value. 23: Slope of the peak TP resistance over the last 5 seconds. 24: State of the TP (0 = OFF, 1 = ON). 25: Slope threshold. Used to determine if pressure should be incremented during sealing. 26: Time of last slope check 27: Last pressure command. 28: State of pressure pulse (0 = OFF, 1 = ON). 29: Last amplifier voltage command. 30: Manual pressure command amplitude in psi. 31: Manual pressure pulse command amplitude in psi. 32: Manual pressure pulse duation in ms. 33: Peak resistance on previous method cycle. 34: Peak resistance on active method cycle. 35: Time of last peak resistance check. 36: Calibration constant for positive pulse. 37: Calibration constant for negative pulse. 38: Checkbox state of "Approach Near". 39: Checkbox state of "Seal Atmosphere". 40: Selected headstage by the slider. 41: User pressure offset in psi. 42: Total sum of user pressure offsets in psi. 43: Total sum of user pressure offsets since last pulse in psi. 44: TTL channel B used for pressure regulation. 45: User pressure deviceID 46: User pressure device hardware type 47: User pressure ADC
References ExistsWithCorrectLayoutVersion, P_DeviceSpecificPressureDFRef, SetPressureWaveDimLabels, SetWaveVersion.
Referenced by BWO_CheckAndClearPipettes, BWO_CheckGlobalSettings, CONF_GetAmplifierSettings, CONF_RestoreHeadstageAssociation, DAP_CheckProc_Settings_PUser, P_ApplyNegV, P_ButtonProc_UserPressure, P_CheckAll, P_CloseDeviceLowLevel, P_DACIsCollectingData, P_DAforManPpulse, P_DAforNegPpulse, P_DAforPosPpulse, P_DataAcq, P_DeviceIsUsedForPressureCtrl, P_FillDAQWaves, P_FindDeviceExecutingPP, P_GetAutoUserOff, P_GetPressureForDA, P_GetPressureMode, P_GetPulseAmp, P_GetUserAccess, P_InitBeforeTP, P_ITC_FIFOMonitorProc, P_ITC_SetChannels, P_LoadPressureButtonState, P_ManSetPressure, P_MethodApproach, P_MethodAtmospheric, P_MethodBreakIn, P_MethodClear, P_MethodSeal, P_NI_GetADWave, P_NI_GetDAWave, P_NI_StopDAQ, P_OpenDevice, P_PressureControl, P_PressureDisplayHighlite, P_RecordUserPressure, P_ResetPressureData, P_SaveUserSelectedHeadstage, P_SetAndGetPressure, P_SetPressureMode, P_SetPressureOffset, P_SetPressureValves, P_TTLforPpulse, P_UpdatePopupDevices, P_UpdatePressureControls, P_UpdatePressureDataStorageWv, P_UpdatePressureMode, P_UpdatePressureModeTabs, P_UpdatePressureType, P_UpdateSSRSlopeAndSSR, P_UpdateTPStorage, P_UpdateTTLstate, P_ValidatePressureSetHeadstage, SCOPE_CreateGraph.
wave P_PressureDataTxtWaveRef(string device)
Returns wave reference for wave used to store text used in pressure control.
Rows: 0 - 7: Headstage 0 through 7 Columns: 0: Digitial to analog converter device type string. 1: DA unit. 2: AD unit.
References COLS, ExistsWithCorrectLayoutVersion, NONE, P_DeviceSpecificPressureDFRef, ROWS, SetWaveVersion.
Referenced by P_GetListOfPressureCtrlDevices, P_HeadstageUsingDevice, P_OpenDevice, P_TTLforPpulse, P_UpdatePopupDevices, P_UpdatePressureControls, P_UpdatePressureDataStorageWv, P_ValidatePressureSetHeadstage.
dfref GetAnalysisFolder()
Return the datafolder reference to the root folder for the analysis browser.
References createDFWithAllParents, GetAnalysisFolderAS.
Referenced by AB_AddMapEntry, AB_ClearAnalysisFolder, AB_LoadLabNotebookFromIgor, AB_LoadStimsetRAW, AB_LoadStimsetTemplateWaves, AB_LoadSweepFromIgor, AB_LoadWave, GetAnalysisBrowserMap, GetExperimentBrowserGUIList, GetExperimentBrowserGUISel.
string GetAnalysisFolderAS()
Return the full path to the root analysis folder, e.g. root:MIES:analysis.
References GetMiesPathAsString.
Referenced by GetAnalysisExpFolderAS, GetAnalysisFolder, SBE_ExportSweepBrowser.
dfref GetAnalysisExpFolder(string expFolder)
Return the datafolder reference to the per experiment folder.
References createDFWithAllParents, GetAnalysisExpFolderAS.
Referenced by AB_GetAllDevicesForExperiment, AB_HasCompatibleVersion, AB_TranslatePath, GetAnalysisDeviceWave.
string GetAnalysisExpFolderAS(string expFolder)
Return the full path to the per experiment folder, e.g. root:MIES:Analysis:my_experiment.
References GetAnalysisFolderAS.
Referenced by GetAnalysisDeviceFolderAS, GetAnalysisExpFolder, GetAnalysisResultsFolderAsString.
dfref GetAnalysisDeviceFolder(string expFolder, string device)
Return the datafolder reference to the per device folder of an experiment.
References createDFWithAllParents, GetAnalysisDeviceFolderAS.
Referenced by AB_ButtonProc_OpenCommentNB, AB_LoadUserCommentAndHistoryFromNWB, AB_LoadUserCommentFromFile, AB_ReExport.
string GetAnalysisDeviceFolderAS(string expFolder, string device)
Return the full path to the per device folder of an experiment, e.g. root:MIES:Analysis:my_experiment:ITC18USB_Dev_0.
References GetAnalysisExpFolderAS.
Referenced by GetAnalysisDevChannelFolderAS, GetAnalysisDeviceConfigFolderAS, GetAnalysisDeviceFolder, GetAnalysisDeviceTestpulseAS, GetAnalysisLabNBFolderAS, GetAnalysisStimSetPathAS, GetAnalysisSweepPathAsString.
dfref GetAnalysisDevChannelFolder(string expFolder, string device)
Return the datafolder reference to the sweep to channel relation of a device and experiment pair.
References createDFWithAllParents, GetAnalysisDevChannelFolderAS.
Referenced by GetAnalysisChannelAcqWave, GetAnalysisChannelStimWave, GetAnalysisChannelStorage, GetAnalysisChannelSweepWave.
string GetAnalysisDevChannelFolderAS(string expFolder, string device)
Return the full path to the sweep to channel relation folder of a device and experiment pair, e.g. root:MIES:Analysis:my_experiment:ITC18USB_Dev_0:channel.
References GetAnalysisDeviceFolderAS.
Referenced by GetAnalysisDevChannelFolder.
dfref GetAnalysisDeviceConfigFolder(string expFolder, string device)
Return the datafolder reference to the sweep config folder of a device and experiment pair.
References createDFWithAllParents, GetAnalysisDeviceConfigFolderAS.
Referenced by AB_LoadSweepConfigData, AB_LoadSweepsFromExperiment, AB_ReExport, GetAnalysisConfigWave.
string GetAnalysisDeviceConfigFolderAS(string expFolder, string device)
Return the full path to the sweep config folder of a device and experiment pair, e.g. root:MIES:Analysis:my_experiment:ITC18USB_Dev_0:config.
References GetAnalysisDeviceFolderAS.
Referenced by GetAnalysisDeviceConfigFolder.
dfref GetAnalysisDeviceTestpulse(string expFolder, string device)
Return the datafolder reference to the testpulse folder of a device and experiment pair.
References createDFWithAllParents, GetAnalysisDeviceTestpulseAS.
Referenced by AB_LoadTPStorageFromIgor, AB_LoadTPStorageFromNWB, GetAnalysisStoredTestPulses, LBV_GetTPStorageLocation.
string GetAnalysisDeviceTestpulseAS(string expFolder, string device)
Return the full path to the testpulse folder of a device and experiment pair, e.g. root:MIES:Analysis:my_experiment:ITC18USB_Dev_0:testpulse.
References GetAnalysisDeviceFolderAS.
Referenced by GetAnalysisDeviceTestpulse.
dfref GetAnalysisLabNBFolder(string expFolder, string device)
Return the datafolder reference to the labnotebook folder of a device and experiment pair.
References createDFWithAllParents, GetAnalysisLabNBFolderAS.
Referenced by AB_FillListWave, AB_GetSweepsFromLabNotebook, AB_LoadLabNotebook, AB_LoadLabNotebookFromIgorLow, AB_LoadLabNotebookFromNWB, AB_ReExport, AB_SplitSweepIntoComponents, GetAnalysLBNumericalKeys, GetAnalysLBNumericalValues, GetAnalysLBTextualKeys, GetAnalysLBTextualValues, NWB_GetStimsetFromSpecificSweep.
string GetAnalysisLabNBFolderAS(string expFolder, string device)
Return the full path to the labnotebook folder of a device and experiment pair, e.g. root:MIES:Analysis:my_experiment:labnotebook.
References GetAnalysisDeviceFolderAS.
Referenced by GetAnalysisLabNBFolder.
dfref GetAnalysisSweepPath(string expFolder, string device)
Return the datafolder reference to the sweep folder of a device and experiment pair.
References createDFWithAllParents, GetAnalysisSweepPathAsString.
Referenced by AB_ReExport, BSP_ButtonProc_RestoreData, GetAnalysisSweepDataPathAS, SB_AddSweepToGraph, SB_UpdateSweepPlot.
string GetAnalysisSweepPathAsString(string expFolder, string device)
Return the full path to the sweep folder of a device and experiment pair, e.g. root:MIES:Analysis:my_experiment:sweep.
References GetAnalysisDeviceFolderAS.
Referenced by GetAnalysisSweepPath.
dfref GetAnalysisSweepDataPath(string expFolder, string device, variable sweep)
Return the datafolder reference to the per sweep folder.
References createDFWithAllParents, GetAnalysisSweepDataPathAS.
Referenced by AB_SplitSweepIntoComponents, BSP_UpdateSweepNote.
string GetAnalysisSweepDataPathAS(string expFolder, string device, variable sweep)
Return the full path to the the per sweep folder, e.g. root:MIES:Analysis:my_experiment:sweep:X_$sweep.
References ASSERT, GetAnalysisSweepPath, GetSingleSweepFolderAsString, IsValidSweepNumber.
Referenced by AB_LoadSweepFromFile, GetAnalysisSweepDataPath.
dfref GetAnalysisStimSetPath(string expFolder, string device)
Return the datafolder reference to the stim set folder.
References createDFWithAllParents, GetAnalysisStimSetPathAS.
string GetAnalysisStimSetPathAS(string expFolder, string device)
Return the full path to the stim set folder, e.g. root:MIES:Analysis:my_experiment::stimset.
References GetAnalysisDeviceFolderAS.
Referenced by GetAnalysisStimSetPath.
dfref GetAnalysisResultsFolder(string expFolder)
Return the datafolder reference to results folder of an experiment.
References createDFWithAllParents, GetAnalysisResultsFolderAsString.
Referenced by AB_LoadResultsFromIgor, AB_LoadResultsFromNWB, GetAnalysisResultsWave.
string GetAnalysisResultsFolderAsString(string expFolder)
Return the datafolder reference to results folder of an experiment, e.g. root:MIES:Analysis:my_experiment:results.
References GetAnalysisExpFolderAS.
Referenced by GetAnalysisResultsFolder.
wave GetAnalysisResultsWave(string expFolder, variable type)
Return one of the four results waves.
expFolder experiment datafolder name type One of LabnotebookWaveTypes
References ASSERT, GetAnalysisResultsFolder, LBN_NUMERICAL_KEYS, LBN_NUMERICAL_VALUES, LBN_TEXTUAL_KEYS, LBN_TEXTUAL_VALUES.
Referenced by SB_GetLogbookWave.
wave GetAnalysisChannelStorage(string dataFolder, string device)
wave is used to relate it's index to sweepWave and deviceWave.
References COLS, ExistsWithCorrectLayoutVersion, GetAnalysisDevChannelFolder, MINIMUM_WAVE_SIZE, NOTE_INDEX, SetNumberInWaveNote, SetWaveVersion.
Referenced by AB_LoadSweepFromNWB.
wave GetAnalysisChannelStimWave(string dataFolder, string device)
Return a wave containing all stimulus channels in the NWB file as a ";"-separated List wave is used to relate it's index to sweepWave and deviceWave.
References GetAnalysisDevChannelFolder, MINIMUM_WAVE_SIZE, NOTE_INDEX, SetNumberInWaveNote.
Referenced by AB_LoadSweepFromNWB, AB_LoadSweepsFromNWB.
wave GetAnalysisChannelAcqWave(string dataFolder, string device)
Return a wave containing all acquisition channels in the NWB file as a ";"-separated List wave is used to relate it's index to sweepWave and deviceWave.
References GetAnalysisDevChannelFolder, MINIMUM_WAVE_SIZE, NOTE_INDEX, SetNumberInWaveNote.
Referenced by AB_LoadSweepFromNWB, AB_LoadSweepsFromNWB.
wave GetAnalysisChannelSweepWave(string dataFolder, string device)
Return a wave containing all sweeps in a unique fashion. wave is used to relate it's index to channelWave and deviceWave.
References GetAnalysisDevChannelFolder, MINIMUM_WAVE_SIZE, NOTE_INDEX, SetNumberInWaveNote.
Referenced by AB_LoadAllSweepsAndStimsets, AB_LoadFile, AB_LoadSweepFromNWB, AB_LoadSweepsFromExperiment, AB_LoadSweepsFromNWB.
wave GetAnalysisDeviceWave(string dataFolder)
Return a wave containing all devices wave is used to relate it's index to sweepWave and channelWave.
References GetAnalysisExpFolder, MINIMUM_WAVE_SIZE, NOTE_INDEX, SetNumberInWaveNote.
Referenced by AB_LoadSweepFromNWB, AB_SaveDeviceList, LBV_GetAllDevicesForExperiment.
wave GetAnalysisStoredTestPulses(string dataFolder, string device)
Return wave with all stored test pulses.
References GetAnalysisDeviceTestpulse.
Referenced by AB_LoadStoredTestpulsesFromNWB.
wave GetAnalysisBrowserMap()
Return AnalysisBrowser indexing storage wave.
Rows: Experiments found in current Directory Columns: 0: DiscLocation: Path to Experiment on Disc 1: FileName: Name of File in experiment column in ExperimentBrowser 2: DataFolder Data folder inside current Igor experiment 3: FileType File Type identifier for routing to loader functions, one of AnalysisBrowserFileTypes
References ANALYSISBROWSER_FILE_TYPE_IGOR, COLS, WaveLocationMod::dfr, ExistsWithCorrectLayoutVersion, GetAnalysisFolder, MINIMUM_WAVE_SIZE, NOTE_INDEX, SetNumberInWaveNote, SetWaveVersion, UpgradeWaveLocationAndGetIt.
Referenced by AB_AddMapEntry, AB_ButtonProc_OpenCommentNB, AB_ButtonProc_ResaveAsNWB, AB_ClearAnalysisFolder, AB_GetAllExperiments, AB_GetMap, AB_LoadFromExpandedRange, AB_LoadFromFile, AB_LoadStimsetForSweep, AB_ReExport, AB_RemoveMapEntry, SB_TranslateSBMapIndexToABMapIndex.
wave GetExperimentBrowserGUIList()
Return the text wave used in the listbox of the experiment browser.
The "experiment" column in the second layer maps to the corresponding row in the experimentMap.
References ANALYSIS_BROWSER_LISTBOX_WAVE_VERSION, COLS, ExistsWithCorrectLayoutVersion, GetAnalysisFolder, MINIMUM_WAVE_SIZE, NOTE_INDEX, NUM_COLUMNS_LIST_WAVE, SetNumberInWaveNote, SetWaveVersion.
Referenced by AB_AddFile, AB_ButtonProc_OpenCommentNB, AB_ButtonProc_SelectStimSets, AB_ClearAnalysisFolder, AB_CollapseListEntry, AB_ExpandListEntry, AB_FillListWave, AB_ListBoxProc_ExpBrowser, AB_LoadFromExpandedRange, AB_LoadFromFile, AB_OpenAnalysisBrowser, AB_ResetListBoxWaves, AB_ScanFolder, BeforeFileOpenHook.
wave GetExperimentBrowserGUISel()
Return the selection wave used in the listbox of the experiment browser.
References ANALYSIS_BROWSER_LISTBOX_WAVE_VERSION, ExistsWithCorrectLayoutVersion, GetAnalysisFolder, MINIMUM_WAVE_SIZE, NUM_COLUMNS_LIST_WAVE, SetWaveVersion.
Referenced by AB_ButtonProc_OpenCommentNB, AB_ButtonProc_SelectStimSets, AB_ClearAnalysisFolder, AB_CollapseListColumn, AB_CollapseListEntry, AB_ExpandIfCollapsed, AB_ExpandListColumn, AB_ExpandListEntry, AB_GetExpandedIndices, AB_ListBoxProc_ExpBrowser, AB_LoadFromExpandedRange, AB_OpenAnalysisBrowser, AB_ResetListBoxWaves, AB_ReturnAndClearGUISelBits, AB_SetGUISelBits.
wave GetAnalysisConfigWave(string dataFolder, string device, variable sweep)
Return the configSweep wave of a given sweep from the analysis subfolder.
References COLS, GetAnalysisDeviceConfigFolder, GetConfigWaveName.
Referenced by AB_LoadSweepFromFile, AB_LoadSweepFromNWB, AB_SplitSweepIntoComponents, SB_AddSweepToGraph, SB_UpdateSweepPlot.
wave ANALYSIS_LBN_GETTER_PROTO(string expFolder, string device)
References ASSERT.
wave GetAnalysLBNumericalValues(string expFolder, string device)
Return the numerical labnotebook values in the analysis browser of a device and experiment pair.
References WaveLocationMod::dfr, GetAnalysisLabNBFolder, UpgradeWaveLocationAndGetIt.
Referenced by AB_FillListWave, SB_AddSweepToGraph, SB_GetSweepPropertyFromNumLBN, SB_UpdateSweepPlot.
wave GetAnalysLBTextualValues(string expFolder, string device)
Return the textual labnotebook keys in the analysis browser of a device and experiment pair.
References WaveLocationMod::dfr, GetAnalysisLabNBFolder, UpgradeWaveLocationAndGetIt.
Referenced by AB_FillListWave, SB_AddSweepToGraph, SB_UpdateSweepPlot.
wave GetAnalysLBNumericalKeys(string expFolder, string device)
Return the numerical labnotebook keys in the analysis browser of a device and experiment pair.
References WaveLocationMod::dfr, GetAnalysisLabNBFolder, UpgradeWaveLocationAndGetIt.
wave GetAnalysLBTextualKeys(string expFolder, string device)
Return the textual labnotebook keys in the analysis browser of a device and experiment pair.
References WaveLocationMod::dfr, GetAnalysisLabNBFolder, UpgradeWaveLocationAndGetIt.
dfref GetCacheFolder()
References createDFWithAllParents, GetCacheFolderAS.
Referenced by GetCacheKeyWave, GetCacheStatsWave, GetCacheValueWave.
string GetCacheFolderAS()
Return the full path to the wave cache datafolder, e.g. root:MIES:Cache UTF_NOINSTRUMENTATION.
References GetMiesPathAsString.
Referenced by GetCacheFolder, SaveExperimentSpecial.
wave GetCacheValueWave()
Return the wave reference wave holding the cached data.
Dimension sizes and NOTE_INDEX value must coincide with other two cache waves. UTF_NOINSTRUMENTATION
References GetCacheFolder, MINIMUM_WAVE_SIZE, NOTE_INDEX, SetNumberInWaveNote.
Referenced by CA_DeleteCacheEntry, CA_FlushCache, CA_MakeSpaceForNewEntry, CA_StoreEntryIntoCache, CA_TryFetchingEntryFromCache, GetCacheStatsWave.
wave GetCacheKeyWave()
Return the wave reference wave holding the cache keys.
Dimension sizes and NOTE_INDEX value must coincide with other two cache waves. UTF_NOINSTRUMENTATION
References GetCacheFolder, MINIMUM_WAVE_SIZE, NOTE_INDEX, SetNumberInWaveNote.
Referenced by CA_DeleteCacheEntry, CA_FlushCache, CA_GetCacheIndex, CA_MakeSpaceForNewEntry, CA_StoreEntryIntoCache, CA_TryFetchingEntryFromCache, GetCacheStatsWave.
wave GetCacheStatsWave()
Return the wave reference wave holding the cache stats.
Rows: One for each cache entry Columns: 0: Number of cache hits (Incremented for every read) 1: Number of cache misses (Increment for every failed lookup) 2: Modification timestamp (Updated on write) 3: Size in bytes (Updated on write) Dimension sizes and NOTE_INDEX value must coincide with other two cache waves. UTF_NOINSTRUMENTATION
References ASSERT_TS, COLS, ExistsWithCorrectLayoutVersion, GetCacheFolder, GetCacheKeyWave, GetCacheValueWave, GetNumberFromWaveNote, NOTE_INDEX, ROWS, SetNumberInWaveNote, SetWaveVersion, WaveVersionIsAtLeast.
Referenced by CA_DeleteCacheEntry, CA_FlushCache, CA_MakeSpaceForNewEntry, CA_OutputCacheStatistics, CA_StoreEntryIntoCache, CA_TryFetchingEntryFromCache.
dfref GetDebugPanelFolder()
References createDFWithAllParents, GetDebugPanelFolderAS.
Referenced by GetDebugPanelListSelWave, GetDebugPanelListWave.
string GetDebugPanelFolderAS()
Return the full path to the debug datafolder, e.g. root:MIES:Debug.
References GetMiesPathAsString.
Referenced by GetDebugPanelFolder.
wave GetDebugPanelListWave()
Return the list wave for the debug panel.
References ExistsWithCorrectLayoutVersion, GetDebugPanelFolder, MINIMUM_WAVE_SIZE.
Referenced by DP_DebuggingEnabledForFile, DP_FillDebugPanelWaves, DP_OpenDebugPanel.
wave GetDebugPanelListSelWave()
Return the list selection wave for the debugging panel.
References ExistsWithCorrectLayoutVersion, GetDebugPanelFolder, MINIMUM_WAVE_SIZE.
Referenced by DP_DebuggingEnabledForFile, DP_FillDebugPanelWaves, DP_OpenDebugPanel, DP_PopMenuProc_Selection.
wave GetAnalysisFuncIndexingHelper(string device)
Return a wave reference which holds an headstage-dependent index.
Can be used by analysis function to count the number of invocations.
References ExistsWithCorrectLayoutVersion, GetDevicePath, NUM_HEADSTAGES.
Referenced by AdjustDAScale, MSQ_DAScale, PSQ_DAScale, ReachTargetVoltage.
wave GetAnalysisFuncDAScaleDeltaV(string device)
Return a wave reference which holds the "Delta V" values of all sweeps from one repeated acquisition cycle.
Used by PSQ_AdjustDAScale(). Rows: Sweeps Columns: Headstages
References ExistsWithCorrectLayoutVersion, GetDevicePath, MINIMUM_WAVE_SIZE, NOTE_INDEX, NUM_HEADSTAGES, SetNumberInWaveNote, SetWaveVersion.
Referenced by AdjustDAScale, FitResistance, PSQ_DAScale, ReachTargetVoltage.
wave GetAnalysisFuncDAScaleDeltaI(string device)
Return a wave reference which holds the "Delta I" values of all sweeps from one repeated acquisition cycle.
Used by PSQ_AdjustDAScale(). Rows: Sweeps Columns: Headstages
References ExistsWithCorrectLayoutVersion, GetDevicePath, MINIMUM_WAVE_SIZE, NUM_HEADSTAGES, SetWaveVersion.
Referenced by AdjustDAScale, FitResistance, PSQ_DAScale, ReachTargetVoltage.
wave GetAnalysisFuncDAScaleRes(string device)
Return a wave reference to the fitted resistance values and its error.
Used by PSQ_AdjustDAScale(). Rows: Headstages Columns: Value Error (standard deviation)
References COLS, ExistsWithCorrectLayoutVersion, GetDevicePath, NUM_HEADSTAGES, SetWaveVersion.
Referenced by AdjustDAScale, FitResistance, PSQ_DAScale, ReachTargetVoltage.
wave GetAnalysisFuncDAScaleResFit(string device, variable headstage)
Return a wave reference to the fitted resistance wave created by CurveFit
Used by PSQ_AdjustDAScale().
References ExistsWithCorrectLayoutVersion, GetDevicePath, SetWaveVersion.
Referenced by FitResistance.
wave GetAnalysisFuncDAScaleSpikeFreq(string device, variable headstage)
Return a wave reference to the spikes frequency wave.
Used by PSQ_AdjustDAScale().
References ExistsWithCorrectLayoutVersion, GetDevicePath, SetWaveVersion.
Referenced by PSQ_DAScale.
wave GetAnalysisFuncDAScaleFreqFit(string device, variable headstage)
Return a wave reference to the spikes frequency wave.
Used by PSQ_AdjustDAScale().
References ExistsWithCorrectLayoutVersion, GetDevicePath, SetWaveVersion.
Referenced by PSQ_DAScale.
wave GetAnalysisFuncDAScales(string device, variable headstage)
Return a wave reference to the DAScale wave.
Used by PSQ_AdjustDAScale().
References ExistsWithCorrectLayoutVersion, GetDevicePath, SetWaveVersion.
Referenced by PSQ_DAScale.
const double ANALYSIS_BROWSER_LISTBOX_WAVE_VERSION
Referenced by GetExperimentBrowserGUIList, GetExperimentBrowserGUISel.
const double NUM_COLUMNS_LIST_WAVE
Referenced by GetExperimentBrowserGUIList, GetExperimentBrowserGUISel.
const string WAVE_NOTE_LAYOUT_KEY
Referenced by GetSweepBrowserMap, GetWaveVersion, SetWaveVersion.
const double WAVE_TYPE_NUMERICAL
const double WAVE_TYPE_TEXTUAL
const double PULSE_WAVE_VERSION
Referenced by GetPulseAverageWave, GetPulseAverageWaveNoteWave.
const string TP_SETTINGS_LABELS
Referenced by GetTPSettings, GetTPSettingsFree.
const double EPOCHS_WAVE_VERSION
Referenced by GetEpochsWave.
const double DQM_ACTIVE_DEV_WAVE_VERSION
Referenced by GetDQMActiveDeviceList.
const double TP_SETTINGS_WAVE_VERSION
Referenced by GetTPSettings, GetTPSettingsLabnotebook, GetTPSettingsLabnotebookKeyWave.
wave GetChanAmpAssign(string device)
Return a wave reference to the channel <-> amplifier relation wave (numeric part)
Rows: 0-3: V-Clamp: DA channel, DA gain, AD channel, AD gain 4-7: I-Clamp: DA channel, DA gain, AD channel, AD gain 8: Amplifier Serial number as returned by AxonTelegraphFindServers. This differs compared to the ones returned by MCC_FindServers, as the latter are strings with leading zeros. E.g.: "00000123" vs 123 E.g.: "Demo" vs 0 9: Amplifier Channel ID Columns: Head stage number
References DeviceCanFollow, DeviceCanLead, ExistsWithCorrectLayoutVersion, GetDevicePath, NUM_HEADSTAGES, ROWS, SetWaveVersion.
Referenced by AI_GetAmpAxonSerial, AI_GetAmpChannel, AI_UpdateChanAmpAssign, CONF_GetAmplifierSettings, DAP_ApplyClmpModeSavdSettngs, DAP_ButtonProc_ClearChanCon, DAP_ChangeHeadStageMode, DAP_CheckHeadStage, DAP_CheckSettings, DAP_RemoveClampModeSettings, DAP_UpdateChanAmpAssignPanel, DAP_UpdateChanAmpAssignStorWv, GetHeadstageFromSettings.
wave GetChanAmpAssignUnit(string device)
Return a wave reference to the channel <-> amplifier relation wave (textual part)
Rows: 0: DA unit (V-Clamp mode) 1: AD unit (V-Clamp mode) 2: DA unit (I-Clamp mode) 3: AD unit (I-Clamp mode) Columns: Head stage number
References ExistsWithCorrectLayoutVersion, GetDevicePath, NUM_HEADSTAGES, ROWS, SetWaveVersion.
Referenced by AI_UpdateChanAmpAssign, DAP_ApplyClmpModeSavdSettngs, DAP_CheckHeadStage, DAP_UpdateChanAmpAssignPanel, DAP_UpdateChanAmpAssignStorWv.
static variable ExistsWithCorrectLayoutVersion(WaveOrNull wv, variable versionOfNewWave)
Check if wv exists and has the correct version UTF_NOINSTRUMENTATION.
References GetWaveVersion.
Referenced by GetAcqStateTracking, GetActiveDevicesTPMD, GetAmplifierParamStorageWave, GetAnaFuncDashboardColorWave, GetAnaFuncDashboardHelpWave, GetAnaFuncDashboardInfoWave, GetAnaFuncDashboardListWave, GetAnaFuncDashboardSelWave, GetAnalysisBrowserMap, GetAnalysisChannelStorage, GetAnalysisFuncDAScaleDeltaI, GetAnalysisFuncDAScaleDeltaV, GetAnalysisFuncDAScaleFreqFit, GetAnalysisFuncDAScaleRes, GetAnalysisFuncDAScaleResFit, GetAnalysisFuncDAScales, GetAnalysisFuncDAScaleSpikeFreq, GetAnalysisFuncIndexingHelper, GetAnalysisFunctionStorage, GetArtefactRemovalDataWave, GetArtefactRemovalListWave, GetCacheStatsWave, GetCellElectrodeNames, GetChanAmpAssign, GetChanAmpAssignUnit, GetChannelClampMode, GetChannelSelectionWave, GetDA_EphysGuiStateNum, GetDA_EphysGuiStateTxT, GetDAQConfigWave, GetDebugPanelListSelWave, GetDebugPanelListWave, GetDeviceInfoWave, GetDeviceMapping, GetDQMActiveDeviceList, GetElapsedTimeWave, GetEpochsWave, GetExperimentBrowserGUIList, GetExperimentBrowserGUISel, GetGraphUserData, GetHSProperties, GetIndexingStorageWave, GetLBIndexCache, GetLBNidCache, GetLBNumericalKeys, GetLBRowCache, GetLBTextualKeys, GetNumericalResultsKeys, GetOverlaySweepHeadstageRemoval, GetOverlaySweepSelectionChoices, GetOverlaySweepsListSelWave, GetOverlaySweepsListWave, GetPAGraphData, GetPopupExtMenuWave, GetPulseAverageDisplayMapping, GetPulseAverageProperties, GetPulseAveragePropertiesWaves, GetPulseAverageSetImageWave, GetPulseAverageSetIndizes, GetPulseAverageWave, GetPulseAverageWaveNoteWave, GetRAPerfWave, GetSetEventFlag, GetSweepBrowserMap, GetSweepSettingsKeyWave, GetSweepSettingsTextKeyWave, GetSweepSettingsTextWave, GetSweepSettingsWave, GetTextualResultsKeys, GetTPResultAsyncBuffer, GetTPResults, GetTPResultsBuffer, GetTPSettings, GetTPSettingsCalculated, GetTPSettingsLabnotebook, GetTPSettingsLabnotebookKeyWave, GetTPStorage, GetValidAcqStateTransitions, P_GetPressureDataWaveRef, P_PressureDataTxtWaveRef, UpgradeSegWvType, UpgradeWaveParam, UpgradeWaveTextParam, WBP_GetAnalysisParamGUIHelpWave, WBP_GetAnalysisParamGUIListWave, WBP_GetAnalysisParamGUISelWave.
static variable WaveVersionIsAtLeast(WaveOrNull wv, variable existingVersion)
Check if the given wave's version is equal or larger than the given version, if version is not set false is returned.
References ASSERT_TS, GetWaveVersion, IsValidWaveVersion.
Referenced by GetCacheStatsWave.
static variable WaveVersionIsSmaller(WaveOrNull wv, variable existingVersion)
Check if the given wave's version is smaller than the given version, if version is not set true is returned.
References ASSERT_TS, GetWaveVersion, IsValidWaveVersion.
Referenced by GetDAQConfigWave, GetDQMActiveDeviceList, GetTPStorage, UpgradeLabNotebook, UpgradeWaveParam, UpgradeWaveTextParam.
variable GetWaveVersion(WaveOrNull wv)
return the Version of the Wave, returns NaN if no version was set UTF_NOINSTRUMENTATION
References GetNumberFromWaveNote, WAVE_NOTE_LAYOUT_KEY.
Referenced by ClearWaveNoteExceptWaveVersion, ExistsWithCorrectLayoutVersion, IsValidConfigWave, RecreateConfigWaveFromLBN, WaveVersionIsAtLeast, WaveVersionIsSmaller.
static variable SetWaveVersion(wave wv, variable val)
Set the wave layout version of wave.
References ASSERT_TS, IsValidWaveVersion, SetNumberInWaveNote, WAVE_NOTE_LAYOUT_KEY.
Referenced by ClearWaveNoteExceptWaveVersion, GetAcqStateTracking, GetActiveDevicesTPMD, GetAmplifierParamStorageWave, GetAnaFuncDashboardColorWave, GetAnaFuncDashboardHelpWave, GetAnaFuncDashboardInfoWave, GetAnaFuncDashboardListWave, GetAnaFuncDashboardSelWave, GetAnalysisBrowserMap, GetAnalysisChannelStorage, GetAnalysisFuncDAScaleDeltaI, GetAnalysisFuncDAScaleDeltaV, GetAnalysisFuncDAScaleFreqFit, GetAnalysisFuncDAScaleRes, GetAnalysisFuncDAScaleResFit, GetAnalysisFuncDAScales, GetAnalysisFuncDAScaleSpikeFreq, GetAnalysisFunctionStorage, GetArtefactRemovalDataWave, GetArtefactRemovalListWave, GetCacheStatsWave, GetCellElectrodeNames, GetChanAmpAssign, GetChanAmpAssignUnit, GetChannelClampMode, GetChannelSelectionWave, GetDA_EphysGuiStateNum, GetDA_EphysGuiStateTxT, GetDAQConfigWave, GetDeviceInfoWave, GetDeviceMapping, GetDQMActiveDeviceList, GetElapsedTimeWave, GetEpochsWave, GetExperimentBrowserGUIList, GetExperimentBrowserGUISel, GetGraphUserData, GetHSProperties, GetIndexingStorageWave, GetLBIndexCache, GetLBNidCache, GetLBNumericalKeys, GetLBRowCache, GetLBTextualKeys, GetNumericalResultsKeys, GetOverlaySweepHeadstageRemoval, GetOverlaySweepSelectionChoices, GetOverlaySweepsListSelWave, GetOverlaySweepsListWave, GetPAGraphData, GetPopupExtMenuWave, GetPulseAverageDisplayMapping, GetPulseAverageProperties, GetPulseAveragePropertiesWaves, GetPulseAverageSetImageWave, GetPulseAverageSetIndizes, GetPulseAverageWave, GetPulseAverageWaveNoteWave, GetRAPerfWave, GetSegmentTypeWaveAsFree, GetSetEventFlag, GetSweepSettingsKeyWave, GetSweepSettingsTextKeyWave, GetSweepSettingsTextWave, GetSweepSettingsWave, GetTextualResultsKeys, GetTPResultAsyncBuffer, GetTPResults, GetTPResultsBuffer, GetTPSettings, GetTPSettingsLabnotebook, GetTPStorage, GetValidAcqStateTransitions, GetWaveBuilderWaveParamAsFree, GetWaveBuilderWaveTextParamAsFree, P_GetPressureDataWaveRef, P_PressureDataTxtWaveRef, SaveLBNumericalDescription, UpgradeSegWvType, UpgradeWaveParam, UpgradeWaveTextParam, WBP_GetAnalysisParamGUIHelpWave, WBP_GetAnalysisParamGUIListWave, WBP_GetAnalysisParamGUISelWave.
static variable IsValidWaveVersion(variable value)
A valid wave version is a positive non-zero integer.
References IsInteger.
Referenced by ClearWaveNoteExceptWaveVersion, SetWaveVersion, WaveVersionIsAtLeast, WaveVersionIsSmaller.
variable ClearWaveNoteExceptWaveVersion(wave wv)
Clear the wave note but keep any valid wave version.
References GetWaveVersion, IsValidWaveVersion, SetWaveVersion.
Referenced by PA_CreateAndFillPulseWaveIfReq.
dfref UpgradeDataFolderLocation(string oldFolder, string newFolder)
Move/Rename a datafolder across different locations.
Both parameters must be absolute datafolder locations. Cases where both exist are also handled gracefully. embed:rst:leading-asterisk * .. code-block:: igorpro * * Function/DF GetMyFolder() * return UpgradeDataFolderLocation("root:old", "root:new") * End * DFREF to the newFolder with the contents of oldFolder
References ASSERT_TS, createDFWithAllParents, DEBUGPRINT_TS, IsEmpty, IsValidObjectName, KillOrMoveToTrash, UniqueDataFolderName.
Referenced by GetDAQDevicesFolder.
wave UpgradeWaveLocationAndGetIt(WaveLocationMod *p)
Rename/Move a wave to a new location.
Valid transformations (and all combinations of them): Moving into a new datafolder Renaming to a new name Nothing The function is idempotent (i.e. it can be called also on already relocated waves). Cases where new == old are also handled gracefully. embed:rst:leading-asterisk * .. code-block:: igorpro * * Function/WAVE GetMyWave(device) * string device * * variable versionOfNewWave = 1 * string newName = "newAndNiceName" * DFREF newDFR = GetNewAndFancyFolder(device) * * STRUCT WaveLocationMod p * p.dfr = $(GetSomeFolder(device) + ":oldSubFolder") * p.newDFR = newDFR * p.name = "oldAndUglyName" * p.newName = newName * * WAVE/Z wv = UpgradeWaveLocationAndGetIt(p) * * if(ExistsWithCorrectLayoutVersion(wv, versionOfNewWave)) * return wv * elseif(WaveExists(wv)) * // handle upgrade * else * Make/R/N=(10, 2) newDFR:newName/Wave=wv * end * * SetWaveVersion(wv, versionOfNewWave) * * return wv * End * wave reference to the wave in the new location, an invalid one if the wave does not exist at the specified former location
References ASSERT, DataFolderExistsDFR, WaveLocationMod::dfr, IsValidObjectName, WaveLocationMod::name, WaveLocationMod::newDFR, WaveLocationMod::newName, RemoveEmptyDataFolder.
Referenced by GetAmplifierParamStorageWave, GetAnalysisBrowserMap, GetAnalysLBNumericalKeys, GetAnalysLBNumericalValues, GetAnalysLBTextualKeys, GetAnalysLBTextualValues, GetLBNumericalKeys, GetLBNumericalValues, GetLBTextualKeys, GetLBTextualValues, GetOverlaySweepSelectionChoices, GetSweepSettingsKeyWave, GetSweepSettingsTextKeyWave, GetSweepSettingsTextWave, GetSweepSettingsWave.
wave GetTPResultAsyncBuffer(string device)
Return a wave reference to the tp result async buffer wave.
Rows: buffered partial result entries Column 0 (ASYNCDATA): Layers: 0: marker 1: received channels 2: now Column 1: baseline level Column 2: steady state res Column 3: instantaneous res Column 4: baseline position Column 5: steady state res position Column 6: instantaneous res position Column 7: average elevated level (steady state) Column 8: average elevated level (instantaneous) Layers: NUM_HEADSTAGES positions with value entries at hsIndex
References COLS, ExistsWithCorrectLayoutVersion, GetDeviceTestPulse, LAYERS, NUM_HEADSTAGES, SetWaveVersion.
Referenced by TP_ROAnalysis, TP_SetupCommon.
wave GetChannelClampMode(string device)
Return a wave reference to the channel clamp mode wave.
Only specialized code which does not have a headstage, or needs to know the clamp mode for unassociated channels, should use this function. Rows: Channel numbers Columns: 0: DAC 1: ADC Layers: 0: Clamp Mode 1: Headstage
References COLS, ExistsWithCorrectLayoutVersion, GetDevicePath, GetHeadstageFromSettings, LAYERS, NUM_AD_CHANNELS, SetWaveVersion, XOP_CHANNEL_TYPE_ADC, XOP_CHANNEL_TYPE_DAC.
Referenced by AFH_GetHeadstageFromADC, AFH_GetHeadstageFromDAC, DAP_ApplyClmpModeSavdSettngs, DAP_CheckHeadStage, DAP_RemoveClampModeSettings, DC_GetConfiguration.
wave GetHSProperties(string device)
Return properties for the headstages during TP/DAQ.
DC_UpdateHSProperties()
References COLS, ExistsWithCorrectLayoutVersion, GetDevicePath, NUM_HEADSTAGES, SetWaveVersion.
Referenced by DC_UpdateHSProperties, ED_TPDocumentation, SCOPE_UpdateOscilloscopeData, TP_RecordTP.
dfref GetDAQDevicesFolder()
Return the DAQ devices folder "root:mies:HardwareDevices".
References GetDAQDevicesFolderAsString, GetMiesPathAsString, UpgradeDataFolderLocation.
Referenced by BSP_GetDevice, DAP_CreateDAEphysPanel, GetAllDevices, GetDeviceMapping, GetITCDeviceList, GetLockedDevices, GetNIDeviceList, GetRepeatedAcquisitionDuration, GetRepeatedAcquisitionFuncList, GetRepeatedAcquisitionStart, GetRunningSingleDevice, IH_KillTemporaries.
string GetDAQDevicesFolderAsString()
Return a data folder reference to the DAQ devices folder.
References GetMiesPathAsString.
Referenced by AB_ReExport, GetActiveDAQDevicesFolderAS, GetActiveDAQDevicesTestPulseFolderAsString, GetAllDevices, GetDAQDevicesFolder, GetDeviceInfoPathAsString, GetDeviceTypePathAsString, GetDistDAQFolderAS.
dfref GetActiveDAQDevicesTimerFolder()
Return the active DAQ devices timer folder "root:mies:HardwareDevices:ActiveDAQDevices:Timer".
References createDFWithAllParents, GetActiveDAQDevicesTimerAS.
Referenced by DAP_UnlockDevice, DQ_StartDAQDeviceTimer, DQ_StopDAQDeviceTimer, DQM_MakeOrUpdateTimerParamWave, DQM_MakeOrUpdtDevTimerTxtWv, DQM_StopBackgroundTimer, DQM_Timer, IsDeviceActiveWithBGTask.
string GetActiveDAQDevicesTimerAS()
Return a data folder reference to the active DAQ devices timer folder.
References GetActiveDAQDevicesFolderAS.
Referenced by GetActiveDAQDevicesTimerFolder.
dfref GetActiveDAQDevicesFolder()
Return the active DAQ devices folder "root:mies:HardwareDevices:ActiveDAQDevices".
References createDFWithAllParents, GetActiveDAQDevicesFolderAS.
Referenced by DAP_UnlockDevice, GetDQMActiveDeviceList.
string GetActiveDAQDevicesFolderAS()
Return a data folder reference to the active DAQ devices folder.
References GetDAQDevicesFolderAsString.
Referenced by GetActiveDAQDevicesFolder, GetActiveDAQDevicesTimerAS.
dfref GetDeviceTypePath(string deviceType)
Return a datafolder reference to the device type folder.
References createDFWithAllParents, GetDeviceTypePathAsString.
string GetDeviceTypePathAsString(string deviceType)
Return the path to the device type folder, e.g. root:mies:HardwareDevices:ITC1600.
References GetDAQDevicesFolderAsString.
Referenced by GetDevicePathAsString, GetDeviceTypePath, GetPopupMenuDeviceListWithData.
dfref GetDevicePath(string device)
Return a datafolder reference to the device folder.
References createDFWithAllParents, GetDevicePathAsString.
Referenced by DAP_UnlockDevice, DB_SetUserData, DC_CalculateChannelColumnNo, GetAcquisitionState, GetActiveSetCount, GetADChannelToMonitor, GetAnalysisFuncDAScaleDeltaI, GetAnalysisFuncDAScaleDeltaV, GetAnalysisFuncDAScaleFreqFit, GetAnalysisFuncDAScaleRes, GetAnalysisFuncDAScaleResFit, GetAnalysisFuncDAScales, GetAnalysisFuncDAScaleSpikeFreq, GetAnalysisFuncErrorCounter, GetAnalysisFuncIndexingHelper, GetAnalysisFunctionStorage, GetCellElectrodeNames, GetChanAmpAssign, GetChanAmpAssignUnit, GetChannelClampMode, GetCount, GetDA_EphysGuiStateNum, GetDA_EphysGuiStateTxT, GetDAQConfigWave, GetDAQDataWave, GetDAQDeviceID, GetDataAcqRunMode, GetEpochsWave, GetFifoPosition, GetFollowerList, GetHSProperties, GetIndexingStorageWave, GetMaxIntertrialInterval, GetNI_ADCTaskID, GetNI_AISetup, GetNI_DACTaskID, GetNI_TTLTaskID, GetNIDAQChannelWave, GetOscilloscopeWave, GetRAPerfWave, GetRepeatedAcquisitionCycleID, GetRepurposedSweepTime, GetRNGSeed, GetScaledDataWave, GetSetEventFlag, GetStimsetAcqIDHelperWave, GetStopCollectionPoint, GetThreadGroupIDFIFO, GetTPOscilloscopeWave, GetTTLWave, GetUserComment, SaveExperimentSpecial.
string GetDeviceInfoPathAsString()
Return the path to the device info folder, e.g. root:mies:HardwareDevices:DeviceInfo.
References GetDAQDevicesFolderAsString.
Referenced by GetDeviceInfoPath.
dfref GetDeviceInfoPath()
Return a datafolder reference to the device info folder.
References createDFWithAllParents, GetDeviceInfoPathAsString.
Referenced by GetDeviceInfoWave.
string GetDevicePathAsString(string device)
Return the path to the device folder, e.g. root:mies:HardwareDevices:ITC1600:Device0.
References ASSERT_TS, GetDeviceTypePathAsString, GetHardwareType, HARDWARE_ITC_DAC, HARDWARE_NI_DAC, ParseDeviceString.
Referenced by AB_LoadUserCommentFromFile, DAP_GUIListOfYokedDevices, DAP_UnlockDevice, DAP_UpdateDataFolderDisplay, GetAllDevices, GetDeviceDataPathAsString, GetDevicePath, GetDeviceTestPulseAsString, GetPopupMenuDeviceListWithData.
dfref GetDeviceDataPath(string device)
Return a datafolder reference to the device data folder.
References createDFWithAllParents, GetDeviceDataPathAsString.
Referenced by AB_ReExport, AFH_GetLastSweepAcquired, AppendEntries, BSP_ButtonProc_RestoreData, BSP_UpdateSweepNote, DB_AddSweepToGraph, DB_GetPlainSweepList, DB_SplitSweepsIfReq, DB_UpdateSweepPlot, GetSweepWave, NWB_ExportAllData, NWB_FirstStartTimeOfAllSweeps, SWS_DeleteDataWaves, SWS_SaveAcquiredData.
string GetDeviceDataPathAsString(string device)
Return the path to the device folder, e.g. root:mies:HardwareDevices:ITC1600:Device0:Data.
References GetDevicePathAsString.
Referenced by AB_LoadSweepConfigData, AB_LoadSweepFromIgor, AB_ReExport, GetAllDevicesWithContent, GetDeviceDataPath, SaveExperimentSpecial, SWS_DeleteDataWaves.
dfref GetMiesPath()
Returns a data folder reference to the mies base folder.
References createDFWithAllParents, GetMiesPathAsString.
Referenced by GetBugCount, GetInteractiveMode, GetMiesVersion, GetPopupExtMenuWave, GetPxPVersion, GetSettingsJSONid, GetUniqueTempPath, GetValidAcqStateTransitions, IH_KillTemporaries.
string GetMiesPathAsString()
Returns the base folder for all MIES functionality, e.g. root:MIES UTF_NOINSTRUMENTATION.
Referenced by AB_HasCompatibleVersion, BeforeExperimentSaveHook, GetAmplifierFolderAsString, GetAnalysisFolderAS, GetCacheFolderAS, GetDAQDevicesFolder, GetDAQDevicesFolderAsString, GetDebugPanelFolderAS, GetGraphUserDataFolderAsString, GetLabNotebookFolderAsString, GetManipulatorPathAsString, GetMiesPath, GetNWBFolderAS, GetResultsFolderAsString, GetStaticDataFolderAS, GetSweepFormulaPathAsString, GetTempPath, GetWaveBuilderPathAsString, IH_Cleanup, P_GetDevicePressureFolderAS, P_GetPressureFolderAS.
dfref GetSweepFormulaPath()
Returns a data folder reference to the sweep formula folder.
References createDFWithAllParents, GetSweepFormulaPathAsString.
Referenced by GetSweepFormulaParseErrorMessage.
string GetSweepFormulaPathAsString()
Returns the temporary folder for Sweep formula, e.g. root:MIES:SweepFormula.
References GetMiesPathAsString.
Referenced by GetSweepFormulaPath.
string GetManipulatorPathAsString()
Retuns data folder path to the manipulator folder, e.g. root:mies:manipulators.
References GetMiesPathAsString.
Referenced by GetManipulatorPath.
dfref GetManipulatorPath()
Return a data folder reference for the Manipulator folder.
References createDFWithAllParents, GetManipulatorPathAsString.
dfref GetSingleSweepFolder(dfref dfr, variable sweepNo)
Return a datafolder reference to a subfolder below dfr for splitted sweep specific data, e.g. dfr:X_5.
References createDFWithAllParents, GetSingleSweepFolderAsString.
Referenced by AR_UpdateTracesIfReq, BSP_ButtonProc_RestoreData, CreateTiledChannelGraph, DB_SplitSweepsIfReq, PA_GenerateAllPulseWaves.
string GetSingleSweepFolderAsString(dfref dfr, variable sweepNo)
Return the path to a subfolder below dfr for splitted sweep specific data.
References ASSERT, DataFolderExistsDFR, IsValidSweepNumber.
Referenced by GetAnalysisSweepDataPathAS, GetSingleSweepFolder, RecreateSweepWaveFromBackupAndLBN.
wave GetDAQDataWave(string device, variable mode)
Return the DAQ data wave.
ITC hardware: 2D signed 16bit integer wave, the colums are for the channel NI hardware: Wave reference wave, one referencing each channel Rows: data Columns: one for each active DA, AD, TTL channel (in that order) For scaling and gain information see SWS_GetChannelGains(). Note: TP_PROPERTIES_HASH: Unique hash for a combination of all properties which influence the test pulse. device device mode One of DATA_ACQUISITION_MODE or TEST_PULSE_MODE
References ASSERT, DATA_ACQUISITION_MODE, GetDevicePath, GetHardwareType, HARDWARE_ITC_DAC, HARDWARE_NI_DAC, NUM_DA_TTL_CHANNELS, SetStringInWaveNote, TEST_PULSE_MODE, TP_PROPERTIES_HASH.
Referenced by AFM_CallAnalysisFunctions, DAP_CheckSettings, DC_CheckIfDataWaveHasBorderVals, DC_Configure, DC_FillDAQDataWaveForTP, DC_MakeAndGetDAQDataWave, DC_MakeHelperWaves, DC_WriteTTLIntoDAQDataWave, DQM_FIFOMonitor, MSQ_DeterminePulseDuration, MSQ_SearchForSpikes, PSQ_DeterminePulseDuration, PSQ_GetNumberOfChunks, PSQ_SearchForSpikes, SCOPE_ITC_UpdateOscilloscope, SCOPE_NI_UpdateOscilloscope, SWS_SaveAcquiredData, TPM_BkrdTPFuncMD, UpdateLeftOverSweepTime.
wave GetNIDAQChannelWave(string device, variable channel)
Get the single NI channel waves.
Special use function, normal callers should use GetDAQDataWave() instead.
References GetDevicePath.
Referenced by DC_FillDAQDataWaveForTP, DC_MakeNIChannelWave.
wave GetEpochsWave(string device)
Return the epochs text wave.
Rows: epochs Column numbers must use global column number constants epochColumnNumber. Columns: 0: Start time in sec 1: End time in sec 2: Tags 3: Tree Level Layers: NUM_DA_TTL_CHANNELS Version History Wave 1: Initial version 2: Renamed column Name to Tags Tags format Initial version in a2172f03 (Added generations of epoch information wave, 2019-05-22), parsed in PA plot since 4e534e29 (Pulse Averaging: Pulse starting times are now read from the lab notebook, 2020-10-07). In d150d896 (DC_AddEpochsFromStimSetNote: Add sub sub epoch information, 2021-02-02) tree level 3 info for pulse train pulses was added, which is read out since ba209bbd (PA plot: Gather more pulse infos, 2021-02-02). And in 2371cfb0 (Epochs: Revise naming, 2021-09-22) we changed the naming of the tags and also adapted PA_RetrievePulseStartTimesFromEpochs. For these three formats we have tests in RPI_WorksWithOldData(). When changing the tags format this test needs to be updated.
References EPOCHS_WAVE_VERSION, ExistsWithCorrectLayoutVersion, GetDevicePath, MINIMUM_WAVE_SIZE, NUM_DA_TTL_CHANNELS, SetEpochsDimensionLabels, SetWaveVersion.
Referenced by EP_AdaptEpochInfo, EP_AddEpoch, EP_ClearEpochs, EP_GetEpochCount, EP_SortEpochs, EP_WriteEpochInfoIntoSweepSettings.
variable SetEpochsDimensionLabels(wave wv)
References COLS, EPOCH_COL_ENDTIME, EPOCH_COL_STARTTIME, EPOCH_COL_TAGS, EPOCH_COL_TREELEVEL.
Referenced by GetEpochsWave.
dfref GetEpochsVisualizationFolder(dfref dfr)
Return the folder for the epoch visualization waves below the sweepfolder/databrowser specific folder.
References createDFWithAllParents.
wave GetDAQConfigWave(string device)
Return the DAQ config wave.
Rows: One for each channel, the order is DA, AD, TTL (same as in the DAQDataWave) Columns: channel type, one of XopChannelConstants channel number (0-based) sampling interval in microseconds (1e-6) decimation mode (always zero) data offset The wave note holds a list of channel units. The order is the same as the rows. TTL channels don't have units. Querying the channel unit should always be done via AFH_GetChannelUnit() or AFH_GetChannelUnits(). This wave is also used for NI devices as configuration template. There is one difference though: While for ITC devices there is one TTL row for each rack, for NI devices there is one TTL row for each channel (up to 8 currently) The channel number column holds the hardware channel number for the NI device Currently the sampling interval is read from channel 0 only and used for all channels ITC hardware: The number of TTL bits which are stored in each TTL channel is hardware dependent and can be queried with HW_ITC_GetRackRange(). Version 1 changes: Columns now have dimension labels One more column with the channel data offset Due to the wave versioning the channel unit is now stored with the CHANNEL_UNIT_KEY as key and it is now separated not with semicolon anymore but a comma. Version 2 changes: DAQChannelType column added
References AddEntryIntoWaveNoteAsList, CHANNEL_UNIT_KEY, COLS, DAQ_CHANNEL_TYPE_DAQ, DAQ_CONFIG_WAVE_VERSION, ExistsWithCorrectLayoutVersion, GetDevicePath, SetWaveVersion, WaveVersionIsSmaller.
Referenced by DC_Configure, DC_FillDAQDataWaveForDAQ, DC_FillSetEventFlag, DC_GetChannelTypefromHS, DC_GetConfiguration, DC_GetStopCollectionPoint, DC_MakeAndGetDAQDataWave, DC_MakeDAQConfigWave, DC_MakeHelperWaves, DC_PlaceDataInDAQConfigWave, DC_PrepareLBNEntries, DC_WriteTTLIntoDAQDataWave, EP_CollectEpochInfo, GotTPChannelsOnADCs, MSQ_DeterminePulseDuration, MSQ_SearchForSpikes, PSQ_CR_DetermineBoundsAction, PSQ_CR_DetermineCycles, PSQ_DeterminePulseDuration, PSQ_EvaluateBaselineProperties, PSQ_Ramp, PSQ_SearchForSpikes, RecreateConfigWaveFromLBN, SCOPE_CreateGraph, SCOPE_ITC_AdjustFIFOPos, SCOPE_ITC_UpdateOscilloscope, SCOPE_SetADAxisLabel, SCOPE_UpdateGraph, SCOPE_UpdateOscilloscopeData, SWS_GetChannelGains, SWS_SaveAcquiredData, TFH_StartFIFODeamonInternal.
wave GetDQMActiveDeviceList()
Returns a reference to the wave of active devices for data acquisition in multi device mode.
The wave is used in data acquisition in multiple device mode to keep track of active devices. Columns: DeviceID id of an active device ADChannelToMonitor index of first active AD channel in DAQDataWave HardwareType type of hardware of the device ActiveChunk if a channel of the device is used for TP while DAQ this column saves the number of the last evaluated test pulse Version changes: 1: Added column activeChunk 2: Changed precision to double 3: Removed column 2 with StopCollectionPoint as it is no longer used
References COLS, DeleteWavePoint, DQM_ACTIVE_DEV_WAVE_VERSION, ExistsWithCorrectLayoutVersion, GetActiveDAQDevicesFolder, SetWaveVersion, WaveVersionIsSmaller.
Referenced by DAP_LockDevice, DQM_AddDevice, DQM_FIFOMonitor, DQM_GetActiveDeviceRow, DQM_RemoveDevice, DQM_TerminateOngoingDAQHelper, IsDeviceActiveWithBGTask, RA_AreLeaderAndFollowerFinished.
wave GetTTLWave(string device)
Return the intermediate storage wave for the TTL data.
References GetDevicePath, GetHardwareType, HARDWARE_ITC_DAC, HARDWARE_NI_DAC, NUM_DA_TTL_CHANNELS.
Referenced by DC_ITC_MakeTTLWave, DC_NI_MakeTTLWave, DC_WriteTTLIntoDAQDataWave.
wave GetStimsetAcqIDHelperWave(string device)
Return the stimset acquistion cycle ID helper wave.
Only valid during DAQ. Rows: NUM_DA_TTL_CHANNELS Columns: 0: Stimset fingerprint of the previous sweep 1: Current stimset acquisition cycle ID
References COLS, GetDevicePath, NUM_DA_TTL_CHANNELS.
Referenced by DAP_OneTimeCallBeforeDAQ, DC_GetStimsetAcqCycleID.
wave GetIVSCCTemporaryWave(string device)
Returns a wave reference to the temporary wave for IVSCC.
Rows: 0: tpBuffer, used to hold previous tp settings. Setting will be restored upon completion of qc function.
References GetDevSpecLabNBTempFolder.
Referenced by IVS_finishInitAccessQCCheck, IVS_runInitAccessResisQC.
dfref GetDevSpecLabNBTempFolder(string device)
Return the data folder reference to the device specific lab notebook folder for temporary waves.
References createDFWithAllParents, GetDevSpecLabNBTempFolderAS.
Referenced by GetIVSCCTemporaryWave, GetSweepSettingsKeyWave, GetSweepSettingsTextKeyWave, GetSweepSettingsTextWave, GetSweepSettingsWave, GetTPSettingsLabnotebook, GetTPSettingsLabnotebookKeyWave.
string GetDevSpecLabNBTempFolderAS(string device)
Return the full path to the device specific lab notebook temp folder, e.g. root:MIES:LabNoteBook:ITC18USB:Device0:Temp.
References GetDevSpecLabNBFolderAsString.
Referenced by GetDevSpecLabNBTempFolder.
string GetResultsFolderAsString()
Return the full path to the results folder, e.g. root:MIES:Results.
References GetMiesPathAsString.
Referenced by AB_LoadResultsFromIgor, GetResultsFolder.
dfref GetResultsFolder()
Return the data folder reference to the results folder.
References createDFWithAllParents, GetResultsFolderAsString.
Referenced by GetNumericalResultsKeys, GetNumericalResultsValues, GetTextualResultsKeys, GetTextualResultsValues.
wave GetIndexingStorageWave(string device)
Return the indexing storage wave.
Rows: 0: DA (CHANNEL_TYPE_DAC) 1: TTL (CHANNEL_TYPE_TTL) Columns: 0: Popup menu index of Wave (stimset) 1: Popup menu index of Indexing end wave (stimset) All zero-based as returned by GetPopupMenuIndex(). Layers: Channels
References CHANNEL_CONTROL_INDEX_END, CHANNEL_CONTROL_WAVE, CHANNEL_TYPE_DAC, CHANNEL_TYPE_TTL, COLS, ExistsWithCorrectLayoutVersion, GetDevicePath, NUM_DA_TTL_CHANNELS, ROWS, SetWaveVersion.
Referenced by IDX_DetIfCountIsAtSetBorder, IDX_IndexSingleChannel, IDX_ResetStartFinishForIndexing, IDX_StoreStartFinishForIndexing, IDX_TotalIndexingListSteps, IDX_UnlockedIndexingStepNo.
dfref GetTempPath()
Return the temporary folder below the MIES hierarchy, e.g. root:mies:trash.
References createDFWithAllParents, GetMiesPathAsString, TRASH_FOLDER_PREFIX.
Referenced by GetElapsedTimeWave, GetTemporaryString, GetTemporaryVar.
dfref GetUniqueTempPath()
Return a unique temporary folder below the MIES hierarchy, e.g. root:mies:trash_$digit.
As soon as you discard the latest reference to the folder it will be slated for removal at some point in the future.
References GetMiesPath, TRASH_FOLDER_PREFIX, UniqueDataFolder.
Referenced by MoveToTrash, OOD_Debugging, ReachTargetVoltage, StoreWaveOnDisk.
dfref GetStaticDataFolder()
Return the datafolder reference to the static data location, e.g. root:mies:StaticData:
References createDFWithAllParents, GetStaticDataFolderAS.
Referenced by GetLBNumericalDescription, LoadWaveFromDisk, SaveLBNumericalDescription, SI_GetMinSampIntWave.
string GetStaticDataFolderAS()
Return the full path to the static data location.
References GetMiesPathAsString.
Referenced by GetStaticDataFolder.
dfref GetActDAQDevicesTestPulseFolder()
Return the datafolder reference to the active DAQ devices folder, e.g. root:MIES:HardwareDevices:ActiveDAQDevices:TestPulse.
References createDFWithAllParents, GetActiveDAQDevicesTestPulseFolderAsString.
Referenced by GetActiveDevicesTPMD.
string GetActiveDAQDevicesTestPulseFolderAsString()
Return the full path to the active DAQ devices location for the test pulse.
References GetDAQDevicesFolderAsString.
Referenced by GetActDAQDevicesTestPulseFolder.
wave GetActiveDevicesTPMD()
Return the active devices wave for TP MD.
Rows: Devices taking part in TP MD Columns: 0: DeviceID 1: ActiveChunk The $NOTE_INDEX wave note entry holds the number of active devices. In addition it is also the next free row index.
References COLS, ExistsWithCorrectLayoutVersion, GetActDAQDevicesTestPulseFolder, MINIMUM_WAVE_SIZE, NOTE_INDEX, SetNumberInWaveNote, SetWaveVersion.
Referenced by DAP_UnlockDevice, IsDeviceActiveWithBGTask, TPM_AddDevice, TPM_BkrdTPFuncMD, TPM_HasActiveDevices, TPM_RemoveDevice.
wave GetDA_EphysGuiStateNum(string device)
Returns wave (DA_EphysGuiState) that stores the DA_Ephys GUI state DA_EphysGuiState is stored in the device specific folder e.g. root:MIES:HardwareDevices:ITC18USB:Device0.
Rows: Column specific GUI control settings usually associated with control name number Columns: 0: State of control Check_DataAcqHS_RowNum. 0 = UnChecked, 1 = Checked 1: Clamp mode of HS number that matches Row number. 0 = VC, 1 = IC, 2 = NC. 2: State of control Check_DA_RowNum. 0 = UnChecked, 1 = Checked 3: Internal number stored in control Gain_DA_RowNum. Gain is user/hardware defined. 4: Internal number stored in setvar:Scale_DA_RowNum. Scalar is user defined. 5: PopupMenu Index of popupMenu:Wave_DA_RowNum. Stores index of active DA stimulus set during data acquisition. Stores index of next DA stimulus set when data acquistion is not active. 6: PopupMenu Index of popupMenu:IndexEnd_DA_RowNum. Stores the index of the last DA stimulus set used in indexed aquisition mode. 7: State of checkbox control Check_AD_RowNum. 0 = UnChecked, 1 = Checked 8: Internal number stored in Gain_AD_RowNum. Gain is user/hardware defined. 9: State of checkbox control Check_TTL_RowNum. 0 = UnChecked, 1 = Checked 10: PopupMenu Index of popupMenu:Wave_TTL_RowNum. Stores index of active TTL stimulus set during data acquisition. Stores index of next TTL stimulus set when data acquistion is not active. 11: PopupMenu Index of popupMenu:IndexEnd_TTL_RowNum. Stores the index of the last TTL stimulus set used in indexed aquisition mode. 12: State of control Check_AsyncAD_RowNum. 0 = UnChecked, 1 = Checked 13: Internal number stored in control SetVar_AsyncAD_Gain_RowNum. Gain is user/hardware defined. 14: State of control check_AsyncAlarm_RowNum. 0 = UnChecked, 1 = Checked 15: Internal number stored in control min_AsyncAD__RowNum. The minium value alarm trigger. 16: Internal number stored in control max_AsyncAD_RowNum. The max value alarm trigger. 17+: Unique controls
References CHANNEL_CONTROL_ALARM_MAX, CHANNEL_CONTROL_ALARM_MIN, CHANNEL_CONTROL_CHECK, CHANNEL_CONTROL_GAIN, CHANNEL_CONTROL_INDEX_END, CHANNEL_CONTROL_SCALE, CHANNEL_CONTROL_WAVE, CHANNEL_TYPE_ADC, CHANNEL_TYPE_ALARM, CHANNEL_TYPE_ASYNC, CHANNEL_TYPE_DAC, CHANNEL_TYPE_HEADSTAGE, CHANNEL_TYPE_TTL, COLS, COMMON_CONTROL_GROUP_COUNT_NUM, DA_EPHYS_PANEL_VERSION, DAG_GetUniqueSpecCtrlListNum, DAG_RecordGuiStateNum, ExistsWithCorrectLayoutVersion, GetDevicePath, NUM_MAX_CHANNELS, SetDimensionLabels, SetWaveVersion.
Referenced by DAG_GetActiveHeadstages, DAG_GetChannelState, DAG_GetHeadstageMode, DAG_GetHeadstageState, DAG_GetNumericalValue, DAG_RecordGuiStateNum, DAG_Update, DAP_ApplyClmpModeSavdSettngs, DAP_ApplyDelayedClampModeChange, DAP_ChangeHeadStageMode, DAP_ChangeHeadstageState, DAP_CheckProc_ClampMode, DAP_ClearDelayedClampModeChange, DAP_GetskipAhead, DAP_LockDevice, DAP_RemoveClampModeSettings, DAP_ResetskipAhead, DAP_UnlockDevice, P_SetLEDValueAssoc, SWS_GetChannelGains.
wave GetDA_EphysGuiStateTxT(string device)
Return a wave reference to the textual GUI state wave.
Rows: Column specific GUI control settings usually associated with control name number Columns: 0: (DA) First stimset name 1: (DA) Last stimset name 2: (DA) Unit 3: (DA) Search string 4: (AD) Unit 5: (TTL) First stimset name 6: (TTL) Last stimset name 7: (TTL) Search string 8: (Async) Title 9: (Async) Unit 10+: Unique controls (SetVariable and PopupMenu only)
References CHANNEL_CONTROL_INDEX_END, CHANNEL_CONTROL_SEARCH, CHANNEL_CONTROL_TITLE, CHANNEL_CONTROL_UNIT, CHANNEL_CONTROL_WAVE, CHANNEL_TYPE_ADC, CHANNEL_TYPE_ASYNC, CHANNEL_TYPE_DAC, CHANNEL_TYPE_TTL, COLS, COMMON_CONTROL_GROUP_COUNT_TXT, DA_EPHYS_PANEL_VERSION, DAG_RecordGuiStateTxT, ExistsWithCorrectLayoutVersion, GetDevicePath, NUM_MAX_CHANNELS, SetDimensionLabels, SetWaveVersion.
Referenced by DAG_GetChannelTextual, DAG_GetTextualValue, DAG_RecordGuiStateTxT, DAG_Update, DAP_ApplyClmpModeSavdSettngs, DAP_LockDevice, DAP_UnlockDevice.
dfref GetNWBFolder()
Return the datafolder reference to the NeuroDataWithoutBorders folder, e.g. root:MIES:NWB.
References createDFWithAllParents, GetNWBFolderAS.
Referenced by GetNWBFileIDExport, GetNWBFilePathExport, GetSessionStartTime, GetSessionStartTimeReadBack, IH_Cleanup.
string GetNWBFolderAS()
Return the full path to the NeuroDataWithoutBorders folder.
References GetMiesPathAsString.
Referenced by AB_ReExport, GetNWBFolder.
wave GetDeviceMapping()
Return a wave mapping the deviceIDs (numeric) to the device name(NI HW only) and user visible device name.
Rows: DeviceIDs, supports 32 as the ITC XOP does COLS: One column for each supported HW type LAYERS: 0: Main device (aka device of a DA_Ephys panel), used for deriving datafolders for storage 1: Name of the device used for pressure control (maybe empty)
References COLS, ExistsWithCorrectLayoutVersion, GetDAQDevicesFolder, HARDWARE_DAC_TYPES, HARDWARE_MAX_DEVICES, LAYERS, ROWS, SetWaveVersion.
Referenced by DAP_UnlockDevice, HW_DeRegisterDevice, HW_GetDeviceName, HW_GetMainDeviceName, HW_RegisterDevice.
dfref GetDistDAQFolder()
Return the datafolder reference to the oodDAQ folder.
References createDFWithAllParents, GetDistDAQFolderAS.
Referenced by GetDistDAQPreloadWave, OOD_CalculateOffsetsYoked, OOD_LoadPreload.
string GetDistDAQFolderAS()
Return the full path to the optimized overlap distributed acquisition (oodDAQ) folder, e.g. root:MIES:HardwareDevices:oodDAQ.
References GetDAQDevicesFolderAsString.
Referenced by GetDistDAQFolder.
wave GetDistDAQPreloadWave(string device)
Return the wave used for storing preloadable data.
Required for yoked oodDAQ only.
References GetDistDAQFolder.
Referenced by OOD_LoadPreload, OOD_StorePreload.
wave GetCellElectrodeNames(string device)
Returns the names of the electrodes.
The electrodes represents the physically connected part to the cell whereas the headstage refers to the logical entity inside MIES. Will be written into the labnotebook and used for the NWB export.
References ExistsWithCorrectLayoutVersion, GetDefaultElectrodeName, GetDevicePath, NUM_HEADSTAGES, SetWaveVersion.
Referenced by DC_PrepareLBNEntries.
wave GetPressureTypeWv(string device)
Returns a 1D wave with the same number of rows as headstages used to store the pressure type.
Available pressure types are one of PressureTypeConstants ROWS: One row for each headstage P_UpdatePressureType
References NUM_HEADSTAGES, P_DeviceSpecificPressureDFRef.
Referenced by P_RecordUserPressure, P_SetLEDValueAssoc, P_UpdatePressureType.
dfref GetDevicePulseAverageFolder(dfref dfr)
Return the pulse averaging folder.
References createDFWithAllParents, GetDevicePulseAverageFolderAS.
Referenced by PA_GenerateAllPulseWaves, PA_InitPASIInParts.
string GetDevicePulseAverageFolderAS(dfref dfr)
Return the full path to the pulse averaging folder, e.g. dfr:PulseAveraging.
Referenced by GetDevicePulseAverageFolder, GetDevicePulseAverageHelperFolderAS.
dfref GetDevicePulseAverageHelperFolder(dfref dfr)
Return the pulse averaging helper folder.
This holds various helper waves for the graph generation.
References createDFWithAllParents, GetDevicePulseAverageHelperFolderAS.
Referenced by PA_GenerateAllPulseWaves, PA_InitPASIInParts, PA_PreProcessPulses, SC_GetPulseAveragePropertiesWaves.
string GetDevicePulseAverageHelperFolderAS(dfref dfr)
Return the full path to the pulse averaging helper folder, e.g. dfr:Helper.
References GetDevicePulseAverageFolderAS.
Referenced by GetDevicePulseAverageHelperFolder.
wave GetPulseAverageWave(dfref dfr, variable length, variable channelType, variable channelNumber, variable region, variable pulseIndex)
Return a wave reference to the single pulse defined by the given parameters.
dfr datafolder reference where to create the empty wave if it does not exist length Length in points of the new wave channelType channel type, one of XopChannelConstants channelNumber channel number region region index (a region is the range with data in a dDAQ/oodDAQ measurement) pulseIndex pulse number, 0-based
References ASSERT, DataFolderExistsDFR, ExistsWithCorrectLayoutVersion, PA_GeneratePulseWaveName, PULSE_WAVE_VERSION, SetWaveVersion.
Referenced by PA_CreateAndFillPulseWaveIfReq.
wave GetPulseAverageWaveNoteWave(dfref dfr, variable length, variable channelType, variable channelNumber, variable region, variable pulseIndex)
Return a wave reference to the single pulse defined by the given parameters.
dfr datafolder reference where to create the empty wave if it does not exist length Length in points of the new wave channelType channel type, one of XopChannelConstants channelNumber channel number region region index (a region is the range with data in a dDAQ/oodDAQ measurement) pulseIndex pulse number, 0-based
References ASSERT, DataFolderExistsDFR, ExistsWithCorrectLayoutVersion, PA_GeneratePulseWaveName, PULSE_WAVE_VERSION, PULSEWAVE_NOTE_SUFFIX, SetWaveVersion.
Referenced by PA_CreateAndFillPulseWaveIfReq.
wave GetPulseAverageSetIndizes(dfref dfr, variable channelNumber, variable region)
Returns the pulse average set properties wave.
These are row indizes into GetPulseAverageProperties()/GetPulseAveragePropertiesWaves() for the pulses which belong to the given set.
References ASSERT, COLS, DataFolderExistsDFR, ExistsWithCorrectLayoutVersion, MINIMUM_WAVE_SIZE, NOTE_INDEX, NOTE_KEY_PULSE_SORT_ORDER, SetNumberInWaveNote, SetWaveVersion.
Referenced by PA_GenerateAllPulseWaves, PA_GetSetIndicesHelper, PA_GetSetWaves.
wave GetPulseAverageSetImageWave(dfref dfr, variable channelNumber, variable region)
Returns the pulse average image wave.
This is used for the image display mode. NOTE_INDEX is used for marking the length of the used columns as there is one pulse per column.
References ASSERT, DataFolderExistsDFR, ExistsWithCorrectLayoutVersion, MINIMUM_WAVE_SIZE, NOTE_INDEX, SetNumberInWaveNote, SetWaveVersion.
Referenced by PA_AddColorScales, PA_ShowImage.
wave GetPulseAverageProperties(dfref dfr)
Return the pulse average properties wave.
It is filled by PA_GenerateAllPulseWaves() and consumed by others.
References ASSERT, COLS, DataFolderExistsDFR, ExistsWithCorrectLayoutVersion, MINIMUM_WAVE_SIZE_LARGE, NOTE_INDEX, PA_PROPERTIES_INDEX_CHANNELNUMBER, PA_PROPERTIES_INDEX_CLAMPMODE, PA_PROPERTIES_INDEX_HEADSTAGE, PA_PROPERTIES_INDEX_LASTSWEEP, PA_PROPERTIES_INDEX_PULSE, PA_PROPERTIES_INDEX_PULSEHASFAILED, PA_PROPERTIES_INDEX_REGION, PA_PROPERTIES_INDEX_SWEEP, SetNumberInWaveNote, SetWaveVersion.
Referenced by PA_GenerateAllPulseWaves, PA_GetSetIndicesHelper, PA_GetSetWaves, PA_InitPASIInParts, SC_GetPulseAveragePropertiesWaves.
wave GetPulseAveragePropertiesWaves(dfref dfr)
Return the pulse average properties wave with wave references.
Belongs to GetPulseAverageProperties() and also has the same NOTE_INDEX count stored there.
References ASSERT, COLS, DataFolderExistsDFR, ExistsWithCorrectLayoutVersion, MINIMUM_WAVE_SIZE_LARGE, PA_PROPERTIESWAVES_INDEX_PULSE, PA_PROPERTIESWAVES_INDEX_PULSENOTE, SetWaveVersion.
Referenced by PA_GenerateAllPulseWaves, PA_GetSetWaves, PA_InitPASIInParts, SC_GetPulseAveragePropertiesWaves.
wave GetPulseAverageDisplayMapping(dfref dfr)
Return the mapping wave for pulse averaging between region/channel to activeRegion/activeChannel.
Belongs to GetPulseAverageProperties() and also has the same NOTE_INDEX count stored there.
References ASSERT, DataFolderExistsDFR, ExistsWithCorrectLayoutVersion, LAYERS, NUM_HEADSTAGES, NUM_MAX_CHANNELS, SetWaveVersion.
Referenced by PA_GenerateAllPulseWaves.
wave GetArtefactRemovalListWave(dfref dfr)
Return the artefact removal listbox wave for the databrowser or the sweepbrowser.
References ASSERT, COLS, DataFolderExistsDFR, ExistsWithCorrectLayoutVersion, MINIMUM_WAVE_SIZE, SetWaveVersion.
Referenced by AR_HandleRanges, AR_HighlightArtefactsEntry, AR_UpdateListBoxWave, AR_UpdatePanel, BSP_BindListBoxWaves.
wave GetArtefactRemovalDataWave(dfref dfr)
Return the artefact removal wave databrowser or the sweepbrowser.
References ASSERT, COLS, DataFolderExistsDFR, ExistsWithCorrectLayoutVersion, MINIMUM_WAVE_SIZE, SetWaveVersion.
Referenced by AR_HandleRanges, AR_HighlightArtefactsEntry, AR_UpdateListBoxWave, AR_UpdatePanel.
wave GetOverlaySweepsListWave(dfref dfr)
Return the overlay sweeps listbox wave for the databrowser or the sweepbrowser.
References ASSERT, COLS, DataFolderExistsDFR, ExistsWithCorrectLayoutVersion, MINIMUM_WAVE_SIZE, SetWaveVersion.
Referenced by AD_SelectResult, BSP_BindListBoxWaves, OVS_AddToIgnoreList, OVS_BeginIncrementalUpdate, OVS_ChangeSweepSelectionState, OVS_EndIncrementalUpdate, OVS_GetHeadstageRemoval, OVS_GetSelectedSweeps, OVS_GetSweepAndExperiment, OVS_UpdateHeadstageRemoval, OVS_UpdatePanel.
wave GetOverlaySweepsListSelWave(dfref dfr)
Return the overlay sweeps listbox selection wave for the databrowser or the sweepbrowser.
References ASSERT, COLS, DataFolderExistsDFR, ExistsWithCorrectLayoutVersion, MINIMUM_WAVE_SIZE, SetWaveVersion.
Referenced by BSP_BindListBoxWaves, OVS_BeginIncrementalUpdate, OVS_ChangeSweepSelection, OVS_ChangeSweepSelectionState, OVS_CheckBoxProc_HS_Select, OVS_EndIncrementalUpdate, OVS_GetSelectedSweeps, OVS_UpdatePanel.
wave GetOverlaySweepHeadstageRemoval(dfref dfr)
Return the overlay sweeps wave with the parsed headstage removal info.
Rows: Same index as in GetOverlaySweepsListWave() and GetOverlaySweepsListSelWave() Columns: NUM_HEADSTAGES, 1 if active and 0 if removed
References ASSERT, DataFolderExistsDFR, ExistsWithCorrectLayoutVersion, MINIMUM_WAVE_SIZE, NUM_HEADSTAGES, SetWaveVersion.
Referenced by OVS_GetHeadstageRemoval, OVS_UpdateHeadstageRemoval, OVS_UpdatePanel.
wave GetOverlaySweepSelectionChoices(string win, dfref dfr, variable skipUpdate=defaultValue)
Return the overlay sweeps wave with all sweep selection choices for the databrowser or the sweepbrowser.
References ASSERT, DataFolderExistsDFR, WaveLocationMod::dfr, ExistsWithCorrectLayoutVersion, LAYERS, MINIMUM_WAVE_SIZE, NOTE_NEEDS_UPDATE, NUM_DA_TTL_CHANNELS, NUM_HEADSTAGES, OVS_UpdateSweepSelectionChoices, SetDimensionLabels, SetNumberInWaveNote, SetWaveVersion, UpgradeWaveLocationAndGetIt.
Referenced by OVS_ChangeSweepSelection, OVS_GetSweepSelectionChoices, OVS_UpdatePanel.
wave GetChannelSelectionWave(dfref dfr)
Return the channel selection wave for the databrowser or sweep browser.
References ASSERT, COLS, DataFolderExistsDFR, ExistsWithCorrectLayoutVersion, NUM_AD_CHANNELS, NUM_DA_TTL_CHANNELS, NUM_HEADSTAGES, SetWaveVersion.
Referenced by BSP_GetChannelSelectionWave.
wave GetAxisLabelCacheWave()
Return a free wave used for the axis label cache.
References COLS, MINIMUM_WAVE_SIZE, NOTE_INDEX, SetNumberInWaveNote.
Referenced by DB_AddSweepToGraph, DB_UpdateSweepPlot, SB_AddSweepToGraph, SB_UpdateSweepPlot.
wave GetSweepBrowserMap(dfref dfr)
Return the sweepBrowser map wave from the given DFR.
References ASSERT, COLS, DataFolderExistsDFR, ExistsWithCorrectLayoutVersion, MINIMUM_WAVE_SIZE, NOTE_INDEX, SetNumberInWaveNote, WAVE_NOTE_LAYOUT_KEY.
Referenced by BSP_ButtonProc_RestoreData, BSP_UpdateSweepNote, OVS_GetSweepAndExperiment, SB_AddToSweepBrowser, SB_GetSweepBrowserMapFromGraph, SB_GetSweepDataPathFromIndex, SB_OpenSweepBrowser, SB_UpdateSweepPlot, WB_OpenStimulusSetInWaveBuilder.
wave GetAnalysisFunctionStorage(string device)
Return the storage wave for the analysis functions.
Only contains valid functions. An analysis function is valid if it has a compatible signature and can be found within the locations searched by AFH_GetAnalysisFunctions(). Rows: Head stage number Columns: 0-TOTAL_NUM_EVENTS - 1: Analysis functions ANALYSIS_FUNCTION_PARAMS: Analysis function params (only for V3 generic functions)
References ExistsWithCorrectLayoutVersion, GetDevicePath, NUM_HEADSTAGES, SetWaveVersion, TOTAL_NUM_EVENTS.
Referenced by AFM_CallAnalysisFunctions, AFM_UpdateAnalysisFunctionWave, DC_PrepareLBNEntries.
wave GetSetEventFlag(string device)
Used for storing a true/false state that the pre and/or post set event should be fired after the sweep which is currently prepared in DC_PlaceDataInDAQDataWave().
Rows: NUM_DA_TTL_CHANNELS Columns: PRE_SET_EVENT POST_SET_EVENT
References COLS, ExistsWithCorrectLayoutVersion, GetDevicePath, NUM_DA_TTL_CHANNELS, POST_SET_EVENT, PRE_SET_EVENT, SetWaveVersion.
Referenced by AFM_CallAnalysisFunctions, DAP_OneTimeCallBeforeDAQ, DC_FillSetEventFlag, IDX_IndexingDoIt, MSQ_ForceSetEvent, PSQ_ForceSetEvent.
wave GetRAPerfWave(string device)
Return the wave for storing timestamps for perf testing repeated acquisition.
References ExistsWithCorrectLayoutVersion, GetDevicePath, MINIMUM_WAVE_SIZE, SetWaveVersion.
Referenced by RA_PerfAddMark, RA_PerfFinish, RA_PerfInitialize.
wave WBP_GetAnalysisParamGUIListWave()
Return the list wave for the analysis parameter GUI.
References COLS, ExistsWithCorrectLayoutVersion, GetWaveBuilderDataPath, SetWaveVersion.
Referenced by WBP_ButtonProc_DeleteParam, WBP_LoadSet, WBP_ToggleAnalysisParamGUI, WBP_UpdateParameterWave.
wave WBP_GetAnalysisParamGUISelWave()
Return the selection wave for the analysis parameter GUI.
References ExistsWithCorrectLayoutVersion, GetWaveBuilderDataPath, SetWaveVersion.
Referenced by WBP_ButtonProc_DeleteParam, WBP_ToggleAnalysisParamGUI, WBP_UpdateParameterWave.
wave WBP_GetAnalysisParamGUIHelpWave()
Return the help wave for the analysis parameter GUI.
References COLS, ExistsWithCorrectLayoutVersion, GetWaveBuilderDataPath, SetWaveVersion.
Referenced by WBP_ToggleAnalysisParamGUI, WBP_UpdateParameterWave.
wave GetAnaFuncDashboardListWave(dfref dfr)
Return the analysis function dashboard listbox wave for the databrowser or the sweepbrowser.
References ASSERT, COLS, DataFolderExistsDFR, ExistsWithCorrectLayoutVersion, MINIMUM_WAVE_SIZE, NOTE_INDEX, SetNumberInWaveNote, SetWaveVersion.
Referenced by AD_Update, BSP_BindListBoxWaves.
wave GetAnaFuncDashboardInfoWave(dfref dfr)
Return the analysis function dashboard info wave for the databrowser or the sweepbrowser.
References ASSERT, COLS, DataFolderExistsDFR, ExistsWithCorrectLayoutVersion, MINIMUM_WAVE_SIZE, SetWaveVersion.
Referenced by AD_SelectResult, AD_Update.
wave GetAnaFuncDashboardSelWave(dfref dfr)
Return the analysis function dashboard listbox selection wave for the databrowser or the sweepbrowser.
References ASSERT, DataFolderExistsDFR, ExistsWithCorrectLayoutVersion, LAYERS, MINIMUM_WAVE_SIZE, SetWaveVersion.
wave GetAnaFuncDashboardColorWave(dfref dfr)
Return the analysis function dashboard listbox color wave for the databrowser or the sweepbrowser.
References ASSERT, DataFolderExistsDFR, ExistsWithCorrectLayoutVersion, SetWaveVersion.
Referenced by AD_Update, BSP_BindListBoxWaves.
wave GetAnaFuncDashboardHelpWave(dfref dfr)
Return the analysis function dashboard help wave for the databrowser or the sweepbrowser.
References ASSERT, DataFolderExistsDFR, ExistsWithCorrectLayoutVersion, SetWaveVersion.
Referenced by AD_Update, BSP_BindListBoxWaves.
wave GetDeviceInfoWave(string device)
Return a wave with device information.
References ExistsWithCorrectLayoutVersion, GetDeviceInfoPath, ROWS, SetWaveVersion.
Referenced by DAP_AdaptPanelForDeviceSpecifics, DAP_UpdateDeviceInfoWaves, HW_ITC_GetNumberOfRacks, P_CheckDeviceAndChannelSelection, P_PrepareITCWaves.
wave GetElapsedTimeWave()
Return a wave suitable for storing elapsed time.
Helper function for DEBUGPRINT_ELAPSED_WAVE() and StoreElapsedTime().
References ExistsWithCorrectLayoutVersion, GetTempPath, MINIMUM_WAVE_SIZE, NOTE_INDEX, SetNumberInWaveNote, SetWaveVersion.
Referenced by MeasureMidSweepTiming_V3, StoreElapsedTime.
wave GetSweepFormulaX(dfref dfr, variable graphNr)
Return the X wave for the sweep formula.
wave GetSweepFormulaY(dfref dfr, variable graphNr)
Return the Y wave for the sweep formula.
wave GetPopupExtMenuWave()
Return the global temporary wave for extended popup menu.
References ExistsWithCorrectLayoutVersion, GetMiesPath, SetWaveVersion.
Referenced by PEXT_ButtonProc, PEXT_Callback, PEXT_PopupMenuItems, PEXT_SetDisabledMenu, PEXT_SubMenuName, PEXT_VerifyAndSetMenuWave.
string GetGraphUserDataFolderAsString()
Return the reference to the graph user data datafolder as string.
References GetMiesPathAsString.
Referenced by GetGraphUserDataAsString, GetGraphUserDataFolderDFR.
dfref GetGraphUserDataFolderDFR()
Return the reference to the graph user data datafolder.
References createDFWithAllParents, GetGraphUserDataFolderAsString.
Referenced by GetGraphUserData, GetPAGraphData.
static string BuildGraphName(string graph)
Referenced by GetGraphUserData, GetGraphUserDataAsString.
string GetGraphUserDataAsString(string graph)
Return the path to the text wave for the graph user data as string.
References BuildGraphName, GetGraphUserDataFolderAsString.
Referenced by TUD_GraphIsManaged.
wave GetGraphUserData(string graph)
Return the text wave for the graph user data.
graph existing graph
References BuildGraphName, ExistsWithCorrectLayoutVersion, GetGraphUserDataFolderDFR, MINIMUM_WAVE_SIZE_LARGE, NOTE_INDEX, SetNumberInWaveNote, SetWaveVersion, TUD_INDEX_JSON, TUD_Init.
Referenced by GetNextTraceIndex, GetTraceInfos, LayoutGraph, SBE_GetPulseStartTimesForSel, TUD_ClearImpl, TUD_GetTraceCount, TUD_GetUserData, TUD_GetUserDataAsWave, TUD_RemoveUserData, TUD_SetUserData, TUD_SetUserDataFromWaves, TUD_TraceIsOnGraph.
wave GetPAGraphData()
Return the wave for trace counts per graph for pulse averaging plot rows one per graph, dimlabel is graph name.
Columns: 0: trace names of all average traces 1: trace names of all deconvolution traces 2: list of used image names
References COLS, ExistsWithCorrectLayoutVersion, GetGraphUserDataFolderDFR, SetWaveVersion.
Referenced by PA_GetTraceCountFromGraphData, PA_ShowImage, PA_ShowPulses.
std::tuple< WAVE, string > GetPAPermanentAverageWave(dfref dfr, variable channel, variable region)
Return permanent average wave for PA plot for a given channel/region as well as its base name Returns a null wave if the permanent wave does not exist.
References PA_AVERAGE_WAVE_PREFIX, PA_BaseName.
Referenced by PA_DrawScaleBars, PA_MakeAverageWavePermanent, PA_ShowImage, PA_ShowPulses.
wave GetPulseInfoWave()
Return a free wave for storing timing information of single pulses.
Rows: Pulses Columns: Length: Total length including baseline PulseStart: Start of the pulse (aka begin of active) PulseEnd: End of the pulse (aka end of active)
References COLS.
Referenced by PA_CalculatePulseInfos, PA_RetrievePulseInfosFromEpochs.
wave GetOverrideResults()
Return the wave used for storing mock data for the analysis function tests.
This wave is created by MSQ_CreateOverrideResults(), PSQ_CreateOverrideResults() or TP_CreateOverrideResults() and does also not follow our usual rules so it might not exist.
Referenced by MSQ_CreateOverrideResults, MSQ_SearchForSpikes, PSQ_EvaluateBaselineProperties, PSQ_GetFinalDAScaleFake, PSQ_PipetteInBath, PSQ_SearchForSpikes, SC_GetSpikeNumbersAndPositions, SC_SpontaneousSpikingCheckQC, TestOverrideActive, TP_AutoAmplitudeAndBaseline, TP_AutoBaseline.
wave GetAcqStateTracking()
Return the wave used for storing acquisition state transitions during testing.
References COLS, ExistsWithCorrectLayoutVersion, MINIMUM_WAVE_SIZE, NOTE_INDEX, SetNumberInWaveNote, SetWaveVersion.
Referenced by AS_GenerateEncounteredTransitions, AS_RecordStateTransition.
wave GetValidAcqStateTransitions()
Return a wave with all valid acquisition state transitions.
It is AS_NUM_STATES x AS_NUM_STATES matrix were the old states are in the rows and the new states in the columns. Every valid transition has a 1 in it.
References AS_EARLY_CHECK, AS_INACTIVE, AS_ITI, AS_MID_SWEEP, AS_NUM_STATES, AS_POST_DAQ, AS_POST_SWEEP, AS_PRE_DAQ, AS_PRE_SWEEP, AS_PRE_SWEEP_CONFIG, AS_StateToString, COLS, ExistsWithCorrectLayoutVersion, GetMiesPath, ROWS, SetDimensionLabels, SetWaveVersion.
Referenced by AS_CheckStateTransition, AS_GenerateEncounteredTransitions.
string GetDANDIFolderAsString()
Referenced by GetDANDIFolder.
dfref GetDANDIFolder()
Return the data folder reference to the DANDI folder.
References createDFWithAllParents, GetDANDIFolderAsString.
Referenced by GetDandiDialogWave.
wave GetDandiSetProperties()
Return a free wave with the DANDI set properties.
Rows: one row for each asset Columns: ID created timestamp (ISO8601) modified timestamp (ISO8601) file path of the asset inside the DANDI set
References COLS, SetDimensionLabels.
Referenced by DND_ParseSetReponse.
wave GetDandiDialogWave(wave props)
References COLS, GetDANDIFolder, ROWS, SetDimensionLabels, TextWaveToList.
Referenced by DND_ChooseAsset.
wave GetDACAmplitudes(variable numDACEntries)
Return a free wave with the DAC amplitudes.
Rows: One for each active DAC Columns: DASCALE: DA Scale from the DAEphys GUI TPAMP: Testpulse amplitude (clamp mode dependent)
References COLS.
Referenced by DC_GetConfiguration.
wave GetYvsXFormulas()
Return a free text wave to store single y vs x formula combinations from sweepformula code.
Rows: One for each y vs x formula combination
wave GetYandXFormulas()
Return a free text wave to store y and x formula combinations from sweepformula code.
Rows: One for each formula Columns: FORMULA_X: formula for x wave FORMULA_Y: formula for y wave
References COLS.
wave GetTPSettingsFree()
Free wave version of GetTPSettingsFree()
References LABNOTEBOOK_LAYER_COUNT, NUM_HEADSTAGES, ROWS, SetDimensionLabels, TP_SETTINGS_LABELS.
Referenced by DAP_EphysPanelStartUpSettings, GetTPSettings.
wave GetTPSettings(string device)
Return the testpulse GUI settings.
Rows: Buffer size: Number of elements to average Resistance tolerance: Tolerance for labnotebook change reporting of resistance values, see GetTPResults() Baseline percentage: Fraction which the baseline occupies relative to the total testpulse length, before and after the pulse itself. Pulse duration [ms] Amplitude VC Amplitude IC Auto TP: On/Off (Requires to also call TP_AutoTPGenerateNewCycleID() when writing) Auto TP: Maximum current [pA] Auto TP: Voltage [mV] Auto TP: +/- Voltage [mV] Auto TP: Percentage [%] Auto TP: Interval [s] Auto TP: Cycle ID Columns: LABNOTEBOOK_LAYER_COUNT
References DAP_TPSettingsToWave, ExistsWithCorrectLayoutVersion, GetDeviceTestPulse, GetTPSettingsFree, ROWS, SetDimensionLabels, SetWaveVersion, TP_SETTINGS_LABELS, TP_SETTINGS_WAVE_VERSION.
Referenced by DAP_LockDevice, DAP_TPGUISettingToWave, DAP_TPSettingsToGUI, DC_GetConfiguration, GetTPResultsBuffer, SCOPE_CreateGraph, SCOPE_UpdateOscilloscopeData, TP_AutoAmplitudeAndBaseline, TP_AutoBaseline, TP_AutoDisableIfFinished, TP_AutoTPActive, TP_AutoTPGenerateNewCycleID, TP_PublishAutoTPResult, TP_RecordTP, TP_ROAnalysis, TP_UpdateTPLBNSettings, TP_UpdateTPSettingsCalculated.
wave GetTPSettingsCalculated(string device)
Return the calculated/derived TP settings.
The entries in this wave are only valid during DAQ/TP and are updated via DC_UpdateGlobals().
References ExistsWithCorrectLayoutVersion, GetDeviceTestPulse, ROWS, SetDimensionLabels.
Referenced by DC_GetConfiguration, DC_MakeHelperWaves, DQM_FIFOMonitor, SCOPE_CreateGraph, SCOPE_ITC_UpdateOscilloscope, SCOPE_UpdateOscilloscopeData, TP_UpdateTPLBNSettings, TP_UpdateTPSettingsCalculated.
wave GetTPSettingsLabnotebookKeyWave(string device)
Returns a wave reference to the TP settings key wave.
Rows: 0: Parameter 1: Units 2: Tolerance Factor Columns (all entries headstage dependent except otherwise noted): 0: TP Baseline Fraction (INDEP_HEADSTAGE) 1: TP Amplitude VC 2: TP Amplitude IC 3: TP Pulse Duration (INDEP_HEADSTAGE) 4: TP Auto On/Off 5: TP Auto max current 6: TP Auto voltage 7: TP Auto voltage range 8: TP buffer size (INDEP_HEADSTAGE) 9: Minimum TP resistance for tolerance (INDEP_HEADSTAGE) 10: Send TP settings to all headstages (INDEP_HEADSTAGE) 11: TP Auto percentage (INDEP_HEADSTAGE) 12: TP Auto interval (INDEP_HEADSTAGE) 13: TP Auto QC 14: TP Cycle ID
References ExistsWithCorrectLayoutVersion, GetDevSpecLabNBTempFolder, LABNOTEBOOK_BINARY_UNIT, LABNOTEBOOK_NO_TOLERANCE, TP_AMPLITUDE_IC_ENTRY_KEY, TP_AMPLITUDE_VC_ENTRY_KEY, TP_SETTINGS_WAVE_VERSION.
Referenced by DC_UpdateGlobals, ED_TPSettingsDocumentation, GetTPSettingsLabnotebook.
wave GetTPSettingsLabnotebook(string device)
Get TP settings wave for the labnotebook.
See GetTPSettingsLabnotebookKeyWave() for the dimension label description.
References COLS, ExistsWithCorrectLayoutVersion, GetDevSpecLabNBTempFolder, GetTPSettingsLabnotebookKeyWave, LABNOTEBOOK_LAYER_COUNT, SetSweepSettingsDimLabels, SetWaveVersion, TP_SETTINGS_WAVE_VERSION.
Referenced by DC_UpdateGlobals, ED_TPSettingsDocumentation, TP_AutoTPTurnOff, TP_UpdateTPLBNSettings.