MIES_DataBrowser.ipf
string DB_OpenDataBrowser()
References AddVersionToPanel, BSP_GetPanel, BSP_InitPanel, BSP_SetDataBrowser, DATA_SWEEP_BROWSER_PANEL_VERSION, DB_GetAllDevicesWithData, GetCurrentWindow, GetMainWindow, NONE, PGC_SetAndActivateControl.
Referenced by CONF_RestoreWindow, PSQ_PipetteInBath, SC_SpikeControl.
variable DB_ResetAndStoreCurrentDBPanel()
Utility function to generate new window recreation macro of DataBrowser (also used for SweepBrowser) after GUI editor adapted controls in development process.
References AddVersionToPanel, ASSERT, BSP_GetPanel, BSP_GetSFFormula, BSP_GetSFJSON, BSP_GetSweepControlsPanel, BSP_InitPanel, BSP_UnsetDynamicSettingsHistory, BSP_UnsetDynamicStartupSettingsOfDataBrowser, BSP_UnsetDynamicSweepControlOfDataBrowser, ControlWindowToFront, DATA_SWEEP_BROWSER_PANEL_VERSION, DATABROWSER_WINDOW_TITLE, DB_ClearAllGraphs, DISABLE_CONTROL_BIT, GetCurrentWindow, GetMainWindow, HasPanelLatestVersion, HIDDEN_CONTROL_BIT, LBV_ClearGraph, LBV_GetDescriptionNotebook, LBV_GetSettingsHistoryPanel, NONE, PGC_SetAndActivateControl, ReplaceNotebookText, SearchForInvalidControlProcs, StoreCurrentPanelsResizeInfo, WindowExists.
string DB_GetMainGraph(string win)
References GetMainWindow.
Referenced by DB_ClearAllGraphs, DB_UpdateSweepPlot.
string DB_ClearAllGraphs()
References DB_GetMainGraph, IsEmpty, RemoveFreeAxisFromGraph, RemoveTracesFromGraph, WindowExists.
Referenced by DB_ResetAndStoreCurrentDBPanel, SaveExperimentSpecial.
static string DB_LockToDevice(string win, string device)
References BSP_DynamicSettingsHistory, BSP_DynamicStartupSettings, BSP_FirstAndLastSweepAcquired, BSP_GetPanel, BSP_HasBoundDevice, BSP_UnsetDynamicSettingsHistory, BSP_UnsetDynamicStartupSettingsOfDataBrowser, ControlWindowToFront, DATABROWSER_WINDOW_TITLE, DB_SetUserData, DB_UpdateLastSweepControls, NONE, UpdateSweepPlot.
Referenced by DB_PopMenuProc_LockDBtoDevice.
static variable DB_SetUserData(string win, string device)
References BSP_SetDevice, BSP_SetFolder, GetDevicePath, MIES_BSP_PANEL_FOLDER, NONE, UniqueDataFolder.
Referenced by DB_LockToDevice.
wave DB_GetPlainSweepList(string win)
References BSP_GetDevice, BSP_HasBoundDevice, DATA_SWEEP_REGEXP, ExtractSweepNumber, GetDeviceDataPath, GetListOfObjects, IsEmpty.
Referenced by GetPlainSweepList.
variable DB_UpdateLastSweepControls(string win, variable first, variable last)
References AD_Update, BSP_GetSweepControlsPanel, GetSetVariable, GetValDisplayAsNum, IsFinite, IsNaN, OVS_UpdatePanel, SetSetVariable, SetSetVariableLimits, SetValDisplay, WindowExists.
Referenced by BSP_ButtonProc_ChangeSweep, DB_LockToDevice, DB_UpdateToLastSweep.
variable DB_UpdateSweepPlot(string win)
Update the sweep plotting facility.
Only outside callers are generic external panels which must update the graph. win locked databrowser
References AR_UpdateTracesIfReq, BSP_FetchSelectedChannels, BSP_GatherTiledGraphSettings, BSP_GetDevice, BSP_GetNotebookSubWindow, BSP_GetSweepControlsPanel, BSP_HasBoundDevice, BSP_UpdateSweepNote, CreateTiledChannelGraph, DATA_SWEEP_BROWSER_PANEL_VERSION, DB_GetLBNWave, DB_GetMainGraph, DB_SplitSweepsIfReq, DEBUG_TIMER_START, DEBUGPRINT, DEBUGPRINT_ELAPSED, DoAbortNow, GetAxesRanges, GetAxisLabelCacheWave, GetConfigWave, GetCursorInfos, GetDeviceDataPath, GetExperimentName, GetSetVariable, HasPanelLatestVersion, LBN_NUMERICAL_VALUES, LBN_TEXTUAL_VALUES, OVS_GetSelectedSweeps, OVS_SWEEP_SELECTION_SWEEPNO, POST_PLOT_FULL_UPDATE, PostPlotTransformations, RemoveFreeAxisFromGraph, RemoveTracesFromGraph, RestoreCursors, ROWS, SetAxesRanges, TUD_Clear.
Referenced by UpdateSweepPlot.
wave DB_GetLBNWave(string win, variable type)
Return the labnotebook waves.
The databrowser only knows about one experiment/device at a time so we don't need to specify what we return further. win panel type One of LabnotebookWaveTypes
References BSP_GetDevice, GetLogbookWaves, LBT_LABNOTEBOOK.
Referenced by DB_AddSweepToGraph, DB_SplitSweepsIfReq, DB_UpdateSweepPlot, LBV_UpdateTagsForTextualLBNEntries.
variable DB_UpdateToLastSweep(string win)
References BSP_FirstAndLastSweepAcquired, BSP_GetPanel, BSP_GetSweepControlsPanel, BSP_HasBoundDevice, CHECKBOX_SELECTED, CHECKBOX_UNSELECTED, ControlWindowToFront, DATA_SWEEP_BROWSER_PANEL_VERSION, DB_UpdateLastSweepControls, GetCheckBoxState, HasPanelLatestVersion, LBV_UpdateTagsForTextualLBNEntries, OVS_ChangeSweepSelectionState, OVS_IsActive, SetSetVariable, UpdateSweepPlot.
Referenced by AD_SelectResult, SWS_AfterSweepDataChangeHook.
variable DB_ButtonProc_Panel(WMButtonAction *ba)
procedure for the open button of the side panel
References BSP_ButtonProc_Panel, BSP_UnHideSettingsHistory, GetMainWindow.
variable DB_PopMenuProc_LockDBtoDevice(WMPopupAction *pa)
References DB_LockToDevice, GetMainWindow.
variable DB_SetVarProc_SweepNo(WMSetVariableAction *sva)
References CHECKBOX_SELECTED, OVS_ChangeSweepSelectionState, OVS_IsActive, UpdateSweepPlot.
string DB_GetAllDevicesWithData()
References GetAllDevicesWithContent, GetListOfLockedDevices, GetUniqueTextEntriesFromList, NONE.
Referenced by DB_OpenDataBrowser.
variable DB_AddSweepToGraph(string win, variable index, BufferedDrawInfo *bdi=defaultValue)
Adds traces of a sweep to the databrowser graph.
win Name of the DataBrowser index Index of the sweep bdi [optional, default = n/a] BufferedDrawInfo structure, when given buffered draw is used.
References AR_UpdateTracesIfReq, BSP_FetchSelectedChannels, BSP_GatherTiledGraphSettings, BSP_GetDevice, CreateTiledChannelGraph, DB_GetLBNWave, DB_SplitSweepsIfReq, GetAxisLabelCacheWave, GetConfigWave, GetDeviceDataPath, GetMainWindow, GetNextTraceIndex, IsValidSweepAndConfig, LBN_NUMERICAL_VALUES, LBN_TEXTUAL_VALUES, OVS_GetSweepAndExperiment.
Referenced by AddSweepToGraph.
static variable DB_SplitSweepsIfReq(string win, variable sweepNo)
References BSP_GetDevice, BSP_HasBoundDevice, COUNTOBJECTS_WAVES, DB_GetLBNWave, GetConfigWave, GetDeviceDataPath, GetSingleSweepFolder, GetSweepWave, KillOrMoveToTrash, LBN_NUMERICAL_VALUES, SplitSweepIntoComponents, TTL_RESCALE_ON, WAVE_BACKUP_SUFFIX.
Referenced by DB_AddSweepToGraph, DB_UpdateSweepPlot.
string DB_FindDataBrowser(string device)
Find a Databrowser which is locked to the given DAEphys panel.
References BSP_GetDevice, BSP_IsDataBrowser, panel.
Referenced by PSQ_PipetteInBath, SC_GetPulseAveragePropertiesWaves, SC_SpikeControl, SetControlInEvent, SWS_AfterSweepDataChangeHook.
variable DB_WindowHook(WMWinHookStruct *s)
References AssertOnAndClearRTError, BSP_GetFolder, BSP_HasBoundDevice, ClearRTError, KillOrMoveToTrash, MIES_BSP_PANEL_FOLDER, PS_StoreWindowCoordinate.