MIES_NeuroDataWithoutBorders.ipf
const double NWB_ASYNC_WRITING_TIMEOUT
Referenced by NWB_ASYNC_FinishWriting.
const double NWB_ASYNC_MAX_ITERATIONS
Referenced by NWB_ASYNC_FinishWriting.
static variable NWB_GetStartTimeOfSweep(WaveText textualValues, variable sweepNo, wave sweepWave)
Return the starting time, in fractional seconds since Igor Pro epoch in UTC, of the given sweep.
For existing sweeps with HIGH_PREC_SWEEP_START_KEY labnotebook entries we use the sweep wave's modification time. The sweep wave can be either an DAQDataWave or a Sweep_$num wave. Passing the DAQDataWave is more accurate.
References ASSERT_TS, DATA_ACQUISITION_MODE, GetLastSettingTextIndep, HIGH_PREC_SWEEP_START_KEY, isEmpty, ParseISO8601TimeStamp, ROWS.
Referenced by NWB_AppendSweepLowLevel, NWB_FirstStartTimeOfAllSweeps.
static variable NWB_FirstStartTimeOfAllSweeps()
Return the creation time, in seconds since Igor Pro epoch in UTC, of the oldest sweep wave for all devices.
Return NaN if no sweeps could be found
References ASSERT, DATA_SWEEP_REGEXP, ExtractSweepNumber, GetAllDevicesWithContent, GetDeviceDataPath, GetLBTextualValues, GetListOfObjects, isEmpty, IsValidSweepNumber, NWB_GetStartTimeOfSweep.
Referenced by NWB_GetFileForExport.
static std::tuple< variable, variable > NWB_GetFileForExport(variable nwbVersion, string overrideFilePath=defaultValue)
Return the HDF5 file identifier referring to an open NWB file for export.
Open one if it does not exist yet. nwbVersion Set NWB version if new file is created overrideFilePath [optional] file path for new files to override the internal generation algorithm fileID HDF5 file identifier or NaN on user abort createdNewNWBFile new NWB file was created (1) or an existing opened (0)
References ASSERT, CleanupExperimentName, CreateCommonGroups, CreateIntraCellularEphys, DateTimeInUTC, DEBUGPRINT, FileExists, GetExperimentName, GetNWBMajorVersion, GetTimeStamp, H5_IsFileOpen, H5_OpenFile, InitToplevelInfo, isEmpty, IsEmpty, IsFinite, NWB_AddGeneratorString, NWB_AddSpecifications, NWB_FirstStartTimeOfAllSweeps, NWB_GetFileForExport, NWB_ReadSessionStartTime, ReadNWBVersion, UNTITLED_EXPERIMENT.
Referenced by NWB_AppendSweepDuringDAQ, NWB_ExportAllData, NWB_ExportAllStimsets, NWB_GetFileForExport, NWB_PrepareExport.
static variable NWB_AddGeneratorString(variable fileID, variable nwbVersion)
References EnsureValidNWBVersion, GetArchitectureBits, GetIgorProBuildVersion, GetIgorProVersion, GetMIESVersionAsString, H5_GetLibraryVersion, H5_WriteTextAttribute, H5_WriteTextDataset, LABNOTEBOOK_VERSION, MarkAsCustomEntry, SWEEP_EPOCH_VERSION, WriteNeuroDataType.
Referenced by NWB_GetFileForExport.
static variable NWB_AddSpecifications(variable fileID, variable nwbVersion)
References EnsureValidNWBVersion, WriteSpecifications.
Referenced by NWB_GetFileForExport.
static variable NWB_ReadSessionStartTime(variable fileID)
References ASSERT, IPNWB_PLACEHOLDER, ParseISO8601TimeStamp, ReadTextDataSetAsString.
Referenced by NWB_GetFileForExport.
static variable NWB_AddDevice(NWBAsyncParameters *s)
References AddDevice, NWBAsyncParameters::device, NWBAsyncParameters::locationID, NWBAsyncParameters::numericalValues, NWB_GenerateDeviceDescription, NWBAsyncParameters::nwbVersion, NWBAsyncParameters::textualValues.
Referenced by NWB_AddDeviceSpecificData, NWB_ASYNC_Worker.
static string NWB_GenerateDeviceDescription(string device, wave numericalValues, WaveText textualValues)
References ASSERT_TS, GetLastSettingIndep, GetLastSettingTextIndep, HARDWARE_ITC_DAC, HARDWARE_NI_DAC, IsEmpty, IsNaN, ParseDeviceString, UNKNOWN_MODE.
Referenced by NWB_AddDevice.
dfref NWB_ASYNC_Worker(dfref dfr)
References AddModificationTimeEntry, NWB_AddDevice, NWB_AppendSweepLowLevel, NWB_ASYNC_DeserializeStruct, NWB_Flush, NWB_WriteLabnoteBooksAndComments, NWB_WriteResultsWaves.
variable NWB_ASYNC_Readout(dfref dfr, variable err, string errmsg)
References BUG.
static variable NWB_WriteLabnoteBooksAndComments(NWBAsyncParameters *s)
References NWBAsyncParameters::compressionMode, NWBAsyncParameters::device, H5_CreateGroupsRecursively, H5_OpenGroup, H5_WriteDataset, H5_WriteTextDataset, NWBAsyncParameters::locationID, MarkAsCustomEntry, NWBAsyncParameters::numericalKeys, NWBAsyncParameters::numericalValues, NWBAsyncParameters::nwbVersion, RemoveUnusedRows, NWBAsyncParameters::textualKeys, NWBAsyncParameters::textualValues, NWBAsyncParameters::userComment, WriteNeuroDataType.
Referenced by NWB_ASYNC_Worker.
static variable NWB_WriteResultsWaves(NWBAsyncParameters *s)
References NWBAsyncParameters::compressionMode, H5_CreateGroupsRecursively, H5_OpenGroup, H5_WriteDataset, H5_WriteTextDataset, NWBAsyncParameters::locationID, NWBAsyncParameters::numericalResultsKeys, NWBAsyncParameters::numericalResultsValues, NWBAsyncParameters::nwbVersion, RemoveUnusedRows, NWBAsyncParameters::textualResultsKeys, NWBAsyncParameters::textualResultsValues, WriteNeuroDataType.
Referenced by NWB_ASYNC_Worker, NWB_ExportAllData.
static variable NWB_AddDeviceSpecificData(NWBAsyncParameters *s, variable writeStoredTestPulses)
References AddModificationTimeEntry, NWBAsyncParameters::locationID, NWB_AddDevice, NWB_WriteTestpulseData, NWBAsyncParameters::nwbVersion.
Referenced by NWB_ExportAllData.
variable NWB_WriteTestpulseData(NWBAsyncParameters *s, variable writeStoredTestPulses)
References NWBAsyncParameters::compressionMode, NWBAsyncParameters::device, GetDeviceTestPulse, GetListOfObjects, GetNoCompression, GetSingleChunkCompression, H5_CreateGroupsRecursively, H5_OpenGroup, H5_WriteDataset, NWBAsyncParameters::locationID, MarkAsCustomEntry, NWB_AppendStoredTestPulses, NWBAsyncParameters::nwbVersion, RemoveUnusedRows, TP_STORAGE_REGEXP, WriteNeuroDataType.
Referenced by NWB_AddDeviceSpecificData.
variable NWB_ExportAllData(variable nwbVersion, string overrideFilePath=defaultValue, variable writeStoredTestPulses=defaultValue, variable writeIgorHistory=defaultValue, variable compressionMode=defaultValue, variable keepFileOpen=defaultValue, variable overwrite=defaultValue)
Programmatically export all acquired data from all devices into a NWB file.
Use NWB_ExportWithDialog() for interactive export. nwbVersion major NWB format version, one of 1 or 2 (aka NWB_VERSION_LATEST) overrideFilePath use this file path instead of an internally derived one writeStoredTestPulses [optional, defaults to false] store the raw test pulse data writeIgorHistory [optional, defaults to true] store the Igor Pro history and the log file compressionMode [optional, defaults to chunked compression] One of CompressionMode keepFileOpen [optional, defaults to false] keep the NWB file open after return, or close it overwrite [optional, defaults to false] overwrite any existing NWB file with the same name, only used when overrideFilePath is passed 0 on success, non-zero on failure
References ASSERT, CloseNWBFile, CompressionModeToString, CONTENT_TYPE_ALL, ControlWindowToFront, DAP_SerializeCommentNotebook, DATA_SWEEP_REGEXP, ExtractSweepNumber, FileExists, GetAllDevicesWithContent, GetChunkedCompression, GetConfigWave, GetDeviceDataPath, GetLBNumericalKeys, GetLBNumericalValues, GetLBTextualKeys, GetLBTextualValues, GetListOfObjects, GetNumericalResultsKeys, GetNumericalResultsValues, GetNWBFilePathExport, GetSessionStartTimeReadBack, GetTextualResultsKeys, GetTextualResultsValues, GetUserComment, IsEmpty, IsFinite, LOG_AddEntry, NWB_AddDeviceSpecificData, NWB_AppendIgorHistoryAndLogFile, NWB_AppendStimset, NWB_AppendSweepLowLevel, NWB_CheckForMissingSweeps, NWB_GetExportedFileSize, NWB_GetFileForExport, NWB_GetStimsetFromPanel, NWB_WriteResultsWaves, PACKAGE_MIES, ROStr, NWBAsyncParameters::sweep.
Referenced by AB_ReExport, IVS_ExportAllData, NWB_ExportWithDialog, NWB_PrepareExport, PerformMiesTasks.
variable NWB_ASYNC_FinishWriting(string device)
Wait for ASYNC nwb writing to finish.
Currently wait up to 10min (NWB_ASYNC_WRITING_TIMEOUT * NWB_ASYNC_MAX_ITERATIONS), everything above 5s is considered a bug.
References ASYNC_WaitForWLCToFinishAndRemove, BUG, NWB_ASYNC_MAX_ITERATIONS, NWB_ASYNC_WorkLoadName, NWB_ASYNC_WRITING_TIMEOUT.
Referenced by CloseNWBFile, DAP_UnlockDevice.
static string NWB_ASYNC_WorkLoadName(string device)
References NWB_WORKLOAD_CLASS.
Referenced by NWB_AppendSweepDuringDAQ, NWB_ASYNC_FinishWriting.
variable NWB_CheckForMissingSweeps(string device, WaveText sweepNames)
References ControlWindowToFront, ExtractSweepNumber, GetLBNumericalValues, GetSweepsWithSetting, ROWS.
Referenced by NWB_ExportAllData.
static variable NWB_GetExportedFileSize()
Return the file size in MiB of the currently written into NWB file.
This is only approximately correct as the file is open in HDF5 and thus not everything is flushed.
References GetFileSize, GetNWBFilePathExport, IsEmpty, ROStr.
Referenced by NWB_ExportAllData.
variable NWB_ExportAllStimsets(variable nwbVersion, string overrideFilePath=defaultValue)
Export all stimsets into NWB.
NWB file is closed after the function returns.
References CloseNWBFile, ControlWindowToFront, GetChunkedCompression, IsEmpty, IsFinite, LOG_AddEntry, NWB_AppendStimset, NWB_GetFileForExport, PACKAGE_MIES, ST_GetStimsetList.
Referenced by NWB_ExportWithDialog.
variable NWB_ExportWithDialog(variable exportType, variable nwbVersion=defaultValue)
Export all data into NWB using compression.
Ask the file location from the user exportType Export all data and referenced stimsets (NWB_EXPORT_DATA) or all stimsets (NWB_EXPORT_STIMSETS) nwbVersion [optional, defaults to latest version] major NWB version
References ASSERT, CloseNWBFile, GetExperimentName, GetNWBVersion, GetTimeStamp, isEmpty, NWB_EXPORT_DATA, NWB_EXPORT_STIMSETS, NWB_ExportAllData, NWB_ExportAllStimsets, UNTITLED_EXPERIMENT.
static variable NWB_AppendStoredTestPulses(string device, variable nwbVersion, variable locationID, variable compressionMode)
Write the stored test pulses to the NWB file.
References GetNumberFromWaveNote, GetStoredTestPulseWave, H5_WriteDataset, NOTE_INDEX, WriteNeuroDataType.
Referenced by NWB_WriteTestpulseData.
static variable NWB_AppendStimset(variable nwbVersion, variable locationID, string stimsets, variable compressionMode)
Export given stimsets to NWB file.
nwbVersion major NWB version locationID Identifier of open hdf5 group or file stimsets Single stimset as string or list of stimsets sparated by ; compressionMode Type of compression to use, one of CompressionMode
References AddModificationTimeEntry, IsEmpty, NWB_WriteStimsetCustomWave, NWB_WriteStimsetTemplateWaves, ROWS, STIMSET_TP_WHILE_DAQ, WB_CustomWavesFromStimSet, WB_StimsetRecursionForList.
Referenced by NWB_ExportAllData, NWB_ExportAllStimsets, NWB_PrepareExport.
variable NWB_PrepareExport(variable nwbVersion)
Prepare everything for sweep-by-sweep NWB export.
References GetNoCompression, IsFinite, NWB_AppendStimset, NWB_ExportAllData, NWB_GetFileForExport, ST_GetStimsetList.
Referenced by DAP_CheckSettings.
variable NWB_AppendSweepDuringDAQ(string device, wave DAQDataWave, wave DAQConfigWave, variable sweep, variable nwbVersion)
References ASYNC_Execute, ASYNC_PrepareDF, DAP_SerializeCommentNotebook, NWBAsyncParameters::device, GetLBNumericalKeys, GetLBNumericalValues, GetLBTextualKeys, GetLBTextualValues, GetNumericalResultsKeys, GetNumericalResultsValues, GetSessionStartTimeReadBack, GetTextualResultsKeys, GetTextualResultsValues, GetUserComment, IsFinite, NO_COMPRESSION, NWB_ASYNC_SerializeStruct, NWB_ASYNC_WorkLoadName, NWB_GetFileForExport, ROStr.
Referenced by SWS_SaveAcquiredData.
static string NWB_GetStimsetFromPanel(string device, variable sweep)
Get stimsets by analysing currently loaded sweep.
numericalValues and textualValues are generated from device list of stimsets
References GetLBNumericalValues, GetLBTextualValues, NWB_GetStimsetFromSweepGeneric.
Referenced by NWB_ExportAllData.
string NWB_GetStimsetFromSpecificSweep(string dataFolder, string device, variable sweep)
Get stimsets by analysing dataFolder of loaded sweep.
numericalValues and textualValues are generated from previously loaded data. used in the context of loading from a stored experiment file. on load a sweep is stored in a device/dataFolder hierarchy. list of stimsets
References GetAnalysisLabNBFolder, NWB_GetStimsetFromSweepGeneric.
Referenced by AB_LoadStimsetFromFile.
static string NWB_GetStimsetFromSweepGeneric(variable sweep, wave numericalValues, WaveText textualValues)
Get related Stimsets by corresponding sweep.
input numerical and textual values storage waves for current sweep list of stimsets
References DATA_ACQUISITION_MODE, GetLastSetting, GetTTLLabnotebookEntry, isEmpty, LABNOTEBOOK_TTL_STIMSETS, NUM_DA_TTL_CHANNELS, NUM_HEADSTAGES, STIM_WAVE_NAME_KEY.
Referenced by NWB_GetStimsetFromPanel, NWB_GetStimsetFromSpecificSweep.
static variable NWB_AppendSweepLowLevel(NWBAsyncParameters *s)
References AddElectrode, AFH_GetDAQDataColumn, ASSERT_TS, CLAMPMODE_ENTRY_KEY, COLS, NWBAsyncParameters::compressionMode, ConvertSamplingIntervalToRate, COUNTOBJECTS_WAVES, CreateLBNUnassocKey, NWBAsyncParameters::DAQConfigWave, NWBAsyncParameters::DAQDataWave, DATA_ACQUISITION_MODE, NWBAsyncParameters::device, ExtractOneDimDataFromSweep, FindIndizes, GetADCListFromConfig, GetAllObjects_TS, GetDACListFromConfig, GetDefaultElectrodeName, GetLastSetting, GetLastSettingIndep, GetNextFreeGroupIndex, GetNWBgroupPatchClampSeries, GetRowIndex, GetSamplingInterval, GetTTLBits, GetTTLLabnotebookEntry, HARDWARE_ITC_DAC, HARDWARE_NI_DAC, InitWriteChannelParams, IPNWB_CHANNEL_TYPE_ADC, IPNWB_CHANNEL_TYPE_DAC, IPNWB_CHANNEL_TYPE_TTL, IPNWB_PLACEHOLDER, IsEmpty, IsFinite, IsNaN, LABNOTEBOOK_LAYER_COUNT, LABNOTEBOOK_TTL_STIMSETS, NWBAsyncParameters::locationID, NUM_DA_TTL_CHANNELS, NUM_HEADSTAGES, NWBAsyncParameters::numericalKeys, NWBAsyncParameters::numericalValues, NWB_ClearWriteChannelParams, NWB_FetchEpochs, NWB_GetStartTimeOfSweep, NWB_GetTimeSeriesProperties, NWB_SOURCE_TTL_BIT, NWBAsyncParameters::nwbFilePath, NWBAsyncParameters::nwbVersion, PROP_NON_EMPTY, ROWS, NWBAsyncParameters::session_start_time, SplitTTLWaveIntoComponents, STIM_WAVE_NAME_KEY, NWBAsyncParameters::sweep, NWBAsyncParameters::textualValues, TTL_RESCALE_OFF, WriteSingleChannel.
Referenced by NWB_ASYNC_Worker, NWB_ExportAllData.
static wave NWB_FetchEpochs(wave numericalValues, WaveTextOrNull textualValues, variable sweep, variable channelNumber, variable channelType)
Return free text wave with the epoch information of the given channel.
See GetEpochsWave() for the wave layout.
References ASSERT_TS, DATA_ACQUISITION_MODE, EP_EpochStrToWave, EPOCHS_ENTRY_KEY, GetLastSettingChannel, ROWS, SetEpochsDimensionLabels, XOP_CHANNEL_TYPE_DAC.
Referenced by NWB_AppendSweepLowLevel.
static variable NWB_ClearWriteChannelParams(WriteChannelParams *s)
Clear all entries which are channel specific.
References WriteChannelParams::device, WriteChannelParams::groupIndex, IsEmpty, WriteChannelParams::samplingRate, WriteChannelParams::startingTime, WriteChannelParams::sweep.
Referenced by NWB_AppendSweepLowLevel.
static variable NWB_WriteStimsetCustomWave(variable nwbVersion, variable locationID, wave custom_wave, variable compressionMode)
Save Custom Wave (from stimset) in NWB file.
nwbVersion major NWB version locationID Open HDF5 group or file identifier custom_wave Wave reference to the wave that is to be saved compressionMode [optional, defaults to NO_COMPRESSION] Type of compression to use, one of CompressionMode
References H5_CreateGroupsRecursively, H5_OpenGroup, H5_WriteDataset, RemovePrefix, WriteNeuroDataType.
Referenced by NWB_AppendStimset.
static variable NWB_WriteStimsetTemplateWaves(variable nwbVersion, variable locationID, string stimSet, variable compressionMode)
References ControlWindowToFront, H5_CreateGroupsRecursively, H5_OpenGroup, H5_WriteDataset, MarkAsCustomEntry, STIMSET_PARAM_SEGWVTYPE, STIMSET_PARAM_WP, STIMSET_PARAM_WPT, WB_CreateAndGetStimSet, WB_GetParameterWaveName, WB_GetSegWvTypeForSet, WB_GetWaveParamForSet, WB_GetWaveTextParamForSet, WB_StimsetIsFromThirdParty, WriteNeuroDataType.
Referenced by NWB_AppendStimset.
static variable NWB_LoadStimset(variable locationID, string stimset, variable overwrite, variable verbose=defaultValue)
Load specified stimset from Stimset Group.
locationID id of an open hdf5 group containing the stimsets stimset string of stimset verbose [optional] set to get more output to the command line overwrite indicate whether the stored stimsets should be deleted if they exist 1 on error
References CHANNEL_TYPE_UNKNOWN, ControlWindowToFront, GetSetParamFolder, GetStimSetType, H5_DatasetExists, H5_ListGroupMembers, H5_LoadDataset, STIMSET_PARAM_SEGWVTYPE, STIMSET_PARAM_WP, STIMSET_PARAM_WPT, WB_GetParameterWaveName, WB_KillParameterWaves, WB_KillStimset, WB_ParameterWavesExist, WB_StimsetExists.
Referenced by NWB_LoadAllStimsets, NWB_LoadStimsets.
variable NWB_LoadCustomWave(variable locationID, string fullPath, variable overwrite)
Load a custom wave from NWB file.
loads waves that were saved by NWB_WriteStimsetCustomWave locationID open file or group from nwb file fullPath full Path in igor notation to custom wave overwrite indicate whether the stored custom wave should be deleted if it exists 1 on error and 0 on success
References createDFWithAllParents, GetFolder, H5_DatasetExists, H5_LoadDataset, KillOrMoveToTrash, RemovePrefix.
Referenced by NWB_LoadCustomWaves.
variable NWB_LoadAllStimsets(variable overwrite=defaultValue, string fileName=defaultValue, variable loadOnlyBuiltins=defaultValue)
Load all stimsets from specified HDF5 file.
fileName [optional, shows a dialog on default] provide full file name/path for loading stimset overwrite [optional, defaults to false] indicate if the stored stimset should be deleted before the load. loadOnlyBuiltins [optional, defaults to false] load only builtin stimsets 1 on error and 0 on success
References DAP_UpdateDaEphysStimulusSetPopups, GetUniqueTextEntriesFromList, GetWaveBuilderParameterTypeName, H5_CloseFile, H5_OpenFile, IsEmpty, LOG_AddEntry, NWB_LoadCustomWaves, NWB_LoadStimset, OpenStimset, PACKAGE_MIES, ReadStimsets, STIMSET_PARAM_SEGWVTYPE, STIMSET_PARAM_WP, STIMSET_PARAM_WPT, StimsetPathExists, WBP_IsBuiltinStimset.
Referenced by DAP_LoadBuiltinStimsets, MEN_DownloadStimsets.
variable NWB_LoadStimsets(variable groupID, string stimsets, variable overwrite, string processedStimsets=defaultValue)
Load specified stimsets and their dependencies from NWB file.
see AB_LoadStimsets() for similar structure groupID Open Stimset Group of HDF5 File. See OpenStimset() stimsets ";" separated list of all stimsets of the current sweep. processedStimsets [optional] the list indicates which stimsets were already loaded. on recursion this parameter avoids duplicate circular references. overwrite indicate whether the stored stimsets should be deleted if they exist 1 on error and 0 on success
References ListFromList, NWB_LoadStimset, NWB_LoadStimsets, WB_StimsetFamilyNames.
Referenced by AB_LoadStimsetFromFile, NWB_LoadStimsets.
variable NWB_LoadCustomWaves(variable groupID, string stimsets, variable overwrite)
Load custom waves for specified stimset from Igor experiment file.
see AB_LoadCustomWaves() for similar structure 1 on error and 0 on success
References NWB_LoadCustomWave, ROWS, WB_CustomWavesPathFromStimSet, WB_StimsetRecursionForList.
Referenced by AB_LoadStimsetFromFile, NWB_LoadAllStimsets.
static variable NWB_GetTimeSeriesProperties(variable nwbVersion, WaveText numericalKeys, wave numericalValues, WriteChannelParams *p, TimeSeriesProperties *tsp)
References AddCustomProperty, AddProperty, ASSERT_TS, WriteChannelParams::channelType, WriteChannelParams::clampMode, DATA_ACQUISITION_MODE, DetermineDataTypeFromProperties, DetermineDataTypeRefTree, WriteChannelParams::electrodeNumber, GetLastSetting, I_CLAMP_MODE, I_EQUAL_ZERO_MODE, InitTimeSeriesProperties, IPNWB_CHANNEL_TYPE_ADC, IPNWB_CHANNEL_TYPE_DAC, IsEmpty, IsFinite, TimeSeriesProperties::missing_fields, NWB_AddSweepDataSets, STIMSET_SCALE_FACTOR_KEY, WriteChannelParams::sweep, V_CLAMP_MODE.
Referenced by NWB_AppendSweepLowLevel.
static variable NWB_AddSweepDataSets(WaveText numericalKeys, wave numericalValues, variable sweep, string settingsProp, string nwbProp, variable headstage, TimeSeriesProperties *tsp, variable factor=defaultValue, string enabledProp=defaultValue)
References AddProperty, DATA_ACQUISITION_MODE, GetLastSetting, IsFinite, LBN_GetEntryProperties.
Referenced by NWB_GetTimeSeriesProperties.
variable NWB_LoadLabNoteBook(variable locationID, string notebook, dfref dfr)
function saves contents of specified notebook to data folder
locationID id of nwb file or notebooks folder notebook name of notebook to be loaded dfr igor data folder where data should be loaded into
References DataFolderExistsDFR, H5_GroupExists.
Referenced by AB_LoadLabNotebookFromNWB.
variable NWB_Flush(variable locationID)
Flushes the contents of the NWB file to disc.
References H5_FlushFile, IsNaN.
Referenced by BeforeExperimentSaveHook, NWB_ASYNC_Worker.
static variable NWB_AppendLogFileToString(string path, string *str)
References FileExists, GetISO8601TimeStamp, LoadTextFile, LOGFILE_NWB_MARKER, NormalizeToEOL.
Referenced by NWB_AppendIgorHistoryAndLogFile.
static variable NWB_AppendIgorHistoryAndLogFile(variable nwbVersion, variable locationID)
References ASSERT, EnsureValidNWBVersion, GetChunkedCompression, GetHistoryAndLogFileDatasetName, GetHistoryNotebookText, GetNWBMajorVersion, GetNWBOverrideHistoryAndLogFile, GetZeroMQXOPLogfile, H5_OpenGroup, H5_WriteTextDataset, IsEmpty, IsNaN, LOG_GetFile, MarkAsCustomEntry, NormalizeToEOL, NWB_AppendLogFileToString, PACKAGE_MIES, ReadNWBVersion, ROStr.
Referenced by NWB_ExportAllData.