MIES_WaveBuilderPanel.ipf
const double FROM_PANEL_TO_WAVE
Referenced by WBP_TranslateControlContents.
const double FROM_WAVE_TO_PANEL
Referenced by WBP_ParameterWaveToPanel, WBP_TranslateControlContents.
string WBP_GetAnalysisFunctions_V3()
Wrapper functions to be used in GUI recreation macros This avoids having to hardcode the parameter values.
References ANALYSIS_FUNCTION_VERSION_V3, WBP_GetAnalysisFunctions.
Referenced by WBP_LoadSet.
const string panel
Referenced by WBP_AdjustDeltaControls, WBP_AnaFuncsToWPT, WBP_ButtonProc_DeleteSet, WBP_ButtonProc_LoadSet, WBP_ButtonProc_OpenAnaFuncs, WBP_ButtonProc_OpenAnaParamGUI, WBP_ButtonProc_SaveSet, WBP_ChangeWaveType, WBP_CreateWaveBuilderPanel, WBP_CutOffCrossOver, WBP_DisplaySetInPanel, WBP_FinalTabHook, WBP_GetFFTSpectrumPanel, WBP_GetStimulusType, WBP_HighPassDeltaLimits, WBP_InitialTabHook, WBP_ListControlsPerStimulusType, WBP_LoadSet, WBP_LowPassDeltaLimits, WBP_MainWindowHook, WBP_ParameterWaveToPanel, WBP_PopupMenu_LoadSet, WBP_ReturnListSavedSets, WBP_ReturnPulseDurationMax, WBP_SetVarProc_EpochToEdit, WBP_ShowFFTSpectrumIfReq, WBP_StartupSettings, WBP_UpdateControlAndWave, WBP_UpdateDependentControls, WBP_UpdateEpochControls, WBP_UpdatePanelIfAllowed.
const string WaveBuilderGraph
Referenced by WaveBuilder, WBP_MainWindowHook.
const string AnalysisParamGUI
Referenced by WBP_LoadSet, WBP_StartupSettings, WBP_ToggleAnalysisParamGUI.
const string DEFAULT_SET_PREFIX
Referenced by WBP_ButtonProc_SaveSet, WBP_LoadSet.
const string SEGWVTYPE_CONTROL_REGEXP
Referenced by WBP_GetWaveTypeFromControl.
const string WP_CONTROL_REGEXP
Referenced by WBP_GetWaveTypeFromControl, WBP_ListControlsPerStimulusType, WBP_ParameterWaveToPanel.
const string WPT_CONTROL_REGEXP
Referenced by WBP_GetWaveTypeFromControl, WBP_ListControlsPerStimulusType, WBP_ParameterWaveToPanel.
const string SEGWVTYPE_ALL_CONTROL_REGEXP
Referenced by WBP_ListControlsPerStimulusType, WBP_ParameterWaveToPanel, WBP_UpdateControlAndWave.
const double WBP_WAVETYPE_WP
Referenced by WBP_AdjustDeltaControls, WBP_ExtractRowNumberFromControl, WBP_GetWaveTypeFromControl, WBP_MainWindowHook, WBP_UpdateControlAndWave.
const double WBP_WAVETYPE_WPT
Referenced by WBP_ExtractRowNumberFromControl, WBP_GetWaveTypeFromControl, WBP_MainWindowHook, WBP_UpdateControlAndWave.
const double WBP_WAVETYPE_SEGWVTYPE
Referenced by WBP_AdjustDeltaControls, WBP_ExtractRowNumberFromControl, WBP_GetWaveTypeFromControl, WBP_MainWindowHook, WBP_UpdateControlAndWave.
const string HIDDEN_CONTROLS_CUSTOM_COMBINE
Referenced by WBP_FinalTabHook, WBP_ListControlsPerStimulusType.
const string HIDDEN_CONTROLS_SQUARE_PULSE
Referenced by WBP_FinalTabHook, WBP_ListControlsPerStimulusType.
const double EPOCH_HL_TYPE_LEFT
Referenced by WBP_AddEpochHLTraces, WBP_DisplaySetInPanel.
const double EPOCH_HL_TYPE_RIGHT
Referenced by WBP_AddEpochHLTraces, WBP_DisplaySetInPanel.
variable WB_OpenStimulusSetInWaveBuilder()
References AB_LoadStimsetForSweep, BSP_GetPanel, BSP_IsDataBrowser, ControlWindowToFront, DATA_ACQUISITION_MODE, GetLastSetting, GetSweepBrowserMap, IsNaN, PGC_SetAndActivateControl, SB_GetIndexFromSweepDataPath, SB_GetSweepBrowserFolder, SB_TranslateSBMapIndexToABMapIndex, STIM_WAVE_NAME_KEY, TUD_GetUserData, WB_CreateAndGetStimSet, WBP_CreateWaveBuilderPanel, WindowExists.
string WBP_CreateWaveBuilderPanel()
References AddVersionToPanel, GetSegmentTypeWave, GetWaveBuilderWaveParam, GetWaveBuilderWaveTextParam, GetWBEpochCombineList, GetWBSvdStimSetDAPath, GetWBSvdStimSetParamDAPath, GetWBSvdStimSetParamPath, GetWBSvdStimSetParamTTLPath, GetWBSvdStimSetPath, GetWBSvdStimSetTTLPath, KillOrMoveToTrash, panel, PS_InitCoordinates, WAVEBUILDER_PANEL_VERSION.
Referenced by AB_ButtonProc_LoadStimsets, ScreenShotsForWaveBuilder, WB_OpenStimulusSetInWaveBuilder, WBP_ListControlsPerStimulusType.
variable WBP_StartupSettings()
References AnalysisParamGUI, CallFunctionForEachListItem, CHECKBOX_UNSELECTED, ControlWindowToFront, GetSegmentTypeWave, GetWaveBuilderWaveParam, GetWaveBuilderWaveTextParam, KillOrMoveToTrash, NONE, panel, PGC_SetAndActivateControl, SearchForInvalidControlProcs, SetCheckBoxState, SetPopupMenuIndex, WBP_AdjustDeltaControls, WBP_LoadSet, WindowExists.
static variable WBP_AddEpochHLTraces(dfref dfr, variable epochHLType, variable epoch, variable numEpochs)
Add epoch highlightning traces Uses fill-to-next on specially created waves added before and after the current trace.
References EPOCH_HL_TYPE_LEFT, EPOCH_HL_TYPE_RIGHT, GetEpochID.
Referenced by WBP_DisplaySetInPanel.
static variable WBP_DisplaySetInPanel()
References COLS, DoAbortNow, EPOCH_HL_TYPE_LEFT, EPOCH_HL_TYPE_RIGHT, GetAxesRanges, GetSegmentTypeWave, GetSetVariable, GetWaveBuilderDataPath, GetWaveBuilderDispWave, HasPanelLatestVersion, panel, RemoveTracesFromGraph, SetAxesRanges, WAVEBUILDER_PANEL_VERSION, WaveMinAndMaxWrapper, WB_GetStimSetForWaveBuilder, WBP_AddEpochHLTraces, WBP_GetSweepColor.
Referenced by WBP_UpdatePanelIfAllowed.
static variable WBP_UpdateDependentControls(string checkBoxCtrl, variable checked)
Reponsible for adjusting controls which depend on other controls.
Must be called before the changed settings are written into the parameter waves.
References CHECKBOX_SELECTED, CHECKBOX_UNSELECTED, DisableControls, EnableControls, EPOCH_TYPE_PULSE_TRAIN, GetCheckBoxState, GetTabID, IsFinite, panel, SetControlUserData, WBP_UpdateControlAndWave.
Referenced by WBP_CheckProc, WBP_ParameterWaveToPanel.
static variable WBP_UpdatePanelIfAllowed()
References DisableControl, DisableControls, EnableControl, EnableControls, EPOCH_TYPE_COMBINE, EPOCH_TYPE_NOISE, EPOCH_TYPE_PULSE_TRAIN, EPOCH_TYPE_SIN_COS, GetCheckBoxState, GetSetVariable, GetTabID, panel, SetSetVariable, WB_IsValidCutoffFrequency, WB_UpdateEpochCombineList, WBP_CutOffCrossOver, WBP_DisplaySetInPanel, WBP_GetStimulusType, WBP_HighPassDeltaLimits, WBP_LowPassDeltaLimits, WBP_ReturnPulseDurationMax.
Referenced by WBP_ButtonProc_NewSeed, WBP_ChangeWaveType, WBP_CheckProc, WBP_CheckProc_PreventUpdate, WBP_InitialTabHook, WBP_LoadSet, WBP_PopMenuProc_WaveToLoad, WBP_PopupMenu, WBP_SetVarCombineEpochFormula, WBP_SetVarProc_UpdateParam, WBP_UpdateEpochControls.
static variable WBP_ParameterWaveToPanel(variable stimulusType)
Passes the data from the WP wave to the panel.
References ASSERT, EPOCH_TYPE_CUSTOM, EPOCH_TYPE_PULSE_TRAIN, FROM_WAVE_TO_PANEL, GetCheckBoxState, GetSetVariable, GetWaveBuilderWaveParam, GetWaveBuilderWaveTextParam, INDEP_EPOCH_TYPE, IsFinite, panel, SEGWVTYPE_ALL_CONTROL_REGEXP, SetSetVariableString, WBP_ExtractRowNumberFromControl, WBP_SetControl, WBP_TranslateControlContents, WBP_UpdateDependentControls, WP_CONTROL_REGEXP, WPT_CONTROL_REGEXP.
Referenced by WBP_InitialTabHook.
static variable WBP_SetControl(string win, string control, variable value=defaultValue, string str=defaultValue)
Generic wrapper for setting a control's value.
References ASSERT, CHECKBOX_SELECTED.
Referenced by WBP_ParameterWaveToPanel, WBP_UpdateControlAndWave.
variable WBP_ButtonProc_DeleteSet(WMButtonAction *ba)
References ControlWindowToFront, GetPopupMenuString, NONE, panel, ST_RemoveStimSet.
variable WBP_CheckProc(WMCheckboxAction *cba)
References WBP_UpdateControlAndWave, WBP_UpdateDependentControls, WBP_UpdatePanelIfAllowed.
variable WBP_InitialTabHook(WMTabControlAction *tca)
Additional initialhook called in ACL_DisplayTab
References ASSERT, GetPopupMenuString, GetSegmentTypeWave, GetSetVariable, IsValidEpochNumber, panel, WBP_ParameterWaveToPanel, WBP_UpdatePanelIfAllowed.
variable WBP_FinalTabHook(WMTabControlAction *tca)
Additional finalhook called in ACL_DisplayTab
References CallFunctionForEachListItem, EnableControl, EPOCH_TYPE_COMBINE, EPOCH_TYPE_CUSTOM, EPOCH_TYPE_PULSE_TRAIN, EPOCH_TYPE_SQUARE_PULSE, HIDDEN_CONTROLS_CUSTOM_COMBINE, HIDDEN_CONTROLS_SQUARE_PULSE, HideControls, panel, ShowControls, WBP_AdjustDeltaControls.
variable WBP_ButtonProc_SaveSet(WMButtonAction *ba)
References DAP_UpdateDaEphysStimulusSetPopups, DEFAULT_SET_PREFIX, GetCheckBoxState, GetSegmentTypeWave, GetSetVariable, GetSetVariableString, GetWaveBuilderWaveParam, GetWaveBuilderWaveTextParam, IsEmpty, NONE, panel, SetSetVariableString, WB_SaveStimSet, WB_UpdateEpochCombineList, WBP_GetStimulusType, WBP_LoadSet.
static variable WBP_GetWaveTypeFromControl(string control)
References SEGWVTYPE_CONTROL_REGEXP, WBP_WAVETYPE_SEGWVTYPE, WBP_WAVETYPE_WP, WBP_WAVETYPE_WPT, WP_CONTROL_REGEXP, WPT_CONTROL_REGEXP.
Referenced by WBP_AdjustDeltaControls, WBP_ExtractRowNumberFromControl, WBP_MainWindowHook, WBP_UpdateControlAndWave.
static variable WBP_ExtractRowNumberFromControl(string control)
Returns the row index into the parameter wave of the parameter represented by the named control.
control name of the control, the expected format is $str_$sep$row_$suffix where $str may contain any characters but $suffix is not allowed to include the substring _$sep. All entries are per epoch type and per epoch number except when the $suffix is ALL which denotes that it is a setting for the full stimset.
References ASSERT, IsFinite, WBP_GetWaveTypeFromControl, WBP_WAVETYPE_SEGWVTYPE, WBP_WAVETYPE_WP, WBP_WAVETYPE_WPT.
Referenced by WBP_AdjustDeltaControls, WBP_ListControlsPerStimulusType, WBP_MainWindowHook, WBP_ParameterWaveToPanel, WBP_UpdateControlAndWave.
variable WBP_UpdateControlAndWave(string control, variable var=defaultValue, string str=defaultValue)
Update the named control and pass its new value into the parameter wave.
References ASSERT, GetSegmentTypeWave, GetSetVariable, GetTabID, GetWaveBuilderWaveParam, GetWaveBuilderWaveTextParam, INDEP_EPOCH_TYPE, IsFinite, panel, SEGWVTYPE_ALL_CONTROL_REGEXP, WBP_ExtractRowNumberFromControl, WBP_GetWaveTypeFromControl, WBP_SetControl, WBP_WAVETYPE_SEGWVTYPE, WBP_WAVETYPE_WP, WBP_WAVETYPE_WPT.
Referenced by WB_MakeWaveBuilderWave, WBP_ButtonProc_NewSeed, WBP_ChangeWaveType, WBP_CheckProc, WBP_PopupMenu, WBP_SetVarProc_UpdateParam, WBP_UpdateDependentControls.
variable WBP_SetVarProc_UpdateParam(WMSetVariableAction *sva)
References WBP_UpdateControlAndWave, WBP_UpdateEpochControls, WBP_UpdatePanelIfAllowed.
static variable WBP_LowPassDeltaLimits()
References GetSegmentTypeWave, GetSetVariable, panel, SetSetVariable.
Referenced by WBP_UpdatePanelIfAllowed.
static variable WBP_HighPassDeltaLimits()
References GetSegmentTypeWave, GetSetVariable, panel, SetSetVariable.
Referenced by WBP_UpdatePanelIfAllowed.
static variable WBP_ChangeWaveType()
References ASSERT, CHANNEL_TYPE_DAC, CHANNEL_TYPE_TTL, DisableControls, EnableControls, GetSegmentTypeWave, GetWaveBuilderWaveParam, KillOrMoveToTrash, panel, WBP_GetStimulusType, WBP_UpdateControlAndWave, WBP_UpdatePanelIfAllowed.
Referenced by WBP_PopMenuProc_WaveType.
variable WBP_GetStimulusType()
References GetPopupMenuString, panel, WB_ParseStimulusType.
Referenced by WB_GetStimSet, WB_UpgradeCustomWaves, WBP_AnaFuncsToWPT, WBP_ButtonProc_SaveSet, WBP_ChangeWaveType, WBP_UpdatePanelIfAllowed.
variable WBP_PopMenuProc_WaveType(WMPopupAction *pa)
References WBP_ChangeWaveType.
string WBP_GetListOfWaves()
References IsEmpty, NONE, WBP_GetFolderPath.
variable WBP_SetVarProc_SetSearchString(WMSetVariableAction *sva)
variable WBP_PopMenuProc_WaveToLoad(WMPopupAction *pa)
References EPOCH_TYPE_CUSTOM, GetSetVariable, GetWaveBuilderWaveTextParam, WBP_GetFolderPath, WBP_UpdatePanelIfAllowed.
string WBP_ReturnListSavedSets()
References GetSetVariableString, IsEmpty, NONE, panel, ST_GetStimsetList.
variable WBP_IsBuiltinStimset(string setName)
Return true if the given stimset is a builtin, false otherwise.
References STIMSET_TP_WHILE_DAQ.
Referenced by NWB_LoadAllStimsets, WB_SaveStimSet.
static variable WBP_LoadSet(string setName)
References AnalysisParamGUI, ASSERT, CHANNEL_TYPE_DAC, DEFAULT_SET_PREFIX, GetCheckBoxState, GetSegmentTypeWave, GetWaveBuilderDataPath, GetWaveBuilderWaveParam, GetWaveBuilderWaveTextParam, INDEP_EPOCH_TYPE, IsValidEpochNumber, KillOrMoveToTrash, NONE, panel, PGC_SetAndActivateControl, ROWS, SetAnalysisFunctionIfFuncExists, SetCheckBoxState, SetPopupMenuIndex, SetSetVariable, SetSetVariableString, WB_GetSegWvTypeForSet, WB_GetWaveParamForSet, WB_GetWaveTextParamForSet, WB_SplitStimsetName, WBP_AnaFuncsToWPT, WBP_GetAnalysisFunctions_V3, WBP_GetAnalysisParamGUIListWave, WBP_UpdateEpochControls, WBP_UpdatePanelIfAllowed, WindowExists.
Referenced by WBP_ButtonProc_LoadSet, WBP_ButtonProc_SaveSet, WBP_PopupMenu_LoadSet, WBP_StartupSettings.
static variable SetAnalysisFunctionIfFuncExists(string win, string ctrl, string stimset, string funcList, string func)
References ControlWindowToFront, IsEmpty, NONE, SetPopupMenuString.
Referenced by WBP_LoadSet.
static variable WBP_UpdateEpochControls()
References GetSegmentTypeWave, GetSetVariable, panel, PGC_SetAndActivateControl, WBP_UpdatePanelIfAllowed.
Referenced by WBP_LoadSet, WBP_SetVarProc_UpdateParam.
variable WBP_SetVarProc_EpochToEdit(WMSetVariableAction *sva)
References GetSegmentTypeWave, panel, PGC_SetAndActivateControl.
variable WBP_PopupMenu_LoadSet(WMPopupAction *pa)
References GetPopupMenuString, panel, WBP_LoadSet.
static variable WBP_CutOffCrossOver()
References GetSetVariable, panel, SetSetVariable, WB_IsValidCutoffFrequency.
Referenced by WBP_UpdatePanelIfAllowed.
static variable WBP_ReturnPulseDurationMax()
Checks to see if the pulse duration in square pulse stimulus trains is too long.
References GetCheckBoxState, GetSetVariable, panel.
Referenced by WBP_UpdatePanelIfAllowed.
dfref WBP_GetFolderPath()
References IsEmpty.
Referenced by WB_UpgradeCustomWaveInWPT, WBP_GetListOfWaves, WBP_PopMenuProc_WaveToLoad, WBP_ReturnFoldersList.
string WBP_ReturnFoldersList()
References COUNTOBJECTS_DATAFOLDER, GetListOfObjects, NONE, WBP_GetFolderPath.
variable WBP_PopMenuProc_FolderSelect(WMPopupAction *pa)
References NONE.
variable WBP_CheckProc_PreventUpdate(WMCheckboxAction *cba)
References WBP_UpdatePanelIfAllowed.
variable WBP_PopupMenu(WMPopupAction *pa)
References WBP_AdjustDeltaControls, WBP_UpdateControlAndWave, WBP_UpdatePanelIfAllowed.
static string WBP_ConvertDeltaLblToCtrlNames(string allControls, string dimLabel)
Convert from the row index of a delta related control to a list of control names.
References ASSERT, GetSegmentTypeWave, GetWaveBuilderWaveParam, GetWaveBuilderWaveTextParam, ROWS.
Referenced by WBP_AdjustDeltaControls.
static variable WBP_AdjustDeltaControls(string control)
Depending on the delta operation the visibility of related controls is adjusted.
control delta operation control name
References ASSERT, DELTA_OPERATION_ALTERNATE, DELTA_OPERATION_DEFAULT, DELTA_OPERATION_EXPLICIT, DELTA_OPERATION_FACTOR, DELTA_OPERATION_LOG, DELTA_OPERATION_POWER, DELTA_OPERATION_SQUARED, DisableControls, EnableControls, GetPopupMenuIndex, GetSegmentTypeWave, GetWaveBuilderWaveParam, panel, ROWS, WB_GetDeltaDimLabel, WBP_ConvertDeltaLblToCtrlNames, WBP_ExtractRowNumberFromControl, WBP_GetWaveTypeFromControl, WBP_WAVETYPE_SEGWVTYPE, WBP_WAVETYPE_WP.
Referenced by WBP_FinalTabHook, WBP_PopupMenu, WBP_StartupSettings.
variable WBP_ButtonProc_NewSeed(WMButtonAction *ba)
References GetReproducibleRandom, NewRandomSeed, WBP_UpdateControlAndWave, WBP_UpdatePanelIfAllowed.
variable WBP_PopupMenu_AnalysisFunctions(WMPopupAction *pa)
References WBP_AnaFuncsToWPT.
static variable WBP_AnaFuncsToWPT()
References CHANNEL_TYPE_TTL, GetPopupMenuString, GetWaveBuilderWaveTextParam, panel, WB_SetAnalysisFunctionGeneric, WBP_GetStimulusType, WBP_UpdateParameterWave.
Referenced by WBP_LoadSet, WBP_PopupMenu_AnalysisFunctions.
string WBP_GetAnalysisFunctions(variable versionBitMask)
Return a list of analysis functions including NONE, usable for popup menues.
AFM_GetAnalysisFunctions
References AFH_GetAnalysisFunctions, NONE.
Referenced by WBP_GetAnalysisFunctions_V3.
string WBP_GetNoiseTypes()
Return a list of noise types, usable for popup menues.
References NOISE_TYPES_STRINGS.
string WBP_GetNoiseBuildResolution()
Return a list of build resolutions , usable for popup menues.
Referenced by WB_MakeWaveBuilderWave.
variable WBP_ButtonProc_OpenAnaFuncs(WMButtonAction *ba)
References ControlWindowToFront, FileExists, GetFolder, GetPopupMenuString, NONE, panel, TP_GetNumDevicesWithTPRunning.
variable WBP_SetVarCombineEpochFormula(WMSetVariableAction *sva)
References EPOCH_TYPE_COMBINE, FormulaProperties::formula, GetSetVariable, GetWaveBuilderWaveTextParam, WAVEBUILDER_COMBINE_FORMULA_VER, WBP_TranslateControlContents, WBP_UpdatePanelIfAllowed.
static string WBP_TranslateControlContents(string control, variable direction, string data)
Convert a control entry for the panel or the wave.
Useful if the visualization is different from the stored data. control name of WaveBuilder GUI control direction one of FROM_PANEL_TO_WAVE or FROM_WAVE_TO_PANEL data string to convert
References FormulaProperties::formula, FROM_PANEL_TO_WAVE, FROM_WAVE_TO_PANEL, WB_FormulaSwitchToShorthand, WB_FormulaSwitchToStimset.
Referenced by WBP_ParameterWaveToPanel, WBP_SetVarCombineEpochFormula.
variable WBP_MainWindowHook(WMWinHookStruct *s)
Wavebuilder panel window hook.
The epoch selection is done on the mouseup event if there exists no marquee. This allows to still use the zooming capability.
References DP_DebuggingEnabledForCaller, GetControlCoordinates, GetEpochID, GetSegmentTypeWave, GetSetVariable, GetWaveBuilderDataPath, GetWaveBuilderWaveParam, GetWaveBuilderWaveTextParam, IsControlDisabled, IsInsideRect, KillOrMoveToTrash, panel, PGC_SetAndActivateControl, ROWS, WaveBuilderGraph, WBP_ExtractRowNumberFromControl, WBP_GetWaveTypeFromControl, WBP_WAVETYPE_SEGWVTYPE, WBP_WAVETYPE_WP, WBP_WAVETYPE_WPT.
string WBP_GetFFTSpectrumPanel()
References panel.
Referenced by WBP_ShowFFTSpectrumIfReq.
variable WBP_ShowFFTSpectrumIfReq(wave segmentWave, variable sweep)
References ASSERT, DEBUGPRINT, EPOCH_TYPE_NOISE, GetAxesRanges, GetCursorInfos, GetTabID, GetWaveBuilderDataPath, IsInteger, panel, RemoveTracesFromGraph, RestoreCursors, ROWS, SEGMENTWAVE_SPECTRUM_PREFIX, SetAxesRanges, WAVEBUILDER_MIN_SAMPINT, WBP_GetFFTSpectrumPanel, WBP_GetSweepColor, WindowExists.
Referenced by WB_MakeWaveBuilderWave.
static std::tuple< RGBColor > WBP_GetSweepColor(variable sweep)
Return distinct colors the sweeps of the wavebuilder.
These are backwards compared to the trace colors
References GetTraceColor.
Referenced by WBP_DisplaySetInPanel, WBP_ShowFFTSpectrumIfReq.
static variable WBP_DeleteAnalysisParameter(string name)
Delete the given analysis parameter.
name name of the parameter
References AFH_RemoveAnalysisParameter, GetWaveBuilderWaveTextParam, INDEP_EPOCH_TYPE.
Referenced by WBP_ButtonProc_DeleteParam.
string WBP_GetParameterTypes()
Return a list of all possible analysis parameter types.
References ANALYSIS_FUNCTION_PARAMS_TYPES.
static string WBP_GetAnalysisParameters()
Return the analysis parameters.
References GetWaveBuilderWaveTextParam, INDEP_EPOCH_TYPE.
Referenced by WBP_GetAnalysisParameterNames, WBP_ListBoxProc_AnalysisParams, WBP_UpdateParameterWave.
static string WBP_GetAnalysisGenericFunction()
References GetWaveBuilderWaveTextParam, INDEP_EPOCH_TYPE.
Referenced by WBP_UpdateParameterWave.
string WBP_GetAnalysisParameterNames()
Return the analysis parameter names for the currently selected stimset.
References AFH_GetListOfAnalysisParamNames, IsEmpty, NONE, WBP_GetAnalysisParameters.
static variable WBP_UpdateParameterWave()
Fill the listwave from the stimset analysis parameters extracted from its WPT.
References AFH_GetAnalysisParameter, AFH_GetAnalysisParamType, AFH_GetHelpForAnalysisParameter, AFH_GetListOfAnalysisParamNames, AFH_GetListOfAnalysisParams, GetListDifference, LineBreakingIntoPar, OPTIONAL_PARAMS, REQUIRED_PARAMS, ROWS, ToTrueFalse, WBP_GetAnalysisGenericFunction, WBP_GetAnalysisParameters, WBP_GetAnalysisParamGUIHelpWave, WBP_GetAnalysisParamGUIListWave, WBP_GetAnalysisParamGUISelWave.
Referenced by WBP_AnaFuncsToWPT, WBP_ButtonProc_AddParam, WBP_ButtonProc_DeleteParam, WBP_ToggleAnalysisParamGUI.
static variable WBP_ToggleAnalysisParamGUI()
Toggle the analysis parameter GUI.
one if the panel was killed, zero if it was created
References AnalysisParamGUI, WBP_GetAnalysisParamGUIHelpWave, WBP_GetAnalysisParamGUIListWave, WBP_GetAnalysisParamGUISelWave, WBP_UpdateParameterWave, WindowExists.
Referenced by WBP_ButtonProc_OpenAnaParamGUI.
variable WBP_ButtonProc_DeleteParam(WMButtonAction *ba)
References FindIndizes, LISTBOX_SELECTED, PROP_MATCHES_VAR_BIT_MASK, ROWS, WBP_DeleteAnalysisParameter, WBP_GetAnalysisParamGUIListWave, WBP_GetAnalysisParamGUISelWave, WBP_UpdateParameterWave.
variable WBP_ButtonProc_AddParam(WMButtonAction *ba)
References AFH_IsValidAnalysisParameter, ASSERT, ControlWindowToFront, GetNotebookText, GetPopupMenuString, GetSetVariableString, GetWaveBuilderWaveTextParam, IsEmpty, ListToNumericWave, SetSetVariableString, str2numSafe, WB_AddAnalysisParameterIntoWPT, WBP_UpdateParameterWave.
variable WBP_ButtonProc_OpenAnaParamGUI(WMButtonAction *ba)
References panel, SetControlTitle, WBP_ToggleAnalysisParamGUI.
variable WBP_ListBoxProc_AnalysisParams(WMListboxAction *lba)
References AFH_GetAnalysisParamNumerical, AFH_GetAnalysisParamTextual, AFH_GetAnalysisParamTextWave, AFH_GetAnalysisParamWave, ASSERT, IsEmpty, NumericWaveToList, ROWS, SetPopupMenuString, SetSetVariableString, TextWaveToList, WBP_GetAnalysisParameters.
variable WBP_ButtonProc_LoadSet(WMButtonAction *ba)
References GetPopupMenuString, panel, WBP_LoadSet.
string WBP_RegenerateEpochParameterNamesCode()
Function to regenerate code for GetEpochParameterNames()
References EPOCH_TYPES_TOTAL_NUMBER, GetCodeForWaveContents, WBP_ListControlsPerStimulusType.
static wave WBP_ListControlsPerStimulusType(variable epochType)
Return a list of all parameter names of the given epochType.
References ASSERT, EnsureLargeEnoughWave, EPOCH_TYPE_COMBINE, EPOCH_TYPE_CUSTOM, EPOCH_TYPE_SQUARE_PULSE, GetNumberFromWaveNote, GetUniqueEntries, GetWaveBuilderWaveParam, GetWaveBuilderWaveTextParam, HIDDEN_CONTROLS_CUSTOM_COMBINE, HIDDEN_CONTROLS_SQUARE_PULSE, IsFinite, IsNaN, MINIMUM_WAVE_SIZE, NOTE_INDEX, panel, ROWS, SEGWVTYPE_ALL_CONTROL_REGEXP, SetNumberInWaveNote, WBP_CreateWaveBuilderPanel, WBP_ExtractRowNumberFromControl, WP_CONTROL_REGEXP, WPT_CONTROL_REGEXP.
Referenced by WBP_RegenerateEpochParameterNamesCode.
string WBP_GetDeltaModes()
References WAVEBUILDER_DELTA_MODES.
string WBP_GetTriggerTypes()
References WAVEBUILDER_TRIGGER_TYPES.
string WBP_GetPulseTypes()
References PULSE_TYPES_STRINGS.