MIES_InputDialog.ipf
variable ID_AskUserForSettings(variable mode, string title, wave data, wave mock)
Shows a dialog and queries numeric values from the user.
We currently ask for NUM_HEADSTAGES headstage dependent entries and one independent value when mode = ID_HEADSTAGE_SETTINGS. All values must be numeric. For ID_POPUPMENU_SETTINGS the row dimension labels of data fill the popup menu, and on return data will have a 1 at the selected entry. mode One of AskUserSettingsModeFlag title dialog title data 1D numeric wave, which must be permanent and in an otherwise empty folder mock This is mock data for testing which is written into data when GetInteractiveMode() is false 0 on success, 1 if the user cancelled the dialog
References ASSERT, DisableControl, GetCurrentWindow, GetInteractiveMode, ID_GetControl, ID_HEADSTAGE_SETTINGS, ID_POPUPMENU_SETTINGS, ID_SetTitle, IsFreeWave, IsNaN, LABNOTEBOOK_LAYER_COUNT, PGC_SetAndActivateControl, ROVar, ROWS, SetSetVariable.
Referenced by DND_ChooseAsset, ReachTargetVoltage.
static variable ID_SetTitle(string win, string title)
Referenced by ID_AskUserForSettings.
static string ID_GetControl(variable index)
References NUM_HEADSTAGES.
Referenced by ID_AskUserForSettings.
static dfref ID_GetFolder(string win)
References ASSERT, DataFolderExistsDFR.
Referenced by ID_ButtonProc, ID_GetWave.
static wave ID_GetWave(string win)
References ASSERT, GetListOfObjects, ID_GetFolder, ROWS.
Referenced by ID_GetPopupEntries, ID_PopMenuProc, ID_SetVarProc.
variable ID_ButtonProc(WMButtonAction *ba)
References ASSERT, ID_GetFolder.
variable ID_SetVarProc(WMSetVariableAction *sva)
References ASSERT, ID_GetWave, IsFinite.
variable ID_PopMenuProc(WMPopupAction *pa)
References ID_GetWave.
string ID_GetPopupEntries()
References GetCurrentWindow, ID_GetWave, ROWS, TextWaveToList.
void ID_Headstage_Panel()
void ID_Popup_Panel()