MIES_Labnotebook.ipf
variable LBN_SetDimensionLabels(WaveText keys, wave values, variable start=defaultValue)
Set column dimension labels from the first row of the key wave.
References ASSERT, COLS, isEmpty, IsInteger, MAX_OBJECT_NAME_LENGTH_IN_BYTES, ROWS.
Referenced by AB_updateLabelsInLabNotebook, ED_FindIndizesAndRedimension, UpgradeLabNotebook.
std::tuple< variable, string, variable > LBN_GetEntryProperties(WaveTextOrNull keyWave, string key)
Queries the unit and column from the key wave.
keyWave labnotebook key wave key key to look for result one on error, zero otherwise unit unit of the result [empty if not found] col column of the result into the keyWave [NaN if not found]
References ROWS.
Referenced by LBV_GetPropertiesForLabnotebookEntry, NWB_AddSweepDataSets, PSQ_AddLabnotebookEntriesToJSON.