LabnotebookQueryFunctions
variable GetLastSettingIndep(wave numericalValues, variable sweepNo, string setting, variable entrySourceType, variable defValue=defaultValue)
Return a headstage independent setting from the numerical labnotebook.
the headstage independent setting or defValue GetLastSetting()
References EnforceIndependentSetting, GetIndexForHeadstageIndepData, GetLastSetting.
Referenced by AD_FillWaves, AD_GetBaselineFailMsg, AD_GetPerSweepFailMessage, AFH_GetSweepsFromSameRACycleNC, CreateTiledChannelGraph, GetLastSettingIndepEachRAC, GetLastSettingIndepEachSCI, GetSamplingIntervalFromLBN, GetTotalOnsetDelay, LBV_LimitXRangeToSelected, MSQ_NumPassesInSet, NWB_AppendSweepLowLevel, NWB_GenerateDeviceDescription, PA_DiffPulseInfos, PSQ_Chirp, PSQ_EvaluateBaselineProperties, PSQ_GetLastPassingDAScaleSub, PSQ_GetLastPassingLongRHSweep, PSQ_NumPassesInSet, PSQ_PipetteInBath, PSQ_Rheobase, RA_DocumentSweepSkipping.
string GetLastSettingTextIndep(WaveText textualValues, variable sweepNo, string setting, variable entrySourceType, string defValue=defaultValue)
Return a headstage independent setting from the textual labnotebook.
the headstage independent setting or defValue GetLastSetting()
References ASSERT_TS, EnforceIndependentSetting, GetIndexForHeadstageIndepData, GetLastSetting, IsTextWave.
Referenced by DAP_CheckSettings, GetLastSettingTextIndepEachRAC, GetLastSettingTextIndepEachSCI, NWB_GenerateDeviceDescription, NWB_GetStartTimeOfSweep, PSQ_PipetteInBath.
variable GetLastSettingIndepRAC(wave numericalValues, variable sweepNo, string setting, variable entrySourceType, variable defValue=defaultValue)
Return a headstage independent setting from the numerical labnotebook of the sweeps in the same RA cycle.
the headstage independent setting or defValue GetLastSetting()
References EnforceIndependentSetting, GetIndexForHeadstageIndepData, GetLastSettingRAC.
variable GetLastSettingIndepSCI(wave numericalValues, variable sweepNo, string setting, variable headstage, variable entrySourceType, variable defValue=defaultValue)
Return a headstage independent setting from the numerical labnotebook of the sweeps in the same RA cycle.
the headstage independent setting or defValue GetLastSetting()
References EnforceIndependentSetting, GetIndexForHeadstageIndepData, GetLastSettingSCI.
Referenced by AD_FillWaves, AD_GetPerSweepFailMessage, AD_GetResultMessage, AD_GetSquarePulseFailMsg, IVS_GetSetQCForSweep, PSQ_Chirp, PSQ_Rheobase, PSQ_SquarePulse, SC_SpikeControl, SC_SpontaneousSpikingCheckQC.
string GetLastSettingTextIndepRAC(wave numericalValues, WaveText textualValues, variable sweepNo, string setting, variable entrySourceType, string defValue=defaultValue)
Return a headstage independent setting from the numerical labnotebook of the sweeps in the same RA cycle.
the headstage independent setting or defValue
References EnforceIndependentSetting, GetIndexForHeadstageIndepData, GetLastSettingTextRAC.
std::tuple< WaveOrNull, variable > GetLastSettingChannel(wave numericalValues, WaveTextOrNull textualValues, variable sweepNo, string setting, variable channelNumber, variable channelType, variable entrySourceType)
Return a numerical or text setting for the given channel.
It also returns headstage independent entries when the given channel refers to an active channel. the wave containing the setting and the index into it. GetLastSettingChannelInternal()
References GetLastSettingChannelInternal.
Referenced by AddChannelUnitFromLBN, AddDAQChannelTypeFromLBN, EP_GetEpochs, GetActiveChannels, GetHeadstageForChannel, NWB_FetchEpochs.
wave GetLastSetting(wave values, variable sweepNo, string setting, variable entrySourceType)
Return a numeric/textual wave with the latest value of a setting from the numerical/labnotebook labnotebook for the given sweep number.
values numerical/textual labnotebook sweepNo sweep number setting name of the setting to query entrySourceType type of the labnotebook entry, one of DataAcqModes. If you don't care about the entry source type pass UNKNOWN_MODE. a free wave with LABNOTEBOOK_LAYER_COUNT rows. In case the setting could not be found an invalid wave reference is returned.
References ASSERT_TS, COLS, EnsureLargeEnoughWave, EntrySourceTypeMapper, GetLastSettingNoCache, GetLBIndexCache, GetLBRowCache, IsNaN, IsTextWave, IsValidSweepNumber, LABNOTEBOOK_GET_RANGE, LABNOTEBOOK_MISSING_VALUE, LABNOTEBOOK_UNCACHED_VALUE, LAYERS, NUMBER_OF_LBN_DAQ_MODES, ROWS.
Referenced by AB_FillListWave, AB_GetSettingNumFiniteVals, AD_FillWaves, AD_GetBaselineChunkFailMsg, AD_GetBaselineFailMsg, AD_GetPerSweepFailMessage, AD_PlotBounds, AFH_GetSweepsFromSameSCINC, AR_ComputeRanges, BSP_RemoveDisabledChannels, CalculateTPLikePropsFromSweep, CreateTiledChannelGraph, ED_WriteChangedValuesToNote, ED_WriteChangedValuesToNoteText, FitResistance, GetLastSettingChannelInternal, GetLastSettingEachRAC, GetLastSettingEachSCI, GetLastSettingIndep, GetLastSettingRAC, GetLastSettingSCI, GetLastSettingTextEachRAC, GetLastSettingTextEachSCI, GetLastSettingTextIndep, GetLastSettingTextRAC, GetLastSettingTextSCI, GetTTLBits, GetTTLChannels, GetTTLChannelsOrBits, GetTTLLabnotebookEntry, IVS_GetSetQCForSweep, LastStimSetRun, LBV_AddTraceToLBGraphTPStorage, MSQ_FastRheoEst, MSQ_GetPulseDurations, NWB_AddSweepDataSets, NWB_AppendSweepLowLevel, NWB_GetStimsetFromSweepGeneric, NWB_GetTimeSeriesProperties, OVS_UpdateSweepSelectionChoices, PA_GetPulseInfos, PSQ_Chirp, PSQ_CR_DetermineBoundsAction, PSQ_CR_GetCycles, PSQ_DAScale, PSQ_DS_GetDAScaleOffset, PSQ_FoundAtLeastOneSpike, PSQ_GetLastPassingLongRHSweep, PSQ_GetPulseDurations, PSQ_PipetteInBath, PSQ_Ramp, PSQ_Rheobase, PSQ_SquarePulse, ReachTargetVoltage, SB_GetSweepPropertyFromNumLBN, SBE_AddMissingADTraceInfo, SBE_ExportSweepBrowser, SC_GetHeadstageQCForSetCount, SC_GetSetSweepCount, SC_GetTrials, SC_LastSweepInSet, SC_ReactToQCFailures, SC_SpontaneousSpikingCheckQC, WB_OpenStimulusSetInWaveBuilder.
wave GetLastSettingNoCache(wave values, variable sweepNo, string setting, variable entrySourceType, variable *first=defaultValue, variable *last=defaultValue, variable *rowIndex=defaultValue)
Return a wave with the latest value of a setting from the numerical/textual labnotebook for the given sweep number. Uncached version, general users should prefer GetLastSetting().
values numerical/textual labnotebook sweepNo sweep number setting name of the setting to query entrySourceType type of the labnotebook entry, one of DataAcqModes first [optional] Can be used to query and return the labnotebook row range. Useful for routines which must make a lot of queries to the same sweep and want to avoid the overhead of calculating first and last. Passing LABNOTEBOOK_GET_RANGE will set the calculated values of first and last after the function returns. Passing a value greater or equal zero will use these values instead. last [optional] see first rowIndex [optional] return the row where the setting could be found, otherwise it is set to LABNOTEBOOK_MISSING_VALUE a free wave with LABNOTEBOOK_LAYER_COUNT rows. In case the setting could not be found an invalid wave reference is returned.
References ASSERT_TS, COLS, DATA_ACQUISITION_MODE, DEBUGPRINT_TS, FindRange, GET_LB_MODE_NONE, GET_LB_MODE_READ, GET_LB_MODE_WRITE, GetSweepColumn, HasOneValidEntry, IsFinite, IsTextWave, LABNOTEBOOK_GET_RANGE, LABNOTEBOOK_MISSING_VALUE, LAYERS, TEST_PULSE_MODE, UNKNOWN_MODE.
Referenced by GetLastSetting.
wave GetLastSettingTextRAC(wave numericalValues, WaveText textualValues, variable sweepNo, string setting, variable entrySourceType)
Return the last textual value of the sweeps in the same RA cycle.
GetLastSetting()
References AFH_GetSweepsFromSameRACycle, GetLastSetting, ROWS.
Referenced by GetLastSettingTextIndepRAC.
wave GetLastSettingRAC(wave numericalValues, variable sweepNo, string setting, variable entrySourceType)
Return the last numerical value of the sweeps in the same RA cycle.
GetLastSetting()
References AFH_GetSweepsFromSameRACycle, GetLastSetting, ROWS.
Referenced by GetLastSettingIndepRAC.
wave GetLastSettingIndepEachRAC(wave numericalValues, variable sweepNo, string setting, variable entrySourceType, variable defValue=defaultValue)
Return the last numerical value for the given setting of each sweep in the same RA cycle.
The returned wave will have NaN for sweeps which do not have that entry. This is done in order to keep the indizes intact. GetLastSetting()
References AFH_GetSweepsFromSameRACycle, GetLastSettingIndep, HasOneValidEntry, ROWS.
wave GetLastSettingTextIndepEachRAC(wave numericalValues, WaveText textualValues, variable sweepNo, string setting, variable entrySourceType, string defValue=defaultValue)
Return the last textual value for the given setting of each sweep in the same RA cycle.
The returned wave will have NaN for sweeps which do not have that entry. This is done in order to keep the indizes intact. GetLastSetting()
References AFH_GetSweepsFromSameRACycle, GetLastSettingTextIndep, ROWS.
wave GetLastSettingEachRAC(wave numericalValues, variable sweepNo, string setting, variable headstage, variable entrySourceType)
Return the last numerical value for the given setting of each sweep for a given headstage in the same RA cycle.
The returned wave will have NaN for sweeps which do not have that entry. This is done in order to keep the indizes intact. GetLastSetting
References AFH_GetSweepsFromSameRACycle, ASSERT_TS, GetLastSetting, HasOneValidEntry, NUM_HEADSTAGES, ROWS.
wave GetLastSettingTextEachRAC(wave numericalValues, WaveText textualValues, variable sweepNo, string setting, variable headstage, variable entrySourceType)
Return the last textual value for the given setting of each sweep for a given headstage in the same RA cycle.
The returned wave will have NaN for sweeps which do not have that entry. This is done in order to keep the indizes intact. GetLastSetting()
References AFH_GetSweepsFromSameRACycle, ASSERT_TS, GetLastSetting, NUM_HEADSTAGES, ROWS.
Referenced by SC_ReactToQCFailures.
wave GetLastSettingTextSCI(wave numericalValues, WaveText textualValues, variable sweepNo, string setting, variable headstage, variable entrySourceType)
Return the last textual value of the sweeps in the same stimset cycle.
GetLastSetting()
References AFH_GetSweepsFromSameSCI, GetLastSetting, ROWS.
Referenced by AD_GetDAScaleFailMsg, PSQ_GetLastPassingDAScaleSub.
wave GetLastSettingSCI(wave numericalValues, variable sweepNo, string setting, variable headstage, variable entrySourceType)
Return the last numerical value of the sweeps in the same stimset cycle.
GetLastSetting()
References AFH_GetSweepsFromSameSCI, GetLastSetting, ROWS.
Referenced by AD_GetSquarePulseFailMsg, GetLastSettingIndepSCI, MSQ_DAScale, MSQ_FastRheoEst, MSQ_GetLastPassingLongRHSweep, MSQ_GetPulseDurations, PSQ_GetLastPassingLongRHSweep, PSQ_Rheobase, ReachTargetVoltage.
wave GetLastSettingIndepEachSCI(wave numericalValues, variable sweepNo, string setting, variable headstage, variable entrySourceType, variable defValue=defaultValue)
Return the last numerical value for the given setting of each sweep in the same stimset cycle.
The returned wave will have NaN for sweeps which do not have that entry. This is done in order to keep the indizes intact. GetLastSetting()
References AFH_GetSweepsFromSameSCI, GetLastSettingIndep, HasOneValidEntry, ROWS.
Referenced by AD_FillWaves, AD_GetChirpFailMsg, AD_GetDAScaleFailMsg, AD_GetPerSweepFailMessage, AD_GetSquarePulseFailMsg, PSQ_AddLabnotebookEntriesToJSON, PSQ_CR_SetHasPassed, PSQ_DAScale, PSQ_SquarePulse.
wave GetLastSettingTextIndepEachSCI(wave numericalValues, WaveText textualValues, variable sweepNo, variable headstage, string setting, variable entrySourceType, string defValue=defaultValue)
Return the last textual value for the given setting of each sweep in the same stimset cycle.
The returned wave will have NaN for sweeps which do not have that entry. This is done in order to keep the indizes intact. GetLastSetting()
References AFH_GetSweepsFromSameSCI, GetLastSettingTextIndep, ROWS.
wave GetLastSettingEachSCI(wave numericalValues, variable sweepNo, string setting, variable headstage, variable entrySourceType)
Return the last numerical value for the given setting of each sweep for a given headstage in the same stimset cycle.
The returned wave will have NaN for sweeps which do not have that entry. This is done in order to keep the indizes intact. GetLastSetting
References AFH_GetSweepsFromSameSCI, ASSERT_TS, GetLastSetting, HasOneValidEntry, NUM_HEADSTAGES, ROWS.
Referenced by AD_FillWaves, AD_GetChirpFailMsg, AD_GetDAScaleFailMsg, AD_GetFastRheoEstFailMsg, AD_GetRheobaseFailMsg, AD_GetSpikeControlFailMsg, MSQ_FastRheoEst, MSQ_GetLBNEntryForHeadstageSCI, MSQ_GetLBNEntryForHSSCIBool, PSQ_AddLabnotebookEntriesToJSON, PSQ_CR_SetHasPassed, PSQ_DAScale, PSQ_Rheobase, SC_GetTrials.
wave GetLastSettingTextEachSCI(wave numericalValues, WaveText textualValues, variable sweepNo, string setting, variable headstage, variable entrySourceType)
Return the last textual value for the given setting of each sweep for a given headstage in the same stimset cycle.
The returned wave will have NaN for sweeps which do not have that entry. This is done in order to keep the indizes intact. GetLastSetting()
References AFH_GetSweepsFromSameSCI, ASSERT_TS, GetLastSetting, NUM_HEADSTAGES, ROWS.
wave GetSweepsWithSetting(wave labnotebookValues, string setting)
Return a wave with all sweep numbers which have a non-empty entry for setting.
labnotebookValues numerical/textual labnotebook setting name of the value to search a 1D free wave with the matching sweep numbers. In case the setting could not be found an invalid wave reference is returned.
References GetNonEmptyLBNRows, GetSweepColumn, GetUniqueEntries, IsTextWave, ROWS, ZapNaNs.
Referenced by MSQ_GetLastPassingLongRHSweep, NWB_CheckForMissingSweeps, PSQ_GetLastPassingDAScaleSub, PSQ_GetLastPassingLongRHSweep, RecreateMissingSweepAndConfigWaves, SWS_DeleteDataWaves.
wave GetLastSweepWithSetting(wave numericalValues, string setting, variable *sweepNo)
Return the last numerical value of a setting from the labnotebook and the sweep it was set.
numericalValues numerical labnotebook setting name of the value to search sweepNo sweep number the value was last set a free wave with LABNOTEBOOK_LAYER_COUNT rows. In case the setting could not be found an invalid wave reference is returned.
References ASSERT_TS, GetNonEmptyLBNRows, GetSweepColumn, IsNumericWave, LAYERS, ROWS.
Referenced by GetLastSweepWithSettingIndep, GetLBIndexCache, GetLBRowCache, PA_GenerateAllPulseWaves.
variable GetLastSweepWithSettingIndep(wave numericalValues, string setting, variable *sweepNo, variable defValue=defaultValue)
Return the last numerical value of a headstage independent setting from the labnotebook and the sweep it was set.
numericalValues numerical labnotebook setting name of the value to search sweepNo sweep number the value was last set defValue [optional, defaults to NaN] value to return in case nothing could be found
References EnforceIndependentSetting, GetIndexForHeadstageIndepData, GetLastSweepWithSetting.
Referenced by DAP_CheckSettings, PSQ_Rheobase.
wave GetLastSweepWithSettingText(WaveText textualValues, string setting, variable *sweepNo)
Return the last textual value of a setting from the labnotebook and the sweep it was set.
textualValues textual labnotebook setting name of the value to search sweepNo sweep number the value was last set a free wave with LABNOTEBOOK_LAYER_COUNT rows. In case the setting could not be found an invalid wave reference is returned.
References ASSERT_TS, GetNonEmptyLBNRows, GetSweepColumn, IsTextWave, LAYERS, ROWS.
Referenced by GetLastSweepWithSettingTextI, GetLBIndexCache, GetLBRowCache.
string GetLastSweepWithSettingTextI(wave numericalValues, string setting, variable *sweepNo, string defValue=defaultValue)
Return the last textual value of a headstage independent setting from the labnotebook and the sweep it was set.
numericalValues numerical labnotebook setting name of the value to search sweepNo sweep number the value was last set defValue [optional, defaults to an empty string] value to return in case nothing could be found
References EnforceIndependentSetting, GetIndexForHeadstageIndepData, GetLastSweepWithSettingText.