WaveVersioningSupport
static variable ExistsWithCorrectLayoutVersion(WaveOrNull wv, variable versionOfNewWave)
Check if wv exists and has the correct version UTF_NOINSTRUMENTATION.
References GetWaveVersion.
Referenced by GetAcqStateTracking, GetActiveDevicesTPMD, GetAmplifierParamStorageWave, GetAnaFuncDashboardColorWave, GetAnaFuncDashboardHelpWave, GetAnaFuncDashboardInfoWave, GetAnaFuncDashboardListWave, GetAnaFuncDashboardSelWave, GetAnalysisBrowserMap, GetAnalysisChannelStorage, GetAnalysisFuncDAScaleDeltaI, GetAnalysisFuncDAScaleDeltaV, GetAnalysisFuncDAScaleFreqFit, GetAnalysisFuncDAScaleRes, GetAnalysisFuncDAScaleResFit, GetAnalysisFuncDAScales, GetAnalysisFuncDAScaleSpikeFreq, GetAnalysisFuncIndexingHelper, GetAnalysisFunctionStorage, GetArtefactRemovalDataWave, GetArtefactRemovalListWave, GetCacheStatsWave, GetCellElectrodeNames, GetChanAmpAssign, GetChanAmpAssignUnit, GetChannelClampMode, GetChannelSelectionWave, GetDA_EphysGuiStateNum, GetDA_EphysGuiStateTxT, GetDAQConfigWave, GetDebugPanelListSelWave, GetDebugPanelListWave, GetDeviceInfoWave, GetDeviceMapping, GetDQMActiveDeviceList, GetElapsedTimeWave, GetEpochsWave, GetExperimentBrowserGUIList, GetExperimentBrowserGUISel, GetGraphUserData, GetHSProperties, GetIndexingStorageWave, GetLBIndexCache, GetLBNidCache, GetLBNumericalKeys, GetLBRowCache, GetLBTextualKeys, GetNumericalResultsKeys, GetOverlaySweepHeadstageRemoval, GetOverlaySweepSelectionChoices, GetOverlaySweepsListSelWave, GetOverlaySweepsListWave, GetPAGraphData, GetPopupExtMenuWave, GetPulseAverageDisplayMapping, GetPulseAverageProperties, GetPulseAveragePropertiesWaves, GetPulseAverageSetImageWave, GetPulseAverageSetIndizes, GetPulseAverageWave, GetPulseAverageWaveNoteWave, GetRAPerfWave, GetSetEventFlag, GetSweepBrowserMap, GetSweepSettingsKeyWave, GetSweepSettingsTextKeyWave, GetSweepSettingsTextWave, GetSweepSettingsWave, GetTextualResultsKeys, GetTPResultAsyncBuffer, GetTPResults, GetTPResultsBuffer, GetTPSettings, GetTPSettingsCalculated, GetTPSettingsLabnotebook, GetTPSettingsLabnotebookKeyWave, GetTPStorage, GetValidAcqStateTransitions, P_GetPressureDataWaveRef, P_PressureDataTxtWaveRef, UpgradeSegWvType, UpgradeWaveParam, UpgradeWaveTextParam, WBP_GetAnalysisParamGUIHelpWave, WBP_GetAnalysisParamGUIListWave, WBP_GetAnalysisParamGUISelWave.
static variable WaveVersionIsAtLeast(WaveOrNull wv, variable existingVersion)
Check if the given wave's version is equal or larger than the given version, if version is not set false is returned.
References ASSERT_TS, GetWaveVersion, IsValidWaveVersion.
Referenced by GetCacheStatsWave.
static variable WaveVersionIsSmaller(WaveOrNull wv, variable existingVersion)
Check if the given wave's version is smaller than the given version, if version is not set true is returned.
References ASSERT_TS, GetWaveVersion, IsValidWaveVersion.
Referenced by GetDAQConfigWave, GetDQMActiveDeviceList, GetTPStorage, UpgradeLabNotebook, UpgradeWaveParam, UpgradeWaveTextParam.
variable GetWaveVersion(WaveOrNull wv)
return the Version of the Wave, returns NaN if no version was set UTF_NOINSTRUMENTATION
References GetNumberFromWaveNote, WAVE_NOTE_LAYOUT_KEY.
Referenced by ClearWaveNoteExceptWaveVersion, ExistsWithCorrectLayoutVersion, IsValidConfigWave, RecreateConfigWaveFromLBN, WaveVersionIsAtLeast, WaveVersionIsSmaller.
static variable SetWaveVersion(wave wv, variable val)
Set the wave layout version of wave.
References ASSERT_TS, IsValidWaveVersion, SetNumberInWaveNote, WAVE_NOTE_LAYOUT_KEY.
Referenced by ClearWaveNoteExceptWaveVersion, GetAcqStateTracking, GetActiveDevicesTPMD, GetAmplifierParamStorageWave, GetAnaFuncDashboardColorWave, GetAnaFuncDashboardHelpWave, GetAnaFuncDashboardInfoWave, GetAnaFuncDashboardListWave, GetAnaFuncDashboardSelWave, GetAnalysisBrowserMap, GetAnalysisChannelStorage, GetAnalysisFuncDAScaleDeltaI, GetAnalysisFuncDAScaleDeltaV, GetAnalysisFuncDAScaleFreqFit, GetAnalysisFuncDAScaleRes, GetAnalysisFuncDAScaleResFit, GetAnalysisFuncDAScales, GetAnalysisFuncDAScaleSpikeFreq, GetAnalysisFunctionStorage, GetArtefactRemovalDataWave, GetArtefactRemovalListWave, GetCacheStatsWave, GetCellElectrodeNames, GetChanAmpAssign, GetChanAmpAssignUnit, GetChannelClampMode, GetChannelSelectionWave, GetDA_EphysGuiStateNum, GetDA_EphysGuiStateTxT, GetDAQConfigWave, GetDeviceInfoWave, GetDeviceMapping, GetDQMActiveDeviceList, GetElapsedTimeWave, GetEpochsWave, GetExperimentBrowserGUIList, GetExperimentBrowserGUISel, GetGraphUserData, GetHSProperties, GetIndexingStorageWave, GetLBIndexCache, GetLBNidCache, GetLBNumericalKeys, GetLBRowCache, GetLBTextualKeys, GetNumericalResultsKeys, GetOverlaySweepHeadstageRemoval, GetOverlaySweepSelectionChoices, GetOverlaySweepsListSelWave, GetOverlaySweepsListWave, GetPAGraphData, GetPopupExtMenuWave, GetPulseAverageDisplayMapping, GetPulseAverageProperties, GetPulseAveragePropertiesWaves, GetPulseAverageSetImageWave, GetPulseAverageSetIndizes, GetPulseAverageWave, GetPulseAverageWaveNoteWave, GetRAPerfWave, GetSegmentTypeWaveAsFree, GetSetEventFlag, GetSweepSettingsKeyWave, GetSweepSettingsTextKeyWave, GetSweepSettingsTextWave, GetSweepSettingsWave, GetTextualResultsKeys, GetTPResultAsyncBuffer, GetTPResults, GetTPResultsBuffer, GetTPSettings, GetTPSettingsLabnotebook, GetTPStorage, GetValidAcqStateTransitions, GetWaveBuilderWaveParamAsFree, GetWaveBuilderWaveTextParamAsFree, P_GetPressureDataWaveRef, P_PressureDataTxtWaveRef, SaveLBNumericalDescription, UpgradeSegWvType, UpgradeWaveParam, UpgradeWaveTextParam, WBP_GetAnalysisParamGUIHelpWave, WBP_GetAnalysisParamGUIListWave, WBP_GetAnalysisParamGUISelWave.
static variable IsValidWaveVersion(variable value)
A valid wave version is a positive non-zero integer.
References IsInteger.
Referenced by ClearWaveNoteExceptWaveVersion, SetWaveVersion, WaveVersionIsAtLeast, WaveVersionIsSmaller.
variable ClearWaveNoteExceptWaveVersion(wave wv)
Clear the wave note but keep any valid wave version.
References GetWaveVersion, IsValidWaveVersion, SetWaveVersion.
Referenced by PA_CreateAndFillPulseWaveIfReq.
dfref UpgradeDataFolderLocation(string oldFolder, string newFolder)
Move/Rename a datafolder across different locations.
Both parameters must be absolute datafolder locations. Cases where both exist are also handled gracefully. embed:rst:leading-asterisk * .. code-block:: igorpro * * Function/DF GetMyFolder() * return UpgradeDataFolderLocation("root:old", "root:new") * End * DFREF to the newFolder with the contents of oldFolder
References ASSERT_TS, createDFWithAllParents, DEBUGPRINT_TS, IsEmpty, IsValidObjectName, KillOrMoveToTrash, UniqueDataFolderName.
Referenced by GetDAQDevicesFolder.
wave UpgradeWaveLocationAndGetIt(WaveLocationMod *p)
Rename/Move a wave to a new location.
Valid transformations (and all combinations of them): Moving into a new datafolder Renaming to a new name Nothing The function is idempotent (i.e. it can be called also on already relocated waves). Cases where new == old are also handled gracefully. embed:rst:leading-asterisk * .. code-block:: igorpro * * Function/WAVE GetMyWave(device) * string device * * variable versionOfNewWave = 1 * string newName = "newAndNiceName" * DFREF newDFR = GetNewAndFancyFolder(device) * * STRUCT WaveLocationMod p * p.dfr = $(GetSomeFolder(device) + ":oldSubFolder") * p.newDFR = newDFR * p.name = "oldAndUglyName" * p.newName = newName * * WAVE/Z wv = UpgradeWaveLocationAndGetIt(p) * * if(ExistsWithCorrectLayoutVersion(wv, versionOfNewWave)) * return wv * elseif(WaveExists(wv)) * // handle upgrade * else * Make/R/N=(10, 2) newDFR:newName/Wave=wv * end * * SetWaveVersion(wv, versionOfNewWave) * * return wv * End * wave reference to the wave in the new location, an invalid one if the wave does not exist at the specified former location
References ASSERT, DataFolderExistsDFR, WaveLocationMod::dfr, IsValidObjectName, WaveLocationMod::name, WaveLocationMod::newDFR, WaveLocationMod::newName, RemoveEmptyDataFolder.
Referenced by GetAmplifierParamStorageWave, GetAnalysisBrowserMap, GetAnalysLBNumericalKeys, GetAnalysLBNumericalValues, GetAnalysLBTextualKeys, GetAnalysLBTextualValues, GetLBNumericalKeys, GetLBNumericalValues, GetLBTextualKeys, GetLBTextualValues, GetOverlaySweepSelectionChoices, GetSweepSettingsKeyWave, GetSweepSettingsTextKeyWave, GetSweepSettingsTextWave, GetSweepSettingsWave.