AnalysisFunctionParameterHelpers
string AFH_GetListOfAnalysisParamNames(string params)
Return a semicolon separated list of user parameters.
params serialized parameters, usually just AnalysisFunction_V3.params
Referenced by AFH_CheckAnalysisParameter, AFH_GetAnalysisParamNumerical, AFH_GetAnalysisParamTextual, AFH_GetAnalysisParamTextWave, AFH_GetAnalysisParamWave, DAP_CheckAnalysisFunctionAndParameter, SetControlInEvent, TestAnalysisFunction_V3, UpgradeWaveTextParam, WB_AddAnalysisParameterIntoWPT, WBP_GetAnalysisParameterNames, WBP_UpdateParameterWave.
string AFH_GetAnalysisParamType(string name, string params, variable typeCheck=defaultValue, string expectedType=defaultValue)
Return the type of the user parameter.
name parameter name params serialized parameters, usually just AnalysisFunction_V3.params typeCheck [optional, defaults to true] Check with an assertion that the readout type is one of ANALYSIS_FUNCTION_PARAMS_TYPES expectedType [optional, defaults to nothing] Expected type, one of ANALYSIS_FUNCTION_PARAMS_TYPES, aborts if the type does not match. Implies typeCheck = true. one of AnalysisFunctionParameterTypes or an empty string
References AFH_IsValidAnalysisParamType, ASSERT, IsEmpty.
Referenced by AFH_GetAnalysisParameter, DAP_CheckAnalysisFunctionAndParameter, SetControlInEvent, TestAnalysisFunction_V3, UpgradeWaveTextParam, WBP_UpdateParameterWave.
variable AFH_GetAnalysisParamNumerical(string name, string params, variable defValue=defaultValue)
Return a numerical user parameter.
name parameter name params serialized parameters, usually just AnalysisFunction_V3.params defValue [optional, defaults to NaN] return this value if the parameter could not be found
References AFH_GetAnalysisParameter, AFH_GetListOfAnalysisParamNames, AFH_IsValidAnalysisParameter, ASSERT.
Referenced by AD_GetDAScaleFailMsg, AD_PlotBounds, MSQ_FastRheoEst, MSQ_FastRheoEst_CheckParam, PSQ_CheckParamCommon, PSQ_CheckSamplingFrequencyAndStoreInLabnotebook, PSQ_Chirp, PSQ_Chirp_CheckParam, PSQ_DAScale, PSQ_DAScale_CheckParam, PSQ_EvaluateBaselineProperties, PSQ_GetBaselineRMSThresholds, PSQ_PipetteInBath, PSQ_PipetteInBath_CheckParam, PSQ_Ramp, PSQ_Ramp_CheckParam, PSQ_Rheobase, PSQ_SquarePulse, ReachTargetVoltage, ReachTargetVoltage_CheckParam, SC_CanStillSkip, SC_ReactToQCFailures, SC_SkipsExhausted, SC_SpikeControl, SC_SpikeControl_CheckParam, UpgradeWaveTextParam, WBP_ListBoxProc_AnalysisParams.
string AFH_GetAnalysisParamTextual(string name, string params, string defValue=defaultValue, variable percentDecoded=defaultValue)
Return a textual user parameter.
name parameter name params serialized parameters, usually just AnalysisFunction_V3.params defValue [optional, defaults to an empty string] return this value if the parameter could not be found percentDecoded [optional, defaults to true] if the return value should be percent decoded or not.
References AFH_GetAnalysisParameter, AFH_GetListOfAnalysisParamNames, AFH_IsValidAnalysisParameter, ASSERT.
Referenced by PSQ_Chirp, PSQ_Chirp_CheckParam, PSQ_DAScale, PSQ_DAScale_CheckParam, PSQ_PipetteInBath, PSQ_PipetteInBath_CheckParam, ReachTargetVoltage, ReachTargetVoltage_CheckParam, SC_ReactToQCFailures, SC_SpikeControl_CheckParam, TestAnalysisFunction_V3, UpgradeWaveTextParam, WBP_ListBoxProc_AnalysisParams.
wave AFH_GetAnalysisParamWave(string name, string params, wave defValue=defaultValue)
Return a numerical wave user parameter.
name parameter name params serialized parameters, usually just AnalysisFunction_V3.params defValue [optional, defaults to an invalid wave ref] return this value if the parameter could not be found wave reference to free numeric wave, or invalid wave ref in case the parameter could not be found.
References AFH_GetAnalysisParameter, AFH_GetListOfAnalysisParamNames, AFH_IsValidAnalysisParameter, ASSERT, ListToNumericWave.
Referenced by AD_GetDAScaleFailMsg, DAP_CheckAnalysisFunctionAndParameter, MSQ_DAScale, MSQ_DAScale_CheckParam, PSQ_DAScale, PSQ_DAScale_CheckParam, TestAnalysisFunction_V3, UpgradeWaveTextParam, WBP_ListBoxProc_AnalysisParams.
wave AFH_GetAnalysisParamTextWave(string name, string params, WaveText defValue=defaultValue, variable percentDecoded=defaultValue)
Return a textual wave user parameter.
name parameter name params serialized parameters, usually just AnalysisFunction_V3.params defValue [optional, defaults to an invalid wave ref] return this value if the parameter could not be found percentDecoded [optional, defaults to true] if the return value should be percent decoded or not. wave reference to free text wave, or invalid wave ref in case the parameter could not be found.
References AFH_GetAnalysisParameter, AFH_GetListOfAnalysisParamNames, AFH_IsValidAnalysisParameter, ASSERT.
Referenced by DAP_CheckAnalysisFunctionAndParameter, SetControlInEvent, TestAnalysisFunction_V3, UpgradeWaveTextParam, WBP_ListBoxProc_AnalysisParams.
variable AFH_IsValidAnalysisParameter(string name)
Check if the given name is a valid user parameter name.
References IsValidObjectName.
Referenced by AFH_GetAnalysisParamNumerical, AFH_GetAnalysisParamTextual, AFH_GetAnalysisParamTextWave, AFH_GetAnalysisParamWave, AFH_RemoveAnalysisParameter, DAP_CheckAnalysisFunctionAndParameter, WB_AddAnalysisParameterIntoWPT, WBP_ButtonProc_AddParam.
variable AFH_IsValidAnalysisParamType(string type)
Check if the given type is a valid user parameter type.
References ANALYSIS_FUNCTION_PARAMS_TYPES, IsEmpty.
Referenced by AFH_GetAnalysisParamType, WB_AddAnalysisParameterIntoWPT.
string AFH_GetAnalysisParameter(string name, string params, string expectedType=defaultValue)
Return an user parameter's value as string.
name parameter name params serialized parameters, usually just AnalysisFunction_V3.params expectedType [optional, defaults to nothing] Expected type, one of ANALYSIS_FUNCTION_PARAMS_TYPES, aborts if the type does not match.
References AFH_GetAnalysisParamType.
Referenced by AFH_GetAnalysisParamNumerical, AFH_GetAnalysisParamTextual, AFH_GetAnalysisParamTextWave, AFH_GetAnalysisParamWave, PSQ_CR_FindDependentAnalysisParameter, WBP_UpdateParameterWave.
string AFH_RemoveAnalysisParameter(string name, string params)
Delete the given user parameter name.
name parameter name params serialized parameters, usually just AnalysisFunction_V3.params serialized parameters with name removed
References AFH_IsValidAnalysisParameter, ASSERT.
Referenced by WBP_DeleteAnalysisParameter.