BackgroundFunctions
variable BkgWatcher::BW_BackgroundWatchdog(WMBackgroundStruct *s)
Helper background task for debugging.
References BkgWatcher::BW_PanelUpdate.
variable DQM_FIFOMonitor(WMBackgroundStruct *s)
Fifo monitor for DAQ Multi Device.
References ANALYSIS_FUNC_RET_EARLY_STOP, ANALYSIS_FUNC_RET_REPURP_TIME, AS_HandlePossibleTransition, AS_MID_SWEEP, ASSERT, AssertOnAndClearRTError, ClearRTError, DATA_ACQUISITION_MODE, DQ_STOP_REASON_ESCAPE_KEY, DQ_STOP_REASON_HW_ERROR, DQ_StopOngoingDAQ, DQM_RemoveDevice, DQM_StopDataAcq, ESCAPE_KEY, GetDAQDataWave, GetDQMActiveDeviceList, GetNIFIFOName, GetTPSettingsCalculated, GotTPChannelsOnADCs, HARDWARE_ITC_DAC, HARDWARE_NI_DAC, HW_GetMainDeviceName, IsNaN, LOG_AddEntry, PACKAGE_MIES, ROWS, SCOPE_UpdateGraph, SCOPE_UpdateOscilloscopeData, TS_GetNewestFromThreadQueue, UpdateLeftOverSweepTime.
variable DQM_Timer(WMBackgroundStruct *s)
Background function for tracking ITI.
References DQM_MakeOrUpdateTimerParamWave, ExecuteListOfFunctions, GetActiveDAQDevicesTimerFolder, RelativeNowHighPrec, ROWS, SetValDisplay.
variable DQS_BkrdDataAcq(string device)
Fifo monitor for DAQ Single Device.
References AS_HandlePossibleTransition, AS_MID_SWEEP, DAG_GetNumericalValue, DATA_ACQUISITION_MODE, DQ_StartDAQDeviceTimer, DQS_StartBackgroundFifoMonitor, HARDWARE_ABORT_ON_ERROR, HARDWARE_ITC_DAC, HW_PrepareAcq, HW_StartAcq.
Referenced by DQS_StartDAQSingleDevice, RA_Counter.
variable DQS_FIFOMonitor(WMBackgroundStruct *s)
Fifo monitor for DAQ Single Device.
References ANALYSIS_FUNC_RET_EARLY_STOP, ANALYSIS_FUNC_RET_REPURP_TIME, AS_HandlePossibleTransition, AS_MID_SWEEP, DATA_ACQUISITION_MODE, DQ_STOP_REASON_ESCAPE_KEY, DQ_STOP_REASON_FINISHED, DQ_StopOngoingDAQ, DQS_StopDataAcq, ESCAPE_KEY, HARDWARE_ABORT_ON_ERROR, HW_ITC_MoreData, SCOPE_UpdateGraph, SCOPE_UpdateOscilloscopeData, UpdateLeftOverSweepTime.
variable DQS_Timer(WMBackgroundStruct *s)
Keep track of time during ITI.
References ExecuteListOfFunctions, RelativeNowHighPrec, SetValDisplay.
variable IVS_finishInitAccessQCCheck(WMBackgroundStruct *s)
Complete the Baseline QC check in the background.
References GetIVSCCTemporaryWave, GetTPResults, IVS_DEFAULT_DEVICE, IVS_DEFAULT_HEADSTAGE, IVS_PublishQCState, PGC_SetAndActivateControl, TP_TestPulseHasCycled.
Referenced by IVS_runInitAccessResisQC.
variable IVS_finishGigOhmSealQCCheck(WMBackgroundStruct *s)
finish the Gig Ohm Seal QC in the background
References AssertOnAndClearRTError, ClearRTError, GetTPResults, IVS_DEFAULT_DEVICE, IVS_DEFAULT_HEADSTAGE, IVS_PublishQCState, PGC_SetAndActivateControl, TP_TestPulseHasCycled.
Referenced by IVS_RunGigOhmSealQC.
variable P_ITC_FIFOMonitorProc(WMBackgroundStruct *s)
Monitor the device FIFO and terminates acquisition when sufficient data has been collected.
References HARDWARE_ABORT_ON_ERROR, HARDWARE_ITC_MIN_SAMPINT, HW_ITC_MoreData, HW_StopAcq, P_FindDeviceExecutingPP, P_GetPressureDataWaveRef.
variable TPM_BkrdTPFuncMD(BackgroundStruct *s)
Background TP Multi Device.
References ASSERT, AssertOnAndClearRTError, ClearRTError, ControlWindowToFront, BackgroundStruct::count, DEBUG_TIMER_START, DEBUGPRINT, DEBUGPRINT_ELAPSED, DeviceHasFollower, DQ_STOP_REASON_ESCAPE_KEY, DQ_STOP_REASON_HW_ERROR, DQ_StopOngoingDAQ, ESCAPE_KEY, GetActiveDevicesTPMD, GetDAQDataWave, GetNIFIFOName, GetNumberFromWaveNote, HARDWARE_DAC_DEFAULT_TRIGGER, HARDWARE_ITC_DAC, HARDWARE_NI_DAC, HW_GetMainDeviceName, HW_NI_PrepareAcq, HW_NI_StartAcq, HW_NI_StopAcq, IsFinite, LOG_AddEntry, NOTE_INDEX, PACKAGE_MIES, ROWS, SCOPE_UpdateGraph, SCOPE_UpdateOscilloscopeData, TEST_PULSE_MODE, BackgroundStruct::threadDeadCount, TP_MD_THREAD_DEAD_MAX_RETRIES, TPM_NI_FIFO_THRESHOLD_SIZE, TPM_NI_TASKTIMEOUT, TPM_StopTestPulseMultiDevice, TS_GetNewestFromThreadQueue, TS_GetNewestFromThreadQueueMult, BackgroundStruct::wmbs.
Referenced by BWO_CheckAndClearPipettes, BWO_InitParaPipetteClear.
variable TPS_TestPulseFunc(BackgroundStruct *s)
Background TP Single Device.
References BackgroundStruct::count, DQ_STOP_REASON_ESCAPE_KEY, DQ_StopOngoingDAQ, ESCAPE_KEY, HARDWARE_ABORT_ON_ERROR, HARDWARE_ITC_DAC, HW_ITC_MoreData, HW_ITC_ResetFifo, HW_StartAcq, HW_StopAcq, SCOPE_UpdateGraph, SCOPE_UpdateOscilloscopeData, TEST_PULSE_MODE, BackgroundStruct::wmbs.