CompilationTester
variable CompilationTester::TestCompilation()
Perform compilation testing.
This function should be called by a Function named run without arguments in ProcGlobal, see https://docs.byte-physics.de/igor-unit-testing-framework/advanced.html#automate-test-runs.
References LoadTextFile, NormalizeToEOL, TestCompilationOnFile.
variable CompilationTester::TestCompilationOnFile(string includeFile, variable useDefine=defaultValue, string define=defaultValue)
References IsEmpty.
Referenced by TestCompilation.
variable CompilationTester::EvaluateResult()
string CompilationTester::LoadTextFile(string filePath, variable required=defaultValue)
Load the contents of the given file into data.
filePath absolute path to a text file required [optional, defaults to false] decides if we abort on a failure to load the file (true) or return an empty string
Referenced by TestCompilation.
static string CompilationTester::GetNVARAsString(dfref dfr, string globalVarName, variable initialValue=defaultValue)
Returns the full path to a global variable.
dfr location of the global variable, must exist globalVarName name of the global variable initialValue initial value of the variable. Will only be used if it is created. 0 by default.
Referenced by GetCompilationState.
string CompilationTester::GetCompilationState()
Return the compilation state variable.
-NaN: Not initialized -0x0: Initialization done -0x1: input.txt could be read from disk and has contents -0x2: Compilation was started -0x4: Compilation was successfull -0x8: Compilation was not successfull (Requires Igor Pro 7, build 30097)
References GetNVARAsString.
variable CompilationTester::IsProcGlobalCompiled()
Return true if ProcGlobal is compiled, false if not.
Observed behaviour: ProcGlobal is compiled after all independent modules FunctionInfo returns an empty string for a non existing function, but an error message if ProcGlobal is not compiled
variable CompilationTester::IsEmpty(string *str)
Returns one if str is empty or null, zero otherwise.
str must not be a SVAR
string CompilationTester::NormalizeToEOL(string str, string eol)
Normalize the line endings in the given string to either classic Mac OS/Igor Pro EOLs (\r) or Unix EOLs (\n)
Referenced by TestCompilation.