BkgWatcher
const string BkgWatcher::PANEL
Referenced by BW_PanelUpdate.
const string BkgWatcher::TASK
Referenced by BW_WindowHook.
const string BkgWatcher::CONTROL_PREFIX
Referenced by BW_ButtonProc_QuitTask, BW_ButtonProc_ShowTask, BW_PanelUpdate.
const double BkgWatcher::INVALIDATE_STATE
const double BkgWatcher::XGRID
Referenced by BW_PanelUpdate, BW_StartTask.
const double BkgWatcher::XOFFS
Referenced by BW_PanelUpdate, BW_StartTask.
const double BkgWatcher::YGRID
Referenced by BW_PanelUpdate, BW_StartTask.
const double BkgWatcher::CONTROL_TYPE_VALDISPLAY
Referenced by GetValDisplayAsString.
static variable BkgWatcher::ASSERT(variable var, string errorMsg)
Referenced by GetValDisplayAsString, SetValDisplay.
static variable BkgWatcher::SetValDisplay(string win, string control, variable var=defaultValue, string str=defaultValue, string format=defaultValue)
References ASSERT, GetValDisplayAsString.
Referenced by BW_PanelUpdate.
static string BkgWatcher::GetValDisplayAsString(string win, string control)
References ASSERT, CONTROL_TYPE_VALDISPLAY.
Referenced by SetValDisplay.
static variable BkgWatcher::IsBackgroundTaskRunning(string task)
Referenced by BW_WindowHook.
variable BkgWatcher::BW_StartPanel()
References BW_CreatePanel, BW_StartTask.
variable BkgWatcher::BW_CreatePanel()
References BW_WindowHook.
Referenced by BW_StartPanel.
variable BkgWatcher::BW_StartTask()
References BW_ButtonProc_StopTask, XGRID, XOFFS, YGRID.
Referenced by BW_ButtonProc_StartTask, BW_StartPanel.
variable BkgWatcher::BW_StopTask()
References BW_ButtonProc_StartTask, BW_PanelUpdate.
Referenced by BW_ButtonProc_StopTask, BW_WindowHook.
variable BkgWatcher::BW_PanelUpdate()
References CONTROL_PREFIX, PANEL, SetValDisplay, XGRID, XOFFS, YGRID.
Referenced by BW_BackgroundWatchdog, BW_ButtonProc_QuitTask, BW_StopTask, BW_WindowHook.
variable BkgWatcher::BW_BackgroundWatchdog(WMBackgroundStruct *s)
Helper background task for debugging.
References BW_PanelUpdate.
variable BkgWatcher::BW_ButtonProc_ShowTask(WMButtonAction *ba)
References CONTROL_PREFIX.
variable BkgWatcher::BW_ButtonProc_QuitTask(WMButtonAction *ba)
References BW_PanelUpdate, CONTROL_PREFIX.
variable BkgWatcher::BW_WindowHook(WMWinHookStruct *s)
References BW_PanelUpdate, BW_StopTask, IsBackgroundTaskRunning, TASK.
Referenced by BW_CreatePanel.
variable BkgWatcher::BW_ButtonProc_StartTask(WMButtonAction *ba)
References BW_StartTask.
Referenced by BW_StopTask.
variable BkgWatcher::BW_ButtonProc_StopTask(WMButtonAction *ba)
References BW_StopTask.
Referenced by BW_StartTask.