#!/bin/bash

set -e

IFS=' '
while read local_ref local_sha remote_ref remote_sha
do
  if [[ "$remote_sha" != "0000000000000000000000000000000000000000" ]]
  then
    # remote branch already exists, nothing to check
    exit 0
  fi

  namespace=$(echo $local_ref | cut -d "/" -f 1-2)

  if [[ "$namespace" == "refs/tags" ]]
  then
    # do nothing for tags
    exit 0
  fi

  branch=$(echo $local_ref | cut -d "/" -f 3-)
  prefix=$(echo $branch | cut -d "/" -f 1)
  pr=$(echo $branch | cut -d "/" -f 2| cut -d "-" -f 1)
  suffix=$(echo $branch | cut -d "/" -f 2| cut -d "-" -f 2-)

  # echo $branch
  # echo $prefix
  # echo $pr
  # echo $suffix

  if [[ "$prefix" != "feature" && "$prefix" != "bugfix" ]]
  then
    echo "The naming of the branch \"$branch\" does not match the required naming scheme as the prefix \"$prefix\" is wrong." > /dev/stderr
    exit 1
  fi

  top_level=$(git rev-parse --show-toplevel)

  nextFreePR=$($top_level/tools/nextFreePRNumber.sh)
  if [[ "$pr" != "$nextFreePR" ]]
  then
    if [[ "$pr" == "XXXX" ]]
    then
      git branch -m $prefix/$nextFreePR-$suffix
      echo "The branch was renamed, please try again." > /dev/stderr
      exit 1
    fi

    echo "The naming of the branch \"$branch\" does not match the required naming scheme as the PR number \"$pr\" is wrong." > /dev/stderr
    exit 1
  fi

  # echo "Good: The remote branch \"$branch\" follows the desired naming scheme."
done

exit 0
